### ISSUE TITLE
showBottom argument in plot.section

### ISSUE THREAD

**Issue by porterdf** [dankelley/oce#1001]
Hi!

I am having a problem getting "showBottom" feature of plot.section to work with my CTD data (emailed to Dan and Clark offline).  It is not reproducible using oce-data, sorry.    Any advice?
```
library(oce)
toread <- c("042.cnv","041.cnv","040.cnv")
ctds <- vector("list", length(toread))
for ( i in 1:length(toread)) ctds[i] <- ctdDecimate(ctdTrim(read.ctd.sbe(file.path(toread[i]))),p=1)
sec1 <- as.section(ctds)
summary(sec1)
png("test.png",type = "cairo")
plot(sec1,
     which=c("temperature","salinity2","oxygen2","map"),
     xtype='distance',ztype='image', 
     showStations=TRUE,showBottom=TRUE)
dev.off()
```
![test](https://cloud.githubusercontent.com/assets/7237617/16428631/b8323cf0-3d40-11e6-9fb9-699944d235d5.png)

**Comment by porterdf** [comment]
Addendum:

I get the following warnings

> 
> Warning messages:
> 1: In sectionGrid(x, debug = debug - 1) :
>   Data flags are omitted from the gridded section object. Use handleFlags() first to remove bad data.
> 2: In lon[i] <- thisStation[["longitude"]] :
>   number of items to replace is not a multiple of replacement length
> ...
>

**Comment by dankelley** [comment]
1. the "Data flags" warning will always happen. (Q to @richardsc do you think we should drop that warning? I personally find it a bit annoying, and I think it's up to users to take care of this ... I vote to just state this in the docs and remove the warning).

2. The other warning is something I'll fix. It arises because your .cnv files have longitude and latitude as columns ... the code was written on the assumption that these would be single-valued, not vector-valued. I'll tweak the code to take just the first element, in creating the section. Note to @richardsc this is going to be extremely isolated, so I'm going to do it in the branch to be released on Friday.

3. To @porterdf I made some issue code for this at [https://github.com/dankelley/oce-issues/blob/master/1001/1001a.R](https://github.com/dankelley/oce-issues/blob/master/1001/1001a.R) and you might want to look. Note that I check whether it is interactive before making the png, and also that this bug is unlikely to relate to multi-panels, so I am using just 1 panel.

**Comment by dankelley** [comment]
Re point #4, I see that's really nothing to do with `oce` so I'm going to ignore it for now. To see that it's not an `oce` issue, note that
```R
library(oce)
data("ctd")
a <- vector("list", 1)
a[1] <- ctd
```
yields
```R
Error in `[<-`(`*tmp*`, 1, value = <S4 object of class "ctd">) : 
  (converted from warning) implicit list embedding of S4 objects is deprecated
```

**Comment by dankelley** [comment]
@porterdf -- are you sure this is a bug? I see that the CTD objects do not have a water depth, viz
```R
> ctds[[1]][['waterDepth']]
[1] NA
```
and when I look in the CNV, I also see no water depth in the header. (Did I miss it? Please have a look with an editor.)

Note that water depth is not just the maximum depth recorded. At one time, we did that in `oce`, but it actually makes no sense because a person very well might just lower to 100m for some purpose, in 4000m of water, and drawing a bottom at 100m for that profile would indicate a scary (fictional) seamount.

Please inform me on whether you think there is a bottom depth indication in the data. If so, I would like to make `oce` read it, before the release planned for early Friday morning, this week. Thanks!

I made a test program [1001b.R](https://github.com/dankelley/oce-issues/blob/master/1001/1001a.R) in the test suite, which shows how you can add bottom depth to the objects, if you know them by some other method (maybe a topography lookup). The results from that look fine to me.

**Comment by richardsc** [comment]
I just updated the oce-issues with another script [1001c.R](https://github.com/dankelley/oce-issues/blob/master/1001/1001c.R) which modifies Dan's example to show how you could get the depth from the NOAA database using the [`marmap`](https://cran.r-project.org/web/packages/marmap/index.html) package. The relevant part is:
```r
lon <- unlist(lapply(ctds, function(x) mean(head(x[['longitude']], 20), na.rm=TRUE)))
lat <- unlist(lapply(ctds, function(x) mean(head(x[['latitude']], 20), na.rm=TRUE)))
bathy <- getNOAA.bathy(min(lon)-1, max(lon)+1, min(lat)-1, max(lat)+1, 
                       resolution = 1, keep=TRUE)
depth <- get.depth(bathy, lon, lat, locator=FALSE)

for ( i in 1:length(toread)) {
  ctds[[i]][["waterDepth"]] <- abs(depth[i,3])
}
```
Note the use of `lapply()` to extract the profile locations from the ctd objects. There are a lot of NAs in the data, which is why I do that trick of taking the `mean(..., na.rm=TRUE)` of the first 20 values.

**Comment by dankelley** [comment]
@porterdf -- If this seems okay, please close the issue; otherwise, please post a comment. I'm rushing things a bit because we are near a release and I don't like to release when there are a lot of active  but simply-fixed issues in the list. Thanks!

**Comment by porterdf** [comment]
@dankelley This does seem okay.  And thank so much for your suggestions.  I totally agree that using maximum depth/pressure does not make sense for plotting bottom depth.  I had incorrectly assumed that the "Depth" returned from `summary(section)` was what was supposed to be plotted by the "showBottom" flag.  All good.

I was also getting some errors (yet to be reported, sorry!) with the grid smoothing function due to mismatching lengths of latitude and longitude vectors, so you're other fix for reading in .cnv files with lat and lon as columns should fix that, I'm guessing.
