### ISSUE TITLE
Keep the warning on removing scan during CTD decimation?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1003]
Clark, whilst looking at #1002 , I found the following. I feel this warning should be kept because we seriously altering the object. Agreed, Clark?
```
git grep "scan" | grep warning
ctd.R:        warning('Removing scan field from decimated object')
```
PS. I'm not entirely sure we should remove `scan`, actually. I've seen BIO files that had scan jumping, and it came from in averaging, I think ... but I don't want to change this behaviour a couple of days before a release.

**Comment by richardsc** [comment]
I agree the warning gets annoying. I suppose this kind of thing is what the processing log is really good for, so perhaps we could move the message there and not bother dumping to the console.

We talked about whether or not to remove scan before, and I'm not married to one way or the other. I think I do prefer to remove it though, since it becomes meaningless, and could actually confuse someone who thought that each "decimated" scan represented a single measurement. Also, how would someone interpret it if the bin average for a bunch of scans produces a fractional number?

A jumping `scan` *could* come from **removing** data (package heave, spikes, etc) rather than averaging, in which case I think it is still a valuable field because it conveys the time series information about the measurements.

**Comment by dankelley** [comment]
1. **DECISION.** keep present behaviour with discarding `scan`. This can always be changed later.

2. I updated `develop` as below. I tested on some data, and it looks okay. It might be nice for @richardsc to look at the diff, but I'm closing this on the assumption that things are ok.

commit b0f4aafe610a02faee4b72ab890671f9270c3ac8
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Wed Jun 29 07:53:01 2016 -0300

    ctdDecimate() has fewer warnings (puts in processingLog)
