### ISSUE TITLE
How to change axis font size in mapPlot()?

### ISSUE THREAD

**Issue by AnneMTreasure** [dankelley/oce#1019]
Hi there,

I have been trying to change the axis tick label size in `mapPlot()`. I've tried both `cex.axis()` and `cex()`, but cannot get this to work. This is related to issue [#315](https://github.com/dankelley/oce/issues/315)

I'm using `oce` version 0.9.19

Thanks so much!
Cheers,
Anne

**Comment by dankelley** [comment]
I added `cex.axis` as an argument to `mapPlot` and `mapAxis` in the `develop` branch. So, you might want to try a test with that, as below
```R
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld, longitudelim=c(-130,-55), latitudelim=c(35,60),
         projection="+proj=lcc +lat_0=30 +lat_1=60 +lon_0=-100", col='gray',cex.axis=1.5)
```
but note that this is probably not the best way to do this, because I'm not sure the label will be positioned well if the size is altered a lot from the default size. There may be lots of interlocking parameters at play, relating to this positioning, so please open a new issue if so. (It also helps to supply test code, ideally related to built-in datasets ... I've done that above.)

Thanks for pointing this out!

PS. also, consider adjusting the `pointsize` argument in your plot-device call, which I've always found to be a good method. I guess these things are personal habit, but I almost never consider adjusting `cex.axis` in my own work.

**Comment by dankelley** [comment]
I have also added a new arg called `mgp` (in `develop` branch, commit bbed49261a7da317c2584a9814c5d9c0e3769617). This can be used to adjust the label positioning. I also added a test code to the [github test suite](https://github.com/dankelley/oce-issues/blob/master/1019/1019a.R); please have a look at that, if you do not like the axis label position.

**Comment by AnneMTreasure** [comment]
Hi there,

Thanks so much for this. The `cex.axis` argument now works in my `mapPlot` call:

`mapPlot(coastlineWorld, projection="+proj=stere +lat_0=-90", longitudelim=c(-180,180), latitudelim=c(-90,-40), col="lightgray", cex.axis = 1.5)`

(sorry, I will include test code using in-built datasets next time!)

but I do get positioning issues. Using the argument `mgp` does help, but I think I will take your advice and rather adjust the `pointsize` argument in the plot-device call, which will make my code a bit tidier and quicker (not having to adjust the size of the text elements individually).

It is useful though to be able to change the `cex.axis` on its own if need be for presentation purposes!

Thanks so much again,
Anne

**Comment by dankelley** [comment]
Thanks. Closing.
