### ISSUE TITLE
cm objects: what is basic storage requirement?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1026]
I realized that it is silly to store the components `u` and `v`, in addition to the direction. Since I just made a change to the name of the direction, I thought I could take the opportunity to look more carefully at our sample interocean/S4 file.

To find out what's in the file (since the lines are long and hard to read), I switched the tab characters to commas, and loaded in a spreadsheet; at the end of this comment is a snapshot.

1. There *is* something called `Hdg` that clearly relates to `Hx` and `Hy`, since `360 - atan2(146,-26)*180/pi` is a check for the first data line in the file. I guess this is the heading of the instrument. Maybe we should store that? Do we also store `Hx` and `Hy`, whatever they are (i.e.what would their units be)?? (Advice, @richardsc ?)
2. `Cond` has an odd unit of `mS` with no distance stated.
3. I've no idea what `dec S` is. Maybe declination to the south? Anyway, it's all zeros here.

Now, our convention is to try to read everything, but that does **not** mean that this stuff should all go into basic `cm` data. Instead, I think `new("cm")` should create a data slot with just the minimal entries. To my mind, those would be `time`, `u`, and `v`. I think the other things should get inserted by `read.cm`, but not made part of the basic object.  (Clark, FYI, when you call `new("cm")` it calls the `setMethod(f="initialize",` part of the code.)

My argument is that we are hoping to store data from other current meters, not just interocean/s4, and therefore our basic object should be patterned on the minimal intersection of all possibilities. Put another way, if I were creating fake data, I'd create `time`, `u`, and `v`, but I don't see why I would also create `direction` since that is contained in `u` and `v`.

<img width="1138" alt="screen shot 2016-07-23 at 12 13 16 pm" src="https://cloud.githubusercontent.com/assets/99469/17078654/e0e1b332-50ce-11e6-90c4-4a598b8911bd.png">

**Comment by dankelley** [comment]
I made the basic storage more limited, and put all additions into calling code, so I'm closing this.

**Comment by richardsc** [comment]
Sorry, I forgot that there was a request for feedback on this -- it would be nice if Github had an "answer" functionality so that I would know that there was something waiting for me to comment, rather than just being tagged, since I get all the alerts even if I'm not tagged.

Good catch re: `direction` and `heading` in the S4 data. Of course the S4 determines the current *direction* by measuring the currents in an x/y frame and then using the instrument heading to get u/v. So yes, I think in such cases we should store `heading` and `direction`, where the former is documented as the instrument orientation and the latter as the direction of the water flow. Of course, Aanderraa instruments don't really distinguish between these (I think) because the entire instrument points in the direction of the flow.

As for `Hx` and `Hy`, could they be measurements of horizontal magnetic field components -- i.e. the pieces required to estimate the heading angle?

**Comment by dankelley** [comment]
Oh, no worries re feedback.  I agree, GH needs some sort of time-dated questions to collaborators, a bit like how email could benefit from a "take back" feature (no need for the person to read a "wanna have lunch today" email after they return from a cruise).

I bet you're right on `Hx` and `Hy`. Good call.

I'm trying to clear up a bunch of things today because I won't have any time during the week.  (It all stems from the `cm` updates, which I want for something I'm doing lately.)
