### ISSUE TITLE
vignette could use more details on the `[[` accessor

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1033]
As the title suggests -- this is a pretty fundamental way of getting stuff out of oce objects for detailed data analysis, and I think it should be one of the first topics in the vignette.

**Comment by dankelley** [comment]
Excellent idea. A first step would be to take the paragraph at the end of section 4.1 and move it somewhere else, with a title that captures the eye, e.g. *How to access data within oce objects* or something.  NOTE: R uses is *extract*, not *access*, and so that's what we have in oce also (see e.g. `help("[[,ctd-method","oce")`) , but I prefer *access* because the dictionary entry for "extract" talks about removal (like teeth). 

I really like the idea of improving the vignette because I think quite often issue reporters could benefit from looking there. We need to be careful about filesize, though, because with the Rmarkdown/html scheme, figures are quite large. That's why some of the figure sizes are quite small in the vignette now ... CRAN doesn't like big package sources.

**Comment by richardsc** [comment]
I added a short section via PR #1048 . Hopefully that's enough. Feel free to edit if you think more clarity is needed.

**Comment by dankelley** [comment]
I altered some text, moving the section up higher in the doc and adding a 3-item list for why `[[` is good. I'd suggest closing this issue.

**Comment by richardsc** [comment]
Great! Closing.
