### ISSUE TITLE
ctdAddColumn vs oceSetData

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1036]
The discussion in #1034 highlighted some of the similarities and differences of `ctdAddColumn()` and `oceSetData()`, specifically:

> 1. 'column' is a bad name since it suggests a matrix (or, equivalently) a table
> 2. `ctdAddColumn` _does_ do something that `oceSetData` doesn't do: it checks that the added item is of the same length as the other items. 

Given the previous discussion about "column" names (in the context of the now deprecated `addColumn()`), should we think about deprecating `ctdAddColumn()`? As for number 2, we can easily add the functionality to check item length for ctd objects, and fail if it's not the same.

As I suspect `ctdAddColumn()` is probably in more common usage, perhaps we could alias it to `oceSetData()`, so from a user perspective it should function as expected, but we eliminate an extra function (and documentation) to maintain?

**Comment by dankelley** [comment]
FYI, in `develop` commit 27b132535d769db98344a61d220b2bd3ecfca2f7 I've marked `addColumn` as "deprecated".

**Comment by dankelley** [comment]
Re aliasing `ctdAddColumn` to `oceSetData`, that's not directly possible because the args are different.  (Actually, I see something in `ctdAddColumn`'s args that should be in `oceSetData`, namely the ability to skip the addition to the processingLog.)  I see that we use `ctdAddColumn` 19 times oce ... I may migrate those to `oceSetData` to see if it "feels" right, and then I can some advice in the docs to consider using `oceSetData` instead. Since `ctdAddColumn` is an old function, and since it's not hurting anything, I don't really want to deprecate it.

**Comment by dankelley** [comment]
Looking at the code, I see that `ctdAddColumn` does three things that `oceSetData` does not do:

1. provides the ability to add something without altering the `processingLog` (I just added that to `oceSetData`, in `develop` commit 2ea4d066595a809320567b6cbce4dfb441d64a57)
2. an arg called `unit` (which is called `units` in `oceSetData`) -- easy to translate
3. provision of a "label" for the data item -- easy to translate ... However, I do not actually like this `label` entry, which is an historical artifact that only works for CTD, and that offers little of benefit to the user. I've opened issue #1047 for that.

**Comment by dankelley** [comment]
This issue has been unaddressed for a long time, and I plan to take a look this weekend. We are not using `ctdAddColumn` very much in the code, so removing it from internal use will not be too hard.
```
$ git grep ctdAddColumn | grep -v ":[ ]*#"
ctd.R:            res <- ctdAddColumn(res, column=d[[field]], name=field, label=field, log=FALSE)
ctd.R:ctdAddColumn <- function (x, column, name, label, unit=NULL, log=TRUE, originalName="",
ctd.R:    oceDebug(debug, "ctdAddColumn(x, column, name=\"", name, "\", label=\"", label, "\", debug) {\n", sep="", unindent=1)
ctd.R:        res@processingLog <- processingLogAppend(res@processingLog, paste("ctdAddColumn(..., name=\"", name, "\", ...)", sep=""))
ctd.R:    oceDebug(debug, "} # ctdAddColumn()\n", sep="", unindent=1)
ctd.sbe.R:            res <- ctdAddColumn(res, S, name="salinity", label="Salinity",
ctd.sbe.R:            res <- ctdAddColumn(res, res@data$depth * g * rho0 / 1e4, name="pressure", label="Pressure",
misc.R:        res <- ctdAddColumn(x, data, name) # FIXME: supply units
rsk.R:        res <- ctdAddColumn(res, column=S, name="salinity", label="Salinity",
section.R:                ctds[[i]] <- ctdAddColumn(ctds[[i]], as.vector(tmp[[N[Ni]]])[look], N[Ni],
```

**Comment by dankelley** [comment]
1. As of `develop` commit cca2300c21e60eda30f26871354ff9f9f2d9160e, `ctdAddColumn` is no longer used internally in oce. I converted all instances to `oceSetData`, and did the normal build tests plus our private-suite test.

2. **IMPORTANTLY** I renamed the `oceSetData` arg `units` to `unit`, because that makes more sense. We are giving the unit for just one item, after all. Luckily, old calls that use `units` as the argument will create errors, so the user can see quickly what to do.

I am closing this, on the assumption that CR will feel free to reopen it, if need be.
