### ISSUE TITLE
imagep() needs an 'add' argument

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1046]
This could be used to draw land, missing-value, etc. codes in `plot,amsr-method`. It could be quite helpful for other things, also.

**Comment by richardsc** [comment]
I feel like we've discussed this before, and I'm interested to see what you propose. The issue, as I recall, is that `image()` doesn't have an `add=TRUE` option, so any solution would involve calls to `par(new=TRUE)` and using the current axis properties to "overplot" the original exactly (but without drawing axes a second time).

I have a few times had scenarios where I needed multiple calls to `imagep()` for the same plot, and it basically involved all of the above: carefully setting axis limits and colorbars for each plot, and then sticking a `par(new=TRUE)` in the middle. Below is an example (from my 2015 JPO paper). Notice the white break in between the two years of mooring data -- this was where the mooring was turned around, and the vertical resolution changed because of different sampling. I thought it better to plot each separately, rather than try and grid to a common matrix to try and do it with one `imagep()` call.
![01-mld](https://cloud.githubusercontent.com/assets/233584/17459636/abfdff7c-5c0e-11e6-8474-5eaeeecd0b32.png)

**Comment by dankelley** [comment]
Actually, `image` has an `add` argument. That's what I used earlier today in `plot,amsr-method`, for adding the masking colours (i.e. for ice, rain, and whatnot); see https://github.com/dankelley/oce/blob/develop/R/amsr.R#L367

**Comment by dankelley** [comment]
I have this working (to some extend) in `develop` branch, commit b17afab162302285c1b481d489096f99cfb7ca1d 

Note some limitations, e.g. of course setting `xlim` has no effect, and there are other limitations. One I should probably fix up is that `colormap` is ignored ... you have to give `breaks` and `col`. My choice was to start with the basics. Adding `colormap` should (I think) be a new issue, given the title of the present issue.

There is a test code in the [oce issues repo](https://github.com/dankelley/oce-issues/blob/master/1046/1046a.R), which is reproduced below, with its output.
```R
library(oce)
if (!interactive()) png("1046a.png")
imagep(volcano)
x <- seq(0, 20, 0.5)
y <- seq(0, 20, 0.5)
z <- outer(x, y, function(x,y) cos(2*pi*x/20) * sin(2*pi*y/20))
imagep(40+x, 20+y, z, breaks=seq(-1,1,0.01), col=oceColorsJet, add=TRUE)
abline(v=40) # check that it's in right place
abline(h=20)
if (!interactive()) dev.off()
```

![1046a](https://cloud.githubusercontent.com/assets/99469/17462550/617e8dbc-5c87-11e6-8ef0-e136c89412a0.png)

**Comment by dankelley** [comment]
Update: I just made it accept `colormap`, in `develop` branch commit dcbffeaf5b8cad8f74c87c824a4d49b68ddc7c3c
