### ISSUE TITLE
imagep() should handle zlim="symmetric"

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1060]
Very often, I find myself doing
```R
zlim <- c(-1, 1) * max(abs(z), na.rm=TRUE)
imagep(x, y, z, zlim=zlim, col=oceColorsTwo, ...)
```
for things like velocity, to place zero at the centre of the colour scale.  It would be nice if `zlim` could take a character argument to accomplish this. At the moment, I'm thinking of calling the value `"symmetric"` ... but if others reading this have better ideas, please post below.

**Comment by richardsc** [comment]
I have a little function called 'symLim()' that does something like this in my "personal" package:

https://github.com/richardsc/crMisc/blob/master/R/misc.R#L67

**Comment by dankelley** [comment]
Ah, so I think we have agreement that "symmetric" is a word that will mean something to people.

**Comment by richardsc** [comment]
Yes, I think so. The only issue with the option of a character string is that then there is no way to specify the magnitude of the limit. That was why I implemented a function that could take a single input and return a symmetric vector of length 2, eg
```r
imagep(x, y, z, zlim=symLim(2))
```
To get limits of plus/minus 2.

**Comment by dankelley** [comment]
In the above, why not use
```R
imagep(x, y, z, zlim=c(-2,2)
```
to get limits of plus/minus 2?

**Comment by richardsc** [comment]
Good point. I actually haven't used that function in a while (was mostly used during my thesis), but I think actually the way I would typically use it was:
```r
imagep(x, y, z, zlim=symLim(z))
```
which I guess is essentially the same as giving a character `"symmetric"`, since you still aren't telling it *what* symmetric limits to use.

Just off the top of my head, what if `zlim` is a single value, then the interpretation is to make it symmetric? e.g.
```r
imagep(x, y, z, zlim=2)
```
would recognize the `length(zlim) == 1` and make the limits plus/minus 2.

**Comment by dankelley** [comment]
I implemented `zlib="symmetric"` in the `develop` branch, so closing this.
