### ISSUE TITLE
Should as.ctd populate empty units for "other" fields?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1091]
As noted in #1080, when `as.ctd()` is used with the `other=` argument, there are no corresponding entries for the `units` fields associated with them. Does it make sense to just create an empty field, that can later be populated?

Another approach would be to have a `units` argument in `as.ctd()`. This could get complicated (e.g. what if the call only specifies units for one of the data fields ... do the other ones just get set as default -- if recognized -- or empty?).

Another approach could be to create a function along the lines of `oceSetData()`, but for adding/changing units.

Maybe this is all too much bother, considering that the solution given in #1080 is not overly complicated.

**Comment by dankelley** [comment]
I see that `as.ctd()` has a `units` argument, so that will work (or can be made to work, if it does not work). But the problem with the `other` argument is that it cannot allow for the display name to differ from the variable name (e.g. we might want to call the variable `temperature` but have the axis say `Temperature`).

For such reasons, perhaps the best solution is to discourage using the `other` argument of `as.ctd()`, and instead encourage the user to employ `oceSetData()`, a function that permits setting the data, the variable name, the display name, and the unit.

**Comment by richardsc** [comment]
Ah, yes, you're right -- `units` is right there in the (very large) argument list for `as.ctd()` (right after `other=` ... :stuck_out_tongue: )

That's a good suggestion for using `oceSetData()`. I wonder if it would make sense for the `other=` arg to accept a list that contains all the stuff that would go into an `oceSetData` call, and then internally it could just use that. I have used the `other=` argument quite a bit in the past, so I definitely wouldn't want to remove it. Plus I like being able to create the full `ctd` object with one function call.

Just spitballing here, really ...

**Comment by dankelley** [comment]
Oh, I'm not suggesting removing `other`. It's just that maybe in the `as.oce` docs should say that another approach is to use `oceSetDat`.  I think 2 things should be done (and I'll do them unless you state that you disagree)
* [ ] the `as.ctd` docs should mention `oceSetData`
* [ ] `as.ctd` should see if `units` is e.g. `other=list(turbidity=list(data=..., name=..., unit=), ...)`. Actually, that looks complicated, and if were writing a function call, I'd be doing this with one line per the entry in `other`, so then I don't see a clear argument for not using `oceSetData`.  Further thoughts on this part, Clark?

**Comment by richardsc** [comment]
> @dankelley wrote: Actually, that looks complicated, and if were writing a function call, I'd be doing this with one line per the entry in other, so then I don't see a clear argument for not using oceSetData

Yes, I suppose you're right. I agree, it's probably good enough to give an example of how to do it in the docs.

**Comment by dankelley** [comment]
I'm scanning issues to see if some can be addressed quickly. This one seems easy (just add something about `oceSetData` in the `as.ctd()` documentation) but I am stuck on something CR wrote, namely "(very large) argument list". Sheesh, that list is kind of crazy-long, in my opinion.  I put the arg list at the bottom of this comment. As a user, my eyes can barely grasp anything from that list. 

The arg list is long because so much stuff *can* go in a `ctd` object. But does that really mean that `as.ctd()` should list all those things? I am starting to think the answer is a definite "no". This is because these details, e.g. serial numbers, are normally inferred from SBE (and RSK, etc) files directly, with the `read.ctd.*()` functions. I think `as.ctd()` is going to be used mainly by people who are presented with e.g. a CSV file (with no metadata) or a webpage of data (again, with no metadata). (Note that the `read` functions insert material into the `metadata` and `data` slots directly; they do not use `as.ctd()` for that.) I think people using `as.ctd()` would be better off with a simple arg list.

So, below are two checklists. In the first, I'll put my votes for what should be kept. There seems to be no way to put two checks in a given item in GH comments, so I made a second list that CR might want to look at (if he has time).

Note that I am thinking of removing even `oxygen`, because I don't think all CTDs will have that. I am thinking that the `as.ctd()` docs should show how to add oxygen and some other column, with two separate `oceSetData` calls. That way, people will see how to do this with data. A similar thing can be done with common metadata.

My suggestion, in summary, is to shorten the arg list for `as.ctd()` quite dramatically. I'd want to let this rest for a few days before doing it, of course, because it could break existing user code. (I have no idea how many users are actually using `as.ctd()`, though ... surely it can't be as many as are using `read.ctd.sbe()` ...??)

Checklist for args to keep (DK)
* [x] `salinity`
* [x] `temperature`
* [x] `pressure`
* [x] `conductivity`
* [ ] `SA`
* [ ] `CT`
* [ ] `oxygen`
* [ ] `nitrate`
* [ ] `nitrite`
* [ ] `phosphate`
* [ ] `silicate`
* [ ] `scan`
* [ ] `time`
* [ ] `other`
* [ ] `units`
* [ ] `flags`
* [ ] `pressureType`
* [ ] `missingValue`
* [ ] `quality`
* [ ] `filename`
* [ ] `type`
* [ ] `model`
* [ ] `serialNumber`
* [ ] `ship`
* [ ] `scientist`
* [ ] `institute`
* [ ] `address`
* [ ] `cruise`
* [x] `station`
* [x] `date`
* [ ] `startTime`
* [ ] `recovery`
* [x] `longitude`
* [x] `latitude`
* [ ] `deploymentType`
* [ ] `pressureAtmospheric`
* [ ] `waterDepth`
* [ ] `sampleInterval`
* [ ] `src`
* [x] `debug`

Checklist for args to keep (CR)
* [ ] `salinity`
* [ ] `temperature`
* [ ] `pressure`
* [ ] `conductivity`
* [ ] `SA`
* [ ] `CT`
* [ ] `oxygen`
* [ ] `nitrate`
* [ ] `nitrite`
* [ ] `phosphate`
* [ ] `silicate`
* [ ] `scan`
* [ ] `time`
* [ ] `other`
* [ ] `units`
* [ ] `flags`
* [ ] `pressureType`
* [ ] `missingValue`
* [ ] `quality`
* [ ] `filename`
* [ ] `type`
* [ ] `model`
* [ ] `serialNumber`
* [ ] `ship`
* [ ] `scientist`
* [ ] `institute`
* [ ] `address`
* [ ] `cruise`
* [ ] `station`
* [ ] `date`
* [ ] `startTime`
* [ ] `recovery`
* [ ] `longitude`
* [ ] `latitude`
* [ ] `deploymentType`
* [ ] `pressureAtmospheric`
* [ ] `waterDepth`
* [ ] `sampleInterval`
* [ ] `src`
* [ ] `debug`

**Comment by dankelley** [comment]
The vignette now says as below. Maybe this can be closed? (It has lingered a long time, sorry for ignoring it.)

<img width="713" alt="screen shot 2016-12-31 at 2 28 08 pm" src="https://cloud.githubusercontent.com/assets/99469/21578819/7ee2efa0-cf65-11e6-894a-4fc3ff5afb99.png">

**Comment by richardsc** [comment]
Yes, this looks good to me! Thanks!

**Comment by richardsc** [comment]
Whoops, forgot to close ...
