### ISSUE TITLE
plot average adp profile doesn't obey `ytype` arg

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1128]
From @jrajewicz. Example -- note that I'm turning the `adp` dataset (which was originally upward looking) into a downward looking deployment by altering the `orientation` metadata:
```r
library(oce)
data(adp)
adp[['orientation']] <- 'downward'
par(mfrow=c(1, 2))
plot(adp, which=24)
plot(adp, which=24, ytype='profile')
```
Note that both plots look the same, where the second one (the "profile" plot) should have the yaxis reversed as is done for e.g. `plot(adp, which=1)`.
![image](https://cloud.githubusercontent.com/assets/233584/20608935/d884b046-b25c-11e6-847d-d19b3c8a5f70.png)

**Comment by richardsc** [comment]
I'll add here, as pointed out in an email, the temporary solution is to forego the convenience of the adp plot method and just calculate and plot the average manually, e.g.
```r
plot(apply(adp[['v']][,,1], 2, mean, na.rm=TRUE), adp[['distance']], type='l', ylim=rev(range(d[['distance']])))
```

**Comment by dankelley** [comment]
Clark: Just checking, were you planning on coding this, or should I take a look? I don't see this as being overly pressing, since your "manual plot" method is perfectly fine. (The only real advantage of doing things in `oce` is that the axis labels come out a bit better, with no effort.)

**Comment by richardsc** [comment]
I assigned myself with the intention of doing it, but won't have time for at least a couple days. Feel free to take a stab if you're looking for a 10 minute distraction :smile:

**Comment by dankelley** [comment]
Maybe I'll leave it to you. I looked at the code for 10min and tried something but it didn't work. It's one of those situations where several variables can be multivalued so all the intersections have to be right. Probably more than 10min. I'll have a lot of grading to do on the weekend so I'd prefer to leave this in your hands. I'll show that I'm cool by inserting an emoji but I have no idea what it means... 💯

**Comment by richardsc** [comment]
Assigning this to @dankelley -- I'm not going to get to it over the holidays (no rush, though).

**Comment by dankelley** [comment]
I started work on this. There is now an issue test for it (https://github.com/dankelley/oce-issues/blob/master/11xx/1128/1128a.R) and this includes `expect_equal` code that makes it easier to verify correctness than looking at images for purple "EXPECT" labels.

PS. Note that I am suggesting a new subdir scheme for issue code. The idea is to make it easier to do a listing. At some point, I think it would make sense to put old issue reports into similar schemes. That would break a few cross-references in the present repo issue listings, but I still think it would be nice to have subdirs with at most 100 files, not possibly thousands of files...

**Comment by dankelley** [comment]
I may have this working in `develop` commit fd5a69a89d8cdc3a9acacdb283998bfd55a541be but I don't think I really understand what I wrote in the documentation originally and could use Clark's help on (a) does the test file actually test what we want? and (b) should the documentation be altered? I don't think this should get closed until we agree on these things. No rush, really; the original intention was solved by a line of code, outside oce.

The documentation presently describes `ytype` with the text "character string controlling the type of the y axis for images (ignored for time series). If "distance", then the y axis will be distance from the sensor head, with smaller distances nearer the bottom of the graph. If "profile", then this will still be true for upward-looking instruments, but the y axis will be flipped for downward-looking instruments**, so that in either case, the top of the graph will represent the sample nearest the sea surface.**" 

I think the bold-faced part is at odds with what the code was intended to do, and it's certainly at odds with what the code does now. Please, Clark, look at the new test code in https://github.com/dankelley/oce-issues/blob/master/11xx/1128/1128a.R and at the graph it makes, and let me know if you agree that the bold-faced part of the text should be deleted. Indeed, since this stuff has not been tested for this condition (as far as I know), we can use this as an opportunity to decide *exactly* what the code should do. (Please pay attention to the axis labels as well as the graph.)

This is complicated to code because there are interacting elements. The orientation has two choices. The `ytype` value has two choices. The user could have given `ylim` or not. So that's 8 possibilities, right off the start.

**Comment by richardsc** [comment]
Hm. This is complicated, but I think actually the bolded statement is correct. The definition of `ytype='profile'` is that the surface is near the top, whether it's an up or downward looking instrument.

Currently, that doesn't seem to happen for `which=24` -- however you can verify the expected behaviour by making "regular" adp plots, e.g. `which=1`. Note how the last panel in the second plot is "flipped" wrt to all the others -- this is the expected behavior for a **downward** looking instrument with `ytype='profile'`:
![image](https://cloud.githubusercontent.com/assets/233584/21553639/c11fc294-cddf-11e6-87e1-d1b5c8edabd8.png)
![image](https://cloud.githubusercontent.com/assets/233584/21553653/d1131a7a-cddf-11e6-9b33-ce9048799468.png)

**Comment by dankelley** [comment]
Below is what the test code gives now for the `develop` branch. So, is that right?

![1128a](https://cloud.githubusercontent.com/assets/99469/21553737/78898f14-cde0-11e6-99de-6908142988d5.png)

**Comment by richardsc** [comment]
Yes, that looks like how I'd expect!

**Comment by dankelley** [comment]
Mind if I close this?

**Comment by richardsc** [comment]
Beat you to it!
