### ISSUE TITLE
Unrecognized ODF units "mmHo"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1150]
This is from the same file in Issue #1149:
```r
Warning messages:
1: In ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL,  :
  unable to interpret ODFunits[3]='mmHo', for item named 'conductivity'
```
From experimenting, I'm pretty sure that this is a typo -- the units actually correspond to `S/m`, which is `mho/m` (not *milli*mho).

I'm going to add a case to catch this, because I have a data from a year of a sampling program with this in it.

**Comment by richardsc** [comment]
Actually, I wonder if it makes sense to *change* the units (with a warning) from what's in the file to something sensible? I propose that for this case, because the units aren't even right, but what about other similar cases? I see from looking in `odf.R` the following units:
```r
        } else if (1 == length(grep("^\\mho(s){0,1}/m\\s*$", ODFunits[i], ignore.case=TRUE))) {
            list(unit=expression(mho/m), scale="")
        } else if (ODFunits[i] == "mmho/cm") {
            list(unit=expression(mmho/cm), scale="")
```
which are `S/m` and `mS/cm` respectively.

**Comment by dankelley** [comment]
This is an interesting one. One the one hand, it's good to be faithful to what is in the file. On the other, we don't want to mess the rest of oce up too much. If the only reasonable purpose were to display units on an axis, I'd say stick with what's in the file. However, for conductivity, we may need to know the units, for calculations, and therefore we have two choices: (a) change upon reading or (b) detect the unit *anywhere* it's needed. For practical reasons of initial coding and (more importantly) code maintenance, (a) is easier.  And the other thing is that if two units are the same, but one is in cgs and the other in mks, then I would prefer the latter. We have precedents on that, e.g. oce uses velo in m/s so we convert from cm/s sometimes.

From the above, I would agree that the best plan is to alter the units away from mho to S, but to retain the numbers. In other words, I'd agree to change to "S/m" and "mS/cm", as you suggest. And a warning seems warranted, too.

**Comment by dankelley** [comment]
One more thing: I think
```R
grep("^\\mho(s){0,1}/m\\s*$", ODFunits[i], ignore.case=TRUE)
```
is wrong. I guess you mean
```R
grep("^\\s*mho(s){0,1}/m\\s*$", ODFunits[i], ignore.case=TRUE)
```
where the first double backslash is for a whitespace, with the asterisk meaning zero or more.

**Comment by richardsc** [comment]
I'm making the change -- it will be part of a PR that I submit in the next day or so (after testing).

As for the regex above -- I think that's a question for you, since you wrote it! :smile: I don't know the specific case that motivated it, but it might be worth seeing if you have such a file in your test dirs somewhere.

**Comment by dankelley** [comment]
Also, I think you mean `[s]{0,1}` or `s{0,1}` and not `(s){0,1}`. The first two both mean zero or one `s` characters. The last means the same, in this case, but it also saves the `s` into a storage area. Saving is not a problem but it's a bit confusing, because that storage area is not being used in the `grep` call, and so it would be confusing to a reader, who might suspect it's a type.

**Comment by dankelley** [comment]
Oh, if I wrote that then regexp, then it's a typo.  The `\\m` means  It means "carriage return" (maybe, or maybe newline-cr ...). It seems like mainly a msdos thing. Possibly once I had a file with that at the start (this happens when people edit files in windows software, sometimes) but I think it was a typo.

**Important** I think the docs on whatever function is doing this reading need to have a section on the errors that get corrected.  That way, people can be on the lookout for such things, and they could maybe see how to fix up their problems even if they can't set aside the time to wait for help from us. (Worst case: open the ODF in an editor, fix the problem, and done in 20s.)

**Comment by richardsc** [comment]
Good call on the docs. I'll edit those too.

Why don't you fix the regex in `develop` and I'll merge into my `cr` branch where I'm doing the edits.

**Comment by richardsc** [comment]
Re: docs -- the above changes were done in `ODFNames2oceNames()`, but I wonder if the unit changing notes should be included there or in `read.odf()` (since it's unlikely anyone would ever call `ODFNames2oceNames()` directly)?

**Comment by dankelley** [comment]
1. I altered `develop` and pushed. I think I did it right--maybe you can check.

2. As for the docs, I think it would be best to put a sentence in the first paragraph about how `ODFNames2oceNames()` gets called, and to tell readers to check that function for the handling of several erroneous values. (In other words, I prefer to put information in one place because otherwise when a new error is handled, we have to remember to document it in two places.) There is also a case that we had with the Flemish Cap data, in which a heading angle (or some-such) came out with a whacky unit ... there is a test in the code for that, actually, but I am pretty sure I did not start a list in the docs. The best way to list is to use `\\itemize{}` so every item ends up on a line by itself and there's no way for users to miss the list.

**Comment by richardsc** [comment]
Thanks! I've updated in the `cr` branch. Will merge after using and testing for a day or two.

**Comment by dankelley** [comment]
Clark, I wonder if it's ok to close this?

**Comment by richardsc** [comment]
Yes, I think so!
