### ISSUE TITLE
swSCTp() not recognizing conductivityUnit

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1151]
I discovered when doing further testing of some of the recent ODF changes I'd been making that:

1. The ODF file in `inst/extdata` has an error in the conductivity unit -- it says "S/m" but is actually conductivity ratio (as indicated by the `originalName=CRAT_01`. I guess another issue could be a discussion of whether we should catch things like this, but my vote is "no", or at least "not right now".

2. Because of this erroneous unit, calls to functions like `swSCTp()` will be wrong, because they use the unit in the metadata. However, if I specify the `conductivityUnit` in the call, I get:
  ```r
  library(oce)
  d <- read.oce('~/src/oce/inst/extdata/CTD_BCD2014666_008_1_DN.ODF')
  swSCTp(d, conductivityUnit = "")
  Error in match.arg(conductivityUnit) : 
    'arg' should be one of “”, “mS/cm”, “S/m” 
```

**Comment by dankelley** [comment]
1. I wonder whether we should pick another file. Or maybe just stop supplying an ODF file?  One problem with things in `inst/extdata` is that they are not easily documented ... if it *were* easily documented, like `data()` things, then the doc could say "the unit in this file is wrong and here is how to fix the unit" which would be valuable ... particularly for ODF, which seems more prone to incorrect  units than other formats.

2. Is anyone assigned to this? I don't see why the `match.arg` didn't work, actually. But I have discovered various times that users don't really understand the syntax, anyway, and I might prefer (if I were the one editing the code) to make the call check for `missing()` on that variable, and use `""` if so, etc.  (I have seen quite a lot of users simply cut/paste lines from these syntax summaries, i.e. they copy an entire `c(...)` sequence because they think you are supposed to do that.)

**Comment by dankelley** [comment]
Oh, I see. You cannot `match.arg` with a list with an element that is a zero-length string. I guess that makes sense -- it could match anything, I guess. I suspect this idiom is used incorrectly in half a dozen places. I'd be happy to fix it up if you like -- I'm the one who wrote that bad code.
```R
> pmatch("", c("a","b"))
[1] NA
> pmatch("", c("","b"))
[1] NA
```

**Comment by dankelley** [comment]
Oh, not that bad. Only two spots
```
$ git grep -n 'c(""'
misc.R:3533:    c("", "\001", "\002", "\003", "\004", "\005", "\006", "\a", "\b",
sw.R:483:                   conductivityUnit=c("", "mS/cm", "S/m"),
```

**Comment by richardsc** [comment]
Sure, go ahead and fix. I assigned you :smile:

**Comment by dankelley** [comment]
CR: your opinion is requested near the end ...

I have recoded for subissue 2 (now it permits `conductivityRatio=""`) in `develop` commit 46f34423972fad7a96034eb417312f4900d3f0c8

But this is a bit ugly. The docs say that if the first item is a `ctd` object then the other arguments are ignored.  (And the code does as the docs say.) Therefore, your call `swSCTp(d, conductivityUnit = "")` will not produce reasonable salinities.  This is not really a surprise -- it's very clear in the documentation -- but it actually did surprise me, when I just tested it.

I think the general pattern in oce is that when the first arg is an `oce` object, then the other args get ignored. I think that's less complicated than handling some args and not others.  When we supply an oce object as the first arg, in other words, we are assuming that we *trust* that object. I like that idea, but this still leaves us with this `ODF` file that is quite problematic. It is mentioned just once in the documentation, in the docs for `read.odf()`.

I think, at the very least, that doc should illustrate how to fix the unit. If you agree, I'll go ahead and do that.  But I would prefer to just find another ODF file.  I guess this is a station-2 profile. That's neat because `data(ctd)` is B Basin and I don't see much point in giving another one for that. We could pick data from anywhere (e.g. Flemish Cap) but in a way I'd prefer to advertise work that Dal/BIO have collaborated on since Gordon Riley's Day and Station 2 is a prime case for that.

For sure, I'd like to name the site where people could get the ODF file. I only know of one such site, the B Basin one. When I search for station-2 data, I get e.g. http://www.bio.gc.ca/science/monitoring-monitorage/azomp-pmzao/slope-pente/conditions-en.php which is a gui and I really don't like that kind of thing at all, for scientific use (although the public appreciates those sites)

Clark, any thoughts on (a) should we change the ODF file and (b) a good replacement?

**Comment by richardsc** [comment]
First, on the args, etc:

I agree with you that we shouldn't code for every combination of args. I guess I was surprised like you were that I couldn't fix a faulty unit by giving the `conductivityUnit` arg, but in retrospect it obviously makes more sense to: either give the individual CTp args, or modify the object.

Second, my opinion:
I say keep the file, but add the example showing how to correct the unit as you suggest. Data is never perfect -- this is a good chance to illustrate how to work with imperfect data (arguably, in this case, it's not even really necessary since salinity is already included in the file), while still highlight a great profile from an historical Dal/BIO location.

Are those wiggles signatures of interleaving?
![image](https://cloud.githubusercontent.com/assets/233584/21486624/ea8b4da0-cb8d-11e6-89e1-d7acb6a8b5e2.png)

I'll close now that the original issue has been addressed.

**Comment by dankelley** [comment]
I imagine those are interleaving, yes. The doc for `read.odf()` makes a TS diagram and shows loops and a very crude way to find them. But I think the data were not QCd yet ... maybe there is another data file. I wish I could remember where I got that file so I could put a URL in the docs.
