### ISSUE TITLE
File that was QC'd and exported as a .pd0 file in RDI Velocity software cannot be read in oce.

### ISSUE THREAD

**Issue by jrajewicz** [dankelley/oce#1153]
I attempted to do some quality control processing steps on a Teledyne Sentinel V ADCP file in Velocity, RDI's processing software. I applied intensity, correlation and error velocity thresholds but otherwise did not change anything about the file. I then exported this cleaned file as a `.pd0`. When I tried to open this 'cleaned' `.pd0` file using `read.oce()`, I get the error message:
```R
Error in br[i, ] <- 0.01 * (65536 * rangeMSB + rangeLSB) : incorrect number of subscripts on matrix
```

The correct date/start time for the file is 7/14/2014 at 9:20:01 (CDT) and end 7/15/2014 at 19:30:50. The instrument does not have bottom tracking capability. It was deployed looking downward.

File `A` is the original unmodified `.pd0` file, `B` is the cleaned and exported `.pd0` file.

[ADCPtestfiles.zip](https://github.com/dankelley/oce/files/676020/ADCPtestfiles.zip)

**Comment by dankelley** [comment]
Are you able to build an R package from source? This will be necessary to test the latest provisional version of oce.  This will require a C compiler, and other development tools. These are easy to set up in linux, and probably most people using linux will need no advice on this.  On Windows, it is necessary to install Rtools, which is quite easy. Things are more complex on OSX. Please see https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source for advice on all of these systems.

**Comment by dankelley** [comment]
Thanks, @jrajewicz. I started a issue test item for this, at https://github.com/dankelley/oce-issues/blob/master/11xx/1153 and that's where Clark and I will put test code. My first test was to see if the times are OK, since we have already done some work on this, and I noticed they are wrong. The result: yes, the times are mixed up. So this indicates deep problems in reading the file.  (NOTE: this test, and all tests that will get used in the test suite or reported here, have output as from the latest commit of the `develop` branch. That's why I asked about whether you were able to build from source (i.e. build from github).

Here's my first test (file `1153a.R`)
```R
library(oce)
a <- read.oce("A.pd0")
b <- read.oce("B.pd0")
head(a[["time"]])
head(b[["time"]])
```
and its output for the original file, `A.pd0`
```
[1] "2014-07-13 22:00:02 UTC" "2014-07-13 22:00:02 UTC"
[3] "2014-07-13 22:00:03 UTC" "2014-07-13 22:00:03 UTC"
[5] "2014-07-13 22:00:04 UTC" "2014-07-13 22:00:04 UTC"
```
and then (wrongly) for file `B.pd0`.
```
[1] "2014-07-13 22:00:01 UTC" "2014-01-10 01:00:00 UTC"
[3] "2014-01-10 01:50:00 UTC" "2014-01-10 02:00:00 UTC"
[5] "2014-01-10 02:50:00 UTC" "2014-01-10 03:00:00 UTC"
```

**Comment by dankelley** [comment]
Further to that,
```R
> range(a[['time']])
[1] "2014-07-13 22:00:02 UTC" "2014-07-14 08:50:50 UTC"
> range(b[['time']])
[1] "2014-01-10 01:00:00 UTC" "2014-08-31 00:00:00 UTC"
```
indicates that the time *range* is also wildly wrong. Somehow it's getting the year right but other things are coming out oddly.

**Comment by dankelley** [comment]
NOTE: I will not be adding further comments except to interact with the reporter or other developers. Instead, I will keep editing the previous comment in-place on the GH website. The idea is to avoid annoyance. I'm really just using GH as a note-taking device right now.

**Comment by dankelley** [comment]
@jrajewicz -- please note the question for you at the end.

I may have made some progress in the `develop` branch commit 6c973fc17c8cc36a26878ebd53a2fc9ac766b8a0

I get lost in lengthy comments, so I'll summarize the output that I now get from https://github.com/dankelley/oce-issues/blob/master/11xx/1153/1153a.R by saying (a) the inferred times are now identical for the two files, (b) the dimensionality of the inferred velocity (and other matrices) are now identical and (c) some test values are as below.

@jrajewicz -- can you check the output from the RDI software, against the values that oce now gives, as below? These values are from the output from the present version of  https://github.com/dankelley/oce-issues/blob/master/11xx/1153/1153a.R with the present version of the `develop` branch.  Here, `a` is from reading `A.pd0` and `b` is from `B.pdo0`.

```R
> ## first profile, first 3 bins, all 4 beams
> a[["v"]][1, 1:3, 1:4]
       [,1]  [,2]   [,3]  [,4]
[1,] -0.031 0.020  0.006 0.034
[2,] -0.075 0.071  0.019 0.028
[3,] -0.030 0.035 -0.011 0.028
> b[["v"]][1, 1:3, 1:4]
       [,1]  [,2]  [,3]   [,4]
[1,] -0.060 0.033 0.008 -0.043
[2,] -0.173 0.011 0.012 -0.043
[3,] -0.077 0.046 0.006 -0.010
> 
> ## second profile, first 3 bins, all 4 beams
> a[["v"]][2, 1:3, 1:4]
       [,1]   [,2]   [,3]   [,4]
[1,]  0.046 -0.027  0.013  0.050
[2,]  0.042  0.029  0.070 -0.003
[3,] -0.011 -0.015 -0.024  0.009
> b[["v"]][2, 1:3, 1:4]
      [,1]   [,2]   [,3]   [,4]
[1,] 0.086  0.044  0.023 -0.037
[2,] 0.015 -0.086  0.038  0.003
[3,] 0.005  0.039 -0.011 -0.009
```

**Comment by dankelley** [comment]
@jrajewicz Also, please check with the RDI software on the headings for `B.pd0`.  I ask because the first value in the heading list differs from `a` and `b`, whereas all the other values are the same. (The pitch and roll are the same throughout, as are temperature, salinity, depth, and pressure. I've been putting such tests in the https://github.com/dankelley/oce-issues/blob/master/11xx/1153/1153a.R test file)

Below are what I get. I wonder if the RDI software gives the same first heading for `B.pdo`?
```R
> head(a[["heading"]], 4)
[1] 290.07  75.83  76.57  78.41
> head(b[["heading"]], 4)
[1]  0.00 75.83 76.57 78.41
```

**Comment by richardsc** [comment]
I've just built from the latest `develop` commit, and this looks promising. I haven't dug through the code yet to see the changes, but I *am* curious to see whether this was an issue with how `oce` was reading the p-files to begin with, or with how RDI writes out their p-file export.

A note for @jrajewicz -- I recall Derek having some text export files for some of his sentinel ADCP data. That might be useful for comparing things to make sure that we're reading the binary files properly. Is there an option in Velocity to output plain text versions of the data?

**Comment by dankelley** [comment]
The change I made was in how Sentinel files are recognized. The code is confusing, with this business of reading some info at the start and later on.  The old code was trying to recognize instrument subtypes by a length of an entry in the header.  There were even comments there that said this was just a *guess*, made basically because we could not find anything in the RDI docs that told us the subtype. Anyway, it turns out that the new file had a length of that item that caused interpretation as workhorse. The new code sees if the first profile was Sentinel, and simply uses that if so, otherwise falling back to the old method of inferring subtype by length.  Well, the above words are probably less clear than the code, viz.
```R
    ## ----------
    ## RISKY CODE
    ## ----------
    ##
    ## There really seems to be nothing specific in the file to tell instrument type, so, in an act of
    ## desparation (or is that hope) I'm going to flag on the one thing that was clearly stated, and
    ## clearly different, in the two documentation entries. The exception is the 'sentinel V' class,
    ## which is recognized by a code sequence 0x00 0x70 (see near line 96), so we capture that first.
    if (isSentinel) {
        instrumentSubtype <- "sentinelV"
        ## 5 beam (4 beam workhorse + a vertical centre beam)
    } else if (FLDLength == 59) {
        instrumentSubtype <- "workhorse" # "WorkHorse Commands and Output Data Format_Mar05.pdf" (and Nov07 version) Figure 9 on page 122 (pdf-page 130)
    } else if (FLDLength == 50) {
        instrumentSubtype <- "surveyor/observer"
        ## "Ocean Surveyor Technical Manual.pdf" table D-3 on page D-5 (pdf-page 139)
        ## also teledyne2014ostm page 144 says could be Surveyor or Observer
    } else {
        instrumentSubtype <- "unknown"
        ## FIXME: I think this is a poor way to determine the intrument type. Why do we even try?
        ##> warning("unexpected length ", FLDLength, " of fixed-leader-data header; expecting 50 for
        ##>         'surveyor/observor' or 59 for 'workhorse'.")
    }
 ```

**Comment by richardsc** [comment]
Ah, yes. That makes sense. This business of inferring instrument type (and even whether the ensembles are all of the same length) has been a moving target over the years. That was much of the work that I did to get the Sentinel support working in the first place.

**Comment by jrajewicz** [comment]
Okay, in answer to your questions @dankelley:
I am getting the same issue where just the heading differs between A and B.
I checked to see if the velocities matched - my 'B' values matched but not the 'A' values..?!? Completely baffling.
I think I know what is going on. When one first opens the .pd0 file in Velocity, it is just the raw data. However, when the .pd0 file is exported, processing is done automatically and the exported .pd0 reflects these changes. I tried removing all auto processing from A and export to B - to no avail, velocities still don't match. Then I tried keeping the Velocity software defaults for A, exporting B and then making sure those same settings were still applied to B before opening it in Velocity and exporting it as a text file. all to no avail- in no test scenario do the velocities match for A and B. Ihope this makes sense. It's somewhat baffling to me.
So, it seems to me that there is some kind of change when a .pd0 is exported but as far as I can tell, I can't control this as a user. I will inquire with Teledyne and see if they can shed some light on this situation and get back to you. I am attaching here a NEW set of A and B .pd0 files, along with text file versions (mostly so you have text files to work with, since the A and B are different as I explained above but at least in the case I know what settings were applied and that it was consistent). The B .pd0 file was exported with default processing settings applied.
[try.zip](https://github.com/dankelley/oce/files/679248/try.zip)

**Comment by dankelley** [comment]
Thanks. Can I ask for a bit of clarification? (My questions are keyed to numbers I added to your comment ... you need to look online to see how I edited your comment, adding these numbers and breaking into paragraphs)

1. Are you saying that the headings you get with RDI software match the ones from oce? I'm not quite sure what you mean by "match".
2. Again, by "match" do you mean matching to the oce values?

We won't likely hear from Clark until next week. And it turns out he doesn't have the RDI software.

I'll look at your new files tomorrow morning, most likely.

Thanks!

**Comment by jrajewicz** [comment]
Hi Dan, 
Sorry for the confusion. 
1. By 'match' I mean the headings output I get with the RDI software are the same as what you are seeing in oce for the two test files A.pd0 and B.pd0. A and B do not have the same heading.
2. The values for the first and second profiles for all 3 bins, for all 4 beams were NOT the same in the RDI output as the oce values for A.pd0. They WERE the same for B.pd0. We should redo this check with the new test files I uploaded. The RDI software shows that velocity values for A_test2 and B_test2 are not the same. Now we should find out if oce yields the same values for A_test2 and B_test2 as the RDI software.

Hope that clears it up!

**Comment by dankelley** [comment]
1. The `A_test2.txt` file is stating a beam coordinate system, while `B_test2.txt` states a east-north-up coordinate system. However, when `oce` reads the files `A_test2.pd0` and `B_test2.pd0`, it interprets each as in the beam coordinate system. **Conclusion:** either `oce` is getting the coordinate systems wrong or the `.txt` files do not correspond to a straightforward dump of the data.
2. I do not know what format the `.txt` files are in, really. The metadata do not tell me much. (I suspect Clark will know immediately, when he sees the data.) As far as I can tell, though, the A case should have an initial velocity (in beam 1, time 1, I suspect) of `-0.113` (in some unit). The next velocity is `-0.061`, and I am guessing that is in the second distance bin. However, when I look at the data (using `https://github.com/dankelley/oce-issues/blob/master/11xx/1153/1153b.R`, I get as follows at the end of this comment. The velocities do not seem to match at all for `-0.113` and match for `-0.061` mid-way through the profile, which makes no sense. (I am guessing the unit is the same.)  **Conclusion:** either `oce` is not reading the data correctly or the `A_test2.txt` file is wrong, somehow.

I'm not sure how to proceed, since I don't know enough about these `.txt` files to know whether we can take them as dumps of the data. Any ideas, anyone?

**Tests**
```R
> a[['v']][1,,1]
 [1] -0.031 -0.075 -0.030  0.018  0.099  0.026  0.008 -0.037 -0.094  0.047 -0.013  0.044  0.047 -0.013  0.037 -0.023  0.033  0.069  0.003
[20] -0.053 -0.049 -0.022  0.009  0.060  0.027 -0.061  0.025 -0.026  0.043  0.002 -0.005 -0.082  0.027 -0.026  0.180  0.022  0.066  0.020
[39]  0.042 -0.040 -0.069  0.138  0.044 -0.085 -0.246 -0.007 -0.184  0.119  0.147 -0.469 -0.304  0.158  0.136  0.243  0.838 -0.246 -0.032
[58]  0.213  0.438 -0.638  1.272 -0.907 -0.690 -1.222 -0.820  0.914 -0.031
> which(a[['v']][1,,1]==(-0.113))
integer(0)
> which(a[['v']][1,,1]==(-0.061))
[1] 26
```

**Comment by dankelley** [comment]
Oh, I just noticed something. Line 28 of `A_test2.txt` *does* match the `a` velocities, apart from all those `NaN` values, which I do not understand.

Q: is the RDI software displaying `NaN` in the file because of a error-detection setting? If so, and if there is a setting to make it output the data even if it considers the numbers to be wrong, then it would be good to get those files.

And we still have the problem of the coordinate system mystery.

**Comment by dankelley** [comment]
Dear @jrajewicz,

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by dankelley** [comment]
**Standardized comment.** This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.
