### ISSUE TITLE
plotProfile(d, xtype='theta') doesn't work for ODF object with theta in data slot

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1161]
This came out of the example file from #1154, which is an ODF object that lacks salinity but has `theta` already in the object.

I  see a similar problem to the original #1154 report when doing:
```r
plotProfile(d, xtype='theta')
```
because again it is trying to calculate theta rather than looking in the object to see if it already exists.

Are there other spots that the "look first/calculate second" approach should be implemented?

**Comment by dankelley** [comment]
Clark -- a question for you at the end.

Thanks -- I'll look. I think `theta` and `sigmaTheta` (and similar) are the main examples, and perhaps the only ones. I think I was doing that because I didn't trust the values in some files. (I don't have any firm memory, though ... this is going back to very early days.)

I propose (and ask that Clark add a comment with his thoughts ... no rush though):

1. The accessor `[[` should return the column if it exists, otherwise calculate.
2. The functional form e.g. `swTheta(ctd)` should return the column if it exists, otherwise calculate it. (Similar for sigma-theta etc.)
3. The functional form e.g. `swTheta(S, T, p)` should calculate the quantity, regardless of whether `theta` is a column. This is the form to use when you desire calculation, no matter what's in the object. It is also nice because you can decide, for example, which of several `T` values you might want to use for a given dataset.

We want to accommodate users' choice to sometimes look up, and other times calculate. And, of course, the docs will need to be clear on this.

**Comment by richardsc** [comment]
I added my thoughts inline to your comment above. The only one I'm not sure I agree on is the second -- about the behaviour of the functional form `swTheta(ctd)`. This is partly because the "accessor" approach is already covered by the `[[` notation, and I feel like we abandoned the "functional accessor" approach several years ago in favour of it.

Thus, I would argue that `swTheta(ctd)` should always calculate `theta` based on the object, rather than access an existing field. Another possibility could be to calculate first, then access, but I'm afraid that will just make it confusing, and would rather keep the `[[` notation as the accepted syntax for accessing data fields.

And yes, this will largely come down to clear documentation.

**Comment by dankelley** [comment]
Thanks, we have a decision then:

1. The accessor `[[` should return the column if it exists, otherwise calculate.
2. The functional forms e.g. `swTheta(ctd)` and `swTheta(S,T,p)` etc should calculate the quantity, regardless of whether `theta` is a column. This is the form to use when you desire calculation, no matter what's in the object. It is also nice because you can decide, for example, which of several `T` values you might want to use for a given dataset.

**Comment by richardsc** [comment]
Agreed (obviously!)

**Comment by dankelley** [comment]
In looking at this, I saw that there was a problem with `[[<-` for the `odf` method. It only comes up when it has to use `callNextMethod`, though, which is why we never saw it before. The diff is as below: we have to use the `...` argument. I will change *every* object in oce to use this form, and run lots of tests before pushing to GH.
```
 setMethod(f="[[<-",
           signature(x="odf", i="ANY", j="ANY"),
-          definition=function(x, i, j, value) {
-              callNextMethod(x=x, i=i, j=j, value=value)
+          definition=function(x, i, j, ..., value) {
+              callNextMethod(x=x, i=i, j=j, ..., value=value)
           })
```

**Comment by dankelley** [comment]
Clark, I think this may be handled now in `develop` commit 1371dc11b2a43ac86e109db23975f2214d295f53. 

No rush on checking this, but just saying "over to you".

The example code (from the test suite)
```R
library(oce)
library(testthat)
## source("~/git/oce/R/ctd.R")
## source("~/git/oce/R/sw.R")

d <- read.oce("CTD_98911_1P_1_DN.txt")

if (!interactive()) png("1161a.png")
par(mfrow=c(1,2))

## 1. test access
expect_equal(length(d[["theta"]]), 127)
expect_equal(head(d[['theta']]), c(0.0346, 0.1563, 0.2153, 0.1970, 0.1916, 0.2141))
plotProfile(d, xtype='theta')

## 2. test assignment (fake signal)
d[["theta"]] <- rep(10, length.out=length(d[["pressure"]]))
expect_equal(length(d[["theta"]]), 127)
expect_equal(head(d[['theta']]), rep(10, 6))
plotProfile(d, xtype='theta')
mtext("EXPECT: vertical line", col="magenta", font=2, line=-1)

if (!interactive()) dev.off()
```
makes as below, without warnings or errors.

![1161a](https://cloud.githubusercontent.com/assets/99469/21578517/915f1d22-cf59-11e6-9fbd-a8382576ed0b.png)

**Comment by richardsc** [comment]
Looks good!
