### ISSUE TITLE
Recommend an approach to read in multiple seabird files?

### ISSUE THREAD

**Issue by boshek** [dankelley/oce#1196]
This is a great package and I wish I'd found it years ago. Quick question though - can you recommend a good way to read in multiple .cnv at one time? I've been trying to experiment with something like this:
[https://github.com/boshek/seabirdR/blob/master/R/read_seabird.R](https://github.com/boshek/seabirdR/blob/master/R/read_seabird.R)

Obviously `oce` has a much more sophisticated approach to my clumsy attempt to read in seabird files. However I am wondering if you can recommend an approach to read in many files. This is the approach that I'd take right now:
```
ctddf <- c()
for( i in list.files(pattern="*.cnv", recursive=recursive)){
  tmp = read.ctd.sbe(i)
  tmp = as.data.frame(tmp[["data"]])
  ctdfdf = rbind(tmp, ctddf)
  ctdfdf$Label = factor(i)
}
```
This approach, while having the advantage for me of being a dataframe, loses all the header information within the ctd class which seems like a waste of all this amazing functionality. I am assuming you have encountered this before and am curious what your solution has been.

**Comment by richardsc** [comment]
Thanks for the kind words about the package! We love hearing about people who discover it and are using it for their work.

I'll post some hints in a followup comment.

**Comment by dankelley** [comment]
It depends on what you want to do with the results. I would normally do as follows
```R
files <- list.files(pattern="*.cnv")
ctds <- vector("list", length(files))
for (i in seq_along(files))
    ctds[i] <- read.oce(files[i])
```

At this stage, `ctds` is a list, each element of which is a ctd object. You can do whatever you want with the elements in that list. For example, to plot the first try
```R
plot(ctds[[1]])
```
or to see what's in that CTD entry, do
```R
summary(ctds[[1]])
```

A great function for lists is `lapply`. For example, here is how to extract the salinities from each of the files
```R
S <- unlist(lapply(ctds, function(x) x[["salinity"]]))
```

Quite often, my first step after reading is to plot all the files. But I like doing that with uniform S and T (etc) scales so that I can page through with the arrow key (or make a movie). For a uniform scale, I'd just do `range(S, na.rm=TRUE)` with the above, etc. This can be useful if the files are related, e.g. for CTD casts. The map in the default plot will be centred on the lon and lat of the station, but often times you'll want to use `clongitude` and `clatitude` (and `span`) to control that.

Oh, I see that Clark is about to respond. We may be racing. I'll finish this and see what he says -- he's smarter than I am so the above will look silly!

**Comment by richardsc** [comment]
Haha, we were racing, but @dankelley was way out in front. +1 on the `lapply()` suggestion -- it is very handy for extracting/manipulating different fields in lists of objects.

One followup that I would post is that some `oce` functions know how to handle lists of `ctd` objects, e.g. `as.section()`, which converts a list of `ctd` objects into a `section`-class object.

This is handy if the multiple files that you're trying to read were all done along a line, or are at least in some way connected together. As an example, you can see the example section data included in oce, by doing `data(section)`, and then use some of the generic functions like:
```r
plot(section)
```

**Comment by boshek** [comment]
Ok this is very helpful. I am looking to turn this into a dataframe because we have been working on an R implementation of the split and merge algorithm for mixlayer and thermocline estimation from CTD casts. Right now the functions that call the algorithm are built with a data.frame in mind (though lists aren't inherently a problem). However, I might just tune it a little more closely to the output of read.ctd.sbe(). Here is the split and merge algorithm if you are interested:

[https://github.com/boshek/limnotools](https://github.com/boshek/limnotools)

For data manipulation, I live primarily in the `tidyverse` and use primarily data.frames with that application. But maybe I am trying to fit a square peg into a roundhole here when I should be learning how to use the round peg....

**Comment by dankelley** [comment]
In oce, data frames are not usually used. This is because we want to store a lot of metadata, along with the data. It would be crazy to, for example, have a "column" in a data frame that simply repeated the serial number of an instrument, or the number of a station, or the calibration coefficients used for each sensor in a CTD instrument, any of the dozens of extra snippets of information that would apply to even something as simple as a CTD cast. And even forgetting about metadata, the data-frame notion fails for lots of data types. For example, consider ADCP records ... they consist of some things that are best represented by vectors (time, bin distances, etc) and others that work best as matrices (velocity, etc). This explains why in oce we (a) use "slots" for `metadata` and `data` (and also for a processing log) and (b) we use `list` to store things inside the `@data` slot.

@boshek -- I think the issue as defined by its title has been addressed. If you agree, perhaps you'd consider closing this issue. In oce, we like for reporters to close issues. And we also try to have granular issues, one issue per narrow topic. So, for example, the previous paragraph is not really relevant in this case, but I thought it might help. I'll look at the link you provided -- thanks!!

**Comment by boshek** [comment]
Indeed and apologies for the tangent.
