### ISSUE TITLE
ctds plot and section plot of different survey days. Indicative labels in the plots

### ISSUE THREAD

**Issue by lorenaolmos** [dankelley/oce#1206]
I would like to plot the ctd data obtained in four stations, in two different days. And afterwards to plot the section obtained by the 4 ctd stations  in the two different days. 

library(oce)
library(readxl)
>a <- read_excel("lorena2.xlsx", sheet = 1, col_names = TRUE, col_types = NULL, na = "",
                skip = 0)

If I had one day, I would split by station 
>asplit <- split(a, a$station)

I was trying to split by both date and station with strplit but It does not work

>asplit <- strsplit(a, c("day", "month", "year", "station"))

Is there any other way to split quickly these data to create the ctd objet and to add the other fields to ctd objects later? 

>ctds <- vector("list", length(asplit))
fields <- c('SBE43', 'Fluorescence', 'Oxygensat')

>for (i in seq_along(asplit)) {
  ctds[[i]] <- as.ctd(asplit[[i]], longitude=asplit[[i]]$longitude[1], 
                      latitude=asplit[[i]]$longitude[1])
  
>  for (field in fields) {
    ctds[[i]] <- oceSetData(ctds[[i]], tolower(field), asplit[[i]][[field]], originalName = field)
  } 
}

how can I plot the ctds including the names of the station and the day of sampling for each graph?

>for (i in seq_along(asplit)) {
  plot(ctds[[i]])
}

How could I include labels of sampling day in the section graph?
>sec <- as.section(ctds)
>plot(sec)

Thank you very much!

[lorena2.xlsx](https://github.com/dankelley/oce/files/859272/lorena2.xlsx)

**Comment by dankelley** [comment]
Can you provide a new dataset? The one you provided does not have station information:
```R
> a <- read_excel("lorena2.xlsx", sheet=1, col_names=TRUE, col_types=NULL, na="", skip=0)
> 
> names(a)
 [1] "day"          "month"        "year"         "trans"        "press"        "temperature" 
 [7] "conductivity" "SBE43"        "Fluorescence" "Salinity"     "Oxygensat"    "Density"     
```

**Comment by dankelley** [comment]
Also, that new dataset does not contain longitude and latitude.

**Comment by lorenaolmos** [comment]
oh sorry! I had not realized. Here is the new excel. Thank you very much 
[lorena2.xlsx](https://github.com/dankelley/oce/files/872156/lorena2.xlsx)

**Comment by dankelley** [comment]
Hi. At https://github.com/dankelley/oce-issues/tree/master/12xx/1206 I have put some R code (look at the file that ends in `.R`) that might be a start for you.  Please read the code for explanations.

Also, please note that I have put some comments in https://github.com/dankelley/oce-issues/blob/master/12xx/1206/1206a.R that I hope can be of some help to you.  The main message is that, with R (or any programming language, as opposed to excel) it is *very* important to establish an accurate and stable system of data organization. Any change to the data (e.g. changing the spelling of a variable name, including changing capitalization) will require rewriting the code, and that makes it difficult to work effectively. Things are different in excel. In excel, you can rely on the user to "decode" variable names by ignoring differences in spelling, etc. And you can rely on them to see that columns are misnamed (as in this most recent file you've posted). But trying to make R code "learn" such things is not a good use of your time. The biggest advice I can give to you, as a new user of R, is to set up data conventions early in your work, and to adhere to them.  It can also help to stop using excel, because it tends to get people into bad habits. In this case, I imagine the data are available as `.cnv` files ... I suggest you just use them, because `oce` can read them, thereby saving you a lot of work.

I hope this helps. It may be a few days before I can add more. Good luck, and have fun with R!

**Comment by lorenaolmos** [comment]
Hi Dan, 
thank you very much for your code and for your advices.  Your help has been exceptionally useful. Sorry for the mess with the excel file! Absolutely, next time I will do everything from the beginning with cnv files. Here I upload the final (and correct excel), and the code for this correct version.

I have just last question, in the deepest section (5), I have data until 109 m, but the section plots only show values until 80 m. Why is this?  

Thank you really much for all your precious help
[lorena2.xlsx](https://github.com/dankelley/oce/files/876406/lorena2.xlsx)


>library(oce)
>library(readxl)

a <- read_excel("lorena2.xlsx", sheet=1, col_names=TRUE, col_types=NULL, na="", skip=0)

a$t <- ISOdatetime(a$year, a$month, a$day, 0, 0, 0, tz="UTC")


#as = a, split up by time
>as <- split(a, factor(a$t))

>n <- length(as) # number of distinct days
>d <- vector("list", n)

>profiles <- vector("list", n)



>for (iday in 1:n) {
  d[[iday]] <- as.ctd(as[[iday]])
  d[[iday]] <- oceSetData(d[[iday]], "oxygen", as[[iday]]$oxygensat)
  d[[iday]] <- oceSetData(d[[iday]], "fluorescence", as[[iday]]$fluorescence)
  d[[iday]] <- oceSetData(d[[iday]], "longitude", as[[iday]]$longitude)
  d[[iday]] <- oceSetData(d[[iday]], "latitude", as[[iday]]$latitude)
  profiles[[iday]] <- ctdFindProfiles(d[[iday]])
}

#plot ctd profiles
>if (!interactive()) png("1206a_profiles_%02d.png")
>for (iday in 1:n) {
  for (j in seq_along(profiles[[iday]]))
    plot(profiles[[iday]][[j]])
}
>if (!interactive()) dev.off()


>if (!interactive()) png("1206a_sections_%02d.png")
par(mfrow=c(2, 1))



#plot section
>par(mfrow=c(2,2))
>for (iday in 1:n) {
  sec <- as.section(profiles[[iday]])
  plot(sec, which="temperature", nlevel=20, ztype='image')
  dist <- geodDist(sec)
  axis(3, at=dist, label=seq_along(dist)) 
  title(main = iday) 
  plot(sec, which="fluorescence", nlevel=20 , ztype='image')
  dist <- geodDist(sec)
  axis(3, at=dist, label=seq_along(dist))
  title(main = iday)
} 


>if (!interactive()) dev.off()

**Comment by dankelley** [comment]
I edited your comment to put it in R format. I think the problem is that oce only contours between non-missing depths. Your station 4 gets down to 107dbar, but your station 3 only gets 71 dbar (see below for how I found that out).  The way oce works is to only interpolate horizontally across depths covered in each of the two adjacent stations. This is by design. We don't want to "pretend" data exist where they do not exist. For example, suppose we had a mid-ocean ridge that was 1000m deep, and had a station on either side of it going down to 2000m. It would not be good to draw contours across the ridge. Oce takes a conservative approach. (There are other ways to contour; try `?interpBarnes` to learn about a method that some people like, but that I *DO NOT* recommend, because it does take into account the fact that water is resistant to exchange in the diapycnal direction, but not in the isopycnal direction.)
```R
> sec[["station",3]]
ctd object has data as follows.
   pressure: 7.0, 7.5, ..., 70.5, 71.0 (length 129)
   salinity: 35.719, 35.721, ..., 35.764, 35.764 (length 129)
   temperature: 14.731, 14.670, ..., 12.464, 12.464 (length 129)
   conductivity: 4.3439, 4.3381, ..., 4.1268, 4.1268 (length 129)
   oxygen: 5.6936, 5.7004, ..., 5.9637, 5.9638 (length 129)
   fluorescence: 3.6257, 3.6505, ..., 0.2635, 0.2620 (length 129)
   longitude: -8.947, -8.947, ..., -8.947, -8.947 (length 129)
   latitude: 42.2, 42.2, ..., 42.2, 42.2 (length 129)
   scan: 215, 216, ..., 342, 343 (length 129)
> sec[["station",4]]
ctd object has data as follows.
   pressure: 5.5, 6.0, ..., 106.5, 107.0 (length 204)
   salinity: 35.672, 35.679, ..., 35.762, 35.762 (length 204)
   temperature: 15.966, 15.897, ..., 12.430, 12.431 (length 204)
   conductivity: 4.4625, 4.4564, ..., 4.1249, 4.1249 (length 204)
   oxygen: 5.5565, 5.5638, ..., 5.968, 5.968 (length 204)
   fluorescence: 3.1267, 2.8580, ..., 0.2419, 0.2564 (length 204)
   longitude: -8.9951, -8.9951, ..., -8.9951, -8.9951 (length 204)
   latitude: 42.2, 42.2, ..., 42.2, 42.2 (length 204)
   scan: 365, 366, ..., 567, 568 (length 204)
```

**Comment by lorenaolmos** [comment]
Ok, I understand now! 
Thank you really much!

**Comment by dankelley** [comment]
Glad to help. 

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by lorenaolmos** [comment]
Perfect!Thanks again
