### ISSUE TITLE
mapImage should be able to work without calling mapPlot first

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1212]
To make a projected image plot, currently one has to first call `mapPlot()`, which sets the hidden variable containing the projection information, followed by a call to `mapImage()`. This means that you always have to plot something (like `coastlineWorld`) before you can make an image plot. E.g.
```r
library(oce)
data(coastlineWorld)
data(topoWorld)
mapPlot(coastlineWorld)
mapImage(topoWorld)
```

I think it would be handy if `mapImage()` could work so that it can be supplied with a `projection=` argument, the same as in `mapPlot()`, that allows it to work as a "primary" plotting function, like `imagep()`. That way (as with `imagep()`) it is possible to plot a matrix field but also to get the colorbar by default.

I could see the new version of `mapImage()` doing the projection setting if either:

1. the `projection=` argument is missing AND `.Projection` isn't already set, or
2. the `projection=` argument is supplied.

Otherwise, it would behave as it does now, where it reads the `.Projection` and *adds* to an existing projected plot.

**Comment by dankelley** [comment]
I don't quite get the recommendation.

Case 1: what projection to use in that case?  (Or by "missing" do you mean "not specified by the user"? These are different things, e.g. for `mapPlot`, there is a default set in the arglist, so `missing(projection)` always returns `FALSE` within `mapPlot`, whether the user sets a value or not.)

Case 2: should we demand that the projection matches the existing? If not, then we can get a confusing condition, e.g. a coastline drawn with one projection, and an image added with another ... and when you see the plot, there's no way to know if this happened.

And I'm not sure what you are thinking about with colourbars.  (Coding that would be tricky, actually, because it gets us into a lot of conditions: 2 for existence of `.Projection()` times 2 for whether `projection` was supplied times 2 for whether a colorbar is desired ... that's 8 right off the bat.)

Right now, a person can make a colorbar, then set up to have a projected plot alongside it, e.g.
```R
library(oce)
data(coastlineWorld)
data(topoWorld)
cm <- colormap(breaks=seq(-8000, 0, length.out=200))
drawPalette(colormap=cm)
mapPlot(coastlineWorld)
mapImage(topoWorld[["longitude"]], topoWorld[["latitude"]], topoWorld[["z"]], colormap=cm)
```
and so I think the issue of drawing palettes is solved. (That reduces the work by a factor of 2, in the above calculation.)

In terms of recoding oce, the simples is to add a new function, perhaps
```R
mapProjection(projection)
{
    # handle 'projection' as mapPlot does
}
```

This is what I was thinking when we were talking yesterday. For the user, I think it's pretty simple, and I think in my own work I would even prefer it, since then I don't have to remember this magic thing that `mapPlot` will "set" the projection, but other `map...` functions will not set it. I think the following code looks quite readible:
```R
mapProjection("+proj=merc")
mapPlot(coastlineWorld)
```
I am not sure I prefer this name. Maybe it should be `mapSetup`.

Thoughts?

I'm on my mobile, if a phone call would be easier for explaining.

**Comment by dankelley** [comment]
I'm fiddling (in `dk` branch, and not pushing to GH) and should have that working tomorrow sometime, I think.

**Comment by dankelley** [comment]
The `dk` branch has what may be a solution. It would be great if @richardsc could try building the branch, and looking at the newly-added final example in the `mapImage` doc.  I don't really want to put this into the `develop` branch until it has a bit more testing, because the internal workings of `mapPlot` also got changed<sup>1</sup>.

<b>1.</b> I've refactored the code, by taking the map-projection setup code from `mapPlot` and putting it into a new function named `mapProjection`. This was so that `mapImage` could get the suggested capability, without having to duplicate code. While I was at it, I tried to improve some other things. Now, instead of using a spherical model of the earth, I set up what seems to be today's common standard of a particular ellipse ... and I also set up the datum to match. (As before, though, the user can specify these things in the `projection` string, if they wish.)

**Comment by richardsc** [comment]
I think we're making progress. After a phone call, we've decided to make some more significant changes to the `mapImage()` UI, as outlined in Issues: #1215 , #1217 , #1216

**Comment by dankelley** [comment]
Further to a f2f today... the following is an easy way to set up a plot, without drawing a coastline. Doing this before a `mapImage` call would seem to be a possible solution that would not confuse users too much, and would not require new coding.
```R
library(oce)
mapPlot(c(10,20), c(30,50), proj="+proj=merc +lon_0=15", type="n")
```

Maybe I should put a line like the above in the `mapImage` docs and we could consider closing this ...??

**Comment by dankelley** [comment]
To be specific, 
```R
library(oce)
data(topoWorld)
mapPlot(c(-180,180), c(-90,90), type="n")
mapImage(topoWorld)
```
seems to me to be just about as nice as the suggested
```R
library(oce)
data(topoWorld)
mapImage(topoWorld)
```
and so I propose adding hints along these lines to the docs for `mapImage` and closing the issue tomorrow morning ... seem ok, @richardsc ?

**Comment by richardsc** [comment]
Yes, though I think that the example should include how to draw the palette too. This is one aspect that is missing from the `imagep()`/`mapImage()` paradigm right now -- because `mapImage()` only adds it doesn't handle the palette.

Maybe something like:
```r
library(oce)
data(topoWorld)
cm <- colormap(topoWorld[['z']], name='gmt_relief')
drawPalette(colormap=cm)
mapPlot(c(-180,180), c(-90,90), type="n")
mapImage(topoWorld, colormap=cm)
```

**Comment by dankelley** [comment]
I added an example for `mapImage` (in "develop" branch). Maybe you can consider closing ... I think #1217 could also be closed, if you consider it sufficient to illustrate a solution in documentation, as opposed to adding new arguments.
```R
## 4. Topography without drawing a coastline first
data(topoWorld)
cm <- colormap(topoWorld[['z']], name='gmt_relief')
drawPalette(colormap=cm)
mapPlot(c(-180,180), c(-90,90), type="n") # defaults to moll projection
mapImage(topoWorld, colormap=cm)
```

**Comment by richardsc** [comment]
Great, closing!
