### ISSUE TITLE
Changed behaviour in binApply1D wrt xbreaks

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1214]
I'm sure that this is related to the recent changes to `binApply1D()` that were done for the ADP ensemble averaging (e.g. #1200), but I'm seeing behaviour that is at least different from what it was before (I know this because some old code broke).

The issue has to do with what happens when `xbreaks` spans a range bigger than the `x` data provided. An example:
```r
x <- seq(0, 899)
xbreaks <- seq(0, 1000, 100)
y <- rnorm(x)
b <- binApply1D(x, y, xbreaks, mean)
str(b)
List of 3
 $ xbreaks: num [1:11] 0 100 200 300 400 500 600 700 800 900 ...
 $ xmids  : num [1:10] 50 150 250 350 450 550 650 750 850 950
 $ result : num [1:9] 0.0564 0.0356 -0.0782 0.0188 -0.083 ...
```

Note that `result` is 1 shorter than `xmids`, I assume because there were no data in the final break specified by `xbreaks`. While this makes sense sort of, it seems counter-productive, as it isn't even possible to plot the binned object, e.g. `with(b, plot(xmids, result))` because they are of different length.

I think that if an xbreak has no values, the `result` should contain NA.

**Comment by dankelley** [comment]
I agree, it should fill in `NA`s.  I can do that tomorrow, if you like.

**Comment by richardsc** [comment]
You're closer to the code, so I think it's better if you make the change. Not a big rush -- I've already implemented a work-around where I need it.

**Comment by dankelley** [comment]
Thanks for catching this.

I think the problem is solved in `develop` commit 139442f32d2b4c55d23305468c986278e47f91fd. I added an item (https://github.com/dankelley/oce-issues/blob/master/12xx/1214/1214a.R) and have copied those tests to `tests/testthat/test_misc.R`. I wonder if you could look at those new tests in `test_misc.R`, to see if I have caught the possible cases.

My solution is a bit ugly ... I could not see an argument to the low-level R functions to handle this sort of thing, but I bet there is a cleaner way than the new code I wrote.

**Comment by richardsc** [comment]
Thanks!

I don't think the solution is that ugly, but then, it wasn't clear to me what was changed recently that caused it to *stop* working (I'm 85% sure that it worked as expected before the recent changes stemming from the adp ensemble average code).

I suppose the answer to that is to go back to the older source (e.g. > 6 months ago), and test that against the new code to see what the behaviour is.

**Comment by dankelley** [comment]
Are you volunteering to go back to the old source to make up some tests? I feel that the new scheme is okay, actually. (I meant that source was ugly, not the user interface. And I mean "ugly" just because I had really suspected that the basic R routines would have a way to handle this, but I don't think they do, and so I have this special-casing in what I wrote.)

**Comment by richardsc** [comment]
TBH I was *thinking* about volunteering to go back through the old source, but after having thought about it for a few minutes I've decided that if I do it won't be on the basis of this open issue, so I'll close.

I tested on the cases that caused me to notice this problem, and they work perfectly, so I'm happy.
