### ISSUE TITLE
consider adding `useRaster=` arg to `imagep()`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1218]
Because I know we've all struggled with the "ghosty lines" issue when making image plots, I thought I'd share a little tidbit that I just got from RTFMing for `image()`. Note this arg:

> useRaster	
logical; if TRUE a bitmap raster is used to plot the image instead of polygons. The grid must be regular in that case, otherwise an error is raised. For the behaviour when this is not specified, see ‘Details’.

With some of the details:

> Images for large z on a regular grid are rendered more efficiently with useRaster = TRUE and can prevent rare anti-aliasing artifacts, but may not be supported by all graphics devices. Some devices (such as postscript and X11(type = "Xlib")) which do not support semi-transparent colours may emit missing values as white rather than transparent, and there may be limitations on the size of a raster image. (Problems with the rendering of raster images have been reported by users of windows() devices under Remote Desktop, at least under its default settings.)
The graphics files in PDF and PostScript can be much smaller under this option. 

So, I did a quick test, which is attached. The first plot was made with
```
image(z)
```
and the second with
```
image(z, useRaster=TRUE) 
```
At least on my screen (with several different viewers), I see ghosty lines on the first plot and a normal-looking image plot on the second. 

I think we should consider adding `useRaster=` to `imagep()`, or at least look into the consequences of doing so ...
[raster.pdf](https://github.com/dankelley/oce/files/911719/raster.pdf)

**Comment by dankelley** [comment]
Interesting I don't think I've ever seen this `useRaster` argument. Also, I find the second page renders faster in macOS preview (because it has to do a lot of calculations to antialias, in the first page). A big question for me would be whether there are any snags when png, pdf, jpg, etc are incorporated into latex.

**Comment by dankelley** [comment]
I've added this to `develop` commit b85f7f8e4764edb087fad58abd821b7c2e142a52 but I'm not exactly sure how to test it, because (for some reason) I'm not seeing these ghostly pixel edges on my system.  Maybe @richardsc can think of a test. I prefer not to explain here what `useRaster` is meant to do ... on of the things I'm hoping is that @richardsc can check how I've documented it (and maybe then also see that all I've done is to add this to the `image()` calls, which means that `useRaster` is ignored if `filledContour` is `TRUE`)

**Comment by richardsc** [comment]
Looks good to me! I definitely see a difference on my two primary pdf viewers (windows and linux), so I think it's a worthwhile improvement.

The documentation looks good! Closing
