### ISSUE TITLE
ctdTrim() should have a `method="upcast"` method

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1221]
I was surprised to discover that this doesn't exist ... Not saying that it needs it for sure (since it's non-standard), but it seems like it would be sensible.

**Comment by dankelley** [comment]
I'll have a look -- it won't be bad to have eyes on that code, anyway, since it has changed a fair bit over the years. (It's not changing for change's sake; this is basically a hard problem of pattern recognition.)

I'll probably just code something analogous to the `downcast` method, and test it with `ctdRaw`, as a start, knowing that tweaks will likely be needed as the algo is applied to more extensive data.

**Comment by dankelley** [comment]
I'm not too happy with the existing scheme, really. The code
```R
library(oce)
data(ctdRaw)
plotScan(ctdTrim(ctdRaw))
```
yields as shown.  I don't like that stuff at the beginning.  This function has changed a lot over the years, trying to fit one circumstance or another. But this graph suggests the method is not that great at the moment.
<img width="774" alt="screen shot 2017-04-22 at 9 31 53 am" src="https://cloud.githubusercontent.com/assets/99469/25304490/ad3f574a-273e-11e7-96f3-e908a983cd28.png">

**Comment by dankelley** [comment]
If I use the SBE method the results are better, but I still don't like the results very much
```R
plotScan(ctdTrim(ctdRaw, method="sbe"))
```
<img width="773" alt="screen shot 2017-04-22 at 9 35 18 am" src="https://cloud.githubusercontent.com/assets/99469/25304504/0359f9fa-273f-11e7-847a-f83e041feb6c.png">

**Comment by dankelley** [comment]
Of course, before getting carried away with the `ctdRaw` dataset, it should be noted that this is the result of a class on a field trip, so the procedures might not be similar to what would be employed on an oceanographic vessel with trained technicians.

**Comment by dankelley** [comment]
In `develop` commit 21920d0898f14c2ef95619cebad77e99582cbb33 I have some test code. It basically just does the same as `"downcast"` but with some small things flipped. Now,
```R
library(oce)
data(ctdRaw)
d <- ctdTrim(ctdRaw, "upcast")
plotScan(d)
plot(d)
```
gives as follows.  The first graph shows that it isolates the upcast, at least rough. But the second one shows that there is junk at each end of the sequence.

I really don't know if `ctdRaw` is a good test case.  The fact that it's in oce is not a good enough reason to warp algorithms to work with it (because then the algorithms might be bad on other datasets)
![1](https://cloud.githubusercontent.com/assets/99469/25304646/fe882fd4-2741-11e7-96b4-30d12afe57d1.png)

----

<img width="670" alt="2" src="https://cloud.githubusercontent.com/assets/99469/25304648/056e7a38-2742-11e7-81ac-2d5d6cbdce33.png">

**Comment by dankelley** [comment]
Oh, and for context (since after this comment, I pass the microphone back to @richardsc), below is what we get from
```R
library(oce)
data(ctdRaw)
plotScan(ctdRaw)
plot(ctdRaw)
```
<img width="669" alt="screen shot 2017-04-22 at 9 57 43 am" src="https://cloud.githubusercontent.com/assets/99469/25304670/4e0677aa-2742-11e7-9974-f972c2557803.png">

----


<img width="674" alt="screen shot 2017-04-22 at 9 57 58 am" src="https://cloud.githubusercontent.com/assets/99469/25304672/5328ec0e-2742-11e7-820e-db321933cb33.png">

**Comment by richardsc** [comment]
I've not tested this extensively, but using both the `ctdRaw` as well as some other data sets I have it seems to be pretty sensible. I think any new problems or requests can have new issues (since the title has been addressed).

Thanks!

**Comment by dankelley** [comment]
Also, re its relevance, note that the SIO guidelines for CTD processing say to use the upcast if there are problems that cannot be solved in the downcast. So it's something we should have had long ago. Thanks for suggesting this!

**Comment by richardsc** [comment]
Yes, this came up because of some recent discussion about an instrument that potentially was having pump issues. Then I looked at a random profile from the Bedford Basin, which shows lots of interesting and important looking differences between up/down cast:
![image](https://cloud.githubusercontent.com/assets/233584/25338334/442dcc1c-28d5-11e7-96b0-0f9f778361f9.png)
