### ISSUE TITLE
write.ctd metadata

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#1231]
Hi Clark/Dan,

We've had some requests from modelers and students to convert our .ODF files to .CSV for easier program ingestion and intuitive viewing.  I'm a little reluctant to do this without incorporating some standard metadata in a header.  Your `write.ctd` function works great to export to a .CSV, but it would be nice to have a "include metadata" option.

**Comment by dankelley** [comment]
Do you have a suggestion of where to put the information, and how to denote it? I'm not an excel sort of person, so I don't know what users would expect.  (I assume the way they work is to visually look at a file, scroll down until they find what seems to be data, then ... well, I just don't know how they might actually be working.  (Maybe the header lines should be in column 1, as strings starting with `#` or something??)

The idea situation would be for you to mock up a file, with say 2 header lines and then data.

**Comment by atcogswell** [comment]
Personally, I'd rather that people just use the ODF and extract the data from there than produce the .CSV.  That said, I think that just a modified version of the base metadata that is produced when you use the plot(x, which="text") would be fine.  Placed at the very top of the .csv in the first column should be OK.  As long as the number of rows it occupies remains consistent. 

[https://github.com/atcogswell/MoPS/blob/master/test.csv](url)

**Comment by dankelley** [comment]
(I fixed your comment so the link would work.)

What you suggest is easy, and I'll do it this afternoon.

Q: shouldn't there be an item for a station ID? I know the lon-lat-time makes it unique, but I find station numbers quite handy e.g. in repeated sampling where a station tends to get occupied (not exactly always at the precise-same lon and lat though).

I propose to put in a blank line at the bottom of the header information, so people who work visually can see where the data start, and people writing code can detect the blank line.

I'd prefer to have ISO times like `2017-04-19 08:54:00` instead of `19/04/2017 8:54` ... could excel people handle that, I wonder?  (Maybe they could handle it if we had `day` and `time` fields?)  I basically find the `/` type dates wildly confusing.

**Comment by dankelley** [comment]
I've updated `develop` commit 67f7f5534a9e8fde0dc83fe637ea1ad428ade738 to do something that may be helpful. Below is a sample code. Maybe you could try it, and comment on whether I seem to have done something useful ... then either suggest changes or close the issue. Thanks!

PS. I'm just using a test file that we include with `oce`. It's not clear to me that we should include that, actually ... it's only likely to be useful to people at a few institutes. So, the code below might fail, some day.

```R
library(oce)
odf <- read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF", package="oce"))
ctd <- as.ctd(odf)
write.ctd(ctd, "test1.csv")
write.ctd(ctd, "test2.csv", metadata=TRUE)
```

I get, in the shell:
```
$ head -5 test1.csv
"scan","pressure","pressureFlag","temperature","temperatureFlag","conductivity","conductivityFlag","oxygenVoltage","oxygenVoltageFlag","fluorometer","fluorometerFlag","par","parFlag","salinity","salinityFlag","oxygen","oxygenFlag","sigmaTheta","sigmaThetaFlag","flagArchaic","flag"
1781,0.5,1,5.885,1,0.71242,1,2.5636,1,3.6333,1,104.43,1,30.8514,1,6.422,1,24.2896,1,0,0
2669,1.5,1,5.9124,1,0.713118,1,2.5786,1,3.6417,1,87.676,1,30.8593,1,6.4833,1,24.2927,1,0,0
2678,2,1,5.9188,1,0.713251,1,2.5811,1,3.6052,1,80.475,1,30.8596,1,6.4916,1,24.2922,1,0,0
2686,2.5,1,5.9109,1,0.713073,1,2.5835,1,3.8124,1,74.103,1,30.8581,1,6.5021,1,24.2919,1,0,0
```
and
```
$ head -10 test2.csv
Station:  8 
Source file:  /Library/Frameworks/R.framework/Versions/3.4/Resources/library/oce/extdata/CTD_BCD2014666_008_1_DN.ODF 
Ship:  CCGS SIGMA T (Call Sign: unknown) 
Cruise:  Scotian Shelf 
Depth:  156 
Start time:  2014-12-16 14:09:09 

"scan","pressure","pressureFlag","temperature","temperatureFlag","conductivity","conductivityFlag","oxygenVoltage","oxygenVoltageFlag","fluorometer","fluorometerFlag","par","parFlag","salinity","salinityFlag","oxygen","oxygenFlag","sigmaTheta","sigmaThetaFlag","flagArchaic","flag"
1781,0.5,1,5.885,1,0.71242,1,2.5636,1,3.6333,1,104.43,1,30.8514,1,6.422,1,24.2896,1,0,0
2669,1.5,1,5.9124,1,0.713118,1,2.5786,1,3.6417,1,87.676,1,30.8593,1,6.4833,1,24.2927,1,0,0
```

**Comment by dankelley** [comment]
NOTE: the output will be just whatever is in the `data` slot. In the case of the file named, there's no time there.  Also, and I consider this a bug, the `*Flag` items are in there. (I think `as.ctd()` should move them from the `data` slot into the `metadata$flags` ... that's why I call this a bug.... but maybe excel users would want that, which raises an issue of just what is best for odf/excel people, and for other users of oce ... maybe @richardsc can give some opinions on that...

**Comment by richardsc** [comment]
Hm. I think that if we're writing out to a csv, and there are flags that exist for some of the variables, there isn't a good reason *not* to write them out. It means the code needs to check if `@metadata$flags` exists, and then add columns to the data frame, but I don't see that as being too hard.

**Comment by atcogswell** [comment]
I agree, the station ID (e.g., HL_02) would be great, station ID is not an option in the ctd[['metadata']].   Yes the ISO time format is better for sure.

**Comment by atcogswell** [comment]
Agreed, better to write them to keep the header row number consistent even if the data is flagged.

**Comment by richardsc** [comment]
One comment on the format for the metadata -- what about using `=` instead of `:` to separate the field name from the field value? I say this because:

1. That's how the WOCE format is done (and in some sense this is about making something similar to that ...) **

2. It makes it a lot easier if someone (not using excel, but using python, haskell, matlab, etc) wants to parse the information. Note that there are several `:`'s in the field values (e.g. time, call sign) which would make splitting based on `:`'s a bit harder.

** Maybe we should just write a WOCE file exporter? e.g. this is the example file from [here](https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/index.htm). Note that it includes a header line for units -- which is handy, but potentially more difficult to handle programmatically (though I realize that isn't the main goal here ...):
```
CTD,20000817WHPSIOJJW
#code : jjward ctd_to_exchange.pl V1.0
#original CTD file: STA221.WCT   Mon Jul 31 14:03:27 2000
#original SUM file: p16csu.txt   Fri Jul 14 10:15:21 2000
NUMBER_HEADERS = 10
EXPOCODE = 31WTTUNES_3
SECT_ID = P16C
STNNBR = 221
CASTNO = 1
DATE = 19910901
TIME = 0937
LATITUDE = -17.5102
LONGITUDE = -150.4812
DEPTH =  3596
CTDPRS,CTDPRS_FLAG_W,CTDTMP,CTDTMP_FLAG_W,CTDSAL,CTDSAL_FLAG_W,CTDOXY,CTDOXY_FLAG_W
DBAR,,ITS-90,,PSS-78,,UMOL/KG,
      1.0,2,  26.6727,2,  36.0935,2,   -999.0,5
      3.0,2,  26.6411,2,  36.0881,2,   -999.0,5
      5.0,2,  26.6365,2,  36.0895,2,   -999.0,5
      7.0,2,  26.6447,2,  36.0905,2,   -999.0,5
      9.0,2,  26.6460,2,  36.0902,2,   -999.0,5
     11.0,2,  26.6483,2,  36.0908,2,   -999.0,5
     13.0,2,  26.6545,2,  36.0936,2,   -999.0,5
     15.0,2,  26.6520,2,  36.0918,2,   -999.0,5
     17.0,2,  26.6519,2,  36.0921,2,   -999.0,5
     19.0,2,  26.6524,2,  36.0946,2,   -999.0,5
     21.0,2,  26.6479,2,  36.0960,2,   -999.0,5
     23.0,2,  26.6394,2,  36.0965,2,   -999.0,5
     25.0,2,  26.6361,2,  36.0962,2,   -999.0,5
```

**Comment by atcogswell** [comment]
Yes, makes good sense to use = .  However, does that mean that you would then eliminate the ISO type time (Start time:  2017-04-19 17:32:43) and replace with the WOCE format which splits the date and time to 2 separate rows?  Note, the coordinate fields in the dev version of the write.ctd function are missing.

**Comment by dankelley** [comment]
Gosh, I go away from the computer for half an hour and miss all the discussion!

Here's my workplan checklist for `write.ctd`
* [ ] add lon and lat (separate lines, for easier parsing, likely no "EW" etc but rather using signs)
* [ ] use `=` to separate
* [ ] make `as.ctd()` move the "Flag" data into the place where it goes for other CTD data, and I will make `write.ctd` have an argument to control whether or not to show those flags (by default, it will show them).
* [ ] unless someone explains why, I'd put date and time in the same field. These are readable by a human, and readable by R (e.g. `as.POSIXct("2017-05-05 13:10:00")` works as expected)
* [ ] add an argument called `woce` that would be a logical, to get WOCE format ... but I don't plan on writing that immediately, since (a) I have never used `write.ctd` and (b) I've never heard of anyone else using it, and (c) it's not what these excel users will want anyhow.

PS. I hope these excel users just drop excel and use a real tool, anyway. So, for example, I don't see it as being sensible to add units to the .csv output, because it would get excel users one step closer to thinking they can do their work in excel, which is a bad thing ... how are they going to compute potential density, N^2, dynamic height, etc., and how are they going to plot a TS diagram, or a section, etc. Let's not encourage them. They should be using R, matlab, python, etc., or they should be asking collaborators to work with them. A wise man once said that making computing tools too easy can be like giving a gun to a five-year old.

**Comment by dankelley** [comment]
I just updated `develop` (commit b0193fdb2051611acbc69d084ff4356deadd80c1) and now we have (same test code as above, several comments ago)

```
$ head -12 test2.csv
```
yields
```
Source file = /Library/Frameworks/R.framework/Versions/3.4/Resources/library/oce/extdata/CTD_BCD2014666_008_1_DN.ODF 
Ship = CCGS SIGMA T (Call Sign: unknown) 
Cruise = Scotian Shelf 
Station = 8 
Longitude = -63.3175 
Latitude = 44.2675 
Depth = 156 
Start time = 2014-12-16 14:09:09 

"scan","pressure","pressureFlag","temperature","temperatureFlag","conductivity","conductivityFlag","oxygenVoltage","oxygenVoltageFlag","fluorometer","fluorometerFlag","par","parFlag","salinity","salinityFlag","oxygen","oxygenFlag","sigmaTheta","sigmaThetaFlag","flagArchaic","flag"
1781,0.5,1,5.885,1,0.71242,1,2.5636,1,3.6333,1,104.43,1,30.8514,1,6.422,1,24.2896,1,0,0
2669,1.5,1,5.9124,1,0.713118,1,2.5786,1,3.6417,1,87.676,1,30.8593,1,6.4833,1,24.2927,1,0,0
```

**Comment by dankelley** [comment]
This has questions for Andrew and Clark. I think we should settle such things so the output doesn't change later.  I think Clark can edit within this comment ... and I ask he does so. If Andrew can edit within the comment, please do so, or make a separate comment and put the info here (for clarity), remove the other document (for brevity), and remove most of this paragraph (for brevity)

Q1. Any other metadata items we should list?

Q2: What's a good order for the items?

Q3: Should we use WOCE names (upper case, underline, etc)?

**Comment by atcogswell** [comment]
Q1. I think if they want more meta-data than this then they can go to the source file and find it.

Q2. This is "my" preferred order but Clark might feel differently:

SOURCE FILE
CRUISE
STATION
START TIME
LONGITUDE
LATITUDE
DEPTH

Q3. I don't really have a preference here, maybe Clark does.

I've tried the argument that people should be using the source file and using R or another program to open, manipulate, view and export.  Some people are just married to Excel and other flat file readers, hard to change minds even though superior options are available.

**Comment by dankelley** [comment]
Sorry, guys, one more Q: should we maybe start with a header line that indicates how many more header lines there are? That's fairly common, but the downside is that it's so easily made wrong, e.g. when someone edits a .csv file ... my vote is to *not* have such a line, but to have a blank line at the end of the header, which is easy for visual inspection and easy for automatic reading. 

PS. I'll incorporate this Q, and your answers, into the previous comment and delete this and answers to it ... again, in the interests of clarity and brevity.

PPS. I've coded so `as.ctd` moves flags to the metadata but I won't push to GH until I also make `write.ctd` show the flags ... I'll be offline an hour or two now, so that will be this evening

**Comment by atcogswell** [comment]
Q4.  I'd be happy without the count line.  The space seems adequate for programming purposes.  

Thanks Dan for moving so quickly on this.  Much appreciated.

**Comment by dankelley** [comment]
I think I've done all the suggested changes, in `develop` commit a4beae127c75b2225113632ec4a4e85fc37cf59f although I'd be happy to add more, if I get more suggestions ... this is all trivial coding, and thanks, guys, for the rapid replies.

**Comment by atcogswell** [comment]
Something a little funky going on I think.  I'm getting a repeat of the Longitude and Latitude fields in the header of my csv output.  
[test.txt](https://github.com/dankelley/oce/files/979891/test.txt)

**Comment by dankelley** [comment]
Can you try again with `develop` commit 931c589dd58db63449436386f859cf96acbe0985?

It's because your data must have multiple lon and lat ... I am used to conventional data that just have a single lon and lat ... if this doesn't work, please email me your .odf file (I'll be offline for a while but will fix this up this evening if it's still broken)

**Comment by dankelley** [comment]
Also, Andrew, how come your .txt file has blank lines between everything? I don't get that in MacOS. I end my lines with `\n` (which is the unix way, and the R way) and I wonder if your OS needs some other ending thing ... I see that the data portion is coming out OK.

Actually, what the heck is going on with your file? It's full of TAB characters... maybe you cut/pasted from inside excel?

**Comment by atcogswell** [comment]
Sorry Dan.  My inexperience here, but how do I use that specific commit.

**Comment by richardsc** [comment]
@atcogswell That's the latest commit, so just do a `git pull` and rebuild.

**Comment by dankelley** [comment]
Andrew, the main reason I put in the commit number is because if you click on that in the website, you get a "diff" to the previous commit. For small bug fixes, this can be quite helpful, since it means the bug reporter can take a look at what changed in the code.

**Comment by atcogswell** [comment]
OK, did the pull then and it failed.  I sent the ODF file to Dan just a few minutes ago.

Error in names(fdf) <- paste(names(fdf), "Flag", sep = "") : 
  'names' attribute [1] must be the same length as the vector [0]

**Comment by dankelley** [comment]
Hi. I've not received the file yet. Possibly it's got filtered. Can you send to kelley.dan@gmail.com please, since my gmail seems more reliable than my work mail. Thanks!

**Comment by dankelley** [comment]
@atcogswell -- thanks for the test file.  I think this should be working in the current `develop` commit. If you agree, please close the issue. PS: some nice interleaving signatures near the bottom of the TS trace
```R
library(oce)
plotTS(read.oce("DCOR2017015.ODF"), type='o')
```

**Comment by atcogswell** [comment]
@dankelley -- Worked great, thank you very much.
