### ISSUE TITLE
Plot Section: add ability to show high-res bathymetry

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#1232]
I know Clark touched on this recently in his blog, but it might be nice to have an option to extract a higher resolution URL based bathymetry layer when plotting a section.

**Comment by dankelley** [comment]
I've started fiddling with this. I'll write ad-hoc code first, to get an idea of whether this will be useful. Then I'll think about the best way to implement.

**Comment by dankelley** [comment]
I've done some tests that are in the test suite (https://github.com/dankelley/oce-issues/blob/master/12xx/1232/1232a.R) with result as below.

I have having a bit of a mental blank on how to subset a vector with N elements between each element. Do you know a clever way to do that, @richardsc?

Anyway, so far my test interpolates to the locations of the stations (red line in snapshot) and also to put a single location between each station (blue line). I suspect that further subsampling will continue to add further wiggliness to the graph.  Having done it this way, I'm not too convinced that this method of subsampling depths at points between the stations makes sense. Maybe we should let the user specify the number of *total* points, for use in `approx`?  But then we could easily miss details where stations are nearby (which is why my idea is going along the lines seen in the code).

I'm going to put the present code along with its results; otherwise, the code at the oce-issues repo can drift from the diagram, and this graph won't make sense.
```R
library(oce)
data(section)
lon <- section[["longitude", "byStation"]]
lat <- section[["latitude", "byStation"]]
lonRange <- range(lon, na.rm=TRUE)
latRange <- range(lat, na.rm=TRUE)
resolution <- 4 # minutes

## get grid that's a few grid points larger than data range
d <- 4 * resolution / 60
W <- round(lonRange[1] - d, 4) # 4 digits means 0.0001deg or 10m.
E <- round(lonRange[2] + d, 4)
S <- round(latRange[1] - d, 4)
N <- round(latRange[2] + d, 4)
topoFile <- download.topo(west=W, east=E, south=S, north=N, resolution=resolution)
topo <- read.topo(topoFile)

## double-sample lon and lat (awkward -- must be a cleaner way that
## will generalize better)
n <- length(lon)
m <- rbind(lon[-n], lon[-n]+diff(lon)/2)
LON <- c(as.vector(m), lon[n])

m <- rbind(lat[-1], lat[-1]+diff(lat)/2)
m <- rbind(lat[-n], lat[-n]+diff(lat)/2)
LAT <- c(as.vector(m), lat[n])

b <- topoInterpolate(lon, lat, topo)
B <- topoInterpolate(LON, LAT, topo)

if (!interactive()) png("1232a.png", width=7, height=5, unit="in", res=150, pointsize=10)
plot(section, which="salinity", xtype="longitude")
lines(lon, -b, col='red')
lines(LON, -B, col='blue')
if (!interactive()) dev.off()
```

![1232a](https://cloud.githubusercontent.com/assets/99469/26761937/f79944da-490e-11e7-9e5a-d03eb1e8f3d3.png)

**Comment by dankelley** [comment]
It seems as though I look at this once a week.  Today's update, in `1232b.R` in the issues repo, which at the moment is as given below (with results shown) seems to be reasonable. Unless someone objects (on my method, or the slowness of my plan), I will write some code to provide an interface to this, sometime during the next 7 days.
```R
## 1232b.R: mesh developed by interpolating on distance
## FIXME: decide on the factor in line 29, defining "N".

resolution <- 4                        # grid resolution [minutes]

library(oce)
data(section)
lon <- section[["longitude", "byStation"]]
lat <- section[["latitude", "byStation"]]

distance <- geodDist(lon, lat, alongPath=TRUE)
resolutionKm <- resolution / 60 * 111  # km



lonRange <- range(lon, na.rm=TRUE)
latRange <- range(lat, na.rm=TRUE)

## get grid that's a few grid points larger than data range
d <- 4 * resolution / 60
W <- round(lonRange[1] - d, 4) # 4 digits means 0.0001deg or 10m.
E <- round(lonRange[2] + d, 4)
S <- round(latRange[1] - d, 4)
N <- round(latRange[2] + d, 4)
topoFile <- download.topo(west=W, east=E, south=S, north=N, resolution=resolution)
topo <- read.topo(topoFile)

span <- geodDist(W, S, E, N)
## n = for approx
N <- 2 * round(span / resolutionKm)
n <- length(lon)
LON <- approx(1:n, lon, seq(1, n, length.out=N))$y
LAT <- approx(1:n, lat, seq(1, n, length.out=N))$y

B <- topoInterpolate(LON, LAT, topo)

if (!interactive()) png("1232b.png", width=7, height=5, unit="in", res=150, pointsize=10)
plot(section, which="salinity", xtype="longitude", ztype="image")
lines(LON, -B, col='blue', lwd=1.4)
if (!interactive()) dev.off()
```
![1232b](https://user-images.githubusercontent.com/99469/27012099-2168b5c0-4ea0-11e7-8ab6-bf57e636b4c4.png)

**Comment by atcogswell** [comment]
Looks great Dan.  Thanks for spending so much time on this.  Very nice addition.

**Comment by dankelley** [comment]
Oh, it's not been much time -- more like 10 minutes, chopped into two chunks but spread out over weeks. My present thinking is that the UI will be that the `showBottom`  argument of `plot,section-method` will gain the new choice of being a `topo` object, and that the Examples portion of the docs recovered with `?"plot,section-method"` will state how to set up such an object. (Possibly `download.topo` should permit the first argument to be a `section` object, making things easier.) 

TBH, I am still not exactly sure on how to interpolate within that `topo` object.  What I've done in the [second-previous comment](https://github.com/dankelley/oce/issues/1232#issuecomment-307635472) to define `LON` and `LAT` is just a trial, and I don't like it. I may end up writing code that steps between station locations, retaining those locations but also putting in intermediate locations, on a certain spacing.  The `approx` method in the second-previous comment](https://github.com/dankelley/oce/issues/1232#issuecomment-307635472) doesn't do that, because it does not retain the station locations. I don't actually see how to do this in a vectorized way in R, and I prefer not to write a loop for it, so it may be time for a bit of C.

**Comment by dankelley** [comment]
I think this works now.  It's now possible to read in a `topo` object, and supply that as the bottom. I won't detail how this works, because it is documented (i.e. if the new doc is unclear, I hope someone will post a note here so I can edit it). The example4 for `?"plot,topo-method"` is now as follows, and it makes as shown below. Seem OK to @atcogswell and @richardsc ?

(Note: the downloaded topo file gets cached for future use. Since "disk" is cheap, a person might want to download a bigger dataset instead of what I did here, which was to download one that's narrowed to the actual dataset. Alternatively, one could discover the limits of the required bathymetry from the section object, as explained in a comment above.)

```R
library(oce)
data(section)
f <- download.topo(west=-80, east=0, south=35, north=40, resolution=4)
t <- read.topo(f)
plot(section, which="SA", xtype="longitude", ztype="image", showBottom=t)
```
<img width="924" alt="screen shot 2017-06-24 at 11 18 32 am" src="https://user-images.githubusercontent.com/99469/27509299-a638e00c-58cf-11e7-9231-d3327c4246bb.png">
