### ISSUE TITLE
Null value not being recognized for ODF file

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1236]
This is just a random ODF file I had on my machine that I used to test the latest code changes (which seemed to work), but I did notice that it appears the `NULL` value substitution doesn't seem to be working. Note that the ODF file has e.g.:
```
PARAMETER_HEADER,
  TYPE='SING',
  NAME='East (true) Component of Current',
  UNITS='m/s',
  CODE=EWCT_01,
  NULL_VALUE=-99.00,
```
but when I plot I see the -99 values which should have been replaced with NAs.

I'll attach the file here (it's public anyway). Note I had to add the `.txt` extension to get it to attach.
[MADCP_98911_1281_0505-102_7200.ODF.txt](https://github.com/dankelley/oce/files/981276/MADCP_98911_1281_0505-102_7200.ODF.txt)

**Comment by dankelley** [comment]
Thanks. I think this is fixed in `develop` commit 113f4f1fe882c8e595621a76753a52973906f01c

I put this new file into `tests_private/local_odf_files` with the `.txt` removed, so now it's part of the developer's test suite. I also added to that test suite a check that the minimum `temperature` exceeds -5C (if there is a `temperature` in the data) and that the minimum `u` exceeds -5m/s (if there is a `u` in the data). So, I'd say the problem (a) is fixed and (b) cannot come back, so long as we do
```
cd tests_private
rm odf_*.out
make odf_01.out odf_02.out odf_03.out
```
before releasing.  (You can also clean away all the `.out` files, and it will test lots of non-ODF files as well, if you have your `/data` set up in a certain way.)

**Comment by dankelley** [comment]
PS. the code does not handle different `NULL_VALUE`s for different data columns. I guess that could get coded in, at some point. I don't know if this matters for any files I've ever seen, though; the only thing that ever seems different is the time column and what kind of whacky dataset would have time entries that are missing (you either have time or you don't, I reckon).

**Comment by richardsc** [comment]
Oh, thanks! I just sat down with a coffee to have a look at this, but I guess even I don't get up early enough to get the worm ... :)

**Comment by dankelley** [comment]
Well, I try hard to stay in bed past 0530 but I seldom succeed.
