### ISSUE TITLE
Units for variable names in write.ctd()

### ISSUE THREAD

**Issue by jspmccain** [dankelley/oce#1244]
Just to make the csv files produced more modular, I think including units with the variable names might be helpful for the `write.ctd()` function. Or, including the variable names as part of the metadata header for csv files might work as well.

This might work to insert right about the last "cat()" function in write.ctd()
```R
for(var_name in 1:object@data %>% names() %>% length()){
  var_name_i <- names(object@data)[var_name]
  units_i <- object@metadata$units[[names(object@data)[var_name]]]$unit %>% as.character()
  cat(paste("Units for", var_name_i, "are", units_i, "\n", sep = ""), 
      file = con)
}
```

**Comment by dankelley** [comment]
We've had some discussion of writing for a woce-exchange format (which has a way of indicating units) and that's the way to go. It will be a slight bit of fiddling, because it is very particular about how units are expressed. (Merely making units that a human can recognize is not useful if code is to be able to parse the files.)  I'll do this, at some point. I'll start with just a few simple things (temperature, salinity, pressure, etc). There a lot of unit types.

This has never really come up seriously before because people don't tend to work in spreadsheets.  (Encouraging people to use spreadsheets is a poor idea, because this goes counter to the code-oriented methods of reproducible science. Also, very few interesting algorithms have been coded for spreadsheets. Just for an example, the seawater-properties calculations of the `GSW-R` package spread over nearly 11 thousand lines of C. And those are some pretty dense lines, with on average about 40 characters per line ... imagine entering such things into excel formulae)

**Comment by jspmccain** [comment]
I completely agree re: discouraging spreadsheet use. Lots of tools are friendly with .csv, but not so many are friendly with .odf. So I was just thinking if an odf is converted to another format (I would be agnostic of csv vs woce-exchange etc.), then how would these be encoded in the file. Sounds like you've thought a lot more than I have about this though! Thank you!

**Comment by dankelley** [comment]
As a note for when I come back to this (likely on the weekend), below is an example of what is typically shown in WOCE exchange `.csv` files. (However, I am not sure this is the format we should be using.)

```
#DEPTH_TYPE      : COR
#EVENT_CODE      : BO
NUMBER_HEADERS = 10
EXPOCODE = 90CT40_1
SECT = A03
STNNBR =     3
CASTNO =     1
DATE = 19930923
TIME =  2222
LATITUDE =   36.8758
LONGITUDE =   -8.5263
DEPTH =   202
CTDPRS,CTDPRS_FLAG_W,CTDTMP,CTDTMP_FLAG_W,CTDSAL,CTDSAL_FLAG_W,CTDOXY,CTDOXY_FLAG_W,
DBAR,,ITS-90,,PSS-78,,UMOL/KG,,
      1.0,2,  16.5319,2,  36.0798,2,   -999.0,9
      3.0,2,  16.5472,2,  36.1657,2,   -999.0,9
      5.0,2,  16.5034,2,  36.1275,2,   -999.0,9
      7.0,2,  16.3897,2,  36.1212,2,   -999.0,9
      9.0,2,  16.3307,2,  36.1237,2,   -999.0,9
     11.0,2,  16.1665,2,  36.1161,2,   -999.0,9
     13.0,2,  16.1342,2,  36.1154,2,   -999.0,9
```

**Comment by dankelley** [comment]
Another link, for when I return to this: at #1231 we've got a comment that holds the following link to a description of the woce data format: https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/exchange/index.htm
but note that the sample file here is not the same as the file I quote on the previous comment (look at the comma at the end of the header line starting with `CTDPRS`), *even though* the file I quote above comes from https://cchdo.ucsd.edu/cruise/90CT40_1 which is a well-known repository.  The bottom line is that even with published formats, there are often small formatting disparities that must be handled.

**Comment by dankelley** [comment]
I've got something at least halfway working in the `develop` branch. An example and some notes are below.
```R
> library(oce)
Loading required package: gsw
> data(ctd)
> write.ctd(ctd, file="test.cnv", format="whp")
> d <- read.ctd("test.cnv")
> plot(d)
> summary(d)
CTD Summary
-----------

* Start time:          2003-10-15 11:38:00
* Station:             2
* Location:            44.684N  63.644W 
* Water depth:         44.141
* Data

                             Min.   Mean   Max.   Dim. OriginalName
    SCAN                     130    220    310    181  SCAN        
    pressure [dbar]          1.48   22.885 44.141 181  CTDPRS      
    DEPTH                    1.468  22.698 43.778 181  DEPTH       
    temperature [°C, ITS-90] 2.9176 7.5027 14.23  181  CTDTMP      
    salinity [PSS-78]        29.916 31.219 31.498 181  CTDSAL      
    FLAG                     0      0      0      181  FLAG        

* Processing Log
    - 2017-05-22 10:33:47 UTC: `create 'ctd' object`
    - 2017-05-22 10:33:47 UTC: `read.ctd(file = "test.cnv")`
    - 2017-05-22 10:33:47 UTC: `inferred water depth from maximum pressure`
```

and here's the first 22 lines of the file.
```
CTD,20031015divINSwho
NUMBER_HEADERS = 10
EXPOCODE = UNKNOWN
SECT = UNKNOWN
STNNBR = Stn2 
CASTNO = 1
DATE =  20031015 
TIME =  1138 
LATITUDE =  44.6843
LONGITUDE =  -63.6439
DEPTH =    NA
SCAN,time,CTDPRS,DEPTH,CTDTMP,CTDSAL,FLAG 
,S,DBAR,M,ITS-90,PSS-78, 
130,129,1.48,1.468,14.2176746972073,29.921,0
131,130,1.671,1.657,14.2230721061401,29.9205,0
132,131,2.052,2.036,14.2216727778983,29.9206,0
133,132,2.243,2.225,14.2187741693973,29.9219,0
134,133,2.624,2.603,14.2232720101746,29.9206,0
135,134,2.672,2.65,14.2297688912975,29.9164,0
136,135,3.005,2.981,14.1886886121977,29.9339,0
137,136,3.196,3.17,14.1089269024127,29.9667,0
138,137,3.482,3.454,14.1363137551459,29.9519,0
```

Notes:
1. I am not translating `time` because I don't think that normally appears in WHP files.
2. I am not inventing an expocode (which is *required* for WHP, but certainly not for a `.cnv` file)
3. I am not copying over a lot of metdata ... again, this is not normally part of a WHP file.

It might be worth doing some tests with other datasets. I think this issue should be closed (although it's up to @jspmccain to do so) because the request stated in the title has been addressed. It can always get reopened for new units that prove to be missing.

A final thought: it's not clear to me how useful this is, and I am not too keen on spending a lot of time translating oce data into csv files. If the idea is to make things easy for scientists who want to use excel, then I feel they should instead learn how to work with real tools. If the idea is to make things easy for the public, then I think graphs are enough ... and a surprising number of people are learning R anyway, so they could use oce if they wanted. (I've seen undergrads pick up R skills in 15 minutes, and most learn it in first year now anyway ... this means a high school graduate could pick it up in an hour).

**Comment by jspmccain** [comment]
Sorry about not closing the issue - still new to github workflows and didn't realize that even existed!

I completely agree about the excel-use challenge, but I didn't bring it up to help that use case. If I wanted to do some analysis in another language, like Julia or Python, uploading and converting ODF files seems like a pain. Obviously a user of Julia or Python could convert them with R though, but broadly I think it's useful to present data in a more widely accessible way.

I appreciate your thoughts and help on this!

**Comment by dankelley** [comment]
Re putting into a format for Julia, Python etc -- that's a great point. It would be nice if DFO could create a convertor from ODF to something else, and there have been some discussions of that, actually.

**Comment by jspmccain** [comment]
Maybe something like an oceanographic [feather](https://blog.rstudio.org/2016/03/29/feather/)!

**Comment by dankelley** [comment]
Yeah, except that a lot of data are not well expressed as data frames. (The very first CTD handling code in oce used data frames, but it did not take too long to see that this system is quite limited, e.g. ADCP data are better expressed as matrices, and aggregating ctd stations into section objects requires something else entirely ... the answer is to use a "list"...)
