### ISSUE TITLE
Check if anything that has a .Call or a .C has all vectors of the same length

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1250]
This came up in #1248 and #1249.

**Comment by dankelley** [comment]
Hm. I now see how `sfm_enu` (in `src/sfm_enu.c`) was designed to work. It has two integers, one for the number of sampling times (call that `np`, say), and another for the length of `heading` (etc). And it does a recycling rule within itself ... but I don't like that recycling rule because (as written) it leads to a lot of duplicated code. Also, if the machine lacks the memory to extend `heading` (etc) to length `np`, then I doubt the machine will be able to e.g. plot data after rotation. Therefore, I am going to change the `sfm_enu` C function, and also change the calling R code. I suppose this could (like any code alteration) cause problems, but I am inclined to think that it's something that should be done, to make the code more maintainable. (Note that we wasted a lot of time yesterday because, effectively, the code wasn't clear enough to me to see the potential problem.)

**Comment by dankelley** [comment]
I feel this is addressed now. Although I had suggested that I would close this, I prefer that @richardsc does that ... probably after doing the valgrind test that I mention at the end of the commit note:

commit ba4e26dca6d14ed81f725b480161f3017c0a6076
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Fri May 19 11:20:12 2017 -0300

    sfm_enu conversion more robust
    
    There was a problem if the user had not supplied pitch, heading and roll
    as vectors of length equal to the number of sampling times.  (In the
    code I call the number of sampling times as "np", thinking "number of
    profiles" as for 'adp' type, but I use the same variable name for 'adv'
    type also.)
    
    The problem is solved -- at the R level -- by lengthening heading, pitch
    and roll as needed.
    
    I also tweaked the C code in src/sfm_enu.c by making it expect all
    vectors to be of the same length. Previously, the code was recycling
    pitch, heading and roll if required, but this scheme was not being used
    correctly in the R code (which proves it was a bad scheme) and it
    entailed code duplication that is dangerous (e.g. a developer might
    modify one block but forget to modify it's doppelganger).
    
    I have built and tested oce but this will not really exercise this
    change. The way to exercise the change is to use the R code from the Rmd
    code that is mentioned in https://github.com/dankelley/oce/issues/1250
    and to run it with valgrind, i.e.
    
        R -d valgrind --no-save < code.R
    
    to see if allocation or access errors are reported.

**Comment by richardsc** [comment]
I did as suggested above with the valgrind checks, and I think everything looks ok. Well, to be honest I'm not too sure since it does say that some bytes were `definitely lost` but I feel like I've seen similar on code that I know was working fine.
```
==6516== 
==6516== HEAP SUMMARY:
==6516==     in use at exit: 228,813,632 bytes in 53,687 blocks
==6516==   total heap usage: 888,076 allocs, 834,389 frees, 2,764,283,786 bytes allocated
==6516== 
==6516== LEAK SUMMARY:
==6516==    definitely lost: 360 bytes in 1 blocks
==6516==    indirectly lost: 0 bytes in 0 blocks
==6516==      possibly lost: 0 bytes in 0 blocks
==6516==    still reachable: 228,813,272 bytes in 53,686 blocks
==6516==         suppressed: 0 bytes in 0 blocks
==6516== Rerun with --leak-check=full to see details of leaked memory
==6516== 
==6516== For counts of detected and suppressed errors, rerun with: -v
==6516== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by richardsc** [comment]
I'll close, and if @dankelley is concerned he can re-open to deal with it.

**Comment by dankelley** [comment]
Thanks -- I think it would have listed an error, if it had a real one. Let's leave this closed, then.
