### ISSUE TITLE
odf to netcdf conversion

### ISSUE THREAD

**Issue by jspmccain** [dankelley/oce#1251]
Are there thoughts on writing a function to convert an odf file to netcdf? I'm looking to do a bunch of conversions, considering writing a function to do it myself but wanted to check in.

**Comment by dankelley** [comment]
I think this would be something for the DFO people who work on ODF, since they already have parsers that obey the format fully and precisely. I wouldn't be surprised if they already have such a tool.

**Comment by richardsc** [comment]
I agree with @dankelley that it could be worth checking with the ODIS folks to see what ODF2*** tools they have.

As with the csv discussion (e.g. #1244) the issue isn't so much about writing to another format (I've recently coded a write-to-netcdf function that I'd be happy to share), but whether spending the time to write a general solution is worth the time that will be saved by yourself or others in reading it. In other words, if we create an `oce` function to output netcdf, we really should either:

1. Choose a netcdf schema that is already in use and documented. An example could be the Argo format, but this is sort of a specific format and I wouldn't recommend that we try and use it as a general output data format, or

2. Decide on our own export format, and document the schema.

Netcdf is definitely better than csv etc as an export format, even if just because it can be easier to include relevant metadata (e.g. units), but it still will end up being YADF (yet another data format) unless it is documented.
