### ISSUE TITLE
separating air and seawater temperatures data from intertidal loggers

### ISSUE THREAD

**Issue by jellrich** [dankelley/oce#1257]
I have intertidal data loggers (HOBO Pendant Logger, Model: UA-002-64; Onset Computer, Pocasset, Massachusetts, USA) that have continuously measured temperature every 30 minutes over several years. Consequently, each logger contains data on air temperature (measured when loggers were emerged) and seawater temperature (measured when loggers were submersed). 

Is it possible to separate the air temperature data and the seawater temperature data that come from each logger by using the “oce” package? Is there an alternative way to do the separation in R?

Thank you very much.

**Comment by richardsc** [comment]
Hi @jellrich -- thanks for posting.

For what you're looking for, from a programmatic perspective (i.e. the `oce` package specifically), the answer is "no" -- there is no automatic way of separating air and water temperature.

That's not to say it is impossible to cook up a scheme to do this -- really it depends on the data. For example, if you had loggers that also measured pressure then you would know precisely when they were in air because you would record atmospheric pressure instead of the tidal height. I have used such combined "pressure-temperature" sensors in the past for such intertidal work, because of this issue.

If you don't have pressure, then it gets a bit trickier. In cases where the water temperature and the air temperature are different, you might be able to cook up a scheme that looks for sudden shifts in temperature as the sensor comes out of the water. However, that might not work if the air and the water are at similar temperatures (as is often the case in shallow/intertidal zones). 

I don't know of any other techniques. If the data were higher frequency, I could envision a scheme that looks for changes in the spectra of the temperatures recorded in air vs water, which would indicate different fluid environments (and therefore a different sensor response) that might help distinguish them, but 30 minutes samples is probably too long for this.

**Comment by jellrich** [comment]
Thank you very much for your reply richardsc,
I'll think about potential schemes and consider combined pressure-temperature sensors for the future.

**Comment by dankelley** [comment]
@jellrich if you want to send data to @richardsc and/or me, I imagine we'd both be happy to have a look to see if we can cook up a scheme. It will depend on time of year and other factors. Possibly it will be quite easy, or possibly it will be something complex enough to justify a publication of its own.

**Comment by dankelley** [comment]
I'm going to close this, because (a) the discussion has ceased, (b) further communications are likely to be outside the domain of `oce` public development.
