### ISSUE TITLE
Seawater potential density anomaly calculation from cell-based data formats

### ISSUE THREAD

**Issue by flopesdematos** [dankelley/oce#1260]
I’m trying to calculate the seawater potential density anomaly using data in ASCII format (but I can use rasters if necessary), one with potential temperature and other with salinity, but `swSigma0` give the following error: 

> Error in as.double(l$salinity) : 
  cannot coerce type 'S4' to vector of type 'double'

There is a way to do it for each cell in order to produce a raster with the same attributes of the two I used but with the density values instead?

The code I used: 

```
library(raster)
library(oce)

lst <- list.files(path = "~/Desktop/", pattern = "asc", full.names = TRUE)
lst

# create rasterStack
myExpl <- stack(lst)  # making a raster object
proj4string(myExpl) <- CRS("+proj=longlat +datum=WGS84")

sal <- myExpl$salinity
temp <- myExpl$temperature

sigma <- raster(swSigma0(salinity = sal, temperature = temp, pressure = 0))

```

Thank you.

**Comment by dankelley** [comment]
Thanks. Could you send me a sample data file (to my private email address, the one you used earlier today), so I can check?

Also, what version of oce are you using? (I will advise you to build from github, if I have to make changes in `oce`.)

Thanks.

**Comment by dankelley** [comment]
I've never used `raster` before, but I just tried and so I think you'll need to use e.g.
```R
sal <- as.array(myExpl$salinity)[,,1]
temp <- as.array(myExpl$temperature)[,,1]
```
to get data in a format that `oce` can use. (It's not set up to use `raster` objects.)

I suppose I could make `oce` do this automatically, but I'd prefer not to do that, because there are a *lot* of functions in `oce` that might possibly need to be changed, and nobody has asked for `raster` support before, so it would be hard to justify the effort of coding, documenting and (later on) maintaining, especially since the conversion method suggested above is quite simple.

**Comment by flopesdematos** [comment]
Dear Dan,

Thank you, it worked perfectly. I agree, the solution is simple and effective and no changes in `oce` is justified. 

Thank you for your quick reply!
