### ISSUE TITLE
the vignette should explain a how to create new classes

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1290]
An offline user question made me think that a few paragraphs could help people in this matter.

**Comment by dankelley** [comment]
Hm. I wrote a new section for the vignette and now ... well, how the *heck* does a user get that vignette? Something may be changed, because I sure can't see how to get it. I'll look at other packages to see if they use a trick to make the vignette be visible.

**Comment by dankelley** [comment]
Oh, I see, the vignette just doesn't get built and installed by Rstudio (even if you use the GUI tool to indicate that this is to be done). 

To see the vignette, build the source (which will make a tarball that contains the vignette) and install that. Or, for quicker looks, clone the source, at the "develop" branch, then use Rstudio to build it, then open `vignette/oce.Rmd` in RStudio and click the "knit" icon.

I'd be very interested to read any suggestions for improving the text. I wrote it really quickly and haven't even passed my eyes over it a second time. Still, my plan is to close this issue on Saturday morning, unless users post comments below arguing that I keep it open. (My policy is to close issues as soon as I can, because I use the open-issue list as a to-do list.)

**Comment by blongworth** [comment]
I'm just starting with ode, intending to plot sections from the GLODAP data set:

http://cdiac.ornl.gov/oceans/GLODAPv2/

I'm working on importing a subset of the GLODAP csv table into oce section objects. I think I can probably figure it out, but maybe a section in the vignette about getting data into section objects would be appropos. Alternatively, this dataset is available in ODV format if that makes an import example easier.

No problem to close this out if it doesn't fit with this issue. I'd be happy to open another issue and/or provide some text for the vignette when I figure it out. Sorry for posting without looking into it fully; just wanted to get this in since you're planning on closing this tomorrow.

**Comment by dankelley** [comment]
This doesn't really fit with the title of the present issue. I am very keen on linking issue content (and code change) to titles, and therefore I think your best plan would be to open a new issue with a title something like "how to create a section object from a .csv file" or something. Of course, it makes sense to spend an hour or so trying, before posting an issue. Your issue will be most helpful if you include 5 or so rows of the csv file, so someone can offer specific code without having to engage in a lot of back-and-forth through comments or email. 

Thanks!

**Comment by blongworth** [comment]
Thanks Dan, will do.

**Comment by dankelley** [comment]
Closing as per plan, extended in respect of comments.
