### ISSUE TITLE
read.odf() not catching QC flags

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1291]
ODF file sent privately in an e-mail.

**Comment by dankelley** [comment]
Thanks. I see that this file has a type of quality code that always seems to appear to the right of actual data.  Presently, `read.odf` looks for e.g. `QQQQ_PSAL` coming to the right of a column named `PSAL`, and it takes the pair as Salinity and its flag. But in the file you sent, I see as below. I'll code it so that this gets accepted, also.

When I execute
```
grep " CODE=" (FILENAME DELETED)
```
I get as follows.
```R
  CODE='SYTM_01',
  CODE='CNTR_01',
  CODE='QCNTR_01',
  CODE='PRES_01',
  CODE='QPRES_01',
  CODE='TEMP_01',
  CODE='QTEMP_01',
  CODE='CRAT_01',
  CODE='QCRAT_01',
  CODE='TEMP_02',
  CODE='QTEMP_02',
  CODE='CRAT_02',
  CODE='QCRAT_02',
  CODE='ALTB_01',
  CODE='QALTB_01',
  CODE='PSAR_01',
  CODE='QPSAR_01',
  CODE='OXYV_01',
  CODE='QOXYV_01',
  CODE='OXYV_02',
  CODE='QOXYV_02',
  CODE='FLOR_01',
  CODE='QFLOR_01',
  CODE='FLOR_02',
  CODE='QFLOR_02',
  CODE='PHPH_01',
  CODE='QPHPH_01',
  CODE='UNKN_01',
  CODE='QUNKN_01',
  CODE='UNKN_02',
  CODE='QUNKN_02',
  CODE='LATD_01',
  CODE='QLATD_01',
  CODE='LOND_01',
  CODE='QLOND_01',
  CODE='PSAL_01',
  CODE='QPSAL_01',
  CODE='PSAL_02',
  CODE='QPSAL_02',
  CODE='POTM_01',
  CODE='QPOTM_01',
  CODE='POTM_02',
  CODE='QPOTM_02',
  CODE='SIGP_01',
  CODE='QSIGP_01',
  CODE='SIGP_02',
  CODE='QSIGP_02',
  CODE='DOXY_01',
  CODE='QDOXY_01',
  CODE='DOXY_02',
  CODE='QDOXY_02',
  CODE='CNTR_02',
  CODE='QCNTR_02',
  CODE='QCFF_01',
```

**Comment by dankelley** [comment]
I think this may work now in the "develop" branch, commit 48181f3b5b6fe0c330de4072e41aefe83107f6c5

For your test file, I find that
```R
d <- read.ctd("PRIVATEFILE.ODF")
d2 <- handleFlags(d)
```
shows that all the `salinity` values are coded with bad values:
```R
> table(d[["salinityFlag"]])

  3   4 
313  52 
```
but that `salinity2` is all good:
```R
> table(d[["salinity2Flag"]])

  1 
365 
```

so maybe you want to do
```R
d <- read.ctd("PRIVATEFILE.ODF")
d[["salinity"]] <- d[["salinity2"]]
d[["salinityFlag"]] <- d[["salinity2Flag"]]
```
and possibly similar for temperature, if the comments in the file state that it is also bad. (Normally it's conductivity that is bad and hence salinity).

**Important:** It would help hugely if you could do e.g.
```R
head(data.frame(d[["metadata"]]$flags))
```
and also
```R
head(data.frame(d[["data"]]))
```
and compare with what you see in a text editor. This will only take 5 or 10 minutes, but it's better that you do it, than for me to do it, since you're likely to have sharper eyes. Doing this is the only real way to check the new code. You might want to try it on a couple of files, and to tell `head` to print more lines.

Meanwhile, I'll run my torture-test, which contains something like 1000 ODF files, so it takes quite a while.

**Comment by clayton33** [comment]
Looks good, thanks.
