### ISSUE TITLE
Adding a scale bar and a compass indicating north or south in oce plotStick

### ISSUE THREAD

**Issue by mfundo2858** [dankelley/oce#1297]
*Instructions: use this template, if it seems appropriate. For example, it only
applies to bug reports, so if you are suggesting a new feature, you should just
delete all the contents and write whatever you would like to write. If you have
private data that are required for your example, you may email them to the
developers, who will pledge to not to share them. Please delete this block
before submitting the issue.*

### Short summary of problem

*I have a stick plot of wind speed and direction that i did using oce package in R, now I want to add on it a legend with a scale bar and compass with north or south direction so that the reader can see where range of the u and v components of the plot and the directions of such components*

### Details (optional)

*Replace this line with a longer description, if the above seems insufficient.*

### What you did

*Replace this line with a description, with code if appropriate*

### What you expected to happen

*Replace this line with a description, perhaps including diagrams.* 

### What happened

*Replace this line with a description, perhaps including diagrams.* 

### How urgent is this?

*Replace this line with an indication of how pressing this is. Can you wait a few days?*

### Output from sessionInfo()

*Replace this line with the output from sessionInfo().*

**Comment by dankelley** [comment]
Oce is not set up to do that with arguments to the `plot*` functions, but it can be done directly by the user, because the user has set a value for `yscale` in the `plotSticks` call (or used the default value).  Try using `par("usr")` to learn about the plot space. Then use basic R commands to draw whatever you want, wherever you want it. R has commands for drawing text, drawing lines, drawing arrows, drawing symbols, etc. Use them, based on what you know about your particular graph -- including where on the graph there is space to draw whatever it is that you want to draw.

You've had several postings lately that have not elicited responses. If you've been trying to get these things done quickly, then I apologize, and hope you realize that the best way forward may be to find a local R user to chat with, so you can deepen your understanding in minutes, not weeks.

With oce, as with most packages, the answers lie in the documentation, and any extension will normally require some basic R skills.  For example, it is a basic R skill to know that `par("usr")` tells you about the user-space for an existing plot, and that (for example) `lines` can be used to draw lines on that plot ... and just a few things like this will let you do whatever it is you need with `plotSticks` and with plotting functions from thousands of R packages. Oce uses so-called "base graphics", so you use base-graphics functions; some packages use `ggplot2` or other schemes, and for them a user needs an additional set of skills.

I've written a long comment because I will not be available to add further comments. I hope this helps you to find a path forward on the three Oce issues you've opened lately, and with other things that you may find in other R packages. Once you learn the basic skills, things like this will seem very easy to you, and at that point, you'll be the local user who helps others 😄

**Comment by dankelley** [comment]
**Standardized comment.** This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.
