### ISSUE TITLE
Nortek Aquadopp HR profiler: read extended velocity data (.hr2)

### ISSUE THREAD

**Issue by LennertSchepers** [dankelley/oce#1299]
When the Extended Velocity Range (EVR) is selected, the Nortek Aquadopp HR profiler measures an additional single measurement cell located 1/3 of the distance into the profile, with 3x the velocity range. 
See http://www.nortek-as.com/lib/technical-notes/tn-028-extended-velocity-range

This is used internally to detect and correct for phase wrapping, but it's still usefull to check these data when you suspect phase wrapping (see for example this discussion: http://www.nortek-as.com/en/knowledge-center/forum/hr-profilers/351501808).

When you export the data in the Aquapro software, the extended velocity measurements are stored in an additional .hr2 file.
Is it also possible to access these data with the oce-package?

PS: so far, I didn't find any documentation on how this is stored in the aquadopp file :s

**Comment by dankelley** [comment]
Sorry, this is new to me.  I like the idea (a lot) but have not seen this referred to in the document I used to set up oce, so I'm pretty sure oce doesn't handle this yet.  Before considering handling it, we'd need to get docs from nortek on the format (i.e. which bytes indicate whether this mode is functioning, where the extra information is stored, etc etc). We'd also need a sample file, to check, because altering code that works through binary files a byte at a time is a risky business with a check.

**Comment by dankelley** [comment]
The discussion of this issue seems to have ended, and the developers will likely close it soon, since it seems to have been addressed. This goes against the usual oce policy of hoping that reporters will close issues, so this is really a request to the original reporter to either (a) close the issue or (b) indicate that further action is desirable.

Thanks!!

PS.  This is a standardized reply.
