### ISSUE TITLE
adpEnsembleAverage() can't handle na.rm=TRUE

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1328]
With current behaviour, a single NA in a sequence of averaged ensembles will cause the entire average to be NA.

**Solution:** there should either be a `...` arg in the `lapply()` calls to `mean()`, or `na.rm` should be added as an explicit argument.

I'm about to push a commit that has both -- i.e. `na.rm=TRUE` *and* a `...` argument (which doesn't add a lot of functionality beyond the `trim` arg in `mean()`, but oh well). @dankelley let me know if you think this is the best approach, and if not feel free to adjust.

Sorry for not doing this on a separate branch ...

**Comment by richardsc** [comment]
See commit 1fa6df7a

**Comment by dankelley** [comment]
That looks perfect, thanks. Also, no worries on a direct commit to "develop". I always do a `git pull` before I start coding anything, and the issue-assignment process makes it exceedingly unlikely that the two of us would be working with the same complex chunk of code at the same time.

I think 1327 is okay now; maybe you could check sometime during the upcoming week, since I think you use argo more than I do. (I was going to use one for an assignment question, but I dropped the idea.)

**Comment by dankelley** [comment]
Is this fixed? Should I be doing something to help in making a decision regarding closure?

**Comment by richardsc** [comment]
It's fixed. I should have labelled as "request review" but it looks like you did that anyway.

Closing.
