### ISSUE TITLE
mapPlot() 'type' arg has awkward completions

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1335]
It handles both `type="polygon"` and `type="p"`, which is awkward with respect to completion.  I'm not sure whether I really think it's ok to change now, though, since I think it's been this way for a while.

I wonder whether the other devs have any thoughts on this.

**Comment by richardsc** [comment]
Interesting. I almost never use `mapPlot()` except with the default (`type="polygon"`) because I'm almost always plotting a coastline *before* adding points, etc.

From my testing it appears that the argument matching will always choose "p" unless "polygon" is typed in full. I admit it is awkward (and a bit inconsistent with the "regular" R way), but I agree that I wouldn't change it now.

**Comment by dankelley** [comment]
Agreed. We'll keep it as it is, unless it leads to bugs or warnings (NOTEs) on a build machine. (We are not supposed to have NOTEs on anything that gets sent to CRAN.) I'm closing this.
