### ISSUE TITLE
colormap() should also return a function to lookup colours

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1374]
I was helping a student and realized that it can be quite tricky to synch colours up with the colourmap. It's fine if you give the "z" arg, but if you don't know the data beforehand, you've got to do some tricks.

Maybe I'm too tired to remember another way, but what I'd like to see would be e.g.
```R
cm <- colormap(zlim=range(z))
plot(x, y, col=cm$lookup(z))
```
for (x, y, z) data.

Perhaps one of the other devels will tell me there is an easy way to do this already.

**Comment by richardsc** [comment]
No, I don't think there is another easy way to do this. The proper use of `colormap()` requires (at some point, at least for scatter plots) actually knowing what the data are. So, you don't make the colormap until you know what `z` is. As an example, if I wanted to plot two different `z` fields on the same colormap, I would do it as:

```r
zlim <- c(-1, 1)
cm1 <- colormap(z1, zlim=zlim)
plot(x1, y1, col=cm1$zcol)
cm2 <- colormap(z2, zlim=zlim)
points(x2, y2, col=cm2$zcol)
```
which can be a bit cumbersome. I'm not sure I like the syntax of having the "lookup" function be returned inside the colormap object, but I guess otherwise it would have to be a function that took both the `z` values *and* the already defined colormap. 

Actually, after thinking (and writing) about it, I kind of like the "function within the object" proposal -- as long as it is easy for the `lookup()` function to know what the already defined colormap was (e.g. zlim, col, breaks, zclip, etc etc). That would make my example above look like:
```r
cm <- colormap(zlim=zlim)
plot(x1, y1, col=cm$lookup(z1))
points(x2, y2, col=cm$lookup(z2))
```

**Comment by dankelley** [comment]
Done in "develop" **BUT** I wouldn't mind some advice on whether the name I've chosen for the function makes sense. I called it `colfunction`. I think it needs the `col` part in case we want to add other functions. The `function` part is what I'm finding hard. I note that `uniroot` calls its function `f`, which is clearly too short. And `optim` calls its function `fn`, which is not bad, but I think `fcn`.  But I still think `function` is better than these abbreviations. So I propose that. However, maybe it ought to be `colFunction`???

**Request to co-devels** Please comment, if you want the function name changed. If I don't hear anything by Saturday morning, I'll close this issue.

Anyway, if you pull and rebuild the develop branch and try example 6 from `?colormap` you'll see how it works. That part of the doc and the output is also given below, to save others from having to rebuild.
```R
## Example 6. colfunction
cm <- colormap(c(0, 1))
x <- 1:10
y <- (x - 5.5)^2
z <- seq(0, 1, length.out=length(x))
drawPalette(colormap=cm)
plot(x, y, pch=21, bg=cm$colfunction(z), cex=3)
```

<img width="569" alt="screen shot 2018-01-31 at 6 29 46 pm" src="https://user-images.githubusercontent.com/99469/35651079-c2bf31a2-06b4-11e8-9e1f-cb08aa7302a4.png">

**Comment by dankelley** [comment]
Closing, pr plan

commit 0a62fd346e5f31483ef038632e440be5a69738b6 (HEAD -> develop, origin/develop, origin/HEAD)
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Feb 1 06:58:16 2018 -0400

    document colormap()colfunction
