### ISSUE TITLE
Find sonar target geographic location based on sensor outputs

### ISSUE THREAD

**Issue by ckwkalk** [dankelley/oce#1411]
### Short summary of problem
I am trying to apply the approach used in  xyzToEnuAdp to calculate the geographic location of a sonar target (so this is not an issue or problem with oce itself).

### Details

I have sonar data from a vessel which provides me with the position (in geographic coordinates) and orientation of the sonar. I also have a distance to target. What I am trying to get is the geographic coordinates of the target along with its vertical offset from the sonar. 

![image](https://user-images.githubusercontent.com/8523350/39622333-0c24d286-4f92-11e8-991e-343969e51362.png)

I think that this is what is happening with the xyzToEnuAdp function. In summary what I am after is:

xyz <- function(lon, lat, heading, pitch, yaw, distance)

Where xy are the geographic coordinates of the target and z is the vertical offset.
The input data I have are:

Latitude Longitude Distance     roll           pitch  yaw
44.54855 -124.3716 47.08359 58.91892 -2.136 74.2
44.54855 -124.3716 47.08359 58.91892 -2.109 74.1
44.54855 -124.3715 46.85874 58.91892 -2.076 73.9
44.54855 -124.3715 46.85874 58.91892 -2.050 74.0
44.54857 -124.3715 46.57393 58.91892 -2.034 74.3
44.54857 -124.3715 46.57393 58.91892 -2.025 74.5

**Comment by dankelley** [comment]
This seems like a spherical trig problem, so e.g. https://en.wikipedia.org/wiki/Spherical_coordinate_system#Cartesian_coordinates, i.e. (tex notation)
$x=r\sin\theta\cos\phi$, $y=r\sin\theta\sin\phi$ and $z=r\cos\theta$ so the problem centres on converting the nautical notation to $\theta$ and \$phi$.

A few additional questions:
1. am I right in thinking the sonar points straight down (if the ship is not pitched)
2. how do you wish to define $x=y=0$?
3. to define z, we'd need also the distance of the transducer below the water surface, $d$, say.

**Comment by richardsc** [comment]
This is a neat problem. I think @dankelley is on the right track thinking about it as a spherical trig problem -- you need to convert from spherical coordinates (with a changing reference frame) to cartesian (geographic) coordinates.

To be clear though, I don't think this is related to any of the "adp" transformation problems, specifically `xyzToEnu()`, because those are simply *rotations* of the coordinate system (which is used to measure velocities), rather than transformations between coordinate systems.

**Comment by ckwkalk** [comment]
When trying to even describe this problem I came across some references which seem to indicate it is a matrix rotation problem:
![image](https://user-images.githubusercontent.com/8523350/39664795-39d6b832-5089-11e8-976a-04f90a9767e9.png)

Also  this seems related: [](https://math.stackexchange.com/questions/1637464/find-unit-vector-given-roll-pitch-and-yaw) 

I can convert from the geographic (Latitude, Longitude) coordinates to a projected coordinate system (i.e. so that the xy coordinates are in metres - see below) which would remove the problem of differing coordinate units but. But because rotations in three dimensions do not combine linearly and not necessarily commutative I am am not sure it is a simple spherical trig problem?

In answer to @dankelley:
1: Yes sonar points straight down
2: for the  $x=y=0$ either the sonar as origin (and then add the displacement onto the known spatial coordinates or use the origin of the spatial coordinate system).
3:For this instance we could say the transducer was 1m below the surface at all times.

The same data with projected coordinates would be:
   Distance     roll  pitch  yaw Longitude Latitude
47.08359 58.91892 -2.136 74.2  391053.9  4933717
47.08359 58.91892 -2.109 74.1  391053.9  4933717
46.85874 58.91892 -2.076 73.9  391057.8  4933717
46.85874 58.91892 -2.050 74.0  391057.8  4933717
46.57393 58.91892 -2.034 74.3  391061.9  4933719
46.57393 58.91892 -2.025 74.5  391061.9  4933719
46.70135 58.91892 -2.018 74.7  391065.9  4933720
46.70135 58.91892 -2.018 74.8  391065.9  4933720
46.70135 58.91892 -2.008 75.2  391065.9  4933720
46.58892 58.91892 -1.994 75.6  391069.8  4933720
46.58892 58.91892 -1.977 75.6  391069.8  4933720

**Comment by dankelley** [comment]
I'm busy with other things at the moment, but maybe some questions:
1. Is your roll really nearly 60deg? This seems rather large, unless this is a drug boat evading the DEA or something.
2. the transformation of lon-lat to x-y depends very much on the map projection scheme (UTM, or over a hundred other popular schemes), but you can play with that yourself, because the best way to handle this problem would likely be to be in an x,y,z system that is relative to the boat itself, i.e. you can use any projection scheme you like.
3. in your notation, does pitch>0 mean upward elevation of the bow relative to the stern?
4. in your notation, does roll>0 mean starboard-side elevation relative to port-side?
5. in your notation, is yaw measured counterclockwise of true north?
6. as @richardsc mentions, there is some subtlety in calculations relating to rotating coordinates

**Comment by ckwkalk** [comment]
In answer to the questions:
1. 60 degrees is rare but in this toy example it helps demonstrate if the maths is working as expected. (If you were trying to outrun the law I guess the orientation of your sonar is the least of your worries?)
2. Agree - probably simplest to make the sonar 0,0,0.
3. Positive pitch = bow up
4. Positive roll is to starboard (starboard sinks, port rises)
5. Positive yaw is clockwise (bow turns to starboard)
6. Yes it seems to be too subtle for me!
I meant to include this link in the previous reply but it seemed to get lost:
https://math.stackexchange.com/questions/1637464/find-unit-vector-given-roll-pitch-and-yaw

**Comment by dankelley** [comment]
I think it also depends on what instrument is measuring the angles -- how it's done mechanically, and what notation they are using on the so-called [Euler angles](https://en.wikipedia.org/wiki/Euler_angles); note on that webpage that there are several possibilities ... the order of applying rotations matters to the definitions and formulae.

If I were you, I'd ask the manufacturer for a formula to use. In oceanographic instrumentation, the manufacturers supply formulae that tell how to do calculations. I'd certainly want that if making commercial products (with incurred liability).

**Comment by richardsc** [comment]
I think the business of rotation matrices and the supposed similarity to the *velocity* transformations is not applicable here. I'm not sure what the text screenshot is from, but to me it looks like a velocity coordinate transformation, which as I said seems to be a different problem for what you're trying to do.

I also agree with Dan that the specifics of this instrument (and the manufacturer specifications) are important. Is this an omni-directional sonar? If so, I would think that the angle between the "vertical" and the target are probably a minor correction, and you could start by simply mapping the ranges with the ship position to triangulate a location and depth. In the below figure you have the pitch of the ship (and sonar) exactly the same as the angle to the target, but I doubt that would really ever be the case. In reality I think the error in radial distance due to the pitch/roll of the ship would be small compared to the target distance (but that depends on whether the target is hundreds of meters away, or just a few).

![image](https://user-images.githubusercontent.com/233584/39718284-393dcbde-520c-11e8-9219-781f6ab322d5.png)

**Comment by richardsc** [comment]
Another issue that could be important (again, depending on the specifics, including the actual ranges and depths involved) is whether there is any water column stratification and whether you expect that to have had an effect on your range measurements (through sound speed variations, refraction, etc).
Another issue that could be important (again, depending on the specifics, including the actual ranges and depths involved) is whether there is any water column stratification and whether you expect that to have had an effect on your range measurements (through sound speed variations, refraction, etc).

Regardless, this is definitely not an oce issue (or even a feature request for a general tool), so I'd propose closing this (if those involved want to continue discussion it could be done offline, e.g. though email).

@dankelley and I are experienced with various acoustic instrumentation, but we are not sonar experts and I think you'd be better off looking for help from a more specific list, or from someone who does (or has done) what you are attempting. I know folks at our local [DRDC Atlantic office](http://www.drdc-rddc.gc.ca/en/research-centres.page) who do this kind of thing frequently.

Sorry we couldn't be of more help!

**Comment by ckwkalk** [comment]
No problems - appreciate you taking the time to have a look especially as it is not directly related to your package - all the best.
