### ISSUE TITLE
ADCP ODF metadata for read.odf()

### ISSUE THREAD

**Issue by Echisholm21** [dankelley/oce#1430]
Looking through the read.odf() code the other day I noticed your note @dankelley about wanting to put in sections for different instruments possibly starting with ADCP. I would be interested in helping you with this if it is still something you want to do. It would help me greatly, in trying to read in archived ADCP ODFs I have noticed there are some more specific header metadata attributes which do not get incorporated into the oce ODF object (example: transducer_offset_from_bottom). If I created a list of these ADCP specific attributes from archived BIO files would this be something you were interested in? I know you are likely busy so let me know if this is too time consuming.

**Comment by dankelley** [comment]
Yes, thanks, I'd be very interested in that. Are you "up to speed" on how these docs are written? If so, I'd suggest you try a pull request against the "develop" branch.  The changes would likely go into `R/odf.R` somewhere after line 722 (that is, in the "@details") section.  The format there is called "roxygen", and it's quite simple -- likely you can tell how it works by looking at the file.

The idea would be that you could alter the text (in RStudio, perhaps), then do the "build and install" step (after setting up some menu items -- sorry, hard to explain by typing but others at BIO know how) to check that the Roxygen is not malformed, and then do a "pull request" (again, others at BIO know how to do pull requests).  Of course, this is all a bit tricky but also (in my view) useful for you to learn ... but if you prefer, just write a comment below with suggested text, and I can easily make it into Roxygen and incorporate it.

**Comment by Echisholm21** [comment]
I think I can manage that. The idea being to add the metadata items into the Roxygen help text for read.odf()? 
Certain items might also need to be incorporated into the code in order to be pulled from the ODF file, but I can leave that to you. 
Thanks Dan!

**Comment by dankelley** [comment]
Yes, idea is either that you learn how to write Roxygen and how to do pull requests (both good things but you may not have time) or that you simply enter some text into a comment.

As an intermediate plan, maybe you could write stuff into a comment here, and I could put it into roxygen, and then you'd see how that got done, and you could edit then and do a pull request.

(It's less work for me if you do the comment method.)

**Comment by Echisholm21** [comment]
Alright, here's what I had written up at line 737 or R/odf.R

```Ruby
#' Some metadata items may be specific to certain instruments, \code{adp}
#' objects have some specific metadata items including DEPTH_OFF_BOTTOM,
#' SAMPLING_INTERVAL (in the EVENT_HEADER) as well as a wealth of metadata
#' hidden inside the HISTORY_HEADER in the PROCESS attribute which is typically
#' used to store any metadata included in other file formats such as netCDF. If
#' there has been drift or movement of a moored ADCP it is also possible that
#' there are two latitude and longitude values named START_LATITUDE and
#' END_LATITUDE (or longitude respectively). 
#'
```

**Comment by Echisholm21** [comment]
A note, although this may get too confusing, START_LATITUDE is also sometimes INITIAL_LATITUDE

**Comment by dankelley** [comment]
Thanks!!

Q: is what you say written in stone (in which case, can you name a URL for the docs) or something that might be changing.  (This just relates to your "have" in the 2nd line, which I think maybe ought to be "may have" unless there is a documented convention.)

I'm really big on having links to docs ... a problem with ODF is finding such links :-)

**Comment by Echisholm21** [comment]
Unfortunately these are not documented conventions, just patterns I have seen after looking through archived ADCP ODF files. Line 2 should definitely be edited to "may have".
 If any documentation does turn up I will send it along!

**Comment by dankelley** [comment]
I tweaked your text a bit and put it in. The text suggests that `odf` objects hold this info in their metadata, but I've not checked on whether they actually do, with the present-day code. (Maybe you could email me a datafile for me to test? I'm not sure whether these new lines in the doc are explaining present-day functionality or previewing changes that ought to be made to `read.odf`.)

**Comment by Echisholm21** [comment]
I will email you a data file, I think that yes they do represent changes that ought to be made to read.odf() in the case of SAMPLING_INTERVAL, read.odf reads it in as a logical value (?) and doesn't register anything for DEPTH_OFF_BOTTOM or the difference between INITIAL and END coordinates.

**Comment by dankelley** [comment]
Thanks. I'll take a look at the code and check that it finds these things, and then I'll build tests into the test suite.

FYI, the below demonstrates how to discover what gets into the metadata:
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> d<-read.odf("~/Desktop/MADCP_HUD2015006_1897_10220-20_1800.ODF")
> names(d[["metadata"]])
 [1] "units"                "flags"                "filename"            
 [4] "deploymentType"       "dataNamesOriginal"    "type"                
 [7] "model"                "serialNumber"         "eventNumber"         
[10] "eventQualifier"       "ship"                 "scientist"           
[13] "institute"            "cruise"               "station"             
[16] "countryInstituteCode" "cruiseNumber"         "date"                
[19] "startTime"            "latitude"             "longitude"           
[22] "waterDepth"           "depthMin"             "depthMax"            
[25] "sounding"             "sampleInterval"      
```
Hm, I don't see anything in there called "header".

Actually, I think `read.odf` ought to have a new argument, named `header` say, with default of `FALSE, and doc:
```R
#' @param header Logical value indicating whether to read the entire header and store it as
#' \code{header} within the \code{metadata} slot of the return value. This can be helpful for 
#' analysts who need information not otherwise read by \code{read.odf}.
```

This could be more detailed, actually; it could make `header` be a list with elements named `ODF_HEADER`, `CRUISE_HEADER`, etc. Perhaps it could even make lists within the lists, but this gets awkward because they reuse names, e.g. `QUALITY_TESTS` is used over and over in `QUALITY_HEADER` in this file ...

If @richardsc is thinking of having a DalDay, that might be the best way to go forward, because what I am proposing in this `header` argument is getting uncomfortably close to doing what I thought BIO people were doing already, in a standalone package (named `ODF` maybe) that I've lost track of.

**Comment by Echisholm21** [comment]
Dan, I think that sounds great and very helpful. I recently found a copy of the ODF package you mentioned here at BIO, I can send it along maybe? From what I've seen you are right, it reads ODFs into lists (with lists inside each list)

**Comment by dankelley** [comment]
I have a copy of that ODF package, but I'd prefer not to get too entangled in it, since it seemed to be still in a development stage and I'm not sure how public it is. If I write the 20 lines it will take to do this in oce, then there's no worry about relying on something that might change. Only "power users" would be doing `oce:read.odf(file, header=TRUE)`, in any case, and we can expect them to know how to search through odd lists (with lots of sibling entries of identical name).

**Comment by dankelley** [comment]
You can see what I mean by the identical names by running the below:
```R
library(oce)
f <- "MADCP_HUD2015006_1897_10220-20_1800.ODF"
l <- readLines(f)
endOfHeader <- grep("^-- DATA --$", l)
header <- l[seq_len(endOfHeader - 1)]
tail(header)
A <- grep("^[A-Z].*,$", header)
h <- vector("list", length=length(A))
names(h) <- gsub(",.*$", "", header[A])
str(h)
```

**Comment by Echisholm21** [comment]
Alright, well that makes sense to me. Thanks again! Let me know if I can assist in any way with sample files or testing.

**Comment by dankelley** [comment]
It's quite slow to do testing from within `oce`, and much better to test standalone codes. Therefore, if you want to help, maybe you could try the following on some of your files. It spits out a lot of stuff, but at the end is the list-of-lists that could be save in the `metadata` slot of an `oce` object. The questions are: (a) does this catch all the blocks in this sample file; (b) does it get each item in each block; (c) does it work with some other ODF files.

The way to do the tests is to compare the output with what you see using an editor on the `.ODF` file.

This is mainly a test of whether the regular expressions I've set up (the `gsub` calls) will recognize and subdivide the lines of the ODF file.  Lacking an open-access definition of ODF files, I'm basically just guessing here, and don't e.g. know whether some may have spaces before/after the `=` signs, or whether my trick in looking for two blanks before a letter will always work (maybe some files have 4 spaces).

A simpler alternative is to just store all the lines of the header in a character vector. Indeed, that could be done; we could have `read.odf(file, header="list")` to get a list, `read.odf(file, header="character")` to save a vector of character strings, etc. That's the beauty of R ... it can be very flexible, but that also means we need to plan ahead a bit.

It might be worth chatting with @richardsc if he is around and not super busy. (Likely he is around but super busy!) I have some meetings today but if you could do some tests today or tomorrow, then oce could get updated for the Saturday timetable (when I often clean up small tasks from the week).


```R
library(oce)
f <- "MADCP_HUD2015006_1897_10220-20_1800.ODF"
l <- readLines(f)
endOfHeader <- grep("^-- DATA --$", l)
header <- l[seq_len(endOfHeader - 1)]
tail(header)
A <- grep("^[A-Z].*,$", header)
h <- vector("list", length=length(A))
names(h) <- gsub(",.*$", "", header[A])
starts <- A+1
ends <- c(A[-1], length(header) + 1) - 1
for (i in seq_along(starts)) {
    cat(header[A[i]], "\n")
    nitems <- 1 + ends[i] - starts[i]
    message("  nitems: ", nitems)
    h[[i]] <- vector("list", length=nitems)
    itemsNames <- NULL
    itemsI <- 1
    for (ii in starts[i]:ends[i]) {
        message(header[ii])
        name <- gsub("[ ]*(.*)=.*$", "\\1", header[ii])
        value <- gsub(".*=[']{0,1}([^[',]*)[']{0,1}[,]{0,1}", "\\1", header[ii])
        message("      name:  ", name, "")
        message("      value: ", value, "")
        itemsNames <- c(itemsNames, name)
        ## print(itemsNames)
        h[[i]][[itemsI]] <- value
        itemsI <- itemsI + 1
    }
    names(h[[i]]) <- itemsNames
    message("bottom of i=", i)
}
str(h)
```

**Comment by Echisholm21** [comment]
I tested this with a few random MADCP ODF files from years 2009-2015. It seems to work great and grab everything.

I got an error on certain files in line 3 which was solved by replacing``` "^-- DATA --$" ```with ```"-- DATA --"```. Which seems quite strange, I'm not sure by looking at it what would be different about those particular files but maybe I can send them along to you if you like. 

Otherwise it seems to be grabbing all the information in the headers, I will try it later today with some other instrument types as well. 

I think you are likely right and @richardsc is quite busy but I will discuss with him if there's a chance 
👍

**Comment by dankelley** [comment]
Can you email a file with the funny `DATA` line? I want to look to see if maybe there is a carriage-return-linefeed combination.  As a lesson, the `^` means "start of string" and the `$` means "end of string", so the test as I've written it will key on
```
-- DATA --
```
but not on
```
Hello my friend, here are my -- DATA -- do you agree with my conclusions
```
etc.  but dropping the `^` and `$` will make it "twig" to this funny line.

Perhaps I need to permit it to have a single character (or blank characters) before or after the `-- DATA --` part.

**Comment by dankelley** [comment]
PS. in line 835 of `R/odf.R`, I am using just `"-- DATA --"` so perhaps I ran into problem files before.

**Comment by dankelley** [comment]
I'm a bit divided on the naming of items in the list. At the moment, the names in the `.ODF` file are used, which means there can be repeats, as below. I am half-inclined to append digits to the item names, to make them distinct (i.e. there would be `HISTORY_HEADER1`, `HISTORY_HEADER2`, etc perhaps). That would make it easier to refer to things using e.g. `header$HISTORY_HEADER1$something`, which might be useful.
```R
> names(h)
 [1] "ODF_HEADER"            "CRUISE_HEADER"         "EVENT_HEADER"          "INSTRUMENT_HEADER"     "POLYNOMIAL_CAL_HEADER"
 [6] "POLYNOMIAL_CAL_HEADER" "POLYNOMIAL_CAL_HEADER" "POLYNOMIAL_CAL_HEADER" "HISTORY_HEADER"        "HISTORY_HEADER"       
[11] "HISTORY_HEADER"        "HISTORY_HEADER"        "HISTORY_HEADER"        "HISTORY_HEADER"        "HISTORY_HEADER"       
[16] "HISTORY_HEADER"        "HISTORY_HEADER"        "PARAMETER_HEADER"      "PARAMETER_HEADER"      "PARAMETER_HEADER"     
[21] "PARAMETER_HEADER"      "PARAMETER_HEADER"      "PARAMETER_HEADER"      "PARAMETER_HEADER"      "RECORD_HEADER"        
> head(names(h[[11]]))
[1] "CREATION_DATE"          "PROCESS"                "PROCESS"                "PROCESS='name "         "PROCESS='long_name "   
[6] "PROCESS='generic_name "
```

**Comment by dankelley** [comment]
Oh, shoot, look at that. In the last line of what I just pasted in the previous comment, we see that it is freaking out on line 141 of the file, which reads
```
  PROCESS='name = u',
```
and I can see why ... there are two `=` in there, so perhaps the pattern is getting mixed up.  This can be fixed up, though.

**Comment by dankelley** [comment]
I am attaching an updated R code. I think it is now decoding left-hand and right-hand sides of items correctly now, as well as removing optional trailing commas and optional embracing single-quote marks.

I wonder whether @Echisholm21 can check this on some files. Here's how. First, of course, rename so that the suffix is `.R`, not `.R.txt`. (GH won't accept `.R` files.) Then, try the code on the named sample file, with line 2 changed to set `debug` to `TRUE`, and see whether the results seem to make sense. I am now printing out small steps in the text processing, because that will let us find errors.  Third, turn debugging off and run it, the do `str(h,1)` to get a quick overview and then `str(h)`. Basically, just run your eyes over it, to see if some things are coming out oddly.

I've done these steps on the named file but a pair of fresh eyes will help.

Then try it on some other files.

Finally, I'd love to get some feedback on the naming of items in the lists. As you can tell at a glance, there are a lot of what I'll call "sibling" items that have the same name. There was a funny TV show with a famous line "This is my brother Darrell, and this is my other brother Darrell".  For easy reference by a programmer, it might be best to call these (continuing the analogy) Darrell_1 and Darrell_2, because then one might do e.g.
```R
d <- read.odf(...)
d[["header"]]$Darrell_1$age
```
instead of perhaps
```R
d[["header"]][[10]]$age
```
after discovering that Darrell_1 was the 10th item in the header.

But I don't know the internal rules for ODF files, e.g. whether things will always come out in the same order, and we maybe don't want R programmers to be writing code with names like `Darrell_1` because that might encourage users to think that the older brother will always be `_1`, etc.

I know what I said above is not too clear, regarding sibling names, but it's something on which I'll need advice from the lab that uses ODF.

Of course, point of all this is that I want to get the functionality right before perturbing oce. It's not good to invent a system and then change it a month later, and it's *really* bad to change it a year later!

[MADCP_HUD2015006_1897_10220-20_1800.R.txt](https://github.com/dankelley/oce/files/2075947/MADCP_HUD2015006_1897_10220-20_1800.R.txt)

**Comment by Echisholm21** [comment]
Hi Dan, 

As far as sibling names, I think it makes sense to distinguish them in some way for easy access. Maybe the" _01" makes sense (that is a common naming scheme for variables here at BIO) this would allow a basic distinction and then programmers could rename individual headers if needed for simplicity based on specific data. When these files are transferred to netCDF (which doesn't allow identical names) the sibling names are put in as attributes like ODF_history_001, ODF_history_002, etc. I think the _01 is a similar enough convention to make sense. I can also get some opinions from around the office here if that would be helpful. 

I will email you some problem files so you can take a look.

I will try the script above on a variety of files as well. 

Cheers!

**Comment by dankelley** [comment]
I've updated the script (attached), and I think it might work on both the "good" file I was using and the two "less good" ones you just emailed. Please test.
[MADCP_HUD2015006_1897_10220-20_1800.R.txt](https://github.com/dankelley/oce/files/2076877/MADCP_HUD2015006_1897_10220-20_1800.R.txt)

**Comment by Echisholm21** [comment]
Will do!

One thing I picked up from the 2015 file, is some of the history lines are too long and getting truncated. 

eg. 
```Ruby
 ..$ PROCESS      : chr "history = Written to an EPIC standard data file by adcp2ep.m\\Ensembles recorded pre and post deployment were t"| __truncated__
```
when it should read 
PROCESS='history = Written to an EPIC standard data file by adcp2ep.m\Ensembles recorded pre and post deployment were trimmed by goodends.m.\Converted to netCDF via MATLAB by rdi2cdf.m 2.2c 10/22/99',

This could just be a printing error but it seems to also be truncated within the R object.

**Comment by Echisholm21** [comment]
Reading the 2011 file with the new script gives a few warnings... 

note: none of the lines producing warnings have trailing commas. 


1: In eval(ei, envir) : malformed string in line 12

for context:
[12] CRUISE_DESCRIPTION='' 

2: In eval(ei, envir) : malformed string in line 45

for context:
[45]  EVENT_COMMENTS='10-NOV-2011: Bins 37-50 were dropped (< 16 m), due to proximity to the surface.' 

3: In eval(ei, envir) : malformed string in line 77


for context:
[77]  PROCESS='Generation'

4: In eval(ei, envir) : malformed string in line 133

for context:
[133]  PROCESS='ODF_History_002 = 5000' 

5: In eval(ei, envir) : malformed string in line 236

[236]   PROCESS='Add_Parameter: A.Data.SYTM_01 = evalin('caller','sytmchan');' 


6: In eval(ei, envir) : malformed string in line 241

[241]   PROCESS='Where Coefficients are:  A0=0 A1=0.01' 

7: In eval(ei, envir) : malformed string in line 246

[246]   PROCESS='Where Coefficients are:  A0=0 A1=0.01' 

8: In eval(ei, envir) : malformed string in line 251

[251]   PROCESS='Where Coefficients are:  A0=0 A1=0.01' 

9: In eval(ei, envir) : malformed string in line 260

[260]   PROCESS='Edit Parameter: ERRV_01 Units=M/s' 

10: In eval(ei, envir) : malformed string in line 264

[264]   PROCESS='Name check performed' 

11: In eval(ei, envir) : malformed string in line 271

[271]   PROCESS='Edit Instrument: Inst_Type=ADCP Model=RD Instruments Serial_Number=15538 '

**Comment by Echisholm21** [comment]
There also seems to be something weird happening when you ```view(h)``` 
Items with sibling names display only the data stored in the first list of a given name, example: each History Header displays only creation date and generation information. 

This could be something within R and the ```view()``` function that will be fixed by appending sibling names with distinct digits.

**Comment by dankelley** [comment]
This is a long comment. I want to walk you (and any others who are reading this) how I worked on the problem stated in https://github.com/dankelley/oce/issues/1430#issuecomment-395118646 

The summary is that I request that you try the attached `.R.txt` file on the three test files, and also on whatever other files you have handy. (If any cause problems, please email them to me and post a note so I can add the files to the test suite.)

OK, now the long part.

I assume you mean file `MADCPS_HUD2011004_1795_15538-24_1800.ODF`. I get a different error on that:
```R
Error in grep("^[ ]*-- DATA --[ ]*$", l) : 
  (converted from warning) input string 223 is invalid in this locale
```
and, examining line 233 of the file, I see as in the attached screenshot. Notice the funny-looking `<b4>` mark on line 233, and on other lines. I put the cursor on that character on line 225 and did `ga` in my (vi) text editor to reveal the details in the lower (status) line of the window. Sure enough, it is character 0xb4 (that is hexadecimal notation).  

I think we are getting different errors because your machine has a different "locale". (Maybe you're using a DFO machine set up to do French accents easily.) So I changed the line
```R
l <- readLines(f, encoding="UTF8")
```
to
```R
l <- readLines(f, encoding="latin1")
```
and now I get the same errors as you do.  (Well, I get an error because I did `options(warn=3)` to make warnings into errors. That's a good way to find problems.)

OK, next I found the spot in the code where the warning was issued, and put `browser()` above it and reran it. Now, I get to inspect what's going on.

(The point of this is to illustrate how to find problems.) With similar tricks I see that the code is having a problem because line 12 of that file ends NOT with `,` and NOT with `'`, but RATHER with ` `. So, it is breaking the pattern that I was assuming.

[MADCP_HUD2015006_1897_10220-20_1800.R.txt](https://github.com/dankelley/oce/files/2077378/MADCP_HUD2015006_1897_10220-20_1800.R.txt)


<img width="1130" alt="screen shot 2018-06-06 at 1 59 17 pm" src="https://user-images.githubusercontent.com/99469/41053508-2479f31a-6992-11e8-8536-5405d210a81e.png">

**Comment by Echisholm21** [comment]
Thanks for the step by step, that is much appreciated. 

I reran all the test files with the updated script and I don't notice anything off the bat but I will take a longer look tomorrow. 

I think the ```View()``` function could be useful especially where the lists are so long, it is a simpler way to look through the file (especially in RStudio).

**Comment by dankelley** [comment]
Thanks. PS. below is what the doc might look like. See typos, or spots that could be made clearer?

> `header`   An indication of whether, or how, to store the ODF file header in the metadata slot of the returned object. There are three choices for header. If it is FALSE, then the header is not stored. If it is "character", then the header is stored as as a vector of character strings, one per line of the file. Finally, if it is "list", then a list is created to describe the header contents. The names of items in the list are taken from the names of items in the ODF file, except that repeated names are transformed by appending _1 to the first, _2 to the second, etc. Typically, each item in the list is a sub-list of a name-value pair, and, here again, digits are appended to avoid repeated names within a category.

**Comment by Echisholm21** [comment]
I think it could be made clearer that ```header``` stores the ENTIRE header, where setting it to FALSE still pulls specific information from the header into the oce object, maybe the word is 'raw' header data... 

May I also suggest that the appending digits include at least 1 leading zero? maybe even 2? (There are headers with at least 100 list items) it is possible that these values will get to be very high and then there may be issues with ordering that could be avoided by using _001 (I have recently experienced this problem first hand in ODF files which is why I mention it)

**Comment by dankelley** [comment]
Thanks. I though of leading 0 but decided against it because things might be odd when we get more digits, but maybe if I use 001 it will be ok. No real problem will happen, as demonstrated below.
```R
> sprintf("%02d", c(1,99,100,1000,1001))
[1] "01"   "99"   "100"  "1000" "1001"
```

**Comment by Echisholm21** [comment]
That seems reasonable! Thanks again.

**Comment by Echisholm21** [comment]
Let me know when this is running in develop or dk and I will close the issue.

**Comment by dankelley** [comment]
I think this should work now, in the "develop" branch, commit f2e95b90b6ea824c132eeae41fb6369ebced8a2b. 

Below is a test code; see `?read.odf` for instructions.
```R
library(oce)
odf <- read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz", package="oce"), header="list")
View(odf[["ODFHeader"]])
```

If you'd like to suggest changes to the `header` portion of the `?read.odf` docs, please add a comment here.

I think it would be helpful to other users if you could take a bit of time over the next days or weeks, to test the update on a suite of ODF files, since I've checked just one.  (It can be problematic when a feature gets added and not explored for a year, because by then users may be committed to the syntax and so necessary fixes might have a large ripple effect.)

Thanks for your help, advice, and patience!

**Comment by dankelley** [comment]
I just modified "develop" so that now, the header is named `header`, as for CTD data. Thus, the suggestion for interactive testing is now
```R
library(oce)
odf <- read.odf(system.file("extdata", "CTD_BCD2014666_008_1_DN.ODF.gz", package="oce"), header="list")
View(odf[["odfheader"]])
```

PS. I am going to build in some tests within the build-test suite. This won't affect anything for the user -- it's just a way to ensure that if I change the interface again (e.g. like how I renamed `ODFHeader` as `header`) then the package will fail its build-test, which is a way to make me be very careful about changes. Oh, and of course it will check that we actually get a list when we ask for it, etc.

**Comment by dankelley** [comment]
In "develop" commit 6ab6ed3dff3d4e9fcf6f17585b41b7cc3ce81c15 there is now a test block (`tests/testthat/test_odf.R`, starting at line 110) that checks whether we get headers as stated in the docs, and also whether the headers match up between the character and list types.

**Comment by Echisholm21** [comment]
Everything looks great! I am testing with a few more ODF files but that will continue through my work over the summer. 
I think this issue has been resolved but I will let you know if I have any trouble with particular files. 

One thing about the doc, (maybe this is me being too nitpicky) but there is a small typo in the header argument text block of ```?read.odf```, 
 "The naming of list entries **iis** patterned on that in the ODF header, except that unduplicateNames is used to transform repeated names by adding numerical suffices."

Thanks again, much appreciated!
:-)

**Comment by dankelley** [comment]
Typo fixed in 16185309239852c90ca25134db7b4876f2fca449 (in case you don't know, you can click on that link to see changes).

**Comment by dankelley** [comment]
@Echisholm21 to return to the beginning, can you make a comment that lists the items you want extracted into the `metadata` slot?  The best plan is to do this as a checklist, by entering content like below (I have used code-block format but you'll enter as normal format). Then, as I do them, I can click the box ... this makes it easy for me to keep track.
```
* [ ] first task
* [ ] second task
```

**Comment by Echisholm21** [comment]
ADCP specific metadata to be extracted:

- [ ] DEPTH_OFF_BOTTOM
- [ ] INITIAL_LATITUDE
- [ ] INITIAL_LONGITUDE
- [ ]  END_LATITUDE
- [ ] END_LONGITUDE
- [ ] SAMPLING_INTERVAL

**Comment by Echisholm21** [comment]
The updated metadata items are great! Thanks!

In my own tests I have discovered a small problem though, I think I have traced it back to line 1130 in odf.R

``` res@metadata$time <- as.POSIXct(strptime(tolower(findInHeader("START_DATE_TIME", lines)), "%d-%b-%Y %H:%M:%S", tz="UTC"))``` 

from commit https://github.com/dankelley/oce/commit/83045e8e86bfb5fbee47d444da3dcb3dd11121c2

When using ```'[['``` methods, this now means that ```odf[['time']]``` returns as a single value from the metadata rather than the data slot item ```'time'```. This has caused a problem in one of my scripts which would be easy to fix by referencing ```odf@data$time``` but I wanted to make you aware of the issue and get your thoughts. This is a new metadata item correct? I don't think I've had this issue before but I could be wrong.

**Comment by dankelley** [comment]
Oh, you're a good detective!! This is a new metadata item. There have been loads of problems with times in other object types. Please try the new commit (notes below)

commit 0051a33637687aa88dc1aeafb2a10881aa1f8933
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Jun 8 14:11:53 2018 -0300

    fix recent read.odf() bug (thanks, EC)

**Comment by Echisholm21** [comment]
Resolved! Thanks!!

My only note on the ```?read.odf``` update would be that the reference to the ```View()``` function should have the v capitalized to prevent confusion, that function is strange but ```view()``` the way it is described now in the help file will not be recognized as a funtion in R. Otherwise it looks great!

**Comment by dankelley** [comment]
I fixed the typo and made that and the `str` example have links.

commit b525df0c4f6f96143af25e9f1b9b15d6921459a4
Author: dankelley <kelley.dan@gmail.com>
Date:   Fri Jun 8 14:33:37 2018 -0300

    fix doc error (thanks again, EC!)

**Comment by Echisholm21** [comment]
Awesome!! 👍

**Comment by dankelley** [comment]
Dear reporter,

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

PS.  This is a standardized reply.
