### ISSUE TITLE
xaxp error when plotting stations from a section object

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1431]
Haven't dug into this -- just reported to look at later:

```
library(oce)
data(section)
plot(section[['station', 1]])
```
```
Error in par(opar) : 
  invalid value specified for graphical parameter "xaxp"
```

**Comment by dankelley** [comment]
Hm, I don't get that. I tried two EOSs; below shows that no output is printed, and the plots look fine. Maybe you can do a traceback(). I could look tomorrow morning if you don't see the problem.
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> data(section)
> plot(section[['station', 1]])
> 
> options(oceEOS="unesco")
> library(oce)
> data(section)
> plot(section[['station', 1]])
> 
```

**Comment by richardsc** [comment]
Weird ... I get it in Emacs (with ESS) but not in RStudio ... Traceback isn't too helpful:
```
> traceback()
4: par(opar)
3: .local(x, ...)
2: plot(section[["station", 1]])
1: plot(section[["station", 1]])
```

**Comment by dankelley** [comment]
Maybe use `plot(..., debug=10)` to find out whether problem is in the top level of `plot,ctd-method` or  in `plotProfile`, `plotTS`, or `plot,coastline-method`.

Maybe try using `png` or `pdf` instead of interactive graphics, to see if that provides a clue.

It's a head scratcher.

**Comment by dankelley** [comment]
Dear reporter,

This issue seems to have gone stale. There is no problem in leaving issues open if tests or development is ongoing, but the developers do not like to leave users "high and dry" by mistake. Therefore, this is a request for a status update. If the issue is still active, perhaps someone can make a comment to that effect, ideally  with a suggested timetable or work-plan for resolution. Otherwise, this issue will become a candidate for closure by the developers, which is not the preferred scheme, since in "oce" we like reporters to be the ones to close issues.

PS.  This is a standardized reply.

**Comment by richardsc** [comment]
Just re-checked this and I no longer get the error. Must have been a PEBKAC issue.

Closing
