### ISSUE TITLE
as.ctd() does not store mean longitude/latitude when they are vectors

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1440]
### Short summary of problem

When creating a ctd object using as.ctd, the description for the longitude and latitude arguments state that "optional numerical value containing longitude in decimal degrees, positive in the eastern hemisphere. If this is a single number, then it is stored in the metadata slot of the returned value; if it is a vector of numbers, they are stored in data and a mean value is stored in metadata.". As shown in the example below, it does not. 

### What you did

```
T <- seq(2,3, length.out = 20)
S <- seq(31.4, 31.6, length.out = 20)
p <- seq(0, 20, length.out = 20)
lat <- rep(44.5, 20)
lon <- rep(-63, 20)
stn <- 'fake'
time <- seq(from = as.POSIXct("2012-01-01 00:00", tz = 'UTC'), by = 'min', length.out = 20)
ctd <- as.ctd(salinity = S, 
                     temperature = T, 
                     pressure = p, 
                     time = time, 
                     longitude = lon, 
                     latitude = lat, 
                     station = stn, 
                     startTime = min(time))

ctd@metadata
$units
$units$salinity
$units$salinity$unit
expression()

$units$salinity$scale
[1] "PSS-78"


$units$temperature
$units$temperature$unit
expression(degree * C)

$units$temperature$scale
[1] "ITS-90"


$units$pressure
$units$pressure$unit
expression(dbar)

$units$pressure$scale
[1] ""



$flags
list()

$pressureType
[1] "sea"

$deploymentType
[1] "unknown"

$waterDepth
[1] NA

$filename
[1] ""

$station
[1] "fake"

$startTime
[1] "2012-01-01 UTC"

$type
[1] ""

$serialNumber
[1] ""
```

### What you expected to happen

That longitude and latitude be in the metadata as these two quantities are needed to calculate distance when making a section object.

### What happened

Longitude and latitude not in metadata

### How urgent is this?

Not urgent.

### Output from sessionInfo()

``` R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8       
 [4] LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] oce_0.9-24      devtools_1.13.4 smatr_3.4-3     plyr_1.8.4      ocedata_0.1.4   fields_9.0     
 [7] maps_3.2.0      spam_2.1-2      dotCall64_0.9-5 marmap_0.9.6    gsw_1.0-5       testthat_2.0.0 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18        pillar_1.0.1        compiler_3.4.3      git2r_0.21.0       
 [5] tools_3.4.3         ncdf4_1.16          digest_0.6.13       bit_1.1-12         
 [9] RSQLite_2.0         memoise_1.1.0       tibble_1.4.1        lattice_0.20-35    
[13] rlang_0.1.6         DBI_0.7             curl_3.1            yaml_2.1.19        
[17] knitr_1.20          httr_1.3.1          withr_2.1.1         stringr_1.2.0      
[21] raster_2.6-7        bit64_0.9-7         R6_2.2.2            sp_1.2-5           
[25] adehabitatMA_0.3.12 reshape2_1.4.3      blob_1.1.0          magrittr_1.5       
[29] shape_1.4.3         stringi_1.1.6    ```

**Comment by dankelley** [comment]
@clayton33 I've made an issue test code (
https://github.com/dankelley/oce-issues/blob/master/14xx/1440/1440a.R) -- does this exercise your bug?

**Comment by dankelley** [comment]
Since this has not worked before, I suppose we have the luxury of choosing things. The docs don't say the name of the thing in the metadata. If I call it e.g. "longitude" then `d["longitude"]` will grab just the single value, because `[[` checks metadata before data. Do you think this is a good behaviour?  I think it ought to be called `longitudeMean` because that reflects the distinction between metadata and data better, i.e. the actual data are that vector of locations, and the mean is "data about the data".

@clayton33 Please give a thumbs-up or a comment if you agree that the metadata item ought to be called e.g. `longitudeMean`.

**Comment by dankelley** [comment]
This (with names `longitudeMean` and `latitudeMean` used, and documented) is now in the "develop" branch, commit 1a7968dd75a1172785b6e3f16649f15c4ce768ba

There is now a test in the build-test suite (https://github.com/dankelley/oce/blob/1a7968dd75a1172785b6e3f16649f15c4ce768ba/tests/testthat/test_ctd.R#L501) so we don't have to worry about this feature breaking in future.

@clayton33 -- if you agree that this name is OK, please close the issue. If you don't like it, or if you want to suggest changes to the wording of the docs, just keep the issue open and make a new comment. Thanks!

**Comment by richardsc** [comment]
I like `longitudeMean`

**Comment by clayton33** [comment]
I think ```longitudeMean``` is fine, but if I create some ctd objects using a similar method above and want to create a section and specify ```xtype = 'distance'``` when plotting the section, then its not going to be able to calculate distance because its going to be looking for ```ctd@metadata$longitude```, and same for latitude (at least I think, I looked at the code a few days ago so I could be wrong on this ... ). But I guess the code for plotting sections could just be changed as well.

**Comment by dankelley** [comment]
Oh, good point, @clayton33. I'll look into that, this morning.

**Comment by dankelley** [comment]
I think it is an `as.ctd()` bug, because (1) it was in the docs for that function and (2) I think storing the mean location in the metadata is a good thing. The only question is about naming. I don't want to have both `metadata$longitude` and `data@longitude` in CTD objects; I just think that's too confusing. Therefore, I think the right thing to do is to store the mean (which is not actually the data) within `metadata`, and to name it such. But then a person wants to be able to do `ctd[["longitude"]]` and have that return something meaningful.

Hm. I am getting myself turned around in circles. Our existing code had the ability to put `longitude` into the `metadata` slot, and indeed the `data(ctd)` object has it there. So that contradicts what I just coded. So that argues that we don't want the thing in the metadata to *always* be called `longitudeMean`, etc.

I am coming around to not wanting to store a mean value into the metadata. I think we should do the rules (comments please):
* if as.ctd() or read.ctd() have *multiple* longitudes and latitudes, then the values go into `data`
* if as.ctd() or read.ctd() have *single* longitude and latitude, then the values go into `metadata`

This contradicts the docs, but the docs never worked and were likely that way for years, so I think we can do whatever the three of us want. It also means that the last 2 versions pushed (this morning) will need to be undone.  I am proposing to drop this idea of putting the mean position into metadata.  (We don't put mean temperature there, etc.) So, the only possible change is that where e.g. `plot,section-method` code wants needs to say e.g. `ctd[["longitude"]][1]` (getting the first longitude of the station) whenever it wants to figure out where to plot a map or figure out the grid for sections. Of course, this doesn't give us the zigzag path we might want for gliders, but I am not 100% sure what to plot for gliders anyway, and I'd prefer to have concrete needs on plotting before trying to make something general that might not be useful in practice.

Sorry this is long. I'm doing other things. I didn't have time to write a short comment. (Apologies to Blaise Pascal.)

**Comment by clayton33** [comment]
I agree on those rules but what if as.ctd() or read.ctd() have _multiple_ longitudes and latitudes but also has longitude and latitude in the header of the file ? I think this might be the case for some files, for example,  in some ODF files. Quickly looking at ```odf.R``` it looks like it reads it and treats it as a variable in data. This comment might be irrelevant, but just wanted to point that out as well.

**Comment by dankelley** [comment]
Oh, interesting on the ODF.  I think that this affects `read.ctd()` but not `as.ctd()`.  I think `as.ctd()` is settled (as in previous comments). As for `read.ctd()`, my feeling is that it ought to store in *both* metadata and data slots, but that it should issue a warning that would tell users how to get the values, e.g. use `ctd[["data"]]$longitude` or `ctd[["metadata"]]$longitude`. Then we have the issue of what `as.section` does with such data ...

**Comment by dankelley** [comment]
In branch "develop", commit e2ffc092b274f04d04d7f6c83b34eee4d82456af, the docs for `?"[[,oce-method"` now have a new paragraph.

> The full contents of the metadata slot of an object named x are returned with x[["metadata"]], and x[["data"]] does the same thing for the data slot. Even if the full contents are not needed, this scheme can be useful in circumventing the searching scheme described in the previous paragraph, e.g. x[["data"]]$longitude might be used to select longitude from the data slot of x, as an alternative to oceGetData(x,"longitude").
