### ISSUE TITLE
subset(argo, within=polygon) request

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1449]
Now that `section` objects can subset by a defined polygon (#1448 ) I think it would be great to have the same functionality for `argo` objects.

**Comment by dankelley** [comment]
Good point!  I'll do this today.  Poor old `argo`, always neglected.  (It's because at this time in the term I want to use sections for geostrophic work .. they have such great data, acquired quickly and often across currents, or between coasts.)

**Comment by dankelley** [comment]
I'm also going to permit `plot(argo, which='map')` as a synonym for `plot(argo, which='trajectory')`, because that's what I was writing into the docs :-)

**Comment by dankelley** [comment]
I've coded a trial solution in "develop" commit 866519ee70517ced79c23d92a73ef7f50b10d771. The docs for `?"subset,argo-method"` give an example, and that works for me. I also added a test in `tests/testthat/test_argo.R` (just search for `within` in that file). I've also done some `str()` work to see if my code seems to be working.

I've tried to code it fairly generally, by examining items in `metadata` and `data` for dimension, etc., instead of special-casing by name.

I think it's ready for some user testing now, so I'll set a label to that effect.

**Comment by richardsc** [comment]
I checked this, and it works! Thanks!

FYI I checked it randomly against float 1901530, which was deployed in 2011:
```r
library(oce)
a <- read.oce('1901530_prof.nc')
plot(coastlineWorld, clatitude=a[['latitude']][1], clongitude=a[['longitude']][1], span=10000)
points(a[['longitude']], a[['latitude']])
```
![image](https://user-images.githubusercontent.com/233584/46228003-33887a80-c337-11e8-9d49-7cbffd17e4c9.png)
