### ISSUE TITLE
applying .csv data to oce

### ISSUE THREAD

**Issue by jgmunden** [dankelley/oce#1464]
### Short summary of problem

Was wondering if oce can read .csv data?

**Comment by dankelley** [comment]
Sure. I can post the few lines that are needed, but I need a sample file. Please email one to me, and I'll post a solution.  (Please, in your email, say if it's ok for me to post the first few lines of the file here on github ... that can help other users who have similar needs.)

**Comment by jgmunden** [comment]
Thank you Dan, see the attached file. The original is a .csv but I've changed it to .xlsx so I could attach it here. It's okay for you to post the first few lines to share with others.

[file.csv.txt.xlsx](https://github.com/dankelley/oce/files/2626474/file.csv.txt.xlsx)

**Comment by dankelley** [comment]
First, by attaching, you have posted it to github.  Therefore, I edited your comment and removed the attachment, for privacy.

Second, here's how I'd work with these data.

First, read the data
```R
d <- read.csv("file.csv")
```
Note that if you have extra header lines, you'll want to supply a `skip` parameter to this function call.

Next, discover names of columns
```R
names(d)
```
The result of this is:
```
1] "Pressure..Decibar."                                 "Depth..Meter."                                     
[3] "Temperature..Celsius."                              "Conductivity..MicroSiemens.per.Centimeter."        
[5] "Specific.conductance..MicroSiemens.per.Centimeter." "Salinity..Practical.Salinity.Scale."               
[7] "Sound.velocity..Meters.per.Second."                 "Density..Kilograms.per.Cubic.Meter."               
```
Here, the dots result from spaces or other odd things in the names. I find it convenient to rename things, so I'll do that now, although this is not required (if you can remember to type all those dots):
```
names(d) <- c("p", "depth", "T", "conductivity","conductance","S","v","density")
```
Now, let's take a look at the data, to see if the numbers seem to make sense:
```R
head(d, 2)
```
This gives
```
   p     depth        T conductivity conductance        S        v  density
1 0.15 0.1495109 13.12152     36813.66    48284.62 30.97198 1495.835 1023.252
2 0.45 0.4485356 13.12499     36813.15    48279.56 30.96855 1495.848 1023.250
```
which looks fine for p, S, and T and I don't care much about the rest (for this, anyway).

Now, create a ctd object
```R
ctd <- as.ctd(d$S, d$T, d$p)
```

Now, we can summarize it, e.g.
```R
summary(ctd)
```
(try it and see), and get a plot with
```R
plot(ctd)
```
```R
plot(ctd,eos="unesco")
```
where we have to use the unesco method for the equation of state because we have not specified lon and lat in calling `as.ctd()`.  (Since we don't have lon and lat, the bottom-right panel of the resultant plot is blank. Otherwise it would be a map.)

As a check, the below calculates the difference between density computed for the `ctd` object and density in the file.
```R
summary(swRho(ctd,eos="unesco") - d$density)
```
and the result,
```
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.0006122 -0.0006121 -0.0006115 -0.0006115 -0.0006111 -0.0006107 
```
suggests that we are getting the same numbers, to within an offset that is *very* small. That is so small that I suppose it could come from your data being based on an extra digit of temperature or something like that ... or maybe the density column in your file is potential density, whereas I am computing in-situ density above.


Please try this out with your actual dataset and see if it's making sense. If you need more help on e.g. isolating downcasts, that shouldn't be hard, but I would need a full datafile, not just the start of one.

**Comment by jgmunden** [comment]
Hi Dan, thanks so much! So great my data plotted. I do have lat and lon, it just isn't recorded by the CTD in the data file. If I wanted to add the lat and lon to ctd so I could have the map as well how would I do that? I tried just adding the coordinates in my original data file but the as.ctd function doesn't seem to accept it.

d = read.csv("10K100766_20181015_080152.csv", header=TRUE, sep=",", row.names = NULL, stringsAsFactors=FALSE)
names(d)
names(d) <- c("p", "depth", "T", "conductivity","conductance","S","v","density", "lon", "lat")
head(d,2)

ctd <- as.ctd(d$S, d$T, d$p, d$lon, d$lat)

**Comment by dankelley** [comment]
There's no ned to put them into the csv file. Try e.g.
```R
ctd <- as.ctd(d$S, d$T, d$p, longitude=-63, latitude=45)
```

**Comment by jgmunden** [comment]
Amazing that worked perfect, really appreciate your help!

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by slaeubli** [comment]
Sorry to reopen this issue again. Maybe a very basic question but I seem to be stuck: I'm very new to working with oce and am wondering how i can easily create a ctd object from a simple data frame (e.g., read through read.csv) including other parameters such as oxygen and pH that are available (in addition to T, p, S as you showed). Is this even possible?

**Comment by dankelley** [comment]
Yes, you can do e.g.
```R
d <- read.csv(file)
ctd <- as.ctd(d$salinity, d$temperature, d$pressure)
ctd <- oceSetData(ctd, "oxygen", d$oxygen)
```
and so forth.  You can set the unit at the same time.  Type `?oceSetData` for more on that.
