### ISSUE TITLE
Should the cmocean palettes be included in oce or in a separate package?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1474]
The `cmocean` palettes have been updated (with some new ones!), and we should update what is available in `oce`.

However, given that the palettes are:

a) not developed by any of the current oce co-authors (Dan and Clark), and

b) are distributed as a separate `cmocean` package with the python ecosystem,

I think it might make sense to turn them into their own (much smaller than oce) package. While we could add Kristen as a co-author of oce, it seems like it would be better for her to get the credit of being co-author on a standalone package based on only on her work (and ours to do the R integration).

Thoughts? @kthyng?

**Comment by dankelley** [comment]
Yes, I think it's a very good idea to split out. There will be some details to sort out, which might be discussed in person some day when @richardsc and I are in the same room. One thing I like about splitting off is that then users can select whichever version they want, independent of the version of oce. 

The existing source code `create_data/ocecolors/create_ocecolors.R`, plus the associated `.txt` files, probably provide the kernel of a new package.

I don't think the new package should "depend" on oce, nor vice versa, because otherwise we can get caught in a circular dependency for the CRAN builds that can lead to problems for both packages. This independence will also please people who want the colors, but don't need oce in their R system.

Using `git blame`, I see that the existing colors were put into oce on 2015-09-29, which is quite a while, so I'd like to respect oce users by providing a way to retain those colors, if desired. This could be done via versioning of the new package, but I think a better scheme might be to retain all old schemes within this new package. After all, the colours only occupy about 6K of storage, so saving old schemes won't have significant impact.  This argues that colours should be retrieved with a new function, not with `data()`.  If cmcolors has a scheme for naming updates, we could use that. Otherwise (or in addition) we could use dates. What I'm thinking is that we might use e.g.
```R
Tcol <- cmcolor("temperature", "1.3")
```
for version 1.3, or maybe
```R
Tcol <- cmcolor("salinity", "2017-03-01")
```
for a scheme that worked on a certain date. This way, users could never be clobbered by changes.

As for Clark's last line, I also would like permission from @kthyng before proceeding, but we won't need her to do any work, other than give us permission to make her a co-author.

**Comment by kthyng** [comment]
I don't have any problem with the way you've had the colormaps in oce so far, but your new plan also makes sense. I'm happy to be a co-author, thanks.

**Comment by dankelley** [comment]
Just a note, because I was just doing this manually ... the gist of the incorporation of cmocean is as follows:
```R
balance <- read.table("https://raw.githubusercontent.com/matplotlib/cmocean/master/cmocean/rgb/balance-rgb.txt")
colorsBalance <- oceColorsClosure(balance)
```
which creates a "closure" `colorsBalance()` which is a function that takes an integer for a number of levels in a graduated palette. This can be used as e.g. (not a self-contained example, but it shows the idea, here plotting the ocean variable called "spiciness0", the GSW-formulation of spiciness referenced to zero pressure)
```R
cm1 <- colormap(z=spiciness0, zlim=c(-2.5, 2.5), col=colorsBalance)
drawPalette(colormap=cm1, pch=3/4)
oce.plot.ts(time, pressure, ylim=plim, yaxs="i", drawTimeRange=FALSE,
            ylab=resizableLabel("p"),
            col=cm1$zcol, type="p", pch=20, mar=c(1.7, 3.5, 1.0, 5.5))
```
The result looks as below (with some extra stuff added to highlight some events)

<img width="786" alt="screen shot 2019-02-02 at 4 04 45 pm" src="https://user-images.githubusercontent.com/99469/52168751-4e636500-2704-11e9-9752-2a2e84f48c80.png">

**Comment by richardsc** [comment]
Since this is being actively developed at https://github.com/aitap/cmocean (and is likely to be available on CRAN soon, I'm going to close this.

@dankelley and I should discuss what to do about the `oceColors*()` functions that are derived from an older version of the `cmocean` palettes, but there is no rush.
