### ISSUE TITLE
Feature request: read in Sippican XBT files

### ISSUE THREAD

**Issue by erinann** [dankelley/oce#1494]
Hello!

Request: 
-  `oce` read in Sippican XBT files. 

Data: 
- I have data files in .edf and .rdf format from a Sippican MX21 that I will email the package authors. 
- I'm not really sure what you'd need the .rdf files for because they require Sippican software to read, but I'll add them for completeness. 

- As a example (fake data), the .edf files is a text file with the following format:

```
// This is a MK21 EXPORT DATA FILE  (EDF)
//
Date of Launch:  08/21/2011
Time of Launch:  22:08:28
Sequence #    :  2
Latitude      :  40 38.43994N
Longitude     :  71 23.12012W
Serial #      :  01125602
//
// Here are the contents of the memo fields.
//
//
// Here is some probe information for this drop.
//
Probe Type       :  T-7
Terminal Depth   :  760 m
Depth Equation   :  Standard
Depth Coeff. 1   :  0.0
Depth Coeff. 2   :  6.691
Depth Coeff. 3   :  -0.00225
Depth Coeff. 4   :  0.0
Pressure Pt Correction:  100.0%
//
Raw Data Filename:  C:\Program Files\Sippican\WinMK21\DATA\T7_00002.RDF
//
Display Units    :  Metric
//
// This XBT export file has not been noise reduced or averaged.
//
// Sound velocity derived with assumed salinity: 30.00 ppt
//
Depth (m) - Temperature (°C) - Sound Velocity (m/s)
0.0	21.00	1518.66
0.7	20.82	1518.16
1.3	20.77	1518.06
2.0	20.76	1518.03
```
- The data set will include XBTs that reach terminal depth and those that were launched in shallower waters.
 
Reasoning:
- It would be much nicer to read in these files instead of converting them to .csv and bringing them into the R environment to convert them to `oce` object.

**Comment by richardsc** [comment]
Thanks for the request! I got the data files, and for now we can use those to base an `.edf` parsing function from so they can be read into R/oce. It would be good to have some kind of official documentation about the file format (from Sippican?) so that we can build the function as general as possible rather than just from the examples we have. Do you know if such documentation exists?

@dankelley this might be a good place to have a discussion about a new object type to handle this data, since it is similar to CTD, but none of the standard CTD functions will apply because `ctd` objects require salinity. Of course, we could fake it by making a fake salinity column, but I think it would be better to start generally and create an `xbt` object type (which is more work, but better in the long run).

**Comment by dankelley** [comment]
@erinann -- 

1) I agree with Clark: it would help a lot if we could get a data-format specification. That way, we wouldn't be guessing about what items will be in the file, and how they will  formatted.  The initial work will be pretty easy, though.

2) Do you need this quickly or can you wait a few days?

3) Would it be okay if we put a snippet of your data (e.g. top 50m) into oce as a dataset? That way, we can write tests that will get performed as part of the building process, which will help a lot in ensuring that the code is reasonable.

@richardsc -- it's quite easy to make a new object type. I wonder, were you thinking of being at Dal someday soon?  An in-person discussion is the fastest way to make decisions about object structures.

**Comment by dankelley** [comment]
@erinann -- in https://github.com/dankelley/oce/blob/develop/sandbox/1494/1494a.R I just coded a very simple thing that might be enough to get you started, if you're in a rush.  Clark and I ought to talk before adding a new object type ... once that's done, we'll have generic functions for plotting etc.

**Comment by erinann** [comment]
@richardsc @dankelley 

Thank you for the quick feedback! 

1. Unfortunately I only have data from T-7 probes, which is one of the most popular. I can ask folks at NOAA and WHOI if they have examples of data files from other probes. I have not been able to find official documentation online about file structures online, but I'm not surprised - Lockheed Martin owns Sippican now.
https://www.lockheedmartin.com/en-us/products/oceanographic-instrumentation.html 

2. This can wait a few days. I am not in a rush at all.

3. Sure. The top 50 meters is fine. I'm a fan a unit tests.

**Comment by dankelley** [comment]
The sandbox code at  https://github.com/dankelley/oce/blob/develop/sandbox/1494/1494a.R now reads some metadata. I also did some tests on the soundspeed, in the 3-panel plot made by that code.  From that plot, I infer that the soundspeed column is in the UNESCO formulation. The wiggles in the mismatch might have to do with the number of digits displayed in the text file.  If we can get docs on the binary format, that could be tested ... well, if the data format is sufficiently simple (e.g. if they haven't used some made-in-house compression scheme).

As for section plots, I'd be pretty inclined to use the code in the sandbox to read in this object (which is still just an "oce" object, not a "xbt" object), then add a col with S=30 repeated out to the write length, then to use `as.ctd()` on that. Once that's done, you can use existing code in oce to do whatever you want, e.g. sections and so forth.

I consider the code in the sandbox to be very brittle. For example, I decode dates based on the file you provided. But maybe that format is because the file was created in a US locale. (Luckily, in your example file, I could guess the format because we only have 12 months etc.)  Similarly, the sandbox code makes assumptions on upper/lower case on items, and even the presence of a "(" in one of the header lines!

**Comment by erinann** [comment]
I haven't had any luck finding other XBT data files. The code in the sandbox has been a great starting point and very helpful for what I'm trying plot.  Thank you. I'll call the rep at Lockheed Martin next week to see if I can get examples of the different probes' data files.

**Comment by richardsc** [comment]
Thanks for the update @erinann . I was kind of waiting to see other file types before we made a whole new `xbt` object. One thing that I thought of is that a new object should be flexible enough to potentially handle other "X" instrument files ... such as XCTD, XSV, XCM, etc.

It just occurred to me that the yearly AR7W cruise that happens out of my institution (Bedford Institute) typically does XBTs across the Labrador Sea. I'll see if I can find the raw files in our data archive.

I've "pinned" this issue for now.

**Comment by dankelley** [comment]
I was doing some `grep` operations as part of addressing (unrelated) issue #1595 and ran across this code that I had written, in the sandbox.

@richardsc, if you can find files gathered by BIO, that would be great. It seems a shame to have written this code and not put it into `oce` so that folks can use it.  And it looks like a small effort to insert the code into `oce`, document it, etc. I'm inclined to just shove it in, on the assumption that it's better than nothing. Do you object?

**Comment by dankelley** [comment]
I ran across the following reference, which describes another (text) file format:

ftp://ftp.nodc.noaa.gov/nodc/archive/arc0056/0061984/1.1/data/0-data/xbt_decoding_format.pdf

**Comment by dankelley** [comment]
Here's one that seems to describe the `.edf` format that we now read:

http://www.marine-geo.org/references/formats/MK21XBT_EDF_DataFormat.pdf

**Comment by dankelley** [comment]
This issue has become a bit stagnant, so I'm adding this comment mainly to resurrect discussion.  I agree with an earlier comment (https://github.com/dankelley/oce/issues/1494#issuecomment-465245547) to make a new object type, and this is pretty easy.  Also, a basis for `read.xbt()` and `plot,xbt-method()` is at https://github.com/dankelley/oce/blob/develop/sandbox/1494/1494a.R so all we need is some docs and boilerplate code.  None of this is hard, and I'd rather fiddle with it in a couple of half-hour coding sessions than have an open issue.

**Comment by dankelley** [comment]
Another documentation file is 
https://pages.uoregon.edu/drt/MGL0910_Science_Report/attachments/MK21_ISA_Manual_Rev_A.pdf
which seems to have come from Sippican, originally.  There is actually a snippet file there, too, and perhaps that ought to go into oce as a sample file. The only problem is that it has only a few points near the surface, and then a few points much deeper, so it would look pretty weird, if plotted.

**Comment by richardsc** [comment]
Apologies for not yet finding the BIO archive of raw XBT data that we could test this on. I'll try and ping the LabSea PI tomorrow to see where I can find the files.

**Comment by dankelley** [comment]
Thanks re BIO archive. I just merged 'dk' into 'develop', so the latter has the xbt support that I added yesterday.  The sample file is weird (it's only 6 points; you can learn more with `?xbt`) so if we can find another, that would be great.  It would be even better if it came with a URL that could be employed by oce users.  (The advantage of the teen-wheeny file that we have now is that at least I can state a file source, even though it's from a document that I cannot find at any company website.)

A few other notes:
1. I did not code in an `as.xbt()` function.  I explain the reasoning for that in the commit notes for 360dc3a.
2. I am not converting `depth` to `pressure`, although I am tempted to do that.  The thing is, it's a bit of a guess, because they must be computing it by assuming that salinity equals 35.  I guess I could add a new column for `pressure`, making that assumption. Your thoughts, @richardsc?
3. There is no data item for `salinity`, although I think some xbt devices can do that.  (I think -- I was googling like nuts yesterday to find sample files and docs on a company website, and I think I ran across some xbts that had conductivity but that could be wrong.)

**Comment by erinann** [comment]
@dankelley and @richardsc 

I'm not sure if these websites are helpful, but I recently ran across them when looking for some GOOS data.

XBT data access:
https://www.aoml.noaa.gov/phod/goos/xbtscience/data.php
I don't see raw files, but it does give a listing of the different probe type.

re 2: https://github.com/dankelley/oce/issues/1494#issuecomment-530314150
XBT biases (how depth is computed):
https://www.aoml.noaa.gov/phod/goos/xbtscience/fre.php

re: 3 https://github.com/dankelley/oce/issues/1494#issuecomment-530314150: Probes that also collect conductivity are called XCTDs. 
http://www.tsk-jp.com/index.php?page=/product/detail/2/2
https://www.lockheedmartin.com/en-us/products/oceanographic-instrumentation.html

**Comment by dankelley** [comment]
@erinann those links are very helpful, thanks!

**Comment by dankelley** [comment]
Another format I'm seeing is e.g.
```
154.623 20100603 145733  -86.102  24.258 N42RF DWH5 16    2010-154-14:55:31
  -0.0 25.92 -9.99
  -1.5 25.92 -9.99
  -3.0 25.87 -9.99
  -4.5 25.81 -9.99
```
An example is a NOAA page about AXBT data (https://www.aoml.noaa.gov/phod/dhos/axbt.php), which has an FTP site (ftp://ftp.aoml.noaa.gov/phod/pub/DHI_Response/AXBT) with data in this format.

I am pretty sure I've seen files that are like this, but strung together. Reading these seems to be not a terribly hard thing, but there is also guesswork, e.g. the tokens on what seems to be a header might be
* dunno
* a date?
* a time?
* lon?
* lat?
* a bunch of "dunno"s
and the data lines seem to b
* z
* temperature
* dunno, but likely sound speed
with -9.99 being a missing value.

I would be reluctant to add code to oce to read something where I'm guessing this much, though. Writing this comment is about as hard as writing the code, but the problem with doing a lot of guesses is that users get exposed needlessly to code that may end up changing in new versions of oce. (Why "needless"? Because if someone actually needs to use such data, they likely know the format, and the better scheme is that they make an issue requesting it, upon which we would ask them to give a citation for the code format.)

**Comment by dankelley** [comment]
Oh, hang on, the ftp site has the file format, in a file called `readme.axbt`. I'm interested in these files for my class, so I'll code this.  I won't bother putting it into oce for a couple of days, though, to let others in this discussion thread object to the addition, if they feel it is unhelpful.

**Comment by dankelley** [comment]
This code is a start for this NOAA axbt format. (No roxygen docs yet, since this is just so I can use this toay.)
```R
library(oce)
read.axbt.type1 <- function(file, missingValue=-9.99)
{
    filename <- "?"
    if (is.character(file)) {
        filename <- fullFilename(file)
        file <- file(file, "r")
        on.exit(close(file))
    }
    if (!inherits(file, "connection"))
        stop("argument `file' must be a character string or connection")
    if (!isOpen(file)) {
        open(file, "r")
        on.exit(close(file))
    }
    res <- new("xbt")
    header <- readLines(file, 1)
    res@metadata$header <- header
    res@metadata$filename <- filename
    headerTokens <- strsplit(header, "[ \t]+")[[1]]
    res@metadata$time <- ISOdatetime(substr(headerTokens[2], 1, 4), # year
                                     substr(headerTokens[2], 5, 6), # month
                                     substr(headerTokens[2], 7, 8), # day
                                     substr(headerTokens[3], 1, 2), # hour
                                     substr(headerTokens[3], 3, 4), # minute
                                     substr(headerTokens[3], 5, 6)) # second
    res@metadata$longitude <- as.numeric(headerTokens[4])
    res@metadata$latitude <- as.numeric(headerTokens[5])
    data <- read.table(file, skip=1, header=FALSE, col.names=c("z", "temperature", "temperatureError"))
    res@metadata$header <- header
    res@metadata$units$z <- list(unit=expression(dbar), scale="")
    res@data <- as.list(data)
    if (!is.null(missingValue)) {
        for (name in names(res@data))
            res@data[[name]][res@data[[name]] == missingValue] <- NA
    }
    res
}
```
As an example,
```R
d <- read.axbt.type1("03june2010_axbt/20100603_145733_H")
summary(d)
```
produces
```
xbt summary
-----------

* File source:        "/Users/kelley/git/dalhousie/teaching/general/axbt/03june2010_axbt/20100603_145733_H"
* Longitude:          -86.102
* Latitude:           24.258
* Time:               2010-06-03 14:57:33
* Data Overview

                               Min.   Mean  Max. Dim. NAs OriginalName
    z [dbar]                 -319.5 -160.5  -1.5  213   0            -
    temperature [°C, ITS-90]  12.03 17.999 25.92  213   0            -
    temperatureError             NA     NA    NA  213 213            -

* Processing Log
    - 2019-09-17 11:21:37.170 UTC: `create 'xbt' object`
```

**Comment by dankelley** [comment]
I've put the code in the just-previous comment into oce as `read.xbt.noaa1()`. You need to call that explicitly, or call `read.xbt()` with a `type=` argument, to get the new feature. That's because I have not trained `oceMagic()` to understand this file type, because the file names are in a form that users might use for their own files of arbitrary purpose, and the first line (recall https://github.com/dankelley/oce/issues/1494#issuecomment-532168850) does not seem to be very amenable to type detection.

**Comment by dankelley** [comment]
After an f2f with @richardsc today, I had a look in `tests/test/test_xbt.R`, which I'm putting below. It shows that `read.oce()` works now.  

I propose to close this issue in a few days, unless someone objects.

```R
## vim:textwidth=120:expandtab:shiftwidth=2:softtabstop=2
library(oce)
data("xbt")

context("xbt (expendible bathythermograph)")

test_that("as.xbt() works", {
          XBT <- as.xbt(z=-xbt[["depth"]], temperature=xbt[["temperature"]])
          expect_equal(XBT[["units"]], list(temperature=list(unit=expression(degree*C), scale="ITS-90"),
                                            z=list(unit=expression(m), scale="")))
          expect_equal(XBT[["z"]], -xbt[["depth"]])
          expect_equal(XBT[["temperature"]], xbt[["temperature"]])
})

test_that("can read .edf file correctly", {
          XBT <- read.oce(system.file("extdata", "xbt.edf", package="oce"))
          expect_equal(XBT@metadata[c("serialNumber", "sequenceNumber", "dataNamesOriginal", "latitude",
                                      "longitude", "probeType","terminalDepth")],
                       list(serialNumber="0",
                            sequenceNumber=49L,
                            dataNamesOriginal=list(depth="Depth", temperature= "Temperature", soundSpeed="Sound Velocity"),
                            latitude=-4, longitude=4.005, probeType="T-4", terminalDepth=460))
          expect_equal(XBT[["data"]],
                       list(depth = c(5.4, 6, 6.7, 7.4, 8, 8.7),
                            temperature = c(20.91, 20.91, 20.91, 20.9, 20.9, 20.9),
                            soundSpeed = c(1575.31, 1575.32, 1575.33, 1575.34, 1575.35, 1575.36)))
})

test_that("data(xbt) and inst/extdata/xbt.edf match", {
          XBT <- read.oce(system.file("extdata", "xbt.edf", package="oce"))
          expect_equal(xbt@metadata[c("serialNumber", "sequenceNumber", "dataNamesOriginal", "latitude",
                                      "longitude", "probeType","terminalDepth")],
                       XBT@metadata[c("serialNumber", "sequenceNumber", "dataNamesOriginal", "latitude",
                                      "longitude", "probeType","terminalDepth")])
          expect_equal(XBT[["data"]], xbt[["data"]])
})

test_that("[[ works for 'z', 'depth', and 'pressure' (given depth)", {
          expect_equal(xbt[["z"]], -c(5.4, 6, 6.7, 7.4, 8, 8.7))
          expect_equal(xbt[["depth"]], c(5.4, 6, 6.7, 7.4, 8, 8.7))
          expect_equal(xbt[["pressure"]], swPressure(-xbt[["z"]], xbt[["latitude"]]))
})
```

**Comment by dankelley** [comment]
I'm closing this, because my plan to close it "in a few days" was over two weeks ago.  (Sorry, I forgot about my plan!). Of course, this can be reopened, if required.
