### ISSUE TITLE
Need function to trim ADCP data using `br`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1497]
This came up in Issue #1496 that one of the main uses for the `br` (bottom range) field is to be able to trim the ADCP data of all the values *beyond* the range, because they are not valid data. `subset,adp-method` won't work for this (I don't think), because the `br` are not constant. So you can't do as with `distance`, say
```r
ds <- subset(d, distance < 100)
```

I will dig out some code that I have used to do this in the past, which may form a basis for a new function in `oce`.

**Comment by dankelley** [comment]
Possibly related -- the other day I was making a map with contours created by the Barnes method. That method will let contours go through land, and so the labelling of the `mapContours` was not good. I was thinking "hm, we need a generic for setting data to NA under certain conditions." This seems like maybe a case in point, since if we subset an array in a ragged way, it won't quite be an array anymore ... I think we need to use `NA` for such things.

I'll be offline for a few hours now.

**Comment by richardsc** [comment]
Here is an example (from a larger script) of how I have done this previously:

```r
## despike bottom range
for (i in 1:4) {
    d[['br']][,i] <- despike(d[['br']][,i])
    d[['br']][,i] <- approx(d[['time']], d[['br']][,i], d[['time']])$y
}

## trim sub-bottom bins
mask <- array(1, dim=dim(d[['v']]))
for (i in 1:4) {
    for (j in seq_along(d[['time']])) {
        II <- d[['distance']] > 0.85*(d[['br']][j,i])
        mask[j, II ,i] <- NA
    }
}
d[['v']] <- d[['v']]*mask
d[['a']] <- d[['a', 'numeric']]*mask
```

Note the hard-coded `0.85` factor -- this has to do with the beam angle and the need to reject velocity data which is close to the surface (could be the bottom or the surface for an upward looking instrument) due to contamination from the side lobes). There is a general rule for this (based on beam angle), but it might be good to have this as an arg (with the general rule as the default value).

The general rule is documented on Page 38 of the [Practical Primer](http://www.comm-tec.com/Docs/Manuali/RDI/BBPRIME.pdf)

![screen shot 2019-02-21 at 10 01 03 am](https://user-images.githubusercontent.com/233584/53174231-b7c9eb80-35bf-11e9-8275-f6c5cf84fd93.png)

**Comment by dankelley** [comment]
So maybe a good name for the generic is `mask()` ... ?

**Comment by richardsc** [comment]
Hmmm ... I think that's *too* generic of a name, at least for the `adp` case ...

Or are you thinking of making a generic that could be used for other data types as well (ctd, etc)? 

I was thinking something like `adpMask()`. I think we should wait on this, and have a face-to-face chat.

**Comment by dankelley** [comment]
I agree on f2f, thanks.

**Comment by dankelley** [comment]
@richardsc -- I wonder whether this ought to be closed. We've not had any action on it in 7 months.  You're assigned the issue, so of course it's up to you to decide.

**Comment by dankelley** [comment]
@richardsc it's been 10 months since the last comment in this issue, and that comment was just to note that it had been 7 months since the previous comment.

Maybe it's time to remove the "pinned" tag, so that github will autosend a reminder in a month, if no action takes place.  But, since I am not the original reporter, nor someone who is likely to make the code fix, I do not feel that it's my place to do that ... any thoughts on this, @richardsc

**Comment by dankelley** [comment]
I unpinned this, because no user has requested it in a long time, so I think it falls into the "would be nice" category, and not the "must have" category.

**Comment by richardsc** [comment]
Closing based on vf2f with @dankelley

**Comment by richardsc** [comment]
Leaving a comment here for @j-harbin, because this was something that we were talking about yesterday (removing data below the bottom). I told you that I thought there was a function to do this already in oce, but you can see from the discussion that @dankelley and I were too lazy (😄 ) to actually add something ....

There is a good example above for what you'll want to do for this.
