### ISSUE TITLE
`flipy` argument for oce.plot.ts

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1515]
`imagep()` has the very handy `flipy=` argument, and I'd like to request that `oce.plot.ts()` gains it as well. 

This would be useful for e.g. plotting glider "swoops" (as @dankelley says) as a time series of pressure.

**Comment by dankelley** [comment]
Good idea, especially for glider valloops.

**Comment by dankelley** [comment]
Commit d08b628b4b55fca1c969086c218a1d1959d6254a in the "develop" branch has this new arg. 

Note that I have coded it so that the y axis will be flipped *even if* you set a `ylim`. That is because I use a `sort` in `R/oce.R` line 1234.  I can change that part, if desired, but I think that is what most people would expect if we say the y axis is "flipped". I am taking the verb "to flip" to apply to the axis, *not* to the range/ylim.  I think this is clearly stated in the doc.

Obviously, I can change the `flipy`/`ylim` interaction (I just need to remove the `sort()` call) but since this is an oft-used function, I'd prefer to do that sometime in the next few days because that will have fewer ripple effects than changing it a few months from now. So, please think about whether you like that part.

The docs have an example. Maybe I should add one more, in which `ylim` is given--think so?

Finally, I wouldn't mind a code review, to be sure I caught all the cases (of which I think there are only 3).

**Comment by richardsc** [comment]
Huh, that's a good idea on the `sort()` approach to specifying a `ylim` with `flipy=TRUE`.

I'll try it out, but I like the idea of it for sure. It would probably make sense to add the same behaviour to `imagep()`, which also has a `flipy` arg, to be consistent.

**Comment by dankelley** [comment]
Hm, I see that
```R
imagep(seq_len(nrow(volcano)), seq_len(ncol(volcano)), volcano,ylim=c(61,1),flipy=TRUE)
```
does *not* do as I have just made happen for `oce.plot.ts()`.  (It creates y axis increasing up the pag.)

I don't want `oce.plot.ts` and `imagep` to differ. And I don't think we can make `oce.plot.ts` alter its behaviour, given that (a) people and code are using the existing behaviour and (b) nobody has asked for a change.

Therefore, I plan to change the new `oce.plot.ts` behaviour w.r.t. `flipy` tomorrow (Mon) morning at 1030, unless I hear an argument against this plan sometime before then.

**Comment by richardsc** [comment]
I'm a bit torn.

On the one hand, I agree we don't want the `flipy` arg in `oce.plot.ts` and `imagep` to have different behaviour.

On the other, making changes to things that have been around a long time (the `flipy` behaviour in `imagep`) could be a pain for users who are used to args.

But, I doubt that there are many users who would have used `imagep(..., flipy=TRUE, ylim=...)`, so I think that a behaviour change there would have minimal consequence.

And thinking about it, I *like* the new behaviour. In fact, in many instances of recent work (such as the swoops that caused me to open this) it would have saved me typing.

We need a tie-breaker opinion, perhaps ...

@clayton33?

**Comment by dankelley** [comment]
Let's do this numerically, on the scale of -1=*keep `imagep` handling of `flipy` as it is* to +1=*make `imagep` agree with days-old `oce.plot.ts` handling of `flipy`. Since this has 0 at the centre, we can find a decision by adding votes (so long as people respect the meaning of +-1, which is strong endorsement of the respective proposition).

I vote -0.25, i.e. I think it is sensible to change `imagep`, but I have slight resistance to it. (The resistance is slight partly because if I make the change, users will immediately see the difference, this being something oceanographers are attuned to, and so they will consult the docs and see the change described clearly.)

**Comment by richardsc** [comment]
Can you move the above comment to a new (and specific) issue about `imagep()` only? We're getting some issue creep here that won't be easy to figure out if someone comes here searching about issues related to imagep and flipy.

**Comment by dankelley** [comment]
Good point -- I moved to a new issue. I also wrote up some text that might be thought of as a first draft for future votes, so please let me know if you would like to change any of that text.  (Once it is agreed upon, I can make an issue-snippet thing for it, so creating a comment with that skeleton will just involve a mouse operation.)

**Comment by dankelley** [comment]
I think this is done now (in "develop") but I am a bit lost in the comment thread. I wonder if @richardsc can try out what is in "develop", and either make a comment reporting his thoughts or close the issue?

Thanks! I think I will be using `flipy` in `oce.plot.ts()` quite a lot, since it's easier to type than `ylim=rev(range(y,na.rm=TRUE))`.

**Comment by richardsc** [comment]
Looks good to me!

And yes, what caused me to open this issue was that I started thinking about how I could make a macro for `ylim=rev(range(y,na.rm=TRUE))` ...

**Comment by dankelley** [comment]
Um, in oce we ask reports to close issues ... 🎐 (that icon was supposed to be a wink but wind-chime came up in the selection list, and I thought that was neat although the icon looks nothing like a windchime to me)

**Comment by richardsc** [comment]
D'oh. Sorry. I saw the red "closed" just above from the link with issue 1516 and thought you had already closed it.
