### ISSUE TITLE
Extracting the bottom amplitude from RDI WH 4 beams ADCP 

### ISSUE THREAD

**Issue by koRneel82** [dankelley/oce#1529]
Hello.
I was wondering if one could map ADCP bottom amplitudes for each beam similarly to what multibeam systems are typically generating (backscatter maps). It think that Rich Pawlowicz https://www.eoas.ubc.ca/~rich/#RDADCP  is outputting this kind of variable (bt_ampl in his matlab function rdradcp.m) - but I could not really figure out how ? Is there a similar output variable in read.adp.rdi perhaps? Thanks in advance.

**Comment by dankelley** [comment]
Maybe you could draw a sketch of what you want and post it?  (I don't have Rich's code set up; @richardsc might know what you mean, though.)

**Comment by richardsc** [comment]
There are a lot of different cases of files that have some things and not others. It depends on whether the ADCP is sampling in self-contained mode, with VMDAS, with WinRiver, etc etc ...

I do notice that at line 1238 in `adp.rdi.R` there is code to read the bottom amplitude (`ba`):
```r
                            br[i, ] <- 0.01 * (65536 * rangeMSB + rangeLSB)
                            bv[i, ] <- 0.001 * readBin(buf[o+c(24:31)], "integer", n=4, size=2, signed=TRUE, endian="little")
                            bc[i, ] <- as.integer(buf[o+32:35])
                            ba[i, ] <- as.integer(buf[o+36:39])
                            bg[i, ] <- as.integer(buf[o+40:43])
```

I don't have any files for which that seems to be enabled (that I know of -- I usually only care about `br` and `bv`, the range and velocity).

If you can send your data file (to `clark.richards@gmail.com` and `dan.kelley@gmail.com`) I can take a look.

**Comment by richardsc** [comment]
Thanks for sending the file. I'm just taking a look, but I think I see why you're not getting all the "bottom" data types (i.e. all the things named `b*`) when you read the file.

Just testing now and will push a fix shortly.

**Comment by richardsc** [comment]
Fixed with commit a70435c1a750. 
```r
library(oce)
d <- read.oce('subset')
par(mfrow=c(4,1))
for (i in 1:4) {oce.plot.ts(d[['time']], d[['ba']][,i])}
```

![image](https://user-images.githubusercontent.com/233584/56176144-7d356b80-5fd0-11e9-9495-682d0037c781.png)

**Comment by richardsc** [comment]
Thanks for pointing this out! It was just a silly mis-type in the code.

**Comment by koRneel82** [comment]
Thanks for verifying this!
Two more questions though:
1/ How can I update your package in RStudio. There is no update for OCE
indicated, as far as I see.
2/ Regarding the bottom amplitude, at 58:00 the ship enters the harbor that
is characterized with a muddy bottom.. is this the reason why there is a
much lower bottom amplitude? What do the zero values mean (no backscatter
amplitude at all = total absorption?)


Op di 16 apr. 2019 om 03:49 schreef Clark Richards <notifications@github.com

**Comment by richardsc** [comment]
Hi @koRneel82 . To update the package using the development version I recommend option 3 from here:

https://dankelley.github.io/oce/installation.html

That is, use the `devtools` package and the `install_github()` function. To do this you will need to be setup on your system to build packages that require compilation of C and Fortran code (which oce uses). On windows you should only need to install ["Rtools"](https://cran.r-project.org/bin/windows/Rtools/). On OSX it can be a little more complicated (but there are some instructions at the bottom of the page).

As for why the amplitudes go low, your theory sounds reasonable but I am not an expert in acoustics and sediments. I'd be a little surprised that a muddy bottom wouldn't return *any* signal at all (especially since it's only 15m deep), but I'm sure someone at RDI might have a better idea.

Unless you have a known application, and some theory, I would be a little careful about over-interpreting the bottom track amplitudes that you get from the ADCP for any kind of "map". The ADCP bt is not at all like a multibeam system (for one thing, the beams are angled, and broadband, and mixed with both bottom track and "profile" pings, etc). There is literature about how to use the "profile" pings to estimate suspended sediment concentrations, but I'm not aware of any kind of bottom classification using ADCP bottom track. Like I said though, I'm not an expert.

**Comment by koRneel82** [comment]
A quote from RDI: "My understanding, is that the data shows the “Echo amplitude” at the bottom for each Beam. I confirm that the more the sea bed is reflective ( rocks, concreate,  cobles ) the more the echo amplitude will be powerful, but it also depends of the Bottom range. As this graph is not corrected for the water column absorption, so unless you know that you are in shallow water it is difficult to estimate the nature of the bottom. In your case we have additional info, because we know that the ship is entering on the harbor with no significant change in the Water depth, so in this case the decrease in the echo intensity actually corresponds to a change in the bottom material ( certainly mud or sediments )  but if you are in open sea a change in the echo intensity can also be due to a change in the bottom range  ( attenuation due to the sound travel in the water column )"

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
