### ISSUE TITLE
Question : sectionSmooth suitable to make pretty section plots

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1540]
For a report that I have been working on, it has been requested that the section plots I create not have any white space, and that some interpolation should be done. I came across ```sectionSmooth``` today, but see that it hasn't really been touched in a hot second (7 years). It has barnes interpolation as a method which looks promising, but just wanted to get your opinion, and maybe some suggestions, if it is suitable, how to choose parameters for the barnes, I've used it in the past, but have totally forgotten, and I know you're kind of the expert @dankelley. 

PS. I brought this function up to @richardsc today and he didn't know it existed

PPS. I might be at Dal Friday afternoon if you want to have a f2f on this subject matter. I feel the same a @richardsc on this matter of interpolating ctd sections, but sometimes ya just gotta please the bosses.

**Comment by dankelley** [comment]
"hot second" -- I like that!  Sorry, I was doing a long meeting yesterday and didn't see these issues and emails. I'll have a f2f with @richardsc today, I think, and likely he can bring me more up to speed (e.g. maybe this is solved already).

**Comment by dankelley** [comment]
Hm. A test code
```R
library(oce)
load("~/Dropbox/ctds.rda")
s <- as.section(ctds)
ss <- sectionSmooth(s, method="barnes")
```
ought to work, according to the docs, but I get
```R
Error in sectionSmooth(s, method = "barnes") : 
  pressure mismatch between station 1 and station2
Execution halted
```
so I'll look into that, since its docs do not say that pressures have to be aligned.

I have some concerns about the Barnes method for gridding in the x-z plane, although I think it has some promise in the x-y plane.  I think maybe you and @richardsc have chatted about this sort of thing, too, and it's likely too long for discussion here.  My guess is that all three of us are in general agreement about the pros and cons of what I might call "fancy" methods ...

**Comment by dankelley** [comment]
I see what's going on. I'm testing for pressure commonality between stations in `R/section.R` lines 2693 to 2701. But this loop is really just for getting max pressure, for which a simple `lapply` will do! And then I am defining `P` in line 2703, by repeating pressures. So the fix may be quite simple. However, I have a meeting this aft and therefore will likely fix this tomorrow morning. (In other words, my listing of line numbers here is just a reminder to myself of where to pick this up again later, when I have a half hour.)

**Comment by clayton33** [comment]
I think the section object provided to ```sectionSmooth``` needs to be gridded first using ```sectionGrid```, when I do the same as you above, but grid it first, I get

```
Error in interpBarnes(X, P, v, xg = xg, yg = yg, xgl = xgl, ygl = ygl,  : 
  lengths of x and z disagree; they are 1840 and 1472
```

setting ```debug = 10``` reveals (output chopped to last few lines),

```
  smoothing par 
    interpBarnes(x, ...) {
Error in interpBarnes(X, P, v, xg = xg, yg = yg, xgl = xgl, ygl = ygl,  : 
  lengths of x and z disagree; they are 1840 and 1472
```

**Comment by dankelley** [comment]
Hm, there was a build-check going on in the background, and it spat out the following. However, when I run this interactively, there is no error. I'll look at this tomorrow, but I sort of think it's a whacky thing related to how I just downgraded Rstudio (e.g. it also whined that I don't have the `R.utils` library in my system ... that seems like an installation problem, not an oce one!)

```R
❯ checking examples ... ERROR
  Running examples in ‘oce-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: plot,section-method
  > ### Title: Plot a Section
  > ### Aliases: plot,section-method plot.section
  > 
  > ### ** Examples
  > 
  > library(oce)
  > data(section)
  > sg <- sectionGrid(section)
  > 
  > ## 1. start of section, default fields.
  > plot(head(section))
  Warning in min(x, na.rm = na.rm) :
    no non-missing arguments to min; returning Inf
  Warning in max(x, na.rm = na.rm) :
    no non-missing arguments to max; returning -Inf
  Warning in min(x, na.rm = na.rm) :
    no non-missing arguments to min; returning Inf
  Warning in max(x, na.rm = na.rm) :
    no non-missing arguments to max; returning -Inf
  Warning in min(x, na.rm = na.rm) :
    no non-missing arguments to min; returning Inf
  Warning in max(x, na.rm = na.rm) :
    no non-missing arguments to max; returning -Inf
  Error in plotSubsection(xx, yy, zz, which.xtype, which.ytype, which[w],  : 
    cannot draw a contour diagram because all values are NA or Inf
  Calls: plot -> plot -> .local -> plotSubsection
  Execution halted
```

**Comment by dankelley** [comment]
I was quite mixed up regarding the just-previous comment (https://github.com/dankelley/oce/issues/1540#issuecomment-488342138). That comment lists what I get with `devtools::check()`, locally, on "develop" branch commit 7a2a9f2c921dbd3250e20b1e3900881826764a0a. And the same error comes up with the travis-ci build (see https://api.travis-ci.org/v3/job/526955397/log.txt and search for the string `"head("` in the browser on that file).

Basically, I was seeing that things worked when I did them interactively, and when I did the *test* menu in RStudio, but not when I did the *check* menu in RStudio.

Ohhhh... I see (as below) this I get interactive failure if I switch to the UNESCO eos. So that's something I can look into. Plus, I've learned something: the *check* menu (equivalently, running `devtools::check()` must not be using the settings in the user's `~/.Rprofile` file.
```R
> plot(head(section))
> options(oceEOS="unesco")
> plot(head(section))
Error in plotSubsection(xx, yy, zz, which.xtype, which.ytype, which[w],  : 
  cannot draw a contour diagram because all values are NA or Inf
In addition: Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
3: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
4: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
5: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
6: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf
```

**Comment by dankelley** [comment]
I've made some progress, e.g. below is a screenshot of the result from `example("sectionSmooth")` using the "develop" branch. There are remaining problems, which I've noted in the commit note, and also I don't see in that screenshot why the spline method is not getting numbers at the surface (I'll check into that).

commit f33fc9fb05937232e40255719858e74b4b944ec2
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu May 2 11:22:58 2019 -0300

    sectionSmooth(..., method="barnes") improved
    
    It no longer requires pre-gridding to pressure levels.
    
    See
    https://github.com/dankelley/oce/issues/1539
    and
    https://github.com/dankelley/oce/issues/1540
    for some discussion of issues that led to this change.
    
    A good way to see this in action is to use
    
    example("sectionSmooth")
    
    There are several problems remaining:
    
    1. the units are not copied over from the original data
    2. does smoothing handle NA data?
    3. what about the bottom -- should we interpolate
       that, so plots get nicer?


![Rplot](https://user-images.githubusercontent.com/99469/57082580-60d24800-6ccd-11e9-8a10-09234f35aadc.png)

**Comment by dankelley** [comment]
@clayton33 -- any chance you could try out the "develop" version on your data?  I've not tested how it handles NA for the Barnes method. I don't really encourage the Barnes method in general, because it "makes up" data, as you can see if you do the above with more contours (you'll see that it draws contours through the ground).

I'm checking back in with you because I've gone down some rabbitholes, fixing odd things. The commit note in the just-previous comment mentions some things that remain, but I won't be looking again until this aft.

PS. on a big dataset, Barnes is annoyingly slow. I think (see comments in the C code) that I can speed it up by about a factor of 3, by using an approximation to the `exp()` function that I wrote when I did stuff by writing C code and plotting in `gri` (this goes back some time; see https://en.wikipedia.org/wiki/Book_of_Genesis)

**Comment by clayton33** [comment]
Didn't complain when I tried out the ```spline``` method, so I'm not sure if anything changed, and I pre-grid my data. When trying the ```barnes``` method, I'm still getting the lengths disagreement error.

**Comment by dankelley** [comment]
Can you give a test code?  I'm getting slightly lost (not an unusual thing).

**Comment by dankelley** [comment]
Oh, I see. Below is a testcode
```R
library(oce)
load("~/Dropbox/ctds_par.rda")
s <- as.section(ctds)
ss<-sectionSmooth(s,method="barnes")
```
and it makes error
```R
 Error in interpBarnes(X, P, v, xg = xg, yg = yg, xgl = xgl, ygl = ygl,  : 
  lengths of x and z disagree; they are 713 and 349 
3.
stop("lengths of x and z disagree; they are ", n, " and ", length(z)) at misc.R#3134
2.
interpBarnes(X, P, v, xg = xg, yg = yg, xgl = xgl, ygl = ygl, 
    xr = xr, yr = yr, gamma = gamma, iterations = iterations, 
    trim = trim, debug = debug - 1) at section.R#2755
1.
sectionSmooth(s, method = "barnes") 
```

**Comment by clayton33** [comment]
*Ding, ding*
Same for applying ```sectionGrid``` first

```
library(oce)
load('ctds.rda')
cs <- as.section(ctds)
csg <- sectionGrid(cs, p = seq(0, max(cs[["pressure"]], na.rm = TRUE),1))
csgs <- sectionSmooth(section = csg, method = 'barnes', xr = 10, yr = 5)
```
gives
```
Error in interpBarnes(X, P, v, xg = xg, yg = yg, xgl = xgl, ygl = ygl,  : 
  lengths of x and z disagree; they are 1840 and 1472
```

**Comment by dankelley** [comment]
Maybe try again (see commit note for test -- I renamed the .rda to avoid conflicts)
```R
commit fffb4c276dac77321031bc2e80731ad3a5e6f563
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu May 2 12:38:22 2019 -0300

    sectionSmooth(method="barnes") OK w/ missing data?
    
    library(oce)
    load("~/Dropbox/ctds_par.rda")
    s <- as.section(ctds)
    ss <- sectionSmooth(s, method="barnes", xgl=20, ygl=20, xr=20, yr=50)
    plot(ss, which="par", ztype="image")

```

**Comment by clayton33** [comment]
line 2704, should be ```section[['station]]``` , not ```s[['station']]```

**Comment by dankelley** [comment]
Fixed in "develop", thanks!
