### ISSUE TITLE
sectionSmooth() not keeping metadata

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1544]
Playing around with some of the new `sectionSmooth()` functionality, I noticed that the smoothed object doesn't keep all the original metadata (e.g. units and flags, at least).
```r
library(oce)
data(section)
ss <- sectionSmooth(sectionGrid(section))
str(ss@metadata)
```
```
List of 9
 $ units    : list()
 $ flags    : list()
 $ filename : chr "a03_hy1.csv"
 $ sectionId: chr "a03"
 $ header   : chr [1:7] "BOTTLE,20001102WHPSIOJJW" "#code : jjward hyd_to_exchange.pl V1.0" "#original files copied from HTML directory: 2000.09.25" "#original HYD file: a03hy.txt   Fri Oct 27 14:26:11 2000" ...
 $ stationId: chr [1:124] "3" "4" "6" "7" ...
 $ longitude: num [1:124] -8.53 -8.62 -8.74 -8.79 -8.9 ...
 $ latitude : num [1:124] 36.9 36.7 36.5 36.4 36.2 ...
 $ time     : POSIXct[1:124], format: "1993-09-23 22:22:00" "1993-09-24 00:13:00" ...
```

**Comment by dankelley** [comment]
Thanks -- I have this on my radar but hadn't made an issue for it. I'm making a checklist that I'll complete as I get things done.

1. [ ] Units: this is pretty easy and I'll do that soon.

2. [ ] Flags: I plan to mark everything as some initial (unchecked) state, since "smoothing" flags is not too sensible.

3. [ ] `scan`: like flags, smoothing makes no sense. I think `scan` simply disappears, and I think that's the right thing, although I suppose I could make up values 1, 2, etc., for the scan in each station.

4. [ ] `time`: Hm, smoothing that makes no sense so I'm not even sure how that got in there. I think `time` ought to be omitted from the smoothed result.

**Comment by dankelley** [comment]
commit 1144174903558f9316968c6f27cfe386d6681e12
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue May 7 13:50:35 2019 -0300

    sectionSmooth() creates flags (set to NA)

**Comment by dankelley** [comment]
Oh, and re that last commit, we also now have a check on the newly-added flag names. The values are set to `NA`, which I think is sensible because we are not imposing strict rules on flag schemes, so "not checked" might be any one of several numerical codes.

**Comment by dankelley** [comment]
I think it's fixed in develop branch. Maybe you can check sometime?

**Comment by dankelley** [comment]
@richardsc since we may be getting a CRAN submission later in the month, I wonder if you can have a check (perhaps within a week or so) to see if this issue is still a problem, so we aren't submitting something with a bug fix that actually causes a new bug?

**Comment by richardsc** [comment]
Looks good!
