### ISSUE TITLE
Plot ADCP progressive vector fit not working

### ISSUE THREAD

**Issue by cjpratt94** [dankelley/oce#1578]
For example
```R
> plot(deu, which=23)
Error in integrateTrapezoid(ttt, u, "cA") : 
  'x' and 'y' must be of same length
```

**Comment by dankelley** [comment]
FYI (to other developers): I have a private data file to test this.

**Comment by dankelley** [comment]
I think this is working now, in the version I describe in a comment at #1579 (please also see that comment, on how to test). When I do
```R
d<-read.oce("/Volumes/GLIDER_DATA/PER2018043_Sentinel-V_132_54_Ship-Harbour-Deep_M2067_May18-Nov18.pd0")
denu <- toEnu(d)
plot(denu,which="progressiveVector")
```
I get a plot like below. As I mentioned when we spoke in person, this graph starts at x=y=0.  Thus, the indication is of a current that goes roughly westward. That may be the wrong direction, since I don't know about whether the declination was set up right, and so forth ... basically I don't know anything about the data file.  Still, I feel that the reading went OK since at least we see here a background current with some wiggles (maybe tides) and perturbations (maybe wind events) so this doesn't look like the kind of random noise you can get if you read a dataset incorrectly (mixing up bytes, etc).  

In case you want to explore further, the following snippet shows what you might start with:
```R
> U<-d[["v"]][,1,1]
> sd(U)
[1] 0.08942394
> mean(U)
[1] -0.01020983
> V<-d[["v"]][,1,2]
> sd(V)
[1] 0.08266551
> mean(V)
[1] 0.01048767
```
which suggests mean currents in bin 1 (nearest the device, I think) are only about 1cm/s whereas the std-dev is more like 8cm/s. By contrast, things are faster further away
```R
> V<-d[["v"]][,55,2]
> sd(V,na.rm=TRUE)
[1] 0.4002131
> mean(V,na.rm=TRUE)
[1] -0.03583006
```
but you'd want to examine the image plots to decide how much to believe the far-away data (there can be problems of surface reflection).

![Screen Shot 2019-06-26 at 10 46 35 AM](https://user-images.githubusercontent.com/99469/60185098-b58ecc80-97ff-11e9-860d-014e460075e1.png)

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
