### ISSUE TITLE
Backscatter Calculations 

### ISSUE THREAD

**Issue by bjvt** [dankelley/oce#1581]
Problem Summary,

Verifying the WinRiver II back scatter values to variables available in "read.adp.rdi"

Details:

I’m trying to figure out how to extract back-scatter data from my PD0 file off an RDI Workhorse using read.oce.adp.  My first task is to compare and understand the algorithms that produce the WinRiver II back-scatter values whose algorithm is shown in the WinRiver II manual.

I know plot(adcp_master, which=5:8) produces a nice plot, and “which=5:8” according to the oce.pdf is a value derived from a1 to a4.  I’d like to find the numeric value in dB for the back-scatter and unsure which algorithm “which=5:8” uses.  I’m also trying to use the adcp_master[["a"]], and compare it to the WinRiver II table.  

The questions are below, sorry there is more than one, and can separate into different issues if desired.  If I did this right, the link to the data is
https://www.dropbox.com/sh/mdewq6gvay26y99/AACbLF-2jWBhQ24SECe7qI3Xa?dl=0

    1. Does the WinRiver II calculate the back-scatter, and this value isn’t picked up by the read.oce.adp?  I have read the closed oce issue #1169 and believe these are raw counts before any processing.
    2. Does the “which 5:8” calculate the value derived from a1 to a4?
    3. adcp_master[["ba"]] gives a dimension of 6,4.  Apparently this means you present an algorithm for back-scatter for the ensembles’ column, but still keeping the 4 beams separate?
    4. I’m stuck on how to find the average of the ‘a’ values given by adcp_master[["a", "numeric"]]. My dim(adcp_master@data$a) is 6,13,4 (ensemble, bins, beams), and I believe that after averaging the ‘a’ beams, I should get a 6,13,1?  I do not know how to do this.
    5. I’m learning R S4 and the formal class method.  Apparently data frames are only 2 dimensional, so adcp_master[["a", "numeric"]] can’t be a data frame unless you collapse it into to dimensions which is this case, if I do as.data.frame(adcp_master[["a"]]) is 6,52.  doing an average on the 4 beams is difficult, as I somehow has to make 4 data frames, 13 columns across.

### How urgent is this?
This is not urgent

**Comment by richardsc** [comment]
Hi Barry (@bjvt)

I'll try and answer as best as I can (and to the best of my knowledge). Neither Dan nor I really have much experience with WinRiverII, as the world of "stream flow" measurements is not a typical use case in oceanography (which is why we wrote the code to read RDI ADCP data in the first place).

> 1. Does the WinRiver II calculate the back-scatter, and this value isn’t picked up by the read.oce.adp?  I have read the closed oce issue #1169 and believe these are raw counts before any processing.

I don't know what WinRiver does with the backscatter, but I can tell you what `oce` does: essentially nothing. As you noted in #1169 we read the *raw* backscatter (or echo amplitude) as it is stored in the file, in *counts*. Any conversion to anything resembling volume backscatter strength must be done after reading the raw values from the file. It's possible WinRiver does this automatically.

There is a function in oce, called `beamUnspreadAdp()` which does a *very simple* count to dB conversion, and then corrects for the effect of spherical spreading. Importantly, this doesn't account for any absorption effects (either from water or suspended matter absorption). There is a classic paper by Deines (1999, I think) that lays out much of this which underpins much of the backscatter work done for oceanographic applications.

https://pdfs.semanticscholar.org/e8e5/b5151a8788b21d9cce0f2cdd720e687b938b.pdf

> 2. Does the “which 5:8” calculate the value derived from a1 to a4?

Using `which=5:8` simply plots whatever backscatter is contained in the adp object. If it was read from a PD0 file, then it will be the backscatter in counts. Plotting it this way does not do any calculations.

I should note that the way backscatter (called `a`) is stored in the object is in "raw" form. This was done partly because expanding from the raw binary format to floating point requires 4 times the memory space. When working with large ADCP data sets (frequent in oceanography) this can cause memory errors.

To get the fields stored as `raw` into a numeric form, you can use the `[[` accessor with the optional argument:
```r
adcp[["a", "numeric"]]
```

> 3. adcp_master[["ba"]] gives a dimension of 6,4.  Apparently this means you present an algorithm for back-scatter for the ensembles’ column, but still keeping the 4 beams separate?

The `ba` field is for the amplitude returned from the **bottom track** ping. It is not an average of the regular bin backscatter values.

> 4. I’m stuck on how to find the average of the ‘a’ values given by adcp_master[["a", "numeric"]]. My dim(adcp_master@data$a) is 6,13,4 (ensemble, bins, beams), and I believe that after averaging the ‘a’ beams, I should get a 6,13,1?  I do not know how to do this.

The easiest way to average a 3D array down to a 2D one is to use the `apply()` function in R. It's kind of tricky, but once you "get it" you'll be impressed with what it can do. For your case, you want to create averages of the 4 beams (so you only have 1 profile per ensemble), you would do:
```r
beam_averaged_backscatter <- apply(d[['a', 'numeric']], c(1, 2), mean, na.rm=TRUE)
```
here the `c(1, 2)` specifies the dimensions you want to *keep* -- in other words, you average *along* them so that you remove the 3rd dimension. The third argument is the function you want to "apply" and arguments after that are passed to the function being applied (`na.rm=TRUE` is very common in such cases, because you don't want a single `NA` to wipe out an entire bin).

If you wanted to average backscatter across all *depths*, but keep the beams separate, you would do:
```
apply(d[['a', 'numeric']], c(1, 3), mean, na.rm=TRUE)
```

and if you wanted to average across time (dim1) and beam (dim3) to get a single profile you would do:
```
apply(d[['a', 'numeric']], 2, mean, na.rm=TRUE)
```

The `*apply()` family of functions in R is *very* powerful (`apply()`, `sapply()`, `lapply()` ...) and I recommend you read up on them.

> 5. I’m learning R S4 and the formal class method.  Apparently data frames are only 2 dimensional, so adcp_master[["a", "numeric"]] can’t be a data frame unless you collapse it into to dimensions which is this case, if I do as.data.frame(adcp_master[["a"]]) is 6,52.  doing an average on the 4 beams is difficult, as I somehow has to make 4 data frames, 13 columns across.

What you're discovering here is one of the big reasons why we have not tried to implement "tidy data" (i.e. tidyverse) approaches within `oce` -- oceanographic data rarely conforms to a simple "data frame" approach. Base R is very powerful, if a little obtuse at times, and is more flexible for working with non-standard data formats.

A couple functions that might be useful for you are `typeof()` and `class()`. For example, on your data, you get:
```
r$> typeof(d[['a']])                                                                                                          
[1] "raw"

r$> typeof(d[['a', 'numeric']])                                                                                               
[1] "double"

r$> class(d[['a', 'numeric']])                                                                                                
[1] "array"

r$> dim(d[['a']])                                                                                                             
[1] 952  13   4
```
So, the `a` data are either type "raw" or "numeric", but in either case they are of a class called "array". Arrays can have many dimensions (e.g. MxNxP for a 3D or MxNxPxQ for 4D, etc). Data frames are kind of like 2D arrays (or matrices), but are not exactly the same since the `array` class has to hold the same "type" in all of its elements.

In reality, a `data.frame` is actually just a special kind of `list()` -- one where each element has the same number of rows, so it can be thought of (and worked with) as a kind of matrix or table. But for a data frame, the columns (i.e. list elements) can each be of different `type` -- numeric, raw, character, logical, etc.

Hope that helps!

**Comment by dankelley** [comment]
A minor point: converting from raw to floating-point expands by about a factor of 8, not 4, on a 64-bit machine.  (There is also some overhead for R objects, which depends on size but for a vector is 48 bytes with the R on my macos laptop.)  Just for giggles, below is a little script that explores this. The top panel is for floating-point and shows difference between actual and 8 times the data length. The bottom panel is for raw type and compares with 1 times the data length. Roughly speaking, then, a floating point type needs 8 bytes per value and a raw type needs 1 byte per value.

A lot of this code is fairly old, and maybe we have some docs suggesting a 4X expansion (like for a 32 bit computer) ... I'll do a `grep` to see if so, and I'll fix the docs.


```R
n <- 1:100
par(mfrow=c(2, 1), mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))

len <- unlist(lapply(n, function(N) object.size(rep(1.0, N))))
plot(n, len-8*n, type="s")
abline(h=0, col=2)

len <- unlist(lapply(n, function(N) object.size(rep(as.raw(0x10), N))))
plot(n, len-n, type="s")
abline(h=0, col=2)
```

<img width="793" alt="Screen Shot 2019-07-07 at 11 46 12 am" src="https://user-images.githubusercontent.com/99469/60770019-e6e38400-a0ac-11e9-8d5a-43fad668938e.png">

**Comment by bjvt** [comment]
Thank you gentlemen!  this will keep me going for a while.  I understand the apply function, but the "c(1,2)" argument had me stumped.  Working with 2D, probably in data.frame will be easier, but I understand the reason now for an S4.  Maybe this is also a reason to delve into tibbles.
Working on a velocity question now,
