### ISSUE TITLE
plot,section-method should have lon0, lat0 aruguments when xtype = 'distance'

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1584]
The title of this issue is more of a question. I'm not saying it should be put it, but I think it would be useful. It came up because I am working on making section plots for transects that have been repeated many times, and there might be times where a station is missing, etc, and want the x-axis to always start from a relative (lat,lon) point.

**Comment by dankelley** [comment]
This is a very good point. Since I'll be looking at section code later today or on the weekend (gotta send in a review first), I'll make the change. Thanks!

**Comment by dankelley** [comment]
I think this works now, in "develop" branch commit e3fae66c9d57a5410121917a22aed4c8ca7cbc63

The test code (in https://github.com/dankelley/oce-issues/blob/master/15xx/1584/1584a.R)
```R
library(oce)
data(section)
gs <- subset(section, 115<=stationId&stationId<=125)

if (!interactive()) png("1584a.png")
par(mfrow=c(3, 1))

##> gs[["longitude","byStation"]]
## [1] -70.6077 -70.8197 -71.0247 -71.2227 -71.3707 -71.5228 -71.7373 -71.9333
## [9] -72.1187 -72.2883 -72.4540

## > gs[["latitude","byStation"]]
## [1] 36.8930 36.9893 37.0843 37.1833 37.2697 37.3583 37.4080 37.4757 37.5530
##[10] 37.6227 37.7000

plot(gs, eos='unesco', which="temperature", xtype="distance", xlim=c(0, 400))
mtext(sprintf("distance from %.3fW %.3fN",
              -gs[["longitude"]][1], gs[["latitude"]][1]), cex=3/4, line=0.5)

lon0 <- -70.0
lat0 <- 36.5
plot(gs, eos='unesco', which="temperature", xtype="distance",
     longitude0=lon0, latitude0=lat0, xlim=c(0, 400))
mtext(sprintf("distance from %.3fW %.3fN",
              -lon0, lat0), cex=3/4, line=0.5)

plot(gs, which="map", span=800)
points(lon0, lat0, pch=20)
mtext(sprintf("filled symbol is %.3fW %.3fN", -lon0, lat0), cex=3/4, line=0.5)

if (!interactive()) dev.off()
```
makes as below. I think this is the desired behaviour. If you agree, @clayton33, please close the issue ... otherwise, please add some comments to suggest another behaviour. Thanks!

![1584a](https://user-images.githubusercontent.com/99469/61555210-332bae00-aa35-11e9-9987-019bf7ac176d.png)

**Comment by clayton33** [comment]
Looks perfect ! Thanks :)
