### ISSUE TITLE
plot,section-method should have an argument to suppress station ticks

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1585]
As summarized by the title, there should be an argument to suppress station tick labels on the top axis when plotting a section. There is already a `showStations` argument, but it pertains to maps, and now re-reading its description `Logical indicating whether to draw station numbers on maps.`, having this argument do kinda different things might make it confusing for users? So `sectionTicks` might be better ? Or `stationTicks`. I'll let DK decide. Initially `showStations` makes most sense to me, but `stationTicks` I think is the runner-up ?

**Comment by dankelley** [comment]
I prefer `showStations`, partly because I find a long list of arguments to be quit bewildering.

**Comment by dankelley** [comment]
Hm, but the default for `showStations` is presently `FALSE` and has likely been that way for years. So I'll make a new arg named `stationTicks`.

**Comment by dankelley** [comment]
I think this ought to work now, in "develop" commit d4346bc1126791f167cdd9bae3150a73ea9ddee4; below is a test code. (I don't quite see how to colour the station names, but this gives the general idea of making notations in the axis region.)

```R
library(oce)
data(section)
GS <- subset(section, 109<=stationId&stationId<=129)
plot(GS, which="temperature", stationTicks=FALSE)
labels <- lapply(GS[["station"]],function(x)x[["station"]])
axis(side=3, at=GS[["distance","byStation"]],labels=labels, col=2, cex.axis=2/3)
```

@clayton33 if this seems ok, please close the issue; otherwise, please add more suggestions.

Thanks -- this is a good thing to have in oce.
