### ISSUE TITLE
adp xyx-enu coordinate transformation should handle variable orientation

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1594]
This stems from #1588, and particularly comments near the end of that issue.  Now that RDI files store `@metadata$orientation` as a vector quantity, with one value per ensemble/profile, the code for converting from xyz to enu coordinates needs some attention.

For example, in `R/adp.R` near line 3317 (in the version as of the present moment, but the line numbers will change over the next few days because I am whittling away on task #1593), we have as below.  The fix here is going to be a simple `ifelse` call to set signs in the equations. The only trick will be if the orientation is neither upward nor downward ... I've not checked yet whether RDI can state such orientations, but other instruments can, I think.

```R
        } else if (orientation == "upward") {
            oceDebug(debug, "Case 3: RDI ADCP in XYZ coordinates with upward-pointing sensor.\n")
            oceDebug(debug, "        Using S=-X, F=Y, and M=-Z.\n")
            ## As an alternative to the next three lines, could just add 180 degrees to roll
            starboard <- -res@data$v[, , 1] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            forward <- res@data$v[, , 2] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            mast <- -res@data$v[, , 3] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            if (haveBv) {
                ## bottom velocity
                starboardBv <- -res@data$bv[, 1]
                forwardBv <- res@data$bv[, 2]
                mastBv <- -res@data$bv[, 3]
            }
            oceDebug(debug, "  defined starboard, etc\n")
        } else if (orientation == "downward") {
            oceDebug(debug, "Case 4: RDI ADCP in XYZ coordinates with downward-pointing sensor.\n")
            oceDebug(debug, "        Using roll=-roll, S=X, F=Y, and M=Z.\n")
            roll <- -roll
            starboard <- res@data$v[, , 1] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            forward <- res@data$v[, , 2] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            mast <- res@data$v[, , 3] # p11 "RDI Coordinate Transformation Manual" (July 1998)
            if (haveBv) {
                ## bottom velocity
                starboardBv <- res@data$bv[, 1]
                forwardBv <- res@data$bv[, 2]
                mastBv <- res@data$bv[, 3]
            }
```

**Comment by richardsc** [comment]
As discussed in the f2f between @dankelley and I today, I'm not sure that it makes sense to re-code the coordinate transformation code to accommodate a (possibly) changing orientation using `ifelse()` blocks. The reasons for this are:

1. it would require changing code that has been quite stable for a long time, and

2. I can't think of any good reasons why we would want to handle coordinate transformations in the case when a unit was *changing* orientation. 

As pointed out in the original issue (#1588, thanks to @hhourston) the problem here is simply that using the *first* ensemble is problematic, because of when the unit is sitting on the deck before deployment.

I think a better solution is to examine the orientation vector when reading the data, and issue a warning to the user if it is detected that it has a variable orientation (i.e. warning if the orientation contains *both* up and down, but not if it is only up or down). That way the onus is on the user to ensure that the metadata is correct for their case. The warning could even give a code snippet to use to update the orientation if necessary (e.g. use `oceSetMetadata()`).

What this suggests is that the time series of `orientation` should be kept, but perhaps not stored in the `@metadata$orientation` object, since that is currently used by `beamTo*()` etc as if it was a single valued object.

Thoughts @dankelley ? If we were to store `orientation` as it was stored previously, where should the time series of orientation be stored? I would actually argue that it could be stored in the `@data` slot, since there are lots of other diagnostic things we are currently reading that get stored there (e.g. `xmitCurrent`, `xmitVoltage`, etc).

**Comment by richardsc** [comment]
An example warning could be something like:

> *Warning:* variable orientation detected. User should verify correct orientation and set `@metadata$orientation` accordingly, e.g. `oceSetMetadata(adp, 'orientation', 'upward')` to set the orientation to "upward"

**Comment by dankelley** [comment]
A warning has been added to the "develop" branch, commit e4202513ba484d95fcefa7cae10cfb97b160259d, as illustrated below. 

(Aside -- I was wrong in the f2f this morning: the first stored orientation is for the first profile *read*, not the first one in the file. The decodeHeader was reading an orientation at the start, but it was being over-written later. I have now removed the first reading, because it would confuse people looking at the code.)

```R
> d<-read.oce("~/Dropbox/a1_20050503_20050504_0221m.000")
Warning: bad ensemble-start byte-pair at byte 159369 in file
    ... recovered from bad ensemble-start byte-pair by restarting at byte 163465 in file
Got to end of data while trying to read an RDI file (cindex=163467; last7f7f=163463)
Warning message:
In read.adp.rdi(file, processingLog = processingLog, ...) :
  the instrument orientation is not constant. The user is advised to determine
the orientation during the relevant measurement phase, and to set this into the
object with e.g.
    adp<-oceSetMetadata(adp,'orientation','upward')
in case conversion to ENU is to be done later.
> which("upward"==d[["orientation"]])
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
> d<-read.oce("~/Dropbox/a1_20050503_20050504_0221m.000",from=27)
Warning: bad ensemble-start byte-pair at byte 159369 in file
    ... recovered from bad ensemble-start byte-pair by restarting at byte 163465 in file
Got to end of data while trying to read an RDI file (cindex=163467; last7f7f=163463)
```

**Comment by dankelley** [comment]
I'm closing this, because the code now notices variable orientation and gives a clear message to the user about what to do.  As @richardsc has pointed out, it seems highly unlikely that users will need to deal with variable orientation, since once the device is in the sampling state, it will likely stay in that orientation.
