### ISSUE TITLE
Request: allow rotation of drawPalette() labels

### ISSUE THREAD

**Issue by GironsLopez** [dankelley/oce#1627]
The labels for the `drawPalette()` function are currently fixed parallel to the palette. I would be a nice improvement to allow rotating these labels to, at least, being perpendicular to the palette as well.

**Comment by dankelley** [comment]
I'll have a look at this, perhaps on the weekend, if I can find time (it's a busy time of the winter term).  Rotating may cause problems with auto-computed `mai` values, but we have `mai` as an argument, so that may mean that we can let the user worry about the changes to margin spacing that would be required by rotating labels.

**Comment by dankelley** [comment]
This looks to be difficult, because `drawPalette()` draws the axes using `axis()`, which does not obey either a `srt` or `crt` argument. 

As `?par` notes, `srt` only works for `text()`.  I did some tests also with `Axis()`, and that also ignores a `str` argument.

Thus, adding this feature would demand a fair bit of fiddling, basically rewriting `axis()`.  Doing that seems excessive, for a feature never requested before and not provided by base-R functions like `axis()` and `Axis()`.

So, unless some other users suggest that this is a really important feature to have, the work will probably not be done.  Sorry.

**Comment by clayton33** [comment]
There is another graphical parameter that applies to `axis()` that could solve the issue, `las`, it controls the orientation, `0 = parallel` and `1 = perpendicular`. Its one option, but I'm not sure if it would affect the `mai` calculations.

**Comment by dankelley** [comment]
Oh, I never heard of `las`!!  This is a great thing to know, and e.g.
```R
plot(1:10,axes=FALSE);axis(side=2,las=1);axis(side=4,las=0)
```
proves it can be helpful.  So maybe I'll code this in ... the idea will be to make `drawPalette()` take a `las` argument, and pass that into `axis()`.  The user can then worry about margin sizes and change them by supplying a value for the `mai` argument, if desired.

**Comment by dankelley** [comment]
I have something provisional in the commit afb97a40e9309f867b66d21fc58ae4e7ae8ad3bc of the "develop" branch. As suspected, the spacing of the margins is going to be a problem, e.g.
```R
library(oce)
imagep(volcano, las.palette=1)
```
cuts off the labels, while
```R
library(oce)
imagep(volcano,las.palette=1,mai.palette=c(0,0,0,0.07))
```
lets us see the labels, but at the expense of making the colour bar pretty thin.

A fuller solution would rewrite the code where it automatically guesses a value for `mai.palette`, but I think that might get pretty messy in the code, which would need to figure out how wide the labels are in every instance.  The downside of this (in addition to possible code-change ripples) would be that plots might not overlay, because the margins will depend on the data, not the setup.

Any thoughts on this, @clayton33, @GironsLopez and others?

**Comment by clayton33** [comment]
I had a feeling this would be the issue, I've never been keen on having perpendicular labels for that very reason. I guess its up to the issue reporter, but I'm going to give a vote of -0.5 of trying to make it work. If it is really wanted by the reporter though, `drawPalette()` does take `las`, not sure if that was because of your recent change though, but playing with `mar` and or `mai` could potentially get something halfway decent ?

**Comment by GironsLopez** [comment]
Thank you for looking into this! Yes, it does look like implementing the fuller solution you propose may be a messy business for little gain. Especially if there are no positive side-effects of undertaking these modifications.

From my side I would be happy with just having the restricted solution and then I can worry about the margins etc. Nevertheless, looking at the bigger picture I understand that it might not be the best approach to include a feature that breaks some other functionality.

**Comment by dankelley** [comment]
@GironsLopez once you have the chance to check the new code, please consider either adding further comments here, or closing the issue.  Thanks!
