### ISSUE TITLE
oce needs a "hex" logo

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1630]
Seeing the great (animated!) hex logo that `sf` has:

![](https://user-images.githubusercontent.com/520851/34887433-ce1d130e-f7c6-11e7-83fc-d60ad4fae6bd.gif)

Made me think that `oce` should have a proper hex logo. Then, we could potentially get some stickers printed, too!

We already have this logo on the [webpage](https://dankelley.github.io/oce/)

![image](https://user-images.githubusercontent.com/233584/70729072-e5139180-1cd8-11ea-829e-abeab01507f6.png)

which would make a nice start (I forget the significance of the image that was used for that logo ...).

There is a package, [`hexSticker`](https://github.com/GuangchuangYu/hexSticker) that might help.

**Comment by dankelley** [comment]
If we are to remake the oce logo (which I agree with) it would be great to get a snapshot of a life-ring.  This one is from somewhere online, likely a photo of a famous ship (the idea I had was that oce is a life-saver) but I am sure I did not try to find the photographer to get permission, or note whether it was creative-commons if on wikipedia or whatever. I wonder if there are life-rings at BIO, and someone who could snap a photo?

**Comment by dankelley** [comment]
My last comment might have given the impression that I want to stick with a life-ring. That's not the case, though.  I think it would be cool to have some brain-storming here, about ideas.  You've got some people in your institute who might have cool ideas, and I'd be inclined to prefer ideas that come from younger people.  Maybe deep-water waves with their mysterious ghost waves shooting out the front and disappearing.  Maybe a pretty section getting animated (or glider data... but maybe save that for the oceanglider package). etc.

Maybe we ought to have a contest.  The prize being something of value, like getting Ukraine to dig up dirt on matlab.

**Comment by dankelley** [comment]
For an animated logo, a neat idea might be to have an argo view.  Maybe a two-panel plot, with a map at left and maybe a T profile (or something) at the right.  The map could have gray dots except for a red one, and the red one could be the source of the T profile (or something).

Maybe @harbin-j might have some ideas on this, and the two of you might want to chat on whether it seems like a good idea.

**Comment by dankelley** [comment]
I made a trial in `sandbox/dk/logo_dk_01.R`, the results of which are below.  Red dots are the stations in the Endeavour cruise of 1768 to 1771 (which I think was the first worldwide oceanographic cruise) on top of SSS (which I chose instead of SST because it shows gyres better).  I think the projection is ok.  I fiddled with the x/y offsets and magnification, and think they are okay.  I fiddled with line widths to make it look ok on my screen at about the magnification it would be if printed up as a sticker, but I was only guessing.  I played a little bit with colours, but not very extensively, so that is something that could use some experimentation, to find a combination that looks pleasing.

Any thoughts on this, @richardsc and @clayton33?

![logo_dk_01](https://user-images.githubusercontent.com/99469/89734203-180d5100-da31-11ea-86fd-49107b7f0e90.png)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
I've removed the "pinned" label, so this issue will proceed to the "stale" and "closed" states, unless there are further comments.  This is a mechanism to prevent addressed issues from filling up the in-box.

**Comment by richardsc** [comment]
I think this is a good hex logo, though I was thinking that I'd like to keep the "life ring" motif ... one option would be to either draw (or stylize a photo) of a life ring. I'm happy with this one for now though, until I get inspired to do some work to make something different 😄
