### ISSUE TITLE
Should oceRenameData() update the dataNamesOriginal field?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1639]
I just tried out the newly added `oceRenameData()` function that was added thanks to @Echisholm21 in issue #1638 . I like it!

However, I was thinking that it might be a good idea if the function updates the `dataNamesOriginal` field, to reflect the changed name. Also, that ensures that the field can still be accessed using the previous name (e.g. see #1068) so it doesn't break old code.

This does get complicated if the name of a field is changed more than once, but honestly I don't see a use case where that would happen.

**Comment by dankelley** [comment]
This has been done in "develop" branch, commit commit 7aeedd7, which also handles 4 other recent issues.  I will leave it to @richardsc to decide whether to close this issue (no rush).

**Comment by dankelley** [comment]
Sorry, and I forgot to point out -- this leaves the *original* name intact.  I think that is the right way to do it, according to the docs and according to my reading of the intention.  The idea is that the user can access by the original name as stored in the file (which might be known to the user by inspection of data files, or other software, or manufacturer's instrument manuals), *or* the most recent "oce" name that is used in the object.

I think @richardsc was suggesting that instead we accept the two most-recent names.    I could see an argument for that, I guess, so if he wants to argue the case, I'd certainly be open to the idea.  (Frankly, though, I'd prefer accepting a list of aliases, going all the way back to the original name, instead of losing that original name.  I just really do not want to lose the original name.)

**Comment by richardsc** [comment]
I like the alias idea, but that's another issue (if anyone feels strongly enough about opening it), so closing this. Thanks!
