### ISSUE TITLE
argo[['dataNameOriginal']] field doesn't match the oce one

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1640]
After trying out `oceRenameDataI()` from #1639 , I noticed some quirks about accessing fields using either the "new" or the "original" name.

Note that for `argo` objects, the function `argoNames2oceNames()` converts the standard Argo names like `TEMP` and `PSAL_ADJUSTED` to the oce version like `temperature` and `salinityAdjusted`.

However, accessing the fields using the "new" name vs the "old" name does not always give identical results:
```r
library(oce)
data(argo)
argo[['dataNamesOriginal']]
```
```
$latitude
[1] "LATITUDE"

$longitude
[1] "LONGITUDE"

$pressure
[1] "PRES"

$pressureAdjusted
[1] "PRES_ADJUSTED"

$pressureAdjustedError
[1] "PRES_ADJUSTED_ERROR"

$salinity
[1] "PSAL"

$salinityAdjusted
[1] "PSAL_ADJUSTED"

$salinityAdjustedError
[1] "PSAL_ADJUSTED_ERROR"

$temperature
[1] "TEMP"

$temperatureAdjusted
[1] "TEMP_ADJUSTED"

$temperatureAdjustedError
[1] "TEMP_ADJUSTED_ERROR"
```

This says that `argo[['temperature']]` and `argo[['TEMP']]` should be the same. But:
```r
all(argo[['temperature']] - argo[['TEMP']] == 0)
```
```
[1] FALSE
```

@dankelley any idea what is going on here?

BTW I see another issue with this related to the `data(ctd)`, but I'll make another issue.

**Comment by dankelley** [comment]
I'll take a look. In fact, I get
```R
> diff(range(as.vector(argo[["TEMP"]]),na.rm=TRUE))
[1] 0
```
(all the values are 0.01), so something very wonky is going on.

**Comment by dankelley** [comment]
This has been done in "develop" branch, commit commit commit 7aeedd74139616f6bd3f4fb7c1fd574331e36bf0, which also handles 4 other recent issues. 

Note that `tests/testthat/test_accessors.R` has a test for this, viz.
```R
test_that("argo original names (issue 1640)", {
          data(argo)
          expect_equal(argo[["temperature"]], argo[["TEMP"]])
})
```
which I think is quite clear, but still I will leave it to @richardsc to decide whether to close this issue (no rush). 

This was a flat-out coding error, based on the assumption that every item within the `data` slot was also within `@metadata$dataNamesOriginal`.  That is not the case for `data(argo)`, since the `time` item is not named in `@metadata$dataNamesOriginal`.

The fix was deep in the lowest-level of the `[[` method, so it might be helpful in other bugs as well (although I've not seen other bugs on this line).
