### ISSUE TITLE
plot,sealevel-method maybe shouldn't remove the mean value

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1649]
As discussed today in a f2f with @dankelley , `plot.sealevel(..., which=1)` removes the mean (but indicates it with an axis label). This is confusing, and also not documented.

One solution is to document the behaviour, but honestly I don't understand why it does it in the first place. I propose that `plot.sealevel()` be modified to plot the raw elevation time series.

**Comment by dankelley** [comment]
I think this should be ok now; please check.  (There was some trickiness about narrowing the ylim if xlim was set, but I removed that because this is not how normal R functions work.)

I have only tested the Juan example from the docs, but that's likely sufficient.  I did all the `which` values and things looked ok on a quick glance.

commit 6e26216a4c14fbc099f41f9e7bc5c6a8ce19e363
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Feb 6 08:39:28 2020 -0400

    plot(sealevel) no longer zero-offsets
    
    see https://github.com/dankelley/oce/issues/1649

**Comment by dankelley** [comment]
I'm closing this, because the suggestion has been followed in the "develop" branch for a few days.

**Comment by richardsc** [comment]
Sorry— I got distracted from checking this.  I’ll take a look.

As for the business about the narrowing of the Y axis, while I think what you said about base R is true, there are some oce functions that don’t behave that way, because we found it annoying. oce.plot.ts() is an example I believe.
