### ISSUE TITLE
Multiple Netcdf files and overlay and contour plot

### ISSUE THREAD

**Issue by IssamHu** [dankelley/oce#1671]
Dear Prof,
I have many netcdf files downloaded from USGODAE Argo GDAC Data Browser.
Each profile include temperature and salinity data along with lat, long, date and pressure data.
How can I combine them in single file?
How can I plot the temperature and salinity in overlay and contour (attached as an example).
Thank you very much

[tempsalinity.pdf](https://github.com/dankelley/oce/files/4373189/tempsalinity.pdf)

[argo_download (15).tar.gz](https://github.com/dankelley/oce/files/4373160/argo_download.15.tar.gz)

**Comment by dankelley** [comment]
This is quite a big question, and very difficult to answer because it is so general, and you have provided so little information on what you have done in your attempts so far, and about your R skill level.

There's no need to combine them into a single file.  If you can read the data (and there are many ways to do this), then you can  manipulate the data in any way that you like using standard R methods, and plot them with whatever R tools you like.  There may be an intersection with the oce package, but that's not necessary.
