### ISSUE TITLE
id not found

### ISSUE THREAD

**Issue by IssamHu** [dankelley/oce#1672]
Prof,
I use this website to view the get the float ID:
https://nrlgodae1.nrlmry.navy.mil/cgi-bin/argo_select.pl?startyear=2019&startmonth=03&startday=01&endyear=2019&endmonth=06&endday=30&Nlat=22.2&Wlon=51&Elon=60.4&Slat=16.5&dac=AO&floatid=ALL&gentype=plt&.submit=++Go++&.cgifields=endyear&.cgifields=dac&.cgifields=delayed&.cgifields=startyear&.cgifields=endmonth&.cgifields=endday&.cgifields=startday&.cgifields=startmonth&.cgifields=gentype

I followed the 2nd example in oce cran in read.argo
that what I get:

> library("oce")
Loading required package: gsw
Loading required package: testthat
> id <- "5905082"
> url <- "ftp://usgodae.org/pub/outgoing/argo/geo/"
> if (!length(list.files(pattern="argo_index.txt")))
>    download.file(paste(url, "ar_index_global_meta.txt", sep="/"), "argo_index.txt")
> index <- readLines("argo_index.txt")
Warning message:
In readLines("argo_index.txt") :
  incomplete final line found on 'argo_index.txt'
> line <- grep(id, index)
> if (0 == length(line)) stop("id ", id, " not found")
Error: id 5905082 not found
> url <- "ftp.ifremer.fr/ifremer/argo/dac/aoml/"
> if (!length(list.files(pattern="argo_index.txt")))
+   download.file(paste(url, "ar_index_global_meta.txt", sep="/"), "argo_index.txt")
> index <- readLines("argo_index.txt")
Warning message:
In readLines("argo_index.txt") :
  incomplete final line found on 'argo_index.txt'
> line <- grep(id, index)
> if (0 == length(line)) stop("id ", id, " not found")
Error: id 5905082 not found

Please how can I solve this problem?

**Comment by dankelley** [comment]
First, the CRAN version of oce does not list the `ftp` file you mention.  It lists an `https` file.

Second, I cannot reproduce your problem at the `ftp` site, because the server does not have that file.   When I open ftp://usgodae.org/pub/outgoing/argo/geo/ I see that you must specify the ocean basin name, and then the year, etc.

Server file structures can be changed without notice, and this could be the cause of the problem.  In any case, once you have downloaded an index file you ought to look at it in a text editor to see if your desired float is there.  If so, then the `grep` should work.

I advise you to find the actual data file (which will be a netcdf file) using web tools.  Then download it.  At that stage, oce may be of some help.

Owing to limits on how often a package can be submitted to CRAN, we cannot keep up with changes to web servers in the oce documentation.  (It is common for servers to work one day, fail the next, then work again.  And the oce docs have dozens, probably hundreds, of references to servers, so keeping track could require so many updates that oce would get banned from CRAN.)

**Comment by IssamHu** [comment]
Prof,
I've download the file, as you suggested from this website: ftp://usgodae.org/pub/outgoing/argo/dac/aoml/2902401/
save the 2902401_prof.nc on desktop. 
Try to open it using these codes, but that what I get:
> library("oce")
Loading required package: oce
Loading required package: gsw
Loading required package: testthat
> library("ncdf4")
> d <- read.argo(file.choose())
Error in R_nc4_open: Invalid argument
Error in ncdf4::nc_open(file) : 
  Error in nc_open trying to open file C:\Users\0000000\Desktop\2902401_prof (1).nc.txt

**Comment by dankelley** [comment]
You have downloaded a text file, not a netcdf file.  Notice the filename. This is likely why nc_open() cannot open the file.
