### ISSUE TITLE
Lacking support for 38 kHz RDI ADCP

### ISSUE THREAD

**Issue by krillThor** [dankelley/oce#1675]
read.adp fails to read in RDI file from a 38 kHz vessel mounted adcp, error message:

Error in decodeHeaderRDI(buf, debug = debug - 1) : 
  unknown freq. bit code:110 (expect 000 for 75kHz, 001 for 150kHz, etc)

[38kHz.ENR.zip](https://github.com/dankelley/oce/files/4430570/38kHz.ENR.zip)

**Comment by richardsc** [comment]
Thanks for the report. It seems like the current version of `oce` doesn't have support for the 38 kHz ADCP because the identifying byte codes do not appear in the manual which we have primarily used to add support, e.g. [page 128 here](https://wiki.oceannetworks.ca/download/attachments/20480039/RDI+ADCP+WorkHorse+Commands+and+Output+Data+Format-+November+2007.pdf)

```
LSB
BITS 7 6 5 4 3 2 1 0
- - - - - 0 0 0 75-kHz SYSTEM
- - - - - 0 0 1 150-kHz SYSTEM
- - - - - 0 1 0 300-kHz SYSTEM
- - - - - 0 1 1 600-kHz SYSTEM
- - - - - 1 0 0 1200-kHz SYSTEM
- - - - - 1 0 1 2400-kHz SYSTEM
```

IIRC, a 38kHz is only possible as a ship-mounted system, and is therefore not a "Workhorse" unit, but an "Ocean Surveyor" unit. A recent manual can be found [here](http://www.teledynemarine.com/Documents/Brand%20Support/RD%20INSTRUMENTS/Technical%20Resources/Manuals%20and%20Guides/Ocean%20Surveyor_Observer/Ocean%20Surveyor%20Technical%20Manual_Apr18.pdf), with page 155 giving the equivalent to above:

```
LSB
BITS 7 6 5 4 3 2 1 0
 - - - - - 0 0 0 75-kHz SYSTEM
 - - - - - 0 0 1 150-kHz SYSTEM
 - - - - - 0 1 0 300-kHz SYSTEM
 - - - - - 0 1 1 600-kHz SYSTEM
 - - - - - 1 0 0 1200-kHz SYSTEM
 - - - - - 1 0 1 2400-kHz SYSTEM
 - - - - - 1 1 0 38-kHz SYSTEM
```

Assuming that there are no other file differences between the WH and OS units, it should be simple to just add detection for that frequency code.

I will try that before pouring over the manuals to see if there are other significant differences.

**Comment by richardsc** [comment]
This has been done in 3c15096d23e91

```r
library(oce)
d <- read.adp.rdi('38kHz.ENR')
```
produces:
```
Warning message:
In read.adp.rdi("~/winHome/Downloads/38kHz.ENR/38kHz.ENR") :
  A list of unhandled segment codes follows. Several Teledyne RDI manuals
  describe such codes; see e.g. Table 33 of Teledyne RD Instruments, 2014.
  Ocean Surveyor/Ocean Observer Technical Manual.
  P/N 95A-6012-00 April 2014 (OS_TM_Apr14.pdf)
    Code 0x00 0x30 occurred 2180 times
    Code 0xe0 0x30 occurred 2180 times
```
indicating that there are some data-type codes that we are not currently decoding. I haven't looked closely at the manual to see what they are for sure (@dankelley knows how to interpret these binary codes better than I), but I suspect they are found on [page 155 here](http://www.teledynemarine.com/Documents/Brand%20Support/RD%20INSTRUMENTS/Technical%20Resources/Manuals%20and%20Guides/Ocean%20Surveyor_Observer/Ocean%20Surveyor%20Technical%20Manual_Apr18.pdf).

A quick plot of the provided data shows that things appear to be being read sensibly (though I have no way of knowing for sure):
![image](https://user-images.githubusercontent.com/233584/78418120-9b481180-760f-11ea-9602-8df9aacfd4db.png)

**Comment by dankelley** [comment]
Thanks, @richardsc for the fix, and @krillThor for the bug report.  As for the unrecognized codes
```
Code 0x00 0x30 occurred 2180 times
Code 0xe0 0x30 occurred 2180 times
```
A quick search on `30h` (which is the RDI way to say `0x30`) turns up hits on two pages in http://www.teledynemarine.com/Documents/Brand%20Support/RD%20INSTRUMENTS/Technical%20Resources/Manuals%20and%20Guides/Ocean%20Surveyor_Observer/Ocean%20Surveyor%20Technical%20Manual_Apr18.pdf; on page 172 we see as below.  I'll need to check again what they mean by MSB (are they talking in little-endian or big-endian?) but even if this is the right thing, it leaves `0xe0 0x30` unexplained.

<img width="659" alt="Screen Shot 2020-04-04 at 7 03 35 AM" src="https://user-images.githubusercontent.com/99469/78424255-9781b280-7642-11ea-8cf4-58ae4309a444.png">

**Comment by dankelley** [comment]
Oh, hang on, I see "LSB MSB" on page 188 (table 46) of that manual stating that LSB=e0h MSB=30h has a meaning for 'variable attitude identification word', so both of these unrecognized blocks seem to relate to attitude.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
