### ISSUE TITLE
colour problem with plot(section, ztype="image") on Mac

### ISSUE THREAD

**Issue by gianmarcoingrosso** [dankelley/oce#1679]
Dear all,
I’m reporting to you the following problem.
When I do a simple plot of a section with command ztype =“image” the colors  of the figure appear with a lot of white lines (see the attached fig).
This seem a problem related to my operate system (I’m a Mac user,  10.15.2  with the last R version 3.6.3), because when I run the code with an online R service (like RStudio Cloud)  the plot is fine. 
Any idea how to resolve this? Thanks in advance for your help
Best
Gianmarco

`library(oce)
data(section)
plot(section, which="temperature", ztype="image")`

![Rplot](https://user-images.githubusercontent.com/60222275/78674984-b2735180-78e4-11ea-8a8e-350dc62bad60.png)

**Comment by dankelley** [comment]
I assume you mean the thin lines surrounding the pixels?  If so, I think @richardsc knows the magic recipe, which has to do with how the plot device is set up.

**Comment by clayton33** [comment]
You have to specify the type as `cairo` when saving a png file. See example code below,
```
library(oce) 
data(section)
png('test.png', type = 'cairo')
plot(section, which="temperature", ztype="image")
dev.off()
```
![test](https://user-images.githubusercontent.com/3463161/78677372-0b7bbf00-78be-11ea-9612-89a8385c431a.png)

**Comment by richardsc** [comment]
For context, the "ghost lines" issue is a result of the antialiasing that is normally done for "Quartz"-type objects (that's the default OSX graphics device for R). @clayton33 solution is the best one, since it keeps all the other nice antialiasing (e.g. of the text, and axis lines, etc).

You didn't specify that your problem was in the generated PNG file, as the same "ghost lines" can be seen even in a regular quartz window in interactive mode. But the solution is the same, you can open a "cairo" device first instead of the (default) quartz one:

```r
library(oce)
data(section)
x11(type='cairo')
plot(section, which='temperature', ztype='image')
```
![image](https://user-images.githubusercontent.com/233584/78680243-a32edc80-78c1-11ea-929a-8757d1132f8f.png)

```

**Comment by gianmarcoingrosso** [comment]
Thanks @clayton33, this works fine after installing xQuartx (https://www.xquartz.org; as suggested here https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#OS-X). However, I see the plot only after saving it and not with a sort of pre-view window. 

Thanks @dankelley but when I run your code I have the following error
`Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In x11(type = "cairo") : unable to open connection to X11 display ''`

**Comment by gianmarcoingrosso** [comment]
There was something wrong with xQuartz...I have reinstalled the software and now also the code proposed by @richardsc works well. Thank you to all of you. From my side the issue can be considered closed and solved very well ;)
