### ISSUE TITLE
plotProfile() gets confused with partial name matches

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1684]
I have a `ctd` object, that has a field called "`ph`" (read in from a file that way). Of course, the correct way of writing it is "pH", but regardless ...

If I do:
```r
plotProfile(ctd, xtype='ph')
```
then the resulting plot displays the x-axis label and unit as "phosphate [umol/kg]", presumably because it's getting a match from a list of "known" field types:
![image](https://user-images.githubusercontent.com/233584/79787482-73e68980-831d-11ea-8d4c-795434c592df.png)

**Comment by richardsc** [comment]
My solution for now is to just rename (using `oceSetData()`, etc) the "ph" column to "pH", and then it works fine, but I wanted to point this out in case there is some overzealous regexping happening that maybe shouldn't be ...

**Comment by dankelley** [comment]
First, I was guessing that the code was doing partial matches according to first letters, akin to the standard R scheme for arguments, viz
```R
a <- function(foo, bar) message(bar)
a(b="BAR")
```
but https://github.com/dankelley/oce/blob/6300fa33d03144d1892777ca6d0ff498536b799d/R/ctd.R#L5741, which I *think* must be called for your case, suggests that we are demanding an exact match in name.

So I'm confused.

If you send me the data+code I can check on this.  It should be fast for me to figure this out, since I wrote the original code, which `git blame` tells me goes back to 2012, with some lines to 2013, 2016.

**Comment by richardsc** [comment]
Sent. Note it's from an RSK file, but the code will show what I was doing.

**Comment by dankelley** [comment]
The problem is at https://github.com/dankelley/oce/blob/6300fa33d03144d1892777ca6d0ff498536b799d/R/ctd.R#L5762
which is a problem because trying to look up a name is faulty when the user has *given* a name.

I will change this.  I don't think we need to fret about breaking existing code because this renaming was an undocumented feature.   But, just in case we want to go back, I'll comment out, with an issue number and a date.

**Comment by dankelley** [comment]
This should work now in the "develop" branch, commit 20424d524e5d72e45fa170a481cd318547cb4077 

(It will take about half an hour to do my local and nonlocal tests, but it was 2 lines so I would be surprised if there is a problem and therefore I'm posting this before my usual procedure of waiting for the tests.)

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
