### ISSUE TITLE
plot(ctd) x axis modification

### ISSUE THREAD

**Issue by IssamHu** [dankelley/oce#1685]
Prof,
I want to plot three profiles in single figure and I want to :
1- hide the Practical Salinity and Temperature [°C] in the first and third plot.
2- modify the x axis title from Practical Salinity to Salinity (PPT) and the Temperature [°C] to Temperature (°C).
The intended plot looks like that : 
![Rplot_5](https://user-images.githubusercontent.com/62583812/79850407-bd17f700-8378-11ea-979f-5b52b8038c4e.png)

The code used to get the plot :
library("oce")
d <- read.oce(file.choose())## select the file you downloaded from GODAE site
ctd1<-as.ctd(d)
d <- read.oce(file.choose())
ctd2<-as.ctd(d)
d <- read.oce(file.choose())
ctd3<-as.ctd(d)
par(mfrow=c(1,3))
plot(ctd1, which =1,type="l", ylab= "",xlab="", zlab="")
title(ylab="Depth (m)")
legend("topleft", "1Jan19", bty="n")
plot(ctd2, which =1,type="l", ylab= "",xlab="", zlab="")
legend("topleft", "11Jan19", bty="n")
plot(ctd3, which =1,type="l", ylab= "",xlab="", zlab="")
legend("topleft", "31Jan19", bty="n")

and I got this plot:
![Rplot01_3](https://user-images.githubusercontent.com/62583812/79850686-20a22480-8379-11ea-9791-88dee5eec26a.png)

The files used from this website:
https://nrlgodae1.nrlmry.navy.mil/cgi-bin/argo_select.pl?startyear=2019&startmonth=01&startday=01&endyear=2019&endmonth=01&endday=31&Nlat=22.2&Wlon=51&Elon=60.4&Slat=16.5&dac=AO&floatid=ALL&gentype=idplt&.submit=++Go++&.cgifields=endyear&.cgifields=dac&.cgifields=delayed&.cgifields=startyear&.cgifields=endmonth&.cgifields=endday&.cgifields=startday&.cgifields=startmonth&.cgifields=gentype

**Comment by dankelley** [comment]
This cannot be one with the present version of oce, because setting `xlab=""` does not cause it to skip labelling the axes.  That could be added, but in the meantime your only choice is to draw the middle panel manually.

**Comment by dankelley** [comment]
This works now in the "issue1685" branch on github.  If you know how to build that, you should find that the following code makes a graph as shown below, i.e. the new method is in the bottom row of the plot.  (Note that this branch is **not** working fully on the oce test suite, as of this moment.  I suspect there are plenty of errors, because quite a lot of code had to be altered.  I will keep testing and fixing bugs in this branch, and consider merging it into the "develop" branch within a week or so.)
```R
library(oce)
data(ctd)
par(mfrow=c(2, 3))
## Top row: shows ok if xlab not given
plot(ctd, which=1, type="l")
plot(ctd, which=1, type="l")
plot(ctd, which=1, type="l")
## Bottom row: shows how to do what user wants in 1685
plot(ctd, which=1, xlab="", type="l")
plot(ctd, which=1, ylab="", type="l")
plot(ctd, which=1, ylab="", xlab="", type="l")
```
![a](https://user-images.githubusercontent.com/99469/79913918-bf229a00-83fa-11ea-83d8-6b25b8991a71.png)

**Comment by IssamHu** [comment]
Please Prof. if you can add into the "develop" the possibility of editing the titles of the two x axis.

**Comment by dankelley** [comment]
Sure, but it won't be for about a week. There are lots of people using "develop" and I don't want to break anything for them.  The code in question had 300 line deletions and 200 line additions so there is a chance for errors.

Besides, if you know how to install from the "develop" branch then you also know how to install from any other named branch.  I am not talking about the CRAN version here.  That only gets updated about once or twice a year.

**Comment by dankelley** [comment]
Oh, you mean editing the x titles above and below the plot?  That's quite risky (in terms of letting the user mix things up with inappropriate labels) and so it is not in the plans.

Anyone with more than a passing understanding of R can create any plot they want.  Use `axes=FALSE` and `xlab="", ylab=""` in the `plot()` call, then use `box()`, then use `axis()` to draw an axis where-ever you want it, then use `mtext()` to draw an axis label wherever you want it. Use `par(new=TRUE)` to add a new plot on top, with a different scale.  This is all standard stuff, and it gives the user the power to do anything they want.  R is good, that way.

**Comment by richardsc** [comment]
I agree with @dankelley that for anything beyond simple customizations you should probably write up your own functions to do exactly what you want. The plotting functions provided by `oce` can not meet every single need of every single user.

I will, however, point out a few things in your original issue that might bear thinking about:

1. You say that you want the salinity units to show up as `Salinity (PPT)`, but I am curious as to why you would use such units. Using practical salinity (which is unitless) has been the accepted standard in oceanography since 1978 or so, and I think it likely that the CTD you were using most likely reports salinity using the PSS (practical salinity scale). If you really want units, you can use the recommended [TEOS-10](http://teos-10.org/) or GSW salinity, called "Absolute Salinity", which has units of g/kg. I do not believe that PPT and practical salinity are considered 

2. If you want to change the parenthesis style, you can do:
```r
options(oceUnitBracket='(')
```
which changes the default for that session.

**Comment by IssamHu** [comment]
Prof.,
I followed your instructions and I got what was I'm looking for.
Thank you very much.
Dr. Clark Richards
Your comments are valuable, thank you very much.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by IssamHu** [comment]
Dear Prof.,
Yes, the issue has been addressed
