### ISSUE TITLE
Consider switching webpage to either pkgdown or blogdown format

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1688]
After learning about [`pkgdown`](https://pkgdown.r-lib.org/) and using for the [`argoFloats`](https://argocanada.github.io/argoFloats/index.html) website, I think that we should consider updating the `oce` site from the existing jekyll one.

For one thing, the pkgdown site bundles the vignette, compiles all the help pages, runs the examples, etc.

I plan on looking into different customization options so that it doesn't look quite as utilitarian. I think it would also be nice if there was a section for a "blog" that we could use to feature new functionality. That's why I mentioned `blogdown`.

I'll be poking at this (for `argoFloats`) so just wanted to capture the idea here.

**Comment by richardsc** [comment]
I have tried building a default pkgdown site, contained in the `website` branch (commit 7934113f7b7) and it seemed to mostly work. There were a few warnings that I'll look at later.

To test it, it either needs to be put into a branch with *only* the webpage stuff (to go into the `gh-pages` branch), or like `argoFloats` it has to be served from `master/docs`. I was going to try just renaming the existing `gh-pages` branch to something else to mess around and see if Github will serve the site, but then I panicked about messing the history by renaming branches.

What I might do instead is just build it on the `master` branch and try hosting that way, which will leave the existing `gh-pages` branch alone as a backup. But, if I do that I'll need @dankelley to change the repo settings to serve the page from there instead (as a "collaborator" I don't seem to have permissions to edit the repo settings).

**Comment by dankelley** [comment]
I remember having a heck of a time figuring out how to set up `gh-pages` as a branch with only the docs, and none of the other stuff.  Based on that, I don't recommend trying to figure out a dance with going to "master", doing the pkgdown command, copying the contents of `docs`, going to th "gh-pages" branch, copying the new "docs" and so forth.  (This would be necessary because pkgdown works on sources, and there *are* no sources in the "gh-pages" branches, per the rules.)

From this reasoning, the solution is to serve it from `docs/` within the "master" branch.  I cannot do that setting until such a subdir exists.  We do not have such a directory at the moment.  Of course I can make one, putting a dummy file in it (so git will "notice" it), and let @richardsc update it, but that might lead to a merge conflict if he has already started.  It might also leave us with no webpage in the meantime.

Therefore, @richardsc, the best plan is to create the `docs` directory in the "master" branch and us "pkgdown" to populate it.  Actually, maybe it will make the `docs` dir.  In either case, be sure to add it to `.Rbuildignore`, if pkgdown doesn't do that for you, because CRAN doesn't want this subdirectory in the sources.

So we're not too badly out of date, I merged "develop" into "master".   There's a question in my mind as to whether people are going to start thinking these webpages are the guide to the CRAN version.  They are not.  The official documentation for a CRAN-installed "oce" is given by `?` and `browseVignettes("oce")`, and not by these webpages.  That's true for even the "develop" branch, and even issue branches.  Github only permits serving these up from the "master" branch, so I think they are trying to set up a system in which users can view these as the semi-stable documentation of what could be called beta software.  It's not *alpha*, which is the "development" branch. But it's not *release*, either.  I don't think I am explaining this well, but this is my interpretation of reasoning behind the restriction in the sources for github pages.  Once we have the new pages up and running, I'll write a clean sentence summarizing this into the README file.

I don't think it's in the cards that CRAN will start serving up pages like this.  After all, they already serve up vignettes, and a PDF that is the full documentation for every single function in a package.  Why incur the extra server cost?  And why buy in to a single package that might get broken, or might change, when they can stay as they are and be in total control, since breakage will only occur if R breaks?

Thanks for looking into this!  I'm excited to see the results.

**Comment by richardsc** [comment]
I'll build from the master branch today, but then I'll need you to change the settings on the repo (or change it so that I can change the settings ... is that possible?).

I'll let you know.

**Comment by dankelley** [comment]
Thanks.  Since I cannot change the settings until the 'docs' dir exits, I just created and pushed that (in "master").  Note that `docs/` has a dummy file in there that should be removed.  Once I pushed that, GH let me update the webpage source, and I switched it to "docs/" in the "master" branch.  I guess this will mean broken pages for a while, but the old page was not especially useful, I think, and we can safely just ignore the old content.

**Comment by richardsc** [comment]
These are the warnings I get, but it does seem to build:
```
Warning messages:
1: Failed to parse example for topic 'ctdFindProfiles'
2: In doTryCatch(return(expr), name, parentenv, handler) :
  "orientation" is not a graphical parameter
|: In doTryCatch(return(expr), name, parentenv, handler) :
  "orientation" is not a graphical parameter
4: In doTryCatch(return(expr), name, parentenv, handler) :
  "orientation" is not a graphical parameter
5: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
6: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
7: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
8: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
9: Failed to parse example for topic 'swDynamicHeight'
```

**Comment by richardsc** [comment]
Ok I've pushed the built site in `master/docs`. You can switch the github-pages settings now @dankelley

**Comment by dankelley** [comment]
Oh, crossed messages. I had already switched.  It built up really quickly.  Tomorrow, I'll do an update using
```R
options(warn=3)
```
to find out more about those warnings.  I don't like to see warnings and errors :-)

I'll also look into why we have as in the screenshot below (and I'll look for more similar things).

THANKS!  This looks great.

I think this can be closed now, but I'll leave that up to you, since you're the reporter.

<img width="540" alt="Screen Shot 2020-05-01 at 10 23 09 AM" src="https://user-images.githubusercontent.com/99469/80808399-dc432f80-8b95-11ea-87f4-6d31fdc0dfb8.png">

**Comment by dankelley** [comment]
Here's why I love this format: if you go to https://dankelley.github.io/oce/reference/interpBarnes.html you see the examples plotted out.  I don't know how many users know to do
```R
examples(topic)
```
to see such things.

**Comment by richardsc** [comment]
One of the customizations I want to look into is organizing the help pages to make groups of man pages, e.g.

https://pkgdown.r-lib.org/articles/pkgdown.html#reference

**Comment by dankelley** [comment]
Oh, that reference looks pretty nice.

**Comment by dankelley** [comment]
I cleaned out most of the warnings from the build.  (In both "develop" and "master".) The only ones left are as below. I could make them go away by intercepting zero-length arrows before wherever we are calling `arrows()`, but I like to keep things close to R, and so I don't want to make that warning go away, in case users are familiar with it, and take value in knowing that their data yield some zero-length arrows.

```R
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
-: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
3: In doTryCatch(return(expr), name, parentenv, handler) :
  zero-length arrow is of indeterminate angle and so skipped
4: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
```

**Comment by richardsc** [comment]
I think this can be closed, based on the stated title. But I'm going to open a new one to discuss organization of the help pages.
