### ISSUE TITLE
Updates to repository README.md

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1691]
Because the new pkgdown site uses the `README.md` as the landing page for the site, I think it could benefit from an update and overhaul.

Right now it basically just only tells people how to install, which is good, but I think it would be nice to include some examples/graphics and other info (e.g. link to @dankelley's book?). Nothing too involved -- that's what the vignettes are for, but just something to catch the eye. 

A hex logo would be nice, too ... (i.e. #1630)

**Comment by dankelley** [comment]
Hm, good point. In the old scheme (using `gh-pages`) we had examples and some other materials.  Maybe some of that could be ported into `README.md`.

Is there an example from the old `gh-pages` that you think we ought to put in?  Maybe all of them.

I'm happy to take 15min to add them.  I think the system will build the images in, so I won't need to figure out how to hyperlink to them.

**Comment by richardsc** [comment]
I think that as long as the images are linked in the "markdown way" i.e. with `![alt text](image.png)` that pkgdown should convert the `README.md` into a properly formatted `index.html`.

Since the old jekyll page isn't hosted anymore, I can't easily see the old pages, however, I recall many of them were quite trivial. I think a CTD example is nice, and maybe an Argo one. Also the sealevel example, and `mapPlot()`, and `landsat`? That's most of what was on there before isn't it?

**Comment by dankelley** [comment]
Yes, they were very simple.  The internet wayback machine has them (sans images) e.g.

https://web.archive.org/web/20171007185645/http://dankelley.github.io/oce/examples.html

I think having just one or two examples would be fine for a start.  Is there something you'd like to have there for an upcoming presentation?

Maybe I'll add them all, and we can delete them.

**Comment by richardsc** [comment]
Maybe just add them all, with subsection headings or something, and we can delete if it feels too long or too detailed?

**Comment by richardsc** [comment]
Oh, I just read your last sentence more closely -- we are clearly on the same wavelength 😄

**Comment by dankelley** [comment]
I'll add them. Should be done by 3PM -- just noting that so we don't get conflicting commits.

**Comment by dankelley** [comment]
Hm. Something is wrong. I cannot seem to figure out how to show the PNGs.  A screenshot is attached.  The top window shows that these .png files are in the repo ("master" branch).  The middle window shows how I'm trying to do it for "oce" (which is not showing any images at https://dankelley.github.io/oce/), but the bottom window shows how I do it in "argoFloats" (which *does* show the image at https://argocanada.github.io/argoFloats/index.html).

@richardsc, can you see what's wrong here?  My eyes are just not seeing it.



<img width="810" alt="Screen Shot 2020-05-05 at 3 28 31 PM" src="https://user-images.githubusercontent.com/99469/81101938-3c630a00-8ee5-11ea-8f1c-0e5a539aa9df.png">

**Comment by dankelley** [comment]
Maybe the problem is that I have these PNG files listed in `.Rbuildignore`.  But I don't think we want these images in the R package, owing to the desire to avoid bloat.  (They add up to nearly 1Mb.)  

PS. I see that the old README (in rst format) is still listed in `.Rbuildignore`, which (apart from my oversight in not renaming the file) suggests that my impression about not including README files in R packages may be correct.  My memory tells me that R packages are not supposed to have README files built in; such files are for developers to read, or websites to intepret.

**Comment by dankelley** [comment]
I solved it.  It's necessary to put the PNGs in two places: alongside `README.md` (so the github page shows them) and in `docs` (so pkgdown can get them).  Possibly the latter would work with a link, but I always worry about whether links carry over to all platforms, etc., so I just left them there.

Also, the main reason to link would be to reduce storage.  But these things do not get incorporated into the package that CRAN builds, so that's not an issue.  As for burning up github storage, well, pkgdown does *tons* of that, it seems.

@richardsc -- we could discuss the selection of examples in our rf2f tomorrow, if you like, and of course feel free to make changes.

**Comment by richardsc** [comment]
This looks great! Closing
