### ISSUE TITLE
consider supporting other languages for mapPlot() longitude/latitude labels

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1706]
Recently I've been producing a number of plots in French, and I noticed that, currently, if doing a `mapPlot()` in our region, that the longitude labels do not change when switching the language,

```
Sys.setenv(LANG = 'fr')
library(oce)
data("coastlineWorld")

proj <- '+proj=merc'
fillcol <- 'lightgray'
lonlim <- c(-70, -56)
latlim <- c(40, 48)

mapPlot(coastlineWorld, 
        longitudelim = lonlim,
        latitudelim = latlim,
        col = fillcol, 
        proj = proj,
        grid = c(2,1))
```
Here, I expect the 'W' to be an 'O',  thankfully, the other three are the same in French (Spanish as well). This can wait a few days if need be.

**Comment by dankelley** [comment]
I suspect this occurs in e.g. `lonFormat()` at line 2834 of R/misc.R ... although I can't figure why I am using "E" and "S" later on there ... do you see why I'd do that?  I think it should be "E" and "W".

Anyway, I'll set this up after lunch.  I can't quite remember what you do to find the new strings and update those .po (or whatever files).  Do you remember that step?

**Comment by dankelley** [comment]
oh, I see ... translation instructions are on my blog! http://dankelley.github.io/r/2014/02/26/oce-translations.html

**Comment by clayton33** [comment]
I had a look through the code too. Is the assignment of "E" and "W", etc in `fixneg()` ?

**Comment by dankelley** [comment]
Yup.  I don't know whether it's an error or whether my other code is using this on both lons and lats.

**Comment by dankelley** [comment]
Can you pull "develop" and try it?  It might work.  I am not sure on the logic of that "E" and "W" but I changed it.  I don't know whether upper- or lower-case is conventional in French... please edit the files (see my blog post) and fix, if I made an error.

Offline for an hour now.

**Comment by clayton33** [comment]
Translations look good.

But the labels aren't working for me... Do they work for you ?

**Comment by dankelley** [comment]
Can you write a little test code for me?  Then I'll trace the logic flow.

**Comment by clayton33** [comment]
I used what I provided when I first opened the issue.

**Comment by dankelley** [comment]
Good lord.  Will you trust whatever code I write for a fix, if I missed that? 🤣

**Comment by dankelley** [comment]
I've coded in "develop" commit dc0edc40833af4ca47ee632df7e31c8939da35d1 (not tested yet, or checked -- those take 1/2 hour on my machine), and for your example I get as below. 

**"Ew, David"**, that looks terrible, because the letter `O` looks like the digit `0`. 

I guess we could put a degree sign in here, but that would also look weird (to me, anyway).  Maybe more space??

Do you have any examples of pretty maps in a French context? Honestly, I could be convinced to just drop the letters and use signed numbers, but that would be a big change to oce and I'm not sure I like doing that, plus some people don't seem to understand that longitude is negative in North America, etc.

![image](https://user-images.githubusercontent.com/99469/84423006-3ce17580-abf4-11ea-9197-b8084e096e61.png)

**Comment by clayton33** [comment]
I know, I know, it's not pretty. Ew, the `0` next to the `O` is not a good time. With a degree symbol it will look even worse. Let me dig around to see if I can find a French map example.

**Comment by clayton33** [comment]
I had a look at what PG does, as he's a good reference for these sorts of things,

https://waves-vagues.dfo-mpo.gc.ca/Library/40759738.pdf

andddd, he avoids it. Hah !

**Comment by clayton33** [comment]
OooOoo, a publication that was supposed to be in both languages, but look at Figure 1...

https://www.erudit.org/fr/revues/natcan/2018-v142-n2-natcan03735/1047147ar.pdf

**Comment by dankelley** [comment]
Yes, PSG makes amazingly beautiful graphs.  I wonder if we should have an arg to `mapPlot()` to control whether a letter is put there, or a degree sign, or both, and so forth.

Maybe it could be called `style`, and take numeric values, so we could have
* style=0 signed numbers ... which is what I like, to be honest
* style=1 as now (default)
* style=2 a degree symbol, with no letters or sign, as in paper at https://github.com/dankelley/oce/issues/1706#issuecomment-642849701
* style=3 a degree symbol, with letters, as in paper at https://github.com/dankelley/oce/issues/1706#issuecomment-642852734

And so forth.  I don't think this would be terribly hard to do

**Comment by clayton33** [comment]
Yeah, i'll leave it up to you, wouldn't be a bad idea for users to have the option. I personally like signed numbers the most as well.

**Comment by dankelley** [comment]
I'll look tomorrow. TBH, I don't really like the present default with the letter, because I would not do that with a pencil on paper.  I can see merit in putting the degree sign, though, since that is often present on maps.  One thing I really don't like is writing "Latitude" and "Longitude" there, because, again, that's not what I am used to seeing in pirate maps in comic books.

**Comment by clayton33** [comment]
Ok sounds good. I just tested it, and I think specific issues has been resolved, so I'll close it, and you can open a new one :)
