### ISSUE TITLE
Teledyne PD0 file - Percent good value lists only two numbers

### ISSUE THREAD

**Issue by jcurole** [dankelley/oce#1760]
To begin, thank you for the oce library.  This is a fantastic tool.

### Short summary of problem

I am analyzing some TD Workhorse PD0 files and my understanding is that the @g slot should contain percent good values which can be interpreted per p. 143 in the WorkHorse ADCP Output Data Formats document.  In the files I am analyzing the only values present are '00' and '64' which do not make sense in the context of p. 143 (seems like these should range from 0-100).

Is this an error code of some sort?  Am I misinterpreting the output from the PD0 file?  Any help is appreciated.

Best, Jason

### Output from sessionInfo()

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_1.2-0      gsw_1.0-5      testthat_2.3.2

loaded via a namespace (and not attached):
[1] compiler_4.0.2 magrittr_1.5   R6_2.4.1       tools_4.0.2    Rcpp_1.0.5     tinytex_0.25   xfun_0.17     
[8] rlang_0.4.7

**Comment by dankelley** [comment]
Dear reporter,

It would help if you could send a private email containing your data, which will let us try to reproduce the error. Be assured that your data will be held private, and discarded after the problem has been solved. Normally it is best to email it to both developers (kelley.dan@gmail.com and clark.richards@gmail.com) because we often work together on bug fixes. Thanks!!

PS.  This is a standardized reply.

**Comment by richardsc** [comment]
Yes, sending a file (or a portion) would be helpful. I suspect I might know why you don't see `g` data (you will only see percent good data if your unit was actually configured to do the ensemble averaging onboard). But looking at the various configuration bits and instrument details will help determine that.

**Comment by jcurole** [comment]
Dan and Richard,

Thanks.  Let me see what I can do.  I assume you are looking for the PD0 file?  You mention a portion of the file---how would that work?

**Comment by richardsc** [comment]
Yes, the PD0 file is what we need.

If the file is too big to send (or Dropbox or whatever), you can potentially just trim it to a smaller file (the ensembles are self-contained so it won't affect the reading if the whole thing isn't there). If you have access to a unix/linux prompt, you should be able to do that by doing something like:

```
$ head -c 10M input.PD0 > output.PD0
```

which will make a 10 megabyte file.

Though, I see you're on Windows ... not sure how to access that unless you have the Windows Subsystem for Linux or if windows Powershell can run those commands.

**Comment by jcurole** [comment]
Richard,

Thanks for the quick response.  Linux/unix isn't a problem as I do most of my work on a cloud server.  The bigger issue is that I work for a private company and I cannot share the data.  If there is a way that I can check myself on the unix system I am happy to report the results, if that helps.  Otherwise I can close the issue.

I also have a question about the correlation and echo intensity values which appear to be in hexidecimal, but I suppose I should open another issue for that?

Best, Jason

**Comment by richardsc** [comment]
Hi Jason,

Right, I understand. Let me think about it a bit (and look at some of the data I have on hand), and see if I can figure out what you should look for so I can understand your situation.

Can you at least paste the results of doing `summary(<objectName>)` and `str(<objectName>)` for the data that you've read in, so I can see the various metadata fields? You can of course scrub any sensitive information (serial numbers, cruise names, etc) before pasting, or if you'd rather provide in an email that's fine too. It would also be useful to know exactly what ADCP model you're using -- e.g. is it one of the newer Sentinel units?

My suspicion is that your unit wasn't set up to do the ensemble averaging internally, but rather to store all pings in an ensemble (just a guess). In this case, there are no percent good statistics because the profiles are all single pings.

As for the correlation and echo intensity, you can get them as numeric fields by doing, e.g.

```r
adp <- read.oce(<filename.PD0>)
echoIntensity <- adp[['a', 'numeric']]
```

They are stored as hex to save space, basically, but the second arg of `[[` does the conversion to numeric (while preserving the array properties).

**Comment by jcurole** [comment]
Apologies for the tardiness in my follow up.

Richard, after some digging it turns out you were correct.  Due to an incorrect setting there was only a single ping per ensemble in some of the earlier data I was reviewing.  As such, the quality values for these data were not being set and were showing up as 00 or 64.

I will now close this comment.

**Comment by richardsc** [comment]
Hi @jcurole -- no worries about the delay. Glad to hear that you figured it out.

In case you're interested in doing your own bin averaging, make sure you check out the `adpEnsembleAverage()` function in `oce`:

```
adpEnsembleAverage             package:oce             R Documentation

Ensemble Average an ADP Object in Time

Description:

     Ensemble averaging of adp objects is often necessary to reduce
     the uncertainty in velocity estimates from single pings. Many
     types of ADPs can be configured to perform the ensemble averaging
     during the data collection, due to memory limitations for long
     deployments. In cases where the instrument is not memory limited,
     it may be desirable to perform the ensemble averaging during
     post-processing, thereby reducing the overall size of the data set
     and decreasing the uncertainty of the velocity estimates (by
     averaging out Doppler noise).

Usage:

     adpEnsembleAverage(x, n = 5, leftover = FALSE, na.rm = TRUE, ...)
```

**Comment by jcurole** [comment]
Clark,

Thanks for the support.  Much appreciated.

I've hit another snag where read.oce is choking on some new PD0 files.
They open in WinADCP, so I don't think they are corrupt.  I had to turn my
attention to some other work, but I am going to make a request to share one
of these with you as I don't think there's any reasonable way for the team
to troubleshoot without a file.  Sadly, if I can't share them then it's
manual export via WinADCP :(

Best, Jason

**Comment by dankelley** [comment]
Please bear in mind that github should not be used to transmit the data (or a link to a dropbox site, or similar).  That way, the only people who could see the data are Clark and myself, and both of us are in positions that involve using confidential information.

**Comment by richardsc** [comment]
Hi Jason,

I agree -- it's next to impossible to diagnose the issue if we can't look at the raw binary files, since that is what oce is reading (based on the RDI manuals), and not any of the exports from WinADCP, etc.

As Dan said, we are accustomed to working with private data and keeping it confidential. If it helps, you can use our professional email addresses to correspond about it, rather than sharing files and details here on Github (though we would like to keep track of what the actual PROBLEM is, it is not necessary to post any details of the actual data here).

My email is: clark.richards AT dfo-mpo.gc.ca (Canadian government scientist)
Dan's is: dan.kelley AT dal.ca (Canadian university professor)
