### ISSUE TITLE
Should a Nortek Aquadopp be a "cm-class" object?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1762]
In following on from my "deep dive" into Nortek aquadopp data, I'm wondering if it should actually be classed as a `cm` (current meter) object, since actually that's what it is.

The counter argument is that it is in fact nearly identical to the equivalent current *profilers*, with the only difference being that it uses a single cell (instead of a profile of them, as with the `adp` class). The data structures are also nearly equivalent, though because there is only one cell we end up with a slightly odd array that has dimensions `(ntime, 1, nbeams)`.

@dankelley is it possible to have it inherit from *both* `adp` and `cm` classes? Or would it be too much hassle to switch things around? I'm mostly just thinking out loud here ...

**Comment by dankelley** [comment]
I don't think multiple inheritance is a good thing.  Say something inherits from classes `A` and `B`.  For example, when a `plot()` is called, should R call `plot,A-method` or `plot,B-method`?

There's also the matter of existing code.  My guess is that the existing code will end up needing perhaps a dozen lines of modification, and that's an awful lot easier than writing new code or copying a big mass of code.  (The problem with copying it that now there are two big blogs of code that will need to be altered if the manufacturer changes things.)

I don't see any real problem of only having a single cell.  Our code was not written with that in mind, and so it's possible at some points we will need to do things like adding a `drop=FALSE` argument to avoid rank reduction, etc.  But doing such things is unlikely to cause problems with other stuff.

We have a lot of code in-place and pretty well-tested for nortek.  And some of that is in C.  We've modified it for lots of different instrument types, and although that means it is long, it also means it is a good place to start.  Certainly there is very little codebase in common between `adp` and `cm` cases, so this feels to me like an `adp` situation.

**Comment by richardsc** [comment]
I thought about this some more, and I think one solution would be to add functionality to `as.cm()` to handle converting this kind of `adp` (or perhaps *any* `adp` object ...).

**Comment by dankelley** [comment]
I made `as.cm()` do this:

commit 8bc03688376f44f8b8023828d0986182f59d42a5
Author: dankelley <kelley.dan@gmail.com>
Date:   Sat Jan 2 08:39:33 2021 -0400

    as.cm() takes adv or 1-cell-adp as first arg


This requires the adp to have just 1 cell, but it produces an error msg telling what to do otherwise. Below is an `adv` example.

**NOTE TO CLARK:** this code does *not* ensure that the coordinate system of the `adp` or `adv` object is ENU.  Maybe it should.  Or maybe it should convert to that.  The reason I bring this up is that the `plot,cm-method` displays components in an E-N coordinate system, not an x-y one.  This goes back to the original `read.cm` code, which was for current meters that (I think) *always* had compasses.  *Question for Clark:*: do you think `as.cm()` should insist (or convert) to ENU?  My preference would be to produce an error if it's not ENU.  The error can tell the user what to do (which is simple).  My reasoning is that doing things like that can confuse a user.  For example, a person could do `plot(as.cm(ADP))` and see that water flows to the north, but then looking at the `ADP[["v"]]` data they might find very different results, and wonder why.  They ought to do `toEnu(ADP)` if they want ENU results.  I think this needs some discussion, though.  What are your thoughts, Clark?

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.0, PROJ 7.2.0
data(adv)
cmAdv <- as.cm(adv)
plot(adv)
```

![](https://i.imgur.com/jDxNdzq.png)

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
Oh, hang on.  I just looked at the comment I just made, and the cm plot is in 'u' and 'v', which is good.  I thought it would end up being in ENU even if the first arg had been in XYZ.  Anyway, the next step is to see if this works on the 1-cell adp dataset which is the subject of this issue.  Let's get it doing something reasonable on an actual application first, dog-food style.

**Comment by richardsc** [comment]
I just tried the new `as.cm()` functionality, and it seems to work great.

I agree that it might be worth adding a warning if the original coordinate system is not in ENU, though I don't think it should fail on that case. U and V are generic enough that they could use used for non-east/north velocities (e.g. XYZ coordinates or even rotated E/N). The warning could be something like:

> Original coordinate detected as something other than ENU (east-north-up). Use caution when interpreting results.

One other deficiency is that the `cm-class` objects (based off of data from an S4 current meter) are not designed to hold `w` (vertical) velocities. So currently the `as.cm()` throws away one of the velocity components ... maybe that's ok here, since we're just doing a class conversion (for convenience) and not a real "analysis" step.

**Comment by richardsc** [comment]
Based on the f2f Z call with @dankelley yesterday, it was decided that it wasn't high priority to add any extra checking to the `as.cm()` call. This is the kind of thing that a user digging into a complicated dataset will need to keep in mind anyway, so no sense chasing squirrels that haven't even been spawned.

Closing!
