### ISSUE TITLE
plot.aquadopp doesn't work

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1773]
> plot(d)
Error in z[, y.look] : incorrect number of dimensions

**Comment by richardsc** [comment]
Since I just sent a sample file (to be used for the orientation discussion in #1761), I wonder if @dankelley could take a look here too -- I don't have as much time today as I planned, and the plotting code in `adp.R` that handles all the various different cases and instruments is quite a tangle.

One thing I'm confused about is that there seems to be some blocks in the code that are checking the `instrumentType` field from the `@metadata`, but with the current version of oce reading the sample aquadopp file I see that `instrumentType` doesn't exist. I tried manually adding it (`d@metadata$instrumentType <- 'aquadopp')` but that didn't fix the issue.

**Comment by dankelley** [comment]
Thanks. I'll likely take a look tomorrow.  The code is pretty complex, as you say, and it will require a bit of time to become (re)submerged in it.

**Comment by dankelley** [comment]
I think I have it working in the "develop" branch, commit 72c3d91afde6904eb118245432d374922dd84963 ; below is a reprex.  I did a quick check, and `plot()` still works for `data(adp)`.

Please have a look, @richardsc, whenever you get a chance.  (This was a simple fix, so no worries about delays in getting back to me, because there's no need for me to retain memory of the steps in a more complex recoding.)

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.0, PROJ 7.2.1
d <- read.oce("~/aqd9330.aqd")
#> Warning in decodeHeaderNortek(buf, type = type, debug = debug - 1): using fixed
#> cell size and blanking distance for Aquadopp, since cannot infer these from the
#> file
plot(d)
```

![](https://i.imgur.com/DEcm52E.png)

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
