### ISSUE TITLE
trouble reading ctd files from IOS database

### ISSUE THREAD

**Issue by jchawarski** [dankelley/oce#1778]
I have some CTD files from a 2007 cruise from DFO's CIOOS database (https://catalogue.cioos.ca/dataset/ios_ctd_profiles)

I've tried each of the functions in the oce pkg, but to no avail. Metadata header seems to lead with a * which is throwing it off, I think. I tried writing a custom read.table function, but I think the header length varies from file to file. 

Anyone have experience working with these files in R?

Thanks!

Couldn't drag and drop the file, but here is the start of the header:

*2017/03/24 16:48:33.44
*IOS HEADER VERSION 2.0      2016/04/28 2016/06/13 IVF16

*FILE
    START TIME          : UTC 2007/07/16 17:53:30.000
    TIME INCREMENT      : 0 0 0 0.416667E-01 0  ! (day hr min sec ms)
    NUMBER OF RECORDS   : 145
    DATA DESCRIPTION    : CTD
    FILE TYPE           : ASCII
    CRC                 : 9F166858
    NUMBER OF CHANNELS  : 12

    $TABLE: CHANNELS
    ! No Name                        Units           Minimum        Maximum
    !--- --------------------------- --------------- -------------- --------------
       1 Pressure                    decibar         2.015          145.758
       2 Depth                       metres          1.994319       144.4617
       3 Temperature:Primary         'deg C (ITS90)' -1.7659        1.9666
       4 Transmissivity              %/metre         43.1           69.5
       5 Fluorescence:URU:Seapoint   mg/m^3          0.31E-01       1.597
       6 PAR                         uE/m^2/sec      0.47E-01       410.627
       7 PAR:Reference               uE/m^2/sec      1183.8         1186.4
       8 Salinity:T0:C0              PSS-78          24.5593        33.3151
       9 Oxygen:Dissolved:SBE        mL/L            7.448          9.511
      10 Oxygen:Dissolved:SBE        umol/kg         323.8          414
      11 Nitrate_plus_nitrite:ISUS   volts           0.526          0.878
      12 Number_of_bin_records       n/a             15             40
    $END

**Comment by richardsc** [comment]
Hi! Could you email an example file to clark.richards@gmail.com and dank.kelley@dal.ca?

Also, is there a manual or something that describes the data format? I should know the answer to this but ....... don't get me started on DFO data management. 

Reading IOS files has come up before, I think, but I can't remember where we stand in it. I can look at this later this evening, probably.

**Comment by dankelley** [comment]
Clark,
 
1. I am going to email a sample file that the reporter sent me.  (To reporter: both Clark and I are capable of keeping data secret.  It looks like these are not actually secret, from your first comment, but even so, please post here saying if it's ok for us to work with the data.  We may want to discuss file contents here, to figure things out.)
2. I've written some sample code (below). I am pretty sure this fails because there is an extra column in the data (at line 641) that is not named in the portion from which I'm trying to infer column names.  That's why the code fails.  We could just add another name to the `names` variable, although that woujld be guessing, and I don't like doing that.
3. My code does not try to determine the *useful* names of the data.  For example, the temperature column is named `"Temperature:Primary"`, and I suppose we could rename that as `"temperature"` to work in `oce`, but who knows just what another temperature, or a third one, might be called.

Julek,

Although we can quite likely help you with the rudiments, it will be a fair bit of work getting the nuances.  For example, unless we write code to scan more of the header, we won't be getting the exact units and scale for temperature, we won't get longitude and latitude, we won't get time, etc ... we won't get all that useful information that's in the header.  The problem is twofold, as I see it:

1. We don't have documentation for this file format, and it seems not quite worth the effort of coding up something that might work for one file and not another.  (For example, I had to make guesses about a reasonable way to infer column names ... and the columns in the file do *not* match what was in the original .cnv file, from what I can tell.)
2. You'd be better off finding out from someone if there are original files somewhere.  Files ending in `.cnv` are really pretty common, and my guess is that these files were constructed from those files. 

That's it from me until tomorrow.  Clark will likely have good ideas, but I'd hope that he takes the evening off!



``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
f <- "2007-019-055.ctd"
lines <- readLines(f, encoding="latin1")
#> Warning in file(con, "r"): cannot open file '2007-019-055.ctd': No such file or
#> directory
#> Error in file(con, "r"): cannot open the connection
endLine <- grep("^\\*END OF HEADER$", lines)
#> Error in as.character(x): cannot coerce type 'closure' to vector of type 'character'
if (0 == length(endLine))
    stop("file \"", f, "\" does not contain an \"*END OF HEADER\" line")
#> Error in eval(expr, envir, enclos): object 'endLine' not found
headerLines <- lines[seq(1, endLine-1)]
#> Error in seq.default(1, endLine - 1): object 'endLine' not found
# Next is brittle, being framed on a number of spaces at the start.  It might
# be better to look for the string "TABLE: CHANNELS" and then skip some lines,
# but isn't that risky, too?  Who knows which elements of the format are fixed,
# and which might be variable?
n <- grep("^[ ]{6,7}[1-9]{1,2} [A-Z]", headerLines)
#> Error in grep("^[ ]{6,7}[1-9]{1,2} [A-Z]", headerLines): object 'headerLines' not found
nameLines <- headerLines[n]
#> Error in eval(expr, envir, enclos): object 'headerLines' not found
names <- gsub("^[ 1-9]*([^ ]*) .*$", "\\1", nameLines)
#> Error in gsub("^[ 1-9]*([^ ]*) .*$", "\\1", nameLines): object 'nameLines' not found
dataLines <- lines[seq(endLine+1, length(lines))]
#> Error in seq(endLine + 1, length(lines)): object 'endLine' not found
d <- read.table(f, skip=1 + endLine)
#> Warning in file(file, "rt"): cannot open file '2007-019-055.ctd': No such file
#> or directory
#> Error in file(file, "rt"): cannot open the connection
if (dim(d)[2] != length(names))
    stop("cannot determine column names. dim(d)[2] is ", dim(d)[2], " but # of names is ", length(names))
#> Error in eval(expr, envir, enclos): object 'd' not found
colnames(d) <- names
#> Error in colnames(d) <- names: object 'd' not found
```

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
Just want to point out that @dankelley's advice about finding the CNV files is not going to be helpful here -- as I see it these are *processed* CTD data that have been run through an entire stream of data cleaning and recalibrating, something that wouldn't be captured in whatever CNV was used at the beginning of the process.

But I agree with Dan -- one can always write code to read all the nuance's of the header metadata, but for these files it is quite a bit of work (I guess why we've never done it before, even though I work at DFO ... ). Dan's code above will be a good start, which can then get passed through an `as.ctd()` call to turn it into a nice CTD object (for making plots, sections, further analysis, etc).

I will point out that there is a bug in Dan's code above that causes it to miss the:
```
      10 Oxygen:Dissolved:SBE        umol/kg         351.1          417.5
```
line, which is why it thinks there is one extra column when it actually reads the data. Seems like a more sensible approach would actually be to use the `$TABLE`/`$END` tags that delineate the data headers.

**Comment by dankelley** [comment]
Yes, my code is confused because a name (`Oxygen:Dissolved:SBE`) occurs *twice*.  Inferring by parsing between TABLE and END would fix that.

I see lots of things that a code should do.  For example, I see lon and lat in the metadata, and forcing a user to read the file manually and add them to the ctd object seems crazy.

And I'm sure that once that's done, another task would seem reasonable.

The problem is that each task will take time.  If these data exist in another form, I do think it would be best just to get those data.  If not, then it becomes quite important to get some documentation, before writing a lot of code that might work for one file and not the next.  Certainly, for such code to enter oce -- which I think is a good idea, if this format is commonly used by the West coast DFO folks -- it would be important to have an open-access document describing the format.  This is a general thing with oce: we don't want to waste developer time coding and recoding by guessing at formats, and we don't want to waste user time trying to use brittle code.

I'm pretty sure that such documents must exist.

Perhaps, @jchawarski, if you have some R skills, you could lend @richardsc and me a hand in this.  The way to approach it is to write standalone code at first, before we even think of putting code into R.  We'd also need an open-access file for testing, so a subset of that file could be inserted into the oce test suite.

I think the priorities for now are:
1. infer column names more robustly, using the START and END tags
2. infer longitude and latitude
3. infer time of sample
4. learn the syntax used for secondary, tertiary, etc sensors

However, the first step (to oce inclusion, as opposed to special-purpose code) is surely to get documentation.  It's silly, for example, to code in a regular expression to find the components of longitude, in degrees and minutes in the sample file, only to find that in other files it might be in decimal degrees.  Or do we code for both now, just in case?  And are "W" and "E" always given, or just sometimes ... is sign used sometimes?

**Comment by dankelley** [comment]
I've coded some more of a solution.  From now, it should be easy for @jchawarski to (a) find docs, which must be open-access, (b) figure out how we can decode common column names, and some other things noted in the code.  

Once such things are done, we (likely all 3 of us together) could move on to  things like (a) inferring information from those 'blocks' in the file, not just by regular expressions (the reg exp method is risky, e.g. I find longitude by looking for `LONGITUDE` on a line, but what if that's part of the name of a research program or something, so it occurs more than once), (b) inserting 'original names', (c) inserting units, etc. ... 

I think this could go into `oce` pretty soon, but the first step is to get open-access docs.

@jchawarski what's your skill level in R?  A general approach of open-source programming is to encourage users to contribute code.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
f <- "~/2007-019-055.ctd"
lines <- readLines(f, encoding="latin1")
endLine <- grep("^\\*END OF HEADER$", lines)
if (0 == length(endLine))
    stop("file \"", f, "\" does not contain an \"*END OF HEADER\" line")
headerLines <- lines[seq(1, endLine-1)]
# Location -- FIXME should be looking in blocks, not using regexps
lon0 <- strsplit(headerLines[grep("LONGITUDE", headerLines)], " +")[[1]]
longitude <- as.numeric(lon0[4]) + as.numeric(lon0[5])/60
if (lon0[6] == "W")
    longitude <- -longitude
lat0 <- strsplit(headerLines[grep("LATITUDE", headerLines)], " +")[[1]]
latitude <- as.numeric(lat0[4]) + as.numeric(lat0[5])/60
if (lon0[6] == "S")
    latitude <- -latitude
cat("location:", longitude, "E, ", latitude, "N\n")
#> location: -103.9175 E,  68.67948 N

tmp <- strsplit(headerLines[grep("START TIME", headerLines)], " +")[[1]]
startTime <- as.POSIXct(paste(tmp[6], tmp[7]), tz="UTC")

# Next is brittle, being framed on a number of spaces at the start.  It might
# be better to look for the string "TABLE: CHANNELS" and then skip some lines,
# but isn't that risky, too?  Who knows which elements of the format are fixed,
# and which might be variable?
n <- grep("^[ ]{6,7}[0-9]{1,2} [A-Z]", headerLines)
nameLines <- headerLines[n]
names <- gsub("^[ 1-9]*([^ ]*) .*$", "\\1", nameLines)
# Rename data.  This is done in a brittle way for now, just as a test
dataNamesOriginal <- names             # FIXME: oce would want this
names[names=="Pressure"] <- "pressure"
names[names=="Depth"] <- "depth"
names[names=="Temperature:Primary"] <- "temperature" # BUG: will not handle secondary data
names[names=="Salinity:T0:C0"] <- "salinity" # BUG: will not handle secondary data
# We could change some other names but this is enough for basic work, and we do
# not have documentation on the names anyway, so this is a bit of a fools game.

dataLines <- lines[seq(endLine+1, length(lines))]
d <- read.table(f, skip=1 + endLine)
if (dim(d)[2] != length(names))
    stop("cannot determine column names. dim(d)[2] is ", dim(d)[2], " but # of names is ", length(names))
colnames(d) <- names

# BUG: next should work, but it does not record the lon and lat
# ctd <- as.ctd(d, longitude=longitude, latitude=latitude)
ctd <- as.ctd(d)
ctd <- oceSetData(ctd, "longitude", longitude)
ctd <- oceSetData(ctd, "latitude", latitude)
ctd <- oceSetMetadata(ctd, "startTime", startTime)
summary(ctd)
#> CTD Summary
#> -----------
#> 
#> * Start time:          2007-07-24 12:58:49
#> * Mean location:       68.679N 103.92W 
#> * Data Overview
#> 
#>                                 Min.    Mean    Max. Dim. NAs OriginalName
#>     pressure [dbar]                3  51.497    99.9   98   0            -
#>     salinity [PSS-78]         13.283  28.802  29.736   98   0            -
#>     temperature [°C, ITS-90] -1.6028 -1.3202  0.5814   98   0            -
#>     longitude                -103.92 -103.92 -103.92    1   0            -
#>     latitude                  68.679  68.679  68.679    1   0            -
#> 
#> * Processing Log
#> 
#>     - 2021-02-05 11:05:36 UTC: `create 'ctd' object`
#>     - 2021-02-05 11:05:36 UTC: `as.ctd(salinity = d)`
#>     - 2021-02-05 11:05:36 UTC: `oceSetData(object = ctd, name = "longitude", value = longitude)`
#>     - 2021-02-05 11:05:36 UTC: `oceSetData(object = ctd, name = "latitude", value = latitude)`
#>     - 2021-02-05 11:05:36 UTC: `oceSetMetadata(object = ctd, name = "startTime", value = startTime)`
plot(ctd)
```

![](https://i.imgur.com/rCQRsG3.png)

``` r
message("\n\nFIXME: read other columns, set original names, etc (see github)")
#> 
#> 
#> FIXME: read other columns, set original names, etc (see github)
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
PS. I made a gist (https://gist.github.com/dankelley/6528c82bd2c569ec659157f9bf9eed4f) for this code, so we can add to it and track changes more easily than with isolated code in comments or .R files.

**Comment by dankelley** [comment]
Better than a gist, I've put code into the `oce-issue` repo, at https://github.com/dankelley/oce-issues/blob/main/17xx/1778/1778a.R

**Comment by dankelley** [comment]
I updated https://github.com/dankelley/oce-issues/blob/main/17xx/1778/1778a.R so now it looks for regular expressions within blocks.  This will e.g. prevent a problem if some header line had the string `"LATITUDE"` in it, which could happen for perhaps the name of a mission, etc.  It also now grabs column names from that block, but the next step would be to look *within* the block for the "table" designators, to avoid more false positives.

We really need docs before proceeding further, I think.  The code is simple enough that any novice user could add the renaming of some of the other columns, for insertion into the `oce` object.

So, I'm done for a while.

**Comment by clayton33** [comment]
We (me and CR) got this request back in September from a colleague at BIO, but it never went anywhere...  I don't think.  I'm touching base with them to see if the ended up locating some documentation, but note that they are on the west coast at the moment so I might not hear back from them until after 12h00 AST.

**Comment by richardsc** [comment]
I’m going to suggest that this would be a good opportunity to apply the rule that we keep talking about, that new functionality like this (which is somewhat standalone) would be better in a nice compact package if it’s own (that hangs off oce of course). 

This is partly motivated by the fact that we just updated oce on CRAN, and so updating for something that doesn’t require compilation etc seems excessive. Since it will only R code it is an easy install_github() call.

**Comment by dankelley** [comment]
That could make sense.  There might be a question as to whether CRAN wants packages that hold just a single function, but perhaps (and I would love to see this) there could be a `dfo` package, into which code for ODF could go, along with code for this IOS format, along with other stuff.  And DFO is big enough that they can run their own CRAN-like repository, meaning that they could update the code monthly if they wanted (which CRAN would never allow).

DFO could always just put stuff into GH, because I think a lot of folks get code from there, but the advantage of a CRAN-like setup is better testing, and demonstrations of those tests on a website.

Anyway, I don't work at DFO so I'm just rambling here.  Actually, it's Munro Day, so I guess I'm not working for Dal today, either :-)

**Comment by dankelley** [comment]
I've updated  https://github.com/dankelley/oce-issues/blob/main/17xx/1778/1778a.R  to have a self-contained function, with rudimentary docs.  I agree with @richardsc that it would make sense to think of this as a function in a new package that adds on to `oce`.  After all, we just released a CRAN version of `oce` a few days ago, and CRAN discourages frequent updates.

I'd be happy to look at this some more if we get docs.

**Comment by jchawarski** [comment]
Hi guys, 

First of all, I am astounded at how quickly you jumped on this. I don't think that I have much to contribute, yet. However I was provided a simpler data format after following up with folks at DFO. I've sent that version to Clark via email. It's a short term fix on a larger problem which we probably all agree on: DFO needs to do a better job of making their data available in a useable format in it's databases, without the need to track down data curators, some of which are starting to retire. I'll follow up once I get somewhere with the data I have in hand. 

Thanks again!

**Comment by clayton33** [comment]
Got some more information on this file format. They're planning on phasing it out soon and transition to `.nc` format, and they have some in-house software to convert the format to `.csv` so we might want to put the breaks on this for the time being, unless we get some documentation.

**Comment by dankelley** [comment]
The code at https://github.com/dankelley/oce-issues/blob/main/17xx/1778/1778a.R is now quite a lot cleaner and more robust.  Handling new column names and units is now quite easy (see first two lines of `read.ctd.ios.R`).

@jchawarski I think this is ready for use now.

Please note that we are thinking of releasing this and similar oce add-on code in a new package (see https://github.com/dankelley/oce/issues/1778#issuecomment-774021080). The idea of that is to provide an easy path for users.  Adding things into `oce` means that users will need to update that package, either using CRAN (which means things can only change on semi-yearly periods) or using Github (which can be tricky since it requires both C++ and Fortran compilers).

**Comment by dankelley** [comment]
@jchawarski -- any chance you could document here, in a comment (possibly with screenshots) how you actually got the sample `.ctd` file that you sent, from the IOS website?  All I can find is an erdapp, which is really tricky to understand.  Is there a way you can a directory of `.ctd` files?

It's odd that I find it easier to write code to read these files than it is to find the files on this government server.

**Comment by dankelley** [comment]
@jchawarski I have made a new R package named, at least provisionally, `dfo`.  This name may change at any time, and if so, I'll edit this comment.  I may also simply remove this package at any time ... it's an experiment in our new approach of making add-on packages to oce.

To learn how to use the package, visit https://github.com/dankelley/dfo and run the code that is in the subsection called `Usage`.  It ought to work.  I am assuming that this file is open-access enough that I can insert it into a package.  If not, I'll have to remove it.

It should be obvious how to proceed: simply change the second line to define a variable naming a local file of interest.

I advise using `summary()` on anything you read, to check that the variable names are simple and follow the `oce` convention.  If any of them come out as upper case strings, especially with colons in them, then that means that `read.ctd.ios()` needs to be tweaked. Those tweaks should be very easy, if you provide me with a sample file over email.

Note that there are two big advantages to this new package:
1. It does not requite a Fortran or C++ compiler to build, and so it ought to be very easy (and fast) for users to update their version
2. It is very small, so builds will take only a couple of seconds.  On most machines, an `oce` build takes several minutes (up to half an hour, if you check the built product).

Please tell me about any problems with this new package by raising an Issue there.

PS. to @richardsc and @clayton33 please let me know if you think it's wrong for me to call this package `dfo`.  It seems crazy to have a package with just one function, but it seems as though IOS is going to switch to a new format soon.  And, the `dfo` package might be a good place to put new `ODF`-related code.

Dan.

**Comment by richardsc** [comment]
Two things (only two because it's the weekend and I'm trying to take a "break" from work ... haha):

1. That package looks great -- I think it's pretty clear that a small package to solve a need could quickly grow to accept new things that folks need.

2. Re: the data locating question -- I went down the ERDDAP rabbit hole for awhile today, and I have to say I came out more confused than when I went in. First, I wasn't able to find the file that @jchawarski referenced when opening this issue, but I WAS able to find what I think are the same data but in a netCDF format ... How? Good question, it was a bunch of clicking somewhat random things ... I think I started here:

https://catalogue.cioos.ca/dataset/ios_ctd_profiles

and clicked the "Explore" pull-down and selected "Go to resource", which goes here:

https://data.cioospacific.ca/erddap/tabledap/IOS_CTD_Profiles.html

But that search page is CRAZY, so instead I clicked "Subset" in the tiny little menu at the top:

![image](https://user-images.githubusercontent.com/233584/107135723-6e215b00-68d3-11eb-8ed8-23fdb4299eba.png)

which takes me here:

https://data.cioospacific.ca/erddap/tabledap/IOS_CTD_Profiles.subset

Then, I selected as follows from the subset pulldown menus:

![image](https://user-images.githubusercontent.com/233584/107135743-990baf00-68d3-11eb-9216-890b3bfd2457.png)

and then clicked on "Files" in the top menu (why? I have no idea ...)

![image](https://user-images.githubusercontent.com/233584/107135752-afb20600-68d3-11eb-866b-d5cefd21932d.png)

That brings me here: https://data.cioospacific.ca/erddap/files/IOS_CTD_Profiles/ which looks like a directory file listing. Selecting `2007/` brings me here:

https://data.cioospacific.ca/erddap/files/IOS_CTD_Profiles/2007/

which looks like this:

![image](https://user-images.githubusercontent.com/233584/107135772-dc661d80-68d3-11eb-9da1-05f1b4389167.png)

Then I just scrolled until I found the file `2007-019-005.ctd.nc` (note the `0055` instead of `055` in the original `.ctd` file), which I read quickly using the `oce` function `read.netcdf()`:

```r
dd <- read.netcdf('~/Downloads/2007-019-0055.ctd.nc')
dd
```
```
oce object has data as follows.
   filename: 2007-019-0055.ctd
   country: Canada
   mission_id: 2007-019
   scientist: Zimmermann S.
   project: Canada's Three Oceans
   agency: IOS, Ocean Sciences Division, Sidney, B.C.
   platform: Louis S. St. Laurent
   instrument_type: Sea-Bird CTD
   instrument_model: SBE-911plus
   instrument_serial_number: 0724
   latitude: 68.679
   longitude: -103.92
   geographic_area: Canadian-Arctic-Archipelago-South 
   event_number: 55
   profile: 2007-019-0055
   time: 1185281929
   PRESPR01, a 99x1 array with value 2.0999999 at [1,1] position
   depth, a 99x1 array with value 2.0999999 at [1,1] position
   TEMPS901, a 99x1 array with value 0.0046000001 at [1,1] position
   PSALST01, a 99x1 array with value 8.51509953 at [1,1] position
   DOXYZZ01, a 99x1 array with value 9.14999962 at [1,1] position
   DOXMZZ01, a 99x1 array with value 406 at [1,1] position
```

# `rerddap` package

THEN I remembered there's an R package for accessing ERDDAP servers, which I figured I could point to the `cioospacific` ERDDAP to get the file through the ERDDAP/package API. 

But I couldn't actually figure it out.

As far as I can tell, you can only access ERDDAP servers that the package knows about -- which honestly seems like a weird approach to me. And as it turns out the "CIOOS Atlantic" ERDDAP *is* actually listed there, but not "CIOOS Pacific" .... sigh ...

```r
library(rerddap)
servers()[grep('Canadian', servers()$name), ]
```
```
# A tibble: 1 x 4
  name                              short_name    url                     public
  <chr>                             <chr>         <chr>                   <lgl> 
1 Canadian Integrated Ocean Observ… CIOOS Atlant… https://cioosatlantic.… TRUE  
```

**Comment by dankelley** [comment]
Wow, @clayton33, that's **amazing** detective work!!!

I tried taking another step (just jumping to the directory listings).  Indeed the file seems the same, except the `.ctd` file has other variables like `PAR`, etc.  Perhaps @jchawarski can document how that `.ctd` file was downloaded, in the same way as @clayton33 has documenting the recover of the `.nc` file.

A few more notes:
1. It looks as though `read.netcdf()` reads a ton of things.  I used `ncdf4::nc_open()` on the file, and it seems that maybe `read.netcdf()` reads all the variables.
2. Unsurprisingly, `read.netcdf()` does not rename the columns.  I don't think it should make guesses on that, either.  It should do what it says it does: just read a netCDF file.
3. When I tried `as.ctd()` on the result from `read.netcdf()`, it did not decode column names.  Frankly, I don't think it should, either.  Some other institution might name things differently, after all.  And a person might have *both* `pressure` *and* `PRESPR01`, for example.
4. It's pretty easy to fix variable names to get a useable CTD object, using e.g. `d<-oceSetData(d, "pressure",d[["PRESPR01"]])` on the object returned by `read.netcdf()`, and then doing similarly for the other variables.  It will make sense to use two different names for the two oxygen values, and `"oxygen"` along with `"oxygen2"` is the choice that's consistent with how oce names things.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
download.file("https://data.cioospacific.ca/erddap/files/IOS_CTD_Profiles/2007/2007-019-0055.ctd.nc","2007-019-0055.ctd.nc")
d <- read.netcdf("2007-019-0055.ctd.nc")
summary(d)
#> * Data Overview
#> 
#>                                 Min.    Mean    Max. Dim. NAs OriginalName
#>     filename                      NA      NA      NA    1   0            -
#>     country                       NA      NA      NA    1   0            -
#>     mission_id                    NA      NA      NA    1   0            -
#>     scientist                     NA      NA      NA    1   0            -
#>     project                       NA      NA      NA    1   0            -
#>     agency                        NA      NA      NA    1   0            -
#>     platform                      NA      NA      NA    1   0            -
#>     instrument_type               NA      NA      NA    1   0            -
#>     instrument_model              NA      NA      NA    1   0            -
#>     instrument_serial_number      NA      NA      NA    1   0            -
#>     latitude                  68.679  68.679  68.679    1   0            -
#>     longitude                -103.92 -103.92 -103.92    1   0            -
#>     geographic_area               NA      NA      NA    1   0            -
#>     event_number                  NA      NA      NA    1   0            -
#>     profile                       NA      NA      NA    1   0            -
#>     PRESPR01                     2.1  50.998    99.9 99x1   0            -
#>     depth                        2.1   50.74    99.4 99x1   0            -
#>     TEMPS901                 -1.6028 -1.3068  0.5814 99x1   0            -
#>     PSALST01                  8.5151  28.597  29.736 99x1   0            -
#>     DOXYZZ01                    8.05  8.7437    9.56 99x1   0            -
#>     DOXMZZ01                   351.1   381.6   417.5 99x1   0            -
#> 
#> * Processing Log
#> 
#>     - 2021-02-07 10:38:53 UTC: `Create oce object`
#>     - 2021-02-07 10:38:53 UTC: `read.netcdf("2007-019-0055.ctd.nc")`
```

<sup>Created on 2021-02-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment]
My last comment suggests that `dfo::read.ctd.ios()` ought to detect whether the file ends in `.ctd` (in which case it would existing code) or in `.nc` (in which case it would use `oce::read.netcdr()` and then rename columns.  So I'll do that (well, first I'll make an issue in `dfo`).

**Comment by jchawarski** [comment]
Hi Dan, thanks for putting this together! read.ctd.ios seems to work smoothly. Truly appreciated!
