### ISSUE TITLE
How to handle multiple recordings of single parameter when building CTD object from data.frame?

### ISSUE THREAD

**Issue by janstrauss1** [dankelley/oce#1780]
Hi @dankelley and @richardsc,

This might be a very basic question but I am not sure how to correctly build a CTD object from an R `data.frame` using `as.ctd`.

Generally, using `as.ctd` as well as `oceSetData` to add some optional data works very well for me but I'm not sure how to deal with multiple (duplicate) recordings that I have for individual parameters (e.g. temperature, salinity...)?

Please see the attached example table [ctd_data.xlsx](https://github.com/dankelley/oce/files/5965121/ctd_data.xlsx) that contains example data for all CTD measurements that I have (including some duplicate recordings of the same parameter). 
I would appreciate if you could briefly outline how to best build an CTD object from such data set.

I would also be very interested in how `oce` handles multiple recordings of single parameters in general? Does it use averages for plotting?

Many thanks in advance for your feedback!

**Comment by dankelley** [comment]
`oce` uses only the first-provided data.  The typical creation of `ctd` data is via `read.ctd()`, and what that does is to decode names (changing maybe `PSAL` to `salinity`, and so forth), and then to use an oce function to rename duplicates, so that the first-found salinity will end up with name `salinity`, and the next-found one would be `salinity2`.

When you access with e.g. `a[["salinity"]]`, it returns the first salinity data, not any others.

And this `[[` method is used in plotting.

So, simply put, the `read.ctd*()` functions focus on the first-found data.  If you want to do something else, the best plan is to use `oceSetData()` to make, say, `salinity` be whatever it is you want.  That might be an average of multiple data streams, or a smoothed version of data, or anything else that makes sense for your science.

Now, as to `as.ctd()`, the normal scheme is to use `as.ctd(yourS, yourT, yourP)` with whatever you want.  Those things get named `salinity`, etc.  You can then use `oceSetData()` to add in `salinity2` (or any name you like) and then you can get these from the `[[` operator, but they will **be ignored** by things like `plot()` and `swN2()`, etc.

I hope this is clear.  @richardsc might have a better way of explaining it.  I seldom use any of the `as.*()` functions, since I tend to work with recognized data files (like SBE files), which means that I can rely on `read.ctd()` for getting the units right, populating relevant metadata, etc.

**Comment by richardsc** [comment]
I agree with all of @dankelley 's points, though I am maybe more often using the `as.ctd()` to build up a ctd object because I find I tend to read data from a lot of weird formats that would never be worth the work of actually coding into `oce`. Usually, because I have a purpose in mind, I don't both with any duplicated sensors and just use the ones that I know I want for my analysis (since this step isn't meant to make any kind of "shareable" data file format but just to be able to use the `oce` helper functions, like `plot()`, `plotTS()`, sections, etc.

The xlsx file you attached looks like it almost certainly came from a SeaBird 911 CTD, which means that somewhere there are `.cnv` files that were the result of running the raw data (HEX+XMLCON) through the SBEDataProcessing. As Dan pointed out, the way we handle this when reading a CNV file is to detect the duplicated sensors and rename them accordingly. Notice how the `names()` of your sheet have distinct numbers, e.g. 1 and 2:
``` r
library(readxl)
ctd <- read_excel('~/Downloads/ctd_data.xlsx')
names(ctd)
#>  [1] "Depth[salt water, m]"                           
#>  [2] "Potential Temprature-1[ITS-90, deg C]"          
#>  [3] "Potential Temprature-2 [ITS-90, deg C]"         
#>  [4] "Potential Temperature Diff 2 - 1[ITS-90, deg C]"
#>  [5] "Conductivity-1 [S/m]"                           
#>  [6] "Conductivity-2 [S/m]"                           
#>  [7] "Conductivity Difference 2 - 1 [S/m]"            
#>  [8] "Salinity-1 [PSU]"                               
#>  [9] "Salinity-2 [PSU]"                               
#> [10] "Salinity Difference 2 - 1 [PSU]"                
#> [11] "Oxygen, SBE 43 [ml/l]"                          
#> [12] "Fluorescence"                                   
#> [13] "Beam Attenuation, WET Labs C-Star [1/m]"        
#> [14] "Beam Transmission, WET Labs C-Star [%]"         
#> [15] "Density-1 [sigma-theta, kg/m^3]"                
#> [16] "Density-2 [sigma-theta, kg/m^3]"                
#> [17] "Density Difference 2 - 1 [sigma-theta, kg/m^3]" 
#> [18] "Nitrogen Saturation [ml/l]"                     
#> [19] "PAR"                                            
#> [20] "Pressure, Digiquartz [db]"                      
#> [21] "Temperature [ITS-90, deg C]"                    
#> [22] "Temperature, 2 [ITS-90, deg C]"
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

So, you could wrap `as.ctd()` with an appropriate number of `oceSetData()` calls in your own function to convert the entire xlsx table into a valid `oce` object. A downside to this is that there is apparently no metdata contained in that file, giving e.g. lon/lat, startTime, station number, cruise, scientist, etc etc.

If you want to be careful about units you could also parse those from the names. If you go this route it might be helpful to look at the `oce` sources, particularly starting around [L245](https://github.com/dankelley/oce/blob/849b6888bf24805410630f344cf1ba174cf4b4e9/R/ctd.sbe.R#L245) in `ctd.sbe.R`.

**Comment by richardsc** [comment]
Unfortunately the numbered names aren't completely consistent, as you can see you have `Temperature` and `Temperature, 2`, but then `Conductivity-1` and `Conductivity-2`. Unfortunately it might just be easier to hardcode your `as.*()` function for the names that you have (provided they are consistent across files (example below to get you started).

As for the doubled sensors --  I'm not sure how familiar you are with ship-board CTD measurements, but usually the reason there are two T/C sensors is:

a) as a backup in case one of them fails in the middle of the cruise (there would also be backups of the backup), and

b) in case one of the sensors produces salinities that are not optimal, when compared against the bottle salinities.

Typically the person doing the post-cruise data processing will look at both salinities, compare them with the bottles, perform any corrections required (like a post-calibration) and then choose one of the two sensors that gives the data requiring the least amount of correction. So typically a "processed" archive of the data won't include salinity1 and salinity2, just whichever was judged to be "best".

I would also point out that any of those parameters related to physical seawater properties (e.g. salinity, density, potential temperature, and depth) are all calculated from C, T, p, and so don't *have* to be included in your `as.ctd()` call (because you can always just do them yourself with the `sw*()` or `gsw_*()` functions).

## Example function
``` r
read_jans_ctd_data <- function(file) {
    require(readxl)
    require(oce)
    d <- read_excel(file)
    ctd <- as.ctd(d[['Salinity-1 [PSU]']],
                  d[['Temperature [ITS-90, deg C]']],
                  d[['Pressure, Digiquartz [db]']])
    ctd <- oceSetData(ctd, 'conductivity', d[['Conductivity-1 [S/m]']],
                      list(unit=expression(S/m), scale=""))
    ctd <- oceSetData(ctd, 'conductivity2', d[['Conductivity-2 [S/m]']],
                      list(unit=expression(S/m), scale=""))
    ctd <- oceSetData(ctd, 'temperature2', d[['Temperature, 2 [ITS-90, deg C]']],
                      ctd[['units']][['temperature']])
    ctd <- oceSetData(ctd, 'salinity2', d[['Salinity-2 [PSU]']],
                      ctd[['units']][['salinity']])
    ## put more lines here for the other stuff you want
    ctd
}

file <- '~/git/rstuff/jan_ctd/ctd_data.xlsx'
ctd <- read_jans_ctd_data(file)
#> Loading required package: readxl
#> Loading required package: oce
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
plot(ctd)
```

![](https://i.imgur.com/WCxjt1V.png)

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by janstrauss1** [comment]
@dankelley @richardsc, many thanks for your very helpful advice and support! I really appreciate it!

Just to give you some background, I only recently started to work with oceanographic data sets (so your general comments on ship-board CTD measurements etc are very helpful for me!). 
Also, I only inherited these CTD data set from a former lab member but unfortunately, I couldn't find any `.cnv` files and actually imported the data from `.mat` Matlab files using `readMat` and I don't have much information on the post-cruise data processing etc...

Thanks again for the great support!
