### ISSUE TITLE
as.section() fails with a list of `argo` objects

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1781]
I'm not sure that it's *supposed* to work, but I've been dogfooding `argoFloats` for a project that I'm working on, and I found that it wasn't possible to make a `section` object out of the "argos" list contained in the argoFloats object after reading profiles. The way we used to work with `argo` objects in `oce` was to read the file that has ALL the cycles for a single ID, stored as a matrix, which `as.section()` can work on just fine.

Example:

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
library(argoFloats)
i <- getIndex()
si <- subset(i, ID=6901191)
#> Kept 171 profiles (0.00709%)
si <- subset(si, cycle=1:10)
#> Kept 10 profiles (5.85%)
d <- readProfiles(getProfiles(si, quiet=FALSE), quiet=FALSE)
#> Downloading 0 file(s)
str(d[['argos']], 1)
#> List of 10
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
#>  $ :Formal class 'argo' [package "oce"] with 3 slots
sec <- as.section(d[['argos']])
#> Error in if (is.na(thelist[[i]][["waterDepth"]])) {: argument is of length zero
```

<sup>Created on 2021-02-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
The problem appears to be related to a missing `waterDepth`, which I think I've seen in other objects that I've tried to make into a section. It seems like `as.section()` should be demanding that in this case, considering I recall that for other objects it will just assume that the `waterDepth` is equal to the maximum pressure.

If this is actually an `argoFloats` issue, please advise. Have either @dankelley or @j-harbin done analysis by making section objects out of argoFloats objects in the past?

**Comment by richardsc** [comment]
I can fix this by doing:
```r
sec <- as.section(lapply(d[['argos']], as.ctd))
```
which produces the expected warning about `waterDepth`:
```
Warning message:
In as.section(lapply(d[["argos"]], as.ctd)) :
  estimated waterDepth as max(pressure) for CTDs numbered 1:10
```
but I'm curious to hear (or discuss) whether it is reasonable to expect users to take that step.

**Comment by dankelley** [comment]
I think `as.section()` ought to stop worrying about `waterDepth` if it's not defined in the objects presented to it.  Sometimes, as with Argo floats, we just don't know. 

Well, actually, a user *could* look it up in a bathymetry file, if they really cared, and if they trusted the position recorded for the Argo float.  Personally, I'd be a "no" on both.  I'd just as soon see plots (which is the main purpose here, I imagine) stop at 1km or 2km or whatever it is.  Otherwise, in the average case, half or more of the plot would be gray colour for the bottom.  Also, I find that positions are bad in something like 10% of the (high-latitude) data I've been looking at lately.

**Comment by dankelley** [comment]
Further to my second paragraph above at https://github.com/dankelley/oce/issues/1781#issuecomment-778765465, the user can get interpolated topo with e.g. `plot(section, bathymetry=TOPO)`, where `TOPO` is a topography object.  I forgot about that.

**Comment by dankelley** [comment]
I don't want `argoFloats` users to have to download a new `oce`, and we cannot re-release `oce` this quickly for something so small (after all, `argoFloats` is not even on CRAN), so I prefer a solution within `argoFloats`.

This does not argue against changing `oce`, of course.  I don't think it should produce an error when `waterDepth` is not in the `metadata`, because the docs for `as.section()` say the first arg can be a list of `oce` objects ... they do not say a list of `ctd` objects!

Returning to `argoFloats`, though, this seems analogous to `argoFloats::applyQC()`, which is a wrapper that insulates users from the details of `oce::handleFlags()`, so that new features for `argoFloats` (not even on CRAN) would not demand changes to `oce` (on CRAN for a long time, on git for 13 years, on google-code before that, etc).

The question is to what this new `argoFloats` function should be named.  Since `applyQC()` is using a verb-noun format, I think that makes sense.  (Plus, it's less arcane than the `as.SOMETHING()` scheme used in R, likely going back through S+ to S.). A verb-noun pair that makes sense is `createSection()`.

@richardsc and @j-harbin, what do you think of this suggested name?  I vote +1 in the usual voting scheme.  Please let me know your thoughts on that (or some other suggested name).  Given work schedules, I suggest a decision on this by noon on Wed 2021 Feb 17 (the day before the new NASA rover is planned to land on Mars ... speaking of bottoms).

**Comment by richardsc** [comment]
As for the `oce` component of this, I agree that probably `as.section()` just shouldn't *ever* demand `waterDepth`, and either adds it based on max pressure (which I agree is probably the wrong thing to do, actually) or maybe should be treated as a larger behavioural change to remove the `waterDepth` components (from creating and plotting) for the next big release of `oce` (I don't see this as particularly major, and therefore requiring thinking about a new release).

As for the `argoFloats()` context, this is maybe worth a f2f discussion, because it relates to some of the original "phase 2" goals I outlined for the package, i.e. to be able to provide some analysis tools that use argo data in aggregate (rather than just single floats). For example, in the `argoFloats` context, I think that the concept of a "section" could be much more broad than that of `oce` (though would likely still use the mechanics of the `section-class`).

In my case, I wanted to make a section out of all the individual profiles from a single ID (see above example, but don't subset for the first 10 profiles), which is a common thing to do in `oce`. But in `argoFloats, we might want to make a section out of all the available *profiles*, regardless of ID. This is where I see something like `createSection()` being not just a wrapper to `as.section()` but actually providing *more* functionality. Imagine an "analysis" tab on the `mapApp()` that allows a user to click some points to define a section spine, and then be able to visualize a virtual transect along that line?

**Comment by dankelley** [comment]
I agree with this.  I've been fiddling a bit, and the oce part is complicated, of course.

Doing things in `argoFloats` makes sense.  I see you've opened an issue there, so I'll continue discussion there.

**Comment by dankelley** [comment]
@richardsc it seems to me that this issue can be closed, because
1. It's been over a month since there has been a comment.
2. This is being added to `argoFloats`.
3. We need to update oce on CRAN, and I think it makes sense to close long-open issues that are being ignored.

Therefore, I will close it tomorrow at 1200h Halifax time, barring a complaint.

**Comment by richardsc** [comment]
Yes, and this meandered a bit.

I'm going to close this, but open a *new* issue based on https://github.com/dankelley/oce/issues/1781#issuecomment-778765465, which is a proposal to make `as.section()` not worry about `waterDepth`.
