### ISSUE TITLE
Main vignette refers to obsolete ctdAddColumn()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1802]
Was just reading through the vignettes, and noticed the below reference to a deprecated function `ctdAddColumn()`:

![image](https://user-images.githubusercontent.com/233584/113491864-3fc29500-94aa-11eb-865b-76ffaa467442.png)

**Comment by dankelley** [comment]
Fixed in "develop".  I can't quite remember how to browse the vignette from within R.  (I know you do `browseVignettes()` but I think there is some kind of load operation that's required first.). In any case, the diff shows it: 7f1fc09785723005d23195c076e9b4462993e2cd.

I'm going to go ahead and close the issue, to save you some time, Clark.  Feel free to reopen it if I made a mistake.  If you're on the lookout for problems with vignettes, it might make sense to open an issue with a more general name, and a checklist of errors in the first comment.  Then we could add to the checklist (*within* that first comment) so that the progress on the checklist would be apparent in an index of the issues.

Thanks!

**Comment by richardsc** [comment]
I just sat down to fix this, after pulling, and got really confused because I couldn't grep `ctdAddColumn` anywhere in the vignette source. You're fast! 😄 Thanks!
