### ISSUE TITLE
Imagep() Section Plot Graphics

### ISSUE THREAD

**Issue by LiamMacNeil** [dankelley/oce#1803]
### Short summary of problem
This might be very simple. Following @richardsc blog post (Making section plots with oce and `imagep()`) for finer control of section plots, however, the graphics are distorted and the continuous legend is plotted onto each section.  It's not reproducible, but I can provide a sample of the data if it's a deeper problem or a bug. 

### Details (optional)

*Replace this line with a longer description, if the above seems insufficient.*

### What you did
```
#Gridded section for finer control
s <- sectionGrid(section, p='levitus')
nstation <- length(s[['station']])
p <- unique(s[['depth']])
np <- length(p)
T <- S <- array(NA, dim=c(nstation, np))
O <- S <- array(NA, dim=c(nstation, np))
F <- S <- array(NA, dim=c(nstation, np))
for (i in 1:nstation) {
  T[i, ] <- s[['station']][[i]][['temperature']]
  S[i, ] <- s[['station']][[i]][['salinity']]
  O[i, ] <- s[['station']][[i]][['oxygen']]
  F[i, ] <- s[['station']][[i]][['fluorescence']]
}
distance <- unique(s[['distance']])

#Graphical parameters
par(mfrow=c(2, 2))
par(oma=c(0.5,0.5,0.5,0.5))

#Specific color palettes
Tcm <- colormap(T, breaks=seq(2, 12, 1), col=oceColorsTemperature)
Scm <- colormap(S, breaks=seq(32, 36.8, 0.2), col=oceColorsSalinity)
Ocm <- colormap(O, breaks=seq(5, 8, 0.2), col=oceColorsOxygen)
Fcm <- colormap(F, breaks=seq(0, 6, 0.2), col=oceColorsChlorophyll)

#Plot composite figure
imagep(distance, p, T, colormap=Tcm, flipy=TRUE,
       ylab='Depth (m)', filledContour=TRUE,
       zlab='Temperature [degC]', ylim=c(5,200))
imagep(distance, p, S, colormap=Scm, flipy=TRUE,
        filledContour=TRUE,
       zlab='Salinity', ylim=c(5,200))
imagep(distance, p, O, colormap=Ocm, flipy=TRUE,
       xlab='Distance [km]', ylab='Depth (m)', filledContour=TRUE,
       zlab='Oxygen', ylim=c(5,200))
imagep(distance, p, F, colormap=Fcm, flipy=TRUE,
       xlab='Distance [km]', filledContour=TRUE,
       zlab='Fluorescence', ylim=c(5,200))*
```
### What you expected to happen
Plot separated from continuous scale bar (Taken from: Making section plots with oce and `imagep()`)

<img width="677" alt="Screen Shot 2021-04-07 at 11 37 31" src="https://user-images.githubusercontent.com/55404512/113884806-accd7780-9795-11eb-9828-62b867d0599e.png">

### What happened
However the scale bar is printed on the plot and fills the section background
<[Oce_plotissue.pdf](https://github.com/dankelley/oce/files/6272300/Oce_plotissue.pdf)>

### How urgent is this?
*Whenever you're able. It's appreciated.*

### Output from sessionInfo()
*R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] cmocean_0.3-1   forcats_0.5.1   stringr_1.4.0   dplyr_1.0.5     purrr_0.3.4    
 [6] readr_1.4.0     tidyr_1.1.3     tibble_3.1.0    ggplot2_3.3.3   tidyverse_1.3.0
[11] oce_1.3-0       sf_0.9-8        gsw_1.0-5       testthat_3.0.2 

loaded via a namespace (and not attached):
  [1] Rtsne_0.15          colorspace_2.0-0    ellipsis_0.3.1      class_7.3-18       
  [5] rprojroot_2.0.2     XVector_0.26.0      fs_1.5.0            rstudioapi_0.13    
  [9] remotes_2.2.0       fansi_0.4.2         lubridate_1.7.10    xml2_1.3.2         
 [13] codetools_0.2-18    splines_3.6.2       cachem_1.0.4        pkgload_1.2.0      
 [17] ade4_1.7-16         jsonlite_1.7.2      phyloseq_1.30.0     broom_0.7.5        
 [21] cluster_2.1.1       dbplyr_2.1.0        BiocManager_1.30.10 compiler_3.6.2     
 [25] httr_1.4.2          backports_1.2.1     assertthat_0.2.1    Matrix_1.3-2       
 [29] fastmap_1.1.0       cli_2.3.1           prettyunits_1.1.1   tools_3.6.2        
 [33] igraph_1.2.6        gtable_0.3.0        glue_1.4.2          reshape2_1.4.4     
 [37] tinytex_0.30        Rcpp_1.0.6          Biobase_2.46.0      cellranger_1.1.0   
 [41] vctrs_0.3.7         Biostrings_2.54.0   multtest_2.42.0     ape_5.4-1          
 [45] nlme_3.1-152        iterators_1.0.13    xfun_0.21           ps_1.6.0           
 [49] rvest_0.3.6         lifecycle_1.0.0     devtools_2.3.2      zlibbioc_1.32.0    
 [53] MASS_7.3-53.1       scales_1.1.1        hms_1.0.0           parallel_3.6.2     
 [57] biomformat_1.14.0   rhdf5_2.30.1        yaml_2.2.1          memoise_2.0.0      
 [61] stringi_1.5.3       S4Vectors_0.24.4    desc_1.3.0          foreach_1.5.1      
 [65] e1071_1.7-4         permute_0.9-5       BiocGenerics_0.32.0 pkgbuild_1.2.0     
 [69] rlang_0.4.10        pkgconfig_2.0.3     lattice_0.20-41     Rhdf5lib_1.8.0     
 [73] cowplot_1.1.1       processx_3.4.5      tidyselect_1.1.0    plyr_1.8.6         
 [77] magrittr_2.0.1      R6_2.5.0            IRanges_2.20.2      generics_0.1.0     
 [81] DBI_1.1.1           pillar_1.5.1        haven_2.3.1         withr_2.4.1        
 [85] mgcv_1.8-34         units_0.6-7         survival_3.2-7      modelr_0.1.8       
 [89] crayon_1.4.1        KernSmooth_2.23-18  utf8_1.2.1          microbiome_1.8.0   
 [93] progress_1.2.2      usethis_2.0.1       grid_3.6.2          readxl_1.3.1       
 [97] data.table_1.14.0   propr_4.2.6         callr_3.5.1         vegan_2.5-7        
[101] reprex_1.0.0        classInt_0.4-3      stats4_3.6.2        munsell_0.5.0      
[105] sessioninfo_1.1.1 *

**Comment by dankelley** [comment]
Did you run it interactively or noninteractively?

There are known problems in interactive use, if the window is resized.  I've never seen an overplot when run as a script, i.e. when run noninteractively.  Perhaps if you can try that and it still fails, you could email me data at dan.kelley@dal.ca?

NOTE: this is not likely to be a problem with the creation of the section.  It's an `imagep()` problem, if it's a problem.  Therefore, if you don't have success non-interactively, and want to try to make a reprex, you might want to work with the 'volcano' dataset.  Here's what I get in a simple reprex (click the link to expand).

<details>

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
par(mfrow=c(2,2))
imagep(volcano)
imagep(volcano)
imagep(volcano)
imagep(volcano)
```

![](https://i.imgur.com/aXNOT7X.png)

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment]
Hi @LiamMacNeil -- thanks for using oce and for the issue report.

I tried running your code above, but got an error:
```
Error in F[i, ] <- s[["station"]][[i]][["fluorescence"]] : 
  number of items to replace is not a multiple of replacement length
```

To check, I reran the Rmd source for my [blog post](https://www.clarkrichards.org/2016/04/25/making-section-plots-with-oce-and-imagep/) and it does seem to work. As indicated above, I traced the error to the fact that in your example code you reference a `fluorescence` field that doesn't actually exist in the `section` dataset (presumably it does exist in your data?). Anyway, I changed that to `phosphate` so that things would work, and that produces as below:

![image](https://user-images.githubusercontent.com/233584/113892484-69c2d280-979c-11eb-91c0-78c299bf7476.png)

Which I think looks as you'd expect.

That being said, I *am* familiar with the "scale bar ends up behind the plot" phenomenon, and I'm pretty sure it results from window resizing. For example, if I take the plot window that I just made above, and stretch it a little, I get:

![image](https://user-images.githubusercontent.com/233584/113892959-eeadec00-979c-11eb-92a8-c2ce2393cff8.png)

**Comment by richardsc** [comment]
@dankelley and I posting at the same time, haha.

Dan is write about interactive vs non-interactive. If you use the `pdf()`, `png()` etc functions to save your plot to a file, and control the size of it through the device arguments, you shouldn't have an issue.

Another suggestion I'd make is that for `imagep()` plots saved with a pdf device there is often ghosty lines between the colors and grids. This is an artifact of the pdf antialiasing, so I recommend for such plots you save as a high res png, e.g.
```
png('plot.png', width=7, height=7, units='in', res=300)
```
where I specified a width and height of 7 inches, but with a display resolution of 300 dpi.

**Comment by LiamMacNeil** [comment]
@dankelley @richardsc Thank you both for the fast and detailed responses. I was running interactively, but the ```png()``` save function did the trick. the png over pdf did provide a higher quality graphic. This works great!

**Comment by dankelley** [comment]
Hi Liam, another hint -- it might already have been said but anyway, I'll repeat it -- is to write e.g.
```R
if (!interactive())
    png('plot.png', width=7, height=7, units='in', res=300)
# plot stuff here
if (!interactive())
    dev.off()
```
in your code. That way, if you run it interactively, it plots to the screen, but if run as a script, it creates the .png file.  I do that all the time.  (I think Clark wrote a macro, to put both steps into one.)

Another hint, which I suspect you're familiar with, is to find a comfortable balance between writing in the console and writing in a script.  I tend to play around in the console, but copy things line by line into a script.  And I often do `rm(list=ls())` in the console (Rstudio has a button that does similar) to clear it, and then run the script again, to be sure the script is complete.  Another hint is that I resize the plot device to math the geometry of my png, and play around that way, so that my final product, the png or pdf, will be suitable.  I also decide on a plot geometry (say, ratio of device width to pointsize) that will work with the journal or report I'm aiming for, and then stick with it.  (For a two-column journal, you'll want to pay attention to whether a particular figure is to be a column wide or two columns wide ... be sure to alter `width` as appropriate but not to alter `pointsize`, because otherwise the figure will look weird compared with the rest).  Sometimes the publisher decides to typeset otherwise, but usually you'll be okay (e.g. in my book [1] they mostly did as I had designed, but in some cases they didn't, and so the font size looks wonky!)

Likely, you already know these things, but I thought it might not hurt to repeat them.

Dan.

**References.**

1. Kelley, Dan E. Oceanographic Analysis with R. New York: Springer-Verlag, 2018. https://www.springer.com/us/book/9781493988426.
