### ISSUE TITLE
Is there an argument to plot a section of oxygen (or other parameters)

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1813]
Hi All,

I'm currently working with CTD data. I'm interested in plotting different parameters (ie. not only temperature and salinity). I can easily go into the source code and reproduce the code that is being used to plot salinity or temperature, but before I do that, I was wondering if there is an argument (ie. something like plot(section, which="oxygen")?

Thanks!

**Comment by dankelley** [comment]
You cannot plot a section with just a single CTD station, but you can do e.g. `plotProfile(ctd1, xtype="oxygen")` with one.  You can build up ctd objects into a section with `as.section()`, and once you have that, you can do e.g. `plot(sec, which="oxygen")`.  I think I have those right.  Check e.g.
```R
?'plot,ctd-method'
?'plot,section-method'
```
for details.  Or we can Z if you are looking for quick results (we could also talk about my JOSS edits if you want).

**Comment by j-harbin** [comment]
Oh amazing! I just found the help page for plotting sections. It's very detailed and arguably should have been my first stop. I'll blame that on it being Friday.

I'll reach out via email to set up a Z time to talk about "argo" stuff. Thanks :)

**Comment by dankelley** [comment]
Also, FYI, you can see help at e.g. https://dankelley.github.io/oce/reference/plot-ctd-method.html, and the advantage of looking there is that it contains figures.  (They are not all as nice as you get in R, though, because of some odd thing where I think it plots them and then resizes the plot device, which does not work well for plots with colour palettes or for maps, either.)
