### ISSUE TITLE
Issues reading SonTek Micro ADV from a flume experiment

### ISSUE THREAD

**Issue by marecotec** [dankelley/oce#1829]
### Short summary of problem

We are having issues reading binary files into oce from Sontek Micro ADV (a rather old one, here's the [specs](https://www.xylem-analytics.asia/productsdetail.php?SonTek-10-MHz-ADV-69)) that is being used within flume experiments as part of our work on deep-sea corals. In summary, we can't get them into an ADV object for analysis.

We have 3 files exported from the Sontek software:
*.ADV
*.sdr
*.sds

Example files from one of our flume tests can be downloaded:
https://github.com/marecotec/ExampleSontek

### How urgent is this?

This is not urgent, grad students are exploring conversions to readable text on the original software, but we would love to use oce from the outset and work with our raw data files as we do for all our other sensors.

### Output from sessionInfo()

R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

oce_1.4-0

### Reproducible Example
library(oce)
read.adv("DEFAULT0005.ADV", type = c("sontek"), start=as.POSIXct("2020-01-01 00:00:00", tz="UTC"), deltat = 0.2, debug=TRUE)

Our errors are coming up with:
no compass, define coordinate system (but no options in docs as how to set manually).

Thanks everyone for great software, it is really being picked up in the biological oceanography community.
Andy Davies

**Comment by richardsc** [comment]
Ok, a little refresher on how to call (my own) functions, and I get as you did with the compass issue. The block causing the stop is here:
```
        res@metadata$compassInstalled <- as.integer(hardwareConfiguration[5]) == 1
        oceDebug(debug, "compassInstalled=", res@metadata$compassInstalled, "\n")
        if (!res@metadata$compassInstalled)
            stop("cannot handle data files for ADV files that lack compass data")
```

Not sure *why* we made it mandatory to have a compass, but it might be possible to make this stage a conditional requirement ...

**Comment by marecotec** [comment]
Thanks Clark, I'll reach out to Sontek to see if they have the data format description. 

My guess for the stop is accurate directionality, and I guess the instrument you used to build the function was a field deployable instrument, flumes are likely a limited user case, but we have very accurate positioning abilities in the lab, expecially in the rotational axis of the ADV head. So I'd be happy to set a compass constant value based on our positional info.

**Comment by richardsc** [comment]
Yes, I think we're going to need a file format description. Just modifying the source to ignore the missing fields gets us past that, but then I get as below:
```r
d <- read.adv('DEFAULT0005.ADV', type='sontek.adr', debug=10)
read.adv.sontek.adr() {
  filesize= 167214
  cpuSoftwareVerNum= 6.5
  dspSoftwareVerNum= 6.8
  orientation= NA
  compassInstalled= FALSE
  recorderInstalled= FALSE
  thermometerInstalled= FALSE
  pressureInstalled= FALSE
  pressureScale= 0.8408471 dbar/count (header gives in nanobar/count)
  pressureOffset= 7885.325 dbar (header gives in microbar)
  compassOffset= 257 (degrees to East of North)
  pressFreqOffset= 0 ("Frequency Pres Sensor Offset" in docs)
  extSensorInstalled= 0 ("0=None, 1=Standard (ch 1/3)" in docs)
  extPressInstalled= 0 (1=Paros 2=Druck 3=ParosFreq)
  pressureScale2= 0 dbar/count^2 (file gives in picobar/count^2)
  serialNumber= A
  probeType= 0 ("3/2-d orientation", according to the docs)
  probeSize= 0 (0 means 5cm; 1 means 10cm probe, according to docs)
  numberOfBeams= 13107 (should be 3)
  probeNomPeakPos= 17593 (not used here)
  probeNsamp= 0 (not used here)
  probeSampInterval= 16840 (not used here)
  probePulseLag= 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 ([5][3], not used here)
  probeNxmit= 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ([5][3], not used here)
  probeLagDelay= 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ([5][3], not used here)
  probeBeamDelay= 0 (not used here)
  probePingDelay= 0 (not used here)
  transformation matrix:
              0          0          0
              0          0          0
              0          0          0
Error in read.adv.sontek.adr(file = file, from = from, to = to, by = by,  :
  first byte of deploymentParameters header should be 0x12 but it is 0x00
In addition: Warning message:
In read.adv.sontek.adr(file = file, from = from, to = to, by = by,  :
  number of beams should be 3, but it is 13107 ... reseting to 3
```

So you can see that we're not getting the right header bytes, nor the correct number of beams ... (I doubt your ADV has 13107 beams ... 😄 )

**Comment by richardsc** [comment]
I was just about to say the same as @dankelley about getting the text files from the software, so we can compare. But also because I just realized that there is a `type="sontek.text"` option, which might work (unlikely, but worth a shot).

**Comment by richardsc** [comment]
The manual that the existing code is based on can be found here:
https://usermanual.wiki/Pdf/ADVFieldManualv790.1715978035.pdf

And here is a screenshot of the kind of thing that we need to see for this instrument:
![Uploading image.png…]()

**Comment by marecotec** [comment]
Thanks both, I've asked my grad student to get us a text version of the 005 file, and I've reached out to Xylem/Sontek to see if we can get a description of the file. Much appreciated as ever.

**Comment by dankelley** [comment]
Thanks. That manual they gave (the PDF doc) is identical to one that we have already, so the good news is that things haven't changed in several years.  But oce will still tweaking to read your data, it seems.

PS. it's nice that sontek gives C code to read the headers, but it makes assumptions about the machine.  The RDI docs are nicer because they will e.g. say that there are 4 bytes for an entry, that it codes for an unsigned integer, and that little-endian notation is used.  Sontek assumes (I think) that people are working with a particular compiler on a particular machine.  I think it's a good guess that their `float` and `int` are 32-bit entries, and that they are using little-endian, but we need to be specific in R, so that the code will work even on big-endian machines (they still exist) and on 64-bit machines, etc.  Still, sontek doesn't seem to cram things in bitwise, as other manufacturers do, so that relieves us from having to look at one particular byte from left to right or from right to left.  The joy of binary formats :-)

**Comment by dankelley** [comment]
*This is a saved, standardized reply.*

The "stale" bot seems not to be working.  If it had been working, this issue would have been auto-closed long ago, since discussion had ceased and the staleBot had issued a warning of upcoming closure.  

I will look into why the bot is failing to do as advertised, but in the meantime I am manually closing this issue.  Of course, the reporter should feel free to reopen the issue, if desired.  If so, please write a comment to bring the developers up-to-speed on the state of affairs, to help them to see whether there is a solution.
