### ISSUE TITLE
PWELCH Issue?

### ISSUE THREAD

**Issue by HolgerF22** [dankelley/oce#1839]
### Short summary of problem
Giving parameters to the command line, I found that there seems to be an inconsistency with what is reported with "debug" on:

Example:
nw=8192  # xts is a time-series
psdoce= oce::pwelch(xts,window=hanning(nw),nfft=nw, fs=100,debug=1);

produces
 pwelch(x, window=1.47104470882287e-07, nfft=8192, fs=(not given), noverlap=100, ...) {
 pwelch(x, window=0, nfft=8192, fs=(not given), noverlap=100, ...) {
        window.len= 8192   step= 4097   noverlap= 4096   x.len= 262144

using noverlap, the value is associated with fs. Changing the order of arguments doesn't help either.

Additionally, there is an issue with detrend, in that low frequencies in simple test cases increase drastically. 
Using detrend=F oftentimes gives large values for the PSD at f=0, no matter how the data looks like or what window is used. Doesn't happen when calculating the PSD via FFT directly or using similar code in Octave or Matlab, pwelch behaves differently here.

##
Not very urgent.

### Output from sessionInfo()

R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin19.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/r/4.1.0/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] rsleep_1.0.3      seewave_2.1.6     infrasonic2_0.2.5
[4] serial_3.0        oce_1.5-0         sf_1.0-0         
[7] gsw_1.0-5         testthat_3.0.3    signal_0.7-7     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         magrittr_2.0.1     units_0.7-2       
 [4] MASS_7.3-54        R6_2.5.0           rlang_0.4.11      
 [7] tcltk_4.1.0        tools_4.1.0        grid_4.1.0        
[10] KernSmooth_2.23-20 e1071_1.7-7        DBI_1.1.1         
[13] remotes_2.4.0      class_7.3-19       tuneR_1.3.3       
[16] phonTools_0.2-2.1  proxy_0.4-26       compiler_4.1.0    
[19] classInt_0.4-3 

### Reproducible Example

If it is possible, please use the `reprex()` function from the `reprex` package
to provide a reproducible example. If you need non-private files that you
cannot upload to GitHub, please put them on a shared site and use
`download.file()` in your code, to save the developers the effort of
downloading the files. If you have private files, please send them to the `oce`
developers.

Whether you use `reprex()` or not, it can help greatly to use the `stopifnot()`
function to demonstrate incorrect values, if that is part of the problem you've
encountered.

**Comment by dankelley** [comment]
Thanks for the report!

I'll take a look.  Regarding how the similarly-named function works in matlab and octave, the oce version is known not to be a precise analogue.

**Comment by richardsc** [comment]
Just tagging #1359 here in case it's related (it was opened, but closed by the stale bot).

**Comment by dankelley** [comment]
(Please note that this is a standardized reply.)

Could you please supply a self-contained example that illustrates your bug, using faked data or a data snippet that you provide as a github attachment or over email?  This should speed things up, by letting us focus on a solution, saving time we would otherwise need to spend locating or creating a relevant dataset, and then writing code that will let us recreate your difficulty.

Another benefit, if you can be clear enough on the expected behaviour, is that it will reduce the need for us to ask you for more details.  (Consider using the `stopifnot()` or perhaps functions from the `testthat` package to indicate clearly what you expect to see.)

*Hint:* Making a reproducible example is easy, with the `reprex` package.  Just write some code that will cause a problem, and copy it to your computer's clipboard.  Then, in Rstudio, type `reprex::reprex()` and it will run that code and then put the results (including links to graphs) on the clipboard.  Then, you can paste that result into the text box in a comment here.

Thanks!

**Comment by HolgerF22** [comment]
Ok:

library(infrasonic2)
library(seewave)
library(oce)

l=50000
#sampling freq
f_s=250
t=((1:l)/f_s - 1/f_s)
#noise
noise    = rnorm(l,mean = 0, sd = 1)
noisevar = 0.1

par(mfrow=c(1,1))
par(cex=0.5)
A1= 0.5*sqrt(2)
A2= 1.0*sqrt(2)
A3= 1.25*sqrt(2)

s = A1*cos(2*pi*t*2) + A2*cos(2*pi*t*5) + A3*cos(2*pi*8*t) + sqrt(noisevar)*noise

#Time series
xts = ts(s/20e-6,start=0,frequency=f_s)

nf = 8192

psd = oce::pwelch(xts,window=hanning(nf),nfft=nf,fs=f_s,debug=1,detrend='false');

plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1)

-------------

In output I get:
pwelch(x, window=1.47104470882287e-07, nfft=8192, fs=(not given), noverlap=250, ...) {

Could be the debug output is wrong and internally everything is calculated correctly.

**Comment by dankelley** [comment]
Sorry to be a pain, but could you use `reprex::reprex()`?  Also, please remove things not required to show the bug (e.g. the first two `library()` calls).  

I tried removing those first two library calls, and the code does not run because `hanning` is not a known function.  My guess is that it is defined within those other two libraries.  And, I don't know what it is returning.  The documentation from `?pwelch` tells you what is allowed for the `window` argument.

The advantage of your using `reprex::reprex()` is that we don't have to keep going back and forth with questions.  Quite a lot of oce users are in far-flung timezones, and often each question/answer pair takes a day or more.

**Comment by HolgerF22** [comment]
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.1, GDAL 3.3.0, PROJ 7.2.1
    l=50000
    f_s=250
    t=((1:l)/f_s - 1/f_s)
    
    noise    = rnorm(l,mean = 0, sd = 1)
    noisevar = 0.1
    
    A1= 0.5*sqrt(2)
    A2= 1.0*sqrt(2)
    A3= 1.25*sqrt(2)
    
    s = A1*cos(2*pi*t*2) + A2*cos(2*pi*t*5) + A3*cos(2*pi*8*t) + sqrt(noisevar)*noise
    
    
    xts = ts(s/20e-6,start=0,frequency=f_s)
    
    nf = 8192
    
    psd = oce::pwelch(xts,nfft=nf,fs=f_s,debug=1,detrend='false')
#>       pwelch(x, window=(not given), nfft=8192, fs=(not given), noverlap=250, ...) {
#>         window.len= 8192   step= 4097   noverlap= 4096   x.len= 50000 
#>           calculating subspectrum at indices  1 to 8192 
#>           calculating subspectrum at indices  4098 to 12289 
#>           calculating subspectrum at indices  8195 to 16386 
#>           calculating subspectrum at indices  12292 to 20483 
#>           calculating subspectrum at indices  16389 to 24580 
#>           calculating subspectrum at indices  20486 to 28677 
#>           calculating subspectrum at indices  24583 to 32774 
#>           calculating subspectrum at indices  28680 to 36871 
#>           calculating subspectrum at indices  32777 to 40968 
#>           calculating subspectrum at indices  36874 to 45065 
#>           calculating subspectrum at indices  40971 to 49162 
#>         resultant spectrum is average across matrix of dimension 11 4096 
#>       } # pwelch()
#> Warning in plot.window(...): "detrend" is not a graphical parameter
#> Warning in plot.xy(xy, type, ...): "detrend" is not a graphical parameter
#> Warning in axis(side = side, at = at, labels = labels, ...): "detrend" is not a
#> graphical parameter

#> Warning in axis(side = side, at = at, labels = labels, ...): "detrend" is not a
#> graphical parameter
#> Warning in box(...): "detrend" is not a graphical parameter
#> Warning in title(...): "detrend" is not a graphical parameter


    
    plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1)


Created on 2021-06-25 by the reprex package (v2.0.0)

 Standard output and standard error
Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter
2: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter
3: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter
4: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter
5: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter
6: In doTryCatch(return(expr), name, parentenv, handler) :
  "detrend" is not a graphical parameter

**Comment by dankelley** [comment]
I don't quite know what you did with `reprex::reprex()` so I edited your comment above to try to make it easier to read.  (I know I did not fix it up entirely, though.). In any case, please note that at the bottom of the present comment (click on the Details word) you will see a reprex that I created. 

Note, in my test (a) I have set a seed so the example should reproduce exactly, (b) you can see the plot (since I followed the scheme I explained for reprex work) and (c) I have dropped the `detrend` argument you supplied.  

The handling of a `detrend` argument is not explained in the docs for `?pwelch`, and so this ought not to be part of our discussion here.  I can see, by looking in the `pwelch` code, that I was working to permit the user to specify a `detrend` but that I had not completed that work.  At the moment, `pwelch()` does as documented: it calls `oce::detrend()` on the time-series portions.  (I think the docs for `?pwelch` are not sufficiently clear on how this works, and maybe that explains why you thought that it could be a character string.)

OK, so that's my explanation of my reprex.  I would like to encourage you to give a similar level of detail.  Let's now return to your question.  In terms of the reprex that I provide within this comment, or in terms of a new reprex from you (but *please* do make it an actual reprex), what is the difficulty?  Please make a precise statement, because I won't see any reply for a day and this could go on for over a week at this rate.

<details>
---
author: kelley
date: 2021-06-25
output: "reprex::reprex\\_document"
title: ash-crane\_reprex.R
---

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
    l=50000
    f_s=250
    t=((1:l)/f_s - 1/f_s)
    

    set.seed(1839)
    noise    = rnorm(l,mean = 0, sd = 1)
    noisevar = 0.1
    
    A1= 0.5*sqrt(2)
    A2= 1.0*sqrt(2)
    A3= 1.25*sqrt(2)
    
    s = A1*cos(2*pi*t*2) + A2*cos(2*pi*t*5) + A3*cos(2*pi*8*t) + sqrt(noisevar)*noise
    
    
    xts = ts(s/20e-6,start=0,frequency=f_s)
    
    nf = 8192
    
    #psd = oce::pwelch(xts,nfft=nf,fs=f_s,debug=1,detrend='false')
    psd = oce::pwelch(xts,nfft=nf,fs=f_s,debug=1,plot=FALSE)
#>       pwelch(x, window=(not given), nfft=8192, fs=(not given), noverlap=250, ...) {
#>         window.len= 8192   step= 4097   noverlap= 4096   x.len= 50000 
#>           calculating subspectrum at indices  1 to 8192 
#>           calculating subspectrum at indices  4098 to 12289 
#>           calculating subspectrum at indices  8195 to 16386 
#>           calculating subspectrum at indices  12292 to 20483 
#>           calculating subspectrum at indices  16389 to 24580 
#>           calculating subspectrum at indices  20486 to 28677 
#>           calculating subspectrum at indices  24583 to 32774 
#>           calculating subspectrum at indices  28680 to 36871 
#>           calculating subspectrum at indices  32777 to 40968 
#>           calculating subspectrum at indices  36874 to 45065 
#>           calculating subspectrum at indices  40971 to 49162 
#>         resultant spectrum is average across matrix of dimension 11 4096 
#>       } # pwelch()

    
    plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1)
```

![](https://i.imgur.com/JItbacM.png)

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by richardsc** [comment]
WRT to the `detrend=` argument, I'm also a bit confused. I see in the `?pwelch` there is a mention of it in the `...` arg:

```
...: optional extra arguments to be passed to ‘spectrum()’. Unless
          specified in this list, ‘spectrum()’ is called with
          ‘plot=FALSE’ to prevent plotting the separate spectra, and
          with ‘taper=0’, which is not needed with the default Hanning
          window.  However, the other defaults of ‘spectrum()’ are
          used, e.g. ‘detrend=TRUE’.
```

If you look at `?spec.pgram` (which is what `spectrum()` calls) you'll find:

```
detrend: logical. If ‘TRUE’, remove a linear trend from the series.
          This will also remove the mean.
```

So, it is at least clear that the `detrend=` arg cannot be a character, but must be logical, e.g. `detrend=FALSE`.

**Comment by dankelley** [comment]
Yes, the docs are unclear.  I want to clean them up, and also to work on other `pwelch()` improvements, but my first goal is to find out what @HolgerF22 needs for their work.

I see in the code that `detrend()` is called on each sub-segment.  And, no `detrend` arg is supplied  to the `spectrum()` call.  So, definitely, we have a bug (meaning a contradiction between what the `?pwelch` docs say and what `pwelch` actually does).  I will fix that and likely do other things to improve `pwelch` over the weekend.  Hopefully we'll also have a clearer statement from @HolgerF22 so that the changes I make can also be useful in that instance.

PS. my guess on the low-freq peak in the spectrum is that the signal is quite noisy.  The `oce::detrend()` function simply draws a line from the first point to the last point, and removes that trend.  I could see that as being problematic for cases with lots of noise, though.  I think `spectrum()` does a similar thing.  I'll be experimenting with all of this on the weekend.

**Comment by HolgerF22** [comment]
The thing is easy to see, clear from your repex: 

In my call to pwelch the sampling frequency fs (set to 250) and number of points for the Fourier transform, nfft, are provided. But if you look at the debug output, the given values are associated with other variables. The output shows     

fs=(not given), noverlap=250

So internally there seems to be a wrong variable association.

**Comment by dankelley** [comment]
FYI, this is what I get for this example, if I go into the `oce::pwelch()` code and remove the `detrend()` call, and this suggests that I ought to update the function to let the user have more control over this argument.

<img width="793" alt="Screen Shot 2021-06-25 at 4 50 14 PM" src="https://user-images.githubusercontent.com/99469/123478208-85888880-d5d5-11eb-8b0d-7312d557ee6f.png">

**Comment by HolgerF22** [comment]
Yes, that would be fine. Detrend should not be necessary, here. The mean of my function is zero ( the noise has zero mean, cosine or sine have zero mean) and the data are windowed (if I do nothing the Hamming window is used, I prefer Blackman-Harris or Hanning. You can provide that in pwelch easily). I don't get the high frequency values around f=0 in octave, matlab or in python, irrespective of using a detrend setting there or not and using different windows. But more freedom is always great.

**Comment by dankelley** [comment]
Thanks, @HolgerF22: now I understand your statement.  I think I need to wait until tomorrow to see the problem in the code because it looks ok to me!  My eyes are tired.  (@richardsc knows that I've been looking at a screen for 12 hours at this stage.)

I see https://github.com/dankelley/oce/blob/466770b9fefa6a2e125ebcea02d6a389b81989b7/R/spectral.R#L83
where `fs` gets handed to the function as the 5th arg.  Then, at  https://github.com/dankelley/oce/blob/466770b9fefa6a2e125ebcea02d6a389b81989b7/R/spectral.R#L118
I see whether the user gave `fs`.  And then, at https://github.com/dankelley/oce/blob/466770b9fefa6a2e125ebcea02d6a389b81989b7/R/spectral.R#L124
I print out the value, if provided, or "(missing)" if not.  For the life of me, I don't see why this is not working.  As I say, though, my eyes will be fresh tomorrow.

Thanks for your patience, @HolgerF22, and I imagine `oce::pwelch()` will not just solve your bug, but also have better possibilities, when I edit it tomorrow.  Note that you can supply the `window` argument as a vector defining a filter.  If you just give it as an integer, a hamming window is created for you, in https://github.com/dankelley/oce/blob/466770b9fefa6a2e125ebcea02d6a389b81989b7/R/spectral.R#L146

**Comment by HolgerF22** [comment]
Thanks, no problem. I looked at it, too and didn't see the issue immediately, either. thanks for taking the time to look at it.
I like the functionality and want to provide my master students not only python but also R code. Additionally, oce looks great to be used in our aeroacoustics research, too.

**Comment by dankelley** [comment]
FYI, this is how the spectra will look tomorrow.  The code is not pushed to GH yet.  I will be updating the arg list and thinking a bit more (maybe adding an example) about how users can gain more control,

But, basically, the results are a *lot* better without my call to `oce::detrend()`.

Oh, and I figured out that weird problem in not getting the right debugging output.

---
author: kelley
date: 2021-06-25
output: "reprex::reprex\\_document"
title: white-boto\_reprex.R
---

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
    l=50000
    f_s=250
    t=((1:l)/f_s - 1/f_s)

    set.seed(1839)
    noise    = rnorm(l,mean = 0, sd = 1)
    noisevar = 0.1

    A1= 0.5*sqrt(2)
    A2= 1.0*sqrt(2)
    A3= 1.25*sqrt(2)

    s = A1*cos(2*pi*t*2) + A2*cos(2*pi*t*5) + A3*cos(2*pi*8*t) + sqrt(noisevar)*noise

    xts = ts(s/20e-6,start=0,frequency=f_s)

    nf = 8192

    #psd = oce::pwelch(xts,nfft=nf,fs=f_s,debug=1,detrend='false')
    par(mfrow=c(3,1), mar=c(3,3,1,1), mgp=c(2,0.7,0))
    psd = pwelch(xts,nfft=nf,fs=f_s,plot=FALSE,debug=1)
#> [1m      pwelch(x, nfft=8192,fs=250,...) {
#> [0m        using window.len=8192  step=4097  noverlap=4096  x.len=50000
#>           calculating subspectrum at indices  1 to 8192 
#>           calculating subspectrum at indices  4098 to 12289 
#>           calculating subspectrum at indices  8195 to 16386 
#>           calculating subspectrum at indices  12292 to 20483 
#>           calculating subspectrum at indices  16389 to 24580 
#>           calculating subspectrum at indices  20486 to 28677 
#>           calculating subspectrum at indices  24583 to 32774 
#>           calculating subspectrum at indices  28680 to 36871 
#>           calculating subspectrum at indices  32777 to 40968 
#>           calculating subspectrum at indices  36874 to 45065 
#>           calculating subspectrum at indices  40971 to 49162 
#>         resultant spectrum is averaged across a matrix of dimension 11x4096 
#> [1m      } # pwelch()
#> [0m
    plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1, xlab="Freq", ylab="log10(spectrum)")
    mtext("detrend not supplied (defaults to FALSE)", cex=par("cex"))
    psd = pwelch(xts,nfft=nf,fs=f_s,plot=FALSE,detrend=FALSE,debug=1)
#> [1m      pwelch(x, nfft=8192,fs=250,...) {
#> [0m        using window.len=8192  step=4097  noverlap=4096  x.len=50000
#>           calculating subspectrum at indices  1 to 8192 
#>           calculating subspectrum at indices  4098 to 12289 
#>           calculating subspectrum at indices  8195 to 16386 
#>           calculating subspectrum at indices  12292 to 20483 
#>           calculating subspectrum at indices  16389 to 24580 
#>           calculating subspectrum at indices  20486 to 28677 
#>           calculating subspectrum at indices  24583 to 32774 
#>           calculating subspectrum at indices  28680 to 36871 
#>           calculating subspectrum at indices  32777 to 40968 
#>           calculating subspectrum at indices  36874 to 45065 
#>           calculating subspectrum at indices  40971 to 49162 
#>         resultant spectrum is averaged across a matrix of dimension 11x4096 
#> [1m      } # pwelch()
#> [0m
    plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1, xlab="Freq", ylab="log10(spectrum)")
    mtext("detrend=FALSE", cex=par("cex"))
    psd = pwelch(xts,nfft=nf,fs=f_s,plot=FALSE,detrend=TRUE,debug=1)
#> [1m      pwelch(x, nfft=8192,fs=250,...) {
#> [0m        using window.len=8192  step=4097  noverlap=4096  x.len=50000
#>           calculating subspectrum at indices  1 to 8192 
#>           calculating subspectrum at indices  4098 to 12289 
#>           calculating subspectrum at indices  8195 to 16386 
#>           calculating subspectrum at indices  12292 to 20483 
#>           calculating subspectrum at indices  16389 to 24580 
#>           calculating subspectrum at indices  20486 to 28677 
#>           calculating subspectrum at indices  24583 to 32774 
#>           calculating subspectrum at indices  28680 to 36871 
#>           calculating subspectrum at indices  32777 to 40968 
#>           calculating subspectrum at indices  36874 to 45065 
#>           calculating subspectrum at indices  40971 to 49162 
#>         resultant spectrum is averaged across a matrix of dimension 11x4096 
#> [1m      } # pwelch()
#> [0m
    plot(psd$freq,10*log10(psd$spec),type='l',log='x',xlim = c(0.01,f_s/2),ylim=c(50,120),lty=1, xlab="Freq", ylab="log10(spectrum)")
    mtext("detrend=TRUE", cex=par("cex"))
```

![](https://i.imgur.com/FepLqwv.png)

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Question for @HolgerF22: is it OK to name you (with your github name, or perhaps your real name) in the help for `pwelch()`?  At the moment, I mention you in the last sentence of a new section of the help.

If you prefer to remain anonymous, I'll drop the last sentence. 

Note that `oce` is not committed to github yet.  I hope to commit it today or tomorrow, since I am getting close to what I consider to be a solution, or at least something worth testing.  Part of this is that I am going through the docs to try to make them clearer. 

There is a new `spec` argument that will help users who want to exert fine-grained control over the actual spectral computation.  As I'm sure you know, R has two main functions for doing such computations, `spec.pgram` and `spec.ar`, and `spectrum` does it work by calling one or the other.

Please notice that the writing is just a first draft.  I am also working on clearer explanations of the complex interactions between the `window`, `nfft`, etc. arguments.  I had tried to mimic the Matlab arguments, and I think that was a mistake.  During the work, I also removed two named argument that were documented as being ignored; they were matlab things but now is the time to just be clear that this is *not* intended as a drop-in replacement.  R is just different from matlab (quite prominently in its spectral analysis, e.g. the `spans` argument) and it is good to draw a line between the two languages.  (Controlling `spans` is one of the reasons why power users might want to supply their own spectral computation function.)

<img width="569" alt="Screen Shot 2021-06-26 at 9 26 14 AM" src="https://user-images.githubusercontent.com/99469/123512936-9205f300-d660-11eb-849e-dd47cbc1e96e.png">

**Comment by HolgerF22** [comment]
Hi, yes of course. You can use my real name, too (Holger Foysi, University of Siegen).

**Comment by dankelley** [comment]
Thanks.  I'll add this info.

**Comment by dankelley** [comment]
**Summary.** 

I have altered `pwelch()` fairly significantly in the "main" branch, commit a93dd9d294bb308120c03c65107b6a9958129037.

I hope @HolgerF22 and perhaps @richardsc will be able to do some tests with this, perhaps starting with the code discussed below under "Test case" (which is a variant of code that @HolgerF22 generously provided).

**Overview.** 

The main changes are that
1. The debug output is more correct.
2. The spectrum seems more accurate at low frequencies.  The code change is that s the time-series chunks are no longer passed through `detrend()`.  I think the problem was that `detrend()` computes the trend by a simple difference from start to end, and that is a non-robust estimate of trend.
3. We now have formal parameters named `demean` and `detrend`, which get passed to `spectrum()`.  This makes more sense than doing this in `pwelch()` itself.
4. `pwelch()` now has a parameter named `spec`, which is aimed at power users who want to exert fine-grained control over the spectral part of the work.

I have more details of these and other changes in the docs given by `?pwelch`; see in particular the "History" section.

The code also has some more checks on how parameters are specified together.  This sort of thing is often a failure point, because the code has to be complex, to handle all the circumstances.  (For example, `nfft` and `window` can interact, and we have to check on that.  And we need to know whether `x` is a `ts` object, so we can see whether `fs` is consistent. There are lots of these things to check.)

**Test case.**

At https://github.com/dankelley/oce-issues/blob/main/18xx/1839/1839a.R there is a test code that shows the improved behaviour at low frequencies.  Below are the result for the old `oce` (the version on CRAN, or the version on github as of yesterday) and for the update (the one at the commit stated at the top of this comment).  I think this demonstrates that the low-frequency behaviour is better now.  I thank @HolgerF22 for pointing out that this part of the spectrum was questionable.

*Old results*

![1839a_old](https://user-images.githubusercontent.com/99469/123520621-eec8d400-d687-11eb-920b-5e809efe5d49.png)

*New results*

![1839a_new](https://user-images.githubusercontent.com/99469/123520622-f38d8800-d687-11eb-9b79-e79df62d599b.png)

**Comment by HolgerF22** [comment]
Thanks to all, seems to work fine now!
