### ISSUE TITLE
Request- read.oce can read in files with incomplete header

### ISSUE THREAD

**Issue by Vinterwoo** [dankelley/oce#1845]
I'm using the read.oce function to read in RDI ADCP data files. The data files I'm reading in represent captured raw data streams from the ADCP, and the first lines of data files do not necessarily start with a complete header. Because the files do not start with a "7f7f", read.oce is unable to read in the file. In the past, I have had to manually open each file with a hex editor, and remove all of the data leading up to the first appearance of "7f7f". Is it possible to add the ability to read in files with an incomplete first ensemble (aka automatically remove all data before first appearance of "7f7f")?

**Comment by dankelley** [comment]
That should be possible.  We do similar things for other `adp` data types, but haven't done it for RDI because, in our experience, files have always been whole.

I'll take a look sometime today.

Thanks.

**Comment by dankelley** [comment]
I'll be putting test files and code in https://github.com/dankelley/oce-issues/tree/main/18xx/1845.  The shellscript I put there, named `create_data.sh`, can only be used by me, because it requires the existence of a particular local file.

**Comment by dankelley** [comment]
A note to @Vinterwoo -- it will not be possible to get `read.oce()` to do this, but I will make `read.adp.rdi()` do it.  

This is because `read.oce()` determines file type by examining the file contents, and there would be no reliable way to distinguish an RDI file from another file that just  happened to have a 7F7F somewhere in the first N bytes.  We don't want to start getting new false positives from `read.oce()`.  Note that this function handles 51 distinct file types, and so we don't want it getting needlessly more complicated by having to recognize partial files.  Besides, in practical work such as the case you bring up, the user will likely know what the file type is.

**Comment by dankelley** [comment]
I think this is working in the "develop" branch, commit 50e0550e4d8b0d5128f12a90e2ebd96c624dc176.  It can be installed from source in the usual way, but please note that this will not appear on CRAN until the next oce release, which might be 6 months away.

The test case at  https://github.com/dankelley/oce-issues/tree/main/18xx/1845 ought to demonstrate that this works.  In it, I am looking at two data files, constructed from a private file.  One of the files is the first 200K bytes of that private file, and the other is the portion from 100K to 200K.  I have used `expect_equal()` calls to check that things are working.  What I'm seeing is an exact match for both vectors and arrays.

I invite @Vinterwoo to try this new version, and either provide a followup comment on problems or close the issue.  If there are problems on your actual files, @Vinterwoo, please email me (or otherwise provide) the data file, along with code demonstrating the problem.

Thanks for noticing it -- it ought to help some other users, also.

**Comment by Vinterwoo** [comment]
Thanks for the quick response on this!
I'm assuming installation via the "normal way" would be:

remotes::install_github("dankelley/oce")

I'm having a some issues on my machine installing as above. But as soon as I get it figured out, I can plan to test out the updated library

**Comment by dankelley** [comment]
Actually, you'll need to install the "develop" branch, using
```R
remotes::install_github("dankelley/oce", ref="develop")
```
as explained in the README file, which you can see on the landing page https://github.com/dankelley/oce

If you don't specify the branch this way, it will use the "master" branch, which is usually updated only during CRAN releases.

**Comment by Vinterwoo** [comment]
Thanks again for that update. 
I'm running RStudio on MacOS 11.4, and after running 

`remotes::install_github("dankelley/oce", ref="develop")`

I'm getting:

ERROR: package installation failed
Error: Failed to install 'oce' from GitHub:

So I can't confirm if the updated branch addresses my issue (though I assume it does).  But I'll need to address this separate issue before I can test the fix.

**Comment by dankelley** [comment]
In case it helps, I built up a macos (11.4) version using R (4.1.0), and put it at the following link.   Whether it will work on your machine is an open question, of course.  The best is to get your system so it can build  the package directly, because then you can try new versions yourself.

https://www.dropbox.com/s/g8e7n9rcqdu530j/oce_1.5-0.tgz?dl=0

**Comment by Vinterwoo** [comment]
Thanks Dan!
