### ISSUE TITLE
Plot for argo not obeying `par` argument

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1879]
The following setting an absurd margin demonstrates that when plotting argo, the par argument is not obeyed. 

``` r
library(oce)
#> Loading required package: gsw
data(argo)
par(mar=c(10,6,15,1))
plot(argo)
```

![](https://i.imgur.com/tXFfr21.png)

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
This is an interesting issue that has lots of cousins.  In "oce", lots of plot functions alter the `par(mar)` and `par(mgp)` values.  We learned in argoFloats that R doesn't like this anymore (if it ever did ... but I don't recall feedback on this matter for oce, over the decade or so it's been on CRAN).

Try doing e.g. `plot(argo, mar=SOMETHING)` to see if that works.

Frankly, I don't want to go through all of `oce` to alter the margins, because that would break existing code.  (If I were a person finishing a thesis, redoing figures with a new font size that was demanded by the Faculty of Graduate Studies, I'd be really unhappy if all the margins changed!)

**Comment by j-harbin** [comment]
I agree that is seems like a big can of worms to go in and change all of the margins. I tried your suggestion of `plot(argo, mar=SOMETHING)` and it fixed my problem. The problem I was having is shown below:

*Note* my reprex is not currently working


```R
library(oce)
data(argo)
time <- argo[["time"]]
cm <- colormap(time) # Create colormap based on time
drawPalette(colormap=cm, pos=3) # Draw color palette
plot(argo, pch=21, col="black", bg=cm$zcol, mar=c(3,3,3,1))
```


![Screen Shot 2021-11-01 at 1 34 09 PM](https://user-images.githubusercontent.com/58750538/139707050-7e6232ee-b07c-4a10-b44c-119bc83288a0.png)

An addition of a `mar` argument in the plot command fixed this problem. Thanks!
