### ISSUE TITLE
ctd[["Absolute Salinity"]] does not work

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1885]
ctd[["absolute salinity"]] does work, but the help docs suggests that ctd[["Absolute Salinity"]] should work.

**Comment by dankelley** [comment]
a reprex would be sweet

**Comment by richardsc** [comment]
```r
library(oce)
data(ctd)
ctd[["Absolute Salinity"]]
```

**Comment by richardsc** [comment]
Produces:
```
> ctd[['AbsoluteSalinity']]
NULL
```

**Comment by richardsc** [comment]
Looking at https://github.com/dankelley/oce/blob/42efc2cc2cabdc5382ecb3ee548582282b5ab46e/R/ctd.R#L866 it appears that the search is for "absolute salinity".

**Comment by richardsc** [comment]
Note that both `ctd[["SA"]]` and `ctd[["sa"]]` works.

probably the best solution is to put a `tolower()` around all such args?

**Comment by dankelley** [comment]
Right.  Fixing now.  I'll upload with half an hour (the time it takes to do a local check).

**Comment by dankelley** [comment]
Done in "develop" branch commit 3678b143d3f966fd59585bc886b7cae0a1d2c6df.  Note that since the docs said one thing but the code did another, I made the code accept all three forms, and the docs indicate so.

I will leave it to the reporter to consider closing this issue.  The automated GH checks will likely be done in a half hour or so, and after that, the status icon on the landing page should get updated.

We now have tests on this in `tests/testthat/test_ctd.R`, viz.
```R
test_that("[[ works on SA, CT and variants", {
    data(ctd)
    SA1 <- ctd[["SA"]]
    SA2 <- ctd[["Absolute Salinity"]]
    SA3 <- ctd[["absolute salinity"]]
    expect_equal(SA1, SA2)
    expect_equal(SA1, SA3)
    CT1 <- ctd[["CT"]]
    CT2 <- ctd[["Conservative Temperature"]]
    CT3 <- ctd[["conservative temperature"]]
    expect_equal(CT1, CT2)
    expect_equal(CT1, CT3)
})
```

**Comment by dankelley** [comment]
This checks out OK on my machine, and in the GH actions (see https://github.com/dankelley/oce/actions).

**Comment by dankelley** [comment]
This issue was closed by the developer who solved the problem, because the following conditions were met:
1. the solution is simple
2. new tests were added to ensure that the solution works
3. the reporter is in frequent contact with the developer

Of course, if the reporter wants to reopen the issue, that's perfectly fine! The point here is just to avoid having issues in the developers' "to do" list, when they are probably done.

**Comment by dankelley** [comment]
We've had a fair bit of discussion offline, and concluded to disallow e.g.
```R
ctd[["absolute salinity"]]
```
because (a) it was never documented and (b) it gets us on a slippery slope of doing default actions for near-matches of names.  However, R does not work on near matches.  If a user does
```R
a <- list(Dan="silly")
```
then `a$dan` returns NULL.  R does not accept `"dan"` as a substitute.  We *do* have some alternates in oce, for convenience (like `Absolute Salinity` and `SA` being alternates) but we should not start ignoring case.  

Returning to our `a$Dan` example, if we were to accept `a$dan` then what would happen if the user added in a new thing called `dan`?

And what about misspellings, which are common.  Maybe we should take `a$dna` to mean `a$Dan`.  But if we do that, then code will be very hard to read, because it will depend in complex ways on what happens to be in the data.
