### ISSUE TITLE
drawPalette() not getting correct length of zlim

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1886]
The reprex below shows that when I look at the length of `cm$zlim` it is 2, however, `drawPalette()` is not recognizing that.

``` r
library(oce)
#> Loading required package: gsw
library(ocedata)
#> Loading required package: testthat
data(section)
stations <- section[['station']]
meanT <- unlist(lapply(stations, function(x) mean(x[["temperature"]])))
cm <- colormap(meanT)
length(cm$zlim) # Showing length of 2
#> [1] 2
drawPalette(cm,pos=3)
#> Error in drawPalette(cm, pos = 3): 'zlim' must be of length 2
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
Try `?drawPalette`, which reveals that the first arg is not the colormap...

**Comment by j-harbin** [comment]
Hehe! Problem fixed.

**Comment by dankelley** [comment]
Also, if you reinstall from github "develop", you'll get a more helpful error msg now
```
> drawPalette(cm,pos=3)
Error in drawPalette(cm, pos = 3) :
  if provided, 'zlim' must be of class 'numeric', but its class is 'listcolormap'
```

**Comment by dankelley** [comment]
Also, I looked at the doc and it says that `length(zlim)` can exceed 2, but the code was demanding it be 2.  So, I altered that in "develop" (see screenshot).  I have not altered the rule that `zlim` must be ordered, although the docs do not say that.  I don't have time now, to figure out what would happen if it were not ordered and since that rule was in the code for years, I have elected to retain it.  We could relax that rule if need be.  (In my own work, I always want ordered.  And nobody has complained about this rule, so far as I can recall, so we can wait until after the solstice to think about this.)
<img width="930" alt="Screen Shot 2021-11-29 at 3 25 38 PM" src="https://user-images.githubusercontent.com/99469/143929967-ef2ff752-3e3d-49dd-9bd0-cef9c4094d7f.png">
