### ISSUE TITLE
plot section produces error for which="density"

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1889]
The following reprex highlights the error when trying to plot a section with `which='density'`. You'll also see upon further inspection, all densities are not 0. Note, I actually noticed this when working with my own section data. As a test case I tried it with the built in section data and discovered the same error.

``` r
library(oce)
#> Loading required package: gsw
data(section)
plot(section, which="density")
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Error in plotSubsection(xx, yy, zz, which.xtype, which.ytype, which[w], : cannot draw a contour diagram because all values are NA or Inf
```

![](https://i.imgur.com/zTZXzcn.png)

``` r
for (i in seq_along(section[['station']])) {
    print(all(is.na(section[['station']][[i]][['density']])))
}
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
#> [1] FALSE
```

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
The problem is that there are many ways to define 'density', and we don't want users becoming confused, so we require precise statements.  The following work. Note that these are both density anomalies (density - 1000kg/m^3) and they are both of the 'potential' form.  The word "density" alone would mean in-situ, which would (I think) rarely be what a user would want.

Maybe you can check the docs to see if they say that `which="density"` is allowed.  If it is documented, I'll add it.  But I would need some serious convincing to make me think it is suitable.

Note that CTD objects do not store density. If you add density into the individual ctd stations in the section object, then I think you call would work because I think it would extract it from those ctd objects ... but I still don't think that's what a person wants, normally.

```R
plot(section,which="sigmaTheta")
plot(section,which="sigma0")
```

**Comment by dankelley** [comment]
This is how you could get what you want.  In the `lapply`, I am using the fact that `[[,ctd-method` will calculate density, and then I'm shoving that into the individual station objects.

But note how the bottom panel just shows nearly-horizontal lines.  That's because in-situ density is a strong function of pressure.  This function masks the horizontal variations that we so often care about (for e.g. thermal-wind calculations of geostrophic currents).
``` r
library(oce)
#> Loading required package: gsw
data(section)
section@data$station <- lapply(section[["station"]],
    function(x) oceSetData(x, "density", x[["density"]]))
par(mfrow=c(2,1))
plot(section,which="sigmaTheta")
plot(section,which="density")
```

![](https://i.imgur.com/c9IsjRo.png)

<sup>Created on 2021-12-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by j-harbin** [comment]
Once again, thanks for this Dan.
