### ISSUE TITLE
latitudelim and longitudelim arguments not obeyed after changing mfrow

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1922]
Hi All,

I am plotting the coastline in a study region, but I noticed when I change the mfrow (to allow a 4 panel plot), the `latitudelim` and `longitudelim` arguments are not obeyed. Is this and "R" thing? The problem in the second way is that it zooms too far out from my study region, so stick plots are harder to see.

``` r
library(oce)
#> Warning: package 'oce' was built under R version 4.1.2
#> Loading required package: gsw
library(ocedata)
#> Loading required package: testthat
#> Warning: package 'testthat' was built under R version 4.1.2
data("coastlineWorldFine")
plot(coastlineWorldFine, longitudelim=c(-65.5,-63), latitudelim=c(47.5, 48.5), mar=c(1,3,4,1))
#> Warning: In plot,coastline-method() : converting longitudelim and latitudelim to clongitude=-64.25, clatitude=48 and span=217
```

![](https://i.imgur.com/n0ehyuU.png)

``` r
par(mfrow=c(4,1))
plot(coastlineWorldFine, longitudelim=c(-65.5,-63), latitudelim=c(47.5, 48.5), mar=c(1,3,4,1))
#> Warning: In plot,coastline-method() : converting longitudelim and latitudelim to clongitude=-64.25, clatitude=48 and span=217
```

![](https://i.imgur.com/5KTdqNS.png)

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
These `*lim` arguments are just suggestions, because `plot,coastline-method()` always sets the `asp` as is appropriate for the given latitude.  In other words, this plot function tries to make a circular island be a circle on the plot, at least if that island is near the centre or the latitude range is small.

You're asking for a short-and-wide plot panel.  I'm not saying short-and-wide is a bad thing, as a height-challenged and widening d00d, but it does make it hard to get nice plots.

In a case like this, I'd be tempted to set wide margins, so the plot panel is more square.  But my bigger recommendation is to sketch what you want on a piece of paper, **independent** of thinking of how `par(mfrow)` might make it.  For example, maybe you would like the left third of the plot to be a map, and the right two-thirds to have 3 panels stacked vertically.  Just think of what would look nice.  Then type `?layout` and read it closely, trying some examples to get practice.

**Comment by j-harbin** [comment]
Thanks, Dan! This helps a lot. Ill close this issue.

**Comment by dankelley** [comment]
As an example, I use
```R
layout(matrix(c(1, 3, 2, 3), nrow=2, byrow=TRUE), widths=c(0.4, 0.6))
```
in making the app shown below.  After the above call, I plot the "easting" panel, then the "northing" one, and finally the easting-northing one (the spiral).  That last one appears twice in the matrix, so it occupies 2 rows.

<img width="918" alt="Screen Shot 2022-02-24 at 9 44 42 AM" src="https://user-images.githubusercontent.com/99469/155535797-f4dd91ca-6e85-4345-998d-5d1c45ef86c1.png">
