### ISSUE TITLE
Add raw magnetometer data functionality to Nortek ad2cp reading

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1931]
This functionality was added last year some time for Nortek Aquadopps, but it should also be possible to implement it for the ad2cp instrument data format. See page 82 in the integrators guide:

[Nortek Integrators guide](https://github.com/dankelley/oce/files/8445459/N3015-007_Integrators-Guide-AD2CP_0322.pdf)

Unfortunately I don't have a test file at the moment (we forgot to turn on that functionality when doing compass cals the other day) but I should be able to generate one fairly easily in the next week or two.

**Comment by dankelley** [comment]
I suspect this is working in the "ad2cp" branch.  No rush, @richardsc, but perhaps before the term starts you can make a sample file that would let us check whether the data are being read correctly.

**Comment by dankelley** [comment]
I'm going to close this, because I think it's been done. The issue can always be reopened if we get some ground-truthed data for testing, but we have no concrete timetable on that, and I don't like leaving issues open for months at a time, when in the course of actual research efforts the issue can be addressed properly, and in a validated context.
