### ISSUE TITLE
section class [[..., "grid:distance-pressure"]] methods not documented?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1940]
After the helpful change of d7968f7abeaf3 to put some of the section plotting examples back into the help page, I'm noticing that the mechanics that handle the "grid extraction", e.g.

```r
sec <- plot(section, which='temperature', ztype='image')
S <- sec[["salinity", "grid:distance-pressure"]]
contour(S$distance, S$pressure, S$field, level=35.8, lwd=3, add=TRUE)
```

don't seem to be documented in `?[[,section-method`.

(a related issue is that I am needing/wanting to do this for `grid:time-pressure`, which isn't currently supported, but that can have it's own issue if necessary).

**Comment by dankelley** [comment]
I'll take a look.  I'm just waiting on some grad-coord stuff.

**Comment by dankelley** [comment]
I've got this working in "develop" commit 4cf2be9f48391dc4b317dde36928bec1dafc1770 but there's something odd about the section: the times are not exactly in order.  You can see this below.  But note that whenever there's a negative value, there is a big positive near it.  I'm sort of wondering whether somebody wrote down the wrong dates.

```R
library(oce)
data(section)
> data.frame(section[["time"]][-1],diff(section[["time"]]))[30:40,]
   section...time.....1. diff.section...time....
30   1993-10-03 01:14:00          5.900000 hours
31   1993-10-03 07:27:00          6.216667 hours
32   1993-10-03 14:40:00          7.216667 hours
33   1993-10-03 18:35:00          3.916667 hours
34   1993-10-03 00:06:00        -18.483333 hours
35   1993-10-04 06:08:00         30.033333 hours
36   1993-10-04 12:31:00          6.383333 hours
37   1993-10-04 18:10:00          5.650000 hours
38   1993-10-05 23:30:00         29.333333 hours
39   1993-10-05 05:00:00        -18.500000 hours
40   1993-10-05 09:58:00          4.966667 hours  
```

**Comment by dankelley** [comment]
Here's a test code to show (I think) that it works.  But I have to sort to get the contouring to work, because base-R contour requires in-order.  (I could have used the oce variant ... just forgot about that, though.)
```R
library(oce)
data(section)
plot(seq_along(section[["station"]]),section[["time"]],type="l")
A <- sectionSort(section, by="time") # odd that we have to do this
B <- plot(A, which="temperature", xtype="time", ztype="image")
C <- B[["salinity", "grid:time-pressure"]]
contour(C$time, C$pressure, C$field, level=35.8, lwd=3, add=TRUE)
```
<img width="793" alt="Screen Shot 2022-05-02 at 4 36 50 PM" src="https://user-images.githubusercontent.com/99469/166313724-53b075e2-4a2b-490c-9a1f-28dc32579be2.png">

**Comment by dankelley** [comment]
Just in case, I looked at the orig data to check the date-time values and oce has stored them correctly.  The snapshot shows this.  The top window is the datafile and the cursor is on the last sample listed for 1993-10-03T18:35.  The line below has time 1993-10-03T00:06 and these are the values that oce has saved (lower window).

I don't see any other checks I can do.  I *guess* I could try to find the original data file again but I don't relish the thought of spending an hour trying to see where the data might live now.

Unless @richardsc has other thoughts on the actual issue -- or wants to think about those odd times -- I think this issue can be closed.

<img width="1340" alt="Screen Shot 2022-05-02 at 4 44 44 PM" src="https://user-images.githubusercontent.com/99469/166315133-26dfcc97-7bf3-4f17-900f-9e072f948b32.png">

**Comment by dankelley** [comment]
To be concrete, I think the time given in the server as 1993-10-03T00:06:00 is actually the next day, i.e. at 1993-10-04T00:06:00 (that would be near the approx 6-hour time between stations).

And I think the time listed as 1993-10-05T23:30:00 was really 1993-10-04T23:30:00.  Again, that would mean about a 6-hour interval.  And then the next sample was again roughly 6-hour later.

But this is a fool's game.  The data were taken 30 years ago.  I imagine the raw data, likely written by hand, are not scanned. And, even if so, where would the images be?

I might add a cleaned-up version of the above sentences to the docs for the dataset, because it is pretty weird. 

It's interesting that this has gone unnoticed.

**Comment by richardsc** [comment]
That is interesting. A nice demonstration that working with real data -- that involves human-recorded metadata -- is hard 😄 .

Thanks for the addition! I'll close the issue.

**Comment by dankelley** [comment]
@richardsc -- mind if I add a few sentences about the timing to the docs on `section`?  I think people like to read things like that, which can make technical docs a bit less stale.

**Comment by richardsc** [comment]
Oh, for sure that is a good thing to add!

**Comment by dankelley** [comment]
Done in "develop" commit 63887119e9f09565925c23a4302cbbc31cceb054; see snapshot 

<img width="452" alt="Screen Shot 2022-05-04 at 10 12 10 AM" src="https://user-images.githubusercontent.com/99469/166688412-09675e97-24a0-4a38-8fc6-759521d84b14.png">
