### ISSUE TITLE
Warning: startTime < 1950, suggesting y2k problem in this cnv file

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1968]
When I do the following code (note: the ctd.csv is just the built in ctd file from oce), I get the following warning

```R
library(oce)
ctd <- read.oce("ctd.cnv")
```

```R
Warning messages:
1: In read.ctd.sbe(file, processingLog = processingLog, ...) :
  startTime < 1950, suggesting y2k problem in this cnv file
```

It does read in the file fine, but any idea why that would be happening?

**Comment by dankelley** [comment]
Did you enclose the file?

**Comment by dankelley** [comment]
In the file, I see
```
# start_time = Oct 15 1903 11:38:38
```
so I think it's a y2k sort of thing.

**Comment by dankelley** [comment]
In the "develop" branch, commit c1e7b1ec87f1f7af6cd56ac00019a81c2d1788e1 (click to see the changes), I have changed oce so that now when you try to read that problem it says
```R
> library(oce)
> ctd <- read.oce("~/ctd.cnv")
Warning messages:
1: In read.ctd.sbe(file, processingLog = processingLog, ...) :
  startTime (1903-10-15 11:38:38) is < 1950, suggesting a turn-of-the-century problem in this cnv file
2: In read.ctd.sbe(file, processingLog = processingLog, ...) :
  this CNV file has temperature in the IPTS-68 scale and this is stored in the object, but note that [["temperature"]] and the sw* functions convert the numbers to ITS-90 values
```
which I hope is clearer.

Also, I updated the docs for the built-in dataset (acquired by typing `?ctd`) to mention that I used `oceEdit()` to alter the `start_time` from 1903 to 2003.

Also, if you do `?ctd` you get a bit more info on how the `data(ctd)` result has year 2003, not 1903.

<img width="565" alt="Screen Shot 2022-06-20 at 5 32 45 PM" src="https://user-images.githubusercontent.com/99469/174674279-a17e725f-16fb-4df3-b84f-a8426dfc71db.png">

**Comment by j-harbin** [comment]
Thanks for the quick fix, Dan! I'll close this issue.
