### ISSUE TITLE
Write Argo to netcdf after subsetting

### ISSUE THREAD

**Issue by Malek-Belgacem** [dankelley/oce#1976]
Hi,

After using `read.argo` to open a netcdf Argo file, we subset certain time and space slices of the data and now we would like to write it back to a netcdf file, but we could not find an appropriate function to do that. 

Please do you have any solution to propose, also using base R functions? We tried the conventional `write.csv`, but it does not seem effective.

Many thanks :)

**Comment by dankelley** [comment]
Hello, and thanks for the question.  No, I'm sorry, but oce can read the netcdf files, but it is not set up to write them.  It would be a great deal of work to code it to do so, and so this feature is not something that we are planning to add.

Rewriting to raw files is not something that oce attempts, for any data type.  For example, oce can read various types of CTD files, but cannot write them.  And the same goes for ADCP files, satellite files, and so forth.  The plan is that analysts will keep the data unchanged, and if some corrections need to be done, they should be done in R, in documented code that can be rerun by somebody else, starting with the original data.

I hope this explains the situation and the setup of oce.

**Comment by dankelley** [comment]
Note that you can always save an R object to an `rda` file, using `save()`, and then you can reload with `load()`.   You can save any kind of data, and even functions, in an `rda` file.  It's very handy.  The only risk is that R might change over the years, and not be able to read old `rda` files.  In my own work, I use `rda` files for things that take over an hour or so to compute.

**Comment by richardsc** [comment]
Hi @Malek-Belgacem! Thanks for using `oce`! 😄 

Just jumping in to further what Dan wrote -- creating "Argo" netCDF files by re-writing the contents of an `argo` object is certainly do able, especially if you work directly with one of the R netCDF packages (like `ncdf4`). However, the "true" Argo netCDF files have to meet a lot of stringent file, data, and metadata requirements, so if your goal is to product something that could be interepreted exactly the same as a "real" Argo NC file you'll have to familiarize yourself with the Argo documentation to make sure you get all the details right. 

If you merely want to write it out to a netCDF file so that other collaborators can use the extracted time and space slices (regardless of analysis language or platform) then you can just define your own netCDF schema and write the fields directly. The below link might be helpful for you if this is your goal.

https://pjbartlein.github.io/REarthSysSci/netCDF.html#create-and-write-a-netcdf-file

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. We use the list of open issues as a sort of "to do" list.

*Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
I'm closing this issue, since it seems to have been addressed fully.  If the original reporter wishes to reopen it, that's fine.  I use open issues as a sort of "to do" list, and this one implies no action on my part, hence nothing to do.
