### ISSUE TITLE
bug: argo[["?"]] doesn't show spice as a possible parameter to extract

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1978]
When I look at the parameters that can be derived from the built in ctd data set I get the following:

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
ctd[["?"]]$dataDerived
#>  [1] "Absolute Salinity"        "Conservative Temperature"
#>  [3] "CT"                       "density"                 
#>  [5] "N2"                       "potential temperature"   
#>  [7] "Rrho"                     "RrhoSF"                  
#>  [9] "SA"                       "sigma0"                  
#> [11] "sigma1"                   "sigma2"                  
#> [13] "sigma3"                   "sigma4"                  
#> [15] "sigmaTheta"               "sound speed"             
#> [17] "SP"                       "spice"                   
#> [19] "SR"                       "Sstar"                   
#> [21] "theta"                    "z"
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Where you can see `spice` is an option. When I do the same thing for the built in `argo` set, I get the following.

``` r
library(oce)
#> Loading required package: gsw
data(argo)
argo[["?"]]$dataDerived
#>  [1] "Absolute Salinity"        "Conservative Temperature"
#>  [3] "CT"                       "depth"                   
#>  [5] "N2"                       "profile"                 
#>  [7] "SA"                       "sigma0"                  
#>  [9] "sigma1"                   "sigma2"                  
#> [11] "sigma3"                   "sigma4"                  
#> [13] "sigmaTheta"               "theta"                   
#> [15] "z"
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

With no `spice` listed. It's interesting because I am still able to extract `spice` from the argo data set (Note: I'm only looking at the summary of the first profile to avoid lots of scrolling in this issue).

``` r
library(oce)
#> Loading required package: gsw
data(argo)
summary(argo[["spice"]][,1], na.rm=TRUE)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  0.1814  0.5965  1.1854  0.9302  1.2273  1.2769
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
Thanks for this.  I also noticed this, after yesterday's argo-tag meeting.  I will look into it.   At least it's something that won't affect the upcoming release of oce (since there are no "encoding issues" for binary files, this issue does not intersect with #1977).

My plan:
1. make `[["?"]]` tell us what we can get.  (If we have S,T,p,lon,lat then we can get `spiciness0`, `spiciness1`, `spiciness2` and `spiciness3` in addition to the other things listed.)
2. make `[["spiciness0"]]` etc work.
NOTE this will be done at a deep level, not just for argo.  That's why it's a bit tricky.  We use a clever scheme, where a `[[` call starts at the particular object type (`argo` in this case) and then, if there's nothing special, drops down a level to a base `oce` object).
