### ISSUE TITLE
Why are there no dataNamesOriginal for adp objects

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#1998]
Hi All,

I was wondering if there was a reason that unlike ctd and argo, for example, adcp does not have `dataNamesOriginal`.  Would there be a way of getting this info?
 See reprex below

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
data(argo)
data(adp)
ctd[['dataNamesOriginal']]
#> $scan
#> [1] "scan"
#> 
#> $timeS
#> [1] "timeS"
#> 
#> $pressure
#> [1] "pr"
#> 
#> $depth
#> [1] "depS"
#> 
#> $temperature
#> [1] "t068"
#> 
#> $salinity
#> [1] "sal00"
#> 
#> $flag
#> [1] "flag"
argo[['dataNamesOriginal']]
#> $latitude
#> [1] "LATITUDE"
#> 
#> $longitude
#> [1] "LONGITUDE"
#> 
#> $pressure
#> [1] "PRES"
#> 
#> $pressureAdjusted
#> [1] "PRES_ADJUSTED"
#> 
#> $pressureAdjustedError
#> [1] "PRES_ADJUSTED_ERROR"
#> 
#> $salinity
#> [1] "PSAL"
#> 
#> $salinityAdjusted
#> [1] "PSAL_ADJUSTED"
#> 
#> $salinityAdjustedError
#> [1] "PSAL_ADJUSTED_ERROR"
#> 
#> $temperature
#> [1] "TEMP"
#> 
#> $temperatureAdjusted
#> [1] "TEMP_ADJUSTED"
#> 
#> $temperatureAdjustedError
#> [1] "TEMP_ADJUSTED_ERROR"
adp[['dataNamesOriginal']]
#> NULL
```

<sup>Created on 2022-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by j-harbin** [comment]
When I read a local adp file on my laptop it does work. I'll close this issue, although unsure why it does not work for the built in data set.

**Comment by dankelley** [comment]
ADP (and similar) instruments store binary data, so there are no names in the files that would be stored as 'original' names.  Thus,
```R
library(oce)
data(adp)
sort(names(adp@metadata))
```
does not state any "original" names, since it was created from a manufacturer's raw binary file.

Perhaps the ladp you are talking about is from an ODF file.  These are text files, and they do contain variable names.

The biggest example is CTD data.  They are usually stored as CNV files, and the header within them explicitly names things.  The names can be weird, so we rename them for use in oce.  Basically, if an instrument -- any kind of instrument -- records something that is a temperature, it will be called `temperature` in the `data` slot, but we also record the original name, because the user might have code (in matlab or something) that refers to data by those names.  But insisting that a user who is working with maybe dozens of instruments at once knows all the names that might be used for temperature is too demanding.

For example, if you do
```R
data(ctd)
ctd[["dataNamesOriginal"]]
```
you'll see some weird names. SBE files have a *whack* of things that can store temperature.  Try doing
```R
?cnvName2oceName
```
and you'll see that there are a lot of names that might be hard to guess.
