### ISSUE TITLE
Help docs for read.topo() has a unfinished sentence for the return value

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2003]
See screen shot below

![Screen Shot 2022-09-27 at 12 02 41 PM](https://user-images.githubusercontent.com/58750538/192563094-5f867958-0c67-47cf-a3d8-faaa95f75764.png)

**Comment by dankelley** [comment]
Fixed in "develop" commit f06cf85a7f4619785899d9a504549bde8baf84b6.  I simply finished what I seemed to have been starting, in removing text to the right of "that".  Why not say something like "that can be plotted with ... and summarized with ... etc"? Because the point is that folks ought to click the "topo" link because that is where more info should reside.

Thanks!

Please close if you think it's been done.  (Hm, 1 word deleted in the code takes 3 paragraphs to explain!)
