### ISSUE TITLE
`legend()` not working as expected with `plot,section-method`

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#2009]
1. I'm using previously written code to produce section plots. The user of the plots requires that the variable names look a certain way, so I had used `legend()` in the past to get the look that was desired, but now it is not working. I'm not sure if this is an `oce` issue, an issue with my version, or if it's a `legend()` problem.

2. A simple reprex is provided below, see comments next to the `legend()` calls for expected behaviour.
``` r
library(oce)
#> Loading required package: gsw
data(section)
# define legend location in plot function
plot(section, which = 'temperature',
     ztype = 'image',
     legend.loc = 'bottomleft')
```

![](https://i.imgur.com/jyEuzp6.png)

``` r
# set no legend to be shown in plot function, add it after
plot(section, which = 'temperature',
     ztype = 'image',
     legend.loc = '')
legend('bottomleft', legend = 'bottomleft test') # not shown, expect it to be in same location as first test
legend('topleft', legend = 'topleft test', text.col = 'white') # shown as expected
legend('topright', legend = 'topright test', text.col = 'white') # shown as expected
legend('bottomright', legend = 'bottomright test') # not shown, expect it to be in bottom right of plot
```

![](https://i.imgur.com/HwtwHVW.png)

<sup>Created on 2022-10-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

3. `sessionInfo()`
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_2.0.1         oce_1.7-11           gsw_1.0-6            csasAtlPhys_0.0.9000

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.2  xfun_0.31         purrr_0.3.4       lattice_0.20-45   colorspace_2.0-3  vctrs_0.4.1       generics_0.1.3   
 [8] htmltools_0.5.2   viridisLite_0.4.0 yaml_2.3.5        utf8_1.2.2        XML_3.99-0.10     rlang_1.0.4       pillar_1.8.0     
[15] glue_1.6.2        withr_2.5.0       sp_1.5-0          readxl_1.4.0      lifecycle_1.0.1   munsell_0.5.0     gtable_0.3.0     
[22] cellranger_1.1.0  rvest_1.0.2       evaluate_0.15     knitr_1.39        callr_3.7.1       fastmap_1.1.0     ps_1.7.1         
[29] fansi_1.0.3       highr_0.9         Rcpp_1.0.8.3      clipr_0.8.0       scales_1.2.0      fs_1.5.2          gridExtra_2.3    
[36] smatr_3.4-8       ggplot2_3.3.6     digest_0.6.29     ocedata_0.2.0     processx_3.6.1    dplyr_1.0.9       ncdf4_1.19       
[43] grid_4.2.1        cli_3.3.0         tools_4.2.1       bitops_1.0-7      magrittr_2.0.3    RCurl_1.98-1.6    tibble_3.1.8     
[50] pkgconfig_2.0.3   xml2_1.3.3        rmarkdown_2.14    httr_1.4.3        rstudioapi_0.13   viridis_0.6.2     R6_2.5.1         
[57] compiler_4.2.1 
```

**Comment by dankelley** [comment]
After you do the section plot, try doing
```R
par("usr")
```
and I think you'll find the 3rd and 4th values informative.  I am pretty sure the section plot does some tricks with the plot region so it can work whether you ask for z or pressure on the axis, etc.  I think you can do z, depth or pressure, in fact.

Anyway, once you do this `par("usr")` try using a `points()` call to try to put a dot on the plot.  You'll quickly seem how this works.  Then you can just call `legend()` with specification of the `x` and `y` parameters, to put things wherever you want. You might always want at a certain depth, or a certain fraction of the full depth, or whatever -- basically, `legend()` will let you put things anywhere in the plot area.

**Comment by clayton33** [comment]
Thanks for the suggestions. I ended up abandoning `legend()` all together. I used `text()` instead and your suggestion of using `par('usr')`. I guess this didn't end up being an issue after all... should have just sent you a quick e-mail. It's still bothering me why it stopped working... but well, I found a solution for now.

**Comment by dankelley** [comment]
I am reopening this so I can look next week, after the flurry of grading/midterms is over.

**Comment by dankelley** [comment]
I see: `legend("bottomleft")` (etc) is trying to draw the legend *below* the plot.

I know I do some tricks in `plot,section-method()` so the y axis decreases up (if you show pressure, but not if you show z) so maybe that's causing some problems.

Note to @clayton33 I'm pretty sure you can do `legend(x,y,...)` if you know a good x and y value for a given plot, but of course that's a hassle.

I'll look into this some more, later this week.

``` r
library(oce)
#> Loading required package: gsw
data(section)
plot(section, which="temperature")
# Permit plotting outside plot area.
par(xpd = NA)
l <- legend("bottomleft", legend="BOTTOMLEFT", text.col=2)
```

![](https://i.imgur.com/hoBkYqG.png)

``` r
# Examine where it tried to put it: at 5753 dbar...
str(l)
#> List of 2
#>  $ rect:List of 4
#>   ..$ w   : num 1390
#>   ..$ h   : num 0
#>   ..$ left: num 0
#>   ..$ top : num 5483
#>  $ text:List of 2
#>   ..$ x: num 279
#>   ..$ y: num 5753
# ... but 5753 is outside the plot area (and would be invisible, if not
# for the use of par(xpd) above.
par("usr")
#> [1]    0.000 5633.493 5483.030    0.000
```

<sup>Created on 2023-02-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
There are two issues in this:
1. We use `par()` at the start and then reset some things later. Here and in other oce functions, this is a bit tricky.  Basically, the R defaults for e.g. margins are somewhat undesirable for oceanographic plots (e.g. in a profile, the axes go at the top and there is no reason to have a lot of whitespace at the bottom, which is what default R gives).  So this and many oce functions alter margins.  But CRAN doesn't like functions that modify margins, or that modify `par(mfrow)`, etc.  So, we set `par` things back at the end of the function. But then that means that the user cannot use `points()` etc because they can come in the wrong place.  This is all a bit too hard to describe in an issue but, long-story-short, I can fix this part of the problem.
2. We are using `contour()` and `.filled.contour()` in this function. Both require that the matrix `x` and `y` values be in order.  What `plot,section-method` does at present is to use the oceanographic "z" coordinate for the `y` axis, which puts deep water at the bottom of the plot.  But then it draws the axis using pressure or depth (by a sort of trick).  This all seems great, *except* that then if the user wants to do e.g. `abline(h=3000)` to draw a line at 3000 dbar, they cannot do so; they have to use `abline(h=-3000)`.  This is tricky and ugly.  I am going to see about changing this, not by messing with the `y` data but instead by using `ylim`.

PS. I am aware that this comment might not make sense to anybody reading this.  It's just me, recording my thoughts before I put my head into a rabbit hole...

**Comment by dankelley** [comment]
@clayton33 I think I have solved this in the "issue2009" branch, commit 46b9b997dcf689ec2c1585dcaa7fee338817ee97.  A reprex is below, if you want to test it.  It should show you that

1. legends now appear as desired, whether done separately or in `plot,section-method`.
2. the `par(usr)` setup is now correct, so you can add things to the plot without multiplying the vertical location by -1.  (Such multiplication was required before because I did a whacky trick of using z for the axis internally, so `contour()` could handle it, but labelling the axis with pressure.)

Perhaps you can have a look sometime, ideally in the next week or two.  If it seems OK, I'll merge it from "issue2009" into "develop".  (The earlier I merge, the less likely there will be merge conflicts.)

PS. I'm doing a little trick in my layout, to give a bit more space to the lower-left panel, which has a palette that uses up space.  I do like `layout()` for things like this :-)

``` r
# Improve section plot re legend and adding new elements.
#
# sandbox/issues/20xx/2009/2009_01.R
#
# https://github.com/dankelley/oce/issues/2009

library(oce)
#> Loading required package: gsw
data(section)
# Focus on a recognizable region (with Gulf Stream)
section <- subset(section, longitude < -70)

par(mfrow=c(1, 3))
layout(matrix(c(1, 1, 2, 3), byrow=TRUE, nrow=2), widths=c(1, 0.9))

plot(section, which="map", span=2000)
legend("bottomleft", legend="TEST") # is this visible?

plot(section, which="temperature", xtype="longitude",
     showBottom=TRUE, ztype="image")
points(-71.5, 2000, col=2, pch=20) # is this visible?
text(-71.5, 2000, "71.5W, 2000 dbar", col=2, pos=1) # is this visible?
legend("bottomleft", legend="TEST") # is this visible?

plot(section, which="temperature", xtype="longitude",
     showBottom=TRUE)
points(-71.5, 2000, col=2, pch=20) # is this visible?
text(-71.5, 2000, "71.5W, 2000 dbar", col=2, pos=1) # is this visible?
legend("bottomleft", legend="TEST") # is this visible?
```

![](https://i.imgur.com/mWItNxT.png)

<sup>Created on 2023-02-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by clayton33** [comment]
Hmn... I think something is going on with the `ylim` argument now... see below `reprex`

``` r
library(oce)
#> Loading required package: gsw
data(section)
# Focus on a recognizable region (with Gulf Stream)
section <- subset(section, longitude < -70)

# put the plotting in a function to make the code below easier too see the different tests
plotTestSection <- function(ylim) {
    plot(section, which="temperature", xtype="longitude",
         showBottom=TRUE, ztype="image", 
         ylim = ylim)
    mtext(text = paste('ylim = ', paste(ylim, collapse = ', ')), line = 0.5) 
}

par(mfrow=c(2,2))
# 1. What was done before
ylim <- c(0,500) # the ylim that currently works in develop branch
plotTestSection(ylim = ylim)

# 2. Try multiplying by above by -1 ?
ylim <- c(0, -500)
plotTestSection(ylim = ylim)

# 3. What about reversing the ylim as done in 1
ylim <- c(500,0) # the ylim that currently works in develop branch
plotTestSection(ylim = ylim)

# 4. Same as 3, but for the ylim as done in 2
ylim <- c(-500, 0)
plotTestSection(ylim = ylim)
```

![](https://i.imgur.com/s7Hr8WE.png)

<sup>Created on 2023-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
Excellent detective work!  I'll take a look.

There were quite a lot of changes, and I forgot to check on `ylim`.

**Comment by dankelley** [comment]
Q for @clayton33 -- can I get your advice on the suggesstion I make after the horizontal line, near the end?  (You may also want to read the other sstuff but
hat do you think it should do with `ylim=c(0,-500)` or `ylim=c(-500,0)`?  At the moment -- and this is not pushed to GH yet -- I do
```R
ylim <- if (!is.null(ylim)) sort(abs(ylim)) else yyrange
```
in the code, and later I do
```R
ylim <- rev(ylim)
```

In other words, at the moment (again, not on GH) all of the following yield the same result
```R
c(-500, 0)
c(500, 0)
c(0, -500)
c(0, 500)
```

The negative numbers don't make sense since the only choices for `ytype` are `"pressure"` and `"depth"`, because the code has
```R
ytype <- match.arg(ytype, c("depth", "pressure"))
```

However, if I add the possibility to plot versus `"z"` (which I think might have worked in the past ... or maybe it's just that this is what I often plot for class-work so they will know that "z" is negative) then negative numbers should be allowed.

I am inclined to not permit negative numbers.  I suppose I should only permit ylim of the form `c(500,0)` in order to follow the usual R notation.

Sorry to be rambling.  I have a simple question: do you agree that I should impose the rules
* the entries in `ylim` must be nonzero
* `ylim[1] > ylim[2]`

**Comment by clayton33** [comment]
Following the usual R notation, ylim of the form `c(500,0)` makes sense. So I guess, yes, I agree your rules make sense.

**Comment by dankelley** [comment]
@clayton33, I think I have things working now for `ylim`, in commit e3484abde9c2544bcdfddcb62b14106645d77f7c of the "issue2009" branch.

Below is a reprex based on yours.  Notice that I use `try()` in the last two lines, to show the error messages but still continue to the end of the reprex.

``` r
library(oce)
#> Loading required package: gsw
library(testthat)
data(section)
# Focus on a recognizable region (with Gulf Stream).
section <- subset(section, longitude < -70)

# put the plotting in a function to make the code below easier too see the different tests
plotTestSection <- function(ylim) {
    plot(section, which="temperature", xtype="longitude",
         showBottom=TRUE, ztype="image", 
         ylim = ylim)
    mtext(text = paste('ylim = ', paste(ylim, collapse = ', ')), line = 0.5) 
}

par(mfrow=c(2, 1))
plotTestSection(ylim = NULL) # auto-scale y
plotTestSection(ylim = c(500, 0)) # top 500 m
```

![](https://i.imgur.com/ab9ipci.png)

``` r
try(plotTestSection(ylim = c(0, 500))) # expect error
#> Error in .local(x, ...) : 
#>   In plot,section-method() require ylim[2]<ylim[1], but ylim=c(0,500) was provided
try(plotTestSection(ylim = c(0, -500))) # expect error
#> Error in .local(x, ...) : 
#>   In plot,section-method() : ylim elements cannot be negative, but ylim=c(0,-500) was provided
```

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
Also, my reprex from a few comments back still works:

``` r
# Improve section plot re legend and adding new elements.
#
# sandbox/issues/20xx/2009/2009_01.R
#
# https://github.com/dankelley/oce/issues/2009

library(oce)
#> Loading required package: gsw
data(section)
# Focus on a recognizable region (with Gulf Stream)
section <- subset(section, longitude < -70)

par(mfrow=c(1, 3))
layout(matrix(c(1, 1, 2, 3), byrow=TRUE, nrow=2), widths=c(1, 0.9))

plot(section, which="map", span=2000)
legend("bottomleft", legend="TEST") # is this visible?

plot(section, which="temperature", xtype="longitude",
     showBottom=TRUE, ztype="image")
points(-71.5, 2000, col=2, pch=20) # is this visible?
text(-71.5, 2000, "71.5W, 2000 dbar", col=2, pos=1) # is this visible?
legend("bottomleft", legend="TEST") # is this visible?

plot(section, which="temperature", xtype="longitude",
     showBottom=TRUE)
points(-71.5, 2000, col=2, pch=20) # is this visible?
text(-71.5, 2000, "71.5W, 2000 dbar", col=2, pos=1) # is this visible?
legend("bottomleft", legend="TEST") # is this visible?
```

![](https://i.imgur.com/GfyJdEg.png)

<sup>Created on 2023-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by clayton33** [comment]
Tested it on code I use regularly to create section plots and it works :) Thank you !

**Comment by dankelley** [comment]
Thanks for the help, and sorry for letting this issue unaddressed for so long.  D.

**Comment by clayton33** [comment]
All good, I had found a decent workaround while I waited.
