### ISSUE TITLE
drawDirectionField problem

### ISSUE THREAD

**Issue by cfranzke72** [dankelley/oce#2011]
I am trying to add arrows to a plot but no arrows are plotted.

A minimal code example is:
library(oce)

data(coastlineWorld)

load("arrowplotdata.RData") #Data can be downloaded at: https://www.dropbox.com/s/2x9v564tckhi9la/arrowplotdata.RData?dl=0

mapPlot(coastlineWorld,projection="+proj=moll",grid=FALSE,col="lightgray",drawBox=FALSE)
mapImage(lon,lat,field21,zlim=c(-3e-7,3e-7))
drawDirectionField(x=lon,y=lat,u=field1,v=field11,scalex=2000,length=0.05,skip=6,add=TRUE,type=2)
mapGrid(col=gray(0.2))
mapPolygon(coastlineWorld[['longitude']], coastlineWorld[['latitude']])

I am using R version 4.2.1 on a iMac Monterey 12.6
oce version: oce_1.7-10

If I just use drawDirectionField(x=lon,y=lat,u=field1,v=field11,scalex=2000,length=0.05,skip=6,type=2) without adding to an
existing map I get a basic plot of arrows. Adding to an existing map does not work for me.

**Comment by dankelley** [comment]
I tried your code, and can verify that I see no arrows.  But, please note that `drawDirectionField()` does not work with map projections.  Only functions starting with the letters `map` work for those diagrams.

I suppose you could work through your grid using `mapArrows()`, but to do that you will need to do some calculations to determine the arrow start/end positions. It will be slow, I think.  I am not sure how easy it would be for those examining the diagram to understand the direction field, however.  They would have to take into account the particular features of the particular projection.  That is, they will need to consider things like whether lines of constant latitude parallel in this projection, along with the amount of distortion in shape, angle, and area there is across the domain, etc.  Map projections are simply tricky things, and I think there is a reason why non-projected representations are quite common in some disciplines.

As a matter of interest, I made the following code, with the following results.  At least I can see that your data field seems to be sensible (not random numbers).  Note that I wrote a function to draw the world coastline twice, because it and your data use a different range for longitude.

```R
# NOTE: drawDirectionField does *not* work with projected maps, so this code
# does not draw these. Also, the code has been pared-down so it does not
# require loading another package for colours.

library(oce)
data(coastlineWorld)
load("arrowplotdata.RData")

# Put each plot in its own file. The scaling avoids too
# much whitespace. In fancier work, you could draw axes
# with separate calls, in which you require that lat go
# from -90 to 90, etc.
png("2011_%d.png", height=3.7, width=7, unit="in", res=200)

addCoastline <- function(col=2, lwd=1)
{
    clon <- coastlineWorld[["longitude"]]
    clat <- coastlineWorld[["latitude"]]
    lines(clon, clat, col=col, lwd=lwd)
    lines(clon+360, clat, col=col, lwd=lwd)
}


# Get overall idea of fields (contours). We need to use
# oceContour() rather than contour() because the latter demands
# that both x and y hold increasing values.
oceContour(lon,lat,field1,asp=1)
addCoastline()
oceContour(lon,lat,field11,asp=1)
addCoastline()

# Get overall idea of fields (images)
imagep(lon,lat,field1, asp=1)
addCoastline()
imagep(lon,lat,field11, asp=1)
addCoastline()

# Subsampling can help to avoid overdrawing on small diagrams
nlon <- length(lon)
nlat <- length(lat)
d <- 2
ilon <- seq(1, nlon, d)
ilat <- seq(1, nlat, d)
drawDirectionField(x=lon[ilon], y=lat[ilat],
    u=field1[ilon,ilat], v=field11[ilon,ilat],
    asp=1, xaxs="i",
    lwd=0.5, cex=0.0,scalex=150)
addCoastline()
```
![2011_1](https://user-images.githubusercontent.com/99469/199685367-b2765a36-bd9d-45c5-86a5-2d0684013e6f.png)
![2011_2](https://user-images.githubusercontent.com/99469/199685372-03d127be-9b27-4910-8009-a6e884a060d9.png)
![2011_3](https://user-images.githubusercontent.com/99469/199685374-0e8bf640-2815-4cc4-bd86-c179d02c8cff.png)
![2011_4](https://user-images.githubusercontent.com/99469/199685378-ddd7f81f-d022-4ccb-ba90-29b9720be822.png)
![2011_5](https://user-images.githubusercontent.com/99469/199685381-c7ce49c6-4e3e-4736-91e1-c679bcbed489.png)

**Comment by richardsc** [comment]
In a classic case of "the developers of the package forgot about existing functionality", I think the function that you want here is `mapDirectionField()`. The code below is from the example in the `mapDirectionField()` docs -- does this do what you want?

😄 

``` r
library(oce)
#> Loading required package: gsw
     data(coastlineWorld)
     par(mar=rep(2, 4))
     mapPlot(coastlineWorld, longitudelim=c(-120,-55), latitudelim=c(35, 50),
             projection="+proj=laea +lat0=40 +lat1=60 +lon_0=-110")
     lon <- seq(-120, -60, 15)
     lat <- 45 + seq(-15, 15, 5)
     lonm <- matrix(expand.grid(lon, lat)[, 1], nrow=length(lon))
     latm <- matrix(expand.grid(lon, lat)[, 2], nrow=length(lon))
     ## vectors pointed 45 degrees clockwise from north
     u <- matrix(1/sqrt(2), nrow=length(lon), ncol=length(lat))
     v <- matrix(1/sqrt(2), nrow=length(lon), ncol=length(lat))
     mapDirectionField(lon, lat, u, v, scale=3)
     mapDirectionField(lonm, latm, 0, 1, scale=3, col='red')
     # Color code by longitude, using thick lines
     col <- colormap(lonm)$zcol
     mapDirectionField(lonm, latm, 1, 0, scale=3, col=col, lwd=2)
```

![](https://i.imgur.com/7IEqSwP.png)

<sup>Created on 2022-11-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cfranzke72** [comment]
Hi, sorry for my late reply but I was at a conference last week.

Thanks for your help. Your code example is very helpful.

**Comment by cfranzke72** [comment]
Hi, is it possible to draw a "unit arrow" outside of the plot area to indicate the length of the arrows?
Similar to a color bar.

**Comment by dankelley** [comment]
@cfranzke72 If you use `par(xpd=NA)` then you can plot anything anywhere in the plot device.

I'm closing the issue on the assumption that the original matter has been addressed.  We use open issues as a "to do" list in oce.  @cfranzke72 if you have further problems, please create new issues, with titles that are precise and narrow enough that a reader will understand the subject just from the title.  Thanks.
