### ISSUE TITLE
Support for MIDAS .ntk file format

### ISSUE THREAD

**Issue by ddieffen** [dankelley/oce#2017]
When using this library I can open the Signature500 files extracted from the device in the ad2cp file format. However when our current profiler is connected to the MIDAS software and data aquisition is performed continuously, it creates .ntk files.

It seems that this file format is undocumented (i cannot find anything on the datastructure) and I was wondering if anyone had any information that would enable us to read this .ntk file format directly.

**Comment by dankelley** [comment]
I don't know about this, but @richardsc might.

**Comment by richardsc** [comment]
Coincidentally I just installed MIDAS to try -- I got it from a colleague because it isn't actually distributed by Nortek anymore (at least, I can't find it [here](https://www.nortekgroup.com/software).

Given that, and that the ntk format isn't documented, I don't know of any resources for reading it. I'm tagging @racheel because he's the one I got MIDAS from, and might have other ideas, though I suspect that he would typically export the data from MIDAS into another format (`.mat` or `.nc`).

As an aside, @dankelley and I have been working on the ad2cp support quite a lot in the last few months, with much of the recent work living in the `ad2cp` branch and not `develop`. We'd love to have your input on some of the planned changes to the codebase, such as issue #2005, and would love it if you can test against ad2cp files that you have.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list, so it helps us to know which issues still need to be addressed.

*Thanks!*

PS.  This is a standardized reply.

**Comment by ddieffen** [comment]
Hello,

Thanks to you all for your inputs, I understand that this format is not documented thus it is not planned to be supported in the future and this ticket can be closed.

Best regards

**Comment by dankelley** [comment]
Thanks.  Good luck in your work, and please don't be shy to reach out to the oce team if you encounter problems or have good ideas for new features.  (I'm not saying we will take all ideas, because we have to weigh our time against the user's benefit.)
