### ISSUE TITLE
Suggestion: Rename argoJuldToTime() to juldToTime()

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2019]
I am currently working with CTD profiles that have their time stored as Julian Day. I've been using the `argoJuldToTime()` to convert these times to POSIXct times. The only argument in `argoJuldToTime()` is a Julian time, so I was wondering if "argo" should be removed from the function name as it could be used for any type of instrument.

Also, I realize that according to the help docs, for Argo standards, Julian day has day =0 at 1950-01-01. I'm not sure if this is standard across instrument types and I realize if it is not then the function name should stay as it (and I should not be using this for my CTD profiles)

**Comment by dankelley** [comment]
Good eyes!  We should not change the name, though, because

1. the name does not prevent its being used for other data types (it does not check the type of the arg)
2. Julian day has multiple meanings.  Well, actually, it has only one *real* meaning, but folks have started calling all kinds of things Julian days.  This function handles a definition used by Argo and likely by other programs, but it's not the real Julian day.

Try doing
```
??julian
```
to see other functions.  The "real" definition is that used in astronomy as used by `julianDay()`. The last lines of the docs for that are as follows.

```R
library(oce)
## example from Meeus
t <- ISOdatetime(1977, 4, 26, hour=0, min=0, sec=0, tz="UTC")+0.4*86400
stopifnot(all.equal(julianDay(t), 2443259.9))
```

More dramatically, the proper Julian day at the "start" of the Argo version is as below.  Not exactly zero or one!

```R
> t <- ISOdatetime(1950, 1, 1, hour=0, min=0, sec=0, tz="UTC")
> julianDay(t)
[1] 2433282
```

**Comment by j-harbin** [comment]
Thanks for this clarification, Dan :). I'll close this issue (and make sure to only ever say Julian Day when appropriate hehe)
