### ISSUE TITLE
Create applyDeclination() function

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2038]
After a chat with CR and DK we realized that if an `adp` object has `oceCoordinate`s that are already in `enu`, there is no way to correct for declination. We decided that `applyDeclination()` would be the answer to this. This will involve creating an metadata data slot named `north` which can either be `true` or `magnetic`. DK will create a check list below.

Subtasks:
* [x] create branch `adp-declination` for this work (even though there will be some adv stuff too)
* [x] add `north` as a field in `metadata` slot of `adp` the data type (DK will do)
* [x] add `north` as a field in `metadata` slot of `adv` the data type (DK will ask JH to do)
* [x] make `summary,adp-method` report `north`, if it exists (DK will do)
* [x] make `summary,adp-method` report `north`, if it exists (DK will ask JH to do)
* [x] ... lots more will get added here by DK and/or by JH

**Comment by dankelley** [comment]
Thanks. The work will go into the branch named `adp-declination`.  PS. I realized in creating the branch name that this will also need to be done for the `adv` type.

**Comment by dankelley** [comment]
Oh jeeze.  I coded it (not yet pushed) and was going into `NAMESPACE` to add an entry ... and noticed that we *already* have something with a similar name that is restricted to `cm` objects (seen screenshot).  Since the old name is -- I think -- better than our new name, I think I'll add this there.  So, although we started with 1 object type ("adp") we now have three ("adp", "adv", "cm").


<img width="1170" alt="Screenshot 2023-02-09 at 1 58 29 PM" src="https://user-images.githubusercontent.com/99469/217898572-344b01cd-18bc-42e5-b2f7-15be2f151845.png">

**Comment by richardsc** [comment]
OF COURSE we already have a function to do this (and forgot about it).

<img src="https://media0.giphy.com/media/xT5LMzIK1AdZJ4cYW4/giphy.gif"/>

**Comment by dankelley** [comment]
I have made some progress in the "adp-declination" branch, commit 5ff5a9d61c5192fdf9ff0aa2ee6c930791ec526d.  The changes are:

1. We have a new generic function named `applyMagneticDeclination()`, with specialized versions for `adp`, `adv` and `cm` classes. The documentation for these functions provides the relevant details so I won't repeat them here.
2. We have a test suite that ensures that the functions work on velocities.  (I will add a check on headings soon.)

Below is a regexp that demonstrates.  I am using a 90 degree case so that the eye can check the patterns more easily (with less data overlap).

<details>

``` r
library(oce)
#> Loading required package: gsw
par(mar=c(3, 3, 1, 1),  mgp=c(2, 0.7, 0))
cex <- 0.4

# current meter
data(cm)
u <- cm[["u"]]
v <- cm[["v"]]
lim <- c(-1, 1) * max(abs(c(u, v)))
plot(u, v, xlim=lim, asp=1, cex=cex)
cm2 <- applyMagneticDeclination(cm, 90) # rotate clockwise 90deg
u2 <- cm2[["u"]]
v2 <- cm2[["v"]]
points(u2, v2, col=2, cex=cex)
mtext("data(cm): black=orig, red=applyMagneticDeclination(cm, 90)")
```

![](https://i.imgur.com/pfsFtXx.png)

``` r

# adp
data(adp)
velo <- adp[["v"]]
u <- velo[, , 1]
v <- velo[, , 2]
lim <- c(-1, 1) * max(abs(c(u, v)), na.rm=TRUE)
plot(u, v, xlim=lim, asp=1, cex=cex)
adp2 <- applyMagneticDeclination(adp, 90) # rotate clockwise 90deg
velo2 <- adp2[["v"]]
u2 <- velo2[, , 1]
v2 <- velo2[, , 2]
points(u2, v2, col=2, cex=cex)
mtext("data(adp): black=orig, red=applyMagneticDeclination(adp, 90)")
```

![](https://i.imgur.com/5AB772L.png)

``` r

# adv
data(adv)
velo <- adv[["v"]]
u <- velo[, 1]
v <- velo[, 2]
lim <- c(-1, 1) * max(abs(c(u, v)), na.rm=TRUE)
plot(u, v, xlim=lim, asp=1, cex=cex)
adv2 <- applyMagneticDeclination(adv, 90) # rotate clockwise 90deg
velo2 <- adv2[["v"]]
u2 <- velo2[, 1]
v2 <- velo2[, 2]
points(u2, v2, col=2, cex=cex)
mtext("data(adv): black=orig, red=applyMagneticDeclination(adv, 90)")
```

![](https://i.imgur.com/UoqIIUl.png)

<sup>Created on 2023-02-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
My next steps will be to (
* [ ] check the headings in the test suite
* [ ] work on how the `declination` argument is handled in the other functions
* [ ] ensure that the new functions demand `enu` as the incoming coordinate system

**Comment by dankelley** [comment]
Commit d41b73cb45603ac7af577f37d06d8f5f97181ad3 of `adp-declination` branch has all tasks addressed **BUT** things are really quite complicated for the `to*` functions for `adp` and `adv` classes so I am not too sure the results are correct.  (For example, what to do with heading when an instrument is upside down?). I think the only way to know if this works is to have some real-world testing by people (perhaps @richardsc) who have datasets with which they are familiar enough to know if things seem to be done correctly.

I feel that the main task, writing `applyMagneticDeclination()` is handled well, and it is both documented and tested.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list, so it helps us to know which issues still need to be addressed.

*Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
Plan: I will merge `adp-declination` into `develop` at 1000h today, at which point I'll also close this issue.

**Comment by dankelley** [comment]
Merged into `develop`, so closing now, after Z with original reporter.
