### ISSUE TITLE
Typo in adp-class help page (low priority)

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2040]
@dankelley, I noticed a typo in the help pages for `adp-class`. See below (where quality is repeated twice)

Corresponding to the velocity array are two arrays of type raw, and identical dimension, accessed by adp[["a"]] and adp[["q"]], holding measures of signal strength and data quality quality, respectively.

**Comment by dankelley** [comment]
That's some some typo!  Fixed in commit ecd67ee49fc5d59708192cf41b784d2199b1c404 of the "adp-declination" branch.  (It's fixed in `R/` and in `man/` but not in `docs/` ... the latter are just for the online manual but I don't see the sense of waiting 10 minutes for that to rebuild.)

Please check and close if okay.

**Comment by richardsc** [comment]
Are you sure that it wasn't meant to refer to the quality of the data quality? Like, "meta-quality"? 

😄

**Comment by dankelley** [comment]
As in "good" is "some good" where I come from, and if it's even better, it's "right some good".  Or, for politeness, "right some good, eh?".

**Comment by j-harbin** [comment]
Looks good!
