### ISSUE TITLE
Update documentation for adpFlagPastBoundary

### ISSUE THREAD

**Issue by j-harbin** [dankelley/oce#2041]
Right now, we have a `trim` argument, which is defaulted to 0.15. After a chat with CR, he let me know that in our equation when we use (1-trim), that actually comes from the cos(beamAngle*pi/180) equation. CR thought we should add some more documentation in regards to trim. I'm happy to do this and do a PR, I'm just unable to assign myself to this issue.

**Comment by dankelley** [comment]
I assigned you.  Please make the PR be with respect to the "develop" branch.  Ta!

**Comment by dankelley** [comment]
I've lost track, a little.  Has this been addressed?  If so, please close.  If not, feel free to reach out for discussion.  Sometimes it's easier to work on code jointly over Z.

**Comment by dankelley** [comment]
@j-harbin I think this has been done, so I will likely close this issue by the end of today, unless you let me know to keep it open.  Thanks!

(I'm applying pressure because I always want simple issues to be cleared up several weeks before a CRAN release.  I've learned that even small changes can cause problems, and so I always want tools to have been used for a few weeks before a CRAN submission, to catch problems.)

**Comment by dankelley** [comment]
I'm closing the issue, since I think it has been addressed.  If you disagree with this action, @j-harbin, please feel free to reopen it and to discuss it over Z or here.
