### ISSUE TITLE
add option to numberAsPOSIXct for GPS roll over time compensation

### ISSUE THREAD

**Issue by MatthiasSiewert** [dankelley/oce#2077]
I have a GPS timestamp referenced to 1980 GPS time

numberAsPOSIXct(cbind(2250, 502834.494144), type="GPS") 
[1] "2042-10-10 19:40:16 UTC"

While it should be 
[1] "2023-02-24 19:40:16 UTC"

This can be compensated for example using lubridate by subtracting the additional 1024 weeks:
test <- numberAsPOSIXct(cbind(2250, 502834.494144), type="GPS") 
test - weeks(1024)
[1] "2023-02-24 19:40:16 UTC"

Solution:
Either add an option to specify GPS week reference, or add a note explaining the problem and solution (took me two hours to figure out...)

See also:
https://www.septentrio.com/en/learn-more/insights/all-you-need-know-about-gps-gnss-week-number-rollover

Otherwise, great work! Thanks!

**Comment by dankelley** [comment]
Thanks.  I'll add an argument, and documentation.  We are planning a CRAN release in a few weeks, and this should be included, since there ought not to be ripple effects.

**Comment by dankelley** [comment]
Here's my plan.  I don't want to add a new argument to the function because it's old and that would be a fairly large change.  Also, and more importantly, that argument would apply only to this one type of time, and there are multiple other types.  Having arguments that are used only in rare cases can be confusing to the user.

But there is a simple solution that I think I'll do later today. That is that if  `type=="gps"`, then the first argument might hold *either* 2 columns (as at present), or 3 columns (if the rollover is different from the default.  The third column would be the rollover value.

At present, `numberAsPOSIXct()` uses
```R
t <- as.POSIXct("1999-08-22 00:00:00", tz="UTC") + 86400*7*t[, 1] + t[, 2]
```
(after which leap seconds are added).  In other words, it assumes a rollover of 1.  So, the default for column 3 should be 1.

With this scheme and your data, you would do
```R
numberAsPOSIXct(cbind(2250, 502834.494144, 0), type="gps")
```
(note the case on `type`; it was wrong in the first comment here).

@MatthiasSiewert and @richardsc: does this my proposal okay to you?  Naturally, I'll document it.  Perhaps I'll add an example, too, because I think a lot of users skip to examples when they look at documentation (I know I do).

**Comment by MatthiasSiewert** [comment]
Sounds like a reasonable solution to me.

**Comment by dankelley** [comment]
@MatthiasSiewert since you seem to be online at the moment, I wonder whether you could look at the documentation draft below.  (This is not pushed to github yet.). 

---

**Paragraph on "gps" style**

"gps" handles the GPS convention. For this, t is a matrix containing either 2 or 3 columns. In the 2-column case, the first column is the number of weeks after 1999-08-22, and the second column is the number of elapsed seconds in that week. In the 3-column mode, allowances can be made for the problem that GPS week data are stored in a 10-bit format that rolls over (resets to 0) every 1024 weeks. The initial sequence of times had week defined with respect to 1980-01-06, and if this is known to be the situation for a given dataset, the third column must be set to 0. Setting the third column to 1 (the default) indicates that time is referenced to 1999-08-22. This pattern continues, with e.g. a value of 2 being appropriate for a reference data of 2019-04-07 and so forth. Once a time is computed with this scheme, the number of leap seconds between 1980 and that time is computed by reference to the built-in `.leap.seconds` database, and the return value is adjusted accordingly.

NOTE: your computation did not account for leap seconds.  I could add an option called maybe `leap` or something, to indicate whether to account for leap seconds.  But the reason I've not done so is that I am really not too sure whether leap seconds are incorporated into the other styles of time specifications, and I don't want to get into a tangle of having to update all the styles (possibly breaking existing user code).  It's pretty easy to undo the leap second addition: just find the leap seconds using the built-in vector named `.leap.seconds`, convert to times, remove anything before 1980 and after the time computed by `numberAsPOSIXct()`, and then subtract that number of seconds.

To @richardsc you might want to weigh in on the leap-second issue.  If you're going to be at Dal tomorrow, we could talk about it.

---

**Examples section**

```R
# Default, unix
numberAsPOSIXct(0)
# Matlab
numberAsPOSIXct(1, type="matlab")
# GPS with default week rollover (Canada Day, year 2010)
numberAsPOSIXct(cbind(566, 345615), type="gps")
# GPS with week rollover 0, meaning data referenced to 1980-01-06
# 2023-02-24 19:40:16.494 UTC
numberAsPOSIXct(cbind(2250, 502834.494144, 0), type="gps")
# yearday
numberAsPOSIXct(cbind(2013, 1), type="yearday") # start of 2013
# Epic time, one hour into Canada Day of year 2018. In computing the
# Julian day, note that this starts at noon.
jd <- julianDay(as.POSIXct("2018-07-01 12:00:00", tz="UTC"))
numberAsPOSIXct(cbind(jd, 1e3 * 1 * 3600), type="epic", tz="UTC")

[Package oce version 1.8-0 [Index](http://127.0.0.1:25099/help/library/oce/html/00Index.html)]
```

**Comment by dankelley** [comment]
@MatthiasSiewert and @richardsc I just edited my previous comment because I was mixed up on leap seconds.

Further to that, I wonder if I should maybe add something like the below to the examples in the docs for this function.  It tells you how to know that 18 seconds had been added to the time (to account for the fact that the satellites do not "know" about leap seconds).  Do you two think that adding something like this would be useful?  (Clark, we can talk about this tomorrow if you'll be at Dal then.)

```R
> ls <- as.POSIXct(.leap.seconds, tz="UTC")
> t <- numberAsPOSIXct(cbind(2250, 502834.494144, 0), type="gps")
> sum(as.POSIXct("1980-01-01",tz="UTC") < ls & ls < t)
[1] 18
```

**Comment by MatthiasSiewert** [comment]
@dankelley
This was the only package in R that I could find that addresses GPS time properly. So additional information would be useful. Both in the help and the documentation.  
`
# GPS with week rollover 0, meaning data referenced to 1980-01-06, including automatic adjustment for leap seconds. 
# 2023-02-24 19:40:16.494 UTC
numberAsPOSIXct(cbind(2250, 502834.494144, 0), type="gps")
`

**Comment by dankelley** [comment]
Actually, I need to think more about leap seconds.  The below confuses me.  I'm recording it here not because I am framing any ideas on it, but instead just to have the record for more thought on this matter.

```R
> tail(.leap.seconds, 2)
[1] "2015-07-01 GMT" "2017-01-01 GMT"
```
Note that this year has a leap second in the middle.  So, let's construct the year interval,
```R
> A <- as.POSIXct("2015-01-01",tz="UTC")
> B <- as.POSIXct("2016-01-01",tz="UTC")
```
and find the difference, modulo the number of seconds in a day
```R
> (as.numeric(B)-as.numeric(A))/86400 - 365
[1] 0
```

That's weird. I was expecting a non-zero result.  So, let's try a year that does *not* contain a leap second.
```R
> AA <- as.POSIXct("2010-01-01",tz="UTC")
> BB <- as.POSIXct("2011-01-01",tz="UTC")
> (as.numeric(BB)-as.numeric(AA))/86400 - 365
[1] 0
```

How can this be?  Indeed,
```R
> (B-A) == (BB-AA)
[1] TRUE
```
reveals that these two years hold the same number of seconds.

**Comment by dankelley** [comment]
@MatthiasSiewert re https://github.com/dankelley/oce/issues/2077#issuecomment-1510383922 are you quoting that line to suggest an alteration?  PS. as you can see at the comment just above the present one, I'm kind of going around in circles as to exactly how to handle leap seconds.  I think `as.numeric()` is compensating for them.  

And, I think, doing numerical operations on POSIXt objects (e.g. `as.POSIXct(...) + 1`) also compensates for leap seconds.

I may see @richardsc this week, and we can perhaps hash this out some more about leap seconds.  In the meantime, @MatthiasSiewert, below is the present help for the function (not on github yet).  I've reworked some of the sentence in an attempt to be a bit clearer.  Also, I've said explicitly that leap seconds are *subtracted*.  And this is yet another odd thing: so far, all leap seconds have been positive, but I assume there is a chance that (if they are retained at all) we might get negative ones sometime.  If so, then R will need to change how `.leap.seconds` is defined because presently it consists of dates, with no indication of whether it is +1 or -1 second.

---

"gps" handles the GPS convention. For this, t is a matrix containing either 2 or 3 columns. In the 2-column case, the first column is the number of weeks after 1999-08-22, and the second column is the number of elapsed seconds in that week. In the 3-column mode, allowances can be made for the problem that GPS week data are stored in a 10-bit format that rolls over (resets to 0) every 1024 weeks. The initial sequence of times had week defined with respect to 1980-01-06, and if this is known to be the situation for a given dataset, the third column must be set to 0. Setting the third column to 1 (the default) indicates that time is referenced to 1999-08-22. This pattern continues. For example, a 2 should be used if the reference date is 2019-04-07, etc. For both the 2-column and 3-column cases, a final correction is done to account for the fact that GPS satellites do not count leap seconds. This is done by consulting the built-in [.leap.seconds](http://127.0.0.1:25099/help/library/oce/help/.leap.seconds) database to find the number of leap seconds between 1980 and the time computed thus far. After subtracting this number of seconds, a final result is returned.

**Comment by dankelley** [comment]
Further to my discussion two comments above at https://github.com/dankelley/oce/issues/2077#issuecomment-1510384113, I see the below in the `?POSIXt` help; note the final phrase (italics mine).

---

Unfortunately, the conversion is complicated by the operation of time zones and leap seconds (according to this version of R's data, 27 days have been 86401 seconds long so far, the last being on (actually, immediately before) 2017-01-01: the times of the extra seconds are in the object .leap.seconds). The details of this are entrusted to the OS services where possible. It seems that some rare systems used to use leap seconds, but all known current platforms ignore them (as required by POSIX). This is detected and corrected for at build time, *so "POSIXct" times used by R do not include leap seconds on any platform*.

**Comment by dankelley** [comment]
@MatthiasSiewert I think I've solved this now, in the "develop" branch (commit note below).  Also, on the leap-second part, see #2078 for details.

There is an issue that might deserve more discussion -- the default for the new third column is to assume a rollover of 1.  That will be a problem for the earlier 19.7 years (rollover 0), and for the 19.7 year period that we are in now (rollover 2).  But if someone is working with old data, that would be wrong.  I chose to keep the old rollover (=1) as the default, because otherwise old code would produce different results on a given data value.  I would appreciate your thoughts, and those of @richardsc, on this matter of default rollover.

Luckily, as I understand it from https://en.wikipedia.org/wiki/GPS_week_number_rollover, newer satellites use 13 bits, which solves the problem for quite a while!

If you think that these changes address the issue you raised, please consider closing this issue.  (That's the system for oce: reporters close issues, not developers.)  But if you think some things still need work, please leave this open and add new comments, or close it and make a new issue with another title.  I'm hoping to get this resolved so I can merge it from "develop" to "main", in preparation for a release of "main" to CRAN in a few weeks.  Thanks a million for this great idea!

Dan.

commit 74cb8cd41d591997ad2c08a31c5cc40f7144298d
Author: dankelley <kelley.dan@gmail.com>
Date:   Mon Apr 17 14:53:24 2023 -0300

    improve numberAsPOSIXct() for type="gps"
    
    1. The user can now supply a 3rd column, for the week-rollover value.
    2. The `leap` argument has been added.
    3. The tests are extended and clarified.
    4. I have a background document in the oce_issues repo, directory
       20xx/2078, about leap seconds.

**Comment by dankelley** [comment]
My most recent update to "develop" has the documentation on the `t` parameter as follows.  I hope this is a good solution.

<img width="1201" alt="Screenshot 2023-04-19 at 4 59 51 PM" src="https://user-images.githubusercontent.com/99469/233188047-0e9ef22a-f21b-4c67-bf24-a3b4ce652ee5.png">

**Comment by dankelley** [comment]
This issue was closed by the developer, because the following conditions were met:
1. a solution has been implemennted
2. new tests were added to check the solution
3. issue discussion seems to have ceased

Of course, if the reporter wants to reopen the issue, that's perfectly fine! The point here is just to avoid having issues in the developers' "to do" list, when they are probably done.

PS. this is a standardized reply (AKA a 'saved reply' in github notation).
