### ISSUE TITLE
Typo in initializeFlagScheme() help page

### ISSUE THREAD

**Issue by avictor88** [dankelley/oce#2082]
> This function **stores add** an item named flagScheme to the metadata slot of an object inheriting from [oce](http://127.0.0.1:42640/help/library/oce/help/oce-class). This is a list containing two items: name and mapping, as provided in the function arguments.

**Comment by dankelley** [comment]
FIxed in "develop" branch, commit c4111b2eecc82f2dc290fb62f3cbe9cbb1cbf49e.

Thanks!

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list for the project.

*Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
This issue was closed by the developer who solved the problem, because the following conditions were met:
1. the solution is simple
2. new tests were added to ensure that the solution works
3. the reporter is in frequent contact with the developer

Of course, if the reporter wants to reopen the issue, that's perfectly fine! The point here is just to avoid having issues in the developers' "to do" list, when they are probably done.
