### ISSUE TITLE
Data Loading Error

### ISSUE THREAD

**Issue by benlafreniere** [dankelley/oce#2084]
Hello, I am having an issue resolving a repeating error code when attempting to read a file using the oce package. Below is the code chunk and error output:

data <- read.oce("FILENAME.cnv")

Error in swSigmaTheta(median(res[["salinity"]]), median(res[["temperature"]]),  : 
  must provide temperature
In addition: Warning message:
In read.ctd.sbe(file, encoding = encoding, processingLog = processingLog,  :
  cannot find temperature; try using the 'columns' argument

R version 4.2.2

**Comment by dankelley** [comment]
The file does not store temperature.  It only stores potential temperature.  You can see that by looking at line 70 of the file, or by doing
```R
read.oce(FILENAME, debug=2)
```
which shows more debugging info, including
```
    About to read .cnv data with these names: c("depth","theta","salinity","pH","oxygen","oxygen2","fluorescence","turbidity","scan","descentRate","timeM","conductivity","density","flag")
```

So, now the question is what should be done.  If you have access to the original files, you could use the SBE software to make it save actual temperature, not theta.

I suppose `oce` could try to infer temperature from theta.  I see that it has depth and salinity, so oce could assume something about how theta was computed (likely using UNESCO formulae, but that's just a guess that would need verification by reading the SBE documentation for the `potemp090C` item).  Once that is known, actual (in-situ) temperature could be computed.  I don't know of a formula, but something like `uniroot()` could be used to infer it.

@richardsc what do you think of modifying `read.ctd()` this way?  We've never heard of this situation in about 15 years of looking at cnv files.  Perhaps the best answer is "regenerate your files".

**Comment by dankelley** [comment]
The snapshot below shows a SBE document in my possession.  This is the single occurrence of the string `potemp090C` in the file.

My guess is that the UNESCO formula is used.  I don't think there is any real way to know for sure, except by loading a ctd hex file and making the software output both in-situ temperature and this potential temperature, and then checking using `oce::swTheta()` etc.  (Maybe @richardsc has some other ideas for how we can determine the formula SBE is using.)


<img width="809" alt="Screenshot 2023-05-12 at 2 39 30 PM" src="https://github.com/dankelley/oce/assets/99469/6b373589-352b-4c4a-808c-28018c7eeeb7">

**Comment by richardsc** [comment]
I'm going to be a party pooper here as it's my opinion that this isn't an oce issue but rather a data pipeline issue. A CTD isn't a CTD if it doesn't have *in situ* temperature -- just like practical salinity is the only salinity that should be archived, in situ temperature is required for all oceanographic work.

My vote is that `oce` should NOT be modified to accomodate files like this. 

For @benlafreniere there are a couple solutions:

1. Reprocess your raw HEX files but make sure you specify temperature (ITS-90) as an output
2. Use the "columns" arg as the oce error suggests to assign the "theta" column to "temperature", then recalculate the temperature and replace (as Dan suggests, this is likely the UNESCO formula, and would have to be done with a uniroot or something similar).

One point that might be worth discussion is the error is because oce is trying to calculate potential density:
```
Error in swSigmaTheta(median(res[["salinity"]]), median(res[["temperature"]]), :
```
Is that really necessary? If it isn't, then presumably removing that line will cause the file to be read successfully, but with theta inside it instead of temperature (which I still think is bad).

**Comment by richardsc** [comment]
One pathway to calculate T90 from PT (assume that it must be referenced to p=0) could be do use the `gsw` package, e.g.

`gsw_CT_from_pt` -> `gsw_t_from_CT`

but of course that also requires using `gsw_SA_from_SP` to get absolute salinity (which needs longitude and latitude). But it should work, I think

**Comment by dankelley** [comment]
It is calling `swSigmaTheta()` so it can use the hydrostatic equation to infer pressure from depth.

That's a second thing that is problematic about this CNV file: it has depth instead of pressure.  As with the theta, I suppose we could try to work around that.  But I don't really think handling such an odd circumstance is something that oce ought to be handling.  The thing is that every change to long-standing code can invite new problems.

So, @benlafreniere, if you're able to generate new CNV files, please be sure to:

1. output pressure, not depth
2. output in-situ temperature, not potential temperature

@richardsc to save Ben some time, do you notice anything else in the data list (see below) that ought to be changed?

```
# name 0 = depSM: Depth [salt water, m], lat = 43.50
# name 1 = potemp090C: Potential Temperature [ITS-90, deg C]
# name 2 = sal00: Salinity, Practical [PSU]
# name 3 = ph: pH
# name 4 = oxsatMg/L: Oxygen Saturation, Weiss [mg/l]
# name 5 = sbeox0Mg/L: Oxygen, SBE 43 [mg/l]
# name 6 = flECO-AFL: Fluorescence, WET Labs ECO-AFL/FL [mg/m^3]
# name 7 = turbWETntu0: Turbidity, WET Labs ECO [NTU]
# name 8 = scan: Scan Count
# name 9 = dz/dtM: Descent Rate [m/s]
# name 10 = timeM: Time, Elapsed [minutes]
# name 11 = c0mS/cm: Conductivity [mS/cm]
# name 12 = density00: Density [density, kg/m^3]
# name 13 = flag: flag
```

**Comment by richardsc** [comment]
Ah, I see. It needs density because it has to also covert depth to pressure. 

I agree with @dankelley -- best to reprocess so the file includes in situ temperature (ITS-90), pressure (dbar), and practical salinity (and conductivity, to be complete).

**Comment by benlafreniere** [comment]
I'll be able to reprocess the data, hopefully that does the trick.

Thanks,


Ben LaFreniere  (he/him)


Marine Resource Specialist II

Maine Department of Marine Resources

Phone: (207) 350-6728


________________________________

**Comment by benlafreniere** [comment]
I'll reprocess the data, and hopefully that does the trick.

**Comment by dankelley** [comment]
Good.  I can't quite remember how to make the `columns`method work (I wrote it but a very long time ago and I don't recall ever using it), but here's a sleazy trick that lets you read the potential temperature as though it were temperature...

```R
library(oce)
d<-read.ctd.sbe(pipe("cat ~/SP23_Region1003ba.cnv|sed -e 's/potemp090C/t090C/'"))
```

Of course, this requires a unix system for `cat` and `sed` to work.  After doing this, you'd then need to ensure that the file has lat and lon, then convert things as @richardsc suggests at https://github.com/dankelley/oce/issues/2084#issuecomment-1546088082

**Comment by dankelley** [comment]
To the original reporter: have you made any progress on this?  Do you need any more help?  In the oce project, we like to use open issues as a sort of "to do" list, so we'd like to know if the issue ought to remain open.

PS. this is a standardized 'saved reply'.
