### ISSUE TITLE
Error using ctdFindProfilesRBR()

### ISSUE THREAD

**Issue by avictor88** [dankelley/oce#2087]
I've been trying to play around with ctdFindProfiles() and ctdFindProfilesRBR(), but I keep receiving an error message when trying to use the ctdFindProfilesRBR() function.

```
library(oce)
rsk <- read.rsk("~/Desktop/2023_03_17.rsk")
ctd <- as.ctd(rsk)
profiles <- ctdFindProfilesRBR(ctd)
```

**Comment by dankelley** [comment]
Hi.  Can you include the error that you receive?

**Comment by dankelley** [comment]
Thanks for this contribution to oce!!

-- Dan.

**Comment by avictor88** [comment]
Hi, I'm getting this as the error: 
Error in seq.int(parameters[1], parameters[2]) : 
  'to' must be a finite number

**Comment by dankelley** [comment]
Thanks.  FYI, the first thing to do when an error occurs is to turn debugging on.  That makes a trace of the flow within the code.  I see as follows.  Note NA values that are shown near the end.  My next step will be to go into the code where these things are printed, and insert a `browser()` call, to let me go inside the code.  Sometime when we're both in the office a the same time, I can teach you these tricks.

```R
> profiles <- ctdFindProfilesRBR(dd, debug=3)
  ctdFindProfilesRBR(x, direction=descending, arr.ind=FALSE, debug=3) {
    originally, startTime[1:18]: 2023-03-17 15:49:57, 2023-03-17 15:54:27.688, ..., 2023-03-17 19:39:54.063, 2023-03-17 19:43:34.813
    originally, endTime[1:18]: 2023-03-17 15:53:31.688, 2023-03-17 15:56:24.75, ..., 2023-03-17 19:42:19.625, 2023-03-17 19:45:50.063
    keeping 18 of 18 start/end pairs
    after trimming, startTime[1:18]: 2023-03-17 15:49:57, 2023-03-17 15:54:27.688, ..., 2023-03-17 19:39:54.063, 2023-03-17 19:43:34.813
    after trimming, endTime[1:18]: 2023-03-17 15:53:31.688, 2023-03-17 15:56:24.75, ..., 2023-03-17 19:42:19.625, 2023-03-17 19:45:50.063
    start[1:18]: 458,  NA, ..., 122932, 126464
    end[1:18]:   NA, 6662, ..., 125261, 128628
Error in seq.int(parameters[1], parameters[2]) : 
  'to' must be a finite number
```

**Comment by avictor88** [comment]
Okay, that would be great, thanks for the tip!

**Comment by dankelley** [comment]
I'll record a lot of steps here, to help you learn how to debug things.  Github will send you emails when I do so, but you can ignore them until next week.

I inserted a `browser()` line and ran the code.  I got as in the snapshot.  Notice that lots of the `start` and `end` values are coming out as NAs.  That's telling me that these are not being computed correctly.  (They are supposed to be the indices of data at the starts and ends of profiles.  Those indices are, of course, integers, and cannot be NA.)

<img width="756" alt="Screenshot 2023-05-19 at 5 03 34 PM" src="https://github.com/dankelley/oce/assets/99469/195bc9b0-480c-428a-a70b-613fcf59b710">

**Comment by dankelley** [comment]
I'll record some steps here, as a way to teach you methods.  Github will send emails for each comment I make, but please just ignore them until next week.

In the snapshot below, you can see that I have inserted the `browser()` and that the code has stopped running there (top panel).  In the bottom panel I am "in" the code, and so I can type variable names to see the values. Note the NA values, which are clearly wrong because `start` and `end` are supposed to be indices for data at the starts and ends of the profiles.

<img width="756" alt="Screenshot 2023-05-19 at 5 03 34 PM" src="https://github.com/dankelley/oce/assets/99469/b1b613ec-ea08-46af-b454-b5ac2c624a42">

**Comment by dankelley** [comment]
And here I am in the editor, looking a few lines above.  I am using vim here, not RStudio.  I seldom use RStudio for working through code because vim lets me do things like split the window, which I've done here.  The bottom panel is what I showed in the previous comment, at the spot where I inserted the `browser()` line.  The top panel shows just a few lines above, where `start` and `end` are being computed.

<img width="1004" alt="Screenshot 2023-05-19 at 5 10 01 PM" src="https://github.com/dankelley/oce/assets/99469/c7a98dbd-33cd-4264-b9fc-44dc2cef2f50">

**Comment by dankelley** [comment]
Back to the browser now.  I'm looking at `startTime` and `endTime`, and also at `keep`. None of these is NA.  Therefore the problem must be in lines 2297 and 2298, where I'm finding which times `t` match up with `time`.  But the `t` is the parameter to the anonymous function being called by `sapply()`. So what that tells me is that some of the `startTime` and `endTime` values are *not* identical to values in `time`.  That is what I need to check next.

(PS to @cameronrichrdson: I'm tagging you because you might find my series of comments to be useful, in learning how to debug things.  I suggest you read the thread from the beginning, when you return to work next week.)

<img width="662" alt="Screenshot 2023-05-19 at 5 12 36 PM" src="https://github.com/dankelley/oce/assets/99469/b42d48c2-1033-4bfd-85eb-528ea8e8f1f1">

**Comment by dankelley** [comment]
Notice, a few comments back, that the first `end` value is NA.  So we should look at that.  Notice that the times *look* the same, in my first test, but when I subtract, they are *very slightly* different (0.0999 millisecond).

I don't know how this came to be, but I think what I ought to do is to change my test for equality to a test that simply finds the nearest match.  (Perhaps @richardsc can weigh in on any ideas of why the times could be slightly different.  I'm guessing it's a rounding thing.

```R
browse[1]> which.min(abs(time-endTime[1]))
[1] 3893
Browse[1]> time[3893]
[1] "2023-03-17 15:53:31.687 UTC"
Browse[1]> endTime[1]
[1] "2023-03-17 15:53:31.687 UTC"
Browse[1]> time[3893]-endTime[1]
Time difference of -0.0009994507 secs
```

**Comment by dankelley** [comment]
Down the rabbithole a bit more/. Notice that they agree for 3 digits and then disagree.  I don't have a theory on why this happens 3/18 times for `start` (that's the fraction that are NA) and that doesn't seem like a rounding error to me.  

I don't intend to explore this rabbithole further.  I'm going to just go for the nearest match, not for equality.

```R
Browse[1]> options(digits=15)
Browse[1]> as.integer(as.numeric(endTime[1])) - as.numeric(endTime[1])
[1] -0.687999725341797
Browse[1]> as.integer(as.numeric(time[3893])) - as.numeric(time[3893])
[1] -0.687000274658203
```

**Comment by dankelley** [comment]
Below is how I modified the code.  The change is in line 2297 and the 10 lines after that.  I used some more indentation to try to show the meaning more clearly.

<img width="1004" alt="Screenshot 2023-05-19 at 5 30 14 PM" src="https://github.com/dankelley/oce/assets/99469/a326b1e2-27db-4d06-bb97-0b915ef37f04">

**Comment by dankelley** [comment]
And here is what I get for the debugging output now.  This seems right to me.  Where the old values were non-NA, I get the same.  And now the NA ones are filled in.  (To be honest, I only checked a few of the non-NA ones.  Maybe either @avictor88 or someone else can check more.)

```
    start    end
1     458   3893
2    4789   6662
3    7445   9019
4   10344  14796
5   17170  21189
6   23491  27604
7   30566  36000
8   38171  41851
9   43986  47247
10  49674  55498
11  57711  60424
12  62398  65599
13 109104 111989
14 112802 113938
15 114711 115841
16 117409 121518
17 122932 125261
18 126464 128628
```

**Comment by dankelley** [comment]
I have it working now (and pushed to GH as "develop" commit d450cd2671e263d259e6391427c827d13ff61151) but when I do
```R
dp <- ctdFindProfilesRBR(d)
plot(dp[[1]])
```
I get an error because dp[[1]] (that is, the first profile) lacks longitude and latitude information.  My default system is to use the new equation of state, which requires lon and lat to get SA and CT.  But I can make it plot by doing
```R
options(oceEOS="unesco")
```
and then doing as above.

I will make a new issue about the problem with lon and lat.

When @avictor88 gets a chance, next week, it might make sense to close the present issue (if there is agreement that I have solved it).

**Comment by richardsc** [comment]
@avictor88 -- we looked at this yesterday and I think concluded that it was working for your data. Can you close this issue if all seems good? Thanks!
