### ISSUE TITLE
Correct ADCP velocity data (no Bottom track) using ship's cog and speed

### ISSUE THREAD

**Issue by koRneel82** [dankelley/oce#2089]
Hi, 
My pole-mounted ADCP data does not have the real water current data, as the sailing of the ship is included.
There was no Bottom track option.

Is there a way that I can obtain the real water current data, using the navigation log (course over ground and speed)?

Thanks in advance

**Comment by dankelley** [comment]
Depending on the veracity of the ship's log, this ought to be possible, at least partly.  I'd try using `approx()` on that log, like
```R
adpTime <- adp[["time"]]
shipUInterpolated <- approx(shipTime, shipU, adpTime)
```
and then subtract, etc.

However, my guess is that the ship is going a lot faster than the water, so the ship's velocity will need to be known very accurately or the results will be very contaminated by errors in the ship's velocity.

I don't know much about ship's logs, but if the systems are like those in the phones in all our pockets, I imagine GPS signals are combined with signals from inertial sensors (since the GPS does not update every sub-second).  This can be a challenge to do well.

As to the feasibility of all this, I'd like to know what @richardsc thinks, since he has more experience.  I imagine ship's logs continually get better, but the design goal is not really to do this sort of thing.  If I recall correctly, @richardsc found that things go off the rails if the ship turns, as might be the case in a coastal.

**Comment by richardsc** [comment]
As @dankelley pointed out, in order to remove the ship velocity you need to have a good estimate of what it is. The best way to do this (when you can see the bottom) is with the bottom track, as it avoids interpolating data streams. Failing that, you can use the ship heading/speed/location information to contruct a velocity that can be substracted.

Importantly, you need to know the heading of the ship (and ADCP), rather than just course over ground. As Dan recalls, I have experience trying to figure out how to correct ship mounted data in a similar situation where heading (and bottom track) were not available, and it was clear that whenever the COG was different from the heading (during turns and when "crabbing across currents") that it was very difficult to accurately remove the ship velocity.

If you want to share what you have (by email to clark.richards@gmail.com) I'd be happy to take a look at what you've got and what your options are.

**Comment by dankelley** [comment]
To the original reporter: have you made any progress on this?  Do you need any more help?  In the oce project, we like to use open issues as a sort of "to do" list, so we'd like to know if the issue ought to remain open.

PS. this is a standardized 'saved reply'.

**Comment by richardsc** [comment]
We've moved discussion of this to email, since it's not really an oce issue and is really more of a data processing thing. I'd say that it's safe to close it here if @koRneel82 agrees.

To @koRneel82 -- I've been poking at your data and will email you with an update soon.

**Comment by koRneel82** [comment]
Yes, safe to close. Thanks.
