### ISSUE TITLE
plot,cm-method doesn't pass `xlim` through to oce.plot.ts()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2121]
As in the title. This isn't a huge deal, but is a bit inconsistent with other `plot.*()` methods:

``` r
library(oce)
#> Loading required package: gsw
data(cm)
focus <- structure(c(1214442262.90556, 1214450822.70713), tzone = "UTC", class = c("POSIXct", "POSIXt"))
plot(cm, which=1, xlim=focus)
abline(v=focus)
```

![](https://i.imgur.com/CIFaBtB.png)

<sup>Created on 2023-06-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
I'm looking at this now.  I'll also make it obey `xaxs` and `yaxs`, which I use quite a lot.  So far, I am only doing this for time-series type plots.

A complication in this is that `which` can be a vector of length exceeding 1.  That was a design mistake, because it complicates an awful lot of code.  (Maybe I want 2 different panels, with different line widths in each, different symbols in each, and on and on.). But we cannot go back in time and drop this multi-valued possibility for `which`.

**Comment by dankelley** [comment]
I think it's working now in "develop" commit fa38280408813e2577a97f8f7d432df934e7cd12.  I only did this for plots using `oce.plot.ts()`.  I can look at other plot types next week.

``` r
library(oce)
#> Loading required package: gsw
data(cm)
focus <- structure(c(1214442262.90556, 1214450822.70713), tzone = "UTC", class = c("POSIXct", "POSIXt"))
par(mfrow=c(3, 1))
plot(cm, which=1)
abline(v=focus)
plot(cm, which=1, xlim=focus)
abline(v=focus)
plot(cm, which=1, xlim=focus, xaxs="i")
abline(v=focus)
```

![](https://i.imgur.com/GDSkQYX.png)

<sup>Created on 2023-06-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment]
Thanks! I was going to try going into the code when I got a chance to do the same, but wanted to be careful as there are quite a few `oce.plot.ts()` calls in there and didn't want to mess things up inadvertently.

Looks good!
