### ISSUE TITLE
Don't add xlab in imagep plot 

### ISSUE THREAD

**Issue by RenCissy** [dankelley/oce#2162]
I use imagep to plot adp data, I hope that add a xlab such as xlab="hour/Date", but it cann't  show in the plot result.

**Comment by RenCissy** [comment]
When I add a xlab in plot(adp,..., xlab="hour/Date"), there a error is following: 
Error in imagep(x = tt, y = x[["distance", j]], z, zlim = zlim, flipy = flipy,  : 
  formal argument "xlab" matched by multiple actual arguments

**Comment by dankelley** [comment]
Here is what I mean.  Note that I am using a `reprex::reprex()` to construct this.  Doing so is a great help to readers, because it means that the code and results are self-contained.  Note that this is for a *single* panel.  The method will not work for multiple panels.


``` r
library(oce)
#> Loading required package: gsw
data(adp)
plot(adp, which=1)
mtext(side=1, "User-Specified xlab", line=2)
```

![](https://i.imgur.com/2Gs11PN.png)

<sup>Created on 2023-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
I don't see any harm in changing `plot,adp-method()` to accept `xlab` directly, so I'll do that later today.

**Comment by dankelley** [comment]
@richardsc if you use the latest commit (the one noted above), then your `imagep()` example will get the label.

**Comment by dankelley** [comment]
This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

PS.  This is a standardized reply.
