### ISSUE TITLE
Aquadopp profiler fields being misread

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2165]
There were some changes made to the aquadopp profiler code recently based on a file that was having issues being read due to some weird characters in the serial number field (e.g. commit 165cb1d).

Upon further look at the data from this file, including comparing against the fields output using Nortek software, it looks like the data reading issues are more complex. Below are two plots of the 3 components of velocity: the first read using oce, and the second read from the binary to ascii conversion using Nortek software. The latter looks sensible -- especially compared to the former, which if I had to guess appears to be starting the reading at the wrong location in the file. Note how the hard boundary seems to be that oce is reading the last half of the first velocity component (after skipping the first half), then the first half of the second component.

![01_aqd_2](https://github.com/dankelley/oce/assets/233584/65645fc0-1483-4208-818c-9b031e7ed377)
![02_aqd_2](https://github.com/dankelley/oce/assets/233584/6b57f7b2-822c-4966-b6e9-eceac8953a89)

Code and data files can be found here:
[arcticbay_aquadopp.zip](https://github.com/dankelley/oce/files/13074093/arcticbay_aquadopp.zip)

**Comment by dankelley** [comment]
When I use `debug=3` in the read call, I get as below.  Does any of this look crazy to you, Clark?
```
    read.adp.nortek(...,from=1,to=NA...)
    fileSize=1017046
    decodeHeaderNortek(buf, type="aquadoppHR", ...) {
      buf starts:a50518004151443135323339800a342e3234343c
      
    
HARDWARE CONFIGURATION
      hardware$size=24
      hardware$serialNumber: AQD15239
      hardware$config:343c
      hardware$frequency:65535
      hardware$picVersion=0
      hardware$hwRevision=4
      hardware$recSize=-5168
      hardware$velocityRange=20
      hardware$fw.version=
      
    HEAD CONFIGURATION
      head$size=112
      head$configPressureSensor=TRUE
      head$configMagnetometerSensor=TRUE
      head$configTiltSensor=TRUE
      head$configTiltSensorOrientation=downward
      head$frequency=1000kHz
      head$headType=0
      head$headSerialNumber=AQP 9686
      head$beamAngles=2525250(deg)
      head$transformationMatrix
            1.5773926     -0.7890625     -0.7890625
             0.000000      -1.366211       1.366211
            0.3676758      0.3676758      0.3676758
      head$numberOfBeams=3
      
    USER CONFIGURATION
      user$transmitPulseLength=92
      user$T2=68(blanking distance, in counts)
      user$receiveLength=T3=24counts
       ABOVE FROM buf[o+9]=0x18 and buf[o+10]=0x32
      user$timeBetweenPings=1475in counts
      user$timeBetweenBurstSequences=512in counts
      user$numberOfBeamSequencesPerBurst=7in counts
      user$averagingInterval=60in seconds
      user$numberOfBeams=3
      user$timCtrlReg=2080
      user$measurementInterval=900
      user$deploymentName=AB19
      user$comments=Arctic Bay 2019 Field Site
      user$mode: 01000000000000000000000000000000
      user$velocityScale: 0.001
      user$originalCoordinate: xyz
      user$numberOfCells: 25
      user$hBinLength: 5908 (p31 of System Integrator Guide)
      cellSize=0.2823644m (FIXME: using formula from unknown source)
      measurementInterval=900
      blankingDistance=0.5496261; user$T1=and user$T2=68
      swVersion=1.3708
      salinity=31.5
    profile data at buf[785] et seq.
    matching bytes: 0xa5 0x21 0x81
    profilesInFile=3939
    ORIG measurement.deltat=900
    NEW  measurementDeltat=899.7715
    profileStart[1:10] after indexing:785  1043  1301  1559  1817  2075  2333  2591  2849  3107  
    profilesToRead=3939
    numberOfCells=25
    numberOfBeams=3
null device 
          1 
```

**Comment by richardsc** [comment]
Oh, another thing is that it might be interpreting the file as an "aquadoppHR" rather than just a regular "aquadopp profiler"?

```
decodeHeaderNortek(buf, type="aquadoppHR", ...) {
```

**Comment by dankelley** [comment]
Good thought -- that type error might be relevant.  I don't remember what is different in the code, but maybe the type is not being passed with this call.  Note that, as below, oce knows that this is not HR.
```R
> print(oceMagic(f))
[1] "adp/nortek/aquadoppProfiler"
```

**Comment by richardsc** [comment]
Some other weird things in the `debug` info:

```
      hardware$frequency:65535
      hardware$picVersion=0
      hardware$hwRevision=4
      hardware$recSize=-5168
```
Frequency is 1000, but that does seem to get stored ok e.g. if I do `d[["frequency"]]` after reading.

recSize is clearly wrong, though:
```
> d[['recSize']]
[1] -5168
```

**Comment by richardsc** [comment]
For the `cellSize` thing, I see the warning about "formula from unknown source", and since it's clearly wrong we'll need to figure out what the *correct* source is.

I found the below matlab code on the Nortek site -- going to see if there's anything useful in there ...

[bin2mat.zip](https://github.com/dankelley/oce/files/13074688/bin2mat.zip)

**Comment by richardsc** [comment]
Nevermind, the `bin2mat` isn't much help because it looks like it's some kind of compiled code rather than an actual script. 😢

**Comment by dankelley** [comment]
I made recSize be read as unsigned and now I get as below with test code as below.

The below uses "develop" commit b68157b2343e5fec59caed87678538d6bd10473a.


![01_aqd_dk_1](https://github.com/dankelley/oce/assets/99469/86d57b13-83c8-4a29-99b8-35644ab2c749)

![01_aqd_dk_2](https://github.com/dankelley/oce/assets/99469/972500e5-3945-44f5-bf82-4d9ec3dd1e98)

![01_aqd_dk_3](https://github.com/dankelley/oce/assets/99469/a138b2c8-2785-42a0-ab8d-125bb4e3d708)

<details>

```R
[1] "adp/nortek/aquadoppProfiler"
    oceMagic(file="AB1904.PRF") {
      'file' is a character value
      'file' is a connection
      first line of file: ¥AQD15239
      second line of file: 4.244<ÿÿÐëÿÿÿÿÿÿ3.42¥p? èAQP 9686=`ó`ó$êÜâââéñøÀ3¸n£3ýÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿö-ÉØm*ü©üú0nO­ÿ/ÿÜ{ýÐþÑÿtÿÃÿ,MbîÿU'dy¥\DÃ< `AB190E=5;Í<é<==:=T=n==¡=º=Ó=ì=>>4>K>b>y>>¦>¼>Ò>ç>ü>?&?:?N?b?v???°?Â?Õ?ç?ù?@@.@?@P@`@q@@@¡@°@À@Ï@Þ@í@û@
      first two bytes in file: 0xa5 and 0x05
      This is probably a nortek file of some sort.  Reading further to see for sure ...
      hardware.configuration[1:2]a505(expect 0xa5 0x05)
      head.configuration[1:2]a504(expect 0xa5 0x04)
      user.configuration[1:2]a500(expect 0xa5 0x00)
      nextTwoBytes:0xa50x21(e.g. 0x5 0x12 is adv/nortek/vector)
    } # oceMagic returning adp/nortek/aquadoppProfiler
  read.oce("AB1904.PRF") {
  } # read.oce()
null device 
          1 

```

**Comment by dankelley** [comment]
Yup, recsize was the problem.  Their docs never say the types of things.  The word size might have been a giveaway, but I tend to code this stuff quickly because the common error is to get off by 1 byte, etc and that is discovered by everything being crazy.

This leaves the cellsize problem.   The line declaring the source as unknown is dated as 2012-06-08 and other code (where it is computed) is dated 2012.  I wonder if that indicates where we might have got the info.  Richard maybe? Or Doug?  I don't keep old emails so I cannot search.  The code block before that has a bunch of formulae, and they depend on the type.

We know (I guess) that the type is not HR.  Maybe it's going to the wrong if statement there.  Do you think you could check into that?  I want to do some grading now for a while.

**Comment by richardsc** [comment]
Yes, I'm looking into the `cellSize` thing.

One thing I noticed is that the `read.oce()` dispatch seems to be working, but the (more direct?) `read.adp.nortek()` is still reading it wrong, for some reason.

**Comment by dankelley** [comment]
Right.  I plan to fix that part about the call through `read.adp.nortek()`.  I know what the problem is but the solution might have ripple effects.

**Comment by dankelley** [comment]
Hm.  The code is skipping quite a lot of bytes, but (at least in the new documentation and the one just-previous to it in my listing) the cell size is stored in the skipped bytes.  Whether it always was stored there or not is an interesting question, though.  If it always was, then our code can use those bytes.  If not, e.g. if those bytes used to be of undocumented (and changing) use, then we cannot decode `cellSize` there.

The snapshot shows the existing code, and the new docs.

<img width="796" alt="Screenshot 2023-10-23 at 4 31 29 PM" src="https://github.com/dankelley/oce/assets/99469/49dea824-ce82-490d-a7ab-d68d9870fb55">

**Comment by dankelley** [comment]
I've instrumented the code some more (and pushed to GH) and I see that the formula being used is at

https://github.com/dankelley/oce/blob/7b688ab07107d7ffc59485edf99c3ef7649ef513/R/adp.nortek.R#L284C78-L284C78

and so the question, perhaps for posing on a Nortek forum would be what formula to use for this machine type, based on what bytes.

@richardsc perhaps you have a user account on the nortek forum and can ask.

For what it's worth, the debugged code spits out as below.  The `cellSize` ought to be 100 cm, so something is definitely wrong.
```
    computing user$cellSize and user$blankingDistance for type="aquadoppHR" and frequency=1000
      cellSize=0.2823644m (FIXME: using formula from unknown source)
```

**Comment by richardsc** [comment]
A little digging found me this:

https://github.com/aodn/imos-toolbox/blob/64c0a010a3987e72a0747cc62daf49df412b43d2/Parser/aquadoppProfilerParse.m#L105

which looks like the same formula that we are using. I'll ask Nortek directly or post to the forum.

**Comment by richardsc** [comment]
One of the IMOS functions gave this link: 

http://www.nortek-as.com/en/knowledge-center/forum/hr-profilers/736804717

But it seems to be dead, suggesting that Nortek no longer hosts an online forum?

**Comment by richardsc** [comment]
Correction -- there still seems to be a community forum but it looks like all the old posts have been scrubbed.

https://support.nortekgroup.com/hc/en-us/community/topics

😢

**Comment by richardsc** [comment]
Oh, here's a hint:
```
computing user$cellSize and user$blankingDistance for type="aquadoppHR" and frequency=1000
      cellSize=0.2823644m (FIXME: using formula from unknown source)
```
The instrumentation you put in shows that the "aquadoppHR" block is being triggered, rather than the "aquadoppProfiler" block, which is this one:

https://github.com/dankelley/oce/blob/7b688ab07107d7ffc59485edf99c3ef7649ef513/R/adp.nortek.R#L298

The formulae are different, at least in the scale factor. If I do 0.0478/0.01350 * cellSize=0.2823644m then I *do* get 1m:

```
> 0.0478/0.01350 * 0.2823644
[1] 0.9997791
```

So, we need to check what the instrument type is being detected as, and what conditional blocks (aquadoppHR vs aquadoppProfile) are being triggered as a result.

**Comment by dankelley** [comment]
Oh, this is good news (that the error is just in how `type` was inferred).  I'll update the code and see if it captures `cellSize` correctly.  One trick is that this function (like all oce functions) permits `file` to be a connection, and I don't think `oceMagic()` can handle that case.  (I suspect the connection object holds the filename as a field, though.  `oceMagic()` examines *both* the filename *and* the file contents, to infer the file type.

This business of accepting `file` to be either a character or file-connection value has caused quite a few problems in the past.  But I don't think we have a choice since this has been in oce for well over a decade.

If I see that `oceMagic()` fails on file connections, I will see about fixing that, which would help for all `read` functions.

**Comment by dankelley** [comment]
@richardsc -- over to you now, for a check...

I think `cellSize` is now ok in "develop" branch commit 98f226884a59d1dee900a19e7b64afa86cb3f448.

I made an entry in the `oce-issues` repository to hold test code, at

https://github.com/dankelley/oce-issues/blob/main/21xx/2165/2165a.R

This code requires the data file to be in a directory called `~/Downloads/arcticbay_aquadopp`, so it is not usable by folks other than you and me.  (It is not in the repo for reasons of privacy and space usage.)

Actually, this file won't likely be usable by me, in a few months, because I tend to remove files I'm not actively using.  Arguably, we could put this in the `oce` repo as a private file, but 1Mb is pretty big for a file in a repo, and it would be better to have a test file that is maybe 1/10 that size (if you're planning a test).

The test code reports the `cellSize` as 0.9997793, which perhaps for a 2-byte number going through a funky formula is as close to 1m as we can get.

Below is one of the images that the test code makes.  Any other problems with it?  (I didn't bother looking at the y axis since I know you will).

![2165a_2](https://github.com/dankelley/oce/assets/99469/a9018cde-966f-4686-9e4b-df8eb47c99e3)

**Comment by richardsc** [comment]
Thanks @dankelley -- this is looking much better now. I'm still doing some testing (will have the unit in the Aquatron next week), so I'm going to leave this open for now.

In the meantime, I got a reply from Nortek support, which we can use to update the formulae in the package at least:

```
Took a bit of digging to figure out why the documentation disappeared, but from what I can find it's due to the fact that the forum post oversimplified by referring to factors as opposed to the actual equations:

Blanking Distance:
BD = T2 * 100 * (750/32768) - T1 * 100 * ((750/Frequency)*16)

Cell size:
CS = (BinLength/256)*(750*17*15/(Frequency_in_kHz*4))*cos(25)

These two can be used to pull the respective variables out of the binary data if necessary, though in general the easiest way is to record what configuration was used in the first place! I will bring this up with the rest of the support team and possibly put together an FAQ so this is documented publicly somewhere, as you're correct that it isn't in any of the manuals or other documentation at all.
```

**Comment by dankelley** [comment]
Thanks.  I'll add this in sometime this week, in both code in docs.  In the latter, I will cite it as "Nortek support pers comm" or similar.  

We could use formulae for each instrument type separately, actually.  It would sure be nice if Nortek would document this because I never trust a pers-comm in a paper let alone in software.

**Comment by dankelley** [comment]
Hm, these formulae are quite different from what we have now.  The snapshot shows this.  The top window is my computation of the factor on `T1` (ignoring the `T2` term for now), using the existing code (top result) and the Nortek-suggested method (bottom line).  The view also shows the comment with the formula, and the actual line of code in oce at the moment.

The factor of 100 difference is likely just cm to m, so I'm not worried. But I am concerned with the difference between the digits 2075 and 2288.  I guess it's just 10% or so, though, and who knows, maybe the second term in the equation will make that smaller.

This is something @richardsc and I should maybe talk about sometime.

![Screenshot 2023-10-25 at 8 39 42 AM](https://github.com/dankelley/oce/assets/99469/52aa6af4-6f2b-4670-8e15-67ef6a1d12e8)

**Comment by dankelley** [comment]
Below is what the latest oce ("develop" branch commit 90d87e1d7f7dc387fcd74e37938ced79f2084e43) gives for the start of the summary for that file of yours.  Thus, it agrees with what Nortek has told us, in a separate (private) email chain.

Note that the codes has 25deg hard-wired.  I suppose that should be as inferred as beam angle from the file, but (a) we would get weird results if the angle were to be inferred incorrectly and (b) I don't know whether these machines even have any other angle.  Plus, I don't know whether the numbers might be different for other different beam angles.  Nor do I know how to compute these things for all the other nortek types.  

Hopefully, when Norek update their manuals, it will be clear, and then the formulae in oce can be altered (if necessary).

Meantime, I wonder whether this issue ought to be closed.  (Another issue could be opened if some particular thing is not being read correctly.). I do like closing issues because then I can let the code "leave my head".

```
ADP Summary
-----------

* Filename:          "/Users/kelley/Downloads/arcticbay_aquadopp/AB1904.PRF"
* Manufacturer:      nortek
* Serial number:     AQD15239
* File type:         aquadoppProfiler
* Firmware:          3.42
* Cell Size:         1.00 m
* Blanking Distance: 0.41 m
* Beam Angle:        25 deg
* Location:          unknown latitude, unknown longitude
* Frequency:         1000 kHz
* Transformation matrix::
    1.5774 -0.7891 -0.7891
     0.000  -1.366   1.366
    0.3677  0.3677  0.3677
* Time:          2019-05-30 11:00:00 to 2019-07-10 11:30:00 (3939 samples, mean increment 15 min)
```

**Comment by dankelley** [comment]
Not to be rude, but I'm keen on closing issues as a way to organize time at a busy time of year.  I think the (2-week old) updated code satisfies the O(1) problem of completely incorrect reading, and we ought to have new issue for anything new that crops up (with a title that will be easier for users to identify).

Obviously, though, it's up to @richardsc to decide on closure.  How about a one-week deadline ... just suggesting :-)

PS. I plan on examining all the existing blanking-distance and cell-size code, when (if?) a new manual becomes available.  But I don't think the present issue title (and initial comments) relate to that.  I'll make a new issue in a moment.

**Comment by richardsc** [comment]
Sounds good. I think we can close this and deal with any other (similar) changes as new issues (e.g. updated manual, aquadoppHR formulae which I still haven't got, etc).
