### ISSUE TITLE
Cannot use read.oce() with large Sentinel V .pd0 files

### ISSUE THREAD

**Issue by kurtisanstey** [dankelley/oce#2196]
Hey @dankelley and @richardsc. You recently added the forcev4=True argument that was limiting the oce2ncdf function due to filesize, which was very helpful! With that change I was able to read then save a 1.2 GB Sentinel V .pd0 file as .nc (~3.7 GB).

However, when I try to do the same with an even larger 2.4 GB Sentinel V .pd0 file it fails immediately at read.oce(): 

```
> ds <- read.oce('~/XXX.pd0', by=1, monitor=TRUE, debug=1)
      read.oce("~/XXX.pd0") {
      read.adp.rdi("~/XXX.pd0", from=(missing), to=(missing), by=1...) {
        fileSize=2460052266
        have Binary Fixed Attitude Header: FALSE
        isSentinel=TRUE near adp.rdi.R line 829
        about to call ldc_rdi_in_file
Increasing ensembles,times,sec100s storage to 150000 elements ...
Increasing ensembles,times,sec100s storage to 225000 elements ...
Increasing ensembles,times,sec100s storage to 337500 elements ...
Increasing ensembles,times,sec100s storage to 506250 elements ...
Increasing ensembles,times,sec100s storage to 759375 elements ...
Increasing ensembles,times,sec100s storage to 1139062 elements ...
Increasing ensembles,times,sec100s storage to 1708593 elements ...
        done with do_ldc_rdi_in_file() with numeric from and to, near adp.rdi.R line 683        NEW method from=1, by=1, to=1698931
        header$dataOffset=3494160602824104610861198125513121328138614021436 (reread because a sentinelV file)
Error in read.adp.rdi(file, encoding = encoding, processingLog = processingLog,  : 
  difficulty detecting ensemble (profile) start indices
In addition: Warning message:
In read.adp.rdi(file, encoding = encoding, processingLog = processingLog,  :
  skipping the first ensemble (a temporary solution that eases reading of SentinelV files)
```

This error does not persist if I limit the number of ensembles read using from= and to= arguments to a maximum of about 1,400,000. There is a total of 1,698,931 ensembles in the file. 

For now I can split the file, and other similarly large .pd0 files, but I'm not sure if that's necessary.

Do you think this is an issue with the read.oce() routine, memory, or some limitation of R? I appreciate your help!

```
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
Matrix products: default
locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    
time zone: America/Vancouver
tzcode source: internal
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] oce_1.8-2 gsw_1.1-1
loaded via a namespace (and not attached):
[1] compiler_4.3.2 tools_4.3.2    Rcpp_1.0.12 
```

Will email you and Clark with access to a file, for testing.

**Comment by dankelley** [comment]
Thanks.  Are you able to build oce from source?  (Instructions are on landing page.)

**Comment by dankelley** [comment]
It is decoding the `profileStart` values incorrectly.  That's what the "difficulty" message is about.  These are meant to be positive integers, but I get
```R
> table(profileStart<0)

  FALSE    TRUE 
1483068  215862 

range(profileStart)
[1] -2147483111  2147482737
```
which, um, is *a bit* confusing!

The computation of `profileStart` is at https://github.com/dankelley/oce/blob/03bdfbc27897603a0f0c4a04213b90ce4572894e/R/adp.rdi.R#L961 and that's what I need to think about.

We've not had this problem reported before.  Other indicators tell me that this a sentinelV file.  I think a lot of the code for that system is quite provisional.  

@kurtisanstey Were the other files you had (and that worked) also sentinelV?  Knowing that might help me.

PS. I will look at this again tomorrow.  My timezone is UTC-4h and I get up pretty early, so work done this late in the day tends to be, um, not the best :-)

**Comment by dankelley** [comment]
Hm.  The profileStart values are all OK until the 1483069-th instance.

You can see that in the plot below, made by adding the following into the test that yields the error message.  (The log base 2 is because I wanted to show that we are far below the wrapping point for 4 byte integers.)

So, I don't quite know what is going on here.  If it was just a few isolated instances, I might guess it was a byte problem that somehow (???) got through the checksum tests.  But it just changes at a certain spot.

I'll pick up this thread tomorrow.

NOTE: I won't push code to GH until I get it working.  If I need tests from somebody, I'll make a new branch.  I don't want other users working with code that is in flux.

```R
Browse[1]> plot(profileStart < 1, type="s")
Browse[1]> abline(v=w, col=2, lty=2)
Browse[1]> mtext(w,col=2,at=w)
Browse[1]> log2(w)
[1] 20.50015
```
![Screenshot 2024-02-22 at 4 21 42 PM](https://github.com/dankelley/oce/assets/99469/702c49f3-45ae-44b8-a023-21b9bdb0ee3e)

**Comment by dankelley** [comment]
Oh, I added more printing (it takes like 5 minutes to rebuild for a test) and I see that the problem is that `ensembleStart` is big:
```R
ensembleStart[firstBad]=-2147483205
Browse[1]> log2(2147483205)
[1] 31
```

So I think I need to tell R to use 64 bit integers for `ensembleStart`.

First I'll check to see if the problem is from the C++ code, though. I hope it's there because C++ can definitely deal with 64 bit integers.  I *think* R can, but some tricks need to be played.

More tomorrow.

**Comment by kurtisanstey** [comment]
Hey @dankelley. Yes, I can build oce from source, and yes, the files that worked were all Sentinel V, though smaller (about 1.2 GB). Again, zero rush so get some sleep!

**Comment by dankelley** [comment]
A wrinkle is that the C++/R interface we use has no predefined object for 64 bit integers.  That makes sense, because R does not officially support 64 bit integers. Instead, R has packages that do this. 

 From my reading, the most popular R package at the moment is `bit64`.  

So I will try storing pointers to indices as doubles in C++ (which will be 64 bits) and then, in the calling program, I'll try using functions in the `bit64` package to turn that back into a sort of 64-bit integer.   Actually, it will not be that.  It will internally still be the 64-bit floating point (all the bits will be the same) but it will have an R attribute that says to interpet it as a `bit64` object.  The package of the same name then has things to override operators like `+`.  I imagine they also override `[` because, if not, this method will not be of any use.

Each test will require building oce, to get the C++ code and the R code hooked up properly.  That means this will be slow work.  And, even if it works, there will undoubtly be lots of echo effects on other things (plotting, subsets, etc).  And maybe R won't even let us allocate arrays large enough to store such data.

Bear in mind that a 2Gb file will expand by a factor of perhaps 6, because in the file lots of things are stored as 1-byte quantities or 2-byte quantities, and these will get expanded into 8-byte "numeric" quantities in R.  The exact factor will depend on the proportion that are 1-byte etc, but I'd guess 6, as an intermediate between 4 and 8.

Timing: I will play a bit with this, off and on, over the next few days.  It is something worth doing, even if in this particular case I advise @kurtisanstey to break the files up into pieces, because working with such large files might be a pain.  (Going back to the previous paragraph, my laptop barely has enough memory to even store such objects in RAM.  And if a function requires duplicating an object, say for an intermediate computation, then for sure I'd run out of memory.)

**Comment by dankelley** [comment]
I just did a little experiment and it looks promising.  Below are some notes -- since these are just for me to remember later, I won't bother writing paragraphs to explain.  The upshot is that I am pretty sure I am storing indices correctly now in the C++ code.

The next step will be to see whether I can get the rest of the code working. 

As it turns out, R can use double-precision values as indices.  But I still think it might make sense to use the `bit64` package so that things like arithmetic will work correctly.  (I don't think adding would work otherwise ... it's all about bit patterns and I guess `bit64` has code to make it work on big-endian as well as little-endian, etc.)

```R
Browse[1]> plot(diff(ldc$ensembleStart64),type="s");abline(v=firstBad,col=2)
Browse[1]> table(diff(ldc$ensembleStart64))

   1448    1626 
1698929       1 
Browse[1]> diff(ldc$ensembleStart64)[1:5]
[1] 1626 1448 1448 1448 1448
```

![Screenshot 2024-02-23 at 7 49 44 AM](https://github.com/dankelley/oce/assets/99469/e1f169a4-6ee9-4001-9200-d35852370c52)

**Comment by dankelley** [comment]
Hm.  It doesn't look as though indexing by a 64-bit integer works.  I'll try just indexing with double, instead. A plus is that then we don't have to load the `bit64` package.
```R
> a<-3.0
> A<-bit64::as.integer64(a)
> A
integer64
[1] 3
> v<-1:10
> v[a]
[1] 3
> v[A]
integer(0)
```

**Comment by kurtisanstey** [comment]
@dankelley and @richardsc thanks for all your work on this. I'll be working with those datasets again in the next few days. Will rebuild with the develop branch and update, then!

**Comment by kurtisanstey** [comment]
It's working well with other large datasets!
