### ISSUE TITLE
"specc" is incorrectly converted to "conductivity", but should be "specificConductance"

### ISSUE THREAD

**Issue by coffm049-2** [dankelley/oce#2211]
**Context:**
I am using 500+ SeaBird CTD `.cnv` files hosted by GLNPO to incorporate into a data harmonizing package for Great Lakes datasets (GLENDA, NCCA, and CSMI). Some of the files have a variable called "specc" while others don't

for example:
```
"# name 12 = specc: Specific Conductance [uS/cm]"
```

**Problem**
When loading this data using oce, `"specc"` gets mapped to `"conductivity"` (see lines 533-534 in [this file](https://github.com/dankelley/oce/blob/692ff2a31499ce5b12c321c86aacaf5689a2f20e/R/ctd.sbe.R#L136) also described in line 156 of [this table](https://github.com/dankelley/oce/blob/692ff2a31499ce5b12c321c86aacaf5689a2f20e/man/cnvName2oceName.Rd#L156) ). However, I want `"specc"` to be mapped to `"specific conductance"` (or something similar). Do you have any suggestions on how to deal with this? Note that specc won't appear in every file, and will furthermore not always be the 12 reported analyte.

_Originally posted by @coffm049-2 in https://github.com/dankelley/oce/discussions/1754#discussioncomment-9297840_

**Comment by dankelley** [comment]
Hi, and thanks for the issue (and previous discussion).  I've just changed the oce source, and am rebuilding and retesting.  I'll post another note when this is done, and the changes are pushed to GH.  You'll want to install from github (instructions on the landing page) because this won't get into the CRAN version for likely several months.  (We limit submissions to CRAN.)

Also, I'd appreciate it if you could check the code out on your data, so we'll know if it worked.

As for your other queries:
1. This will not affect files that don't have that column.
2. The order of columns doesn't matter.

**Comment by dankelley** [comment]
I've updated the code in the "develop" branch, with commit note as follows.  @coffm049-2 can you try rebuilding from github (use `remotes::install_github("dankelley/oce", ref="develop")` to do that) and try it out?  If you have problems, please email me the data file (kelley AT dal DOT ca) and I'll take a look.

Note that you can use `summary()` on any oce object, to discover what we call the "original name" (it's in the table of variable properties) and that you can refer to them.  For example, the new code will read that column into something you can access by either `d[["specificConductance"]]` or `d[["specc"]]`.

Our convention in the oce community is that users ought to be the ones to close issues.  So, at your convenience, if the new code seems to work properly, please make a note to that effect and close the issue.  Or, if there are problems, post a comment stating so.  This helps us, because we use open issues as a sort of "to do" list.  There is **no rush** on this, of course.

Thanks!

commit ef59cdc058b65d56dbc05afe8b90b7df723c8492
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu May 2 15:11:38 2024 -0300

    read.ctd.sbe() treats specc correctly (issue 2211)
    
    Thanks to GH user @coffm049-2 for pointing this out.

**Comment by coffm049-2** [comment]
This is **successful** on my end. However, I couldn't check this using 'summary', instead I used 'names'. See image below. 

![image](https://github.com/dankelley/oce/assets/147004005/ca6cdba0-4ab0-4e8b-839a-e6aa53aef170)

**Comment by dankelley** [comment]
FYI, you do `summary()` on the full object, not the data part, e.g. as below.  The "original name" is over on the right of the table it shows.  Summaries are pretty handy.  They don't show everything in the object, but just some things that seem to be useful in many workflows.

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
summary(ctd)
#> CTD Summary
#> -----------
#> 
#> * Instrument:          SBE 25
#> * Temp. serial no.:    1140
#> * Cond. serial no.:    832
#> * File:                "/Users/kelley/git/oce/create_data/ctd/ctd.cnv"
#> * Original file:       c:\seasoft3\basin\bed0302.hex
#> * Start time:          2003-10-15 15:38:38
#> * Sample interval:     1 s
#> * Cruise:              Halifax Harbour
#> * Vessel:              Divcom3
#> * Station:             Stn 2
#> * Mean Location:       44.684N 63.644W
#> * Data Overview
#> 
#>                                 Min.   Mean   Max. Dim. NAs OriginalName
#>     scan                         130    220    310  181   0         scan
#>     timeS [s]                    129    219    309  181   0        timeS
#>     pressure [dbar]             1.48 22.885 44.141  181   0           pr
#>     depth [m]                  1.468 22.698 43.778  181   0         depS
#>     temperature [°C, IPTS-68]  2.919 7.5063 14.237  181   0         t068
#>     salinity [PSS-78]         29.916 31.219 31.498  181   0        sal00
#>     flag                           0      0      0  181   0         flag
#> 
#> * Processing Log
#> 
#>     - 2018-11-14 20:03:47 UTC: `create 'ctd' object`
#>     - 2018-11-14 20:03:47 UTC: `read.ctd.sbe(file = file, debug = 10, processingLog = processingLog)`
#>     - 2018-11-14 20:03:47 UTC: `oce.edit(x = ctd, item = "startTime", value = as.POSIXct(gsub("1903",     "2003", format(ctd[["startTime"]])), tz = "UTC") + 4 * 3600,     reason = "file had year=1903, instead of 2003", person = "Dan Kelley")`
head(ctd[["salinity"]]) # oce name
#> [1] 29.9210 29.9205 29.9206 29.9219 29.9206 29.9164
head(ctd[["sal00"]]) # originalName (discorable from the summary)
#> [1] 29.9210 29.9205 29.9206 29.9219 29.9206 29.9164
```

<sup>Created on 2024-05-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
FYI, I ran across the attached document about relating specific conductance and conductivity.

I don't know how up-to-date the formulae is, though, or whether other instruments used (or use) the same form.  For this reason, I do not plan on adding information on this conversion to the oce docs.  (In oce, we generally strive to let users access their data, but not to replace the literature or grey literature on how to deal with those data.)

[Sea-Bird Electronics - 2001 - Fresh Water Conducitivity Measurents Using the SBE.pdf](https://github.com/dankelley/oce/files/15199750/Sea-Bird.Electronics.-.2001.-.Fresh.Water.Conducitivity.Measurents.Using.the.SBE.pdf)

**Comment by coffm049-2** [comment]
Thank you for following up on this. This is the same formula that I've seen from other practitioners, so at least it's internally consistent on my end, but I can't speak to other cases (especially outside of fresh water).

I appreciate the effort you put in the consistency of your documentation!
