### ISSUE TITLE
oce should not require sqlite3 to be installed

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#565]
RBR data files use sqlite3 data format, and at present ``read.logger()`` handles these files with ``system()`` calls to an external ``sqlite3`` program.  But not everyone has ``sqlite3`` installed so this is an awkward method.  It would be better to use the ``RSQLite`` R package, because it contains its own sqlite3 program.

**Comment by dankelley** [comment]
Fixed in ``develop``.

**Comment by richardsc** [comment]
This is great!

I wonder if it makes sense to have the `RSQLite` dependency be a "suggests" instead of "depends". This is partly to keep the core oce dependencies pretty basic, but also more in line with the current framework where specific data types *may* require extra packages -- e.g. `ncdf4` for argo, `tiff` for landsat, etc.

**Comment by dankelley** [comment]
Excellent point. I will change this morning.

Actually, I find those "loading" messages distracting. Presently, oce loads ```mapproj`` and therefore ``maps``, even if not needed.  I would change to a suggest, but that would mean the examples would have to be switched to proj4 notation, which may be trickier for some users. (I'm not sure it *is* tricker, actually, since with mapproj you have to learn about that ``orientation`` arg, which is poorly documented. And with proj4, you have the advantage of its common use in other systems, esp GIS.)

**Comment by dankelley** [comment]
Done, in ``develop``, ``logger`` and ``gsw`` branches (the three ones I tend to use).
