### ISSUE TITLE
unable to install develop branch

### ISSUE THREAD

**Issue by MichaelFolkes** [dankelley/oce#575]
I have previously succeeded installing the ``develop`` branch. But not today.
From my R console:
```"ERROR: compilation failed for package 'oce'"```

I can install it if I change ref to ``master``.

I have the full console output in a text file if you want to see it, just not clear how I can share it.
I'm doing this just to get latitude labels in my mapPlot()!
thanks

**Comment by dankelley** [comment]
Can you email dan.kelley@dal.ca with the full output?  I'll delete this comment when I get it. (Normally I don't like having emails in comments)

**Comment by dankelley** [comment]
The problem is that you are on a MSwindows machine, but the ``ncdf4`` package is not pre-built for that. You'll need (I guess) to download that package as source, and then build it. I guess you could also lean on the ``ncdf4`` author, in hopes of getting a prebuilt MSwindows version.

I infer this from the output from your log file:
```
Installing dependencies for oce:
ncdf4

   package ‘ncdf4’ is available as a source package but not as a binary
```

**Comment by dankelley** [comment]
Wait a sec. I don't see why it's demanding ``ncdf4``.  The ``develop`` branch of ``oce`` has as follows. So I don't see why your build is dying.
```
$ grep ncdf DESCRIPTION
Suggests: ocedata, foreign, ncdf4, tiff, akima, proj4, RSQLite, DBI
```

**Comment by dankelley** [comment]
Possibly @richardsc has some insights?  I don't have any way to test with MSwindows.

**Comment by richardsc** [comment]
Yes, that is weird. I'll look into it with my windows VM -- but it's XP so is a little outdated.

If it is needed though, the ncdf4 author does provide a pre-built Windows package (i.e. zip file) that can be installed. See:

http://cirrus.ucsd.edu/~pierce/ncdf/

**Comment by dankelley** [comment]
Michael, can you try downloading again? I think I fixed the problem.

**Comment by MichaelFolkes** [comment]
But I'm confused why it's asking for it this time. But I succeeded previously...
I'll do the download. thanks for the quick advice.

**Comment by dankelley** [comment]
I suppose it's trying to get ``ncdf4`` working just "in case".  But the new download should work.

**Comment by MichaelFolkes** [comment]
Here's the output after the compiling.
I don't get the compiling error and am trying to interpret this. I sense it failed and re-installed the stable version?


```
installing to C:/Program Files/R/R-3.1.1/library/oce/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
  problem copying .\oce.dll to C:\Program Files\R\R-3.1.1\library\oce\libs\x64\oce.dll: Permission denied
** R
** data
** demo
** inst
** tests
** preparing package for lazy loading
Warning: package 'gsw' was built under R version 3.1.2
Creating a generic function for 'subset' from package 'base' in package 'oce'
Creating a generic function for 'summary' from package 'base' in package 'oce'
Creating a generic function for 'plot' from package 'graphics' in package 'oce'
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
Warning: package 'gsw' was built under R version 3.1.2
*** arch - x64
Warning: package 'gsw' was built under R version 3.1.2
* DONE (oce)
Reloading installed oce

Attaching package: ‘oce’

The following object is masked _by_ ‘.GlobalEnv’:

    mapDirectionField

Warning messages:
1: package ‘ncdf4’ is not available (for R version 3.1.1) 
2: package ‘gsw’ was built under R version 3.1.2 
> 

> packageVersion("oce")
[1] ‘0.9.15’
> 
```

**Comment by richardsc** [comment]
Hi @MichaelFolkes. It looks to me like it installed the develop version -- the stable version is 0.9.14.

I was able to install the latest oce develop on windows XP using R 3.1.2 and devtools. I didn't get any warnings ...

The `gsw` warning shouldn't be a big deal. We just released that package to CRAN a couple weeks ago, so it is only available for the newest version of R, which is 3.1.2 (you're running 3.1.1). To make that go away you just need to install the latest version of R.

I'm still not sure why you're getting the `ncdf4` warning. I wonder if you have specific startup code in your .Rprofile? I ask because this message:

```
The following object is masked _by_ ‘.GlobalEnv’:

    mapDirectionField
```
suggests that there are two versions of the `mapDirectionField()` function, and the one in `.GlobalEnv` is masking the `oce` one. Maybe there is something related to `ncdf4` there too?

The other option is to install `ncdf4` from the author's website as I mentioned above.

**Comment by MichaelFolkes** [comment]
Note quite - I had a temporary version of ```mapDirectionField``` in an sourced R file. That'll confuse everything!
That was for back when Dan was modifying it in the summer.
I seem to be running ok. I was also confused that 0.9.15 was the stable release.
I'll do the ```ncdf4``` install if necessary - but seem to be ok now?

**Comment by MichaelFolkes** [comment]
Shall I close?

**Comment by richardsc** [comment]
Yes, I think you should be ok now -- close away!

I would only go down the ncdf4 rabbit hole if you actually need it for something.

**Comment by MichaelFolkes** [comment]
Awesome support as always. Thanks.

**Comment by richardsc** [comment]
You're welcome!
