### ISSUE TITLE
mapAxis incomplete latitude labels

### ISSUE THREAD

**Issue by MichaelFolkes** [dankelley/oce#576]
Please forgive me as I am a mere mortal...
My latitude labels in this plot show just 35N and 40N. Should I expect more?
```
require(oce)
require(ocedata)
data(coastlineWorldMedium)
longitudelim <- c(-180,-125)
latitudelim <- c(45,55)
mapPlot(coastlineWorldMedium, longitudelim=longitudelim, latitudelim=latitudelim, proj="+proj=lcc +lat_0=40 +lat_1=60 +lon_0=-150",  grid=c(10,10))
mapGrid(dlongitude=5, dlatitude=5)
mapAxis(side=2, latitude=seq(35,60, by=5))
```

**Comment by richardsc** [comment]
Yes, you should! Thanks for reporting -- this looks like a bug in `mapAxis()`, but it might have to wait until @dankelley is back online.

I note that if `mapAxis()` is called with default arguments (which *should* put a label at every grid line), it spits out a bunch of warnings, which I'm sure are related to your issue:

```
> mapAxis()
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In mapAxis() :
  mapAxis(side=1) cannot draw latitude labels yet; contact author if you need this

2: In optimize(function(lon) abs(lonlat2map(lon, lat)$x -  ... :
  NA/Inf replaced by maximum positive value
3: In optimize(function(lon) abs(lonlat2map(lon, lat)$x -  ... :
  NA/Inf replaced by maximum positive value
4: In optimize(function(lon) abs(lonlat2map(lon, lat)$x -  ... :
  NA/Inf replaced by maximum positive value
5: In optimize(function(lon) abs(lonlat2map(lon, lat)$x -  ... :
  NA/Inf replaced by maximum positive value
...
```

**Comment by richardsc** [comment]
Playing around, the bug seems to be related to the location of the international dateline. See the example code below, and the entry in the [oce-issues](https://github.com/dankelley/oce-issues/tree/master/576) repo:

```r
library(oce)
library(ocedata)
data(coastlineWorldMedium)
longitudelim <- c(-180,-125)
latitudelim <- c(45,55)

par(mfrow=c(2, 2), mar=rep(2, 4))
for (llon in seq(-190, -160, 10)) {
    mapPlot(coastlineWorldMedium, longitudelim=c(llon, -120), latitudelim=latitudelim,
            proj="+proj=lcc +lat_0=40 +lat_1=60 +lon_0=-150",  grid=c(5, 5))
    mapGrid(longitude=-180, latitude=NULL, lwd=4, col=2)
}
```
which produces:
![01](https://cloud.githubusercontent.com/assets/233584/6008894/f9377968-aaf2-11e4-9099-d11c1e34677a.png)

**Comment by dankelley** [comment]
Hi all. Likely I'll have a look tomorrow sometime. Nasty storm here. Eyes tired from straining to see the road. Looks like Clark's detective work has turned up the problem. The underlying code is a bit messy, actually, because it has to deal with cases in which a given latitude appears twice on a plot, etc. (This happens in some projections. The whole deal with all of this is that pretty much anything can happen in some projection!)

**Comment by MichaelFolkes** [comment]
Cool detective work Clark.
Thanks for the help. Looking forward to some hopeful emails later this week!

**Comment by MichaelFolkes** [comment]
I just ran Clark's code. My longtitude labels don't line up with the grid!
Oi!

**Comment by dankelley** [comment]
I think this is fixed now in ``develop``. It passes the test that CR made in the oce-issues, and I added another test that matches the original MF code.

The fix was in line 107 of ``R/map.R``, where I define two hemispheres to search. Well, they *were* hemispheres before, and I've not changed the name of the variable, but now they are spheres!

The method I'm using is a bit odd, making use of ``optimize()`` to try to find locations on the side that correspond to given lats and lons. This is all because there is no way to know whether inversion is possible. In this *particular* case, inversion is possible, i.e. the grid lines come to the edge of the plot. But that's not always going to be the case, e.g. in projections that show the whole earth as a sphere within a box ... no grid lines need to extend to the box edges.

**Comment by dankelley** [comment]
I wish GH had threaded comments. I am replying to the comment just before the previous one.

Michael, if you now get complete labels on latitude, then the non-alignment should be a new issue number. That's the only way to keep track of changes, since GH doesn't have threaded comments. The rule is simple: when an issue *as stated in the initial subject line* is fixed, the issue should be closed, and any new problems should be new issues. The idea is to make it easier (for the developer and also for other users) to track progress.

PS. Michael, please bear in mind that you can upload images to these comments. So if you open a new issue you should (a) write complete code to reproduce the bug and (b) include an image. Seem ok? Thanks for the patience!!

**Comment by MichaelFolkes** [comment]
Understood and thanks for the tutorial. I should prob take the time to read the intro guide to GH etiquette - wherever it may be. I'll rerun all and respond here (and possibly new issue) based on results.
With appreciation.

**Comment by dankelley** [comment]
Well... not sure there is any guide!  This is just a convention we have in oce, to try to let other users find similar problems.

This one-issue-per-bug scheme also comes in handy for the related [oce-issues](https://github.com/dankelley/oce-issues) repo. If you go there and look at the [Makefile](https://github.com/dankelley/oce-issues/blob/master/Makefile) you'll see that we have the issues in "themes". The idea of that is that when work is done on, say, mapping, then simply typing ``make map`` (in a unix console) reruns all the issue test code that has been tagged as relating to maps. That's when having isolated issues gets really handy. If that test suite breaks, I can consult the webpage title to see what it was all about, and to read the discussion. This is a scheme for developing "in the open", as they say, and it is helpful to developers like me and Clark who are just doing this as a hobby (i.e. nobody pays us to do this), and it's helpful to users who get into a problem when Clark and I are too busy with our jobs for days or weeks.

Thanks for the reports, Michael, and please keep them coming in.  (Oh yeah, and please close this if it's done ... the other part of our procedure is that only reporters close bugs, unless they have been fixed and are sitting idle for a few weeks.)

PS. I'd put the above into a sort of "README" for issues, but GH has no facility for that. I've requested it a few times, but it doesn't fit into their idea of what issues are for. Frankly, I think they handle issues poorly compared with other systems.

D.

**Comment by MichaelFolkes** [comment]
Superb. Works like a charm.
thanks once again. The future is not plastics, it's open source.
