### ISSUE TITLE
Feature request: `mapAxis()` should have more options to make it a parallel of `axis()`

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#577]
Currently `mapAxis()` only has 3 args, meaning there is no way to control labels, ticks, etc.

**Comment by dankelley** [comment]
Good point. I'll have a look tomorrow.  There will be some subtle things to handle, e.g. ``at`` (and therefore ``labels``.)  The idea of ``at`` doesn't carry over because it's not cartesian.  (Put another way, ``axis()`` only labels ``x`` values on ``side=1``.) Therefore that does not carry over. I don't think ``labels`` carries over either. I think I am going to use the present comment (edited as I work on this) to take notes. I'll list the things I think that I'll change. I'll tick them off when done, or I will write **ignore** if I think they should not be done.

* [ ] ``at``
* [ ] ``labels``
* [ ] ``tick``
* [ ] ``line``
* [ ] ``pos``
* [ ] ``outer``
* [ ] ``font``
* [ ] ``lty``
* [ ] ``lwd``
* [ ] ``lwd.ticks``
* [ ] ``col``
* [ ] ``col.ticks``
* [ ] ``hadj``
* [ ] ``padj``
* [ ] ``...``

**Comment by dankelley** [comment]
I think this is working now. I set up a test on the ``oce-issues`` site, e.g. the following yields as shown.
```splus
library(oce)
try(source("~/src/oce/R/map.R"))
data(coastlineWorld)
longitudelim <- c(-180,-125)
latitudelim <- c(45,55)
if (!interactive()) png("01.png")
mapPlot(coastlineWorld, longitudelim=longitudelim, latitudelim=latitudelim,
        proj="+proj=lcc +lat_0=40 +lat_1=60 +lon_0=-150",  grid=c(10,10),
        axes=FALSE)
mapGrid(dlongitude=5, dlatitude=5)
mapAxis(side=1, tcl=-0.5, col.ticks='blue') # wild values to show effect
mapAxis(side=2, col.ticks='red', lwd.ticks=5) # wild values to show effect
if (!interactive()) dev.off()
```
![01](https://cloud.githubusercontent.com/assets/99469/6021806/e250b5e2-ab8e-11e4-9a13-5e7c83840629.png)

**Comment by richardsc** [comment]
Great, thanks!
