### ISSUE TITLE
mapPlot longitude labels lose alignment from grid in Rstudio external graphics window

### ISSUE THREAD

**Issue by MichaelFolkes** [dankelley/oce#578]
I brought this up in issue #576, so am mentioning it here, but I don't consider it an issue.
Running this example code, written by @richardsc, if you run this in Rstudio, then open the resulting plot in an external Rstudio graphics window, the longitude labels lose alignment from the grid (as you resize the window).

I'm starting to appreciate the complexity of projections is substantially more challenging than a normal plot. 
Bottom line is creating the plot in png() or pdf() etc is safe. 

```
library(oce)
library(ocedata)
data(coastlineWorldMedium)
longitudelim <- c(-180,-125)
latitudelim <- c(45,55)

par(mfrow=c(2, 2), mar=rep(2, 4))
for (llon in seq(-190, -160, 10)) {
    mapPlot(coastlineWorldMedium, longitudelim=c(llon, -120), latitudelim=latitudelim,
            proj="+proj=lcc +lat_0=40 +lat_1=60 +lon_0=-150",  grid=c(5, 5))
    mapGrid(longitude=-180, latitude=NULL, lwd=4, col=2)
}
```

**Comment by richardsc** [comment]
Thanks for pointing this out!

This *is* an odd one ... I can reproduce the described behaviour using a `quartz()` window on OS X, without using RStudio (See image below). The odd thing is that for some aspect ratios the axis ticks are clearly wrong, but for a *slightly* different ratio they are perfectly right.

![screen shot 2015-02-02 at 7 43 32 pm](https://cloud.githubusercontent.com/assets/233584/6012269/25ef95b4-ab14-11e4-9b70-4653f5f64855.png)

The issue can occur for `par(mfrow=c(1,1))` too, and note that it can affect *both* lat and lon labels.

Since it appears that the redraw of the projection is correct, the fix seems to be to just issue the `mapPlot()` command again, which will redraw the axes correctly.

@dankelley I can't tell if this is actually a bug with `mapPlot()`, or just some weird interaction between the projection and the axes.

**Comment by dankelley** [comment]
I suspect this is related to something I don't understand about plot geometries. For example, ``imagep`` plots also have problems in resizing. To see that, try as follows
```splus
library(oce)
data(adp)
imagep(adp[['v']][,,1])
```
and resize. You'll see the colourscale sometimes overlaps the graph. The ``imagep`` code is trying to figure out the sizes of these things based on calls to ``par("fin")`` as at e.g. line 86 of ``R/imagep.R`` (and quite a few other lines). Resize, and the colourbar and plot overlap. But then keep the resized window unaltered and repeat the ``imagep`` call, and the plot is ok. This suggests that the information becomes "known" to ``par`` only at certain times. About a year ago I tried to read through the underlying C code to understand this, but didn't get very far because the code is so complex^1.

[1] The complexity of the underlying C graphics code has been a matter of discussion in the R community. Some developers suggest that the only way to fix its bugs would be to rewrite the whole thing. But that's hard with decades-old code, and especially hard for *complex* code like that at the guts of R. Besides, the graphics system is not really broken, in the sense that something stated in the documentation is untrue. There are bigger tasks for the core R development team, e.g. the slowness of loops and some issues of scoping; see Ross Ihaka's blog for some very interesting papers and talks about these things. His words have a lot of strength, since he was the original co-developer of R, way back when. But he is an associate professor and think his dean would be unhappy to see him take a decade off from his teaching schedule to rewrite the R internals, and his granting agency would probably be even more unhappy.
