### ISSUE TITLE
grid() lines don't align with ticks when axis is POSIX time

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#581]
I suspect the problem has to do with the variable number of days in a month. The problem seems to occur only when the time range is > 4 months, i.e. when it uses the first day of the month as the tick locations -- though there may be a problem with multi-year series as well. I don't know if it's a problem with `grid()`, or with `oce.axis.POSIXct()`. See the sample code in [oce-issues/581](https://github.com/dankelley/oce-issues/tree/master/581):

```r
rm(list=ls())
library(oce)

## create some fake data that spans the better part of a year
trange1 <- as.POSIXct(c("2010-07-02 16:00:32", "2010-07-31 00:00:48"), tz='UTC')
trange2 <- as.POSIXct(c("2010-07-02 16:00:32", "2010-10-16 00:00:48"), tz='UTC')
trange3 <- as.POSIXct(c("2010-07-02 16:00:32", "2011-05-16 00:00:48"), tz='UTC')
trange4 <- as.POSIXct(c("2010-07-02 16:00:32", "2012-05-16 00:00:48"), tz='UTC')
trange5 <- as.POSIXct(c("2010-07-02 16:00:32", "2022-05-16 00:00:48"), tz='UTC')

if (!interactive()) png('01-%03d.png', width=1000, height=400)

nt <- length(grep('trange', ls()))
for (i in 1:nt) {
    trange <- get(ls()[grep('trange', ls())[i]])
    ## create a time vec
    timeConst <- seq(trange[1], trange[2], length.out=100)

    ## create a data matrix
    p <- seq(50, 900)
    d <- matrix(rnorm(length(p)*length(timeConst)), nrow=length(timeConst))

    imagep(timeConst, p, d)
    grid(col=1)
    rm(trange)
}

if (!interactive()) dev.off()
```
With figures below. It's a bit hard to see on here, but in the 3rd and 4th figures the grid lines are not always aligned with the tick marks.

![01-001](https://cloud.githubusercontent.com/assets/233584/6044079/053233bc-ac5f-11e4-83fd-b0ea9f26a9b5.png)
![01-002](https://cloud.githubusercontent.com/assets/233584/6044080/09a06b3a-ac5f-11e4-8eac-4a9aff9403fb.png)
![01-003](https://cloud.githubusercontent.com/assets/233584/6044081/0de4f86e-ac5f-11e4-8d50-c38c0d4fe101.png)
![01-004](https://cloud.githubusercontent.com/assets/233584/6044084/1149a22a-ac5f-11e4-9afc-abb16183b8db.png)
![01-005](https://cloud.githubusercontent.com/assets/233584/6044090/16110b7c-ac5f-11e4-8884-77a6cbdec2a4.png)

**Comment by dankelley** [comment]
It's not often I say this, but I don't think this is a bug in ``imagep()``.  Tthis happens in other cases also. I'm attaching a screenshot with some R code that is independent of oce. See the italics in the help page (the part that's highlighted). What this means is that ``grid()`` cannot be relied upon to make a grid except if the axis is of default form.

Now, what I *can* do is to add a ``grid`` argument to ``imagep()``, as I've done to some other Oce functions like ``mapPlot()``.

![screen shot 2015-02-04 at 2 36 03 pm](https://cloud.githubusercontent.com/assets/99469/6046800/98bb3324-ac7b-11e4-8fbc-b733d9391af2.png)

**Comment by dankelley** [comment]
Here's a test case showing that it's not limited to oce:
```splus
trange <- as.POSIXct(c("2010-07-02 16:00:32", "2011-05-16 00:00:48"), tz='UTC')
if (!interactive()) png('03.png', width=1000, height=400)
timeConst <- seq(trange[1], trange[2], length.out=100)
plot(timeConst, seq_along(timeConst))
grid()
if (!interactive()) dev.off()
```
![03](https://cloud.githubusercontent.com/assets/99469/6047234/d0d5f296-ac7e-11e4-950c-0f93bff0a666.png)

**Comment by dankelley** [comment]
Clark, want me to add an option to ``image()`` to print a grid?  I guess it would require a few new args ... actually, I am toying with a method for such things: the arg could be called ``grid`` and it could be interpreted as follows:
* if ``FALSE``, no grid of course
* if ``TRUE``, just add a default grid with line width etc as the ``grid()`` default
* if a list, then the list could contain e.g. ``lwd`` for line width, etc.
What I like about this scheme is that the options for the grid would be a little easier for the user to recognize. Otherwise, I could make e.g. an arg called ``grid.lwd`` and so forth but somehow I like the idea of linking things in a list. In fact, I wish this were more the R convention, grouping things in lists like this so that the overall argument list is clearer.

**Comment by richardsc** [comment]
I think the `grid=list(...)` idea for `imagep()` is a good one, though I would argue that it should call a specific (new) function that does all the work. This makes the solution more portable (e.g. to `oce.plot.ts()` plots, which suffer from the same problem). It also allows a user to do, say, an `imagep()` call, add a bunch of other things to the plot, and then add a correct grid when it's all done.

What should it be called? `oceGrid()`, `oce.grid()`, `oce.grid.ts()` (the last is consistent with `oce.plot.ts()`)?

**Comment by dankelley** [comment]
You mean a new function to be called after, right?

I also like the idea, despite the fact that it is not R-ish (to make up a word).

What I can do is to make the various functions create variables that get consulted later. This is like how ``mapproj`` does things.  Again, though, it is not quite in the R tradition (or "functional language" tradition). To keep it in the R tradition, I could make the functions return a value (silently). Thus you could do
```splus
axes <- imagep(...)
grid(axes)
```
This is *not quite* analogous to R, but it's close, as you can see from the below, where ``axis()`` returns a value
```
> plot(1:3)
> a<-axis(1)
> a
[1] 1.0 1.5 2.0 2.5 3.0
```
but ``plot()`` does not:
```
> a<-plot(1:3)
> a
NULL

**Comment by richardsc** [comment]
Hm. Maybe I'm a bit confused.

Currently, `imagep()` and `oce.plot.ts()` using `oce.axis.POSIXct()` for positioning tick marks and formatting axis labels. The current issue notes that when `grid()` is used after such a call, there can be discrepancies between the locations of the ticks and the grid lines (related question -- are we positive that the *ticks* are in the right place?).

I guess what I was thinking is that either:

1. `oce.axis.POSIXct()` should return values the same way that `axis()` does, so that a normal call to `grid()` after either `imagep()` or `oce.plot.ts()` will work as expected, or

2. there should be a new function, called something like `oce.grid.POSIXct()` that will put gridlines in the correct place.

Will either of those work if the call to `oce.axis.POSIXct()` is buried *inside* another function (e.g. `imagep()`)?

It's also possible (read: likely) that I don't really understand what `axis()` and `grid()` and their variants are doing, and it's just coincidence that I've spent the last 4 years thinking that the reason I mostly got sensible plots was something more than coincidence ...

**Comment by richardsc** [comment]
Ok, I see from reading TFM:

> ‘grid’ adds an ‘nx’ by ‘ny’ rectangular grid to an existing plot.

So `grid()` is *incapable* of putting gridlines on a plot where the ticks are not equally spaced. Further, I see this:

> nx, ny: number of cells of the grid in x and y direction.  When
>           ‘NULL’, as per default, the grid aligns with the tick marks
>           on the corresponding _default_ axis (i.e., tickmarks as
>           computed by ‘axTicks’).

**Comment by dankelley** [comment]
Yes, your reading of the manual is right. We have almost the same idea on the return value. Right now, ``oce.axis.POSIXct()`` returns the tick locations. (Oh, and I am pretty sure they are correct, at the start of the month; a quick ``abline()`` could test that.) So my idea is that e.g. ``imagep()`` would return tick locations on *both* axes, in a list. It could return lots of other stuff, too. I think this is the R way to get thing working, e.g.
```splus
i <- imagep(...)
gridOce(i$xticks, i$yticks)
```
or some such. I don't know on the name. An analogy to ``grid()`` seems wrong (despite the name) because the first two args should then be ``nx`` and ``ny`` which contradicts the above. An altnative that doesn't have this confusion with ``grid()`` would be e.g.
```splus
i <- image(...)
abline(h=i$yticks)
abline(v=i$xticks, lty='dotted')
```
etc., i.e. we rely on the fact that users understand how to use ``abline``.

Actually, in my own work I prefer to use ``abline`` because I find that the default ``grid`` settings make lines that I can barely see. (This may just be my eyes, though.)

I could see lots of nice things about a return value. For example, ``imagep()`` could be called in an autoscaling sort of mode, and the user could then use the return value to find out how that scale actually got set up.

I am coming around to thinking that pretty much all oce plot functions should return something useful. It would be invisible, so it wouldn't print when you call the function; that way, the old behaviour works as before, and we get some new capabilities. I prefer this to my other idea of global variables (as ``mapproj`` uses) because that is not the normal R way of working.

**Comment by richardsc** [comment]
I tend to avoid `abline()` for grid-like things, because it requires treating the horizontal and vertical lines separately, which is an extra line of code, and I mostly like the defaults so I rarely change them.

One advantage to having a "dedicated" grid function, is it would know what to do with the list return value from something like `imagep()`, `oce.plot.ts()`, or `oce.axis.POSIXct()`. So, if the defaults are set the same as `grid()`, you could do

```r
ip <- imagep(...)
oce.grid(ip)
```
without having to know that the tick locations are stored in `xticks` and `yticks`. 

In line with the `oce.axis.POSIXct()` and `oce.plot.ts()` functions, which already use the "dot" notation but are not actually generic functions, I would propose as above, i.e. 

```r
oce.grid()
```

**Comment by dankelley** [comment]
Yes, I like the idea. and I guess the name maybe should have the dot.

Are you reasonably settled on the syntax you suggest in the immediately previous comment? I think it's a good syntax, and I'm inclined to just do it that way and think about changes later.

**Comment by richardsc** [comment]
I think so.

To be clear, you are proposing to:

1. Add silent return values to `imagep()`, `oce.plot.ts()`, `oce.axis.POSIXct()`. Are there any others? Probably `oceContour()` too. (*aside: it seems as though `oceContour` should perhaps have been named `oce.contour` given the other similar functions ...*)

2. Create a function called `oce.grid()` that will behave very similarly to `grid()`, except that it takes the return value from the above functions as a first argument, instead of `nx, ny`, and then uses `abline(h=...); abline(v=...)` to put the grid lines where the ticks are.

**Comment by dankelley** [comment]
1. You're right on the name ``oceContour``. Maybe I'll make an alias.

2. Yes, that's the general idea, but the args are very different for ``oce.grid()``.

PS. it's mostly coded now. I won't push until I do more tests though. I will push once ``imagep()`` works, since then we can see if it "feels" right, before moving on to others.

**Comment by richardsc** [comment]
> 2. Yes, that's the general idea, but the args are very different for oce.grid().

Why should the args be *very* different? I would think that the arg list should look something like:

```
Usage:

     grid(x, col = "lightgray", lty = "dotted",
          lwd = par("lwd"), equilogs = TRUE)
     
Arguments:

     x: return value from imagep() or whatever that contains the x and y tick locations

     col: character or (integer) numeric; color of the grid lines.

     lty: character or (integer) numeric; line type of the grid lines.

     lwd: non-negative numeric giving line width of the grid lines.
```

I guess it makes sense to have an arg that says which axis to do, e.g.

```
ip <- imagep(...)
oce.grid(ip, axis='xy') #default: do horiz and vert grid lines
oce.grid(ip, axis='x') #do only vertical grid lines
oce.grid(ip, axis='y') #do only horizontal grid lines
```

**Comment by dankelley** [comment]
I think it's very different because ``grid()`` takes ``nx`` and ``ny``, which are only permitted to be single numbers. I just pushed the git and will be offline a while.

If you look near line 235 in ``R/oce.R`` you can see a provisional methodology.  It does not have the ``axis`` arg you suggest (although it could) ... right now the idea would be e.g. following to get only x grid.
```splus
ip <- imagep(...)
oce.grid(ip$xat)
```

**Comment by dankelley** [comment]
Hm, back to the name. Doing grep in ``NAMESPACE`` indicates that the majority of functions are using camel case, and that argues that the new function should be named ``oceGrid``, not ``oce.grid``. I wish R didn't have these choices in function names. One solution might be to just provide non-camel names for every oce function, in addition to the camel-case ones (using aliases).

This is what I mean by getting it to "feel" right before stitching the new ideas into a lot of functions. Right now, ``imagep()`` returns a list with items ``xat`` and ``yat``. The "at" in the name is taken from the ``axis()`` argument, so that feels right to me.

The function name, ``oce.grid`` or ``oceGrid`` (or even ``oce_grid``) has not yet gelled in my mind.

I propose returning to this tomorrow.

PS. I used to hate the underline notation but now that Hadley is promoting it, I no longer feel that way. But it seems too late to alias hundreds of function names.

**Comment by dankelley** [comment]
I think the ``imagep()`` test is promising. What I'd like to do next is to code for a second case. I suppose ``oce.plot.ts()`` is the next task, so I'll try that.

Then I'll need to decide what to do about plots that create multi-panel displays, e.g. ``plot.adp`` with default arguments. Frankly, since it's impossible to "return to" old panels, there doesn't seem to be any sense in returning info for all the panels (which is one possibility) but it might make sense to return info on just the last-drawn panel so that the one-panel case acts just like ``imagep()``.

So, there are some things to think about, I think.

**Comment by dankelley** [comment]
I now have ``oce.plot.ts()`` working.  The help page on ``oce.grid`` shows examples with both ``imagep`` and ``oce.plot.ts``. It might be time to make a checklist here. I'd prefer to start with things that I and Clark use, so I hope Clark will feel free to add. It seems to me that the best plan is to start small, in case there is something inelegant about the approach. Eventually I suppose this should get into all the plot generics but I'd like to handle 2 or 3 specific cases first.

A tick will be put next to an item when it's coded, documented, and pushed to GH.

* [ ] plotTS()

**Comment by dankelley** [comment]
This seems to have been addressed...

**Comment by richardsc** [comment]
Yes, I think so, but I've kept it open until I can get a good chance to test it (and we got pretty distracted by the naming issue).

Also, from above it looks like you were going to make `plotProfile()` work with `oce.grid()`. Has that been done?

**Comment by dankelley** [comment]
Sorry, cancel that -- ``plotProfile`` not done yet.  This should be left open, at least until ``plotProfile`` is done (since I mentioned that function).  I'll probably work on this on Saturday

**Comment by dankelley** [comment]
I'm losing track a bit on this issue. Clearly I was thinking of doing something a couple of months ago and now I don't know what it was!  The remaining things seems to be for ``plotProfile()`` but the issue title is about times, so I'm not sure what is requested.

**Comment by richardsc** [comment]
Same here. I'll close (since I think the original issue as stated has been addressed), and open a new Issue.
