### ISSUE TITLE
breaks arg doesn't work in plot.adp()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#585]
Example:
```r
library(oce)
data(adp)
plot(adp, which=1, breaks=seq(-1, 1, 0.5), drawTimeRange=FALSE)
mtext('EXPECT: 3 color levels between -1 and 1', col='magenta', font=2)
```
![screen shot 2015-02-12 at 1 37 00 pm](https://cloud.githubusercontent.com/assets/233584/6174372/3fb68584-b2bc-11e4-943f-95fb4234983b.png)

**Comment by dankelley** [comment]
I'll look at this tomorrow but the code for all of this is so tangled[^1] that I may need to go over it on Saturday.  I know what's causing the problem in the present issue, but I don't want to just tweak it to fix this bug because it may cause another. The work will be in a new branch named ``imagep`` (which I realize is a name that's been used before, and it's probably not even the right name but at least it's not ``develop``).

[^1]: The problem is that there are so many things that may be specified or left missing, and the code has to keep track of all the possible combinations. If each code chunk has ``n`` lines, and if there are ``m`` arguments that either be present or missing, the work takes ``n*2^m`` lines, which gets in the range of 10^2. That means several editor screens, which makes it a bit hard to work with.

**Comment by richardsc** [comment]
Yeah, I understand. I figured I could fix it easily and just make a pull request, but I was afraid of making it worse so I just reported it.

One solution to the tangliness of the code could be to use the `...` arg instead of trying to reproduce all the args of the functions that will be called (e.g. `imagep()`, `oce.plot.ts()`, etc). Maybe that gets more complicated because of the variety of plot types, but might be something to think about.

**Comment by dankelley** [comment]
The ``...`` arg tends to make things confusing, unless passed to only one sub-function. The example below illustrates when ``...`` contains thing not expected by the sub-function.
```
> a<-function(x,y) x
> b<-function(x, ...) a(x, ...)
> b(3,z=3)
Error in a(x, ...) : unused argument (z = 3)
```

**Comment by dankelley** [comment]
I am contemplating using a jump table. It would involve an R comment like the above, and then R code to determine the cases e.g. below. The advantage is that the comment could then get reproduced in the docs, and it should be easier to read (and write) than a paragraph that gets into the tangled mess of what is permitted.
```
# Jump table
# /----------- case number
# | /--------- zlim given
# | | /------- breaks given
# | | | /----- colormap given
# | | | | /--- action
# | | | | |
# 1 F F T Use colormap
# 2 T T x Error: cannot give both zlim and breaks
if (missing(zlim) && missing(breaks) && !missing(colormap)) case <- 1
# more setup for cases, probably a dozen of them. Then a simple sequence of ifs
if (case == 1) {
  # handle case 1, maybe 5 to 10 lines
} else if (case == 2) {
  # etc
```

**Comment by dankelley** [comment]
The issue as stated may be working now in the ``imagep`` branch, with the updated ``585A.R`` test, which does a 3-panel plot (testing the stated bug and also the choice of giving a colormap).

**Comment by richardsc** [comment]
Looks like the issue is fixed now, so I'll close. Did you end up implementing the jump table, or will that be for another day?

**Comment by dankelley** [comment]
The jump table is for another day. This problem was one in passing info from ``plot.adp`` to ``imagep``.
