### ISSUE TITLE
ctdTrim: "bilinear method could not converge on a solution"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#588]
Seeing this warning with a bunch of different `.rsk` files. I'm not sure what the reason is, since I don't really understand what the code in `ctdTrim()` is doing with this bilinear method:

```r
library(oce)
library(magrittr) # just for fun, really
d <- read.oce('050107_20130620_2245cast4.rsk')
d %>% subset(pressure > 2) %>% ctdTrim %>% ctdDecimate %>% plot
```
```
Warning message:
In ctdTrim(.) : bilinear method could not converge on a solution
```
It seems to work, in that it trims, but perhaps there's a step that it's skipping? I've emailed the file.

**Comment by dankelley** [comment]
I think this is fixed now in ``develop``. I made an item in the test suite, which requires private data so it's only useful for CR and me.

PS. The problem was that CTD objects created from ``.rsk`` files did not have a ``scan`` column. The "bilinear" business starts at  ``R/ctd.R`` line 573. What it's doing is to try to model pressure as a function of scan, with a top portion where p=0 and a lower portion where it's linear. I guess it shouldn't really be looking for p=0 as opposed to some small number of metres for the equilibration depth, but I doubt that adding an extra parameter to the ``nls`` search is warranted since 3D searches are likely to be harder than 2D ones.
