### ISSUE TITLE
plot.landsat() fails for panchromatic band

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#592]
Only tried for LANDSAT8 -- as an example I'm using the same image from your [blog post](http://dankelley.github.io/r/2014/07/01/landsat.html). The issue seems to happen only when the landsat object has more than just the `panchromatic` band. Notable this works fine:

```r
library(oce)
l <- read.landsat('LC80080292014065LGN00', band=8)
plot(l)
```

but this one gives the error:
```r
library(oce)
l <- read.landsat('LC80080292014065LGN00', band=c(8, 10))
plot(l, band='panchromatic')
```
```
Error in if (0 == sum(d, na.rm = TRUE)) stop("landsat object has only zero values in \"",  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sum(d, na.rm = TRUE) : integer overflow - use sum(as.numeric(.))
```

**Comment by richardsc** [comment]
Hmm ... seems that I also get the error in the case where panchromatic is the only band in the object, but if I specify which band to plot:
```r
library(oce)
l <- read.landsat('LC80080292014065LGN00', band=8)
plot(l, band='panchromatic')
```
```
Error in if (0 == sum(d, na.rm = TRUE)) stop("landsat object has only zero values in \"",  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In sum(d, na.rm = TRUE) : integer overflow - use sum(as.numeric(.))
```

**Comment by dankelley** [comment]
I think this should work in ``develop`` now. I added an entry to the test suite, which tests your three cases.

PS. the error was a bad idea for checking if the band was full of zeros. We need that check because the TIRS1 band is now being shipped as a matrix of zeros, while they try to fix problems with that sensor. Anyway, I was checking by summing, but you cannot sum integers if the result exceeds 32 bit capacity. This is because R does not have a 64 bit integer. The error it gives is very nice: it tells you that there's no problem summing if in floating point ("numeric") format. Anyway, now I just do ``all(d==0)`` to check for blankness.

**Comment by richardsc** [comment]
Looks, good. Thanks!
