### ISSUE TITLE
should +.section be renamed?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#605]
I am having trouble seeing how to register this as an s3 method (issue #604).

But this makes me wonder -- do we *really* want to hold on to ``+.section``? The name is not very good, because it is not an arithmetic operation. Other appending operations don't take a similar form, and so users will be unlikely to guess this. If we follow the ``ctd`` class, a natural name would be ``sectionAddCtd``. So the question is whether 
```r
section <- section + ctd
```
is more intuitive than
```r
section <- sectionAddCtd(section, ctd)
```

**Comment by richardsc** [comment]
I'm fine with renaming it. In some ways, I really like that syntax because it shows the power of the S3/S4 methods in R, but functionally I think the proposed alternate syntax is just as intuitive.

On the other hand, I think basically every time I've used `+.section` has been in a loop where I loop through a bunch of files and read them in. In that case the functionality is basically the same. You could argue though that if you just wanted to add a bunch of `ctd` objects to a section one at a time, that:
```r
section <- section + ctd2 + ctd3 + ctd4
```
is more intuitive and easier to read than:
```r
section <- sectionAddCtd(sectionAddCtd(sectionAddCtd(section, ctd2), ctd3), ctd4)
```

Maybe `sectionAddCtd()` could have a similar syntax to `makeSection()`, so that you could do:
```r
section <- sectionAddCtd(section, ctd2, ctd3, ctd4)
```

**Comment by dankelley** [comment]
You can do e.g.
```r
s <- makeSection(ctd1, ctd2, ctd3, ctd4)
```
I think.

PS. the reason for renaming is that I just gave up on trying to find how to "register" the function as S3 after quite a lot of trials, and gave up on making it S4 after a shorter time.  I've added ``sectionAddStation`` to ``develop``. I decided that "Station" is a better name, but I can make an alias or change it.

PPS. I have also changed a lot in ``develop`` in the past 2 days. The new R-devel warns of all kinds of things. For example, if a doc has a URL, it checks that the link works.  I actually like that quite a lot, although it made me to a lot of searching for moved links (and I gave up on some, just highlighting as sans-serif without making an actual link).

**Comment by richardsc** [comment]
Right, I think I knew about that format for the args in `makeSection()`. Between that and the new `sectionAddStation()` I think the syntax is functional and intuitive.

Though, I *do* like the idea of also aliasing to `sectionAddCtd()`.

**Comment by dankelley** [comment]
Done.
