### ISSUE TITLE
plot.ctd and plotProfile conductivity options need testing

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#619]
Pull request #618 added functionality to make conductivity profile plots for ctd objects. There are a few things to think about/clean up:

* [ ] Conductivity units: there are 3 possibilities -- ratio, mS/cm, and S/m. The changes made in PR #618 assume mS/cm. See e.g. [line 2856](https://github.com/dankelley/oce/blob/develop/R/ctd.R#L2856) in `ctd.R` and [line 835](https://github.com/dankelley/oce/blob/develop/R/misc.R#L835) in `misc.R` (this is in `resizeableLabel()`)
* [ ] Do we want combo plots, as with salinity? (e.g. `conductivity+temperature`)
* [ ] others?

**Comment by dankelley** [comment]
It seems to me that we need to add ``conductivityUnit`` to the ``metadata`` slot of CTD objects. I guess the choices are ``NA`` (if no conductivity data), ``"ratio"``, ``"mS/cm"`` and ``"S/m"``. I suppose we can assume unit ``"ratio"`` for SBE (not sure, though) and maybe RBR has it somewhere in a table (I don't know ... the code presently just assumes mS/cm).

This all matters for sw properties. Both UNESCO and GSW formulae are expressed in ratio units, so we definitely are going to want to keep track for RBR data because they are reported in mS/cm (I think). The present ``read.logger()`` code copies conductivity directly (thus mS/cm for at least some RBR) so we need a flag.  I guess if we knew the data had been trimmed dog outliers, we could make some guesses based on the range of the data, or something.

**Comment by dankelley** [comment]
I see that ``logger.R`` actually stores conductivity ratio for RBR files, assuming unit mS/cm (see near line 420). Maybe that needs changing, on the idea that the object should store the data as given.

**Comment by dankelley** [comment]
Hm. If the ``metadata`` holds the unit, then we *could* store ratio, and just use the unit later for plotting. I'm not sure of whether this is best, although it might make things easier for the user, who would otherwise have to do e.g.
```r
c <- ctd[["conductivity"]]
t <- ctd[["temperature"]]
p <- ctd[["pressure"]]
unit <- ctd[["conductivityUnit"]]
swSCTp(c, t, p, unit)
```

**Comment by richardsc** [comment]
I like the idea of storing the data as given in the file, and I think you're idea of having a metadata slot for the unit is probably the best way to do this. If we store `ratio`, but write the "original" unit into `ctd@metadata$conductivityUnit` I worry that it could get confusing for the user, with tangled code doing the conversion before plotting, etc.

There are likely to be some ripple effects, because the unit will come up in anything that calculates or plots, so if we think that's the way to go perhaps we should document where changes are required in this thread.

PS. This is only partly related, so I think I'll open a new issue for discussion, but the above example would be *greatly* simplified if `swSCTp()` accepted a ctd object as the first argument. Then the unit could come straight from the metadata without the user ever thinking about it.

**Comment by dankelley** [comment]
Maybe you could pull and try the example for ``?read.logger`` ... it shows one method for how a user might do things. In this example, I've got the user switching to conductivity ratio.  (I think I'd likely do that in my own work because I'd be scared that some one of the many functions dealing with conductivity might not be checking the unit ... so far, none of them checks, because this is just a first stab.)

**Comment by richardsc** [comment]
Sorry for the slow reply. I tried the example, and it seems to work sensibly. I notice that thanks to #627 `swSCTp()` now recognizes the conductivity unit in the object.

**Comment by richardsc** [comment]
I'm reopening this issue, related to the recent discussion re: conductivity stored in ctd objects and the related `conductivityUnit`, as I note that as the code is now, when one does:
```r
plotProfile(ctd, xtype='conductivity')
```
one gets a plot of the conductivity in the file (i.e. as a conductivity ratio), but with an axis labelled as `mS/cm`.

I think this is my fault, because I hacked in the fix to the code in the first place, so I'll have a look at some point today to clean it up and change the default axis label to reflect the actual units that are now stored in the ctd object.

**Comment by richardsc** [comment]
See PR #647. If you approve and merge, I'll close this issue.

**Comment by dankelley** [comment]
Merged. Thanks!

**Comment by richardsc** [comment]
One thought -- if you try the new code you'll see that the axis is labelled "C [ratio]". Is that a sensible way of expressing the unit, when it's not actually a unit?

Or should it be something more obvious like "C ratio"

**Comment by dankelley** [comment]
I think it should be "Conductivity ratio" for the long name and "C" for the short name. I might tweak the code, if it's not using ``resizableLabel()``.

**Comment by richardsc** [comment]
Great! Closed.
