### ISSUE TITLE
as.ctd should have an argument for conductivity

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#620]
Currently the only way to create a ctd object (using `as.ctd()`) that includes conductivity is to use the `other` argument. Seems to me like it makes sense to include `conductivity` as one of the regular arguments.

I don't think the order really matters much, because it should probably always be named, but I would be tempted to stick it after `pressure`, giving:

```r
as.ctd <- function(salinity, temperature, pressure, conductivity,
                   SA, CT,
```

**Comment by dankelley** [comment]
I agree, and will do this at some point. I think it should be me, because there are some tricks involved, e.g. what if both S and C are given and they contradict -- which takes precedence? Also, issues of whether using unesco or gsw. In other words, it's more than just adding a column ... the column has to work meaningfully. And also there is the issue of the various units for C.

**Comment by richardsc** [comment]
Great. It's not high priority, since there is roundabout functionality that works.

**Comment by dankelley** [comment]
I think this is fixed now. I use this now in ``read.logger()``, so that the test code for issue [622](https://github.com/dankelley/oce-issues/tree/master/622) provides a test.

**Comment by richardsc** [comment]
I think this isn't working yet. I made a test case in [`oce-issues/620/](https://github.com/dankelley/oce-issues/tree/master/620) that uses the `a.rsk` file from Issue #622.

You'll see I used `stopifnot()` to check if `conductivity` exists in the new ctd object, which as of now causes the script to fail.

**Comment by dankelley** [comment]
Possibly fixed now?

**Comment by richardsc** [comment]
Yup, seems to work now. Thanks! Closing.
