### ISSUE TITLE
read.logger should create salinity column if it doesn't exist

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#622]
When reading a logger rsk (i.e. RBR) that doesn't have salinity in the database, I think oce should calculate it with a printed warning.

I've emailed a file.

**Comment by dankelley** [comment]
I made a test suite. You'll need to copy over your datafile as ``a.rsk`` to make it work.

I think it's ok now. I don't have many rsk files, so I don't know if this breaks anything else.

PS. the fix was to trim ``names``, because that's used later on as well as for naming the ``data`` columns.  I guess the code could also be using ``names(data)`` later on, but somehow it seemed cleaner this way because I think I use ``names`` in lots of places in oce, instead of using ``names(data)``.

**Comment by dankelley** [comment]
PS. I don't see why ``ctdTrim`` fails on this so I'm going to open up a new issue.

**Comment by dankelley** [comment]
Should be fixed in ``develop`` now. Thanks!

**Comment by richardsc** [comment]
Looks good, thanks!
