### ISSUE TITLE
read.logger() should subtract atm pressure by default

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#624]
My idea is to add a new arg that can be used to preserve pressure unaltered. That way, a default ``read.logger()`` call will subtract pressure, and so will a call to ``read.oce()``, which may be the desired operation in most cases, but yet an expert can set an argument to retain the data as measured.

I need to figure out
* [x] what to call the new arg (will fill in here when decided...)
* [x] how to assess best atm pressure to use (probably use one in the file if it exists, but let user set it ... possibly set it by the argument that tells whether to subtract

**Comment by dankelley** [comment]
I decided to call the arg ``patm``, and the doc will be along the lines:

  \item{patm}{controls the handling of atmospheric pressure. There are three
      alternatives.  (1) If \code{patm} is \code{TRUE} (the default), then an
      estimate of atmospheric pressure is subtracted from the raw data and the
      resultant is the pressure in the return value.  The estimate will be
      \code{atmosphericPressure} in the data table named \code{deriveDepth} or,
      if that is not found, it will be 10.1325 dbar. (2) If \code{patm} is
      \code{FALSE}, then the raw pressures are copied directly to the returned
      object.  (3) If \code{patm} is a numerical value, then it will be
      subtracted from the raw data.}

**Comment by dankelley** [comment]
I've coded this into ``develop`` and added a test suite. The latter uses ``stopifnot()`` to check the action. I think it's ok but maybe @richardsc could check on some of his data?  (I'll close this tomorrow, Sunday, evening unless I hear that there is a problem.)

**Comment by richardsc** [comment]
I like the approach. I wonder if it might be more sensible to have the `patm` arg default to `FALSE`, because:

1. it doesn't break the existing functionality, and 
2. is consistent with how the data are exported from the manufacturer's software. 

At first I thought that it should spit out a warning to say that it's doing something *other* than just reading the data, but I think if the user has to *tell* oce to remove the pressure, a warning would be unnecessary.

Also, in cases where the pressure is altered (e.g. either `patm=TRUE` or `patm=numeric`), it would make sense to add a processing log item.

**Comment by richardsc** [comment]
I like the approach. I wonder if it might be more sensible to have the `patm` arg default to `FALSE`, because:

1. it doesn't break the existing functionality, and 
2. is consistent with how the data are exported from the manufacturer's software. 

At first I thought that it should spit out a warning to say that it's doing something *other* than just reading the data, but I think if the user has to *tell* oce to remove the pressure, a warning would be unnecessary. Note that because of this change, the code in the example for `read.logger` is now wrong.

Based partly on that example, the reason I was thinking this might be better is because the `pressureAtmospheric` variable read from the rsk is almost *always* 10.1325, which is the default value in Ruskin when the loggers are configured. This is fine for deep ocean or quick plotting, but for someone more concerned about what the "real" atmospheric pressure is might want to read the object and do something fancy like in the example. I don't know ... I keep bouncing back and forth on whether I think clarity in function calls or saving keystrokes is better ...

Also, in cases where the pressure is altered (e.g. either `patm=TRUE` or `patm=numeric`), it would make sense to add a processing log item.

**Comment by richardsc** [comment]
Also, I notice that for the example file in `oce-issues/622`, specifying `patm=FALSE` still results in the pressure being corrected. See `622b.R`.

Is this because it is using pressure to calculate salinity?

**Comment by dankelley** [comment]
I've altered the code and created a new test case [622.c.R](https://github.com/dankelley/oce-issues/blob/master/622/622c.R) and I wonder if you could check that and also the new wording for ``?read.logger``?

**Comment by richardsc** [comment]
This seems to be working, though I was confused for awhile because it appears that `read.oce()` doesn't pass the `patm` arg through to `read.logger`. It works fine if you call `read.logger()` directly though.

**Comment by dankelley** [comment]
Sorry about that. I wasn't passing ``...``, but I *was* passing ``type``. It's a bit tricky to parse ``...`` to see if it contains an item named ``type`` so I didn't bother with that ... I just pass in ``...`` now.

I've updated ``622d.R`` to test this. Note the use of ``stopifnot()``, which is a handy way of describing expected behaviour (handy because the script won't run if the condition isn't met).

@richardsc since you're using this in your work, maybe you could take a quick check and put a note here saying if it's ok. Then I can close or do more mods. Thanks!

**Comment by richardsc** [comment]
Great, thanks. This seems to be working now, so I'll close and leave any new problems to new issues.
