### ISSUE TITLE
swSCTp should accept a ctd object

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#627]
This came up in relation to Issue #619, where we are discussing how to deal with instruments that record different conductivity units, and what should ultimately be stored in the object. 

My proposal is that `swSCTp()` should accept a ctd object as the first argument, consistent with many of the other `sw*()` functions (e.g. `swAlpha`, `swBeta`, etc). In this case, the calculation of salinity from an object with C, T, and p could use the metadata `conductivityUnit`, rather than having to specify it as different from `ratio`.

**Comment by dankelley** [comment]
I adjusted ``develop`` and it seems ok now (see code in [627](https://github.com/dankelley/oce-issues/tree/master/627).  I put the test code 627b.R into the test code also, so that if something goes wrong in this part of the code, it will be signalled by a build/check failure.

I'll let you check it before closing, as per policy.

PS. this probably applies to some other functions but I'd appreciate new issues (so that the subject line is all I need to see what the issue is about.)

**Comment by richardsc** [comment]
Seems to work. Thanks!

**Comment by richardsc** [comment]
Makes sense for the reverse function to also accept a ctd object, so see #630.
