### ISSUE TITLE
plotProfile should work with oce.grid

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#634]
Migrated out of the tail end of #581 . `plotProfile()` should interface with the new `oce.grid()` the same as other recently updated functions, such as `imagep`, `oce.plot.ts`, `plot.adp`, `plot.echosounder`, and `plotTS`.

**Comment by dankelley** [comment]
This one is a bit tricky, owing partly to coding issues and partly to the fact that there might be two vertical grids (for combination plots) and the grids may need colour matching to the plot (again, fiddly coding).

Since this issue is quite old and has attracted few "I want it too" comments, and since ``plotProfile()`` has an argument ``grid`` that gets us partway there,  I will likely focus on 4-star issues before I take the admittedly small time (under 2 hours) that I'd need to fix this.

**Comment by dankelley** [comment]
It's 6 months since the last comment, so I figure it's time to fix this or retire it!  I'll have a look.

**Comment by dankelley** [comment]
Hm. `plotProfile()` is something like 800 lines long.  So, yes, this will be tricky to code.

**Comment by richardsc** [comment]
I'm going to close this, because:

1. it has been 8 months since the original report

2. I have not personally encountered a need for this functionality, and 

3. My memory of the original impetus for `oceGrid()` was for time axis, where sometimes the tick marks weren't at regular intervals (e.g. months). I don't see why `plotProfile` would ever have anything other than a regular axis and grid.
