### ISSUE TITLE
Discussion re: conductivityUnit for logger vs ctd objects.

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#644]
Actually, just continuing the discussion from #642 about whether or not to store `conductivityUnit` in the logger object, and then what to do with it when `as.ctd()` is called.

Currently ctd objects store C-ratio, reasoned as:

> My opinion is that loggers should have whatever unit the manufacturer uses, but that ctds should have conductivity ratio because (a) that is what many data files contain, (b) that's what UNESCO formuale use and (c) that's what GSW formulae use, (d) it would be arduous and error prone to tweak every function that uses conductivity to permit a value with a unit and (e) as.ctd() is available to get something from a logger unit into the ctd style.

The question then is whether oce should try and read the conductivity unit from the raw file that is being converted, such as a logger `.rsk` or an SBE `.cnv`. This would facilitate the conversion to C-ratio, without the need for ad hoc tests (that might fail for some cases, e.g. low salinity water).

**Comment by dankelley** [comment]
Good questions. I just made ``read.logger()`` save ``@metadata$conductivityUnit`` in the case of a ``.rsk`` file, so that part is done. 

We still have the issue of ``.cnv`` files. This is tricky stuff because there seem to be variations in the headers, e.g. the sample file in oce lacks conductivity, but to show the variance in header formats, notice that it has
```
# name 2 = pr: pressure [db]
# name 3 = depS: depth, salt water [m]
```
while an Arctic file I have on my machine has two conductivity probes and the header line looks like
```
# name 1 = prDM: Pressure, Digiquartz [db]
# name 2 = depSM: Depth [salt water, m]
``
Well, I can see how to make a pattern recognizer for these two, but the question is how many other variations are out there in the wild...

PS. the Arctic file has two conductivity probes, with header:
...
# name 5 = c0mS/cm: Conductivity [mS/cm]
# name 6 = c1mS/cm: Conductivity, 2 [mS/cm]
```
so it seems that a pattern to get the unit might be as in e.g.
```r
h <- "# name 5 = c0mS/cm: Conductivity [mS/cm]"
unit <- gsub(":.*","",gsub(".*=[ ]*","",h)) # may have chars at start
> length(grep("S/m", unit))
[1] 0
> length(grep("mS/cm", unit))
[1] 1
```
and so forth.  In any case, one thing is clear: **I was wrong in thinking cnv files stored unitless conductivity**.

**NOTE.** I think we should be dumping data files into the issues website. See the README there for a convention that might help. Doing this will help on keeping track of the possibilities that occur in the datafile headers. Also, if both CR and DK put in files that represent their own work, we will be more likely to find errors and chances for improvement.

**Comment by dankelley** [comment]
I put two .cnv files in the [644 issue page](https://github.com/dankelley/oce-issues/tree/master/644) and ``develop`` now infers ``metadata@conductivityUnit`` in both cases. I'm not saying any other part of the code handles those units correctly ... the first step is just to decode the header lines and save into metadata.

**Comment by richardsc** [comment]
> We still have the issue of .cnv files. This is tricky stuff because there seem to be variations in the headers, e.g. the sample file in oce lacks conductivity

Unfortunately I think it will be almost impossible to code for this completely generally, as the generation of a `.cnv` file *always* requires a human being to process the raw (`.hex`) file using a GUI program. Which variables get output to the cnv is a matter of clicking and selecting, which means that it will almost always be different, and that the metadata formats have likely changed in time.

On the topic of duplicate conductivity sensors, which is very common on rosette CTD systems (also dual temperature sensors) -- how does oce currently parse such files? Will it read in both? It would make sense to read it and assign data to `conductivity` and `conductivity2` or something?

**Comment by dankelley** [comment]
@richardsc Do you happen to know how much of the header is human entered? For example, a ``grep -i oxygen *.cnv`` in the issues directory shows (in a SLEIWEX file)
```
03dk.cnv:# name 8 = sbeox0Mm/Kg: Oxygen, SBE 43 [umol/Kg]
03dk.cnv:# name 9 = sbeox0Mg/L: Oxygen, SBE 43 [mg/l]
03dk.cnv:# name 10 = sbeox0PS: Oxygen, SBE 43 [% saturation]
03dk.cnv:# name 11 = sbeox0ML/L: Oxygen, SBE 43 [ml/l]
```
which makes me worry about trying to interpret the stuff between ``=`` and ``:`` because it's inconsistent ("M" for micro in name 8 but "M" for milli in name 11). However, the stuff in the ``[ ... ]`` seems rather more sensible. I'm wondering whether both get entered by the operator, or neither, etc.

**Comment by richardsc** [comment]
Hey, that's a good idea to thread comments and replies! I also like the "email-style" quote and response.

> Dan wrote:
> I think in almost all work I've done for myself, salinity is present in the cnv files. Basically, this is a scheme in which it's assumed that the user running the GUI program knows which sensors ought to be combined to create salinity. This seems sensible, for someone else looking at the various columns would have a hard time knowing what the sensors were set up to do (and whether they worked ok).

Outputting salinity in the cnv file is a choice the user makes when running the GUI, and is not a required output. One may choose to not output salinity because the goal is merely to write a file of the *raw* measured data, for further processing by someone else or another institution. The issue is that the SBE software that creates the cnv files (SeaSave, I think) *also* performs many of the data processing steps that we would do within R (upcast removal, "wild point edit", sensor lagging, C-cell thermal mass corrections, and finally pressure/time averaging).

As for the duplicate conductivities (and temperatures): if salinity *is* present in the file, it means that the user has made a decision about *which* variables to use for the calculation, possibly based on information exterior to the file (e.g. bottle calibrations). If oce can read *all* fields from the cnv then it would allow the analyst to evaluate which are best on their own terms. Just a thought.

> Dan asked:
> Do you happen to know how much of the header is human entered? 

I don't think much is actually *human entered* (except for comments), but the decision of which channels or derived variables to write to the cnv is definitely *human decided*. The output of the `name N = ...` fields is controlled by the software, and I don't know where along the line the decision to use such wacky units is made. It does suggest that grepping for the name *and* what's inside the `[...]` might be a good way to parse what is actually in the table columns.

**Comment by dankelley** [comment]
I like that idea of checking both.

A few other things have come to mind:
1. handle the various temperature units (of which I think only two are in active use)
2. add args to ``read.ctd.sbe()`` to let the user control things precisely, based on whatever inside knowledge they happen to have (e.g. give column number for a quantity, and give its unit also).
3. ``as.ctd()`` may need similar arguments to specify units.
4. Any changes have to be compatible with a pretty full range of files, including the ones in the issue repo and others that should be added there ... and I really think we need more test files to justify a lot of coding and user-visible changes.
5. Temperature should be dealt with also; see my [blog posting](http://dankelley.github.io/r/2015/05/10/ITS90-temperature-scale.html)
6. Probably pressure has a whack of different units too, but I am guessing that any variation will be swamped by questions of removing atmospheric pressure.

**Comment by richardsc** [comment]
I made a new branch called `conductivity`, where we can start cleaning up this `conductivityUnit()` stuff and where we can add functionality. 

For example, in commit ccadc913aa I added an `xtype='conductivity+temperature'` option to `plotProfile()`. I haven't updated the docs yet, so it might not build right now.

No need for you to wade in guns-a-blazing right now, but I'd like to get this sorted before the next CRAN submission. I've been looking at conductivity quite a bit, and this functionality makes "processing from raw data" much easier.

**Comment by dankelley** [comment]
Sounds good. Please stay away from ``R/sw.R`` and ``man/sw*Rd``, because I'm messing with them a lot lately and we don't want to get too confused on merge conflicts. As for ``R/ctd.R``, perhaps just stay away from ``as.ctd()`` and ``read.ctd.sbe()``, since those are things that may changing the most on my end, as I work on the T90 task. I find that git can merge reasonably well if the changes in the files are well separated. But cleaning up a merge conflict is sometimes really quite tricky.

**Comment by dankelley** [comment]
@richardsc -- do you remember where we are on this?  It's been several weeks since the last comments. My preference would be to close this (given that we have discussed it, quoting from the title) and to have new issues on precise things that need doing.

**Comment by richardsc** [comment]
I agree. I'll close this and open a more general issue to address the need to better incorporate `conductivityUnit` for ctd objects.
