### ISSUE TITLE
need functions for IPTS-68 and ITS-90 interconversion

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#646]
I've put some thoughts on my [blog](http://dankelley.github.io/r/2015/05/10/ITS90-temperature-scale.html).

One other thing: The GSW functions seem all to be using ITS-90, whereas the UNESCO ones are using IPTS-68, I assume.

**Comment by richardsc** [comment]
Strangely, this T conversion issue is not something that has *ever* occurred to me when calculating seawater properties with instrumental data. However, it clearly should be done, especially when using UNESCO-80 with data from newer (i.e. post 1990) instruments.

I know that the RBR units have the temperature unit in the db, though it is also safe to assume that they all use ITS-90 since there are no RBR instruments that are even that old. Old SBE files might be an issue, but as noted in the link from your blog post everything SBE has done since 1995 has been ITS-90.

**Comment by dankelley** [comment]
``develop`` now has conversion functions, but I plan to leave this open for a while, to remind me to think of how to handle things otherwise. For example, perhaps ``swRho()`` should detect this. However, there is another possibility: if a CNV (or other) file has clearly marked IPTS-68 data, maybe the ``oce`` object should save ``temperature`` as ITS-90 and ``temperature68`` as the IPTS-68. This way, existing code that expects ITS-90 will work properly.

NOTE: the difference is not large, e.g.
```r
T68 <- seq(3, 20, 1)
T90 <- T90fromT68(T68)
sqrt(mean((T68-T90)^2))
```
yields just 0.003 degC, which is not going to show up on a profile. I don't have specs for old instruments, like the one used in our class at Dal, which generated ``data(ctd)``, but I sort of doubt that I'd trust them to 3 millidegrees.

**Comment by richardsc** [comment]
Bumping this again so that we can think about it some more before a potentially new version of oce gets submitted. 

I was browsing the WHP manuals today, and found this one by Fofonoff and Millard:

https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/whp/manuals/pdf/91_1/algo6.pdf

which does a bunch of tests consistent with the one you did just above. Note that the conclusion of those tests is:

> The ITS-90 has a significant effect on the calculation of salinity as the PSS-78 algorithm was developed on the IPTS-68 temperature scale. The following tables of salinity differences at two conductivity ratios indicate the magnitude of the error when conversion of ITS-90 to IPTS-68 is ignored.

**Comment by dankelley** [comment]
I made a new label (and marked it thus). Maybe we can do this for the things we really want to get done for the next release. This label should be applied to things that are timely, important and achievable, and should not be applied to every new issue because that would mean there could never be a new release. Of course, we can always unlabel things if the need for a release outweighs the desire to fix something (e.g. UHL is a hard problem and we can't really let that block a new release, so it should not get this label).

**Comment by dankelley** [comment]
This is not quite a trivial issue. Decisions need to be made about what to store in objects. Documentation needs to be made clearer (if an arg is called "temperature" what does that mean?). Some algorithms may need adjustment (e.g. are unesco functions looking for 68 or 90 version?).

**Comment by richardsc** [comment]
Agreed that it's not trivial. The question will be how much work should we do to make it easier for users, i.e. to insulate them from having to think about it?

Here are my thoughts:

1. Mostly likely just about every sensor in use today (and for the last 20+ years) records ITS-90. Therefore the `temperature` field in objects should be documented as such and no changes made to the default behaviour when reading data.

2. If a user knows that they have temperature values corresponding to IPTS-68, then a `metadata` item called `temperatureUnit` is added to indicate as such. The original IPTS-68 temperature could be stored in a field called `temperature68` and an ITS-90 field `temperature` is created and added to the object (and to the processing log).

3. Since the UNESCO formulae are based on IPTS-68, any calculations involving the `temperature` field stored in the object should be converted before passing to the appropriate `sw*()` function. For calculations done on vectors (i.e. *outside* of the object, doing something like `swTheta(S, T, p)`), it is up to the user to read the documentation and know the temperature convention.

4. Because `gsw` and TEOS-10 use ITS-90, no changes should be required when using `eos='gsw'`.

Anything I've missed? Thoughts?

Though it is a relatively small error (*O(0.005)* psu), it's too bad we never thought about this before, even from the documentation standpoint.

**Comment by dankelley** [comment]
I think we agree on all the points. 

As a side note, ``data(ctd)`` uses t68 even though the sample was taken in 2003, within your guess of 20 years. But we use an old machine for that, since it's just for teaching. This is convenient, in a way, because regenerating that dataset will be a test of the updated ``read.ctd()``.

I had a look at some Arctic data starting in 2003, and the data for 2003 don't list a unit, while the others all list t90. I'll have a look in some WOCE archives to see what units they give.

This is going to be quite "fiddly" work, and I'll likely do it in stages, starting with ``read.ctd.sbe()`` and moving on to ``swRho()`` and then ``as.ctd()``. I'd prefer to get just a few common functions working (to decide on coding, how to phrase the documentation, etc) as opposed to trying to do everything at once. 

There are lot of functions to tackle; ``grep sw NAMESPACE`` reveals 30 that will need doc updates, and then we have ctd-related functions that are going to require some coding.

My very first step (probably Saturday) will be to tackle ``read.ctd.sbe()``, since this is a workhorse for a majority of users so it's a good test for the user interface for dealing with these things.

Thanks for noticing this!!

PS. the idea of the new label is that clicking on that brings up all the "show stopper" bugs. This can prevent remembering an important issue the day after a release.

**Comment by dankelley** [comment]
I've made ``read.ctd.sbe()`` handle this now:

1. ``read.ctd.sbe()`` now handles IPTS-68 files. What it does is to save the original data as e.g. ``ctd[["temperature68"]]`` and to put the ITS-90 values into e.g. ``ctd[["temperature"]]``. The metadata stores ITS-90 as ``temperatureUnit`` after this automatic conversion.

2. I updated ``data(ctd)`` and ``data(ctdRaw)`` accordingly.

3. A new item in the build-test suite is enough to verify that this works.

**Comment by dankelley** [comment]
After updating ``read.ctd.sbe()`` I started work on ``swRho()``. As is my habit, I've been working on the docs and the code at the same time, and isolating this to this one function, ``swRho()``, to avoid a lot of rewriting later.

The question is: what should be the unit of ``temperature`` in an ``swRho()`` call? I have thought of several possibilities, and coded and documented each, not liking any of them very much.  Maybe @richardsc can comment (but note that none of this is in ``develop`` yet ... it's all too plastic until I decide more firmly on the UI).

Note that I am only talking about the ``temperature`` argument, not the case in which the first argument is a ctd object ... the latter is a separate case and is a matter of coding, not UI.

1. ``IPTS-68``. This will break the calculation if a user is supplying ``ctd[["temperature"]]`` and they have IPTS-68 data, but I think this is a rare case. (And note that the ``data(ctd)`` and ``data(ctdRaw)`` cass are both now updated.)

2. ``ITS-90``. I like this better because old code (on most newish data) will have the values as anyhow. It puts a bit of a burden on ``eos="unesco"`` users, but if they are using the old EOS they probably don't care about three digits after the decimal anyway.

3. *switchable* i.e. assume IPTS-68 for one ``eos`` value or ITS-90 for the other.  This is what I started to code at first, but it is pretty tricky to code and as I was writing the docs I realized that it might confuse users, also.

From the above, I prefer style 2. The docs I've written (again, not on GH) are as follows. Am I clear? If not, please put a comment within the comment, with new text.
```latex
  \item{salinity}{either practical salinity (in which case \code{temperature}
    and \code{pressure} must be provided) \strong{or} an \code{oce} object, in
    which case \code{salinity}, \code{temperature} (in the ITS-90 scale; see
    next item), etc. are inferred from the object.}

  \item{temperature}{\emph{in-situ} temperature [\eqn{^\circ}{deg}C], as defined
    on the ITS-90 scale.  This scale is used by GSW-style calculation (as
    requested by setting \code{eos="gsw"}), and is the value contained within
    \code{ctd} objects (and probably most other objects created with data
    acquired in the past decade or two). Since the UNESCO-style calculation is
    based on IPTS-68, the temperature is converted within the present function,
    using \code{\link{T68fromT90}}.}
```

**Comment by dankelley** [comment]
Below is a checklist of functions I'll need to examine, many of which will need recoding. I will add the word "*irrevelvant" for any that are unaffected. I will put a tick in the box when (a) the code works, (b) the docs have been updated and (c) the built-test suite checks values.
* [ ] ``swAbsoluteSalinity()``
* [ ] ``swAlpha()``
* [ ] ``swAlphaOverBeta()``
* [ ] ``swBeta()``
* [ ] ``swConservativeTemperature()``
* [ ] ``swCSTp()``
* [ ] ``swDepth()``
* [ ] ``swZ()``
* [ ] ``swDynamicHeight()``
* [ ] ``swLapseRate()``
* [ ] ``swN2()``
* [ ] ``swPressure()``
* [ ] ``swRho()``
* [ ] ``swRrho()``
* [ ] ``swSCTp()``
* [ ] ``swSigma()``
* [ ] ``swSigmaT()``
* [ ] ``swSigmaTheta()``
* [ ] ``swSigma0()``
* [ ] ``swSigma1()``
* [ ] ``swSigma2()``
* [ ] ``swSigma3()``
* [ ] ``swSigma4()``
* [ ] ``swSoundAbsorption()``
* [ ] ``swSoundSpeed()``
* [ ] ``swSpecificHeat()``
* [ ] ``swSpice()``
* [ ] ``swSTrho()``
* [ ] ``swTFreeze()``
* [ ] ``swThermalConductivity()``
* [ ] ``swTheta()``
* [ ] ``swTSrho()``
* [ ] ``swViscosity()``

**Comment by richardsc** [comment]
I think that I also prefer your option 2, i.e. 

> 2. ITS-90. I like this better because old code (on most newish data) will have the values as anyhow. It puts a bit of a burden on eos="unesco" users, but if they are using the old EOS they probably don't care about three digits after the decimal anyway.

and I like the docs you provided above. Let me know what I can do to help.

**Comment by dankelley** [comment]
@richardsc - one way to help would be to look at the new docs for ``swRho()`` and see if the writing is OK. My plan is for other manpages to refer to that one, e.g. ``swTheta()`` does that now.

You say "I think" and so a second way to help is to say if you still think the same way. This is, after all, a disruptive change. Howevever, I still think it's a good change, especially going forward, since the IPTS-68 scale has been "gone" for a long time. Below is an example of the size of the change:
```r
> options(digits=10)
> swRho(30,10,100)
[1] 1023.506185
> swRho(30,T90fromT68(10),100)
[1] 1023.506575
> (swRho(30,10,100)-swRho(30,T90fromT68(10),100))/swRho(30,10,100)
[1] -3.806111075e-07
```

**Comment by richardsc** [comment]
Great, I'll have a look a the docs.

And yes, I still think the same way about what is the best course of action here. I prefer the idea that the function arguments are consistent, regardless of the eos used, because I think ultimately that will be simpler for the user. In addition any new data is almost guaranteed to be ITS-90. As long as the docs are clear re: temperature units, and the reading of ctd objects automatically does the 68to90 conversion if it knows the temperature is T68, there should be a minimum of confusion.

**Comment by dankelley** [comment]
I feel this has all been done in ``develop``, commit 86fbad5c5cce3cc68d52edd20b35d82f56e430b8. Therefore I am closing this.  Any new issues can be more specific, e.g. that a particular function does something wrong. I realize that only probably CR and I will ever notice such things, and only then by looking at docs or code, because the differences in practical work are very small compared with data wiggles.
