### ISSUE TITLE
Section Plot

### ISSUE THREAD

**Issue by ajcanepa** [dankelley/oce#657]
Hi All,
First of all thans, many thanks to Dan Kelley for make this package.
I'm very new with it and my question is about "fine tunning" of the section plot. In my case I'm plotting a section in a fjord area (Chilean Patagonia) and the salinity changes happen just in the few first meters (from 0 to 15 meters). My sectionGrid object was built until 200 meters because at this depth we have measurements.
So, my question if is there any option or program over there to make a "cut" in the section plot?. Let say to plot the first 20 meters and after a horizontal cut to plot (as usual) the rest of depths sampled in the section?...attached a screen-shot of an already section plot with some commercial software (can be surfer?)
![salinity_section](https://cloud.githubusercontent.com/assets/10628672/7965006/20f722e8-09f1-11e5-869a-5007f4898072.jpg)

Thank you for your time and help, any advice will be very appreciated!!

Regards,

Antonio

**Comment by dankelley** [comment]
Hi. There is no way to do this as oce is presently set up. If the ``plot`` method for sections permitted an argument ``axis=FALSE`` then this could be done with ``par(mfrow)`` etc, but in your example the x axis was not present in the top plot (I imagine you'd like it in the bottom plot).

I think I should add an ``axis=FALSE`` ability to the ``section`` variant of ``plot()``, because then it would be easy to turn off axis labelling. If you'd like to see that, let me know, and also post here whether you are able to build R packages from source (which is a requirement to get updates between CRAN releases).

If you visit [oce-issues/657](https://github.com/dankelley/oce-issues/blob/master/657/657.R) you will see R code that is similar to that I put below, which yields a graph like I am including here. This might help.
```r
library(oce)
data(section)
top <- sectionGrid(section, p=seq(0, 200, 5))
bottom<- sectionGrid(section, p=seq(200, 6000, 100))
if (!interactive()) png("657.png")
layout(matrix(1:2, nrow=2), widths=1, heights=c(0.25, 0.75))
plot(top, which="temperature", mar=c(1, 3, 1, 1))
plot(bottom, which="temperature", mar=c(3, 3, 1, 1))
if (!interactive()) dev.off()
```
![657](https://cloud.githubusercontent.com/assets/99469/7966214/e6e5b594-09f8-11e5-93d7-c189bf3318c9.png)

**Comment by richardsc** [comment]
I'm going to jump in here with a "Yea" for adding an `axis=FALSE` argument to `plot.section()`. I've wanted this before even just when stacking plots (with a consistent x-axis). My work around was typically to re-grid the data separately and plot using `imagep()` or `oceContour()`, but for quick plots it's hard to beat `plot.section()`.

**Comment by ajcanepa** [comment]
Dear Dan,
Thank you so much for your help....I'll check this code. However the idea to have an axis=FALSE ability to the section variant of plot(), will be excellent....moreover with the abiliy to set axis=False. About my ability to build package from source, If I understand the question, I think I can compile source packages using "install.packages(path_to_file, repos = NULL, type="source")", inside RStudio. If I'm wrong I can figure out how to build R packages from source. Now I just have installed the CRAN distribution of "oce" package.
Again, many thanks!!

**Comment by dankelley** [comment]
I had another person suggest an ``axis`` argument, so it's popular!  Will do.

**Comment by ajcanepa** [comment]
Excellent!,
Just a one more question. ¿Can be the label of temperature (the bottom-right square with "T") removed from the top panel?
Thank you!

**Comment by dankelley** [comment]
I updated the ``develop`` branch. Please install it, and then you can try the new sample file
```r
library(oce)
source("~/src/oce/R/section.R")
data(section)
top <- sectionGrid(section, p=seq(0, 200, 5))
bottom<- sectionGrid(section, p=seq(200, 6000, 100))
if (!interactive()) png("657b.png")
layout(matrix(1:2, nrow=2), widths=1, heights=c(0.25, 0.75))
plot(top, which="temperature", mar=c(0, 3, 1, 1), axes=FALSE, legend.loc="")
axis(2, at=pretty(par('usr')[3:4]))
plot(bottom, which="temperature", mar=c(3, 3, 0.4, 1))
if (!interactive()) dev.off()
```
which should make as below.  Note that it is a bit "fiddly" (requiring extra knowledge of how margins work, etc) but it should be reasonably useful. At some point I could put in another argument to yield split windows, but frankly I prefer the present approach because it lets the user decide how to set up gridding (and often smoothing) differently for the different panels.
![657b](https://cloud.githubusercontent.com/assets/99469/7968412/144f8c86-0a07-11e5-818c-689198b7dca7.png)

**Comment by dankelley** [comment]
@ajcanepa -- is this handled now? If you think so, please close the issue. In the "oce" project, we generally leave the issue closing to the reporter. That way, we can be more certain that we have been of help. Thanks. Dan.

**Comment by ajcanepa** [comment]
Dear Dan Kelly,
Many thanks for everything!...It works perfect now!....
I'm working into add vertical profiles of abundance (like violin plots)...If I have more questions, I'll come back!.
Thanks again!

Antonio
