### ISSUE TITLE
Something has broken the `as.ctd` salinity functionality for RBR files

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#662]
I'm not sure when this happened, but now when I do

```r
library(oce)
d <- as.ctd(read.logger('file.rsk'))
```
I get:
```
Error in as.ctd(d) : no salinity in oce object
```

Note that I'm working from the current `develop` branch (i.e. 9de602f0a4). I'm guessing this came in with changes related to the `odf` and `bremen` classes?

**Comment by dankelley** [comment]
Good catch.  I was working to make ``as.ctd()`` more general. It now checks whether the first argument is inherits from  ``oce``, and if so, tries to extract salinity etc. The idea is to improve generality. But I forgot that RSK data may lack salinity!  Silly moi.

I updated both oce and the oce-issues (642) for this. Can you check?

Sorry about this. The new scheme should be better than the old one, when the kinks are removed. I want the code to do something sensible for any object (including sections, lowered adcps, etc., and of course including loggers, soon to be called ``rsk``).

**Comment by richardsc** [comment]
Thanks. There seem to be some other things missing, as when I re-run some code (that works for the current CRAN version) using `ctdFindProfiles()` I get this error:

```r
library(oce)
d <- as.ctd(read.oce('file.rsk'))
p <- ctdFindProfiles(d)
```
```
Error in if (inferWaterDepth && !is.finite(res@metadata$waterDepth)) { (from 03.R#37) : 
  missing value where TRUE/FALSE needed
```

It looks like a different error from the thread title, but I suspect it's related (i.e. not parsing all the same information from the `logger` object that it used to), so I'm posting here.

I've also added another case to oce-issues/642 that demonstrates.

**Comment by richardsc** [comment]
Hm. I thought that the current CRAN version worked, but I just installed and tried and got the same error ... :(

**Comment by dankelley** [comment]
@richardsc -- I see an email which I think was a cc from a bug report here. Maybe the comment you deleted? Anyway, I think it *is* a bug. The following
```R
library(oce)
d <- as.ctd(read.oce('file.rsk'))
p <- ctdFindProfiles(d)
```
gives
```
Error in if (inferWaterDepth && !is.finite(res@metadata$waterDepth)) { : 
  missing value where TRUE/FALSE needed
```
which is a bug.  I've made a new issue test code and will look at this bug later this morning.

**Comment by dankelley** [comment]
I think the new ``ctdFindProfiles()`` bug is now fixed in ``develop``. @richardsc was this the gist of the comment that you deleted ... and is the bug fixed for you now?

PS. this ``waterDepth`` has caused several problems lately. Knowing water depth is important for section construction, since not all experiments involve driving the rosette as deep as possible. WOCE-class data always seem to have a water depth, and even lots of coastal data do too. But I have to do a trick wih ``as.ctd()``. I had forgotten to do that, but you can tell from the diff below what I've done ... if the user provides it in the ``as.ctd()`` call, we use it ... otherwise, do something at least halfway sensible and use max pressure.
```
diff --git a/R/ctd.R b/R/ctd.R
index 5b11e67..bdc61d6 100644
--- a/R/ctd.R
+++ b/R/ctd.R
@@ -162,6 +162,8 @@ as.ctd <- function(salinity, temperature, pressure, conductivity,
         mnames <- names(ctd@metadata)
         res <- new("ctd")
         res@metadata <- ctd@metadata
+        if (is.na(waterDepth) && !("waterDepth" %in% mnames))
+            res@metadata$waterDepth <- max(ctd[["pressure"]], na.rm=TRUE)
         res@data <- ctd@data
         res@processingLog <- processingLogAppend(res@processingLog, paste(deparse(match.call()), sep="", collapse=""))
         res <- ctdAddColumn(res, swSigmaTheta(res@data$salinity, res@data$temperature, res@data$pressure),
```

**Comment by dankelley** [comment]
PS. I think I got myself mixed up on which issue was which, so my previous comment has been edited back and forth a bit. I added an overall target in the test suite called ``asctd`` and this may help us in future if I remember to update that. (Only I should edit the overall Makefile, because otherwise we are going to get merge conflicts on almost every issue.)

**Comment by richardsc** [comment]
Sorry, I should have just edited the comment rather than delete it. The actual bug report related to `waterDepth` was just above that comment. The comment I deleted said that the issue also arose for the CRAN version of `oce`, which was not true.

the `develop` branch now works as before (at least for the code I've been running in the last week or so), so I'll close the issue.

Thanks!

**Comment by dankelley** [comment]
Reopening until I go through the ``as.ctd()`` code again. There is some code there that is no longer being invoked (because an ``rsk`` object is a sub-class of an ``oce`` object) and I want to be sure there is no "good stuff" in that unused code block, before I delete it.

**Comment by dankelley** [comment]
As the one who reopened this, I am now closing it again because I think I fixed it 9 days ago ... in any case, it can be reopened or another bug report given
