### ISSUE TITLE
as.ctd and lon/lat time series

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#669]
I've run into a series of warnings that occur when I create `ctd` objects using `as.ctd()` that have vectors for `longitude` and `latitude`. Basically, if I do something like:

```r
library(oce)
data(ctd)
lon <- rnorm(ctd[['time']])
lat <- rnorm(ctd[['time']])
ctdnew <- as.ctd(ctd[['salinity']], ctd[['temperature']], ctd[['pressure']],
                 longitude = lon, latitude = lat)
plot(ctdnew)
```
I get:
```
Warning messages:
1: In range(coastline[["longitude"]], na.rm = TRUE) - x@metadata$longitude :
  longer object length is not a multiple of shorter object length
2: In x@metadata$longitude + c(-1, 1) * min(abs(range(coastline[["longitude"]],  :
  longer object length is not a multiple of shorter object length
3: In range(coastline[["latitude"]], na.rm = TRUE) - x@metadata$latitude :
  longer object length is not a multiple of shorter object length
4: In x@metadata$latitude + c(-1, 1) * min(abs(range(coastline[["latitude"]],  :
  longer object length is not a multiple of shorter object length
```

This seems to be because the metadata field for `longitude` and `latitude` contain vectors instead of the expected single values, and the plotting directive to make the map can't handle vectors.

Another approach could be to use `ctdAddColumn()` to add the `longitude` and `latitude` vectors to the `@data` slot, but this has the disadvantage that it does not work with the default `plot.ctd()`:

```r
ctdnew@metadata$longitude <- NULL
ctdnew@metadata$latitude <- NULL
ctdnew <- ctdAddColumn(ctdnew, lon, 'longitude')
ctdnew <- ctdAddColumn(ctdnew, lat, 'latitude')
plot(ctdnew)
```
```
Error in if (asp < asp.page) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In min(abs(range(coastline[["longitude"]], na.rm = TRUE) - x@metadata$longitude)) :
  no non-missing arguments to min; returning Inf
2: In min(abs(range(coastline[["latitude"]], na.rm = TRUE) - x@metadata$latitude)) :
  no non-missing arguments to min; returning Inf
```

What do you think is the best solution here?

**Comment by dankelley** [comment]
I knew this would come up!  I avoided answering it when I was looking at some glider data the other day ... but that was just because the thing doesn't go far on one glide!

Maybe ``as.ctd()`` should detect whether ``longitude`` is of length 1 or length [put in metadata] equal to ``salinity`` [put in data] or otherwise [error case]. What do you think of that?

In other words, I'm hoping for input on the plan of the data. How it gets handled in plotting, etc., is as easy one way as another, but I think we can use this as a sort of talisman case, in which information might be "metadata" or "data".  (Another case might be time ... it could the a single number for when the profile was made, or time as the device logged data.)

The plotting can always check one place and then another -- that's no problem.

**Comment by richardsc** [comment]
> Maybe as.ctd() should detect whether longitude is of length 1 or length [put in metadata] equal to salinity [put in data] or otherwise [error case]. What do you think of that?

I think this scheme makes sense. As you say the plotting can be adopted for the different cases but this is an example of where something can blur `metadata` and `data`. This has probably come up in a tangential way for `adp` objects, which sometimes have position data and sometimes don't -- but one might want to actually enter a single location, as for a mooring.

**Comment by dankelley** [comment]
I did some work on this in ``develop``. Testing is going to be important since ``as.ctd()`` is an important function. Therefore, in addition to the new [oce-issues tests](www.github.com/dankelley/oce-issues/669) I have expanded the build-test suite (not to include multiple lon and lat, but as a start to include how lists and data frames are added, which I also tried to improve).

My decision was to keep lon and lat in metadata. This is partly because a CTD doesn't typically measure those things, but another big factor is in code simplification. (The user should typically not know or care where things actually get stored.)

@richardsc -- it would be great if you could test on some of your data, because breaking ``as.ctd()`` will hurt quite a few users who might be building from ``develop``.

**Comment by richardsc** [comment]
My only concern with putting lon/lat in `metadata` is what happens when a ctd object is trimmed, using either `subset.ctd()` or `ctdTrim()`?

To test, I added [669b.R](https://github.com/dankelley/oce-issues/blob/master/669/669b.R) to `oce-issues` -- note that trimming the `ctdnew` object using either `subset()` or `ctdTrim()` results in an object with no data.

I *fairly* sure that these are new errors, but the `ctdTrim(ctd, method='scan', ...)` (from issue #670) is new so there may be some other bugs creeping in.

**Comment by dankelley** [comment]
Will look tomorrow. I don't know what I'd do without you, man!

**Comment by richardsc** [comment]
What would you do without me? A lot more research, probably! :)

Anyway, scratch my previous comment about the "no data" objects, turns out it was an ID10T error in `669b.R`. Pull `oce-issues` again and the figures will make fine.

**However,** my suspicion about having lon/lat in `@metadata` is true -- they do not get trimmed. E.g.:

```
> length(ctdnewSubset[['scan']])
[1] 101
> length(ctdnewSubset[['longitude']])
[1] 181
```

**Comment by dankelley** [comment]
I have updated ``develop`` and the ``oce-issues/669b.R`` and I think this bug is fixed. Note that I have decided on a blended strategy: if only one lon/lat pair is available, it goes into metadata, but otherwise it goes into data. This means that subset should work now, etc.

I added a test like in your previous comment into ``tests/ctd.R``, using ``stopifnot()``, which BTW is a great function to use in issue tests, too.

**BEWARE:** I did a lot of refactoring in ``rsk.R`` and ``oce.R``, to clarify the code. (I know this kind of thing can lead to new bugs, but I think the risk is outweighed by the improved code structure, which should be more flexible and fixable.)

**Comment by dankelley** [comment]
@richardsc -- any chance of a check? I'm trying to clear up the 4-star issues.

**Comment by richardsc** [comment]
Sure! Some points:

1. I see that when a `ctd` object is created with a vector (i.e. length > 1) lat and lon, the vectors go into the `@data` slot. It also appears that single valued lat and lon go into `@metadata`, which from the code appear to be averages. Correct?

2. Because of the single-valued `@metadata` lat and lon, when doing a `plot(ctd)` the map always shows a single point instead of the vector position.

3. If the `@metadata` lat and lon are averages one could get a false impression that a profile taken over a long time (either in strong currents, or from a glider) was in fact taken at a single location. I think it would be better to plot the vector lat and lon.

Thoughts?

**Comment by dankelley** [comment]
I went back and forth on where to put (and whether to put in two places).  I think it should be one or the other, actually, and I'll recode for that. Then the plot method would check for it in metadata first, then in data, and wouldn't have to decide what to do if in both.

**Comment by richardsc** [comment]
I like that idea. Then `ctd[['longitude']]` is unambiguous, because the accessor will only find it in *either* `@metadata` or `@data`.

**Comment by dankelley** [comment]
I think this is better in ``develop`` now (commit e85d51f58c7c8faed81060d49c874328e12793b6). I'm not sure we have sufficient tests in [oce-issues](www.github.com/dankelley/oce-issues/669) but maybe if the original reporter can pop some more tests in there, we could be good to close.

**Comment by richardsc** [comment]
Looks good!
