### ISSUE TITLE
mapPlot is *very* slow for limited view maps

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#672]
It seems like most of the time is being taken up by the axis labelling ...

```r
library(oce)
data(coastlineWorld)
lonlim <- c(-75.25, -75.15)
latlim <- c(38.78, 39.14)
tt <- system.time(mapPlot(coastlineWorld, longitudelim = lonlim, latitudelim = latlim))
print(tt)
```
```
   user  system elapsed 
 30.238   1.490  31.834 
```

31 seconds is *bewilderingly* slow just to make a map of Delaware Bay. I haven't dug into the code yet, but perhaps you have an idea why this takes so long?

See sample code in `oce-issues/672`

**Comment by dankelley** [comment]
I'll have a look, perhaps tonight. I also find it pretty annoying, so I want to figure it out.

**Comment by dankelley** [comment]
1. If I use ``projection="+proj=merc"`` it gets twice as fast on my machine.

2. I think the problem rests with the small grid. What ``mapPlot()`` is doing is drawing *all around* the globe. This is silly when we know the lon and lat limits, though. I will change it to draw within a region (say) 5X larger than the lon-lat limits.  (It is necessary to go beyond the limits given by e.g. ``longitudelim`` because the *actual* limits will depend on plot geometry.)

**Comment by dankelley** [comment]
Commit a766aee61a5414243ef3973bd073b039394c650c in ``develop`` now does the test cases for this issue in under 0.5s on my machine, a speedup of more than 100X.

**Comment by dankelley** [comment]
I wonder if this is fixed now?

**Comment by richardsc** [comment]
Yup, seems good now. Thanks!
