### ISSUE TITLE
Trouble reading CTD data from Teledyne RDI's CTD-NV

### ISSUE THREAD

**Issue by eduardocrichard** [dankelley/oce#678]
Dear all,

I've been trying to read CTD data using read.ctd with no success. I have tried several files but all return the same error message, which is:
```
Error in read.ctd("POS-KW1-P12.ctd") : Cannot discover type in line '›'
```

Since ``type`` argument accepts SBE19, WOCE, ODF and ODV I suppose read.ctd doesn't support .ctd files generated by Teledyne RDI is that correct? Is there any other function that supports it?
Thanks a lot!

**Comment by dankelley** [comment]
Maybe you could email me a sample file so I could have a look? dan.kelley@dal.ca

**Comment by eduardocrichard** [comment]
Sent.

**Comment by dankelley** [comment]
Hi. The files are in a binary format. I was hoping for text-based, because then a solution would be quite quick for you.  If you can find some documentation on the format, it's possible I could code something for you. I can't make any promises though, especially about how long it would take. Sometimes decoding binary data is somewhat easy but sometimes it is very painstaking.

So, in summary:
1. Please try to find documentation on the binary format. This will be something that describes what each byte in the file means. If you can find that, please send it to me by email. I could have a go at it on Saturday morning.

2. Your best solution might be to use some RDI software to convert to text-based format. Often manufacturers provide something to do that.

**Comment by eduardocrichard** [comment]
I don't have the software, only the data. I'll try to download RDI software, though I think they only ship it to you when I buy  any equipment. 
I'm also gonna check for the convertion routine.
Thanks a lot!

**Comment by dankelley** [comment]
Good luck. Others have found RDI to be quite helpful, so if you don't find what you want by looking on their website, you might make progress by contacting them directly, asking for software or documentation on the file format.

**Comment by dankelley** [comment]
I noticed that the first few dozen bytes were identical on the two files you sent. Other RDI instruments signal the file type with the first two bytes. On that assumption, I have made ``oceMagic()`` tentatively identify the file type as ``"possibly RDI CTD"`` if the first two bytes are ``0x9b`` and ``0x00``. If this interferes with other file types, I'll have to remove that.  Thus, if someone tries ``read.oce()`` on one of these files, the message will be as follows ... the point is to encourage others to also look into getting the file format documentation.
```
Error in read.oce(file) : unknown file type "possibly RDI CTD"
In addition: Warning message:
In oceMagic(file) :
  Possibly this is an RDI CTD file. Oce cannot read such files yet, because
 the author has not located file-format documents.  If you get such documents
 from RDI, please send them to dan.kelley@dal.ca so the format can be added.
```

**Comment by eduardocrichard** [comment]
I have contacted then through e-mail, let's wait and see if they reply.
Additionally I've been looking for help with some other oceanographers
friends that are more used to deal with ctd data than I am.

I don't really know why these data are in binary, but thank you for all
attention anyway and obviously congratulations on oce  package.

Cheers,
Em 26/06/2015 08:36, "Dan Kelley" <notifications@github.com> escreveu:

**Comment by dankelley** [comment]
I am closing this issue, since it's been over 3 weeks and still no documentation on the data format. Of course, this can be reopened with the click of a mouse, if we get the format. Thanks, @eduardocrichard, and good luck.  Dan.
