### ISSUE TITLE
Plot ADP

### ISSUE THREAD

**Issue by marbiouk** [dankelley/oce#681]
Hi Dan et al,

Is there an easy way of doing beam averaging or simple math on the ADP class data and plotting it, i.e. 

plot(adp, which=mean(5:8))

or

plot(adp, which=5*n)

To generate a single plot?

Also in plot.adp, if I add the ylab argument (i.e. to change it from Distance [m] to something else (i.e. round brackets) it springs the error below as:
Error in imagep(x = tt, y = x@data$distance, z = z, xlim = xlim[w, ],  : 
  formal argument "ylab" matched by multiple actual arguments

I can't set lab to NA either.

Thanks, sorry if this isn't the right place to put this.

**Comment by richardsc** [comment]
Hi @marbiouk, 

This is definitely the place to put these sorts of things. The advantage to having issues instead of personal emails is that someone else might benefit from previous questions/answers.

## 1. plot.adp() and which

`plot.adp()` currently has some `which=` options for plotting distance or time averaged velocities (i.e. 19-22 and 24-27), but not for the backscatter. Unfortunately I don't think there is a simple way of performing arithmetic operations on the `which=` arguments, because really they are just tests used in a series of `if () else if ()` blocks in the code. E.g. you can see the tangled next of `if` statements by doing

```r
getMethod('plot', 'adp')
```

One way to get what you want would be to do the desired operations on the object and save it to a *new* object, which could then be plotted with `plot.adp()`. For example:

```r
library(oce)
data(adp)
adpMean <- adp
adpMean[['a']] <- adpMean[['a', 'numeric']] # convert `a` array from raw to numeric
adpMean[['a']][,,1] <- apply(adp[['a', 'numeric']], c(1, 2), mean) # the [,,1] dim is now the mean
plot(adpMean, which=5)
```

To be honest though, `plot.adp()` was not really meant to make complicated plots of derived fields, and I think you'd be better off just making plots manually using the lower-level functions, such as `imagep()`. For the beam averaged backscatter I would do that something like:

```r
a <- adp[['a', 'numeric']]
amean <- apply(a, c(1, 2), mean)
d <- adp[['distance']]
t <- adp[['time']]
imagep(t, d, amean)
```

## 2. plot.adp() and `ylab`

Thanks for pointing this out. What is happening is that `ylab` is hardcoded into the function itself, and any attempt to pass a different one using the `...` args causes a collision. Perhaps this should be changed to provide the default only when the user doesn't specify a `ylab`.

For your case, if what you want is round brackets in the label, you can do this more generally by setting the `oceUnitBracket` with

```r
options(oceUnitBracket='(')
```
which changes the default bracket type for units on oce plots.

**Comment by marbiouk** [comment]
@richardsc Thanks, that's perfect, that is excellent. I have made great progress in the last half hour. My next issue follows imagep, it doesn't like the following arg, for example, if I just want to remove the x axis labels from the plot, usually in R we'd use  xaxt='n'. imagep ignores it, is this intentional.

**Comment by dankelley** [comment]
Yes, ``imagep()`` does not handle ``xaxt``. It could be made to handle that argument, if there is a strong need. Note that you'd need to be able to build oce from source, to get the new feature (if it's added). Thanks.

**Comment by dankelley** [comment]
You can get the equivalent to ``xaxt="n"`` by using ``axes=FALSE`` and then drawing the x and y axis. So that's just one more step compared to an ``xaxt`` solution.

**Comment by richardsc** [comment]
To say that anything we have done is "intentional" implies that we have a grand plan for all the functionality that currently exists :). I feel like Dan and I have discussed this before, and there was a reason why we didn't include it, but it escapes me now.

To clarify on Dan's solution, you can do something like:

```r
imagep(t, d, a, axes=FALSE)
axis(2)
box()
```

**Comment by marbiouk** [comment]
Thanks @richardsc and @dankelley for your help, incredibly good software and a life saver for me. The extra step work around is not a problem. I'll integrate that into the workflow. Thanks again.
