### ISSUE TITLE
R-devel build problem with enviroment

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#683]
I fixed up some problems with namespace, but there are still 3 problems with R-devel:

```
* checking R code for possible problems ... NOTE
mapPlot: Error while checking: invalid 'envir' argument
tidemVuf: Error while checking: invalid 'envir' argument
webtide: Error while checking: invalid 'envir' argument
```

I'm just citing them here so @richardsc can see the updates ... sorry for not opening an issue on the namespace problem and my fix.

**Comment by dankelley** [comment]
In this comment I'll list some links ... I won't make another comment for links, since I don't want this to be a multi-page-scroll issue.
* https://github.com/trinker/pacman/issues/66
* https://github.com/rpremraj/mailR/issues/22

**Comment by dankelley** [comment]
I am making some progress on this, step by step. Since it's a hassle installing R-dev on my own box (e.g. cannot build the 'rgdal' package, for some reason). I think this is a moving target, e.g. today it caught something it hadn't caught during a previous build. I will just keep plugging away at it. My main question now is how to handle data, e.g.
```
plot,adp: no visible binding for global variable 'coastlineWorld'
plot,adp: no visible binding for global variable 'coastlineWorldFine'
plot,adp: no visible binding for global variable 'coastlineWorldMedium'
```

**Comment by dankelley** [comment]
As of commit fdd60d912b7d30443e152bfb260489232118f44d, the ``develop`` branch passes the win-builder tests properly. I will still be on the lookout for new problems, though, since it seems that code-checking is an important feature of R-devel.  (PS. I tried to install R-devel myself, and it was really quite difficult, e.g. I couldn't build ``rgdal`` because something about my PROJ.4 installation was not right. Maybe with the R-consortium we will get the ability to try out R-devel without large admin effort...)

**Comment by richardsc** [comment]
Great. I haven't bothered to try installing R-devel because I don't want to mess with a working system (in fact, I'm still on 3.2.0 because of that libpng bug), but when the time comes I'll upgrade and will be able to do independent checks.

Also, if it's a pain to do winbuilder checks more than once or twice a day, I can easily do Windows checks in the evening on my windows machine.

Finally, since `rgdal` seems to pass the R-devel checks ([http://cran.r-project.org/web/checks/check_results_rgdal.html](http://cran.r-project.org/web/checks/check_results_rgdal.html)), it's too bad that they don't provide binaries built from the check for testing purposes ...

**Comment by dankelley** [comment]
PS. if you download the rgdal binary, it segfaults. At least it did on my box. Basically, R-devel is hard to use ... I think this causes extra problems for CRAN because people find it hard to test against R-devel but when they go to submit ... bam.
