### ISSUE TITLE
axis labels have inconsistent spacing inside parentheses

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#685]
As illustrated in the snapshot, ``resizableLabels()`` has inconsistencies in the spacing inside parentheses (or square brackets). I think it should be consistent, but the question is: which is best? In the bottom axis left-hand panel, the bracket is nudged up to the content, and that looks slightly tight to my eye, although I think it obeys typographic convention so it's OK. In the horizontal axes of right-hand panel, a space is used inside the brackets, and this looks slightly *too* spaced-out to me. Maybe I should be using a phantom(".") or whatever R calls it. @richardsc  -- any opinion?
![screen shot 2015-07-03 at 10 55 24 am](https://cloud.githubusercontent.com/assets/99469/8500459/c4548636-2172-11e5-90f7-24ef86a4c1d0.png)

**Comment by richardsc** [comment]
Personally, I like the "tighter" version. It's curious to my why two things that use the same code would have different spacing though ...

Interestingly, I noticed this discrepancy the other day too. I came up because I was using `plotProfile()` (which uses `resizableLable()`) alongside a plot that required a manual label:
![01-station-001-tdiff-001](https://cloud.githubusercontent.com/assets/233584/8501505/25c576cc-2174-11e5-804a-8ab8d5bc2c11.png)

The plot on the left is just a call to `plotProfile(d, xtype='temperature')`, and the one on the right was a call to the normal `plot()`, followed by:
```r
mtext(expression(dT~group('[', degree*C, ']')), line=par('mgp')[1])
```
Notice that aside from the spacing difference, the square brackets plot for the plot on the right are taller.

**Comment by dankelley** [comment]
This came up because ``resizableLabel()`` is a long list of special cases, and they were written at different times, maybe when I had a different aesthetic sense.

I will switch them all to the tighter version. I may see if there is a way to lead the way to a "tightness" argument, although this kind of code is hard to edit because it is non-DRY.

**Comment by dankelley** [comment]
I pushed to ``develop`` a trial version that I think will be helpful. So far it only handles the ``"T"`` case. A test code is
```r
library(oce); xlab<-resizableLabel("T", psep="^");plot(1:3,1:3,xlab=xlab)
```
and a snapshot of the code (showing it's much prettier ... argument enough for me to switch) is below.
<img width="493" alt="screen shot 2015-07-03 at 2 07 35 pm" src="https://cloud.githubusercontent.com/assets/99469/8502919/1d572206-218d-11e5-9b3d-9eab8e23b586.png">

**Comment by dankelley** [comment]
I've made the results of ``resizableLabel()`` be more consistent. I decided to use less space, but now ``options(oceUnitSep=" ")`` can be used to add space.
