### ISSUE TITLE
read.rsk now removes patm by default, when it shouldn't

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#690]
This is probably related to recent changes (of which there were quite a few, and I haven't had a chance to follow them closely), but I notice now that `read.rsk()` removes atmospheric pressure by default now, e.g. see [Line 172 in ctd.R](https://github.com/dankelley/oce/commit/0d22c3ce4f4d748956a8df3055728e7d6c1f0e51#diff-b9ffe32ba07808beeebaef329f4f875bR172).
> CR: I'm mixed up. Your link is to ``ctd.R``, not ``read.rsk()`` within ``rsk.R`` ... see comment thread below; prob best to chat on phone. -DK

This is contrary to the docs, which state that the argument `patm` controls the removal of atmospheric pressure, and it should be `FALSE` by default.

Perhaps we need to have a phone conversation to decide about what to do about the fact that the RSK pressures are "absolute", and not "sea pressure", and how to make those changes without breaking too many other things? E.g. the current version breaks all my code that reads RSK files, because I have `patm=TRUE`, and so it removes *an extra* 10.1 dbar.

Also, see on Line 172 that the default to remove if `pressureAtmospheric` is not defined is 11.4. What is that number from? Shouldn't it be 10.13?
> CR: yes, fixed in ``develop`` now. -DK

**Comment by dankelley** [comment]
Thanks for checking! These fixes will take maybe 20 minutes and I may do them before I go in to work.

1. These are flat-out errors, not design decisions. As you note, there were a lot of changes to things lately. or example, ``read.rsk`` used to be able to return a ``ctd`` object, but now it returns only ``rsk``, no matter what. (Well, that's my design ... I will check that the code does that and the docs say that.) The reason for this was the realization that ``rsk`` (and ``odf``, etc.) is a *new* type of object, stemming from a data-file type, not an instrument type. The new paradigm will be
```r
d <- read.oce("...")
plot(d) # if you don't know much about it
plot(as.ctd(d)) # if you know (or guess) that it can be considered a ctd
```

2. I wish we could have a small ``.rsk`` file for inclusion in oce so that the test suite could read the file and check things. That would make us immune to code changes. The only publically avail file I know of is ``sample.rsk`` but (a) it is very long, 300k, which makes it as large as ``topoWorld`` (the largest datafile) and (b) it lacks pressure and conductivity. I wonder if RBR might be able to put on their website a small file that is CTD-ish. (By small I mean of the size of files in ``oce/inst/extdata``, maybe under 10 to 20k, which is enough for a typical ctd cast.) I see in oce-issues ``642`` that we have something called ``file.rsk``, but I don't know where that came from, and I assume it's private.

3. Regarding a phonecall, possibly 0900 my time, or 1030 my time? I may still be in other meetings then, though, so I'd ask that you ring my office phone 3 times and give up if I don't answer. I suspect I'll have the code fixed in less time than it took to type this, though.

**Comment by dankelley** [comment]
Hm, maybe we *should* talk! I see the docs as below. I don't think we want that. I think we want to store the pressure from the file, no ifs, ands, or buts. The user can always alter pressure later, in the same way that they could alter any other field, if they have knowledge and even minimal skill to use ``[["pressure"]]``. So I will propose to change the doc I've written below. It might make sense to discuss that here or on the phone. OK, now below the text from ``?readrsk``

```latex
 \item{patm}{controls the handling of atmospheric pressure, an important issue
    for RBR instruments that record total pressure, i.e. the sum of atmospheric
    pressure and sea pressure. There are three alternatives.  (1) If \code{patm}
    is \code{FALSE} (the default), then total pressures are put in the return
    value. This means that profile plots will start at what appears to be
    approximately 10 metres depth. It also leads to errors in the calculation of
    pressure-dependent seawater properties.  However, note that if salinity is
    calculated by \code{read.rsk}, an estimate of atmospheric pressure is first
    subtracted. The estimate is \code{atmosphericPressure} in the data file or
    10.1325 dbar if the file lacks that value. (2) If \code{patm} is
    \code{TRUE}, then the above-stated estimate of atmospheric pressure is
    subtracted from the raw data.  (3) If \code{patm} is a numerical value, then
    it will be subtracted from the raw data.}
```

**Comment by dankelley** [comment]
I see another problem in the docs.  (I am keen to look at the docs first, then the code. I have this bad habit of changing code without docs.)  For ``?trimRsk`` I see as follows. This is a remnant from what we wanted for SLEIWEX work. But I don't think it's consistent with how we handle RSK pressure anymore, so I propose to change it. (We can't be timid on altering code that probably only the two of us have used ... I don't actually recall a single contact from anyone regarding rbr data...)

OK, below the text that I don't like. I don't think we should remove pAtm (last paragraph).
```latex
\details{The \code{"water"} method is mainly for quick and dirty work.  In many
  cases, the user will be working with several files, and so it will make sense
  to use the \code{"time"} method, to synchronize the time series.  Normally,
  notes will have been taken in the field, so no guessing need be done about the
  time the instruments went in the water.  In some cases, though, the time will
  have to be inferred from the data, and so it might make sense to start by
  trimming with the \code{"water"} method, after which \code{\link{summary.rsk}}
  is used to find the probably time when the instrument was put into the water.

  After the data are trimmed in time, the pressure record is modified by
  subtracting 10.1325~dbar, the average sea-level pressure.
}
```

**Comment by dankelley** [comment]
I updated the ``as.ctd`` incorrect patm. A diff is below. Note that the line numbers differ from your statement at the start (you were using an old ``develop``).
```diff
$ git diff HEAD^1
diff --git a/R/ctd.R b/R/ctd.R
index 6cd274f..2e48b18 100644
--- a/R/ctd.R
+++ b/R/ctd.R
@@ -181,7 +181,7 @@ as.ctd <- function(salinity, temperature, pressure, conductivity,
         pressure <- d$pressure
         ## "rsk" stores total pressure, not sea pressure as "ctd" stores.
         if (inherits(o, "rsk")) {
-            pressure <- pressure - if (is.na(m$pressureAtmospheric)) 11.4 else m$pressureAtmospheric
+            pressure <- pressure - if (is.na(m$pressureAtmospheric)) 10.1325 else m$pressureAtmospheric
         }
         ## "rsk" stores conductivity (in mS/cm, not as ratio), and does not store salinity
         conductivity <- d$conductivity
```

**Comment by dankelley** [comment]
I think we do need a phonecall so I can tell exactly what you mean. I'm guessing that the problem is that ``as.ctd()`` is subtracting patm, but you don't want it to do that because ``read.rsk()`` already subtracted it? If that's the case, then some thought will be required. I think the object will need to record that ``as.ctd()`` should not further subtract.

To be honest, I think ``read.rsk()`` should not permit subtraction of atm pressure, *except* in one way: it needs to subtract *something* in order to get salinity.  But maybe it shouldn't try to get salinity. Maybe ``as.ctd()`` should be tasked with that. After all, if we read an adcp dataset, we don't calculate say detided currents ... we just try to read the data and let users do extra things. But this is something we really should talk about, partly because it relates to RBR instruments that exist and might exist, and also to what people would like to do with them. Part of my problem in the sloppy code may be just that I've never worked with them (after the pT sensors from SLEIWEX, which were in ascii format).

Sorry for all the comments. I had some time before going to work. I realize that the code fixup is going to require some thought, so I spent my time jotting down ideas.

**Comment by dankelley** [comment]
I have rewritten ``read.rsk()`` and ``as.ctd()``. A test file is now provided in oce, and this is used for build tests in ``oce/tests/rsk.R``, and I've tried to document this quite clearly so that the test can be used to evaluate correctness. This can break us from the common problem where bugs get fixed but they comeback.

@richardsc -- if you have some time, perhaps you could build ``develop`` and look at the docs on ``read.rsk()`` and ``as.ctd()``, focussing on the ``patm`` and ``atmosphericPressure`` arguments. Then, please have a look at the test code, to see if you agree with the tests.  We know the tests will pass -- that's not the question. The question is whether the things tested for are what readers would expect, based on reading of the docs. If it is not, then this issue needs more work, even if it happens to work in your own particular way of working with data. (I think I have all 6 possible test cases, so your way should be in there ... or have I missed something?)

I am doing something here that I plan to do more, in addressing issues. Whenever feasible, I'd like to assess whether issues are fixed by developing formal test code within the build-tests. This will mean that we will be sure bugs have been fixed and we can see quickly when they come back. Granted, inventing test code can be tricky, but if we have a pattern of using it within oce-issues tests, then it won't be too hard to incorporate them into the test suite.

**Comment by richardsc** [comment]
Looking good! A few points:

1. In the doc for `read.rsk()`, the stated value for S35T15 conductivity is 42.914, but I'm pretty sure that it is 42.91754 mS/cm (at least from the `swCSTp` docs).

2. The example should be updated, since: it currently is wrapped in a `## Not run` block, and it should probably use whatever rsk file we end up including in the package. Also the recent changes make the 

  `ctd <- as.ctd(rsk, pressureAtmospheric=patm)`

  line obsolete.

I'll look at the tests next ...

**Comment by dankelley** [comment]
Turns out it's a bit tricky doing things with ``decompressFile()``. That is in R.utils, and doing ``library(R.utils)`` causes lots of function shadowing. That means the user sees a screenful of scary messages when oce launches, which I definitely don't want.  I'm looking into this.

**Comment by dankelley** [comment]
I'm not even sure we'll be able to have these tests in CRAN (see below from R-devel). But I think there is a way to designate tests as non-cran. (Certainly that's easy in examples.)
```
* using log directory 'd:/RCompile/CRANguest/R-devel/oce.Rcheck'
* using R Under development (unstable) (2015-07-11 r68646)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'oce/DESCRIPTION' ... OK
* this is package 'oce' version '0.9-18'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Dan Kelley <Dan.Kelley@Dal.Ca>'

Possibly mis-spelled words in DESCRIPTION:
  ADCP (15:69)
  CTD (16:16)
  rgdal (20:27)
* checking package namespace information ... OK
* checking package dependencies ... NOTE
  No repository set, so cyclic dependency check skipped

Package suggested but not available for checking: 'ncdf4'
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'oce' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking for GNU extensions in Makefiles ... OK
* checking compiled code ... OK
* checking sizes of PDF files under 'inst/doc' ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... ERROR
Running examples in 'oce-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: read.rsk
> ### Title: Read a rsk file
> ### Aliases: read.rsk
> ### Keywords: misc
> 
> ### ** Examples
> 
> library(oce)
> ## A CTD-style rsk
> if (requireNamespace("R.utils")) {
+   file <- system.file("extdata", "sample.rsk.gz", package="oce")
+   tmp <- tempfile(fileext=".rsk")
+   R.utils::decompressFile(file, destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
+   rsk <- read.rsk(tmp)
+   ctd <- as.ctd(rsk)
+   plot(ctdTrim(ctd))
+ }
Loading required namespace: R.utils
Warning in file(file, "r") :
  cannot open file 'd:/RCompile/CRANguest/R-devel/oce.Rcheck/examples_i386/D:\temp\RtmpGUYumI\file29ac3bed3fed.rsk': Invalid argument
Error in file(file, "r") : cannot open the connection
Calls: read.rsk -> file
Execution halted
** running examples for arch 'x64' ... ERROR
Running examples in 'oce-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: read.rsk
> ### Title: Read a rsk file
> ### Aliases: read.rsk
> ### Keywords: misc
> 
> ### ** Examples
> 
> library(oce)
> ## A CTD-style rsk
> if (requireNamespace("R.utils")) {
+   file <- system.file("extdata", "sample.rsk.gz", package="oce")
+   tmp <- tempfile(fileext=".rsk")
+   R.utils::decompressFile(file, destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
+   rsk <- read.rsk(tmp)
+   ctd <- as.ctd(rsk)
+   plot(ctdTrim(ctd))
+ }
Loading required namespace: R.utils
Warning in file(file, "r") :
  cannot open file 'd:/RCompile/CRANguest/R-devel/oce.Rcheck/examples_x64/D:\temp\Rtmpeep79Z\file21902dea53ec.rsk': Invalid argument
Error in file(file, "r") : cannot open the connection
Calls: read.rsk -> file
Execution halted
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
** running tests for arch 'i386' ... ERROR
Running the tests in 'tests/rsk.R' failed.
Last 13 lines of output:
  +     stopifnot(all.equal.numeric(ctd[["pressure"]], rsk[["pressure"]]))
  +     ## III.b
  +     rsk <- read.rsk(tmp, patm=10)
  +     ctd <- as.ctd(rsk, pressureAtmospheric=1)
  +     stopifnot(all.equal.numeric(ctd[["pressure"]], rsk[["pressure"]]-1))
  + }
  Loading required namespace: R.utils
  Error in file(file, "r") : cannot open the connection
  Calls: read.rsk -> file
  In addition: Warning message:
  In file(file, "r") :
    cannot open file 'd:/RCompile/CRANguest/R-devel/oce.Rcheck/tests_i386/D:\temp\RtmpAZRgfW\file28805eb5c83.rsk': Invalid argument
  Execution halted
** running tests for arch 'x64' ... ERROR
Running the tests in 'tests/rsk.R' failed.
Last 13 lines of output:
  +     stopifnot(all.equal.numeric(ctd[["pressure"]], rsk[["pressure"]]))
  +     ## III.b
  +     rsk <- read.rsk(tmp, patm=10)
  +     ctd <- as.ctd(rsk, pressureAtmospheric=1)
  +     stopifnot(all.equal.numeric(ctd[["pressure"]], rsk[["pressure"]]-1))
  + }
  Loading required namespace: R.utils
  Error in file(file, "r") : cannot open the connection
  Calls: read.rsk -> file
  In addition: Warning message:
  In file(file, "r") :
    cannot open file 'd:/RCompile/CRANguest/R-devel/oce.Rcheck/tests_x64/D:\temp\Rtmp0oTkJM\file202c4b9e2914.rsk': Invalid argument
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking running R code from vignettes ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 4 ERRORs, 2 NOTEs
```

**Comment by dankelley** [comment]
I may do the tests with [testthat](http://r-pkgs.had.co.nz/tests.html) and wrap these ones in the flag that says not to do them on cran. I'm really not too concerned about the cran tests ... so long as they work locally, we know they work.

**Comment by dankelley** [comment]
I learned how to use ``testthat``, and it is much nicer than the old way. When tests pass, they are nearly silent. But when they fail, they report lots of useful stuff. This prevents a problem I was having, in which I wrote a test, it failed, then I had to write in new code to spit out the values of the things I was checking. See ``tests/testthat/test_rsk.R`` for an example of usage.

**Comment by dankelley** [comment]
I'm feeling that this has been solved, and we're waiting for a check. Therefore, changing labels.

**Comment by richardsc** [comment]
I think this is looking good, and I've had a look at the `testthat` tests to make sure they're sensible. Closing!
