### ISSUE TITLE
read.rsk() and as.ctd() have differing names for atm pressure

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#691]
They should be the same. I prefer the longer name (``pressureAtmospheric``, used by ``as.ctd``) because ``patm`` (used by ``read.rsk``) might not mean much to some readers. @richardsc - any opinion on this?

**Comment by richardsc** [comment]
Well, I agree that names should be consistent, but actually the two different names are not for the same thing. In `read.rsk()` the `patm=` argument is a logical flag that says whether to *remove* atmospheric pressure (which is stored as `@metadata$pressureAtmospheric` in the rsk object) from the pressure as stored in the file. 

In `as.ctd()` the `pressureAtmospheric=` argument is for specifying the magnitude of the atmospheric pressure, which subsequently also gets stored as `@metadata$pressureAtmospheric`.

Perhaps the issue is actually that `patm=` is a bad argument name for the task it implies, and should be something like `removeAtmosphericPressure=TRUE`, or `removePressureAtmospheric=TRUE`, or `removePatm=TRUE`, or `seaPressure=TRUE`, or ...?

The only request I'd make if the `patm` arg is changed is to (at least temporarily) retain an alias so that dozens of my recent scripts don't break all at once ...

**Comment by dankelley** [comment]
Actually ``patm`` may be logical or numeric; see ``?read.rsk``, case 3.

Perhaps ``read.rsk()`` should be left the same, and ``as.ctd()`` changed. An argument for this is that ``pressureAtmospheric`` requires a lot of typing, to distinguish it from the other ``as.ctd()`` argument named ``pressure``.

I am going to leave this on the back burner for a while. I'll try to figure out how to code the other  ``read.rsk()`` and ``as.ctd()`` things first. Also, I think to some extent I need to wait until I can get a good test file, before I'll be using these things much personally ... and it's a bit hard to write code when I'm not using it, at least a little.

**Comment by richardsc** [comment]
> Actually `patm` may be logical or numeric; see `?read.rsk`, case 3.

Ha, classic case of RTFM! I forgot about that option.

I don't really think it's a big deal to type `pressureAtmospheric`, since most IDEs (Emacs and RStudio anyway) do argument completion with the TAB key. It's also consistent with the name `pressure`, as well as with how other fields are named, such as `waterDepth`, `sampleInterval`, etc.

**Comment by dankelley** [comment]
OK, makes sense. Conclusion--I won't change the names of the args. Closing. Thanks!
