### ISSUE TITLE
as.ctd(read.rsk(...)) should populate empty metadata fields

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#692]
Using `as.ctd()` to manually create a ctd object, say by doing something like:
```r
ctd <- as.ctd(salinity=1:10, temperature=1:10, pressure=1:10)
```
automatically creates empty `@metadata` fields for all the options that were not specified, e.g.:
```
> str(ctd@metadata)
List of 23
 $ header          : NULL
 $ type            : chr ""
 $ model           : chr ""
 $ filename        : chr ""
 $ serialNumber    : chr ""
 $ filename.orig   : chr ""
 $ systemUploadTime: NULL
 $ ship            : chr ""
 $ scientist       : chr ""
 $ institute       : chr ""
 $ address         : chr ""
 $ cruise          : chr ""
 $ station         : chr ""
 $ date            : chr ""
 $ startTime       : chr ""
 $ recovery        : chr ""
 $ waterDepth      : int 10
 $ sampleInterval  : logi NA
 $ names           : chr [1:5] "salinity" "temperature" "pressure" "sigmaTheta" ...
 $ labels          : chr [1:5] "Salinity" "Temperature" "Pressure" "SigmaTheta" ...
 $ src             : chr ""
 $ longitude       : logi NA
 $ latitude        : logi NA
```

However, using `as.ctd()` on an rsk object *only* populates the metadata with the rsk metadata fields. An example (using the currently included `rsk` dataset with a kludge to add conductivity):
```r
data(rsk)
rsk@data$conductivity <- rnorm(rsk[['time']])
str(as.ctd(rsk))
```
```
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 5
  .. ..$ filename        : chr ""
  .. ..$ conductivityUnit: chr "mS/cm"
  .. ..$ waterDepth      : logi NA
  .. ..$ names           : chr "sigmaTheta"
  .. ..$ labels          : chr "Sigma Theta"
  ..@ data         :List of 6
  .. ..$ pressure    : num [1:145] -0.186 -0.245 -0.198 -0.214 -0.254 ...
  .. ..$ temperature : num [1:145] 11.3 11.3 11.3 11.3 11.3 ...
  .. ..$ salinity    : num [1:145] 1.006 0.4644 0.0453 NaN 0.6074 ...
  .. ..$ conductivity: num [1:145] 1.4498 0.692 0.0688 -0.9474 0.8948 ...
  .. ..$ sigmaTheta  : num [1:145] 0.3621 -0.0632 -0.3912 NaN 0.0521 ...
  .. ..$ time        : POSIXct[1:145], format: "2008-06-26 00:00:00" "2008-06-26 00:10:00" ...
  ..@ processingLog:List of 2
  .. ..$ time : POSIXct[1:3], format: "2015-07-09 13:11:54" "2015-07-09 13:11:54" ...
  .. ..$ value: chr [1:3] "create 'ctd' object" "ctdAddColumn(x = res, column = swSigmaTheta(salinity, temperature,     pressure), name = \"sigmaTheta\", label = \"Sigma Theta\"| __truncated__ "as.ctd(salinity = rsk)"
```

**Comment by richardsc** [comment]
Relatedly, also notice that some of the rsk object metadata fields are wrong:
```
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 5
  .. ..$ filename        : chr ""
  .. ..$ conductivityUnit: chr "mS/cm"
  .. ..$ waterDepth      : logi NA
  .. ..$ names           : chr "sigmaTheta"
  .. ..$ labels          : chr "Sigma Theta"
```

Notice that `waterDepth` is `NA`, and the `names` and `labels` fields only have `sigmaTheta` for some reason.

**Comment by dankelley** [comment]
I'll check on ``waterDepth``. Is that something that rsk contains, typically?  (I think it's only in SBE when someone types it in, based on a depth sounding.) As for ``names`` and ``labels``, good catch! But, actually, I sort of think these are not useful, since (a) probably they aren't used in plotting anyway and (b) a user can always do ``myCtd@data$tenS <- 10*myCTD[["salinity"]]`` or such-like, which will not change the label because it's a direct insertion. I think I should get rid of ``names`` and ``labels``.

**Comment by richardsc** [comment]
My understanding was that if `waterDepth` is not provided, it is inferred from the maximum pressure. But then I went to `?as.ctd` to look, and found:
```
waterDepth: optional numerical value indicating the water depth in
          metres. See “Details.”
```
but there is no `Details` section on the man page :cry: 

But a test confirms that to be TRUE:
```r
str(as.ctd(1:10, 1:10, 1:10))
```
```
Formal class 'ctd' [package "oce"] with 3 slots
  ..@ metadata     :List of 23
  .. ..$ header          : NULL
... SNIPPED ...
  .. ..$ startTime       : chr ""
  .. ..$ recovery        : chr ""
  .. ..$ waterDepth      : int 10
```

**Comment by dankelley** [comment]
Yes, I'm adding the details section!  I have gone back and forth on this. I really don't think ``waterDepth`` should be defined unless it's been specified or read from the file. I think the main place it enters is in section plotting, but in doing that, if no waterDepth is in the metadata, the code can always (for that one purpose alone) guess that it was a full-depth profile.

My problem with storing a guess in the metafile gives the value too much authority. For example, if we don't know longitude, it is just NA. I think that's the right approach. I wouldn't want someone doing a summary() and seeing made-up things.

I think the only purpose to which waterDepth is ever put is drawing the bottom on section plots.

PS. there is a fair bit of stuff in the ctd metadata that is quite sbe specific, startTime and recovery being examples. They are there mainly because the very first .cnv file I ever looked at contained them. I'm not clear that they will be present in all .cnv files, however.

**Comment by richardsc** [comment]
Checking out changes as of `develop` commit a06fb4dd8310617f7151d3f2047a4dd9a66c9175, and I notice from a quick test that this issue is still present:
```
> str(read.oce('060130_20150706_1513.rsk')@metadata)
List of 8
 $ filename           : chr "/Users/richardsc/Dropbox/rbr/orp/ctd/rsk/060130_20150706_1513.rsk"
 $ model              : chr "RBRconcerto"
 $ conductivityUnit   : chr "mS/cm"
 $ temperatureUnit    : chr "ITS-90"
 $ pressureType       : chr "absolute"
 $ pressureAtmospheric: num 10.1
 $ serialNumber       : int 60130
 $ sampleInterval     : num 0.167
> str(as.ctd(read.oce('060130_20150706_1513.rsk'))@metadata)
List of 5
 $ filename        : chr ""
 $ conductivityUnit: chr "mS/cm"
 $ waterDepth      : logi NA
 $ names           : chr "sigmaTheta"
 $ labels          : chr "Sigma Theta"
```

**Comment by dankelley** [comment]
This is a perfect case for trying out the ``stopifnot()`` scheme. And now it can be done with data stored inside ``oce``, avoiding the private-data problem. Below is a start. I'll post again when it all works.
```r
library(oce)
try(source("~/src/oce/R/rsk.R"))
file <- system.file("extdata", "sample.rsk.gz", package="oce")
tmp <- tempfile(fileext=".rsk")
R.utils::decompressFile(file, destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
rsk <- read.rsk(tmp)
ctd <- as.ctd(rsk)
stopifnot(all.equal(ctd[["filename"]], rsk[["filename"]]))
```

**Comment by dankelley** [comment]
@richardsc I think I'm mostly done with the test code. See prev comment. Note that I'm asking whether you agree in a few spots. Also, it would be great if you suggest tests for whatever else I may have missed in the present discussion. I'm hoping this scheme will help. I find the concreteness helps me to see what an issue is all about.

**Comment by richardsc** [comment]
Nice. Will have a look at this tonight or tomorrow.

**Comment by richardsc** [comment]
The current version looks good with the *populated* metadata fields now.

The other part of the issue what that there is a difference between using `as.ctd(salinity=..., temperature=..., pressure=..., ...)` and `as.ctd(rsk)`, in that the creation of a ctd object from "scratch" using `as.ctd()` creates empty metadata fields that aren't created during the coercion of an rsk object.

See [oce-issues/692](https://github.com/dankelley/oce-issues/tree/master/692):
```r
## https://github.com/dankelley/oce/issues/692

library(oce)
library(testthat)
try(source("~/src/oce/R/ctd.R")) # DK uses for faster code-test cycle

## PART 1: rsk conversion
file <- system.file("extdata", "sample.rsk.gz", package="oce")
tmp <- tempfile(fileext=".rsk")
requireNamespace("R.utils")
R.utils::decompressFile(file, destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
rsk <- read.rsk(tmp)
rsk[["filename"]] <- "sample.rsk" # trick it ... otherwise a tmp file
ctd <- as.ctd(rsk)
ctdManual <- as.ctd(ctd[['salinity']], ctd[['temperature']], ctd[['pressure']])

expect_equal(ctd[['longitude']], ctdManual[['longitude']])
expect_equal(ctd[['latitude']], ctdManual[['latitude']])
```

So I guess part of the question is, should the default behaviour of `as.ctd()` be to create *empty* metadata fields?

**Comment by dankelley** [comment]
Thanks for bringing this up. I think it is good to figure this out now, to establish policy for other cases.  

1. My feeling is that as.ctd() should not be defaulting all those things. As presently done, the fcn cannot know whether the user specified the items or they were just defaulted. I propose to make them be of non-defaulted type, and to use ``missing()`` to see if the user supplied something, and then to insert into metadata only if so. **Q** What do you think of this plan?  Note that it can be done in a way that won't affect old user code. I'm sure new bugs will come up, but with testthat, we should be able to find them before users do.

2. I'd like your thoughts on the basic kernel of CTD objects. This is defined in ``new()``, and I wonder if  you could look at ``R/ctd.R`` and tell me what you think.  I feel that ``waterDepth`` should be removed from ``metadata``, since some datasets won't even have that. As for ``data``, it necessarily contains p, T, S, and C. One could argue that C should be optional, and therefore should not be in ``new()``. Or maybe one could argue that T is optional. I see arguments on both sides, but *one* of them should be present or it ain't a CTD, so I put both in (recognizing that many datasets have both). What are your thoughts on that?

**Comment by dankelley** [comment]
I decided to go ahead and "thin out" the CTD metadata. I think (hope) I've done it in a way to be backwards compatible.  Basically, the old part of ``as.ctd()`` was using default function arguments for all kinds of things that made sense when CTD objects were from typical SBE datafiles (with added header info on station number, etc). Now, things get shoved into ``metadata`` only if the value is known.

The codebase is pretty complicated, so I ran ``make ctd`` in oce-issues to see if things still work. They seem to. I also updated ``oce-issues/692.R`` with some more test-that stuff, which I've put below partly because I want the present issues reports to show more of test-that, so users can see how it's done.
```r
## https://github.com/dankelley/oce/issues/692

library(oce)
library(testthat)
try(source("~/src/oce/R/ctd.R")) # DK uses for faster code-test cycle

## PART 1: rsk conversion
file <- system.file("extdata", "sample.rsk.gz", package="oce")
tmp <- tempfile(fileext=".rsk")
requireNamespace("R.utils")
R.utils::decompressFile(file, destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
rsk <- read.rsk(tmp)
rsk[["filename"]] <- "sample.rsk" # trick it ... otherwise a tmp file
ctd1 <- as.ctd(rsk)

expect_equal(ctd1[["filename"]], rsk[["filename"]])
expect_equal(ctd1[["serialNumber"]], rsk[["serialNumber"]])
expect_null(ctd1[["waterDepth"]])

mnames <- sort(c("pressure", "temperature", "salinity", "conductivity", "sigmaTheta"))
##, "temperatureUnit", "conductivityUnit"))
expect_equal(mnames, sort(ctd1[["names"]]))
mlabels <- sort(c("Pressure", "Temperature", "Salinity", "Conductivity", "Sigma Theta"))
expect_equal(mlabels, sort(ctd1[["labels"]]))
expect_equal(rsk[["temperatureUnit"]], ctd1[["temperatureUnit"]])
expect_equal("ITS-90", ctd1[["temperatureUnit"]])
expect_equal("mS/cm", ctd1[["conductivityUnit"]])

## PART 2: with columnar data
ctd2 <- as.ctd(1:10, 1:10, 1:10)
expect_equal(sort(c("labels", "latitude", "longitude", "names" , "temperatureUnit", "conductivityUnit")),
             sort(names(ctd2@metadata)))
expect_null(ctd2[["waterDepth"]])
expect_equal("ITS-90", ctd2[["temperatureUnit"]])
expect_equal("ratio", ctd2[["conductivityUnit"]])
```

**Comment by richardsc** [comment]
I've thought about it a bit, and I guess I agree that it doesn't make sense to have a whole bunch of empty fields in the metadata slot. The reason I originally brought this up is that it makes it harder to add things by doing:
```r
ctd[['latitude']] <- 45
```

But I recently remembered about the `oceEdit()` function, which really is the way that such metadata changes should be done anyway:
```r
ctd <- oceEdit(ctd, 'latitude', 45)
```

**Comment by dankelley** [comment]
This is interesting. I think the magic code for ctd ``[[`` should recognize some words. Thus, doing 
```r
ctd[['latitude']] <- 45
```
should notice that it knows the name, and then it should notice that the item has just one value and therefore it should go into ``ctd@metadata``.  This could be a lot of programming, though.

Maybe we need e.g.
```r
ctd[["zodiacSign", "metadata"]] <- "Pisces"
```
etc. I think users who are comfortable using ``[[`` will be comfortable in this sort of extra notation. Note that it would be build deep into the ``oce`` object, so that ctd and all other objects would get the behaviour.

Note that users already do that with e.g. getting thing byStation from sections.

Your thoughts?

**Comment by richardsc** [comment]
To be honest, I'm not sure it's worth all the hacking -- I had forgotten about `oceEdit()` for metadata, and there is already a function for adding data columns: `ctdAddColumn()`. 

Perhaps `oceEdit()` should have an alias for `oceAddMetadata()`?

Perhaps `ctdAddColumn()` should have a more generic `oceAddColumn()` or `oceAddData()` version?

Regardless, I think the original issue is addressed, so maybe we should open a new issue to discuss this data/metadata access thing ...
