### ISSUE TITLE
plot.rsk() doesn't reset par when finished

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#699]
Currently, oce plot generics (such as `plot.ctd()`) resets `par` to whatever it was before the plot was made, i.e. so that "standard" plots made after a four panel ctd plot are single panel.

This doesn't seem to be the case with `plot.rsk()` however, e.g.

```r
library(oce)
data(rsk)
plot(rsk)
plot(1,1)
```

where the second plot still has a "two-panel" layout.

**Comment by dankelley** [comment]
Below is how we can write that in the "new form", with testthat.
```r
library(oce)
library(testthat)
data(ctd)
plot(ctd)
expect_equal(par('usr'), c(0, 1, 0, 1))
data(rsk)
plot(rsk)
expect_equal(par('usr'), c(0, 1, 0, 1))
```
Note -- I made an issue test code with this content.

**Comment by dankelley** [comment]
I think this is fixed in ``develop``, in the sense that the ``testthat`` code (as above, and as in the newly-constructed issue test) works ok now. I may shove this (and similar) into the build-test suite, wrapped in the conditional that prevents it being done on CRAN tests (because that would be slow, and not needed, since local tests will reveal whether things work.

**Comment by dankelley** [comment]
``lobo`` and ``lisst`` were doing the same thing. I've changed them. I also added checks in the build-test for all the multi-panel plots that I could find (i.e. I did ``ls -c1 data/*.rda``, edited out the ones that don't have plotting signatures, and put them into the test suite, modifying code as required, i.e. in the ``lobo.R`` and ``R/lisst.R`` files.)

**Comment by richardsc** [comment]
Looks good. Thanks!
