### ISSUE TITLE
oce object metadata/data access questions

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#700]
From a discussion started in issue #692:

Perhaps `oceEdit()` should have an alias for `oceAddMetadata()`?

Perhaps `ctdAddColumn()` should have a more generic `oceAddColumn()` or `oceAddData()` version?

**Comment by dankelley** [comment]
Not all things are columns (adp!) but maybe ``oceAddMetadata()`` and ``oceAddData()``?

Just thinking about function names (ignoring previous coding) it would seem we should have maybe also ``oceAlterMetadata()`` and ``oceAlterData()``. Another way would be for "add" functions to also alter existing values, but somehow it seems clearer to me to have two. And creating ``oceDeleteMetadata()`` and ``oceDeleteData()`` seems natural. Maybe even ``oceGetMetadata()`` and ``oceGetData()``.

Having written all that stuff, I'm not sure that we need ``oce`` in the names. But there is something in R called ``getDataPart`` so it might be good to have ``oce`` there. Also, it tells people that these things ONLY work for oce objects, not for anything else.

If the general idea seems ok to you, I'll look into how to code. My thought is that these should be bound inside the objects, not free-floating functions.

This doesn't seem like a lot of work, but it seems helpful. The first step is to decide on function names, because it does end up being a lot of work changing function names (and their doc files, and the links back and forth).

**Comment by richardsc** [comment]
> Dan wrote:
> Just thinking about function names (ignoring previous coding) it would seem we should have maybe also ``oceAlterMetadata()`` and ``oceAlterData()``. Another way would be for "add" functions to also alter existing values, but somehow it seems clearer to me to have two. And creating ``oceDeleteMetadata()`` and ``oceDeleteData()`` seems natural. Maybe even ``oceGetMetadata()`` and ``oceGetData()``.

I like these names and suggested functionality. I guess the biggest advantages to using such functions, over say just directly editing things, are

1. consistent object access protocols

2. documentation in the `processingLog`, without having to two two steps, where the second involves calling `processingLog()` (which I *never* do anyway ... )

It seems that the `oceAlter*()` functions would just be wrappers, in other words something like:
```r
ctd <- oceAlterMetadata(ctd, 'latitude', 45)
```
instead of 
```r
ctd[['latitude']] <- 45 # assuming @metadata$latitude exists
```

and the `oceDelete*()` functions would behave like:
```r
ctd <- oceDeleteMetadata(ctd, 'latitude')
```
instead of doing
```r
ctd[['latitude']] <- NULL
```

**Comment by dankelley** [comment]
No, I don't think they would be wrappers. The thing is that if someone wants something not already in the metadata, how do they do it? Right now the only way is e.g.
```r
x@metadata$zodiac <- "Pisces"
```
because the ``[[`` function called by ``x[["zodiac"]]`` will have no idea where to put an item named ``zodiac``.

My idea is to allow people to control where things go (even completely new things), which is something that ``[[`` cannot  be expected to do (unless it gets a new argument). We saw that with ``longitude``, which arguably could go in metadata or data.

**Comment by dankelley** [comment]
Sorry, I should have said "yes, like wrappers". Doing too many things at once. I'll check in on this thread later this afternoon, sorry for prev confusing msg.

**Comment by dankelley** [comment]
I added some code for this, viz
```
$ grep Get NAMESPACE 
       oceGetData, oceDeleteData, oceSetData,
       oceGetMetadata, oceDeleteMetadata, oceSetMetadata,
```
in the ``develop`` branch. I think it might make sense to use it for a little while, to see if the names "feel right". Note that ``Set`` can add something new, or alter something existing ... I decided not to separate these because R doesn't do so with ``<-``.

NOTE. it is possible that the ``Get`` functions may be expensive (in terms of memory or time) compared to direct access. It's a bit hard to predict or test such things, because R does a lot of copying (and promising to copy) behind the scenes, even in what seems to be direct access.

@richardsc -- does what I've done seem helpful?

**Comment by richardsc** [comment]
It does seem helpful! I'd like some time to test and try out the new functions, and I'll be slow for the next week or two, so I'll leave this open for now.

**Comment by dankelley** [comment]
Thanks. PS. I didn't get an email on this. Probably some spam filter captured your message (and, I think, some others lately).

**Comment by richardsc** [comment]
These seems to be working as I'd expect, so I'll close as any new bugs should have new Issues.
