### ISSUE TITLE
read.landsat is getting lon/lat slightly wrong for some images

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#707]
Ok, this is a bit strange. It definitely *used* to be ok ... and I'm not sure that it's happening for *all* L8 images, but it is for some of the ones I've been looking at in Western Greenland.

First, to run the tests in [oce-issues/707](https://github.com/dankelley/oce-issues/tree/master/707) you'll need to get the L8 image I've been using. I can provide it if you can't find it online. Here is the info:
```
Landsat Summary
---------------

* Data file:           /data/archive/landsat/LC80100112013172LGN00
* Time:                2013-06-21 15:08:41
* Spacecraft:          LANDSAT_8
* Header file:         /data/archive/landsat/LC80100112013172LGN00/LC80100112013172LGN00_MTL.txt
* Data:
*     band aerosol has dim=c(8411,8251)
* UTM zone:             22 (used for whole image)
* UTM lower left:       378600 easting 7597800 northing (m)
* UTM upper right:      630900 easting 7845300 northing (m)
* Lower left:          -53.964710E 68.466510N
* Lower right:         -47.803720E 68.462250N
* Upper right:         -47.453560E 70.677920N
* Upper left:          -54.289610E 70.682710N
* Processing Log::
  * 2015-07-20 23:09:55 UTC: ``create 'landsat' object``
  * 2015-07-20 23:09:58 UTC: ``read.landsat(file = file, band = 1)``
```

Now, if you run `707a.R` in oce-issues using the latest oce, you'll get two images, the second of which is:
![707a-002](https://cloud.githubusercontent.com/assets/233584/8792391/a642d31c-2f34-11e5-91dd-0272c33bd691.png)

Notice that the coastline (which was itself determined from a landsat image using different software, and has been independently verified using local maps of the region, and *used to* line up perfectly with this image) does not line up with the coastline in the image. Close, but no cigar ...

Any ideas?

**Comment by richardsc** [comment]
Added some labels and assigned to you @dankelley because I know I'll screw things up if I try and fix this ... :)

**Comment by dankelley** [comment]
Thanks. I put in a request for the data. I dunno, but the usgs site seems to be harder than it used to be. It took me a long time to find the "give scene id" webpage, without which it's hard. And then I couldn't find a "download" option, and instead "ordered" the dataset. If I don't get an email in a couple of hours, I may post here again (knowing the timezones) and ask you to put the dataset in dropbox or icloud or something.

**Comment by dankelley** [comment]
Sorry, I just now see you are zooming in to a small domain. Can you provide me with your coastline file so I don't have to try to find a datafile that might be different? Also, since it's the same amount of work, could you provide the landsat image? The usgs system has sent me notifications that they got my request and are working on it, but nothing about being downloadable yet. I should have some time today or this evening to look.

**Comment by dankelley** [comment]
Cancel landsat request ... I just downloaded it. But I'd still appreciate a coastline file, to save me another hour of fiddling. (Really, I was pretty sure I could get usgs downloads in a few seconds once upon a time. Now it's a one-hour wait to get a download link by email. And it's not an email problem -- the emails just sailed through.)

**Comment by dankelley** [comment]
Sorry, cancel last 3 messages. I got the landsat data, and I see the coastline.rda there. I should learn to look before I type!

**Comment by dankelley** [comment]
Oh my. It turns out the landsat image I just downloaded lacks a .TXT file, which oce wants. This makes me wonder how you got it working at all. I got the file from usgs. Maybe I should try glovis??
```
$ ls /data/archive/landsat/LC80100112013172LGN00/
LC80100112013172LGN00.xml		LC80100112013172LGN00_sr_band4.tif
LC80100112013172LGN00_cfmask.tif	LC80100112013172LGN00_sr_band5.tif
LC80100112013172LGN00_cfmask_conf.tif	LC80100112013172LGN00_sr_band6.tif
LC80100112013172LGN00_sr_band1.tif	LC80100112013172LGN00_sr_band7.tif
LC80100112013172LGN00_sr_band2.tif	LC80100112013172LGN00_sr_cloud.tif
LC80100112013172LGN00_sr_band3.tif
```

**Comment by dankelley** [comment]
I'd prefer not to get too sidetracked trying to make oce read the .xml file. So, back to original request (in a now-deleted comment) -- please put the landsat data somewhere that I can get them.

**Comment by dankelley** [comment]
Cancel last msg. I downloaded a different way, or a different file, or something. I'm not only too dull to code for landsat ... I'm to dull to even download landsat. (Will delete this and prev comment.)

**Comment by dankelley** [comment]
Just to be clear:
1. you know that this exact image (not the same region on another day) plotted ok before at this fine scale?
2. any rough idea of when it last worked, so I can look in the code to see what I changed? I assume you mean previous to issue #675 but since I'll be working on other things through the morning, I thought it smart to check precisely. I know I changed some fundamental things back then. There was always an issue with precise trimming, I think. In the old days, I used to convert the box to UTM northing/easting, then chop that way, on the assumption that the image is precise in UTM coordinates. I think I switched to simple linear interpolation, and I'm pretty sure that's the source of the problem. Probably will look tonight.

**Comment by richardsc** [comment]
I can confirm that it worked for commit 78a391e9f79ed9c68252ec21f1069cafca4e55d3, which was before the recent landsat changes that accompanied Issue #675. At least, for the very regional zoom-in I was looking at it worked.

If I revert to commit 78a391e9f79ed9c68252ec21f1069cafca4e55d3, and then re-run the tests in [oce-issues/707](https://github.com/dankelley/oce-issues/tree/master/707), the coastline lines up for the "trimmed" view. In `707b.R`, I've done the same plots, but added `coastlineWorldFine`, which you can see for the entire image is clearly offset from the coastline, but for the trimmed view more-or-less lines up (I don't expect `coastlineWorldFine` to line up as well as my hi-res coastline). I've also plotted the "trim box", which if you look closely does not line up with the actual trimmed image (e.g. notice that the trim box doesn't include the glacier face, but the trimmed image does).
![707b-001](https://cloud.githubusercontent.com/assets/233584/8801554/9b568304-2f89-11e5-8d98-01db27358d56.png)
![707b-002](https://cloud.githubusercontent.com/assets/233584/8801560/9f62b6c0-2f89-11e5-8e1c-ab0505a01883.png)

Perhaps a phone call would be a good idea ...

**Comment by richardsc** [comment]
Following our phone conversation, I just updated [oce-issues/707/707b.R](https://github.com/dankelley/oce-issues/tree/master/707/707b.R) using the latest version of oce (commit be4e5eaeb557eb741f2195aea83fe034b44d5086), and changing the color image to the `tirs1` band to make it easier to see the coastline. The images produced are:
![707b-001](https://cloud.githubusercontent.com/assets/233584/8803623/d1ba5bf8-2f95-11e5-9771-70d008fa700f.png)
![707b-002](https://cloud.githubusercontent.com/assets/233584/8803626/d60860ce-2f95-11e5-8ac4-8690afa3324c.png)

**Comment by dankelley** [comment]
I am going to use comments here as a personal note-taking tools, editing and deleting as I see fit ... they will likely make no sense as sent over email.

1. I had a look at the .txt file for this image and tried using ``oce::lonlat2utm`` on the UL point, as given below. Note that it has the wrong zone (the metadata says zone 22), plus the wrong easting (metadata says 378600) and northing (metadata says 7845300).  So, I'll be looking at this next (Wednesday).
 ```
> library(oce)
Loading required package: gsw
> lonlat2utm(-54.28961,70.68271)
$easting
[1] 600038.1

$northing
[1] 7844244

$zone
[1] 21

$hemisphere
[1] "N"
```

**Comment by dankelley** [comment]
I'll probably work on this during the upcoming weekend.

**Comment by dankelley** [comment]
This is an old issue and the code is tricky.  Thanks, @richardsc, for providing the commit hash of a version that worked. That helped me a lot in the progress I've made...

... at the moment (c9459acb9314514d6c44b2ee3e8794033172d59a), the ``landsatTrim`` branch makes ``707a-002.png`` and ``707b-002.png`` look ok (as defined by purple text along top margin).  However, the other two tests seem wrong.  (I'd love it if we could trim down the tests to just two...)

I think the present state is as follows:
1. ``landsatTrim()`` works in branch ``landsatTrim``. Evidence: the image and the drawn coastlines match up (that's the two 002.png files).
2. Plotting at large-scale is distorted. Evidence: see the coastline mismatch on the two 001.png files.

Possibly the second point is due to the image being drawn with lon-lat axes that are rectilinear. The *data* are not defined in those terms, but rather in northing and easting with the UTM projection (with the extra complication of which zone is used...). But I am still surprised to see in ``707b-001.png`` an error that looks like 5 to 10km (estimated by eye). Of course, I really don't know what I'm looking at ... I'm just going by the parts I indicate by (ugly) arrows in the attached.  (Can @richardsc verify, by comment-with-comment, whether I'm trying to match things that should be matched?)

I would like to understand how a projection could give such large shifts, before messing a lot more with the code. If I understood that (e.g. if I could explain quantitatively why the mismatch is this size at this lat, and a smaller size for NS images) then I'd feel more confident in messing with the code for large changes.

Your thoughts, @richardsc?

![screen shot 2015-08-15 at 1 20 24 pm](https://cloud.githubusercontent.com/assets/99469/9289723/79f3b35a-4350-11e5-92f6-a4c0f586af57.png)

**Comment by dankelley** [comment]
PS. I see that #675 has come back with the change ... but luckily I did it only in ``landsatTrim``, not in ``develop``, and so no normal users will run into the re-breakage of #675

**Comment by dankelley** [comment]
PPS. the re-breakage of #675 is now re-solved (if that's grammatical).

**Comment by dankelley** [comment]
I think I've made some progress. A problem at the large scale graph was using the lower-left and upper-right lon/lat values to infer axes. But the polygon containing those corners is not a rectangle (owing to UTM projection properties) and so I tried instead inferring the range of lon/lat from all four vertices of the polygon, averaging across lat and lon as appropriate. This seems to improve things a fair bit.

*NOTE* it is not a terrific solution because there is an inherent problem with rectilinear axes and projected content, but I propose that problem to be something for the future (i.e. it does not fit the wording of the present issue title).

I am putting below the graphs from the newly-updated 707a.R test. I think the 707b.R test provides no additional information, so that it should be deleted.  (I am on a mission to clarify things ... e.g I tried to put purple text that makes the graphs self-describing.)

I think I've got this to the stage where I'd appreciate it if @richardsc could look at the tests now. Sorry this has taken so long.

![707a_1](https://cloud.githubusercontent.com/assets/99469/9293414/e34971e0-4400-11e5-847d-617508926067.png)
![707a_2](https://cloud.githubusercontent.com/assets/99469/9293415/e355ae60-4400-11e5-9db7-74caae59985a.png)

**Comment by richardsc** [comment]
This is looking better to me. I'll do some testing, and will report back here. This is complicated enough that I'd like to make sure I understand the changes before we move on.

**Comment by dankelley** [comment]
@richardsc any thoughts on a timescale for testing? Did you want me to try some things?

**Comment by richardsc** [comment]
Sorry I've fallen a bit behind on testing this. I will keep it in my list but it will probably have to wait until at least next week (I'm travelling until the weekend).

I wouldn't mind if you could try some of your own tests. One test I thought would be to get the exact lon/lat of a prominent coastal feature (from Google, or some such), and then check the location of that spot in various differently scaled plots from a landsat image -- i.e. full image, plus a few trimmed ones (where the lat/lon have been re-calculated after trimming).

**Comment by dankelley** [comment]
Thanks. I'll look. I also can't promise quick results .. mainly I was wondering whether this should have the 4 stars removed because otherwise it will block a release. My feeling is that a new rsk datafile plus a week or two of use without need to bug-fix may be a criterion for a release. I wouldn't mind a pre-Christmas release, if possible.
