### ISSUE TITLE
topoWorld lat/lon appears to be somewhat wrong

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#708]
See the example code in [oce-issues/708](https://github.com/dankelley/oce-issues/tree/master/708), which produces the image below, where the 250 m contour is plotted in red. Notice how it overlaps Newfoundland by quite a bit? Is that expected?

![708a](https://cloud.githubusercontent.com/assets/233584/8835304/a4a8811a-3087-11e5-8ede-3a6abdc140e6.png)

**Comment by dankelley** [comment]
This is because topoWorld is very coarse, and the coastline is very steep at that spot. I made a new tst file, with output below.

As an aside, I know my coding to chop the lon is ugly. I thought I wrote a fcn to shift the lon, but can't remember the name (or if I put it into oce yet)...
```r
rm(list=ls())
library(oce)
library(ocedata)
data(coastlineWorld)
data(coastlineWorldFine)
data(topoWorld)
if (!interactive()) png('708b.png')
par(mar=rep(2, 4))
asp <- 1/cos(45*pi/180)
plot(coastlineWorldFine[["longitude"]],
     coastlineWorldFine[["latitude"]],
     asp=asp, type='l',
     xlim = c(-75, -50), ylim = c(35, 55))
tlon <- topoWorld[["longitude"]]
tlon <- ifelse(tlon > 180, tlon-360, tlon)
look <- 361:720
contour(tlon[look],
        topoWorld[["latitude"]],
        topoWorld[["z"]][look,], levels=-250, lwd=2, col=2, add=TRUE)
if (!interactive()) dev.off()
```

![708b](https://cloud.githubusercontent.com/assets/99469/8838220/84390df4-30a1-11e5-9026-294084007486.png)

**Comment by dankelley** [comment]
I added the some new text to the docs for ``topoWorld`` to keep readers from getting blindsided. Given CRAN policies, I don't think we have the choice of adding a topo with resolution similar to ``coastlineWorldFine``.  (Since ``coastlineWorldFine`` has many details at 1m scale,  and ``topoWorld``  is presently at 100km resolution, we would require a topo file 10,000 times larger than at present. I can't predict what it would be with compression, but even if compression were a factor of 100, the dataset would be 50 times to large for can policies).

Any chance you could assess whether this should be closed?

PS. below is the text I added.
```latex
\details{The coarse resolution can be a problem in plotting depth contours along
  with coastlines in regions of steep topography. For example, near the
  southeast corner of Newfoundland, a 200m contour will overlap a coastline
  drawn with \code{\link[ocedata]{coastlineWorldFine}}. The solution in such
  cases is to download a higher-resolution topography file and create a
  \code{topo} object with \code{\link{read.topo}} or \code{\link{as.topo}}.}
```

**Comment by richardsc** [comment]
Sounds good. Sorry for the noise -- closing!
