### ISSUE TITLE
as.ctd should have a `deploymentType()` argument

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#719]
Thanks to #715 there is now a `deploymentType` metadata slot, but as of now `as.ctd()` doesn't have an argument to set it for a new object. It should!

**Comment by dankelley** [comment]
I put this in (``develop`` at c219f7c3867f25c2dbee53caa9d6749e1a55b8b9).  In looking at my code, I see that I am rebuilding the ``metadata`` slot instead of shoving new data into it, and I should perhaps change that. If I do that, then I can add to the info on the ``ctd`` object the fact that certain metadata are guaranteed to be present.
