### ISSUE TITLE
Adding data value quality flags to oce

### ISSUE THREAD

**Issue by Xandac** [dankelley/oce#756]
Hi Dan,

Please consider adding quality flag columns to oce for data types like ctd since it would be very beneficial for each data value to have its own corresponding quality flag.

I will email you an example file since I cannot add one here.

Thanks,
Jeff

**Comment by dankelley** [comment]
Thanks, Jeff. I got the data file. Can you also email me the latest version of your ODF code? That way, I could test with your data file, without altering the oce code that reads ODF.

Another thing -- I plan to rename ``ODF2oce`` as ``as.oce()`` since that's more sensible and flexible. I realize that I'll need to keep altering that, as your ODF package evolves (e.g. I'm hoping you'll make ODF data items into objects, so I can use ``inherits()`` in ``as.oce()``...).

PS. I'm emailing your datafile to @richardsc also.

**Comment by Xandac** [comment]
Dan, the last version I provided to you is the most up-to-date version.

**Comment by dankelley** [comment]
Thanks. Clark and I discussed whether this would go in the next release (our meeting notes are [online](https://github.com/dankelley/oce/wiki/release-discussion-%5BSept-2015%5D) and decided that it won't, because it is going to be a bit complicated. (I don't like to make a formal release with features that have not been used daily for several weeks, at least.) However, we *will* be working on this in the ``develop`` branch. Most likely we will start with argo data, getting code roughed in there, before turning to ctd data. This way we can develop methodology that will work fairly generally.

Q: is there a document that will describe the flags that occur in ODF files?  And is that document open-access, so it can be linked to here and referred to in oce help files?  (I think we have such docs for argo, for woce, etc. ... maybe you use woce codes??)

**Comment by dankelley** [comment]
@xandac regarding the (private) BIO code for the ODF library...

**ISSUE 1**

With the code as I have it (and I admit it’s hacked because of issue #2 below), I cannot do a “R CMD test”.  The failure is in 
	tests/testthat/test_readODF.R
where it tries using
	readFile()
and the reason is that readFile() is not named in the NAMESPACE file.

Since you’re using roxygen, you need a
	@export
line in the roxygen block for
	readFile()

**ISSUE 2**

Regarding the encoding problems, was there any thought of the BIO code using e.g.

	fixed=TRUE

in grep() calls?  I think some may need a setting for useBytes also.  Presumably you folks are using a different locale to mine (probably with government service you need one that handles English and French) but the basic problem is that I’m using R and OSX pretty much “of of the box” and I can’t build your code without adding fixed=TRUE and other things.

**Comment by dankelley** [comment]
I started an oce-issues on this. Below is the output. This won't work for normal users, since it's required to have the (as yet unreleased) ODF package installed and patched for quite a few encoding problems I ran into. But I'm putting this as a note. The next challenge will be to figure out what flags correspond to what patterns, for the ODF output. It looks like the rule is that if the i-th column has a name starting with ``QQQQ_`` then it's a flag for the (i-1)-th column. But then there are two final columns (in this instance) that seem to be flags of some type.
```R
> library(ODF)
> library(oce)
> d <- read_odf("CTD_HUD2014030_163_1_DN.ODF")
> print(names(d$DATA))
 [1] "SYTM_01" "CNTR_01" "PRES_01" "QQQQ_01" "TEMP_01" "QQQQ_02" "CRAT_01"
 [8] "TEMP_02" "QQQQ_03" "CRAT_02" "ALTB_01" "FLOR_01" "QQQQ_04" "OXYV_01"
[15] "OXYV_02" "PSAR_01" "FLOR_02" "QQQQ_05" "PHPH_01" "LATD_01" "LOND_01"
[22] "PSAL_01" "QQQQ_06" "PSAL_02" "QQQQ_07" "POTM_01" "QQQQ_08" "POTM_02"
[29] "QQQQ_09" "SIGP_01" "QQQQ_10" "SIGP_02" "QQQQ_11" "DOXY_01" "QQQQ_12"
[36] "DOXY_02" "QQQQ_13" "CNTR_02" "FFFF_01" "QCFF_01"

```

**Comment by dankelley** [comment]
1.  I've made some progress, with ODF data. See commit 9a2c13e92996cfe96ce2aa7dca9bcb23647d7862 of the ``develop`` branch, and the [test code](https://github.com/dankelley/oce-issues/tree/master/756). What happens -- only for ODF data -- is that any column with name starting with ``"QQQQ"`` is taken to be a flag for the preceding column.

2. At present, ``as.ctd()`` can take new columns with names like ``temperatureFlag``, but I'm not entirely sure this makes sense. Maybe such things should be provided in the ``other`` argument. Or maybe there should be an argument called ``flags`` that is a list or data frame with items of appropriate names. I think most users will create CTD objects with ``read`` functions, however, so maybe it doesn't matter that the arg list for ``as.ctd()`` is getting confusingly long.

3. NOTE: nothing in the oce code actually *uses* the flags yet. I am not sure there is any point in trying to set up such functionality. I think the best plan is for the user to decide. For example, they might subset based on a particular flag value, or the value of a combination of flags at a given level. This lets users write code that works with their particular flag system, e.g. it looks to me like ODF must use flag value ``1`` to indicate good data, but maybe other people might use another numerical value (or even string value). @richardsc and @Xandac -- any thoughts on this?

**Comment by dankelley** [comment]
I made a new issue #758 for some ODF column names I didn't know. Below is what I get from the test file in the [oce-issues directory for this issue](https://github.com/dankelley/oce-issues/tree/master/756), and the list indicates the present idea -- simply naming flags with the paired column name.
```R
* Statistics of data::
                                 Min.          Mean         Max.
    scan                  3845.000000  1.155095e+04 15657.000000
    pressure                11.000000  1.185000e+02   226.000000
    pressureFlag             1.000000  1.000000e+00     1.000000
    temperature              9.481300  1.249037e+01    18.202900
    temperatureFlag          1.000000  1.000000e+00     1.000000
    conductivity             0.844806  9.359474e-01     1.053497
    temperature2             9.470600  1.248739e+01    18.201600
    temperature2Flag         1.000000  1.000000e+00     1.000000
    conductivity2            0.844359  9.359404e-01     1.053517
    ALTB                     4.000000  7.212192e+01    99.520000
    fluorometer              0.011200  4.543472e-02     0.159400
    fluorometerFlag          1.000000  1.000000e+00     1.000000
    oxygen_voltage           2.200500  2.617109e+00     3.262700
    oxygen_voltage2          1.902000  2.266623e+00     2.822900
    par                     -0.012790  1.093032e+01   172.630000
    fluorometer2            -1.884700 -8.985144e-01     0.030000
    fluorometer2Flag         1.000000  1.000000e+00     1.000000
    PHPH                     7.969000  8.048046e+00     8.178000
    latitude                42.193200  4.219355e+01    42.194030
    longitude              -65.926390 -6.592346e+01   -65.921680
    salinity                33.374100  3.463491e+01    35.621100
    salinityFlag             1.000000  1.000000e+00     1.000000
    salinity2               33.370400  3.463737e+01    35.624300
    salinity2Flag            1.000000  1.000000e+00     1.000000
    theta                    9.472600  1.247520e+01    18.201100
    thetaFlag                1.000000  1.000000e+00     1.000000
    theta2                   9.462100  1.247215e+01    18.199500
    theta2Flag               1.000000  1.000000e+00     1.000000
    sigmaTheta              24.592400  2.618500e+01    27.151000
    sigmaThetaFlag           1.000000  1.000000e+00     1.000000
    sigmaTheta2             24.621300  2.618752e+01    27.151700
    sigmaTheta2Flag          1.000000  1.000000e+00     1.000000
    oxygen_by_volume         3.965600  4.723127e+00     5.814100
    oxygen_by_volumeFlag     1.000000  1.000000e+00     1.000000
    oxygen_by_volume2        3.896900  4.668044e+00     5.758200
    oxygen_by_volume2Flag    1.000000  1.000000e+00     1.000000
    scan2                    3.000000  2.991667e+01    93.000000
    flag                     0.000000  0.000000e+00     0.000000
    QCFF                     0.000000  0.000000e+00     0.000000

```

**Comment by dankelley** [comment]
Work has started, and discussion has move to #760 (and, in broader terms, #759) so I am closing this, in the interests of clarity. The new plan (not yet finalized as a plan, and only broadly tested in code) is for the flags to go into ``ctd@metadata$flags``, so that ``ctd@data`` contains only actual data.
