### ISSUE TITLE
coastlineWorld (and variants) have more than just coastlines

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#772]
This is sort of an aesthetic issue, but I noticed recently that the `coastlineWorld` datasets (e.g. `coastlineWorld` in oce and `coastlineWorldMedium`/`coastlineWorldFine` in ocedata) come from shapefiles that have country borders in them. Sometimes it's nice to have non-political maps (also, I've been toying with a stippled coastline fill, which the country borders mess up).

I think it would be nice to have variants that don't include the borders, since, why should that matter for the ocean anyway?

I saw from `?coastlineWorldFine` in ocedata that:

```
Source:

     Downloaded from <URL: http://www.naturalearthdata.com>, in files
     ‘ne_50m_admin_0_countries.shp’ for ‘coastlineWorldMedium’, and
     ‘ne_10m_admin_0_countries.shp’ for ‘coastlineWorldFine’.
```

and looking on the website I see there is a version that is just for coastlines:

http://www.naturalearthdata.com/downloads/10m-physical-vectors/

However, a quick, download and plot shows that the polygons aren't well suited to `plot.coastline()`:
```r
library(oce)
cl <- read.oce('~/Downloads/ne_10m_coastline/ne_10m_coastline.shp')
plot(cl)
```
![screen shot 2015-10-30 at 8 49 57 pm](https://cloud.githubusercontent.com/assets/233584/10860967/05d51764-7f48-11e5-9efe-1e716aad1d11.png)

**Comment by richardsc** [comment]
The [Land](http://www.naturalearthdata.com/downloads/10m-physical-vectors/) dataset from the naturalearth website might be a good option:
![screen shot 2015-10-30 at 9 01 32 pm](https://cloud.githubusercontent.com/assets/233584/10861017/73230ed8-7f49-11e5-810e-88fbeda9c37b.png)

**Comment by dankelley** [comment]
I agree it's nice to have no borders sometimes. I actually like borders in some cases, though.

There is a general issue at play here, with datasets. CRAN is resistant to large datasets, but yet users want them. For example, right now we have in ``levitus`` a degraded world-ocean-atlas, with just the top layer and with just 1deg resolution (or whatever it is). Similarly for topography. Both of these are a problem in non-global work, as is the coarse world coastline. But what do we do? We can't make levitus be 12*12*32 times as large because that makes it 1Gb. Similarly for topo. And, I fear, similarly for coastlines. The "fine" one is already 3M, making up a lot of the size of ``ocedata``. So making datasets for non-border coastlines will double the size of ``ocedata``.

I think the solution for the user is to make concrete suggestions on how they should create their own datasets, and where they should store them. I think this would only be 3 to 5 lines in a help file. 

The only trick is where to tell users to put the ``.rda`` file. 
* I would be inclined to suggest ``~/data/R`` on osx and linux.  (Sensible to you? Maybe ``~/R/data instead``? I'm guessing it would help to separate R data from other data, so it seems to make sense to have a dir for that.)
* I have no idea at all on how to specify an equivalent for windows (ideas?).

**Comment by richardsc** [comment]
Yeah, I agree -- I mostly opened the issue so the discussion wasn't just in our email box and others might find it. The reason for including things in packages of course is that it makes code more reproducible.

I think it doesn't matter where the rda goes -- I'd probably put with where I store other data, such as `/data/coastlines/coastlineHigh.rda` or something.

A neat approach would be to add a .Rprofile hook to load such things (if they exist) when oce or ocedata are loaded.

**Comment by dankelley** [comment]
Right, I agree. I will start by documenting more precisely how coastlineWorld was created, in its help page. Gosh, a long url on the datafile: ``http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip``

**Comment by dankelley** [comment]
I gave up trying to figure out how to unzip the file programmatically, so the instructions tell how to locate the file on the web, etc. An advantage of this is that then users can check out the other files. I also have a new section on installing your own files.

**Comment by richardsc** [comment]
This is great. I had a good trawl through the [natural earth data](https://www.naturalearthdata.com) tonight and wrote code to import all the physical maps based on the new instructions in the man page. Check out Canada, with lakes, rivers, glaciated areas, and internal borders!
![map4](https://cloud.githubusercontent.com/assets/233584/10900288/e0273f18-81ab-11e5-804f-341b7882eee4.png)

**Comment by richardsc** [comment]
I guess this should be closed, but I'm so happy with that map I'd like to advertise it more ... perhaps I'll toss it up on my blog.

**Comment by richardsc** [comment]
Tweaked the colours a bit ... this is fun!
![map4](https://cloud.githubusercontent.com/assets/233584/10901096/c89594ac-81b6-11e5-98a8-432394601ba2.png)

**Comment by dankelley** [comment]
[1] You should definitely be putting this sort of thing on your blog! 

[2] When I get a chance I will put more on reading coastlines, saving them, etc., into the docs for ``?"coastline-class"`` because they should go there. I think that's where they belong; I put some new info on ``?read.coastline`` and I now feel there should just be a pointer there, and that the "class" help is the place for people to read about where to download data, the usefulness of storing the data, longitude-cut issues, and so forth.

[3] PS. I never quite realized how many lakes we have up here, all in the arc of low-lying spots. It woiuld be a fun exercise to plot areal density of lakes and rivers, versus local elevation.  I could turn into a geographer, or geologist, or whatever.
