### ISSUE TITLE
plot.coastline doesn't allow a `col` argument when `fill` is specified

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#774]
Example:
```r
library(oce)
data(coastlineWorld)
plot(coastlineWorld, col=2)
```
produces the error:
```
Error in polygon(x[["longitude"]], x[["latitude"]], col = fill, ...) : 
  formal argument "col" matched by multiple actual arguments
```

If the "filling" is turned off, then it will work (because it is just drawing lines):
```r
plot(coastlineWorld, col=2, fill=NULL)
```

Note that the same thing happens using `mapPlot()` on coastline objects -- though the default behaviour of `mapPlot()` is that filling is off:
```r
mapPlot(coastlineWorld, col=2) # works
mapPlot(coastlineWorld, col=2, fill='grey')  #doesn't work
```
```
Error in polygon(x, y, col = fill, ...) : 
  formal argument "col" matched by multiple actual arguments
```

**Comment by dankelley** [comment]
This is slightly tricky. I think this should be brought into line with the args for ``polygon()`` if ``fill=TRUE`` or with ``lines()`` if ``fill=FALSE``. However, that means different meanings for ``col`` in the two cases. And we need to keep things close to consistent with the previous setup. So there may be lots of special cases -- always tricky to code.  I started to code it, thinking it was a 5min hack, but not really.

**Comment by richardsc** [comment]
Yes, I agree it's tricky because of the overlapping uses for arguments. I meant to point that out ... I also started to just fix it myself (before even creating the issue), but stopped because I didn't want to turn a rat   house into a rat nest.

**Comment by richardsc** [comment]
Maybe having `fill.col` and `line.col` arguments would be the best way to go, however it will change from the existing behaviour. 

We should also make sure that `mapPolygon()` is consistent with whatever we choose.

**Comment by dankelley** [comment]
The simplest will be to detect whether  ``"col" %in% names(list(...))`` in the ``plot`` method for ``coastline`` objects, and to handle that as a special case. Then the old behaviour can be retained (on the assumption that people like it) and all we would do is to replace an error condition with something more sensible.  I don't want to change existing behaviour if I can help it. Will think more tonight -- tomorrow aft I may try some experiments.

**Comment by richardsc** [comment]
Do you mean treat the presence of a `col` argument as a special case *after* adding new arguments to make things more consistent? To be honest I've always found the default behaviour somewhat confusing *because* it's not consistent between functions. For example, I might often do:
```r
mapPlot(coastlineWorld, fill='grey') # make a plot
## ... some other overplotting stuff ... such as mapImage, etc
mapPolygon(coastlineWorld, col='grey') # to put the land polygons back on top
```
Note the different arguments to accomplish filled land.

**Comment by dankelley** [comment]
This is confusing because ``polygon()`` takes ``col`` to be a fill colour, and ``border`` to be an outline colour. By contrast, ``lines()`` and ``plot()`` take ``col`` to be the drawing colour. So, the user might wonder how ``mapPlot()`` would work ... if (a) it is analogous to ``plot()`` then ``col`` means the lines but if (b) it is analogous to ``polygon()`` then ``col`` is the filled colour.

Possibly the below is OK logic for ``mapPlot()`` [I propose leaving the others aside until this seems right, and then altering them to match, if required]. The idea is to keep ``fill=NULL`` as it is, but to add a new ``border=NULL`` argument, and a ``col=NA`` argument (these match ``polygon()``).

It would help a lot if we could agree on the logic in this sketchy way because the actual code spreads over several screenfuls at the font size I can read.
```r
if (is.logical(fill)) {
  if (fill) {
    # case A: fill with colour "col"
    #     if "border" is provided, make border that colour
    #     That is, emulate polygon
  } else {
    # case B: draw lines with colour "col" if provided, or otherwise "border" is provide ... else use black
  } else if (is.null(fill)) {
    # case C: do as at present, for compatibility
  } else if (fill specifies a colour) {
    # case D: as case B, but replace "col" with "fill"
  } else {
    stop("'fill' must be a NULL, a logical or a colour")
}
```

**Comment by richardsc** [comment]
Yeah, this is leaving my mind in a bit of a state ...

I think the previous is decent enough logic, at least for testing. We can always alter after some use.

**Comment by dankelley** [comment]
Time for a weekly update ... I was about to try coding this, and it really is tricky, trying to make a balance between (a) compatibility and (b) a sensible scheme for the future. I've put some more detailed notes in the [README.md file](https://github.com/dankelley/oce-issues/tree/master/774). Since 10 lines of pseudocode becomes 100 lines of actual code, I want to get this pseudocode in a good shape before writing code. My plan is to leave it for a few days, and then I'll write up some ideas for a new paragraph in the docs, and put that into  the [README.md file](https://github.com/dankelley/oce-issues/tree/master/774). Only when it all seems quite clear will I start the coding, since I don't think we want to run into confusion with all the possible cases ... I count 5 cases just for the case without projection, and of course we don't want to code 5 cases for non-projection and another 5 cases for projection, and then have to change the meaning of args and have to recode all 10 cases.

**Comment by dankelley** [comment]
It's nearly 3 months after the last real comments, and as I now return to this, I am still not too clear on the right approach. I am going to put some thoughts below, and edit this comment in-place as I think about this over the weekend.

Given the complexity, I don't want to try to fix this anywhere near a cran release. Therefore, if I do not see a clean solution within a day or so, I intend to simply make `plot.coastline` check if `col` is in `names(list(...))`` and print a more helpful error message if so (it will say that they cannot control the colour of coastlines, but that they can control the filled colour with `fill`.)

Making a uniform solution for both `plot.coastline` and `mapPlot` may be tricky, given the history.  And, besides, if we can describe things well in the docs and in error messages, that will be an improvement.

We are really in this bind because `plot` and `polygon` have different meanings for `col`.  For this reason, I *like* calling the fill colour `fill`, which is both intuitive and historical (within oce).

**Option 1** add `border` and `col` to both `plot.coastline` and `mapPlot`. This has the advantage of matching the `polygon` argument names, *and* the word "border" feels natural in this context.  If neither is supplied, obey the old arguments to still do as we do now.  (This will require some tricky conditioning on `fill`, and I am not sure how likely that is to break functionality.)

**Option 2** check to see if `col` is supplied in `...`, and make an error message if so. That message could tell people that the inside colour is set by `fill`, and that the edge colour cannot be set ... or whatever is the present state.  Then, make a new issue to handle option 1 and mark that `Next^2 Release`.

The idea of option 2 is partly to find a way to resolve this issue in at least some way, without blocking CRAN release.  I really don't want to make wholesale changes that are going to require a large test suite, a few weeks before a CRAN release because we may just make things worse for users.

@richardsc -- what are your thoughts? Maybe there are more options? I am concerned about this, which I see as the remaining tricky issue blocking release.

**Comment by dankelley** [comment]
I've started branch `issue774` and will play with this a bit to see if I can fix things up. No promises.

**Comment by dankelley** [comment]
I feel this works fine in the branch called `issue774`, and now have what I think is a reasonable test in git-issues **but** it only tests `plot(coastline)` and not `mapPlot()`. Tomorrow (or on the weekend) I will look at the latter and if I can make good progress I'll merge into `develop`. I do not want any `next-release` issues to be open as of upcoming Monday, at which point I plan to punt any `next-release` issues to `next2-release` and work towards a CRAN submission, to meet our timetable.

**Comment by richardsc** [comment]
I'm having a hard time keeping track of why this seemingly benign issue has proved to be so malignant.

As you say, part of the problem is because `plot()` and `polygon()` take differently named arguments for similar things. But then, functions like `mapPlot()` behave like *either* `plot` **or** `polygon` depending on the object (e.g. vector of lon/lat vs coastline).

Maybe we're just overthinking this -- coastline objects behave like polygons and so should have `border` and `fill` arguments. Everything else just uses `col` as if for lines/points. I'm sure that's a rat colony of conditionals, and probably some changes from the current behaviour, but the version is still < 1.0 ...

**Comment by dankelley** [comment]
Um, but `plot.coastline` can call `mapPlot` so I do want to bring the args into a bit more alignment.

Another issue is that coastline objects contain `metadata$fillable` which also must be obeyed. So that is  *yet another* nuance in the actions.  I think it won't be hard for me to alter `mapPlot` so both it and `plot.coastline` obey the polygon style of args. And I think I can do all of this compatibly.

Note that I made a milestone with Monday's date. That's when I plan to move any unsolved `Next Release` to the `Next^2 Release` label. Beyond peephole testing of issues, I think we need some time of just plain old usage, to iron out wrinkles.

I don't think the present issue is crucial in and of itself -- nobody has complained in a few years -- but as an occasion to finally fix up the arg lists of these two functions, I think is of a very high priority because my guess is that map plotting is an entry to oce, so I don't want people at the workshop learning a method that will get changed in the very next cran release.

**Comment by dankelley** [comment]
I feel that this is now working. I have new test code in issues. I wonder whether @richardsc could check it sometime?  (Must use the `issue774` branch ... I'll merge into `develop` when/if this seems fixed.) I am about to go in a meeting for 1 or 2 hours, not sure.

**Comment by richardsc** [comment]
I'd say this is looking good. I'll leave it for a couple days to try and play around some more, but if no problems arise it can be closed by the milestone date.

**Comment by dankelley** [comment]
Thanks!

**Comment by dankelley** [comment]
@richardsc I don't want to close this without your permission, but I also would like to stick to the plan of only starting prerelease work when the `Next Release` issues are closed.

**Comment by richardsc** [comment]
I think the current solution is good for the upcoming release. It will may break some old code, but the warning about `fill` deprecation should take care of that. I definitely like the consistency between `plot.coastline()` and `mapPlot()` at least.

Closing!
