### ISSUE TITLE
ODF file flag fields

### ISSUE THREAD

**Issue by Xandac** [dankelley/oce#778]
Hi Dan,

I have a slight issue with how the conversion from ODF to oce is handled.  Currently the code changes both the ODF "FFFF" and "QCFF" codes to the oce code "flag".  The "FFFF" code has not been used in years so it should be ignored.  The "QCFF" code is new and will be used so it should be kept.  Do you use the "FFFF" code yourself? If not then would you please update the ODF2oce function to ignore the "FFFF" code and change the "QCFF" code to "flag" instead.  If you do use "FFFF" then would you please change the oce code for "QCFF" from "flag" to "qflag".

Thanks,
Jeff

**Comment by dankelley** [comment]
I don't use the flag myself, but I suspect it may be in some files that my student is using. How about the following scheme:
```r
flag <- if ("ffff" %in% names(X)) X$ffff else if ("qfff" %in% names(X)) X$qfff else NULL
```

**Comment by Xandac** [comment]
QCFF has a higher priority than FFFF so I if I understand your code correctly then I would make the code look like:

flag <- if ("qcff" %in% names(X)) X$qcff else if ("ffff" %in% names(X)) X$ffff else NULL

**Comment by dankelley** [comment]
I've tweaked the code. Now, if it finds ``FFFF`` it calls the result ``flag_archaic``.  This will possibly be of some use ... I'm not entirely sure though, because I don't have many test files.

@Xandac this raises another issue, in that the test file provided with oce in [inst/extdata](https://github.com/dankelley/oce/blob/develop/inst/extdata/CTD_BCD2010666_01_01_DN.ODF) uses this ``FFFF`` code. Jeff, does this mean the file should be updated? Perhaps you could suggest a new fil, if so. It should be a CTD file, I think, and actually Station 2 would be great because it advertises this important station. The present file is just 55k long, and I would hope for a replacement that length or shorter. Presumably the existing file can be run through BIO code to update the flag name (or should I just change lines 353 and 355 in an editor, writing ``QCFF`` where it says ``FFFF``?

**Comment by dankelley** [comment]
@Xandac -- any thoughts on (a) whether I need to do more work until you close this and also (b) should I use another sample file (as in previous comment)? Thanks!

**Comment by Xandac** [comment]
I will send you another sample file shortly.

**Comment by dankelley** [comment]
@Xandac -- is this something you feel you can close, or is there more I should be doing? (Remember, in the oce club we encourage reporters to close issues ... developers only do that if communication links have dropped.)
