### ISSUE TITLE
Do ensemble averaging for adp objects

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#781]
For "raw" ADCP data, it is often desirable to do ensemble averaging (e.g. time averaging) of the single ping to smooth the velocities and reduce the noise. Oce should have such functionality, which would likely take advantage of one of the functions `binAverage()`, `binMean1D()` or `binMean2D()`.

Using `binMean2D()` could be interesting, because one could also easily specify averaging _both_ time and depth bins ....

**Comment by dankelley** [comment]
Decisions to make re the defaults:
1. boxcar in time? (DK: yes, CR: ?)
2. work only on velo? (DK: yes, CR: ?)

Extra args can permit other stuff of course. For example, we could have an arg called `filter` that is ignored at the start, but that becomes perhaps `rep(1, 3)/3` by default (i.e. boxcar). It could also be named filters but if that's done then there needs to be another arg for the length, which gets confusing. 

Users will probably know the filter they want so they can supply coefficients themselves, saving a lot of coding mess by permitting a dozen named filters.

I'm not really clear on what should get averaged. Maybe if velo is filtered then so should amplitude etc but some of those are stored non-numeric so that's a small wrinkle.

Some care will be required in setting up arguments. The more arguments, the more difficult the coding and (I think) the harder it is for the user to understand. Maybe we should wait until one of us (or some other user) has a specific need, because then the work will likely be most relevant. @richardsc Did you have a dataset where you wanted to do this? If so (a) what filter did you want to use and (b) what fields did you want to filter?

**Comment by richardsc** [comment]
> Decisions to make re the defaults:
1. boxcar in time? (DK: yes, CR: yes)
2. work only on velo? (DK: yes, CR: no, include all fields)

I think that all fields need to be averaged, because otherwise the resulting object either has to drop the original fields or we have to deal with matrices of different sizes (and therefore different time bases, etc). The `raw` form for some fields is a wrinkle, but just a coding one.

I do have a dataset for this, that I have previously done the ensemble averaging manually. By far the most common approach is to do a boxcar filter in time, but I think it would be prudent to try to make it somewhat flexible. For example, I have also done averaging based on distance, when the `adp` object has longitude and latitude.

I'll get a dataset for this, and will add the (ugly) manual code that I used previously.

**Comment by richardsc** [comment]
Ok, don't judge, but here is some hacky old code from when I did the bin averaging myself. Not sure it will even run now, but I think you'll get the idea. I'll send the data file in an email.
```r
rm(list=ls())
library(oce)

camplat <- 68.91357
camplon <- -50.40264
angle <- -34      # rotation angle for along/across fjord axis

raw <- read.oce('ADCP061_000000.ENS', from=10, to=2506)

## Fix NA in first row of bottom velocity so that `despike` will work; not sure why it's there
raw[['bv']][1,] <- 0 

## Convert to xyz
maxDepth <- max(raw[['br']], na.rm=TRUE)
## xyz <- beamToXyz(subset(raw, distance < maxDepth))
xyz <- beamToXyz(raw)

## Remove the ship motion using bottom velocities
xyz[['bv']][,1] <- despike(xyz[['bv']][,1])
xyz[['bv']][,2] <- despike(xyz[['bv']][,2])
xyz[['bv']][,3] <- despike(xyz[['bv']][,3])
## FIXME: The bottom velocities should probably be smoothed before subtraction

xyz[['v']][,,1] <- xyz[['v']][,,1] - xyz[['bv']][,1]
xyz[['v']][,,2] <- xyz[['v']][,,2] - xyz[['bv']][,2]
xyz[['v']][,,3] <- xyz[['v']][,,3] - xyz[['bv']][,3]

enu <- beamUnspreadAdp(toEnu(xyz, declination=-33))

## Do bin averaging to smooth
z <- enu[['distance']]
nt <- dim(enu[['v']])[1]
nz <- dim(enu[['v']])[2]
dt <- 60 #s
tba <- binAverage(enu[['time']], enu[['time']], xinc=dt)$y
u <- array(NA, dim=c(length(tba), nz, 4))
a <- array(NA, dim=c(length(tba), nz, 4))
lon <- lat <- NULL
for (i in 1:nz) {
  ## velocities
  for (j in 1:4) {
    ba <- binAverage(enu[['time']], enu[['v']][,i,j], xinc=dt)
    u[,i,j] <- ba$y
  }
  ## backscatter
  for (j in 1:4) {
    ba <- binAverage(enu[['time']], enu[['a', 'numeric']][,i,j], xinc=dt)
    a[,i,j] <- ba$y
  }
  t <- ba$x
}
br <- bv <- array(NA, dim=c(length(tba), 4))
for (j in 1:4) {
  br[,j] <- binAverage(enu[['time']], enu[['br']][,j], xinc=dt)$y
  bv[,j] <- binAverage(enu[['time']], enu[['bv']][,j], xinc=dt)$y
}
lon <- binAverage(enu[['time']], enu[['slongitude']], xinc=dt)$y
lat <- binAverage(enu[['time']], enu[['slatitude']], xinc=dt)$y
t <- as.POSIXct(t, origin='1970-01-01', tz='UTC')

## trim off below bottom velocities
br <- apply(br, 1, mean, na.rm=TRUE)
for (i in 1:length(t)) {
  zI <- z > 0.94*br[i]
  for (j in 1:4) {
    u[i,zI,j] <- NA
    a[i,zI,j] <- NA
  }
}
```

**Comment by richardsc** [comment]
No immediate requests for this, so removing the `Next Release` label. But I still want to do it so keeping open.

**Comment by richardsc** [comment]
@Vinterwoo has requested this! (via #1177 but moving discussion here for completeness).

What's your timeline for needing this @Vinterwoo? I probably can't do this in the next couple days, but maybe by the end of the week.

**Comment by Vinterwoo** [comment]
Thanks for looking into this @richardsc. No rush on this feature, the end of the week would be perfect.

**Comment by richardsc** [comment]
I've started working on this in branch `cr-781`. It's still very preliminary (I started with the docs and am adding functionality as I go), but below is an example:
```r
library(oce)
data(adp)
par(mfrow=c(2, 1))
plot(adp,** which=1)
plot(adpEnsembleAverage(adp, n=3), which=1)
```
![image](https://cloud.githubusercontent.com/assets/233584/22535868/520f0ba2-e8d4-11e6-9cb7-d31a433b45f5.png)

**Comment by Vinterwoo** [comment]
That looks great @richardsc, thanks for putting that together. Will this be something that is available in the next release?

**Comment by richardsc** [comment]
Yes, for sure it will get included in the next release. If you can't wait until then you can always build the package from source, using the `cr-781` branch, but **warning:** this code is very provisional and not thoroughly tested.

It's also very "loopy", which I did for now for the sake of figuring out the method, so it might be quite slow on a larger data set. If speed is an issue the next step will be to make better use of the `*apply()` family of functions, or maybe re-write in C.

**Comment by dankelley** [comment]
A nuance: the code near `R/adp.R` line 3073 of the `cr-781` branch should have an `is.raw()` test, and then an `as.raw()` coercion, because some elements (like backscatter) are stored in "raw" format in the adp object.

Also, if we can be sure that simple ensemble averaging (i.e. using `mean` as the function) will be sufficient, then this could quite easily be done in C. But if we want users to be able to supply a function, things get a bit more complicated. (I say "a bit" mainly because I've never written C code that calls back to R to evaluation a function, but this is certainly permitted and well documented, so it could be done).  My feeling is that we ought to say with R coding until it proves too slow in actual work, however, because R is much less error-prone than C, and because most users will have some R skill, and quite a few users will also be keen to contribute their own ideas to the code.

**Comment by richardsc** [comment]
Good point on the `is.raw`/`as.raw`. I forgot about those fields.

**Comment by richardsc** [comment]
I've updated the `cr-781` branch to convert the `raw` arrays after the averaging. I also decided that rather than let the function sit waiting for extra functionality (that hasn't been asked for), I removed the `deltat` and `method` arguments. So, the user needs to specifiy *only* the number of pings to average, and it will do a simple mean of those pings.

I'll test some more but will propose merging sooner rather than later if @dankelley thinks the code looks ok.

**Comment by dankelley** [comment]
That's a good idea on not adding parameters that would be unused. Such things can always be done later. Generally, I'd say this passes the criterion for getting it into the hands of users. Plus, it's a new function, so it's presence won't break any existing code. If user experience shows that the interface needs changing, then that would be a new issue.

All of this argues for a merge.  I do think it would be good to have a little test suite goodness, though. I can do that, if you like. The way I do that is basically like below:

1. run the function to produce some results.
2. print the results
3. edit the printed results into a `test_equal` (or other comparison)
4. test locally, since a broken test will cause build failure

This is mainly a test against future changes, but in writing the tests, there are eyes on the results (e.g. in this case, if the `time` vector didn't have the right length, that flaw would be clear in editing the results into tests).

I can write a test if you like, Clark. That would basically be a code review. I'd prefer to do it on `develop`, though. Then I'd post a "I think this can be closed" comment and let you decide whether to close it.

**Comment by richardsc** [comment]
In the wake of other time-consuming tasks, I realized this was a little forgotten about. I'm going to merge the branch with develop, and fix any conflicts that arise. I think the test writing can come after that, if @dankelley wants to write one, and we can close the issue then.

**Comment by richardsc** [comment]
See PR #1199

**Comment by dankelley** [comment]
I've fulfilled PR 1199 and done some other adjustments (#1201 etc). This is now tested fairly thoroughly in the test suite, so I recommend that @richardsc consider closing this.

**Comment by jsta** [comment]
I have some more complex adv de-spiking code that I ported to R from https://github.com/macvicab/MITT/blob/master/CleanSpike.m that I am considering releasing as a separate package. Maybe it could find a home within `oce`?

**Comment by richardsc** [comment]
Hi @jsta ! Thanks for pointing that out. I definitely think that it could be helpful, and (without talking to @dankelley yet) I think it would make a pretty great separate package that builds on `oce`.

Since it's off topic for this thread, maybe you could move this to a new issue, and we can discuss there?

Thanks!

**Comment by richardsc** [comment]
Not sure why I left this open so long. I'll close and we can deal with any other issues separately.
