### ISSUE TITLE
add "build from source" instructions for OSX to webpage

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#786]
Configuring an OSX system to be able to build oce from source is a significant task, due to the variants in R binaries (i.e. "Snow Leopard" vs "Mavericks"), the requirement for significant external tools (XCode, Latex, GFortran), and exceptions for different processor architectures. Some definitive instructions should be added to the oce webpage (or better, to a wiki here on the Github site) documenting the process as much as possible.

**Comment by dankelley** [comment]
I love the wiki idea. I was thinking of the main webpage but it feels to me that the wiki is better, because it's so easy to make sub-pages, etc.  I think the notes you sent earlier are an excellent start.

My hope with this R consortium is that they will set up a bunch of osx machines of different types, and maybe even pay someone to ensure that R works on them. And I don't really see why R doesn't just provide gfortran within itself, ensuring that it uses that one during compilation and ignoring whatever the user may have on the box.

**Comment by richardsc** [comment]
First draft of wiki page:

https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source

**Comment by dankelley** [comment]
I like the wiki a lot.  I read it with the editor open, and made some tiny changes (marking software in fixed font, mainly, but also I think two sentences were made clearer by small working shifts.

I feel that the wiki is definitely good enough to be linked from the official oce docs. Mind if I do that?

**Comment by richardsc** [comment]
Yes, feel free to link away!

**Comment by dankelley** [comment]
Done, thanks! I'd say this means we can close but that's up to the reporter to judge :smiley:

**Comment by richardsc** [comment]
Going to keep it open for now so I remember to go back and update the sections I left empty.

**Comment by richardsc** [comment]
I've filled this in enough now that I'm going to close the issue.

**Comment by dankelley** [comment]
THANKS -- I think this is important for users who report bugs. Otherwise, the testing is going to be all up to us, because I don't like to update the precompiled OSX unless I think it's OK (and the windows is a lot slower, requiring an offsite compile, download, copy, etc.)
