### ISSUE TITLE
Advice for calculating Richardson number from CTD and ADCP data

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#787]
From a question from @gonzalobravoargentina:

> I am trying to calculate the number of richardson with ctd (N2) and velocity (v, u) from ADCP, there is some equation in the OCE package? or I should calculate dv/dz and du/dz with some diff equation in R.

The short answer to your question is that there are no functions in oce to calculate the Richardson number. In general, Ri is kind of a tricky thing to calculate from data because: 

a) there are a few different definitions (e.g. gradient Ri, bulk Ri), 

b) the relevant fields are often not measured at the same scales (e.g. ctd data vs ADCP bins), and 

c) calculating derivatives tends to amplify the noise in the measurements if no smoothing is performed.

That being said, here are a few thoughts. 

The function `swN2()` calculates the buoyancy frequency from a density profile, which as you probably knows involves an estimate of drho/dz. If you read the help page for `swN2()`, you'll see that quite a bit of thought has gone into how best to calculate the density derivative, and there is a fair bit of control over what method is used. The principles used in `swN2()` will likely be useful for informing how best to calculate du/dz and dv/dz for the velocity gradients. 

The default method for N2 is to use a smoothing spline with `smooth.spline()` to smooth the density profile, and then predict the derivative directly from the spline. The amount of smoothing can be controlled with the `df=` argument (see the help page for `smooth.spline()`).

If `swN2()` is called with `derivs="simple"`, then the derivative is estimated using `diff()` on the density and pressure and dividing them. Depending on your velocities this might be sufficient for the vertical gradients.

The other thing to consider is that most likely the density profiles and velocity profiles are at different depths. For example, CTD data will likely be quite highly resolved, while the velocity data will be averaged to vertical bins (which for RDI have some overlap with the above and below bins), possibly of several meters in extent. I recall that the test data from Issue #777 had 4m bins. You will either need to interpolate the velocity to match the density resolution, or average the density field to match the velocity measurements (recommended). You probably already know about `ctdDecimate()`, but that is where I would start for thinking about how to average the density to match the velocity.

While this issue represents "advice" as opposed to the standard "bug report", I'll leave it up to you @gonzalobravoargentina to close the issue when you're satisfied that the original question has been addressed.

**Comment by richardsc** [comment]
Hey @dankelley, can you make a new label type to cover issues such as this one (I don't seem to have label-making privileges)? Maybe something like "question" or "advice"?

**Comment by dankelley** [comment]
I agree with Clark's advice. There are no standardized methods for doing this. Many things that seem simple in a textbook are difficult to do with data. In a textbook, a derivative is perfectly clear--a limiting value of a function. But it's impossible to do limits with data. This is is one reason why calculating N^2 is tricky, and that's just half of the Richardson-number calculation.  Whenever you read about Ri in a paper, the authors will generally state how they calculated it (often by running some particular smoothing filter through data) and if you start a list, you'll notice that there is no single, standardized, method. This is partly because every dataset seems to have its own challenges, and methods tuned for one application can fail for another.

In the book I'm writing, I say that we are using ROP (research operating procedures) and not SOP (standardized operating procedures). A big reason for this is that the work involves data collected at sea. I think if we mainly did lab work, we'd have SOP for a lot of things.  (For example: use bottles of such-and-such volume made from such-and-such material; wash each bottle N times in such-and-such acid at such-and-such concentration, then wash M times with distilled water of quality Q, then air dry at temperature T in a dust-free environment refreshed by air run through a such-and-such filter.)

Please note that I followed Clark's advice, and made a new label, 'advice/science', which seems to be the best description of this. I also made 'advice/programming', which could be used for things that are more along the lines of computer programming.

**Comment by richardsc** [comment]
Hi @gonzalobravoargentina,

Did you have any luck with this? If you'd like to post sample code here I'd be happy to comment on it. If you can make a reproducible example (i.e. one that we could run without heavy editing of the source code), that is best.

See http://adv-r.had.co.nz/Reproducibility.html for tips on making a reproducible example.

**Comment by gonzalobravoargentina** [comment]
I am working on it, but is not going easy. 
I have a question about the ADP files, where the data of depth or pressure come from?

                                          Min.          Mean          Max.
v                                    -2.190000e+00  4.370884e-01  6.485000e+00
q                                     0.000000e+00  1.172778e+02  2.550000e+02
a                                     3.000000e+00  5.400147e+01  2.320000e+02
g                                     0.000000e+00  1.065154e+01  1.000000e+02
br                                    9.595000e+01  1.145926e+02  1.236300e+02
bv                                   -3.276800e+01 -7.433576e+00  5.553000e+00
pressure                         0.000000e+00  0.000000e+00  0.000000e+00
temperature                    6.340000e+00  6.632901e+00  6.930000e+00
salinity                             3.100000e+01  3.100000e+01  3.100000e+01
depth                               2.900000e+00  2.900000e+00  2.900000e+00

**Comment by richardsc** [comment]
Typically an OceanSurveyor does not record pressure data -- this is because it is a hull mounted transducer and there is no place for a pressure port.

Perhaps what you're looking for is the `distance` variable, which you can get by doing e.g.:
```r
library(oce)
data(adp)
d <- adp[['distance']]
```
These distances are the *perpendicular* distance of the **centre** of the bin from the ADCP transducer. Note that to know the real **depth** of the bin you have to add the depth of the transducer -- I think that's what you get when you look at the `depth` variable (e.g. 2.9 m). 

You may also need to think about whether the velocity data has already been corrected for pitch/roll variations -- this is often referring to as "bin mapping".

**Comment by dankelley** [comment]
I'm wondering about the conditions for closing this issue. According to the title, I suppose this should be closed when advice has been given. That happened 5 days ago, so I'd argue that this should be closed.

Discussion can always be added to closed issues, but it seems to me that the issue (according to its title) has been resolved.

Just a suggestion ... I'll let the poster decide, of course.

**Comment by gonzalobravoargentina** [comment]
I dont have time to work more on it know so I will closed and added commentaries when I get closer. Thanks!
