### ISSUE TITLE
read.echosounder() only read BioSonics instruments?

### ISSUE THREAD

**Issue by gonzalobravoargentina** [dankelley/oce#790]
It try to read a echosounder file of a Simrad EK 60 MK1 and is not working, I have 3 extensions files  (.idx, .raw .bot). Is posible to read this files?

**Comment by richardsc** [comment]
Currently oce cannot read such files. In order to try to be able to read them we would need some documentation on the file format. I was unable to find such documentation in 2008/2009, when I acquired data from the Simrad system on the Coriolis II, but it wasn't a high priority so I didn't look too hard.

There are lots of ES and multibeam forums, and it's possible that the solutions are described somewhere. I'll try and have a look around tomorrow, but in the meantime if you've found any documentation that would be a good place to start.

**Comment by richardsc** [comment]
Not sure if this will be of any use, but there seems to be some description of the data format in this manual:

http://www.simrad.com/www/01/NOKBG0397.nsf/AllWeb/F2AB311B3F6E6B15C1257106003E0806/$file/164692ad_ek60_reference_manual_english_lores.pdf?OpenElement

**Comment by richardsc** [comment]
The `EchoviewR` package looks like a good option for serious echosounder processing:

http://journal.frontiersin.org/article/10.3389/fmars.2015.00015/full

The downside is that it requires the EchoView program, which is not free.

**Comment by richardsc** [comment]
Another option might be to have a look at the [Echolab Matlab toolbox](http://hydroacoustics.net/viewtopic.php?f=36&t=131).

**Comment by dankelley** [comment]
There are no immediate plans to add this data type to oce, so this issue (as described in its title) seems to have been addressed fully, and is a candidate for closure, perhaps.
