### ISSUE TITLE
makeSection() should be deprecated in favour of as.section()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#791]
No need to have two functions that seemingly do the same thing, and `makeSection()` has non-standard naming. Seems like whatever it does differently from `as.section()` can be incorporated into the latter.

I see that currently `as.section()` actually *calls* `makeSection()` at [Line 1577](https://github.com/dankelley/oce/blob/acc8a1109e3b9b01f35d3fb95425ef686e5b076c/R/section.R#L1577)
```r
makeSection(ctds) # FIXME: why have makeSection(), when as.section() is a better name?
```

**Comment by dankelley** [comment]
I'll change this in a few days. It's a only few screenfuls of code, and people must not have been using `makeSection` since it's had an error for something like a year, in calling a now non-existent `+` operator to string a ctd into an existing section.

**Comment by dankelley** [comment]
This comment will be used for thoughts during coding. It will be edited over time ... thus, the email aspect of GH will fail on this comment. The point is that I find scrolling across screens of a webpage to be quite confusing (and it's made worse by the GH choice to use a lot of whitespace, which I think reduces the information density by a factor of 4 or so).

The interfaces of these two functions are quite different, so I don't think I can make them work with a common argument list. For example, in
```r
s1 <- makeSection(ctd1, ctd2, ctd3, ctd4)
s2 <- makeSection(s1, ctd5)
```
we permit the first arg to be either a CTD or an existing section. Two interesting things are going on here:

1. `makeSection()` examines the first (but only the first) arg and handles CTD and SECTION differently
2. The second arg to `makeSection()` is `...`, which lets the user supply an arbitrary number of CTDs. 

I like the first of these, and it's a common pattern in oce and in R generally. But the second makes a direct emulation of `makeSection()` with `as.section()` a bit tricky for coding, since the latter has all these named arguments. And I have this general feeling that things that are tricky to code are tricky because they are tricky to describe in the docs, which means they are tricky also for users.

The second of these is a problem. I think it's an example of an interface that scales poorly. If a person wants to add just one CTD to an existing section, they can use `sectionAddCtd`. They can also repeat that in a loop, to add a lot of CTDs. So the mode `makeSection(section, CTD)` is covered already. The other mode, with a lot of CTDs named, is not too useful in general. Sure, it might seem convenient for 3 CTDs, but for 30 or 300, it's a problem to get right. I much prefer asking the user to string the CTDs into a list (and the docs can show how).

Given all of this, my present feeling is *not* to alter `as.section()` to check whether the second, third, etc., arguments are CTDs, so that `makeSection(section, CTD1, CTD2)` will simply become something that cannot be done directly.   I know this may break some code but the fact that `makeSection()` has been broken (spitting an error message) for about a year tells me that nobody using the `development` branch is going to be affected, and that probably means most users who would be string CTDs together, which I consider a fairly advanced operation (compared to plotting a CTD, which I imagine is quite common).

**Comment by dankelley** [comment]
I've updated `as.section()` in the `develop` branch, to handle more cases as discussed in the just-previous comment. I also added several tests, and these echo the docs, so the docs should be more helpful now.  

Finally, I've put a deprecation warning into `makeSection()`, although this function still exists. The warning says it will be removed in the next CRAN release. But, for my own work, I've given up on `makeSection` and see no real need to keep it. I'm a bit concerned that I leave it in `develop`, I'll forget to remove it before a CRAN release. So my vote is to just delete `makeSection`. @richardsc -- what do you think about removal?

**Comment by richardsc** [comment]
I know it will break some of my code (which is fine), but I don't have a good sense of how many other users would be confused by a full removal. I seem to recall that @atcogswell had been using sections.

**Comment by dankelley** [comment]
At the moment I have it marked with `.Deprecate`, and I think the [bioconductor](https://www.bioconductor.org/developers/how-to/deprecation/) scheme is that this be done in one release (which gives a warning), that the next release will mark it defunct (tossing an error) and the next after that will remove it. I think oce should follow this scheme.

**Comment by atcogswell** [comment]
Not really a hug issue for me, I can make the necessary updates to my code the next time I use it.
________________________________________

**Comment by dankelley** [comment]
@richardsc maybe you could try a build sometime and see if you agree with me that this has been addressed ... if not, we could leave it open. Thanks!

**Comment by atcogswell** [comment]
Hi Dan,

I’m on to another project right now and don’t really have time to go back to this right now.  Perhaps leave it open then.

Andrew

**Comment by dankelley** [comment]
Sorry, Andrew; that last was meant for Clark (indicated by the at-sign). Thanks. Dan.

**Comment by richardsc** [comment]
This seems good now. Closing.
