### ISSUE TITLE
1. resizableLabel needs more O2 units; 2: metadata$units requested

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#794]
This is probably part of a bigger discussion on units, generally, but tonight I noticed while working on #762 that when an `oxygen` channel exists in a ctd object, `plotProfile()` automatically gives it a unit of `umol/kg`. 

Now, `umol/kg` does seem to be a standard (see e.g. http://www.argodatamgt.org/content/download/2928/21973/file/ARGO_oxygen_proposition_v1p2.pdf), but it's a *calculated* variable, not what DO sensors typically measure. The "raw" measurement is typically "% saturation", which can be converted to `mL/L`, `umol/L`, and `umol/kg`. RSK files store `% saturation` by default.

Not a big rush, but one of those things that worth thinking about. Right now we have separate `@metadata` fields for `temperatureUnit` and `conductivityUnit`. Long term it might make sense to have a `units` field that contains units for all the data channels.

**Comment by dankelley** [comment]
I agree -- I think it should be called `x@metadata$dataUnits` because then the name is clearly related to the data. (Some people might think of other meanings for units, e.g. that word is sometimes used for devices.)

**Comment by dankelley** [comment]
Here's an idea for an interface: `x[["temperature"]]` yields as now, but `x[["temperature", "unit"]]`` gives its unit. That way users can write code using units, without worrying about where that info is stored. We could actually do other stuff like this, e.g. `x[["temperature", "flag"]]` could return a flag vector.

CR--What do you think?

**Comment by dankelley** [comment]
I've given this 4 stars because if we are going to do something general like I propose, I'd like that in the next release. (We won't get user interface conflicts because that second word was never used in accessors before.)

**Comment by richardsc** [comment]
I think this could work. I think that the accessor approach to grabbing units can be a little cumbersome, but really the most benefit is in having that behind the scenes, for convenience functions like `plotProfile()` etc.

Keeping track of all these units is hard, but at least if they're documented in the object when they are available to be read from a file the user can sort it out. And functions like `plotProfile()` can use what is there rather than having to guess.

**Comment by dankelley** [comment]
Re "cumbersome" I agree. As usual, this back-and-forth is very helpful.

Best to retain the present scheme, e.g. `d[["oxygenUnit"]]` etc.

I think I'll go ahead and set this up. No need for an issue of its own, I think.  So long as users were not doing `d@metadata$conductivityUnit` but instead were doing `d["conductivityUnit"]`, their code will still work even if the stuff goes into `metadata$units`. But *old objects will break* if we move to `metadata$units` and that argues *against* making a new item called `metadata$units`. I still feel it should be in a new item, though, because we are still at version 0.x and can modify such things.

Let's vote.

DK:
* [ ] store as `metadata$oxygenUnit`
* [x] store as `metadata$units$oxygenUnit`

CR:
* [ ] store as `metadata$oxygenUnit`
* [ ] store as `metadata$units$oxygenUnit`

**Comment by dankelley** [comment]
I have pushed 957c2fa8cea63c42394f584385b117f88c952971 to `develop`. Now, there are more oxygen units. I decided to make the default be to show *no* unit, which I think makes sense. (I'd rather it not show a unit that might have been guessed.)

I have not coded in an `oxygenUnit` but I'll do that once we get a vote (see prev comment). I ticked that I prefer a particular scheme for that but I don't feel strongly ... say my preference is 60% only, so if you have a 100% the other way, you'll win the vote. Possibly you can edit the above comment with a numerical value.

**Comment by richardsc** [comment]
Voted!

**Comment by dankelley** [comment]
Thanks!

**Comment by dankelley** [comment]
1. I altered the title because I couldn't find the right issue just now.

2. I altered the code and several data files. Below is the commit and msg ... please note the request at the end, because I do suspect we will have problems reading some old data.  NOTE: I will rebuild the "cm" dataset to have this new `metadata$units` item, once I can find the code that built it in the first place and create an entry in `create_data`.

commit 405df792640b9eaa890ceb1e83a9382030841a41
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Sun Dec 13 12:23:50 2015 -0400

    put T/C units in metadata$units, a list
    
    This involved changing a lot of files, so we can expect new bugs, even
    though I tried to make the accessor functions be robust across the
    change. I rebuilt the ctd, rsk and section objects to be in this new
    format, which should mean that objects created with the previous system
    will still "work". However ...
    
    EXPECT BUGS and please report them!

**Comment by richardsc** [comment]
Great! I'm good at breaking things so I'll look out for issues in testing.

I wonder if a related issue to this should be that `as.ctd()` gets a `units=` argument, for when objects are created that way.

**Comment by dankelley** [comment]
Do you mean replace `temperatureUnit` and `conductivityUnit` with `units=list(temperatureUnit=...,)`?  I'd vote not to add another arg that does the same thing, because e.g. what if there is a conflict .. which arg wins will be an extra wrinkle in the code and a confusion for the user. 

Another choice would be to replace the two existing with a new `units=list()`, but doing that will demand that the user specify both (or, again code and user confusion).

From the above, I'm coming down on the side of not adding a new `units` arg. But maybe you could argue for ... er, um, that arg?

**Comment by richardsc** [comment]
Well, as you point out the version isn't at 1.0 yet so users should expect things to change.

The problem with the current scheme is that there is no way to add *other* units (beyond temperature and conductivity). So in the case of the `oxygen` data that started this, how would one include the correct unit in the metadata, where other functions (like `plotProfile()`) can use it?

I think that in general I'm liking the approach of the new `units` arg, because it organizes what could potentially become a mess of metadata elements. The problem is backward compatibility with what we've already done (which was actually relatively recently, IIRC). I see two solutions:

1. remove the `temperatureUnit=` and `conductivityUnit=` args from `as.ctd()`, and replace with something like `units=list(temperatureUnit=..., conductivityUnit=...)` as you proposed. 

2. keep the two existing unit args, but add a new one called something like `otherUnits=list(oxygenUnit=..., turbidityUnit=...)` which is documented to take everything *except* for T/C. They all still get slotted into the same `@metadata$units$...` list, as are being done now.

**Comment by dankelley** [comment]
You're right, it's version 0.x now. I propose I remove the two existing `.*Unit` args and replace with `units=list()`. Same idea on `flags=list()`.

And, as usual, you've seen to the core of the issue -- if we make it a list, then people can have units for their other data (and later on, those units could get use for plots etc).

**Comment by dankelley** [comment]
I started a [wiki page](https://github.com/dankelley/oce/wiki/developer-checklist) to keep track of work items. I find it hard to remember them, and therefore they tend to get lost (unless the issue title makes them obvious).

**Comment by dankelley** [comment]
I started some work on units in a new branch named `units`.  There’s more to do, but I thought I should mention this because others may run into problems when I merge this into `develop`.

From now on, we do e.g.
```R
	X@metadata$units$temperature <- “my new unit"
```
and not the old
```R
	X@metadata$temperatureUnit <- “the old way”
```

I have made the accessors work, but I’m sure there are some wrinkles that will need fixing.

I also plan to rebuild all the objects, probably this afternoon.

This is mainly to clean things up. The interface for creating objects is still using e.g. 
```R
new( … temperatureUnit=“hi old buddy”)
```
instead of the planned
```R
new(… units=list(temperature=“my new buddy”))
```
and the same for the `as.X()` functions.

Gradually, the units will find their way into summaries. So far this only works on coastlines, e.g. below see the unit in the 3-number summary.
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> data(coastlineWorld)
> summary(coastlineWorld)
Coastline Summary
-----------------

* Number of points: 10696 , of which 287 are NA (e.g. separating islands).

* Statistics of subsample::

                           Min.     Mean      Max.
   latitude [degree north]  -90 18.42117  83.64513
   longitude [degree east] -180 11.12873 180.00000

* Processing Log::
  * 2015-12-22 08:58:31 UTC: ``create 'coastline' object``
  * 2015-12-22 08:58:31 UTC: ``read.oce(file = "ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp")``
```

**Comment by dankelley** [comment]
I've merged `units` into `develop`, since it's been working fine for me for several days of different sorts of tasks, and since I think it is on balance better than `develop`, despite the chance that it will have some new bugs to be discovered.

**Comment by dankelley** [comment]
I think this issue has been addressed in `develop`, but the issue has touched on several topics so I'm not quite sure. It would help a lot if @richardsc could assess whether this needs to remain open, or whether it could be closed, with any remaining work being in new issues with narrower definitions.

**Comment by richardsc** [comment]
I've had a bit of a test and look over the last couple days. I think this can be closed now and new problems assigned to new Issues.
