### ISSUE TITLE
default palette for colormap (and maybe imagep?) should be oceColorsViridis

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#810]
The default colour scheme for `colormap()` is "Jet", which is problematic for a variety of reasons already discussed when we added a suite of nice python-derived colormaps a few months ago. I think that the default should be changed to `oceColorsViridis`.

One could also make the argument for switching the default in `imagep()`, but it isn't Jet and has been how it is for so long I'd argue to just leave it alone.

**Comment by dankelley** [comment]
I know I'm not supposed to like jet. However, I discovered something when showing something in class. We have a reasonably good setup (the uni paid a lot of money for the projector etc, the room lights can be turned off etc) but with these newer color schemes the students could not see a thing. But with jet, they could see things I pointed out. I can say "see the yellow band" and point to the screen, and they see it. However, if I say "see the green smudge that's a little different from the blue-green smudge" they cannot see anything.

I tried tests with printing, using a variety of printers. Some printers are better than others, but for a lot of them, the problem is similar (but not as bad) as with the projector.

For teaching, I therefore find "jet" to be the better option. Heresy, I know.  It really amounts to a desire to be quantitative, using colour changes as contour levels, and that's easier with colours that are clearly distinct.

... I expect flames :wink:

**Comment by richardsc** [comment]
Haha, that's a great story actually, and not one that you often hear because I think most people are focused on publication quality plots. I actually saw something similar at a conference I was at a few months ago where the projector was dropping some of the "Jet" colour levels so that everyone who used it had to apologize to the audience that the feature they were pointing out was missing. But at the same time, there were TV screens at the sides of the room so that people at the back could see those, and the colours were just fine on there.

Ok, I'll close. I just thought it was worth bringing up :). No flames here.
