### ISSUE TITLE
Add support to subset Argo objects by "mode" (delayed, realtime, etc)

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#830]
This came up in Issue #759 , but is separate from the concept of "quality flags", which was dealt with in Issue #829.

The notes below relating to the "mode" have been copied over from #759:

* there is a field called `DATA_MODE` variable, which describes whether each profile represents "delayed mode" or "real time" data. Many studies using Argo data make use of *only* "delayed mode" data, as this is considered to be the most reliable. The `nc` file contains the following description:

  > R : real time; D : delayed mode; A : real time with adjustment

  These are typically considered to be the most reliable data, and therefore I think should be the fields read by oce by default. Perhaps `read.argo()` can have an argument like `mode=c('delayed', 'realtime')`, where the default is `delayed`.

* there are QC fields for each profile (e.g. `PROFILE_TEMP_QC`), and for each sample within the data matrix (e.g. `TEMP_QC`). The `PROFILE_*_QC` field summarizes the amount of good data in each profile, and so is somewhat redundant. See table 2a at: http://www.cmar.csiro.au/argo/dmqc/user_doc/QC_flags.html. I think it's used as a quick way of tossing entire profiles, rather than evaluating each depth level.

* The "corrected" profiles are stored in the `ADJUSTED` fields, e.g. `TEMP_ADJUSTED`. Note that even though the field is "adjusted", one should also look at the `DATA_MODE` field to determine which profiles are actually "delayed" mode profiles. It's possible that some data may have been adjusted, but not yet gone through delayed mode processing. E.g. the `DATA_MODE` variable for my example float looks like:
  ```
  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  ```
  This means that the last 40 or so profiles have been "adjusted", though they are not considered to be "delayed mode".

* There are also QC fields for the "adjusted" values, but for the file I have been using as an example (contained in the oce-issues repo) they seem to be the same as the original QC fields

**Comment by richardsc** [comment]
Pull Request #831 adds the data mode functionality (but **NOT** the "ADJUSTED" data functionality). Test code can be found in [oce-issues/830](https://github.com/dankelley/oce-issues/tree/master/830).

Note that I also tweaked the `summary()` method to show the number of delayed/adjusted/realtime profiles:
```r
> summary(d)
Argo Summary
------------

* source:     "/Users/richardsc/src/R-kelley/oce/create_data/argo/6900388_prof.nc"
* id:         "6900388"
* Profiles:   "166 delayed; 0 adjusted; 41 realtime"
* Time ranges from 2005-10-29 13:52:11 to 2011-06-20 15:17:14 with mean increment 10.00029 days
* Statistics of data
                                 Min.       Mean     Max.
     longitude [°E]           -60.520 -37.264246  -21.385
     latitude [°N]             48.743  56.716464   64.335
     salinity [PSS-78]         14.067  34.932594   47.899
     temperature [°C, ITS-90]  -1.564   6.106073   55.997
     pressure [dbar]            3.600 522.250122 6534.600
* Processing Log::
  * 2016-01-16 22:33:40 UTC: ``create 'argo' object``
  * 2016-01-16 22:33:40 UTC: ``read.argo(file = "~/src/oce/create_data/argo/6900388_prof.nc")``
```

and I updated the `subset()` method to handle `dataMode`:
```r
D <- subset(d, dataMode == "D")
```

Note that for the example in [oce-issues/830](https://github.com/dankelley/oce-issues/tree/master/830) I'm reading the included `argo` dataset, which means that following these changes it will have to be rebuilt to include the new `@metadata$dataMode` field. Will that happen automatically on build?

@dankelley I'd appreciate your eyes on the code, since my knowledge of methods, classes, etc is much lower than yours.

**Comment by dankelley** [comment]
Thanks a million for all of this.

Here is what we have to do when a dataset is altered:

1. build oce with new code but existing dataset. It can help to also do a build-check, which will fail if any old tests fail in the new data format.  (We want to know if it will fail!)
2. do as follows:
    cd create_data/argo
    make clean
    make
    # go into R and look at the local load('argo.rda') or a while
    make install # puts it in the data/ directory
3. we now have an updated dataset, so rebuild and recheck again

I did the above and pushed to GH. I noticed a few problems in the check (may all be mine, since I'm cleaning up documentation and adding object-orientation docs) which I'll clean up within the hour.

**Comment by dankelley** [comment]
I **love** the new `subset.argo`.  I always wondered whether something was different with those profiles that get chopped out when the subsetting is restricted to the `"D"` data. THANKS!

**Comment by richardsc** [comment]
I was thinking that in addition to the classic `subset()` syntax (e.g. above) it might be handy to have a calling mode something like:
```r
d <- subset(argo, 'delayed')
```
but I didn't really know how to code that option. Do you think it would make sense, or is it better to keep a consistent `LOGICAL` approach to specifying the subset?

**Comment by dankelley** [comment]
It could be coded, but it disagrees with the basic `subset` so I think it's a bad idea.

I'm twiddling with the code right now, trying to use roxygen2 for some of these docs.  It's a bit tricky, but once I figure it out for one thing, we can start using that for new things. The advantage will be that docs will be findable as for other packages. It is wonky, though; to get help on the basic subset you type
```r
?'subset,oce-method'
```
which is not what we had before.  I think there is a way to make aliases for the old
```r
?'subset.oce'
```
but I'm not sure that's really advised. To be frank, I never knew how to find those things before, anyway.  I am going to make the output from
```r
?oce
```
give much better hints on how to find such detailed information.

I mention this mainly because git doesn't "understand" the top line of a roxygen2-generated `.Rd` file, and so if you were to alter one of those that I had since roxygen2-ized, we would lose the changes.  I guess I'm advising that you not edit `.Rd` files too much, or, if you do, please put a note to that effect in the pull request so that I'll know that I have to manually copy some info over, if I've done the roxygen2 trick on the given function.  You will find roxygen2 is quite nice, with less need for closing braces etc.

**Comment by richardsc** [comment]
> It could be coded, but it disagrees with the basic subset so I think it's a bad idea.

I agree I think. Better to keep it simple and consistent.

>  I think there is a way to make aliases for the old
    ?'subset.oce'
but I'm not sure that's really advised. To be frank, I never knew how to find those things before, anyway.

I second the confusion about how to find help on such things. Currently, you have to know that there are methods for a particular class, and then just try to get the help page. One way to get some hints is to use `showMethods()`, e.g.:
```
> showMethods('subset')
Function: subset (package base)
x="adp"
x="adv"
x="ANY"
x="argo"
x="cm"
x="ctd"
x="echosounder"
x="lobo"
x="met"
x="oce"
x="odf"
x="rsk"
x="sealevel"
x="section"
x="topo"
```

**Comment by richardsc** [comment]
As for the note about Roxygen2 generated files, the fact that it puts a comment like:
```
% Generated by roxygen2 (4.1.1): do not edit by hand
% Please edit documentation in R/oce.R
```
is usually enough to warn me about where to actually edit the docs.

**Comment by dankelley** [comment]
I'm trying (slowly) to get things to the state where someone can do
```r
?oce
```
and start to see how to do things. For example, doing that will show a link for help on the `[[` function ... and it also shows what you can type if you don't want to click that link.

If neither you nor I can remember how to find S4 help then I don't imagine newcomers will find it.

Note: as I roxygenize, I am trying always to put in an `@aliases` to get the old name, so people won't need to change their habits.

**Comment by dankelley** [comment]
I switched the docs for some `adv` functions into roxygen format. Then the build check complained that some things were not documented. I was trying to see how to make it mellow out on that (so people would realize that `[[` for adv was just inherited from the base class) but then I realized that the adv extraction has some extra details (e.g. we can get `a` in raw or numeric form) so I wrote some more words for that. Indeed, I *like* the fact that it complains that those things are not documented, since probably most cases will have some tailoring.

I plan to do `argo` next, because that's being worked on lately.  And, actually, I want the excuse to write a sentence or two on the different modes (of course you'll want to fix it up since I'll get it wrong) because the case of the built-in dataset convinces me that I need to know this!  **Please reply if you're in the middle of editing some argo docs, and I'll skip it. It will only take me 15 minutes.**

**Comment by dankelley** [comment]
I updated things. Also, I think you were missing something in your new `subset` code, so I updated; a diff is below.  PS. I love these subset examples. Argo is becoming my favourite dataset because there is so much teachable stuff in it.
```
diff --git a/R/argo.R b/R/argo.R
index 62d06d1..38e7182 100644
--- a/R/argo.R
+++ b/R/argo.R
@@ -125,6 +125,7 @@ setMethod(f="subset",
                   res@data$salinity <- x@data$salinity[keep,]
                   res@data$temperature <- x@data$temperature[keep,]
                   res@data$pressure <- x@data$pressure[keep,]
+                  res@metadata$dataMode <- x@metadata$dataMode[keep]
                   res@processingLog <- processingLogAppend(res@processingLog, paste("subset.ctd(x, subset=", subsetString, ")", sep=""))
               } else {
                   res@data$time <- x@data$time[keep]
```

**Comment by dankelley** [comment]
I feel this is suitable for closing (by the reporter ...), unless you wanted more stuff. (It's my usual definition of the closing criterion -- "has the task in the title been addressed".)

**Comment by richardsc** [comment]
> Also, I think you were missing something in your new subset code, so I updated; a diff is below.

I didn't think so, but I'll look at this closer later. I think the line you added is when subsetting for pressure, which doesn't trim entire profiles and therefore should trim out `dataMode` values (just like it doesn't trim `time` values).

**Comment by dankelley** [comment]
Oh, I'm likely wrong, sorry. I'll be offline until likely tomorrow morning.

**Comment by richardsc** [comment]
I think it is wrong, but will fix it. No biggie.

Another thing I noticed that needs to be added for `argo` subsetting generally is to subset the `flags` field. Working on that tonight.

**Comment by richardsc** [comment]
See PR#832. Dan's fix was reverted, and `subset.argo()` now will:

1. subset all data fields present in the object (not just T, S, and p)

2. subset the `@metadata$flags` field to match the data subsetting.

I will close once @dankelley has had a look.

**Comment by dankelley** [comment]
Thanks for the PR and the great additions. I will likely add flags to CTD data sometime this week. That will mean any flag code will get tested two ways, which should help to make it sensible and robust. (Also, I think, `argo` and `ctd` are the two datasets in which human-edited flags are most common, so these are the cases we most need to consider.)

**Comment by dankelley** [comment]
There's an error in building the new version, revealed by travisCI and by a build-check in RStudio. I'll have a look sometime today.

**Comment by dankelley** [comment]
I fixed the error. We had to skip out also the `profile` field.  FYI in RStudio, doing the test suite (not the build tests) is just a keystroke and maybe 30s.  The actual build test takes a few minutes.

**Comment by dankelley** [comment]
@richardsc I'm curious as to why the realtime mode data have better TS. Just an accident, do you think?

```r
library(oce)
data(argo)
par(mfrow=c(1,3))
plot(argo,which=4)
plot(subset(argo,dataMode=="D"),which=4)
plot(subset(argo,dataMode=="R"),which=4)
```

![a](https://cloud.githubusercontent.com/assets/99469/12389747/353c1af0-bdb1-11e5-8b64-7ec32ed9c791.png)

**Comment by richardsc** [comment]
> @dankelley wrote: I'm curious as to why the realtime mode data have better TS. Just an accident, do you think?

Good question! My guess is that even though the delayed mode data are considered to be "best", there is still the possibility of spikes and other bad data points. I'd expect that those funny points probably have flags indicating as such ... I'll have a look before closing.

**Comment by dankelley** [comment]
Yes, they have the flags.  I guess I just find it neat that, by coincidence, the data that needed to be flagged were in that delayed component. Actually, I don't really get why the dataset has both components. Surely the delay is not going to be several years?  Anyway, this is just for my interest -- nothing to do with the issue, which I think has been addressed very nicely.  (I may make a new issue on reading all the data.)

**Comment by richardsc** [comment]
I think this is addressed for now, so closing.
