### ISSUE TITLE
plot.section() fails for some auxiliary data types

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#837]
See https://github.com/richardsc/mbari

**Comment by richardsc** [comment]
See code in `example8486.R` at the above linked repo.

Using an `argo` object with some added supplemental data fields, I get weird errors when trying to plot (some of) the fields. Note that it doesn't happen for all fields, e.g.

```r
plot(ds, which='temperature')    # works!
plot(ds, which='chlorophyll')
Error in if (any(diff(x) <= 0) || any(diff(y) <= 0)) stop("increasing 'x' and 'y' values expected") (from section.R#863) : 
  missing value where TRUE/FALSE needed
```

**Comment by dankelley** [comment]
I see what is happening (below -- just notes to myself; browser output at `section.R` line 866) and will look into *why* it happens, now. Again, to be clear, this comment is just a note to myself -- sorry for an email ding.
```
Browse[1]> diff(order(yy[yy.unique]))
 [1]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[18]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[35]   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
[52]   1   1   1   1   1 -64   1   1   1   1   1   1   1  58
```

**Comment by dankelley** [comment]
I think this is working now in `develop` commit 0a02cc3ea2630837516b0590497ce1582d316f77

My logic was wrong; `plot.section()` was only doing the `sectionGrid()` when the `which` had been identified from a list. Now it does that all the time, so long as `which` is neither `data` nor `map`. The diff is larger than it should be -- the actual fix was just in one if statement -- because I had to make it print tons of stuff to see the problem.

PS. I did this in the `argo` branch and then merged `argo` back into `develop` because I think normal users should not be touching feature branches like `argo`.  There is more stuff to be done with the `argo` branch, and so if there end up being bugs in the present fix, I'll do them in `develop` so normal users can get them.

PPS. I modified `example8486.R` to plot the test.
