### ISSUE TITLE
vignette should be updated for CRAN release

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#859]
It wouldn't hurt to update the vignette to highlight recent changes. Perhaps we can use this issue to suggest possible additions, and then decide on a definitive goal to achieve by early next week.

Some ideas:

* [ ] argo objects
* [x] more examples of projections
* [x] map projection with `mapImage()`
* [ ] colormaps
* [ ] others...

**Comment by dankelley** [comment]
Agreed. I translated the Rnw to Rmd. The procedure is a bit tricky. I'll explain in Rstudio terms:
1. edit `vignette/oce.Rmd` and **do not touch anything in** `inst/doc`.
2. run `devtools::build_vignettes()` in the project. This will build up html etc and copy over to `inst/doc`
3.build package as normal

The missing step, and the reason why we didn't have a vignette, was not doing step 2. Previously, the recommendation was to put vignette materials into `inst/doc` but now they say put into `vignette`, which I had done, but I had not realized that then a normal build won't help. I understand why the normal build won't help ... creating vignettes is not part of the build process; the build just copies files.

Anyway, we now have a `vignette/oce.Rmd`. It doesn't have the TDR stuff. I edited a few other minor things also. I like all your examples. I think maybe I'll do some today, probably starting with the projections because I can use my blog item to find some nice ones to show. For argo, I may basically redo things like we have in the examples already (but they *see* them in the vignette, so repetition is fine).

**Comment by dankelley** [comment]
I have trimmed the hugeness reasonably well. See the final note at #862 for hints on what we might want to do if more figures get added. I have not completed the checklist, because I'm not too sure what @richardsc had in mind.

A request to Clark -- if you want to add things, please keep the size in mind. I think, if only as an exercise, we should avoid increasing the size from what it is now. So, if you add an argo figure, then I think we should remove some other figure (I vote to remove the `plotScan` figure because I think that is very specialized).  

It would be wonderful to get the content of the vignette settled this weekend so we can be on track for the pre-release countdown on Monday.

I found a few bugs while making the vignette, and I suspect we will run into others. That's why I want to get these things cleaned up as per the timetable, so that after that it is just bug fixes and then a release.

I have been uploading to win-builder periodically, and that always catches problems we don't see on local builds. We want zero NOTES on win-builder.

**Comment by dankelley** [comment]
Oh, I just read https://groups.google.com/forum/m/#!topic/knitr/Jkc9HWa4zl8 but am going offline now for the day. Possibly the retina and svg options might help. I'd hugely prefer svg because of resolution and didn't even know we could rely on that but http://blog.revolutionanalytics.com/2011/07/r-svg-graphics.html is now several years old and the message there was that browsers could work with svg. And maybe it doesn't matter if windows people cannot use svg, if rstudio works with them. I'm a bit scared on converting to svg though.

I would like to leave the next round of vignette edits (content, retina, svg) in Clark's hands, if he has time to look before tomorrow evening, which is my informal deadline for clearing things up.

**Comment by dankelley** [comment]
OK, I don't think svg is a good thing to pursue. I tried an example and it segfaulted. I found it segfaults on the below (which has an operation used in all oce axes by `resizableLabel()`).
```r
> svg('hello.svg')
> strwidth("hello", "inches")

 *** caught segfault ***
address 0x4, cause 'memory not mapped'

Traceback:
 1: strwidth("hello", "inches")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

```

**Comment by dankelley** [comment]
Also, I figured out that you need to trick `svg()` but now look at what I get when plotting the `data(section)` object! The svg file is crazy huge.
```
$ ls -lh section.png section.svg 
-rw-r--r--  1 kelley  staff    84K  6 Feb 18:40 section.png
-rw-r--r--  1 kelley  staff   1.4M  6 Feb 18:40 section.svg
```

**Comment by richardsc** [comment]
I'm going to noodle around with the vignette for awhile now. I expect you're probably done for the day, so  I shouldn't conflict. If I do anything to make it much bigger I'll just revert to the current version.

**Comment by richardsc** [comment]
I've made a few changes, but mostly just fixing up oddities and things that I found. Given the timeline and the amount of effort just put into keeping the vignette small, I think adding too many other examples (e.g. Argo) is unnecessary at this point. See the commit list for the changes I made, which were

* fix the first `mapPlot()` call to eliminate the `fill` deprecation warning
* adjust the margins on the polar stereographic plot to not chop axis labels
* fix a bunch of verbatim instances that had been demarcated with @ symbols instead of backticks

I'm going to leave this open until at least tomorrow so @dankelley can have a look.

**Comment by richardsc** [comment]
A couple more changes:

* made a proper list out of the partial summary of seawater functions, and
* added a warning about the potential for different results when using `sw*(..., eos="gsw")` vs calling the underlying `gsw` function directly (e.g. Issue #863)

**Comment by richardsc** [comment]
One thing I just noticed is that the solution for Exercise 3 isn't complete, e.g.

> Exercise 3. Draw a T-S diagram for the section data, **colour-coded by station.**

but the solution is just:
```r
library(oce)
data(section)
ctd <- as.ctd(section[["salinity"]], section[["temperature"]], section[["pressure"]])
plotTS(ctd)
```
which does no color coding.

**Comment by richardsc** [comment]
Hm. The "colour-code by station" is actually a bit tricky, and is arguably easier in the second approach given for Exercise 3, e.g.:
```r
library(oce)
data(section)
SS <- TT <- pp <- id <- NULL
n <- length(section@data$station)
i <- 1
for (stn in section@data$station) {
    SS <- c(SS, stn[["salinity"]])
    TT <- c(TT, stn[["temperature"]])
    pp <- c(pp, stn[["pressure"]])
    id <- c(id, rep(i, length(stn[["pressure"]])))
    i <- i + 1
}
cm <- colormap(id)
ctd <- as.ctd(SS, TT, pp)
plotTS(ctd, col=cm$zcol)
```
but it involves the use of the `colormap()` function, which isn't described previously in the vignette.

To color-code the plot for the first solution, I think it's going to be even trickier (but that could just be my inexperience). I'd guess that the most "elegant" way to do it would involve some `lapply()`'s, but that's going to make a nice simple example look pretty daunting to a new user ...

Perhaps we should just think about removing the "colour-code" part of the exercise? It seems to be more about accessors anyway ...

I've updated the second solution as above to include the colors, but haven't done the first one yet. I'll let @dankelley pipe in on this.

**Comment by dankelley** [comment]
Thanks for all this. I will be going through it this morning.  I'll put a few notes below.
1. I don't think `oce.html` should be in `.Rbuildignore`, because it is generated manually by using `devtools::build_vignettes()`. It was the same with the old `oce.pdf`; the idea is that vignettes get built by the developer, not by the building machine. (This is so vignettes can depend on anything the developer wants to them to depend on, e.g. private data.)
2. I've altered the section example to just use 2 colours, and to code by longitude. That is more interesting scientifically than by station.
3. I've added a Hurricane Juan exercise.
4. I will be doing a read-through of the vignette this morning and will probably make some final modifications, and then I'll post a note here.

**Important timing note.** Unless you close this or object, I plan to close this at 1PM my time.  That leaves us with #774 still open, though, which is a concern.

**Comment by richardsc** [comment]
Whoops. The color stuff I was talking about above I must have forgot to push before going to bed last night. I'll merge your version and take a look this morning.

**Comment by dankelley** [comment]
Beware -- I rewrote that section example to not use colour. I think it's better scientifically. Please be sure to pull, edit quickly, then push. If we both do that we should not have hour-long edits that will conflict.

I am right now cleaning some code-diagnostic issues that Rstudio reveals. Some are in the vignette's R code.

**Comment by richardsc** [comment]
I agree that your changes are better. Normally for big changes I prefer to use a PR -- especially if there's a chance of merge conflicts, but in retrospect the commit I forgot to push last night was < your changes to Exercise 3.

**Comment by dankelley** [comment]
I'm playing right now with `.Rbuildignore` to see what (if any) vignette files can be added there. The `devtools::build_vignette()` step puts several files into `inst/doc` but my tests are suggesting they are not all required.  (I want to chop out `inst/doc/oce.R` because RStudio spits code diagnostics on that, since `stationId` is not in scope ... I think that is erroneous because otherwise how could any subset ever work.)

**Comment by dankelley** [comment]
I'm going through the doc now. I think I will be done by noon my time.

If you're at loose ends, maybe you could think about what exactly goes in `.Rbuildignore` with regard to vignettes made from Rmarkdown.  I am confused on how to set that up.  (I'd love the package size not to be expanding by too much with this release.)

I ask because when I build, I see
```
* installing the package to build vignettes
```
which seems to suggest we should **not** be including `oce.html`, because maybe it builds it.  

But if I add `inst/doc/oce.html` to `.Rbuildignore`, then the package won't build; it dies as follows
```
Warning in file(con, "w") :
  cannot open file '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/oce/doc/index.html': No such file or directory
Error in file(con, "w") : cannot open the connection
ERROR: installing vignettes failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/oce’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/oce’
make: *** [quickoce] Error 1
```

**Comment by richardsc** [comment]
I'm really not too familiar with the package/vignette process ... Maybe it's time to ask WWHD? 

https://github.com/hadley/dplyr

**Comment by richardsc** [comment]
My understanding was that the vignette output doesn't need to be included in the git repo (i.e. put it in `.gitignore`), because it gets built when the package is built and installed. But then it shouldn't be included in the `.Rbuildignore`, because of course it's needed to properly install the package.

I'll be mostly offline again until tonight, so I can look into more then if you need.

**Comment by dankelley** [comment]
WWHD -- very funny!  PS. right now on cbc radio 1 there is a piano lesson: intriguing.

**Comment by dankelley** [comment]
I've gone through the vignette, from top to bottom. It seemed pretty disjoint to me in places.  I think it's reasonably ok now, although I suppose if you will be mentioning it in your workshop presentation (which I'd recommend, actually) then it could use one final pass (by you?) to get rid of snags. One thing to look for is author vs authors; most of this was originally written with 1 author only, so there may be remnant errors in sentences that start plural and end singular.

I also twiddle with the `.gitignore` and `.Rbuildignore` and now it passes on `Travis CI`.

**Comment by richardsc** [comment]
I took a good read through the vignette tonight, and I like where it's at. You can see the edits that I made from the commit diff at https://github.com/dankelley/oce/commit/56546e2df6981943e821d70e0e482b7ff0049893

One thing that I *didn't* change, but that jumped out at me as odd, were the following lines from the solution for Exercise 5:
```r
f <- coriolis(GS@data$station[[1]]@metadata$latitude)
g <- gravity(GS@data$station[[1]]@metadata$latitude)
```
This seemed like not the best way to extract latitude from an individual station, given that earlier in the vignette we try to highlight the utility of the accessor functions. Why not use:
```r
f <- coriolis(GS[["station"]][[1]][["latitude"]])
g <- gravity(GS[["station"]][[1]][["latitude"]])
```
Neither solution is very "pretty", but at least the second is:
1. shorter, and
2. less brittle to underlying object changes

**Comment by dankelley** [comment]
@richardsc I don't want to close this without your permission, but I also would like to stick to the plan of only starting prerelease work when the `Next Release` issues are closed.

**Comment by richardsc** [comment]
```r
latMean <- mean(GS[["latitude"]])
f <- coriolis(latMean)
```
An even better solution!

I'm happy with the vignette at this point, so I'm closing.
