### ISSUE TITLE
mapImage() not obeying projection if filledContour=TRUE

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#861]
I saw this in the example for `mapImage`, i.e.
```r
par(mfrow=c(2,1), mar=c(2, 2, 1, 1))
lonlim <- c(-70,-50)
latlim <- c(40,50)
topo <- decimate(topoWorld, by=2) # coarse to illustrate filled contours
topo <- subset(topo, latlim[1] < latitude & latitude < latlim[2])
topo <- subset(topo, lonlim[1] < longitude & longitude < lonlim[2])
mapPlot(coastlineWorld, type='l',
        longitudelim=lonlim, latitudelim=latlim,
        projection="+proj=lcc +lat_1=40 +lat_2=50 +lon_0=-60")
breaks <- seq(-5000, 1000, 500)
mapImage(topo, col=oce.colorsGebco, breaks=breaks)
mapLines(coastlineWorld)
box()
mapPlot(coastlineWorld, type='l',
        longitudelim=lonlim, latitudelim=latlim,
        projection="+proj=lcc +lat_1=40 +lat_2=50 +lon_0=-60")
mapImage(topo, filledContour=TRUE, col=oce.colorsGebco, breaks=breaks)
box()
mapLines(coastlineWorld)
```
produces as below.
![bug](https://cloud.githubusercontent.com/assets/99469/12846411/d84dfac6-cbe2-11e5-8cde-93d4103e128e.png)

**Comment by dankelley** [comment]
I think I'm too tired from working on vignettes last night and early this morning. I now no longer think this is a bug. I was somehow thinking that the outline in the bottom panel should line up with longitude, but it doesn't, and cannot, because the underlying code for filled contours is in xy space (or `par("usr")` space, not sure on the terminology).

I made an issue for this at [https://github.com/dankelley/oce-issues/blob/master/861/861a.R](https://github.com/dankelley/oce-issues/blob/master/861/861a.R) and it creates as below (with jet, to make it quantitative, although admittedly ugly). Since this seems okay, I'm closing this. Whew. I did **not** want a new real bug a few days before we set up the release branch.

![861a](https://cloud.githubusercontent.com/assets/99469/12848022/9da5625a-cbed-11e5-910f-ffb773e5bed5.png)

**Comment by richardsc** [comment]
Just piping in for completeness. Yes, I think this is complicated by the interpolation being done in XY space instead of lon/lat. I expect that for the example you have above, the rectangular filled.contour results is because the "curviness" of the original box is smaller than the actual pixel width. I think in cases where the curviness is more pronounced the filled.contour version looks more sensible, though there are other issues where it interpolates regions that never existed in the original field.

I might try to populate some examples of this which we can base future improvements on, but this is not a `nextRelease` issue.

**Comment by dankelley** [comment]
Thanks for the notes -- good to have for future reference. I'm removing the 'next release' label ... probably that should be done when closing anything so they don't come up in a label search.
