### ISSUE TITLE
read.adv.nortek() doesn't have a default `to=` argument

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#888]
I guess this was probably by design (perhaps to avoid accidentally drinking in huge amounts of data), but it's a bit count-intuitive that `to=` has to be specified to read a `.vec` file.

Should we reconsider this?

**Comment by dankelley** [comment]
I noticed that, too. I think it used to drink the whole file. The problem is that doing so can grind a machine to a halt. But maybe it *should* grind the machine to a halt, to teach the user that they need smaller data files or a bigger RAM.

I guess it could default to maybe 100 profiles, and to spit a warning, or something. I'm quite divided on this, really.

**Comment by tomvanengeland** [comment]
Hi Dan and Clark,

I see your point. Loading an entire vector file can take quite some time.

On the other hand:
I'm currently updating a package on eddy covariance measurements for publication on CRAN, and I would like to use the adv objects from oce as one possible data input to enable both Nortek and Sontek users to work with the eddy covariance package. From my point of view, it would be very convenient if the read.adv function could just read an entire file without further specification of a "to=" argument.
Also, a nice thing about oce is that you do not have to convert to text files. But in case of a vector file you do not know exactly how many observations you have until you've converted the file with Nortek software (in Windows as far as I can tell) to read the .hdr file.

Best regards,

Tom

**Comment by richardsc** [comment]
Thanks for the input @tomvanengeland ! I guess that's two votes for removing the need to specify the `to=` argument.

**Comment by dankelley** [comment]
I think it's 3 votes. Likely I'll do it soon.

**Comment by dankelley** [comment]
I created an issue in the git-issues repo, [888a.R](https://github.com/dankelley/oce-issues/blob/master/888/888a.R), but this test code won't work except for Clark and me, owing to the use of private data.  What the test suggests to me is that the `develop` branch (below) works ok on this. Perhaps Clark can test and see if it seems ok to him.  (The simplest test is just whether it got the right number of data. I think there are some text files in our private archive that tell the number of samples.)

commit ecbeece7c1936869bac27deb4db44b828aab5bcc
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Wed Mar 9 13:47:59 2016 -0400

    adv (vector) reading improved (issue 888)

**Comment by dankelley** [comment]
Oh, I see another thing to fix: the 3num for adv is stating NA values for things stored as raw. This is buried deep in code so when I fix it at the deep spot, it will work also for vector data.

**Comment by dankelley** [comment]
I just fixed this summary bug in `develop` commit e272098ad00413ad7d631f57ec0eaf3bc49661cd

**Comment by richardsc** [comment]
Great, I tested and am closing.

@tomvanengeland -- I'm interested in this eddy covariance package you mentioned -- are you doing the package development somewhere I could take a look at the functionality? I didn't see it listed under your Github account.

**Comment by tomvanengeland** [comment]
Hi Clark,

Thanks for all the efforts. Currently, we only have a recent version on 
our computer and an old version on an SVN server.
I'm not that familiar with github yet, since I only use it to follow the 
oce package development.

I just picked up this work after more than a year of silence. I was 
thinking of putting it on github from the moment we have a fully 
functional version.
At this point some functions are broken since I'm working on them, and 
the documentation lags hopelessly behind. But it would be great to here 
your ideas.
Are you working on Eddy Covariance measurements?

Do you have experience with Sontek systems? I have no idea about the 
Sontek data files and just had a look at a document from 2001. Am I 
correct if I assume that the .adr files are the actual binary autonomous 
deployment files and the .adv files from a serial connection to a pc? 
The problem that I have now is that our package uses a basename for a 
deployment and file extensions for different type of data or graphs. 
This means that our read function that uses read.oce also receives a 
basename and has to look for the proper extensions in a path.

I've also noticed that the help file from the read.adv function mentions 
an 8-bit analog 1 and a 16-bit analog 2. Since I was in doubt, I 
contacted Nortek ( in The Netherlands). They told me that the Vectors 
have two 16-bit analog inputs. It seems to me that this 8-bit assumption 
is both in the code and the help file, but I'm not sure? The code of 
read.adv.nortek shows in the assignment to analog1    size=*1* and what 
= "integer", wheres the assignment to analog2 mentions size=2.


Best regards,


Tom
