### ISSUE TITLE
read.ctd.sbe error when no pressure column in CNV file

### ISSUE THREAD

**Issue by jbg90** [dankelley/oce#903]
Hi! I am trying to use the oce package to plot my CTD results. The CTD was Sea-Bird SBE 9. I am not sure how to open the file in R to get it to run. I saw depending on the formatting of the CTD this code line should be different but none of them seem to work for me. 

plot(ctd, which=c(1,2,3,5), fill="lightgray")

I'm using the raw data output from the CTD in .cnv format.

Thanks!

**Comment by richardsc** [comment]
Hi @jbg90. Can you provide the full input/output of the commands you tried? It's not clear what you mean by "does not work for you". Did you receive an error or is the output not what you expect?

I assume that you have already read the file using a command like 

ctd <- read.oce("filename.cnv")

Oce should be able to read cnv files but occasionally we find one with a slightly different format that doesn't work.

**Comment by jbg90** [comment]
I'm getting the error:

> ctd <- read.oce("myfile.cnv")Error in read.ctd.sbe(file, processingLog = processingLog, ...) :
  object 'found.pressure' not found

Does this have to do with how my data is formatted?

On Mon, Mar 28, 2016 at 5:35 PM, Clark Richards <notifications@github.com>
wrote:

> Hi @jbg90 <https://github.com/jbg90>. Can you provide the full
> input/output of the commands you tried? It's not clear what you mean by
> "does not work for you". Did you receive an error or is the output not what
> you expect?
>
> I assume that you have already read the file using a command like
>
> ctd <- read.oce("filename.cnv")
>
> Oce should be able to read cnv files but occasionally we find one with a
> slightly different format that doesn't work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dankelley/oce/issues/903#issuecomment-202606686>
>



-- 
*Jillian Gilmartin*
PhD Student - Marine Biology - IDP
Vice President, Galveston Graduate Student Association
*Texas A&M University at Galveston*
200 Seawolf Parkway
OCSB Building, MARB Suite
Galveston, TX 77553

**Comment by richardsc** [comment]
It might be. Can you cut/paste the output of running the command

sessionInfo()

in an R terminal?

Also it might be helpful to see he cnv file you're reading. If you send an email to clark.richards@gmail.com I'll have a look. Of course I'll keep the data private.

**Comment by jbg90** [comment]
> sessionInfo()R version 3.1.0 (2014-04-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] oce_0.9-18 gsw_1.0-3

loaded via a namespace (and not attached):
 [1] grid_3.1.0      lattice_0.20-29 multcomp_1.3-7  mvtnorm_1.0-0
nlme_3.1-117    sandwich_2.3-2
 [7] splines_3.1.0   survival_2.37-7 TH.data_1.0-4   tools_3.1.0
zoo_1.7-11


On Mon, Mar 28, 2016 at 6:49 PM, Clark Richards <notifications@github.com>
wrote:

> It might be. Can you cut/paste the output of running the command
>
> sessionInfo()
>
> in an R terminal?
>
> Also it might be helpful to see he cnv file you're reading. If you send an
> email to clark.richards@gmail.com I'll have a look. Of course I'll keep
> the data private.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dankelley/oce/issues/903#issuecomment-202630694>
>



-- 
*Jillian Gilmartin*
PhD Student - Marine Biology - IDP
Vice President, Galveston Graduate Student Association
*Texas A&M University at Galveston*
200 Seawolf Parkway
OCSB Building, MARB Suite
Galveston, TX 77553

**Comment by dankelley** [comment]
I just updated the `develop` branch of oce, so that it won't have this particular error; see [1] below for how to install. I don't think this will help a whole lot because it seems as though your file must lack a pressure column, which is pretty odd.

Clark and I will probably toss this back and forth a bit to figure it out. So, it would help if you also email me your .cnv file (dan.kelley@dal.ca is a good address).  I can look Tuesday morning between 0500 and 0600, New York time.

[1] ... you can access the updated version using instructions at http://dankelley.github.io/oce/installation.html and it's easy on linux, while a bit harder in windows. As for osx, I can build up a copy and put it online for you but I'd prefer if Clark and I test this first.

**Comment by richardsc** [comment]
Ha! @dankelley and I found the issue at exactly the same time! The fix was indeed to initialize the `found.pressure` variable with a `FALSE`.

Dan does have a good point though -- your file lacks a `pressure` column. While it does have a `depth` column, it is very atypical to report *only* depth in a CTD dataset, since what the instrument actually measures is pressure, and the depth is a derived quantity. This can matter because there are different ways of calculating depth from pressure. I can tell from the parameters in the CNV that this file has undergone some processing (e.g. it has been bin averaged to depth levels of 1 meter), so I expect that whoever processed the file excluded exporting the pressure column.

Anyway, that's somewhat tangential, since your file did actually hit a real bug in how oce handles CNV files when there is no pressure column present (which is was supposed to be able to do). You will notice when you run the updated version (see below for instructions on how to install it), you'll get a warning that looks like:

```
Warning message:
In read.ctd.sbe(file, columns = columns, station = station, missing.value = missing.value,  :
  created a pressure column from the depth column
```

## Installing the updated version

I see from your `sessionInfo()` that it looks like you're on Windows. The best way to install the `develop` version is to use the devtools package, as described in the link Dan provided above, e.g.
```r
library(devtools)
install_github("dankelley/oce", ref="develop")
```
Note that for windows you need to install [Rtools from CRAN](http://cran.r-project.org/bin/windows/Rtools) before the above will work.

When/if you can confirm that the bug seems to be fixed, you can go ahead and close this issue. We like to leave it to the reporters to close issues, to make sure that the original intent has been answered to their satisfaction.

**Comment by jbg90** [comment]
I am still running into the same issue. I downloaded Rtools and devtools
and attempted to run it after opening those libraries and still nothing.

> read.oce("mydata.cnv",found.pressure=FALSE)Error in read.ctd.sbe(file, processingLog = processingLog, ...) :
  object 'found.pressure' not found


Is this how you suggested writing it out?

On Mon, Mar 28, 2016 at 8:14 PM, Clark Richards <notifications@github.com>
wrote:

> Ha! @dankelley <https://github.com/dankelley> and I found the issue at
> exactly the same time! The fix was indeed to initialize the found.pressure
> variable with a FALSE.
>
> Dan does have a good point though -- your file lacks a pressure column.
> While it does have a depth column, it is very atypical to report *only*
> depth in a CTD dataset, since what the instrument actually measures is
> pressure, and the depth is a derived quantity. This can matter because
> there are different ways of calculating depth from pressure. I can tell
> from the parameters in the CNV that this file has undergone some processing
> (e.g. it has been bin averaged to depth levels of 1 meter), so I expect
> that whoever processed the file excluded exporting the pressure column.
>
> Anyway, that's somewhat tangential, since your file did actually hit a
> real bug in how oce handles CNV files when there is no pressure column
> present (which is was supposed to be able to do). You will notice when you
> run the updated version (see below for instructions on how to install it),
> you'll get a warning that looks like:
>
> Warning message:
> In read.ctd.sbe(file, columns = columns, station = station, missing.value = missing.value,  :
>   created a pressure column from the depth column
>
> Installing the updated version
>
> I see from your sessionInfo() that it looks like you're on Windows. The
> best way to install the develop version is to use the devtools package,
> as described in the link Dan provided above, e.g.
>
> library(devtools)
> install_github("dankelley/oce", ref="develop")
>
> Note that for windows you need to install Rtools from CRAN
> <http://cran.r-project.org/bin/windows/Rtools> before the above will work.
>
> When/if you can confirm that the bug seems to be fixed, you can go ahead
> and close this issue. We like to leave it to the reporters to close issues,
> to make sure that the original intent has been answered to their
> satisfaction.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dankelley/oce/issues/903#issuecomment-202653170>
>



-- 
*Jillian Gilmartin*
PhD Student - Marine Biology - IDP
Vice President, Galveston Graduate Student Association
*Texas A&M University at Galveston*
200 Seawolf Parkway
OCSB Building, MARB Suite
Galveston, TX 77553

**Comment by jbg90** [comment]
I think I answered my own question but ran into another issue.

> found.pressure<-FALSE #Potentially do this?> read.oce("mydata.cnv")Error in read.ctd.sbe(file, processingLog = processingLog, ...) :
  no column named 'pressure', 'depth' or 'depSM'



On Mon, Mar 28, 2016 at 8:14 PM, Clark Richards <notifications@github.com>
wrote:

> Ha! @dankelley <https://github.com/dankelley> and I found the issue at
> exactly the same time! The fix was indeed to initialize the found.pressure
> variable with a FALSE.
>
> Dan does have a good point though -- your file lacks a pressure column.
> While it does have a depth column, it is very atypical to report *only*
> depth in a CTD dataset, since what the instrument actually measures is
> pressure, and the depth is a derived quantity. This can matter because
> there are different ways of calculating depth from pressure. I can tell
> from the parameters in the CNV that this file has undergone some processing
> (e.g. it has been bin averaged to depth levels of 1 meter), so I expect
> that whoever processed the file excluded exporting the pressure column.
>
> Anyway, that's somewhat tangential, since your file did actually hit a
> real bug in how oce handles CNV files when there is no pressure column
> present (which is was supposed to be able to do). You will notice when you
> run the updated version (see below for instructions on how to install it),
> you'll get a warning that looks like:
>
> Warning message:
> In read.ctd.sbe(file, columns = columns, station = station, missing.value = missing.value,  :
>   created a pressure column from the depth column
>
> Installing the updated version
>
> I see from your sessionInfo() that it looks like you're on Windows. The
> best way to install the develop version is to use the devtools package,
> as described in the link Dan provided above, e.g.
>
> library(devtools)
> install_github("dankelley/oce", ref="develop")
>
> Note that for windows you need to install Rtools from CRAN
> <http://cran.r-project.org/bin/windows/Rtools> before the above will work.
>
> When/if you can confirm that the bug seems to be fixed, you can go ahead
> and close this issue. We like to leave it to the reporters to close issues,
> to make sure that the original intent has been answered to their
> satisfaction.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dankelley/oce/issues/903#issuecomment-202653170>
>



-- 
*Jillian Gilmartin*
PhD Student - Marine Biology - IDP
Vice President, Galveston Graduate Student Association
*Texas A&M University at Galveston*
200 Seawolf Parkway
OCSB Building, MARB Suite
Galveston, TX 77553

**Comment by dankelley** [comment]
@jbg90 I'll let Clark handle this. I've got a few hundred pages of stuff to read before a meeting today (i.e. I need to skim!!)

**IMPORTANT** please use the github interface for discussing issues, or, if you want to use the email interface, please chop out the content that has already been sent AND YOUR PERSONAL INFORMATION. I edited your two comments to do that. Having the "already sent" stuff is not really a problem, but it's probably a bad idea putting personal information on a website (with identify theft, etc).  What we do in oce is to refer to people by their username, unless or until they include a personal name. Thus, Clark and I refer to each other by name. The other convention is that if you use the "@username" notation, then that person will get an email notification about the comment. By default, the reporter gets those notifications for their own issues, and Clark and I get those emails for all issues.

Your fix was a good one because it does not involve recompiling oce. (And I think you need to do that...I don't have time just now to figure out if you did.) However, there is this problem of oce having a bug demanding a pressure column ... to fix that, you'll need to get set up to build from github (instructions are on the main oce user-focussed website)

**Comment by richardsc** [comment]
To install the develop version of oce, you need to run the following (after installing Rtools.exe):
```r
install.packages('devtools') # if you didn't have it already
library(devtools)
install_github("dankelley/oce", ref="develop")
```
To assist is debugging, I suggest you cut/paste everything in the console from starting your R session to the completion of those commands. Once those commands are successful, you should be using the fixed version of oce and your pressure/depth issue will go away.

Another option is to fix the file so that it contains pressure. Do you have access to the original `.HEX` and `.CON` or `.XMLCON` files from the CTD? If so, just repeat the SBE data processing steps but make sure to include pressure in the output.

**Comment by jbg90** [comment]
It worked! For some reason the download wasn't fixing the issue on my personal laptop (it's very old........ ).

Thank you for the quick support! You helped a lot.

**Comment by richardsc** [comment]
You're welcome! Glad we got it sorted, and thanks for the the issue report! :smile:
