### ISSUE TITLE
What should argoGrid/ctdDecimate etc do with flags?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#912]
In playing around with the new `handleFlags()`, it occurred to me that currently, `argoGrid()` doesn't touch the `@metadata$flags` fields, and I don't think that it should.

Obviously the best approach would be to use `handleFlags()` *before* gridding the data, but what is the best way to communicate this to an unsuspecting user? A warning message saying that the `flags` field is being discarded? Silently throwing it away after gridding? Or keeping the original flags?

A disadvantage to the latter is that a user might try to put a gridded argo dataset through `handleFlags()`. In the default case, this would appear to work, because the gridded matrices have the exact same dimensions as the original data:
```r
> library(oce)
> data(argo)
> cat(dim(argo[['pressure']]), '\n')
56 207 
> dg <- argoGrid(argo)
> cat(dim(dg[['pressure']]), '\n')
56 207 
```
but of course the flags no longer correspond to the gridded data points.

Thoughts? I think I favour the warning message, followed by dropping the flags field from the gridded object.

**Comment by dankelley** [comment]
This is an interesting question, in general. One approach would be to set non-good flags for anything inferred from non-good data. So, for example, if we use approx() to find values at some pressure $p$ that is bracketed by $p_a$ and $p_b$, we could look at the flags at the endpoints, and do something clever. (If they are the same, then the output values get that flag; if they differ, the output value is the highest-badness of the two flags, etc.) But I think this is getting into making defaults that the user should be thinking about. So, I think I agree -- leave the flags alone.  Really, the flags apply *only* to the raw data, and not to any derived data (except by inference).

So, generally, I think flags should get dropped. Otherwise we could end up with people using derived products and thinking they have been hand-checked (or at least individually checked), which they have **not** been.

Returning to `argo`, I agree: `argoGrid` should (1) delete the flags and (2) print a warning. That warning could maybe say (let's agree on the phrasing)

```R
warning("argo data-quality flags were dropped during gridding; if you want to deal with flags, first apply 'handleFlags()' to the argo object")
```

**Comment by richardsc** [comment]
I opened this issue for the argo case because that's what I was thinking about, but really, it applies to any object that stores flags, including `ctd`. I'll change the title to be a bit more general.

I like the warning. We could either write object-specific ones (such as above) to go in at the end of the `handleFlags()` object method, or put a more general warning in the `handleFlagsInternal()` function.

**Comment by dankelley** [comment]
Shouldn't the warning be going in `argoGrid()` etc.? Another option might be for `argoGrid` to leave a notification in the `metadata`, and to have `handleFlags` check for such a thing, but that seems confusing. If I were using `argoGrid` and it spat out a message, I'd find that helpful. But I think it is a bit class-specific, and actually complicated. For `argo` we probably have agreed-upon flags, so `argoGrid` could check them and not spit a warning if all the flags are okay. But for e.g. ctd and others, there are too many flag conventions for e.g. `sectionGrid` to be able to make specific warnings.

**Comment by richardsc** [comment]
> Shouldn't the warning be going in argoGrid() etc.?

Yes, good point. This is something that should be handled by the gridding function (e.g. `argoGrid()`, `ctdDecimate()`, `sectionGrid()`, etc), not by `handleFlags`.

**Comment by richardsc** [comment]
The argo part of this is done from PR #917, but perhaps this issue should be broken up for each of the other classes that it affects (e.g. ctd and section objects for now)?

**Comment by dankelley** [comment]
I think this is ok now in `develop` commit e677b0e0dbbea91a3ae26df82e51b1c42986ff49

I used a template and reworded the text a bit, to work for any function. The info goes in a section, so people won't miss it. It could also just go in a paragraph in the details, I suppose ... I tried both ways and the 'section' scheme seemed more likely to catch the readers' eyes.

**Comment by richardsc** [comment]
This is looking good. Closing!
