### ISSUE TITLE
Calculate MLD?

### ISSUE THREAD

**Issue by CaraWilson** [dankelley/oce#940]
Hi Dan & Clark - Quick question - is there a routine in in oce to calculate MLD?  It didn't seem that way from the documentation, but it would be a useful function to have.  While there are different ways this can be done offering published methodologies, like de Boyer Monte ́gut [2004] and/or Kara [2000] would be handy.

**Comment by dankelley** [comment]
This is something I thought should go in my book instead of in oce, because it would likely get misused.  I'll send you pages from my book by private email (since I'm not allowed to publish them online).

**Comment by CaraWilson** [comment]
Thanks!  


> On Apr 26, 2016, at 9:42 AM, Dan Kelley <notifications@github.com> wrote:
> 
> This is something I thought should go in my book instead of in oce, because it would likely get misused. I'll send you pages from my book by private email (since I'm not allowed to publish them online).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/dankelley/oce/issues/940#issuecomment-214806339>


______________________________

Cara Wilson
NOAA/NMFS/SWFSC                                      
Environmental Research Division 
Southwest Fisheries Science Center 
99 Pacific Street, Suite 255A
Monterey, CA 93940

Phone:  831-648-5337
Fax:      831-648-8440
cara.wilson@noaa.gov
http://www.pfeg.noaa.gov/~cwilson

**Comment by richardsc** [comment]
Hi @CaraWilson ! I agree with Dan about whether oce should have an MLD routine or not -- I think more research oriented functionality would be better served in it's own package, that way there is more responsibility of the user to know and understand what their using.

I have coded versions of the Kara etal [2000] method for some of my work (see http://journals.ametsoc.org/doi/abs/10.1175/JPO-D-14-0238.1). I'd recommend going though their approach and coding it out, since it is relatively simple. I'd be happy to share my code, too, but it was not written for general purpose use so is a bit messy (i.e. no documentation, etc).

**Comment by dankelley** [comment]
Hi @CaraWilson 

If you think the issue (as defined by its title) has been addressed, please close it. This is a generic message the developers send to reporters when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!
