### ISSUE TITLE
read.ctd.sbe should know what conductivity unit to use for salinity calculation based on unit field

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#942]
This is coming from the same file in #941, where there is no salinity channel so it has to be calculated from C, T, p. In doing so, we get the warning:
```
2: In read.ctd.sbe("S262-023-CTD.cnv") :
  max(conductivity) > 5, so dividing by 42.914 before computing S. However, the original data are left in the object.
```

This part of the code dates from the time before we were actually reading units, but now it should be possible to just pass the `unit` string into `swSCTp(..., conductivityUnit=)` to get the correct result.

**Comment by richardsc** [comment]
I'll also point out that the test could potentially fail for certain situations. E.g. the idea is that a `S/m` unit will never be above "5", but a quick calculation says that warm water could be:
```r
> swSCTp(5.1, 30, 0, conductivityUnit = 'S/m')
[1] 30.08236
```
so this is a dangerous test, anyway.

**Comment by richardsc** [comment]
A further note, the warning says that the original conductivity is retained in the file, but a look at the `@data` slot refutes this:

```r
str(d)
  ..@ data         :List of 14
  .. ..$ depth                  : num [1:7738] -0.115 -0.112 -0.11 -0.109 -0.109 -0.108 -0.107 -0.107 -0.109 -0.112 ...
  .. ..$ conductivity           : num [1:7738] 0.000373 0.000367 0.000359 0.000355 0.000356 0.000354 0.00035 0.000342 0.000334 0.000329 ...
  .. ..$ temperature            : num [1:7738] 25.3 25.3 25.3 25.3 25.3 ...
  .. ..$ pressure               : num [1:7738] -0.116 -0.113 -0.111 -0.11 -0.11 -0.109 -0.108 -0.108 -0.11 -0.113 ...
  .. ..$ scan                   : int [1:7738] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ fluorescence           : num [1:7738] 1.75e-04 1.40e-04 9.52e-05 6.10e-05 4.30e-05 ...
  .. ..$ oxygenConcentrationMole: num [1:7738] 268 268 268 268 268 ...
  .. ..$ par                    : num [1:7738] 1282 1287 1293 1297 1301 ...
  .. ..$ v                      : num [1:7738] 2e-04 1e-04 1e-04 1e-04 0e+00 0e+00 1e-04 1e-04 0e+00 0e+00 ...
  .. ..$ v1                     : num [1:7738] 2.94 2.94 2.94 2.94 2.94 ...
  .. ..$ v2                     : num [1:7738] 3.25 3.26 3.26 3.26 3.26 ...
  .. ..$ v3                     : num [1:7738] 1.71e-07 2.84e-07 4.74e-07 7.90e-07 0.00 ...
  .. ..$ flag                   : num [1:7738] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ salinity               : num [1:7738] 0.012 0.012 0.012 0.012 0.012 ...
  .. ..- attr(*, "namesOriginal")= chr [1:13] "depSM" "c0mS/cm" "tv290C" "prdM" ...
```

**Comment by dankelley** [comment]
I think this is ok now in `develop`, commit 5e53d48de714f8835680cc6bd2af8e5be3dcac44

Since this is something we really want to get right, I hope Clark can look at the code diffs to see if he thinks I've done things right. It looks ok to me but extra eyes never hurt. All I can say is that I think the code looks ok now, and also that a `grep` on salinity in the `test.out` in our CNV directory shows the salinities are not crazy.

1. I made a git-issue test site, which uses **private** data. Seems ok to me. **NOTE** I changed the warnings that get spat out, re the `conductivity` item. I wonder if you can see if that seems ok now, Clark? I don't quite understand your comment (https://github.com/dankelley/oce/issues/942#issuecomment-215829690) because the conductivities stored in oce are the same as in the file. We should **not** close until this is clear, I think.
2. our `Dropbox/oce-working-notes/CNV` test suite passes cleanly now. But it would help a lot if Clark could skim quickly over its output to see that things look ok in summary form.
3. I changed the auto-division to get cond-ratio to key on a max value > 10, instead of 5. But we now recognize the cond unit so this should not come up often.
4. I altered the warning messages that occur with conversions, so the wording is almost the same in each (and, I hope, clearer)
5. I altered the method used by `lookWithin()` (in `R/sw.R`) to try to make it better auto-detect odd units. I am not entirely sure this will always work, and I wonder whether Clark can have a look at the diffs over the past 2 days to see what I've done. I now have things boiling down to how the `[[` accessor works. That *should* make things a lot less brittle to change.
6. A final note: I was quite amazed to see a pressure in PSI in one of our `CNV` files. I guess that proves I shouldn't have decided to ignore those whacky English units, but I still will resist coding in 30 variants of Fahrenheit temperatures, until a user really needs them.

Lots of stuff here. Since we don't have threaded comments in GH, maybe Clark can use the `>` mechanism to comment within the above list. (He could maybe send an email to me noting the update, since GH won't email for internal changes to comments.)

Sorry for the nearly-week delay.  It was only a dozen lines of code but I needed uninterrupted time to look since this stuff is subtle and wide-ranging.

**Comment by richardsc** [comment]
My tests and a code review indicate that this should work as stated. If it doesn't we can re-open or create a new issue.
