### ISSUE TITLE
Add option to sort sections by time with sectionSort()?

### ISSUE THREAD

**Issue by mhalvers** [dankelley/oce#950]
Hi Dan and Clark -

In the spirit of having plot.section() handling time/depth slices, can sectionSort() be modified to handle sorting by time?

Mark

**Comment by richardsc** [comment]
Hi Mark,

Great suggestion! Definitely seems sensible and do-able. I'm going to assign it to myself, but likely won't be able to look at it until at least tonight.

If @dankelley thinks he has time today, feel free to re-assign it to yourself and go for it.

**Comment by richardsc** [comment]
Sounds good. I'll have a go at it later.

**Comment by mhalvers** [comment]
Thanks.  I had a list of ctd objects which I knew were not sorted according to time, yet 
`plot.section(...,xtype="time")` was plotting correctly.  It made me whether `plot.section()` was calling `sectionSort`, but then I noticed doesn't support sorting by time.

**Comment by richardsc** [comment]
>  I had a list of ctd objects which I knew were not sorted according to time, yet 
plot.section(...,xtype="time") was plotting correctly.

Hm. Are you sure about this? My tests so far suggest that if the stations are not ordered in time that `plot.section()` doesn't actually work properly ...

**Comment by richardsc** [comment]
Ok, it does looks like `plot,section-method` does an order of the `x` variable before plotting:
```r
                      ## Put x in order, if it's not already
                      ox <- order(xx)
                      xxOrig <- xx
                      if (any(xx[ox] != xx)) {
                          xx <- xx[ox]
                          zz <- zz[ox,] ## FIXME keep this???
                          ##warning("plot.section() reordered the stations to make x monotonic")
                          bottom.x <- c(min(xxOrig), xxOrig[ox], max(xxOrig))
                          bottom.y <- c(graph.bottom, -waterDepth[ox], graph.bottom)
                      }
```

**Comment by richardsc** [comment]
Implemented in PR #951. Waiting for approval from @dankelley , at which point @mhalvers you can build from source and let me know if it looks ok.

**Comment by mhalvers** [comment]
By the way the reason I was hoping `sectionSort` had a time argument is because I was trying to extract a time series of temperature at a particular depth from a list of ctd objects.  I wondered if using `as.section` and `ctdDecimate` would be the easy way to do this.  I could then plot the time series by slicing the section with something like `myCTDSection[["temperature"]][[depth=15,]]'.  Is a section object the right approach or should I just extract the temperature from each object and place it into a data frame?

**Comment by richardsc** [comment]
Well, I think adding the `time` option to `sectionSort()` makes sense, as the `xtype='time'` option for the plot method was only added recently (and it is doing that sort manually, which is not DRY), so it's a nice general addition.

As for your use case, I'm not seeing a simple way of accessing a time series at a given depth in the way you're thinking. Remember that section objects are still just lists of CTD objects (even when gridded), so you can't reference it like you would a matrix.

One option would be to use `lapply()`, something like:
```r
library(oce)
data(section)
s <- sectionGrid(section, p=seq(0, 1000, 10))
T100 <- unlist(lapply(s[['station']], function(x) x[['temperature']][x[['pressure']]==100]))
oce.plot.ts(s[['date']], T100) # note that the times aren't sorted as this issue addresses
```
![screen shot 2016-05-02 at 12 26 47 am](https://cloud.githubusercontent.com/assets/233584/14947158/971ff726-0ffc-11e6-8c7f-b6c4e44fb2a7.png)

Another approach would be to write a function that puts the gridded section object into a matrix, which you can then access with indices. Coincidentally I wrote a blog post earlier in the week about how to do this (but in the context of having more control over plotting):

http://clarkrichards.org/r/oce/section/ctd/2016/04/25/making-section-plots/

**Comment by dankelley** [comment]
You guys have been busy. I'll try to touch on the points, starting with the most relevant.

1. Mark: I agree with Clark that the best method for your actual problem is to ignore contouring and work directly with the data by extracting information from the individual profiles and assembling them as you see fit. That way you have control over the methodology, e.g. if you want to smooth in time, that's easy, if you want to smooth across nearby depths, again easy.  It also lets you do clever things like look at time variability of some signal ("S" say) along an isopycnal, as opposed to along a pressure surface (which can be good to get rid of heaving effects on some space-time scales).  It's also easy to describe in a paper. I would never use gridding for such a task as the one I think you must have in mind. I don't like having an extra step between me and my data.

2. Clark and Mark: yes, contouring orders in whatever is on the horizontal axis. This is a standard aspect of contouring (or image plots), because otherwise you'd be drawing scribbles back over the page. I suppose a person might want a diagram like that sometimes but it's not possible with typical contouring codes.  (This is a bit like the advantage of drawing points on scattergrams, instead of connecting lines ... but with the extra dimension the lines get even more "scribbly".)

3. Clark, your patch for `sectionSort` looks good.  I just incorporated it into `develop` and it builds+tests fine on my box. Thanks for that!

Mark, if you feel that this issue has been sorted, please close it. In the oce community, we ask reporters to close issues ... the developers only do that if the issue has been addressed and discussion has gone silent for a week or so after asking the reporter to assess progress.

**Comment by mhalvers** [comment]
Just built oce successfully this morning, and `sectionSort` arranges by time.  Clark, I will check out your blog post for help.  Eventually I knew I'd need to extract data from oce objects so I could do some analysis, but my `sectionSort` idea was just an attempt at a quick and dirty plot.  Thanks!
