### ISSUE TITLE
date range in margin using oce.plot.ts() ?

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#953]
What should the date range be in the margin of time series plots? Currently its the range on the axes, but perhaps the range of the data is more suitable, and might be less misleading when showing the plot to someone else?

Another alternative is to remove the margin range and have the x-axis be more descriptive? My personal preference is to have the months labeled ( as done now) , and a second x-axis with the year.

**Comment by dankelley** [comment]
I think we've gone back and forth on this, actually. The point is to avoid mystery plots, where e.g. it says "4:00" to "12:00" or whatever, without saying what day it is, or the year.  I wonder whether the best scheme might be not to show a range at all, but rather some kind of central time. For example, if the time range is over an hour and under a day, maybe list the day at the top. Or, if over a month and under a year, list the year. I think over a year requires nothing because e.g. "1999" clearly is a year and not a time, because there is no ":" in it.

Any thoughts on this, @richardsc?

**Comment by richardsc** [comment]
Personally, I quite like the default behaviour, because it allows for a quick plot that is completely unambiguous about the time axis. It can be redundant, depending on how the auto-formatting gets done, but in such cases it's easy to ignore.

When I'm ready to make publication quality plots, I will typically make use of
```r
options(oceDrawTimeRange=FALSE)
```
and then customize the time axis myself using the `format=` argument.

I like the two-line axis idea @clayton33, but I see that as more of a "personal" add-on that would be a fun little coding project, since it might be hard to make it as general as would be desired for `oce.plot.ts()`. This thread would be a good place to explore such a function, even if it doesn't go into oce.

On a related note @clayton33, do you use a "personal" package for organizing functions that you like to use? I found this extremely helpful when I was doing my thesis work, and continue to use various things that I've cooked up over the years.

**Comment by dankelley** [comment]
@clayton33 one approach is illustrated in the snapshot, i.e. use `xaxs="i"`. Seem an ok solution?

![screen shot 2016-05-02 at 12 31 14 pm](https://cloud.githubusercontent.com/assets/99469/14958591/df8f4376-1061-11e6-80c8-2b7b43dc6c1b.png)

**Comment by richardsc** [comment]
Oooohhhh ... I guess I mis-understood the discussion. This is about the "default" behaviour where the axis limits get expanded a little bit so the data don't run right into the edge.

Yes, in such cases if I want different behaviour I do as @dankelley showed above with the `xaxs="i"`. Often that is necessary when lining up multiple panels, e.g. where one is an `imagep()` with time axis.

**Comment by dankelley** [comment]
Another option: `drawTimeRange=TRUE` and `FALSE` could be as now, but `drawTimeRange="axis"` could be as `TRUE` now, while I could add `="data"` could be what @clayton33 wants.

This seems to me to be a good solution and I could code it if someone gave me a happy face or a 'hooray' icon in this comment 😺

**Comment by richardsc** [comment]
Genius. 👍

**Comment by dankelley** [comment]
Hm, well, maybe genius but hard to code. This is because the time range gets drawn by `oce.axis.POSIXct()`, which in turn calls the deep R function `axis()`.  But `axis()` doesn't know anything about the data; it only knows about `par("usr")` that exists. Now, I *could* move the drawing up a level, from `oce.axis.POSIXct()` to `oce.plot.ts()` but then we would lose the fact that the time range can be shown also for `imagep` (and probably other types of) plots. So what I thought would be a few-line fix in `oce.axis.POSIXct()` will turn into (a) a lot of code changes and (b) user-interface changes.  The latter is not good, I think.  Therefore I am dropping this idea of a string-based value for `drawTimeRange`.

PS. of course, I coded half of this in, before realizing this need to leap-frog information between functions. I'm just going to delete the half-baked code without checking it in.

**Comment by dankelley** [comment]
@clayton33 -- below is a generic response we use in oce...

If you think the issue (as defined by its title) has been addressed, please close it. This is a generic message the developers send to reporters when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by dankelley** [comment]
The discussion of this issue seems to have ended, and the developers will likely close it soon, since it seems to have been addressed. This goes against the usual oce policy of hoping that reporters will close issues, so this is really a request to the original reporter to either (a) close the issue or (b) indicate that further action is desirable.
