### ISSUE TITLE
numbering of multiple channels not consistent with past scheme

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#958]
I think I might have touched on this tangentially somewhere else in the mess of the recent `cnv`-related issues, but I'm not sure I like the new scheme of using `_N` to distinguish multiple channels with the same name, e.g: `temperature_2` vs the old `temperature2`.

I guess part of this was related to the `temperature68` issue, which I think we've resolved by *not* numbering it, but rather using the proper `units` field to describe the scale.

In any case, I'd like to discuss the merits of the "underscore" numbering vs the old way. One argument I would make for the old way is that it is consistent with old code (of which I have a fair bit).

**Comment by dankelley** [comment]
I don't have much time, just at this time of day, but this seems simple: I think we should use e.g. `foo2` and not `foo_2`, so we are in agreement. I think that slid in with the underline by accident, almost. I was surprised when I saw it!  Too much editing, too many branches. But I am now very, very keen to get the original data names in as many objects as we can, and that means a lot of rewriting.

**Comment by dankelley** [comment]
I've changed this in `develop` commit f9f121fa774878000dc4c84d602495a50f6b0110 and also put the function that does renaming in `NAMESPACE`.

PS. the purist might say there could be contradictions e.g. `landsat` has data items that end in numbers, and so do `lisst` objects, but I don't see that as a huge problem. Besides, who knows, we could use `_2` etc and then a month from now there would be someone with a data file that had names like that.  Really, there is no scheme that will always work because in R, anything can be a name, e.g. the whacky example
```R
> assign(" ", 10)
> get(" ")
[1] 10
```
