### ISSUE TITLE
ctdDecimate should remove the `scan` field from the data slot

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#960]
Just noticed that after doing a `ctdDecimate()` the `scan` field is left as empty:
```r
library(oce)
data(ctd)
d <- ctdDecimate(ctd, p=1)
str(d)
```
```
  ..@ data         :List of 7
  .. ..$ scan       : logi(0) 
  .. ..$ time       : num [1:45] NA 129 131 135 140 ...
  .. ..$ pressure   : num [1:45] 0 1 2 3 4 5 6 7 8 9 ...
  .. ..$ depth      : num [1:45] NA 1.47 1.97 2.97 4.02 ...
  .. ..$ temperature: num [1:45] NA 14.2 14.2 14.2 14.1 ...
  .. ..$ salinity   : num [1:45] NA 29.9 29.9 29.9 30 ...
  .. ..$ flag       : logi(0) 
```

This seems sensible, as a "binned/decimated" scan is meaningless (as for flags), but leaving that field as an "empty" causes problems with other functions. E.g. `plotScan()` won't work if `scan` is empty (though admittedly using `plotScan` on a `ctdDecimate`ed object is a bit weird). Another issue, and the one that caused me to notice this was that I have a script that exports the `@data` slot from a `ctd` object to a csv file by first converting it to a data frame, e.g.:
```r
df <- data.frame(ctd@data)
```
but this also fails, because the fields don't have the same number of rows.

I propose just removing `scan` (and `@data$flags`?) from the decimated object.

**Comment by richardsc** [comment]
See PR #961 for a very simple fix to this -- basically, just check for the presence of a `scan` or `flags` field in the new object data, and remove it if it's there (with a warning). Maybe the warning isn't needed

**Comment by dankelley** [comment]
I'm gong to reject the patch. I've seen DFO files (e.g. some that CL is working with in her thesis) that have been bin-averaged by some DFO software (or maybe SBE software), and that have scan numbers still present. It confused the heck out of me, to see the scan be 1 for one level, then 10 for another, then 30 for another (non-uniform sinking rate). So I think oce should do similar, averaging the scan. I can look how to make oce do this, if you'd like to reassign this one to me, otherwise maybe you could try?

**Comment by richardsc** [comment]
Fair enough -- re-assigned!

**Comment by dankelley** [comment]
Should be ok now in `develop` commit f53aa48e074a523712d5e2165b54ec1893bd666a
