### ISSUE TITLE
read.rsk not parsing units for "non-standard" channels

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#976]
Just noticed from one of the RSK test files, which was a CTD with a turbidity sensor, that `read.rsk()` isn't parsing units for turbidity, even though it is actually contained in the sqlite db.
```
==================================================================================================== 
== i:6, file: /Users/richardsc/Dropbox/oce-working-notes/rsk/065584_20140816_1633.rsk
==================================================================================================== 
rsk summary
-----------
* Instrument:         model RBRconcerto serial number 65584
* Atmosph. pressure:  10.1325
* Pressure type:      absolute
* Source:             ``/Users/richardsc/Dropbox/oce-working-notes/rsk/065584_20140816_1633.rsk``
* Time ranges from 2014-08-16 11:08:00 to 2014-08-16 16:01:06 with 26179 samples and mean step 0.6717918 s
* Statistics of data
                              Min.                Mean                Max.                Dim.  OriginalName
     time                     2014-08-16 07:08:00 2014-08-16 09:50:23 2014-08-16 12:01:06 26179 -           
     conductivity [mS/cm]     -0.0087453          29.286              33.126              26179 -           
     temperature [°C, ITS-90] 0.30147             2.3162              7.352               26179 -           
     pressure [dbar]          9.8223              133.68              310.11              26179 -           
     turbidity                0.22164             0.69047             491.67              26179 -           
```

Since we now have a `units` metadata field, and we parse units for cnv files, it makes sense to try and do it here. One issue I foresee could be non-ascii characters in the units.

I'll try and find some example files, from instruments with lots of extra sensors, to test this idea out. I don't believe this is a submission stopper issue.

**Comment by dankelley** [comment]
I've done some work on this and think it's ok. I also altered how `rsk2ctd` works, with respect to pressure, so that things will make more sense to users. (For example, the unit has a `scale` that can be `"sea"` or `"absolute"` now.)

To avoid making public a suite of test files that are possibly better considered private, the test suite item that I made uses `~/Dropbox/` in a way that will probably only work for Clark and me.  Clark, can you do `make` in to that issue subdir and examine the output carefully? Please pay attention particularly to units and original-names. I had these tangled in my first (un-pushed) version of the solution to this.

I think things are ok now in `develop` commit b84b7fffa5182b989470278704a9f1fbccf0ce16 but leave it up to Clark to check, and possibly close this.

Naturally, I'd be interested in learning of new units, in addition to the ones I've built in so far.  It's very easy to add new units, and to save time, Clark, it would be great if you could code them in. (Look in `R/rsk.R`, function `unitFromStringRsk()`.)

PS. FYI, the pressure unit in `.rsk` files is sometimes `dbar` and other times `dBar`.

**Comment by richardsc** [comment]
I added another file to the Dropbox dir -- one that has some other units (% for oxygen, ug/l for chla, and pH_units for pH). The 976 issue dir seems to work fine, and even though it gives warnings about unknown units `read.rsk()` seems to do sensible things:
```
> d <- read.oce('080284_20151023_1221.rsk')
Warning messages:
1: In unitFromStringRsk(unitsRsk[iname]) :
  '%' is not in the list of known .rsk units
2: In unitFromStringRsk(unitsRsk[iname]) :
  'µg/l' is not in the list of known .rsk units
3: In unitFromStringRsk(unitsRsk[iname]) :
  'pH_units' is not in the list of known .rsk units
> summary(d)
rsk summary
-----------
* Instrument:         model RBRmaestro serial number 80284
* Atmosph. pressure:  10.1325
* Pressure type:      absolute
* Source:             ``080284_20151023_1221.rsk``
* Time ranges from 2015-10-23 08:50:10 to 2015-10-23 09:03:54 with 9900 samples and mean step 0.08333337 s
* Statistics of data
                               Min.                Mean               
     time                      2015-10-23 04:50:10 2015-10-23 04:57:02
     conductivity [mS/cm]      0.14162             0.14871            
     temperature [°, ITS-90]   18.682              19.084             
     pressure [dbar, absolute] 9.1331              11.853             
     oxygen [%]                91.207              97.656             
     chlorophylla [µg/l]       215.3               215.38             
     ph [pH_units]             8.6677              8.751              
     temperature2 [°, ITS-90]  20.087              20.369             
                               Max.                Dim. OriginalName
     time                      2015-10-23 05:03:54 9900 -           
     conductivity [mS/cm]      0.1569              9900 cond06      
     temperature [°, ITS-90]   20.494              9900 temp09      
     pressure [dbar, absolute] 13.027              9900 pres19      
     oxygen [%]                102.2               9900 doxy07      
     chlorophylla [µg/l]       215.39              9900 fluo10      
     ph [pH_units]             9.0096              9900 ph__02      
     temperature2 [°, ITS-90]  20.661              9900 temp10      
```

I'll look at it some more, and possibly add the units so they are recognized. Also, I'd like to find other files that have common sensor units so they can be added. Another approach would be to just get the full list of "channel types" and units from the Ruskin developer and code them all in.

**Comment by dankelley** [comment]
1. I added the units you mentioned (`develop` branch commit a325d156510a525f1901101017deeb75658cd61d).

2. I notice that two files give the below, with the exact same pressure value. Do you think we should warn on this sort of thing?  I don't think so anymore. See `R/rsk.R` line 797.
```R
# rsk[2] = /Users/kelley/Dropbox/oce-working-notes/rsk/050046_20111007_1413.rsk
Warning in read.rsk(rsks[i]) :
  non-standard pressureAtmospheric value: 10.1324996948242
```

3. Yes, I think it would be good to get a full list, especially if that is something we could get quickly for this release. Since it makes somewhat-reasonable guesses when the unit is unknown, I don't see this as a cran-stopper.  Still, in general, I really do prefer to catch all units and formulate them in a standard way. For example, some rsk files in this test set use `"dbar"` and others use `"dBar"` and I don't like that because we might later want to have tests on whether it is `"dbar"`.

4. Any more rsk-related that might impinge upon a cran release? We probably only have a few days left, since acceptance might take 5 or more days.

**Comment by dankelley** [comment]
In `develop`, I corrected an error (degC, not deg) and also now using `debug=99` (as in the test suite) will produce info on the conversion.

**Comment by dankelley** [comment]
Any status update on this?

**Comment by richardsc** [comment]
Thanks for the reminder. Looks good now!
