### ISSUE TITLE
plotProfile leaves non-default par settings

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#986]
I feel like we've discussed this before, but I couldn't find an issue related to it so here we go.

Most `oce` generic plot functions reset `par()` settings after they are done plotting -- e.g. if you do:
```r
library(oce)
data(ctd)
plot(ctd)
plot(rnorm(100))
```
the `mfrow`/`mar` etc get reset after the `plot.ctd()` call so that any further plots use the par settings that were in effect *before* `plot.ctd()` was called. In general, I think this is good behaviour because it allows for quick summary plots of object while doing other work without have to constantly redefine par settings.

However, `plotProfile()` *doesn't* do this -- i.e. it leaves the par settings from the `plotProfile()` internals in effect, so that further plots to the device have funny margins. Example:
```r
plotProfile(ctd, 'salinity')
plot(rnorm(1000))
```
cuts off the bottom axis on the second plot:
<img width="812" alt="screen shot 2016-06-14 at 13 42 18" src="https://cloud.githubusercontent.com/assets/233584/16053222/dee814f2-3235-11e6-9eb4-99125e2aceae.png">

I'd like it if `plotProfile()` returned the axis settings as `plot.ctd()` does, please :).

**Comment by dankelley** [comment]
will do, thanks!

**Comment by dankelley** [comment]
This is trickier than I thought it would be. If we go back to the `par('mar')` as before the call, then e.g. `lines()` and `points()` will not work properly.  To see this, contrast 

**works nicely**
```R
test <- TRUE
plot.new()
opar<-par(no.readonly=TRUE)
par(mar=c(2,3,2,2))
plot(1:5,1:5)
grid()
if (test) par(opar)
abline(v=3,col=3)
```
for `TEST` being `TRUE` (bad result: cannot overdraw later) and `FALSE` (good result: can overdraw later).

The issue, really, is that oceanographers need space on the top to draw "proper" profiles.  And I really think they *are* proper, the way we draw them. Now, we could of course relax the bottom-spacing a bit. I basically hate the R system of having tons of extra space. However, below looks reasonably OK, and it doesn't affect the margins.
```R
library(oce)
orig <- par('mar')
data(ctd)
plotProfile(ctd, mar=mar)
```
But I need Clark's opinion on this, I think. I see two options.

1. We *could* make it so that `plotProfile` simply does not mess with mar at all, i.e. that the default would be `par("mar")`, and that in the docs we suggest how to get tighter. But that would change the geometry of a lot of existing plots. Therefore, I propose ...
2. We keep as it is, but we say in the docs that setting `mar=par("mar")` is the way to prevent it from messing up.

Clark, your thoughts?

**Comment by richardsc** [comment]
Good point about the effect on `lines()` and `points()`. That isn't something I've encountered, because if I'm over-plotting I do it by calling `plotProfile()` again using the `add=TRUE` argument, e.g.
```r
plotProfile(ctd, xtype='temperature')
plotProfile(ctd, xtype='temperature2', add=TRUE)
```

In thinking about it more, I think your number 2 is probably the better approach. In looking back through some of my code I noticed that I've taken the:
```r
opar <- par(no.readonly=TRUE)
plotProfile(ctd)
par(opar)
plot(rnorm(1000))
```
approach of just saving and then re-setting par. Sorry for the noise!

**Comment by dankelley** [comment]
I altered the docs in `develop` commit 27d42f9775b0431ab5664b0422bb10acc664b0f4, and I think this fixes this issue. Clark, maybe you can check the doc (mainly the `mar` part although I also fixed some escaped-quote typos for another argument) and consider closing this.

**Comment by richardsc** [comment]
Looks good to me. Thanks!
