### ISSUE TITLE
fillGap() should have an option to extrapolate at ends

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#994]
This came up because of #987 when I started doing some stringent tests of identity of captured profiles. The first one comes out wrong, for smoothing using `stats::filter`, because of `NA`s that get inserted at the ends, which become constants as I am filling the gaps presently. I do have another way to handle #987 though, so these two issues are not intimately linked.

**Comment by richardsc** [comment]
I think that this is probably useful, regardless of the requirements of #987. I have many times written code to just lop off beginning and trailing NAs, thereby ignoring other data associated with those indices.

It could also be more general, rather than just linear extrapolation (but have linear be the default). Much like `ctdFindProfiles()`, the user could specify a function to do the extrapolation (e.g. quadratic? spline? an AR(N) process?), as well as the number of points with with to do the fit.

**Comment by dankelley** [comment]
+1 on idea of user-supplied function. We should have more such things in oce ... something to bear in mind. I think only #987 is a serious issue regarding a new release, and I'm pretty sure it's ok (enough) now.

**Comment by dankelley** [comment]
Closing, per discussion of CR and DK today.
