### ISSUE TITLE
Remove `adorn` arg from plot.section

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#995]
I'd like to overlay contours of a field on a section plot, but it's not clear to me how to do that in a way that doesn't mess up margins. `plot.section()` doesn't have an `add=TRUE` argument, so that doesn't work. Note that the docs say:

I feel like there's probably a way to do this with the `adorn=` argument, but there aren't any examples (despite the help page indicating that there should be) so I'm a bit lost, as is @porterdf.

Non-working example, to illustrate what I tried first:
```r
library(oce)
data(section)
plot(section, which='temperature', ztype='image')
plot(section, which='temperature', ztype='contour', add=TRUE)
```
```
Error in contour.default(x = xx[xx.unique], y = yy[yy.unique], z = zz[xx.unique,  : 
  formal argument "add" matched by multiple actual arguments
```

**Comment by dankelley** [comment]
The `adorn` argument is presently being ignored.  I can make that work, but the present (very helpful!) request is to do something fairly sophisticated, which `adorn` was not intended to do. In fact, I feel that the `adorn` argument should be **removed** since it is not presently being followed, and since there are better ways to do this.

History can help in explaining this. The `which` argument to `plot,section-method` can be a vector with more than one value, and the result is a plot with multiple panels. This is accomplished by the plot method using `par(mfrow)`, etc.  I did that for reasons that I now think are silly. It is actually *simpler* for the user to set up function calls for the panels, and that means that `adorn` serves no purpose. Only in the very simplest of cases (maybe drawing a line at a certain depth) would it even make sense to write e.g.
```R
plot(section, which="temperature", adorn={abline(h=1000)})
```
because you can see that the braced block is going to be a crazy mess if we need to put more code there. The only way to read it would be to extend that code over several lines. But it's a lot simpler for the user to just write
```R
plot(section, which="temperature")
abline(h=1000)
```
which is the more "R-ish" notation.

So, that's my argument to not try to make `adorn` work again. What do you think, @richardsc?  Not that it's a game-changer, but another factor is that we are in the hours-left countdown to a CRAN submission, and I do not want to mess with the code without adding a week to the schedule. Deleting an unused argument is very easy to do without ripple effects, but writing code to pass that argument around is slightly trickier. I can try the latter, though ... I want your opinion on whether I should.

Also, @porterdf, please note that what you want to do is certainly feasible, because all the information in `oce` objects is accessible. It's a matter of writing code to extract that information and then doing whatever needs to be done (contours, etc). Clark and I can help with that.  I'd be happy to send some code, but first I'm hoping to get clearance from @richardsc to delete the `adorn` argument.

**Comment by richardsc** [comment]
Clearance granted. Go ahead and delete `adorn`. Maybe that explains why I never used it, because I felt like I could never get it to work.

**Comment by dankelley** [comment]
Sorry to be going back and forth on this, but I see that we have the `adorn` method in the following.  And I am pretty sure you and I have used on e.g. multiple-panel `adp` plots, so I am now thinking that `adorn` is worth an hour of code attempts. Therefore, I plan to look more carefully at this today. If I can see how to make `adorn` work, and if I can convince myself that the code edits are small enough, then we could still submit soon. I do like advertising our country, though, so I like SJBD or CD ... the latter now seems the right decision. Your thoughts, @richardsc?
* [ ] oce.plot.ts
* [ ] plot,adp-method
* [ ] plot,adv-method
* [ ] plot,argo-method
* [ ] plot,cm-method
* [ ] plot,ctd-method
* [ ] plot,echosounder-method
* [ ] plot,lobo-method
* [ ] plot,rsk-method
* [ ] plot,sealevel-method

**Comment by richardsc** [comment]
Ok, worth a code-review and attempt. But I can tell you that if I've used `adorn` on a plot, it hasn't been in the last 4 years. Granted, that's not necessarily an argument for *getting rid* of it from all the functions you list above, but maybe an argument against *adding* it to the section method.

I don't know what you mean by "SJBD or CD" ... 😕 

In the context of the present issue (overplotting on an image section plot), I would think the better argument to add would be an `add=TRUE`, similarly to e.g. `plot.ctd()`, `plotProfile()`, `oceContour()`, etc.

**Comment by dankelley** [comment]
SJBD=St Jean Baptiste Day; CD=Canada Day.

In looking at the code, it's a bit too messy to fix quickly. However, simple deletion of the arg is easy, so will do in next 10 min, at which point I'll post here again with the commit code.

**Comment by richardsc** [comment]
Great. I'm going to tidy the issue titles up, and make a new one for my suggested addition above (adding the `add=TRUE` arg to plot.section).

**Comment by dankelley** [comment]
Done in `develop` (see below). I'll be offline a few hours now.

commit 4e754bb5889ac9e2655b693835213cbf33b75117
Author: Dan Kelley <kelley.dan@gmail.com>
Date:   Thu Jun 23 15:37:36 2016 -0300

    plot,section-method drops argument 'adorn'

**Comment by dankelley** [comment]
See #997 for some notes on this, looking more broadly. I've decided *not* to remove it from `plot,section-method`, but rather to get it working (which it is, in `kelley`) and test it, and then to deprecate it.

**Comment by dankelley** [comment]
Basically handled along with #997, so closing this one now, too.

**Comment by dankelley** [comment]
Sorry, Clark -- I thought I had opened it ... still, I reckon you can reopen this if you want!
